Sudoku
HarshCasper/NeoAlgo pull request #1005
Opened 2020-09-13 15:03 UTC by ishi0301

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description
Soduku Solver
(Write your answer here.)

### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#976

2020-09-13 15:04 UTC, ishi0301 commented
@HarshCasper @Abhijit2505 @SKAUL05 @iamrajiv Please review my code.

2020-09-26 14:09 UTC, ishi0301 commented
Kindly review @iamrajiv @HarshCasper @siddharth25pandey @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99  .

2020-09-26 14:29 UTC, siddharth25pandey commented
@ishi0301 Please remove the unnecessary css & html file

2020-09-26 14:48 UTC, ishi0301 commented
Removed unnecessary files. Please approve. @iamrajiv @HarshCasper @siddharth25pandey @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99.

2020-09-26 14:55 UTC, siddharth25pandey requested changes
@ishi0301 Please do the suggested changes
Thanks!

2020-09-26 14:55 UTC, siddharth25pandey commented on C-Plus-Plus/other/sudoku_solver.cpp
> +#include <cmath>
Add single header file **bits/stdc++.h**

2020-09-26 14:55 UTC, siddharth25pandey commented on C-Plus-Plus/other/sudoku_solver.cpp
> +	int mat[9][9] =
Take Dynamic Input from the user

2020-09-26 14:55 UTC, siddharth25pandey commented on C-Plus-Plus/other/sudoku_solver.cpp
> +bool isSafeToPut(int mat[][9],int i,int j,int n,int number){
Don't fix any number of rows/columns

2020-09-26 14:55 UTC, siddharth25pandey commented on C-Plus-Plus/other/sudoku_solver.cpp
> +bool SudokuSolver(int mat[][9],int i,int j,int n){
Don't fix any number of rows/columns

2020-09-26 14:55 UTC, siddharth25pandey commented on C-Plus-Plus/other/sudoku_solver.cpp
> +	int mat[9][9] =
take rows & columns by user's input.

2020-09-26 15:28 UTC, ishi0301 commented
Made necessary changes. Please approve. @iamrajiv @HarshCasper @siddharth25pandey @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99.

2020-09-26 15:37 UTC, siddharth25pandey requested changes
@ishi0301 Don't directly fix the size of the grid.
What happen if user enter a square grid which is greater than 10, let's say 15*15.
Therefore, please change it.

2020-09-26 15:37 UTC, siddharth25pandey commented on C-Plus-Plus/other/sudoku_solver.cpp
> +    int mat[10][10];
Don't fix the size of the grid

2020-09-27 07:17 UTC, ishi0301 commented
@siddharth25pandey please check now and approve it. @iamrajiv @HarshCasper  @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99.

2020-09-27 08:49 UTC, siddharth25pandey approved these changes
@ishi0301 Good to go
Able to merge
Thanks!

2020-09-27 10:28 UTC, iamrajiv approved these changes

2020-09-27 10:28 UTC, merged