Unique no 3
HarshCasper/NeoAlgo pull request #1006
Opened 2020-09-13 15:13 UTC by ishi0301

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description
Unique_no_3

### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#988

2020-09-13 15:14 UTC, ishi0301 commented
@HarshCasper @iamrajiv @Abhijit2505 @SKAUL05 Please review my code.

2020-09-13 17:46 UTC, iamrajiv requested changes
@ishi0301 Update the program name as `Unique_Number_III.cpp`. I think you have used Bitmasking so you can add this concept in code comments.

2020-09-13 17:46 UTC, iamrajiv commented on C-Plus-Plus/other/Unque_no_3.cpp
> +//UNIQUE NUMBER III
@ishi0301 Update all single-line comments in one multiline comment. Something like this
```
/* 
...
*/
```

2020-09-13 17:46 UTC, iamrajiv commented on C-Plus-Plus/other/Unque_no_3.cpp
> +
@ishi0301 Add sample input-output

2020-09-15 13:58 UTC, ishi0301 commented
Made requested changes . Kindly review. @iamrajiv @SKAUL05 @Abhijit2505 @Kajol-Kumari @HarshCasper @atarax665

2020-09-15 13:59 UTC, iamrajiv commented
@ishi0301 Resolve the merge conflicts.

2020-09-15 14:00 UTC, iamrajiv requested changes

2020-09-15 14:00 UTC, iamrajiv commented on C-Plus-Plus/README.md
> +- [Unique_no_3](other/unque_no_3.cpp)
@ishi0301 Update this to `[Unique_Number_III ](other/Unique_Number_III.cpp )`

2020-09-15 15:17 UTC, ishi0301 commented
Resolved conflicts. @iamrajiv @HarshCasper @Abhijit2505 @SKAUL05 @Kajol-Kumari @atarax665 .Please review.

2020-09-15 15:20 UTC, iamrajiv requested changes

2020-09-15 15:20 UTC, iamrajiv commented on C-Plus-Plus/README.md
> +<<<<<<< HEAD
@ishi0301 Remove this.

2020-09-15 15:40 UTC, ishi0301 commented
@iamrajiv removed that line

2020-09-15 15:52 UTC, iamrajiv requested changes
@ishi0301 Format the program like this
```cpp
/*
Unique_Number_III
Given an array that contains all elements occurring 3 times, but one occurs only once. Find that unique element.
*/

#include <iostream>
using namespace std;

int main() {
	int cnt[64] = {0};
	int n, num;
	cin >> n;
	for (int i = 0; i < n; i++) {
		cin >> num;
		int j = 0;
		while (num > 0) {
			int last_bit = (num & 1);
			cnt[j] += last_bit;
			j++;
			num = num >> 1;
		}
	}
	int p = 1;
	int ans = 0;
	for (int i = 0; i < 64; i++) {
		cnt[i] %= 3;
		ans += (cnt[i] * p);
		p = p << 1;
	}
	cout << ans << endl;
	return 0;
}

/*
Input:
7
6 2 5 2 2 6 6
Output:
5
Time Complexity: O(n)
*/
```

2020-09-16 03:59 UTC, ishi0301 commented
@iamrajiv formatted the code.

2020-09-16 05:17 UTC, iamrajiv approved these changes
@ishi0301 LGTM!

2020-09-16 07:14 UTC, ishi0301 commented
@SKAUL05 @Abhijit2505 kindly review.

2020-09-16 07:15 UTC, SKAUL05 approved these changes

2020-09-16 10:23 UTC, merged

2020-09-16 10:23 UTC, iamrajiv commented
@all-contributors please add @ishi0301 for code