Longest Common Prefix
HarshCasper/NeoAlgo pull request #1009
Opened 2020-09-13 19:20 UTC by devanshiv123

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Longest Common Prefix using C++.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#917

2020-09-20 08:01 UTC, iamrajiv requested changes
@devanshiv123 Resolve the merge conflicts.

2020-09-22 06:46 UTC, devanshiv123 commented
> @devanshiv123 Resolve the merge conflicts.

@iamrajiv Resolved merge conflicts.

2020-09-22 12:40 UTC, iamrajiv approved these changes

2020-09-25 16:28 UTC, atarax665 approved these changes
LGTM :)

2020-09-25 20:26 UTC, merged