JS code for Russian Peasant
HarshCasper/NeoAlgo pull request #1021
Opened 2020-09-15 14:53 UTC by ritvij14

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
This is the Russian Peasant Algorithm in Javascript, an algorithm to simplify the multiplication of 2 large numbers.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #978 
(Write your answer here.)

2020-09-15 14:54 UTC, ritvij14 commented
@iamrajiv @atarax665 @siddharth25pandey @plazzy99 please review this.

2020-09-18 19:46 UTC, iamrajiv requested changes
@ritvij14 Format the code using Prettier.

2020-09-18 19:46 UTC, iamrajiv commented on JavaScript/README.md
> +
remove this line break

2020-09-19 02:45 UTC, ritvij14 commented on JavaScript/README.md
> +
@iamrajiv done.

2020-09-19 14:19 UTC, ritvij14 commented
@iamrajiv @plazzy99 please review this PR.

2020-09-19 17:45 UTC, plazzy99 approved these changes
👍🏻

2020-09-20 07:46 UTC, iamrajiv approved these changes

2020-09-22 12:02 UTC, ritvij14 commented
@atarax665 @siddharth25pandey please review this, only one review is left to merge.

2020-09-22 12:42 UTC, merged