Array mirror inverse - C
HarshCasper/NeoAlgo pull request #1046
Opened 2020-09-17 20:07 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#661

2020-09-17 20:14 UTC, iamrajiv requested changes

2020-09-17 20:14 UTC, iamrajiv commented on C/cp/Array_Mirror_Inverse.c
> +
@SangeetaMishra To use `bool` in C you have to import `stdbool.h`.

2020-09-17 20:14 UTC, iamrajiv commented on C/cp/Array_Mirror_Inverse.c
> +  bool f = 1;
@SangeetaMishra With `bool` `true` and `false` looks good rather `1` and `0`.

2020-09-17 20:31 UTC, iamrajiv approved these changes

2020-09-18 16:53 UTC, atarax665 approved these changes
LGTM :)

2020-09-20 14:08 UTC, SangeetaMishra commented
@Abhijit2505 Can you please review the PR

2020-09-22 05:55 UTC, siddharth25pandey approved these changes
@SangeetaMishra Good to go
Able to merge
Thanks!

2020-09-22 05:55 UTC, merged