Russian Peasant Algorithm - C++
HarshCasper/NeoAlgo pull request #1051
Opened 2020-09-18 18:13 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#978

2020-09-18 23:28 UTC, iamrajiv approved these changes

2020-09-19 17:44 UTC, plazzy99 approved these changes
👍🏻

2020-09-19 18:11 UTC, atarax665 requested changes

2020-09-19 18:11 UTC, atarax665 commented on C/other/Russian_Peasant_Algorithm.c
> +		if (b%2) {
```suggestion
		if (b % 2) {
```

2020-09-19 18:11 UTC, atarax665 commented on C/other/Russian_Peasant_Algorithm.c
> +		a*=2;
```suggestion
		a *= 2;
```

2020-09-19 18:11 UTC, atarax665 commented on C/other/Russian_Peasant_Algorithm.c
> +		b/=2;
```suggestion
		b /= 2;
```

2020-09-19 18:14 UTC, SangeetaMishra commented
@atarax665 I have made the required changes

2020-09-19 18:19 UTC, atarax665 approved these changes

2020-09-19 18:19 UTC, merged