Euler's Totient Function - Java
HarshCasper/NeoAlgo pull request #1054
Opened 2020-09-18 19:53 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#445

2020-09-18 20:01 UTC, iamrajiv requested changes
@SangeetaMishra LGTM! Format the code like this
```java
/*
Euler's totient function, also known as phi-function ϕ(n), counts the
numberof integers between 1 and n inclusive, which are coprime to n.
*/
import java.util.Scanner;

public class Euler_Totient {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter an integer: ");
		int n = sc.nextInt();

		int temp = n;
		//This gives euler totient function for N
		// Time Complexity: O(N*root(N))
		int ans = n;
		for (int i = 2; i <= n; ++i) {
			if (n % i == 0) {
				ans = ans - ans / i;
				while (n % i == 0)
					n /= i;
			}
		}
		if (n > 1) {
			ans = ans - ans / n;
		}
		n = temp;
		System.out.println("\nThe euler totient function for " + n + " is " + ans);

		//This gives euler totient function from 1 to N
		// Time Complexity: O(N loglogN) - same as Sieve of Eratosthenes
		int phi[] = new int[n + 1];
		for (int i = 0; i <= n; ++i) {
			phi[i] = i;
		}
		for (int i = 2; i <= n; ++i) {
			if (phi[i] == i) {
				for (int j = i; j <= n; j += i) {
					phi[j] = phi[j] - phi[j] / i;
				}
			}
		}
		System.out.println("\nThe euler totient function for all integers from 1 to " + n + " is:\n");
		for (int i = 1; i <= n; ++i) {
			System.out.println(i + " " + phi[i]);
		}
	}
}

/*
Time Complexity: O(N loglogN)
OUTPUT
Enter an integer: 10
The euler totient function for 10 is: 4
The euler totient function for all integers from 1 to 10 is:
1: 1
2: 1
3: 2
4: 2
5: 4
6: 2
7: 6
8: 4
9: 6
10: 4
-----
(1,3,7,9) are coprime to 10
*/
```

2020-09-18 20:21 UTC, iamrajiv approved these changes

2020-09-19 07:43 UTC, Kajol-Kumari approved these changes
@SangeetaMishra Minor change required, Rest LGTM :+1:

2020-09-19 07:43 UTC, Kajol-Kumari commented on Java/math/Euler's_Totient_function.java
> +		// Time Complexity: O(N loglogN) - same as Sieve of Eratosthenes
can we please remove this line as we have already included it in the commented form below the code section.

2020-09-19 18:06 UTC, atarax665 approved these changes
Make these changes so that I can merge this PR.

2020-09-19 18:06 UTC, atarax665 commented on Java/README.md
> +- [Iterative](countDigits/iterative.java)
```suggestion
- [Iterative](math/countDigits/iterative.java)
```

2020-09-19 18:06 UTC, atarax665 commented on Java/README.md
> +- [Recursive](countDigits/recursive.java)
```suggestion
- [Recursive](math/countDigits/recursive.java)
```

2020-09-19 18:06 UTC, atarax665 commented on Java/README.md
> +- [String Method](countDigits/stringmethod.java)
```suggestion
- [String Method](math/countDigits/stringmethod.java)
```

2020-09-19 18:08 UTC, SangeetaMishra commented
@atarax665 I have made the required changes

2020-09-19 18:21 UTC, merged