Ag278 swapnibbles
HarshCasper/NeoAlgo pull request #1057
Opened 2020-09-19 20:08 UTC by ag278

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is code to swap nibbles in C using bitwise operator

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#980

2020-09-19 20:09 UTC, ag278 commented
@iamrajiv @siddharth25pandey @Kajol-Kumari please review my PR

2020-09-20 07:59 UTC, iamrajiv requested changes
@ag278 Name the program like this `Swap_two_nibbles.c`.

2020-09-20 09:37 UTC, Kajol-Kumari requested changes
@ag278 please incorporate the following changes.

2020-09-20 09:37 UTC, Kajol-Kumari commented on C/other/Swap two nibbles.c
> +*/
please provide one blank line at the end of the file.

2020-09-20 09:37 UTC, Kajol-Kumari commented on C/other/Swap two nibbles.c
> +    printf(" %d\n",result);
Please provide a message like `output` before printing the result here.

2020-09-20 13:29 UTC, ag278 commented
@iamrajiv @Kajol-Kumari I have solved the issues. Please verify it

2020-09-20 13:46 UTC, iamrajiv approved these changes

2020-09-20 14:34 UTC, Kajol-Kumari approved these changes
@ag278 Minor change required, Rest LGTM :+1:

2020-09-20 14:34 UTC, Kajol-Kumari commented on C/other/Swap_two_nibbles.c
> +Output:
please change this line to `output is: 35` as you have made the change in the code here.

2020-09-20 14:42 UTC, siddharth25pandey approved these changes
@ag278 Good to go
Able to merge.
Thanks!

2020-09-20 14:42 UTC, merged

2020-09-20 14:42 UTC, siddharth25pandey commented
@all-contributors please add @ag278 for his code