Max_Sum_Rectangle-matrix Code in C
HarshCasper/NeoAlgo pull request #1082
Opened 2020-09-24 17:22 UTC by nutanaarohi123

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
#937 
C code to find the maximum sum subarray in the 2-D matrix using Kadane’s algorithm to reduce the time complexity to O(n^3).

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#937

2020-09-24 17:25 UTC, nutanaarohi123 commented
Kindly review this. @SKAUL05  @iamrajiv  @Kajol-Kumari

2020-09-24 19:17 UTC, iamrajiv requested changes
@nutanaarohi123 Update time complexity `O(n^3)` to `O(cols^2 * rows)` and space complexity `O(n)` to `O(rows)`.

2020-09-25 02:13 UTC, nutanaarohi123 commented
> @nutanaarohi123 Update time complexity `O(n^3)` to `O(cols^2 * rows)` and space complexity `O(n)` to `O(rows)`.

Updated the changes. Kindly review @iamrajiv.

2020-09-25 02:34 UTC, SKAUL05 approved these changes

2020-09-25 02:43 UTC, iamrajiv requested changes

2020-09-25 02:43 UTC, iamrajiv commented on C/dp/Max_Sum_Rectangle.c
> + Space Compleity: O(rows)
@nutanaarohi123 fix typo

2020-09-25 03:23 UTC, nutanaarohi123 commented on C/dp/Max_Sum_Rectangle.c
> + Space Compleity: O(rows)
> @nutanaarohi123 fix typo

DONE

2020-09-25 03:27 UTC, iamrajiv approved these changes

2020-09-25 12:30 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2020-09-25 15:40 UTC, merged