Finding the Numbers
HarshCasper/NeoAlgo pull request #1094
Opened 2020-09-26 07:07 UTC by narayan2111

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Program to find the Unique numbers in an array out of which two numbers occur exactly once and are distinct.
You need to find the other two numbers and print them in ascending order.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#922

2020-09-26 07:08 UTC, narayan2111 commented
kindly review this PR @iamrajiv @plazzy99 @Kajol-Kumari

2020-09-26 12:38 UTC, plazzy99 requested changes
https://www.geeksforgeeks.org/find-unique-pair-array-pairs-numbers/

code is exactly same with comments and all

2020-09-26 13:46 UTC, narayan2111 commented
> https://www.geeksforgeeks.org/find-unique-pair-array-pairs-numbers/
> 
> code is exactly same with comments and all

Updated the whole code and comments but algorithm is same.
Also I don't find any algorithm better than this.

2020-09-26 13:53 UTC, narayan2111 commented
> https://www.geeksforgeeks.org/find-unique-pair-array-pairs-numbers/
> 
> code is exactly same with comments and all

@plazzy99 
Updated the whole code and comments but algorithm is same.
Also I added geeksforgeeks in comment from where i had taken help

2020-09-27 16:32 UTC, narayan2111 commented
Kindly review this PR @Kajol-Kumari @iamrajiv @plazzy99

2020-09-27 18:45 UTC, Kajol-Kumari approved these changes
@narayan2111 Minor comment, Rest LGTM :+1:

2020-09-27 18:45 UTC, Kajol-Kumari commented on C/other/Find_the_numbers.c
> +//Program to find the Unique numbers in an array out of which two numbers occur exactly once and are distinct.
please use multiline comment here.

2020-09-28 04:28 UTC, iamrajiv approved these changes

2020-09-28 15:09 UTC, narayan2111 commented
Kindly review this PR @plazzy99

2020-09-28 16:15 UTC, plazzy99 approved these changes

2020-09-28 16:15 UTC, merged