Painter partition
HarshCasper/NeoAlgo pull request #1103
Opened 2020-09-26 17:40 UTC by NEEHITGOYAL

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added solution to this problem using binary search approach to reduce time complexity and also used dynamic array
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1068

2020-09-26 17:42 UTC, NEEHITGOYAL commented
kindly review and merge this pr

2020-09-28 16:08 UTC, plazzy99 requested changes

2020-09-28 16:08 UTC, plazzy99 commented on C-Plus-Plus/cp/painter_partition.cpp
> +    {
refractor the code with proper indentation.

2020-09-28 16:08 UTC, plazzy99 commented on C-Plus-Plus/cp/painter_partition.cpp
> +
remove all the unwanted line space

2020-09-28 17:25 UTC, NEEHITGOYAL commented
@plazzy99 done identation and removed unwanted spaces

2020-09-28 18:32 UTC, plazzy99 approved these changes
👍🏻

2020-09-29 04:41 UTC, merged