Search index position in java
HarshCasper/NeoAlgo pull request #1123
Opened 2020-09-29 15:25 UTC by rutujadhanawade

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for Search insert position in java.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1119

2020-09-29 15:25 UTC, rutujadhanawade commented
@iamrajiv @atarax665 @plazzy99 Please review.

2020-09-29 22:48 UTC, plazzy99 requested changes

2020-09-29 22:48 UTC, plazzy99 commented on Java/other/Search_insert_index.java
> +            arr[i] = sc.nextInt();
remove extra lines spaces

2020-09-29 22:48 UTC, plazzy99 commented on Java/other/Search_insert_index.java
> +            arr[i] = sc.nextInt();
make proper indentation

2020-09-30 04:12 UTC, rutujadhanawade commented
Done :+1: @plazzy99 Please review.

2020-09-30 04:43 UTC, iamrajiv approved these changes

2020-09-30 16:25 UTC, plazzy99 approved these changes
👍🏻

2020-09-30 16:25 UTC, merged