Bilinear Search in C
HarshCasper/NeoAlgo pull request #1187
Opened 2020-10-01 08:28 UTC by sparkingdark

new file:   C/search/bilinear.c

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes i read it.

### Description
It is the implementation of bilinear search in c regarding issue #195 
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#195

2020-10-03 08:40 UTC, atarax665 requested changes
Format your code according to C style guide.

2020-10-03 08:40 UTC, atarax665 commented on C/search/bilinear.c
> +    int i = 0;
Use meaningful name for the variables instead of i, j, p.

2020-10-03 08:40 UTC, atarax665 commented on C/search/bilinear.c
> +}
Add sample input/output and time/space complexity of the algorithm in commented form.

2020-10-03 08:47 UTC, atarax665 commented
Update README.md

2020-10-03 14:46 UTC, sparkingdark commented
Okay I will do the requested changes.

2020-12-08 07:49 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-08 07:49 UTC, closed without merging