Added ArmstrongNumber.java
HarshCasper/NeoAlgo pull request #1230
Opened 2020-10-02 08:17 UTC by rohangawhade

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added a java code to check whether the input number is an Armstrong number or not.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1217

2020-10-03 16:17 UTC, rohangawhade commented
@siddharth25pandey  Kindly review my PR

2020-10-07 18:22 UTC, atarax665 requested changes

2020-10-07 18:22 UTC, atarax665 commented on Java/math/ArmstrongNumber.java
> +	    if(num == val) System.out.println(num+" is armstrong");
```suggestion
	    if(num == val) System.out.println(num+" is an armstrong number.");
```

2020-10-07 18:22 UTC, atarax665 commented on Java/math/ArmstrongNumber.java
> +	    else System.out.println(num+" is not armstrong");
```suggestion
	    else System.out.println(num+" is not an armstrong number.");
```

2020-10-07 18:22 UTC, atarax665 commented on Java/math/ArmstrongNumber.java
> +Number is not armstrong
Edit sample I/O according to your code.

2020-10-07 18:22 UTC, atarax665 commented on Java/math/ArmstrongNumber.java
> +	        res = res/10;
```suggestion
	        res = res / 10;
```

2020-10-07 18:22 UTC, atarax665 commented on Java/math/ArmstrongNumber.java
> +	        int temp = res%10;
```suggestion
	        int temp = res % 10;
```

2020-10-07 18:22 UTC, atarax665 commented on Java/math/ArmstrongNumber.java
> +	    int val=0;
```suggestion
	    int val = 0;
```

2020-10-07 19:02 UTC, rohangawhade commented on Java/math/ArmstrongNumber.java
> +	    int val=0;
@atarax665  Made the suggested changes.

2020-12-08 07:56 UTC, HarshCasper commented
LGTM!

2020-12-08 07:56 UTC, merged