Find numbers
HarshCasper/NeoAlgo pull request #1245
Opened 2020-10-02 13:52 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#922

2020-10-02 13:57 UTC, iamrajiv requested changes
@SangeetaMishra Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

2020-10-02 14:08 UTC, iamrajiv approved these changes

2020-10-02 17:58 UTC, atarax665 requested changes

2020-10-02 17:58 UTC, atarax665 commented on Python/other/find_the_numbers.py
> +# Python program to find the inique numbers in an array out
```suggestion
# Python program to find the unique numbers in an array out
```

2020-10-02 17:58 UTC, atarax665 commented on Python/other/find_the_numbers.py
> +    print("The distinct numbers are ", x, " and ", y)
Add sample Input/Output and Time and Space Complexity in commented form.

2020-10-03 13:53 UTC, Abhijit2505 approved these changes
Looking good to me, but there are merge conflicts. Please resolve them as well.

2020-10-04 18:06 UTC, SangeetaMishra commented
@atarax665 Please review this

2020-10-05 09:08 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2020-10-05 11:10 UTC, merged