Z algorithm in C++
HarshCasper/NeoAlgo pull request #1247
Opened 2020-10-02 15:16 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#417

2020-10-02 18:57 UTC, atarax665 requested changes
Format your code using https://www.techiedelight.com/tools/clike

2020-10-02 18:57 UTC, atarax665 commented on C-Plus-Plus/cp/zalgorithm.cpp
> +    cin >> text >> pattern;
Prompt user to input the original string and the pattern to be searched separately.

2020-10-02 19:50 UTC, atarax665 requested changes

2020-10-02 19:50 UTC, atarax665 commented on C-Plus-Plus/cp/zalgorithm.cpp
> +Input
Format the input according to the changes you have made recently.

2020-10-03 04:19 UTC, iamrajiv approved these changes

2020-10-04 15:55 UTC, plazzy99 approved these changes
👍🏻

2020-10-04 18:03 UTC, atarax665 approved these changes

2020-10-04 18:03 UTC, merged