Z algorithm in C
HarshCasper/NeoAlgo pull request #1248
Opened 2020-10-02 15:28 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#417
(Write your answer here.)

2020-10-03 04:18 UTC, iamrajiv approved these changes

2020-10-03 09:00 UTC, plazzy99 approved these changes
👍🏻

2020-10-03 10:02 UTC, atarax665 requested changes
Format your code using https://www.techiedelight.com/tools/clike

2020-10-03 10:02 UTC, atarax665 commented on C/cp/zalgorithm.c
> +AABACAAFGAABAABA
Sample input/output should be same as what we will get when the program is run in IDE.
eg- ```Enter the text: AABACAAFGAABAABA```

2020-10-04 05:51 UTC, atarax665 approved these changes
Looks good to me now. DO this small change and it will be good to merge.

2020-10-04 05:51 UTC, atarax665 commented on C/cp/zalgorithm.c
> +	int z[n] = {};
```suggestion
	int z[n];
```

2020-10-04 15:52 UTC, merged