Least Common Multiple
HarshCasper/NeoAlgo pull request #1310
Opened 2020-10-09 08:51 UTC by yashaswibiyahut

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Least Common Multiple using gcd

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ]  I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-10-09 08:53 UTC, yashaswibiyahut commented
kindly review this PR @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv @HarshCasper

2020-10-09 09:00 UTC, SKAUL05 approved these changes
LGTM

2020-10-09 14:35 UTC, yashaswibiyahut commented
@SKAUL05 if one 1 review is enough then  kindly merge this PR 😊

2020-10-09 16:40 UTC, atarax665 requested changes

2020-10-09 16:40 UTC, atarax665 commented on C-Plus-Plus/other/lcm.cpp
> +
You may add description of the in-built LCM function that was introduced in C++17, which may come handy during competitive programming. You can read about it [here](https://www.geeksforgeeks.org/stdlcm-in-cpp17/)

2020-10-09 16:40 UTC, atarax665 commented on C-Plus-Plus/other/lcm.cpp
> +    int n1, n2, max;
```suggestion
    int n1, n2;
```
We don't need any extra variable here.

2020-10-09 16:40 UTC, atarax665 commented on C-Plus-Plus/other/lcm.cpp
> +    cout<<"\tOUTPUT\n";
Remove this line, its better to print the output as ```LCM of a and b --> x```

2020-10-10 06:08 UTC, yashaswibiyahut commented
done @atarax665  kindly review it.

2020-10-10 14:07 UTC, plazzy99 approved these changes
👍🏻

2020-10-10 15:58 UTC, iamrajiv approved these changes

2020-10-10 18:11 UTC, yashaswibiyahut commented
Kindly merge this PR @iamrajiv

2020-10-10 18:29 UTC, atarax665 approved these changes

2020-10-10 18:29 UTC, merged