dynamic user input added
HarshCasper/NeoAlgo pull request #1320
Opened 2020-10-11 20:03 UTC by reachpranjal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-11-01 17:15 UTC, atarax665 requested changes

2020-11-01 17:15 UTC, atarax665 commented on Python/math/Area.py
> -    Calculate the area of a rectangle
Do not remove these docstrings, docstring helps in understanding how a function works.

2020-11-01 17:15 UTC, atarax665 commented on .vscode/settings.json
> +{
Remove this file, this ain't needed.

2020-12-08 08:10 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-08 08:10 UTC, closed without merging