Tenary search
HarshCasper/NeoAlgo pull request #1330
Opened 2020-10-15 14:28 UTC by CormacKrum

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Added Tenary Search Both in Iterative And Recursive Approach in CPP.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#1326 )

2020-10-15 16:30 UTC, atarax665 requested changes

2020-10-15 16:30 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +
Please remove unnecessary line breaks.

2020-10-15 16:30 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +	p = ternarySearchRecursion(l, r, key, ar);
Print recursive and iterative result separately with heading as ```Iterative approach``` and ```Recursive Approach```.

2020-10-15 16:30 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +}
Add sample input/output and time complexity for your code.

2020-10-15 20:14 UTC, atarax665 requested changes

2020-10-15 20:14 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +	int ar[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
Prefer taking dynamic inputs.

2020-10-15 20:14 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +}
Add sample input/output at the end of your code in format
```
'''
Time Complexity : 

Sample I/O : 

Input :

Output : 

'''
```

2020-10-16 15:55 UTC, CormacKrum commented
@atarax665  Please Review My PR.

2020-10-16 18:07 UTC, atarax665 requested changes

2020-10-16 18:07 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +	int *ar = new int[r];
You can initialize an array normally as ```int ar[r];```

2020-10-16 18:07 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +	cin>>r;
Prompt user to enter the number of elements.
i.e ```cout << "Enter the number of elements in the array : "<<endl;```

2020-10-16 18:07 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +	for(int i=0;i<r;i++){
Prompt user to enter the elements of the array.

2020-10-16 18:07 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +	cin>>key;
Prompt user to enter the number to be searched and do edit sample input/output accordingly.

2020-10-17 16:56 UTC, CormacKrum commented
@atarax665  Please Review My PR.

2020-10-18 16:56 UTC, atarax665 requested changes
Do add comments wherever necessary. Everything else looks fine to me.

2020-10-18 16:56 UTC, atarax665 commented on C-Plus-Plus/search/TernarySearch.cpp
> +int ternarySearchRecursion(int l, int r, int key, int ar[])
Use meaningful variables name instead of ```l```, ```r```. A meaningful variable name would help beginners to get grasp of the algorithm in no time.

2020-10-19 20:31 UTC, JayantGoel001 commented
@atarax665 Please Review My PR Again.

2020-10-27 13:07 UTC, atarax665 approved these changes
👍👍

2020-10-27 14:27 UTC, JayantGoel001 commented
@atarax665 Please Merge My PR.

2020-11-01 17:14 UTC, atarax665 commented
@JayantGoel001 Upadate README.md

2020-11-01 18:08 UTC, plazzy99 approved these changes
👍🏻 
Update readme file

2020-11-01 18:43 UTC, JayantGoel001 commented
I have update Readme 
Kindly Check
@atarax665 @plazzy99

2020-11-01 19:08 UTC, plazzy99 approved these changes
👍🏻

2020-11-01 19:09 UTC, JayantGoel001 commented
Please Merge My PR @plazzy99

2020-11-01 19:27 UTC, plazzy99 commented
> Please Merge My PR @plazzy99

your pr will be merged after 3 successful review

2020-11-02 10:03 UTC, iamrajiv approved these changes

2020-11-02 10:03 UTC, merged

2020-11-02 10:03 UTC, iamrajiv commented
@all-contributors please add @JayantGoel001 for code