Hacktoberfest
HarshCasper/NeoAlgo pull request #1332
Opened 2020-10-16 04:54 UTC by ArnavHP18

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

added polynomial regression in python ml

### Checklist

- [ y] I've read the contribution guidelines.
- [y ] I've checked the issue list before deciding what to submit.
- [y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-10-17 02:15 UTC, Abhijit2505 requested changes
Although the main algorithm is correct, there are few questions,

1 - The dataset is small, having only two columns, the real-time dataset doesn't come like this and to perform polynomial regression we need to tweak the data.
2 - Add a method to determine the degree of the polynomial equation.

2020-10-17 02:15 UTC, Abhijit2505 commented on Python/ml/Polynomial_Regression.ipynb
> +    "X_poly = poly_reg.fit_transform(X ,y)"
You have taken the degree of the polynomial regression as 5, as this was a small dataset it was easy to determine the degree.

I would like you to implement the same from the `car price prediction` dataset on Kaggle and also come up with a method to get the degree.

Hint - In the polynomial regression equation, which is the most significant term?

2020-10-17 02:15 UTC, Abhijit2505 commented on Python/ml/Polynomial_Regression.ipynb
> +   "cell_type": "code",
One more thing to keep in mind while preparing any regression model,
don't forget to make an EDA.

2020-10-27 13:05 UTC, atarax665 commented
@ArnavHP18 We haven't heard from you you in a while. Do the suggested changes ASAP to get this PR merged.

2020-12-09 10:04 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-09 10:04 UTC, closed without merging