Implemented Ternary Search in Java
HarshCasper/NeoAlgo pull request #1334
Opened 2020-10-16 11:29 UTC by parjanyaacoder

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented Ternary Search in Java

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1333

2020-10-16 11:31 UTC, parjanyaacoder commented
@atarax665  Please review. Thank you.

2020-10-16 18:10 UTC, atarax665 requested changes
I will suggest you to make function to implement ternary search alhorithm in both iteratively and recursively. You may refer #1330 
- Also add sample input/output and complexity of your program at the end in commented form,

2020-10-18 04:29 UTC, parjanyaacoder reviewed
@atarax665  All changes have been made.

2020-10-18 18:27 UTC, atarax665 requested changes

2020-10-18 18:27 UTC, atarax665 commented on Java/search/TernarySearch.java
> +  static int ternarySearchRecursive (int arr[], int f, int l, int h)
Use variable names ```left``` and ```right``` instead of l and h. This will help others in better understanding the code.

2020-10-18 18:27 UTC, atarax665 commented on Java/search/TernarySearch.java
> +    int i, j, k, l, m, n, h, mid1, mid2, f = -1, element;
Few unnecessary variables have also been declared.

2020-10-19 09:02 UTC, parjanyaacoder reviewed
@atarax665 Done requested changes.

2020-10-19 16:33 UTC, atarax665 approved these changes
Update README.md, everything else looks fine to me.

2020-10-19 18:30 UTC, iamrajiv approved these changes

2020-10-21 04:57 UTC, parjanyaacoder commented
@atarax665 @iamrajiv Updated Readme also. Please merge this pull request.

2020-11-04 11:36 UTC, plazzy99 approved these changes
👍🏻

2020-11-04 11:36 UTC, merged