Trie.py and README updated
HarshCasper/NeoAlgo pull request #1342
Opened 2020-10-17 07:44 UTC by Bidonsaha

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-10-17 17:16 UTC, atarax665 commented
Fill the PR template.

2020-10-17 17:43 UTC, atarax665 requested changes
Format your code according to PEP8 requirements. You can use http://pep8online.com/ for this.

2020-10-17 17:43 UTC, atarax665 commented on Python/ds/Trie.py
> +	"""
Instead of here add sample input/output at end of the program. Sample output should be same as whats seen when the code runs in an IDE.

2020-10-19 07:40 UTC, Bidonsaha reviewed
I've formatted it in pep8 adn updated the sample i/o section.Do check it.

2020-10-20 15:31 UTC, atarax665 approved these changes
LGTM :)

2020-10-20 16:49 UTC, iamrajiv approved these changes

2020-10-27 07:51 UTC, Bidonsaha commented
Hey @plazzy99 please review the request..

2020-10-27 13:26 UTC, plazzy99 approved these changes
👍🏻

2020-10-27 13:26 UTC, merged

2020-10-27 18:43 UTC, Bidonsaha commented
Hey @plazzy99  @iamrajiv  @atarax665  can you please add the hackotberfest labels?