Happy number
HarshCasper/NeoAlgo pull request #1354
Opened 2020-10-19 04:41 UTC by salonishah01

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Happy Number code in python

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1308

2020-10-20 16:18 UTC, atarax665 requested changes
You have made too many changes in README. Revert it and just add the hyperlink of your contributed code. Everything else looks fine.

2020-10-20 16:18 UTC, atarax665 commented on Python/other/HappyNumber.py
> +
Remove these blank lines.

2020-10-21 03:33 UTC, salonishah01 commented on Python/other/HappyNumber.py
> +
@atarax665 Done

2020-10-22 16:48 UTC, atarax665 reviewed
You have made so many unnecessary changes in README. Do revert them and just link your program under ```other``` heading.

2020-10-22 16:48 UTC, atarax665 commented on Python/other/HappyNumber.py
> +
```suggestion
"""
```

2020-10-23 03:25 UTC, closed without merging

2020-10-23 03:32 UTC, salonishah01 commented
@atarax665 It was getting difficult to resolve the changes committed. I have generated another PR #1373 , with correct updations.