added Happy_Number problem's code in java, for issue #1308
HarshCasper/NeoAlgo pull request #1364
Opened 2020-10-22 06:49 UTC by rishigarg94

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-10-22 06:50 UTC, rishigarg94 commented
@atarax665  @iamrajiv  @plazzy99  please, review my PR for issue #1308  , i have uploaded code in java

2020-10-22 08:48 UTC, plazzy99 requested changes

2020-10-22 08:48 UTC, plazzy99 commented on Java/cp/Happy_Number.java
> +        " is a Happy number");
refractor your code with proper indentation

2020-10-22 10:51 UTC, iamrajiv requested changes
@rishigarg94 Add sample input-output, time complexity and space complexity.

2020-12-09 10:07 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-09 10:07 UTC, closed without merging