Added a String Permutation program using C
HarshCasper/NeoAlgo pull request #1366
Opened 2020-10-22 07:59 UTC by amit14mitra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-10-22 17:47 UTC, atarax665 requested changes
Use of proper comments enhance the readability of the code, so use comments wherever necessary to explain your approach.

2020-10-22 17:47 UTC, atarax665 commented on C/other/String_permutation.c
> +# Added a permutation of strings program using C
```#``` indicates pre=processor directives in C++, use ```//``` for commenting.

2020-10-22 17:47 UTC, atarax665 commented on C/other/String_permutation.c
> +	int n;
Prompt user to input the length of the string.

2020-10-22 17:47 UTC, atarax665 commented on C/other/String_permutation.c
> +	scanf("%d", &n);
Prompt user to input the string.

2020-10-22 17:47 UTC, atarax665 commented on C/other/String_permutation.c
> +}
Add sample input/output and complexity of the program in commented form. (Refer other merged PRs for insight)

2020-10-23 06:22 UTC, amit14mitra commented
Hi,

I have done the changes now. you can check it.

Thanks,
Amit

On Thu, 22 Oct 2020 at 23:18, Abhinav Anand <notifications@github.com>
wrote:

> *@atarax665* requested changes on this pull request.
>
> Use of proper comments enhance the readability of the code, so use
> comments wherever necessary to explain your approach.
> ------------------------------
>
> In C/other/String_permutation.c
> <https://github.com/TesseractCoding/NeoAlgo/pull/1366#discussion_r510333098>
> :
>
> > @@ -0,0 +1,51 @@
> +# Added a permutation of strings program using C
>
> # indicates pre=processor directives in C++, use // for commenting.
> ------------------------------
>
> In C/other/String_permutation.c
> <https://github.com/TesseractCoding/NeoAlgo/pull/1366#discussion_r510346451>
> :
>
> > +
> +    j = n-1;
> +    while(i<j) {
> +        tmp = s[i];
> +        s[i] = s[j];
> +        s[j] = tmp;
> +        i++;
> +        j--;
> +    }
> +    return 1;
> +}
> +
> +int main()
> +{
> +	char **s;
> +	int n;
>
> Prompt user to input the length of the string.
> ------------------------------
>
> In C/other/String_permutation.c
> <https://github.com/TesseractCoding/NeoAlgo/pull/1366#discussion_r510346625>
> :
>
> > +    j = n-1;
> +    while(i<j) {
> +        tmp = s[i];
> +        s[i] = s[j];
> +        s[j] = tmp;
> +        i++;
> +        j--;
> +    }
> +    return 1;
> +}
> +
> +int main()
> +{
> +	char **s;
> +	int n;
> +	scanf("%d", &n);
>
> Prompt user to input the string.
> ------------------------------
>
> In C/other/String_permutation.c
> <https://github.com/TesseractCoding/NeoAlgo/pull/1366#discussion_r510347319>
> :
>
> > +	s = calloc(n, sizeof(char*));
> +	for (int i = 0; i < n; i++)
> +	{
> +		s[i] = calloc(11, sizeof(char));
> +		scanf("%s", s[i]);
> +	}
> +	do
> +	{
> +		for (int i = 0; i < n; i++)
> +			printf("%s%c", s[i], i == n - 1 ? '\n' : ' ');
> +	} while (next_permutation(n, s));
> +	for (int i = 0; i < n; i++)
> +		free(s[i]);
> +	free(s);
> +	return 0;
> +}
>
> Add sample input/output and complexity of the program in commented form.
> (Refer other merged PRs for insight)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TesseractCoding/NeoAlgo/pull/1366#pullrequestreview-514957481>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL5VGDTWIELSBJVQMP4JOBLSMBV5TANCNFSM4S22NPNA>
> .
>

2020-10-24 14:25 UTC, atarax665 commented
@amit14mitra Sorry, but I couldn't see any new commit.

2020-10-24 14:30 UTC, amit14mitra commented
Hi,

I have already PR a totally new file of the same problem with the revised
version.

Thanks,
Amit

On Sat, Oct 24, 2020, 19:56 Abhinav Anand <notifications@github.com> wrote:

> @amit14mitra <https://github.com/amit14mitra> Sorry, but I couldn't see
> any new commit.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TesseractCoding/NeoAlgo/pull/1366#issuecomment-715922557>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL5VGDXG3PJJX6AWOJ2T7ZLSMLPX5ANCNFSM4S22NPNA>
> .
>

2020-10-30 18:23 UTC, closed without merging