Max_subarray_sum(DP).cpp
HarshCasper/NeoAlgo pull request #1377
Opened 2020-10-23 10:48 UTC by AnshikaY

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes 
### Description
(Write your answer here.)
Code to find maximum subarray sum using prefix sum array.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
(Write your answer here.) PR #1337

2020-10-23 12:59 UTC, iamrajiv requested changes
@AnshikaY No need to add README(2).txt instead add these contents in `Max_subarray_sum(DP).cpp ` in comments. Also, update the C++ README file by adding the link of the program in it.

2020-10-23 12:59 UTC, iamrajiv commented on C-Plus-Plus/dp/Max_subarray_sum(DP).cpp
> +
remove unnecessary line breaks

2020-10-23 12:59 UTC, iamrajiv commented on C-Plus-Plus/dp/Max_subarray_sum(DP).cpp
> +Time Complexity : O(n)
time complexity, space complexity and sample input-output should be in a comment you can take reference from existing code in repository

2020-10-23 16:51 UTC, iamrajiv requested changes
@AnshikaY Do not make new PR to edit the README you can do that in this PR only.

2020-10-23 18:46 UTC, iamrajiv requested changes
@AnshikaY Unnecessary files are also committed please take a look like.

2020-10-23 18:46 UTC, iamrajiv commented on C-Plus-Plus/README.md
> +- [Maximum Subarray Sum](C-Plus-Plus/dp/Max_subarray_sum(DP).cpp)
change it to `- [Maximum Subarray Sum](dp/Max_subarray_sum(DP).cpp)`

2020-10-24 08:38 UTC, AnshikaY commented
> @AnshikaY Unnecessary files are also committed please take a look like.

@iamrajiv No idea how the extra files are being reflected in this commit. Should I directly delete them from the delete file option?

2020-10-24 10:38 UTC, iamrajiv commented
@AnshikaY No do not delete the files because if you delete the files it will be counted as a commit. I would suggest making the files even with  NeoAlgo repository files which are not needed.

2020-10-24 10:41 UTC, iamrajiv commented
@AnshikaY The reason of doing this is we do not want any change in other files and that can only happen when you make files even with the branch in which you want to merge your PR and in this case, the master branch of NeoAlgo repository.

2020-10-26 07:13 UTC, AnshikaY commented
@iamrajiv The commit history generated is pretty random. Each time I try to make a commit, new random files and commits start being reflected under this PR. I am unable to understand the cause and solution of this.

2020-10-26 22:31 UTC, iamrajiv commented
@AnshikaY This problem is occurring because it might be the case that you to pulled the commit from `TesseractCoding:master` to `AnshikaY:master`. Also, I would suggest do not make PR form `master` instead make another branch.

2020-10-26 22:43 UTC, iamrajiv approved these changes
@AnshikaY I have removed the unwanted changes.

2020-10-27 11:02 UTC, AnshikaY commented
> @AnshikaY I have removed the unwanted changes.

@iamrajiv Thanks for your patience and for adding to my learning!
Regards.

2020-10-29 14:49 UTC, atarax665 approved these changes
Resolve merge conflict. Code looks good to me. :+1:

2020-12-21 13:47 UTC, merged