Create PrimeNumber.c with time complexity and user input
HarshCasper/NeoAlgo pull request #1381
Opened 2020-10-24 03:57 UTC by manavbhikadiya

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-10-24 03:58 UTC, manavbhikadiya commented
Changes complete with user input and time complexity. please accept my pull request.

2020-10-24 14:09 UTC, atarax665 requested changes
Iterative approach will be fine after the suggested change is made. You also need to implement this recursively.

2020-10-24 14:09 UTC, atarax665 commented on C/math/PrimeNumber.c
> +   for(int i=2 ; i < num/2 ; i++) {
We need to check for factors of the number only till ```sqrt(n)```. Refer [this](https://stackoverflow.com/questions/5811151/why-do-we-check-up-to-the-square-root-of-a-prime-number-to-determine-if-it-is-pr) to learn more.

2020-12-09 10:16 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-09 10:16 UTC, closed without merging