Ackerman Function #1361 solution in python
HarshCasper/NeoAlgo pull request #1382
Opened 2020-10-24 14:54 UTC by pra17dod

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description
I read each and every detail mentioned in the contributing.md

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR will add solution of issue #1361 on Ackermann Function in python in which I was assigned.

2020-10-24 23:22 UTC, iamrajiv requested changes
@pra17dod Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

2020-10-24 23:22 UTC, iamrajiv commented on Python/math/ackermann_function.py
> +def Ackermann_func(m, n):
@pra17dod Add little bit description about Ackermann Function.

2020-10-25 13:52 UTC, pra17dod commented
Please review again the changes I made, @iamrajiv.

2020-10-25 14:19 UTC, iamrajiv approved these changes

2020-10-25 16:15 UTC, atarax665 requested changes

2020-10-25 16:15 UTC, atarax665 commented on Python/math/ackermann_function.py
> +# Space complexity: O( M * N )
Add sample input/output in commented form.

2020-10-25 16:21 UTC, pra17dod commented
Please review again the changes I made, @atarax665 .

2020-10-25 19:08 UTC, iamrajiv approved these changes

2020-10-26 05:59 UTC, pra17dod commented on Python/math/ackermann_function.py
> +def Ackermann_func(m, n):
Yaa sure

2020-10-26 08:32 UTC, plazzy99 approved these changes
👍🏻

2020-10-26 08:32 UTC, merged