Create list_fibonacci.c
HarshCasper/NeoAlgo pull request #1390
Opened 2020-10-31 15:08 UTC by thomasina23

list the required number of terms in the Fibonacci Series

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This program accepts an input number from the user and list out the given number of terms in the Fibonacci Series

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Added new code

2020-10-31 18:18 UTC, atarax665 requested changes

2020-10-31 18:18 UTC, atarax665 commented on C/math/list_fibonacci.c
> +     int t1=0, t2=1, t3, i, terms;
Use more meaningful variable names.

2020-10-31 18:18 UTC, atarax665 commented on C/math/list_fibonacci.c
> +     for(i=2;i<terms;++i)
```suggestion
     for(i = 2; i < terms; ++i)
```

2020-10-31 18:18 UTC, atarax665 commented on C/math/list_fibonacci.c
> +}
Add sample Input/Output and time/space complexity of your code in commented form.

2020-10-31 18:18 UTC, atarax665 commented on C/math/list_fibonacci.c
> +     for(i=2;i<terms;++i)
```suggestion
     for(i = 2; i < terms; ++i)
```

2020-10-31 18:20 UTC, atarax665 commented
Update ```C/README.md```. Refer any merged PR for better insight.

2020-12-09 10:24 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-09 10:24 UTC, closed without merging