Create Generate_Pythagorean_Triplet.c
HarshCasper/NeoAlgo pull request #1391
Opened 2020-10-31 16:06 UTC by Harikrishnaa3131

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-10-31 16:33 UTC, iamrajiv reviewed
@Harikrishnaa3131 Add sample input-output, space complexity and time complexity. Also, update the README.

2020-11-02 18:06 UTC, atarax665 requested changes

2020-11-02 18:06 UTC, atarax665 commented on C/math/Generate_Pythagorean_Triplet.c
> +Sample Input:
Add time/space complexity too. This whole clock should be in commented form.
i.e- 
```
/*
Time Complexity : 
Space Complexity : 

Sample I/O : 

Input : 

Output : 

*/
```

2020-11-02 18:06 UTC, atarax665 commented on C/math/Generate_Pythagorean_Triplet.c
> +This program finds the pythagorean triplet in the given limit
This should be at top. Do not forget to comment this line using ```//```.

2020-11-02 18:06 UTC, atarax665 commented on C-Plus-Plus/math/Product_of_fractions.cpp
> +}
Add sample input/output and Time and space complexity of your program in commented form. Refer any merged PR for better insight.

2020-11-21 15:09 UTC, plazzy99 requested changes

2020-11-21 15:09 UTC, plazzy99 commented on C-Plus-Plus/math/Product_of_fractions.cpp
> +
also remove these redundant spaces

2020-11-21 15:09 UTC, plazzy99 commented on C/math/Generate_Pythagorean_Triplet.c
> +
remove redundant spaces from everywhere.

2020-12-09 10:25 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-09 10:25 UTC, closed without merging