Gaurav6982
HarshCasper/NeoAlgo pull request #1398
Opened 2020-11-02 12:34 UTC by Gaurav6982

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have Added Files for Rectangle Cutting using DP WITH CPP and JAVA.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-11-02 12:34 UTC, Gaurav6982 commented
Please Review @plazzy99

2020-11-02 12:59 UTC, iamrajiv requested changes
@Gaurav6982 Do not edit unnecessary files i.e. `bin_exp.js `.

2020-11-02 13:28 UTC, Gaurav6982 commented
> @Gaurav6982 Do not edit unnecessary files i.e. `bin_exp.js `.
I have not made a change in that file, actually that was my previous commit which got added itself. I think I have made some error while making a pull request. Sorry for that.

2020-11-02 22:39 UTC, iamrajiv requested changes
@Gaurav6982 Still `bin_exp.js` files is there please do not commit these files.

2020-11-03 09:15 UTC, plazzy99 commented on JavaScript/math/bin_exp.js
> +/*
remove this file from this pull request.

2020-11-03 15:36 UTC, closed without merging