Create chinese_remainder_theorem.py
HarshCasper/NeoAlgo pull request #1405
Opened 2020-11-10 04:25 UTC by ashu-cybertron

Add it as my contribution

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
from functools import reduce

k = int(input("Enter size of array : ")) 
print("Enter value of coprime divisors :",end=' ')
n=list(map(int,input().split()))
print("Enter value of remainders :",end=' ')
a=list(map(int,input().split()))

def chineserem(n, a):
    sum=0
    pr=reduce(lambda a, b: a*b, n)
    for n_i, a_i in zip(n,a):
        p=pr/n_i
        sum += a_i* muinv(p, n_i)*p
    return sum % pr
def muinv(a, b):
    b0= b
    x0, x1= 0,1
    if b== 1: return 1
    while a>1 :
        q=a// b
        a, b= b, a%b
        x0, x1=x1 -q *x0, x0
    if x1<0 : x1+= b0
    return x1
#n=[2,3,5]
#a=[1,2,4]

    
print("x=",chineserem(n,a))

it is the program of the Chinese remainder system in python please add it as my contribution

2020-11-10 04:41 UTC, ashu-cybertron commented
please check

2020-11-12 18:16 UTC, iamrajiv reviewed
@ashu-cybertron Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

2020-11-14 15:50 UTC, atarax665 requested changes

2020-11-14 15:50 UTC, atarax665 commented on Python/other/chinese_remainder_theorem.py
> +from functools import reduce
Do not use built in functions.

2020-11-14 15:50 UTC, atarax665 commented on Python/other/chinese_remainder_theorem.py
> +print("x=",chineserem(n,a))
Add Sample Input/Output and Time Complexity of your code at the end in commented form.

2020-11-15 21:42 UTC, ashu-cybertron reviewed
please check the changes @atarax665 @iamrajiv

2020-11-16 07:21 UTC, iamrajiv requested changes
@ashu-cybertron Update the Readme.

2020-11-16 07:21 UTC, iamrajiv commented on Python/other/chinese_remainder_theorem.py
> +def mulitply(li):
Fix typo mistake

2020-11-16 15:27 UTC, ashu-cybertron reviewed
it is improved see this @atarax665 @iamrajiv

2020-11-20 18:02 UTC, plazzy99 approved these changes
👍🏻

2020-11-20 18:03 UTC, plazzy99 commented
update readme.md file

2020-11-20 21:56 UTC, ashu-cybertron commented
i have updated readme @atarax665 @iamrajiv  plz merge it and make me assignee

2020-11-21 02:02 UTC, iamrajiv approved these changes

2020-11-21 15:02 UTC, atarax665 approved these changes

2020-11-21 15:03 UTC, merged

2020-11-21 15:04 UTC, atarax665 commented
@all-contributors add @ashu-cybertron  for code :+1: