Add files via upload
HarshCasper/NeoAlgo pull request #1420
Opened 2020-12-02 15:04 UTC by DeagleOfficial

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

C++ Program to generate and display all subsets of a given integer array using a Recursive backtracking approach in O(n) space complexity and O(2^n) time complexity.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-02 17:52 UTC, atarax665 requested changes
Format your code according to [C++ style guide](https://google.github.io/styleguide/cppguide.html). You can use [this](https://www.techiedelight.com/tools/clike).

2020-12-02 17:52 UTC, atarax665 commented on C-Plus-Plus/other/subsets.cpp
> +    cin >> size;
Prompt user to enter the size of the array.

2020-12-02 17:52 UTC, atarax665 commented on C-Plus-Plus/other/subsets.cpp
> +//Sample IO
Use multi-line comment. i.e ```/*............................*/```

2020-12-02 18:18 UTC, DeagleOfficial commented on C-Plus-Plus/other/subsets.cpp
> +//Sample IO
Made the changes, @atarax665

2020-12-04 14:47 UTC, atarax665 approved these changes

2020-12-08 08:06 UTC, charlie219 approved these changes

2020-12-09 10:20 UTC, merged