Ugly Number With Recursion (Addition of Ugly Number Problem #1286)
HarshCasper/NeoAlgo pull request #1424
Opened 2020-12-05 14:22 UTC by ErzaTitania-2001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

Yes

(Write your answer here.)

### Checklist

- [Yes ] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Addition of Ugly Number Problem #1286

2020-12-05 16:06 UTC, iamrajiv requested changes
@ErzaTitania-2001 Do not mix `ArmStrongRecursion.java` and `UglyRecursion.java` programs in the same PR. You can make separate PR for `ArmStrongRecursion.java` program.

2020-12-09 04:06 UTC, ErzaTitania-2001 commented on Java/cp/UglyRecursion.java
> +//finding nth ugly number using recursion
I'm quite new to GitHub. Sorry for the troubles. 
Ugly Problem link : https://github.com/TesseractCoding/NeoAlgo/issues/1286
PDDI Problem link : https://github.com/TesseractCoding/NeoAlgo/issues/1217

2020-12-09 04:16 UTC, ErzaTitania-2001 commented on Java/cp/UglyRecursion.java
> +//finding nth ugly number using recursion
@iamrajiv @atarax665 when is this pull request going to be resolved?

2020-12-09 05:58 UTC, iamrajiv approved these changes

2020-12-09 05:58 UTC, merged

2020-12-09 05:58 UTC, iamrajiv commented
@all-contributors please add @ErzaTitania-2001 for code