Fixed a bug in prime_number.py
HarshCasper/NeoAlgo pull request #1426
Opened 2020-12-08 06:57 UTC by charlie219

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

I noticed an issue with prime_number.py regarding the recursive approach. The condition to check (num==2) must be before then it is actually placed. which resulted in the wrong execution of the program.
For an input of 2, the recursive approach returned `False` which instead should be `True`.

I have also changed my profile link in `CONTRIBUTORS.md` file.

### Checklist

- [Y ] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

None

2020-12-09 16:51 UTC, atarax665 approved these changes

2020-12-09 16:51 UTC, atarax665 commented on Python/math/prime_number.py
> +        return True
Add a line break after this.

2020-12-09 18:35 UTC, charlie219 commented on Python/math/prime_number.py
> +        return True
Line Break Added

2020-12-10 07:31 UTC, iamrajiv requested changes
@charlie219 Do not edit `CONTRIBUTORS.md` file. Contributors are added by the bot when the PR gets merged.

2020-12-10 08:45 UTC, charlie219 commented
@iamrajiv actually I am already added in `CONTRIBUTOR.md` for one of my merged PR, here I have just updated a link of my profile

2020-12-10 13:51 UTC, iamrajiv approved these changes

2020-12-10 13:52 UTC, merged