Bucket Sort added in cpp
HarshCasper/NeoAlgo pull request #1430
Opened 2020-12-08 15:51 UTC by YASH01009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(WoC)

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [N] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Can u pls tell what exactly to do with README.md)

2020-12-08 16:02 UTC, charlie219 commented
@YASH01009 update the `README.md` under C-Plus-Plus folder under **Sorting**. You must add the link to your code.
For further details, refer to PR #1412

2020-12-08 17:44 UTC, YASH01009 commented
I have edited the file.

2020-12-08 18:14 UTC, YASH01009 commented
Should I again make a new pull request after committing changes to the same branch ?? 
Thanks !! I am a bit new to open source.

2020-12-08 18:59 UTC, charlie219 commented
@YASH01009, you don't need to make another PR for the same issue, the changes made will be reflected.

2020-12-10 08:05 UTC, Kajol-Kumari requested changes
Hey @YASH01009 please revise your logic for bucket sort in this code as I am not getting the desire input.

For input 
```
4
9 2 1 10
```
I am getting `9 2 1 10` as output which shouldn't be the case. Also I can see that users can input restricted values only as the value of `k` is fixed here. Can we please make it generalised ?

2020-12-10 08:05 UTC, Kajol-Kumari commented on C-Plus-Plus/sort/bucket_sort.cpp
> +	// cpoy the elts back to arr
please correct the typo here

2020-12-10 08:05 UTC, Kajol-Kumari commented on C-Plus-Plus/sort/bucket_sort.cpp
> +}
leave an extra blank space at the end of the file

2020-12-11 10:26 UTC, YASH01009 commented on C-Plus-Plus/sort/bucket_sort.cpp
> +	// cpoy the elts back to arr
I corrected this typo. I also resolved the error for the aforementioned output.

2020-12-11 10:28 UTC, YASH01009 commented on C-Plus-Plus/sort/bucket_sort.cpp
> +}
I left a blank line at the end. Coming to generalizing, as far as my knowledge is concerned, this is similar to counting sort in constraints, I mean based on the input values we decide the size of the bucket. If you want me still generalize, I will think of some way...

2020-12-12 03:07 UTC, HarshCasper requested changes

2020-12-12 03:07 UTC, HarshCasper commented on C-Plus-Plus/sort/bucket_sort.cpp
> +// Usecase : if all the elements are in a given range
Use Multi-Line Comments instead of Single-Line Comments

2020-12-12 03:07 UTC, HarshCasper commented on C-Plus-Plus/sort/bucket_sort.cpp
> +// average time complexity : O(nlog(n/k)), where k is #buckets
Time and Space Complexity can be mentioned at the end of the Code

2020-12-12 03:07 UTC, HarshCasper commented on C-Plus-Plus/sort/bucket_sort.cpp
> +		sort(bucket[i].begin(), bucket[i].end());
Have a consistent indentation, throughout the Code

2020-12-12 03:07 UTC, HarshCasper commented on C-Plus-Plus/sort/bucket_sort.cpp
> +	int n = arr.size(), k = 10;
Use meaningful variable names. Code Quality is one of the important aspects here. Try using Snake Case or Camel Case to name your variables.

2020-12-12 03:07 UTC, HarshCasper commented on C-Plus-Plus/sort/bucket_sort.cpp
> +}
Have a sample I/O to show the Users, how its being done.

2020-12-27 03:25 UTC, HarshCasper requested changes
Resolve the Merge Conflicts as well.

2020-12-27 03:25 UTC, HarshCasper commented on C-Plus-Plus/sort/bucket_sort.cpp
> +	int n = arr.size(), k = 10;
I don't yet see usage of meaningful variable names.

2020-12-27 03:25 UTC, HarshCasper commented on C-Plus-Plus/sort/bucket_sort.cpp
> +		sort(bucket[i].begin(), bucket[i].end());
No changes made for making the indentation more consistent.

2020-12-31 11:58 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-31 11:58 UTC, closed without merging