Radix Sort added in C, C++, Java
HarshCasper/NeoAlgo pull request #1431
Opened 2020-12-08 18:00 UTC by YASH01009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(WoC)

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

2020-12-09 09:02 UTC, YASH01009 commented
@HarshCasper can you pls have a look at this request and suggest changes? I will accordingly structure all my future PRs. Thanks!!

2020-12-12 03:09 UTC, HarshCasper commented on C-Plus-Plus/sort/radix_sort.cpp
> +// Radix sort is based on counting sort
Use Multi-Line Comments instead of Single-Line Comments. The latter looks cumbersome.

2020-12-12 03:14 UTC, HarshCasper requested changes
Try to follow the same principles in the rest of your implementation as well. 

Moreover, we require every PR to be as atomic as possible. Try to have different PRs for different implementations even if they revolve around the same algorithms.

2020-12-12 03:14 UTC, HarshCasper commented on C-Plus-Plus/sort/radix_sort.cpp
> +// Time complexity : O(n)
Mention Time and Space Complexity at the end of the Code

2020-12-12 03:14 UTC, HarshCasper commented on C-Plus-Plus/sort/radix_sort.cpp
> +// This works bcz of the nature of counting sort
Don't use shorthand words for describing your Code. We cannot expect everyone to understand these shorthand words

2020-12-12 03:14 UTC, HarshCasper commented on C-Plus-Plus/sort/radix_sort.cpp
> +}
Add a newline at the end of the file

2020-12-12 03:14 UTC, HarshCasper commented on C-Plus-Plus/sort/radix_sort.cpp
> +	int ele = pow(10, p);
Use proper variable names by following a convention like Snake Case or Camel Case

2020-12-12 03:14 UTC, HarshCasper commented on C-Plus-Plus/sort/radix_sort.cpp
> +	return 0;
Add a Sample I/O at the end of your Code

2020-12-12 05:02 UTC, YASH01009 commented
I resolved all the suggestions. I will follow all of them from my next PR as well. I will surely make all my future PRs atomic, @HarshCasper Thanks!!

2020-12-12 12:46 UTC, plazzy99 approved these changes
👍🏻

2020-12-14 06:05 UTC, shraddhavp commented
Merge conflicts  to be reolved @YASH01009

2020-12-14 07:04 UTC, YASH01009 commented
I resolved the conflicts @shraddhavp

2020-12-20 06:45 UTC, merged