Added staircase_search
HarshCasper/NeoAlgo pull request #1446
Opened 2020-12-10 16:11 UTC by gargVader

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Program to search for a key in rowwise and columnwise sorted matrix.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1428

2020-12-10 16:59 UTC, iamrajiv requested changes

2020-12-10 16:59 UTC, iamrajiv commented on C-Plus-Plus/search/Staircase_Search.cpp
> +
@gargVader Remove unnecessary line breaks.

2020-12-10 17:21 UTC, iamrajiv approved these changes

2020-12-11 17:56 UTC, atarax665 approved these changes
:+1:

2020-12-11 17:56 UTC, merged

2020-12-11 17:57 UTC, atarax665 commented
@all-contributors please add @gargVader  for code