Yuktybranch1
HarshCasper/NeoAlgo pull request #1456
Opened 2020-12-11 06:21 UTC by yukty2000

…er Of Code

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes, I have  read the Contributing Guidelines on Pull Requests.
### Description
Motivation-
This is another application of the catalan number series - solved using tabulation method.
(Write your answer here)
### Checklist

- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [ Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#1436 Add code for number of binary trees to dp folder for Winter Of Code

2020-12-12 03:39 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +#include <bits/stdc++.h>
Have a beginner description about the Algorithms and the Code Implementation in a Multi-Line Comment.

2020-12-12 04:02 UTC, HarshCasper requested changes

2020-12-12 04:02 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +#include <bits/stdc++.h>
Have a beginner description about the Algorithms and the Code Implementation in a Multi-Line Comment.

2020-12-12 04:02 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +    lli *dp=(lli *)malloc((n+1)*sizeof(lli));
Have all your primary logic in another function. The main() function should strictly serve as your Driver Code.

2020-12-12 04:02 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +        dp[i]=0;
Use proper Variable Names. Prefer using Snake Case or Camel Case convention.

2020-12-12 04:02 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +    /*for(int i=0;i<=n;i++)
Don't use Single and Multi-Line Comments inconsistenly

2020-12-12 06:58 UTC, yukty2000 commented
@HarshCasper sir, I have made the changes.

2020-12-12 12:39 UTC, plazzy99 approved these changes
👍🏻

2020-12-15 16:49 UTC, yukty2000 commented
@HarshCasper  Sir, please merge my pr.

2020-12-27 03:28 UTC, HarshCasper commented
Few more changes: 

- Resolve the Merge Conflicts. 
- Format the Code properly. 
- Use meaningful Variable Names.

2020-12-27 11:21 UTC, yukty2000 commented
Made the changes @HarshCasper .

2020-12-31 11:58 UTC, HarshCasper requested changes

2020-12-31 11:58 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +#include <bits/stdc++.h>
Can you please justify the comments here? Please left align them.

2020-12-31 11:58 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +        for(int loop2=0;loop2<i;loop2++)                        //We loop over the possible splits from 0 to i-1
Keep the Comments above the Line of Code. Not beside them.

2020-12-31 11:58 UTC, HarshCasper commented on C-Plus-Plus/dp/number_of_binary_trees.cpp
> +        */
Justify the Comments. Left align them.

2021-01-01 05:23 UTC, yukty2000 commented
I have left aligned the comments and made the changes @HarshCasper sir.

2021-01-05 10:19 UTC, HarshCasper approved these changes

2021-01-05 10:19 UTC, merged