1711shashank
HarshCasper/NeoAlgo pull request #1457
Opened 2020-12-11 06:46 UTC by 1711shashank

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes I have read the Contributing Guidelines

### Description

Kth largest element in an array
Kth smallest element in an array

### Checklist

- [✔ ] I've read the contribution guidelines.
- [ ✔] I've checked the issue list before deciding what to submit.
- [✔ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

https://github.com/TesseractCoding/NeoAlgo/issues/1425

2020-12-12 04:08 UTC, HarshCasper requested changes

2020-12-12 04:08 UTC, HarshCasper commented on C-Plus-Plus/other/Kth largest element.cpp
> +//Q Kth largest element
Have a beginner description about the Algorithms and the Code Implementation in a Multi-Line Comment.

2020-12-12 04:08 UTC, HarshCasper commented on C-Plus-Plus/other/Kth largest element.cpp
> +//Input
Mention I/O Format at the end of the Code

2020-12-12 04:08 UTC, HarshCasper commented on C-Plus-Plus/other/Kth largest element.cpp
> +    priority_queue<int, vector<int>, greater<int>> minh;
Have all your primary logic in another function. The main() function should strictly serve as your Driver Code.

2020-12-12 04:08 UTC, HarshCasper commented on C-Plus-Plus/other/Kth largest element.cpp
> +    int n, k;
Use proper Variable Names. Prefer using Snake Case or Camel Case convention.

2020-12-12 07:53 UTC, 1711shashank commented
@HarshCasper 
Resolved Changes

2020-12-12 12:38 UTC, plazzy99 requested changes

2020-12-12 12:38 UTC, plazzy99 commented on C-Plus-Plus/other/Kth largest element.cpp
> +// 8
Add time and space complexity

2020-12-12 12:38 UTC, plazzy99 commented on C-Plus-Plus/other/Kth smallest element.cpp
> +// 6
Add time and space complexity

2020-12-12 12:38 UTC, plazzy99 commented on C-Plus-Plus/other/Sort a nearly sorted array.cpp
> +*/
Add time and space complexity

2020-12-12 17:47 UTC, atarax665 requested changes
Input and output should be accompanied with proper messages.
i.e -
```
cout<<"Enter the size of the array : "<<endl;
cin>>size;
```

2020-12-12 17:47 UTC, atarax665 commented on C-Plus-Plus/other/Kth largest element.cpp
> +#include <iostream>
You don't need to add ```#include <iostream>``` if you have already added ```#include <bits/stdc++.h>```. Make the change in both the programs.

2020-12-12 18:10 UTC, 1711shashank commented
Resolved Changes

2020-12-12 18:14 UTC, plazzy99 approved these changes
👍🏻

2020-12-12 19:03 UTC, atarax665 requested changes
Change the file name to ```Kth_largest_element.cpp``` and ```Kth_smallest_element.cpp``` and make the changes in ```README.md``` respectively.

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Kth largest element.cpp
> +    cout<< minHeap.top();
```suggestion
    cout<< "Kth largest element in the array is: "<< minHeap.top();
```

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Kth smallest element.cpp
> +    cout<< maxHeap.top();
```suggestion
    cout<< "Kth smallest element in the array is: "<< maxHeap.top();
```

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Kth largest element.cpp
> +    // a={7, 5, 9, 8, 6, 4, 10}
Remove this comment as you have already added Sample I/O at the end.

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Kth largest element.cpp
> +
```suggestion
    cout<< "Enter the elements of the array: "<<endl;
```

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Kth largest element.cpp
> +size=7 k=3
Format Sample I/O according to the recent changes that you have made in taking input and displaying output. Sample I/O should be exactly same as what would be displayed once the program is run in some IDE. Make changes in both the program.

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Sort a nearly sorted array.cpp
> +/* Sort a nearly sorted (or K sorted) array
Raise a separate PR for this program and do raise an issue for the same if its doesn't exist currently.

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Kth smallest element.cpp
> +    // arr={7, 5, 9, 8, 6, 4, 10}
Remove this comment as you have already added Sample I/O at the end.

2020-12-12 19:03 UTC, atarax665 commented on C-Plus-Plus/other/Kth smallest element.cpp
> +
```suggestion
    cout<< "Enter the elements of the array: "<<endl;
```

2020-12-13 10:37 UTC, plazzy99 approved these changes
👍🏻

2020-12-13 18:15 UTC, atarax665 approved these changes
:+1: Good Work

2020-12-14 17:56 UTC, merged