Knapsack Problem using Greedy Method (WoC)
HarshCasper/NeoAlgo pull request #1482
Opened 2020-12-12 06:00 UTC by k-sashank

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)
The Knapsack Problem is a pretty prominent problem in DSA and Competitive Programming. In this problem, there a bunch of objects with different weights and different profits. There is a limit on the weight which can be included in a Knapsack. The answer must be the highest profit that can be made by including a combination of objects from the ones mentioned in the problem while following the weight constraint.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
Knapsack Problem - Greedy Method (WoC) #1469

2020-12-13 18:43 UTC, iamrajiv requested changes
@k-sashank Add sample input-output. Also, Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

2020-12-14 03:59 UTC, k-sashank commented
@iamrajiv I have made the required changes!
Please review once again!

2020-12-14 08:34 UTC, iamrajiv approved these changes

2020-12-15 09:42 UTC, k-sashank commented
@atarax665 Please review the PR!

2020-12-15 11:44 UTC, HarshCasper requested changes

2020-12-15 11:44 UTC, HarshCasper commented on Python/cp/Knapsack_Problem-Greedy_Method.py
> +def Knapsack(p, w, TW):
Add an Introduction here about the Algorithm

2020-12-15 11:44 UTC, HarshCasper commented on Python/cp/Knapsack_Problem-Greedy_Method.py
> +    pr = []
Use meaningful Variable Names. Not something ambiguous

2020-12-15 11:44 UTC, HarshCasper commented on Python/cp/Knapsack_Problem-Greedy_Method.py
> +p = [10, 5, 15, 7, 6, 18, 3]
Make the input dynamic. Not a Driver Code

2020-12-15 11:44 UTC, HarshCasper commented on Python/cp/Knapsack_Problem-Greedy_Method.py
> +# Sample Input 1:
Give sample I/O in a Multi-Line Comment and not Single-Line

2020-12-15 18:21 UTC, k-sashank commented
@HarshCasper I made the required changes!
Please review again!

2020-12-17 13:21 UTC, k-sashank commented
@HarshCasper I made the required changes!
Please review again!

2020-12-27 03:30 UTC, HarshCasper requested changes
Resolve the Merge Conflicts as well. Rest looks good 👍

2020-12-27 03:30 UTC, HarshCasper commented on Python/cp/Knapsack_Problem-Greedy_Method.py
> +print(total_profit)
Enclose this in a `if __name__ == '__main__'` Block.

2020-12-31 11:59 UTC, HarshCasper commented
Are you still working on it @k-sashank ?

2021-01-05 10:21 UTC, closed without merging