Directed Cycle detection added in C++
HarshCasper/NeoAlgo pull request #1488
Opened 2020-12-12 07:11 UTC by YASH01009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(WoC)

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#1468 Directed Graph Cycle Detection / WoC)

2020-12-15 11:48 UTC, HarshCasper commented on C-Plus-Plus/graphs/DirectedCycleDetection.cpp
> +	for(int i = 0; i < Graph[src].size(); i++)
Add comments here explaining the Code

2020-12-15 11:48 UTC, HarshCasper commented on C-Plus-Plus/graphs/DirectedCycleDetection.cpp
> +	for(int i = 0; i < v; i++)
Add comments here explaining the Code

2020-12-15 11:49 UTC, HarshCasper reviewed
Looks good to me! 

@iamrajiv Maybe you can take a look and merge it

2020-12-15 15:20 UTC, YASH01009 commented
@HarshCasper All the requested changes are done, now !!

2020-12-16 14:02 UTC, iamrajiv requested changes
@YASH01009 Change the variable name `v` to `vertex` and `e` to `edge`.

2020-12-16 15:29 UTC, YASH01009 commented
@iamrajiv changes done !!

2020-12-17 10:47 UTC, iamrajiv approved these changes

2020-12-27 03:31 UTC, merged