Added Cycle Detection in a Directed Graph in Java
HarshCasper/NeoAlgo pull request #1489
Opened 2020-12-12 07:27 UTC by YASH01009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(WoC)

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#1468 Directed Graph Cycle Detection / WoC)

2020-12-15 14:40 UTC, HarshCasper requested changes
Code looks great to me! 

@plazzy99 and @iamrajiv Would love you guys taking a look at it

2020-12-15 14:40 UTC, HarshCasper commented on Java/README.md
> +- [Bubble Sort](sort/BubbleSort.ja
I don't understand this change? Can you revert this to the original hyperlink?

2020-12-15 14:40 UTC, HarshCasper commented on Java/graphs/DirectedCycleDetection.java
> +using dfs. Here, ststus array shows if
Typo Errors like `ststus`. You can try fixing this.

2020-12-15 14:40 UTC, HarshCasper commented on Java/graphs/DirectedCycleDetection.java
> +		int v, e, a, b;
Can you try using more meaningful variable names?

2020-12-15 15:10 UTC, YASH01009 commented
All the requested changes are now done !!

2020-12-16 13:59 UTC, iamrajiv requested changes
@YASH01009 Change the variable name `v` to `vertex` and `e` to `edge`.

2020-12-16 15:34 UTC, YASH01009 commented
@iamrajiv changes done !!

2020-12-17 10:54 UTC, iamrajiv approved these changes

2020-12-17 11:26 UTC, plazzy99 approved these changes
👍🏻

2020-12-17 16:38 UTC, merged

2020-12-17 16:39 UTC, iamrajiv commented
@all-contributors please add @YASH01009 for code