Added N-queens.py
HarshCasper/NeoAlgo pull request #1502
Opened 2020-12-13 05:45 UTC by Pranav016

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added N-queens problem in python.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1475

2020-12-13 06:43 UTC, charlie219 commented
@Pranav016 update the `README.md` file by making a new heading `Backtracking` and add the link to your code there

2020-12-13 07:07 UTC, Pranav016 commented
> @Pranav016 update the `README.md` file by making a new heading `Backtracking` and add the link to your code there

Oh I forgot, I'll do it rn.

2020-12-15 14:46 UTC, HarshCasper requested changes

2020-12-15 14:46 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +# You are given N, and for a given N x N chessboard, find a way to place N queens such that no queen can attack any other queen on the chess board. A queen can be killed when it lies in the same row,
Gosh! That's a very very long comment! 

We usually assume that the Code should be formatted enough to be readable enough. You can try breaking down this Comment into multiple lines.

2020-12-15 14:46 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +# Sample input
Share sample Input and Output at the end of the Code.

2020-12-15 14:46 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +# main
Enclose the main in a proper `if __name__ == '__main__'`

2020-12-15 14:46 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +
Remove extra lines from the Code

2020-12-15 14:46 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +        solution[i][j]=1
Can you try formatting your Code? If you are using an IDE like PyCharm, you can do that automatically via `Ctrl+Alt+L`

2020-12-15 14:46 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +def isSafeToPut(i,j,n,solution):
Add proper Docstrings for functions to explain their functionality

2020-12-15 15:53 UTC, charlie219 commented
@HarshCasper u was assigned similar issue for #1524 
Please have a look on my PR and consider the best solution

2020-12-16 00:24 UTC, Pranav016 commented
Sure, I'll make all the suggested changes. Thanks for the feedback 😄

2020-12-16 00:29 UTC, Pranav016 commented
> @HarshCasper I was assigned similar issue for #1524
> Please have a look at my PR and consider the best solution
> PR #1538

Hello @charlie219 , please refer to this issue #1475 that was raised 4 days ago. Do follow the [CODE_OF_CONDUCT](https://github.com/TesseractCoding/NeoAlgo/blob/master/CODE_OF_CONDUCT.md) and check existing issues before any PRs and respect others time :)

2020-12-17 05:04 UTC, charlie219 commented
@Pranav016 there is already a section for backtracking in `REDME.md`, I think it's useless to create a separate heading or it.
Please update this.

2020-12-17 05:06 UTC, Pranav016 commented
> @Pranav016 there is already a section for backtracking in `REDME.md`, I think it's useless to create a separate heading or it.
> Please update this.

That heading got merged to master after this PR was made. I'll update it..

2020-12-17 05:13 UTC, Pranav016 commented
> > @Pranav016 there is already a section for backtracking in `REDME.md`, I think it's useless to create a separate heading or it.
> > Please update this.
> 
> That heading got merged to master after this PR was made. I rebased then I noticed. I'll update it..

Updated!

2020-12-21 14:17 UTC, HarshCasper requested changes
Tiny changes. Would be good to merge after this 💯

2020-12-21 14:17 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +# Problem statement- You are given N, and for a given N x N chessboard. We have to place all queens such that they are not in the same row, or same column, or the same diagonal of any of the other qu
Modularize this. It is not readable enough. Break down the same using Multiline Strings

2020-12-21 14:17 UTC, HarshCasper commented on Python/backtracking/N-queens.py
> +# 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0
Use Multi-Line String instead of Single Line Comments

2020-12-21 14:24 UTC, charlie219 commented
@HarshCasper, there already exist N-Queens under Backtracking in Python. I don't this its right to add another similar code.

2020-12-21 14:32 UTC, Pranav016 commented
> @HarshCasper, there already exist N-Queens under Backtracking in Python. I don't this its right to add another similar code.

@charlie219 I raised an issue for this problem 10 days ago, refer to #1475 .
I just checked an issue where you commented 8 days ago(same day this PR was made) that you want to work on the same problem, refer to #1524 

Please check existing issues and pull requests to make sure Contribution guidelines are being followed and value other's time as well.

2020-12-22 03:53 UTC, Pranav016 commented
> > @HarshCasper, there already exist N-Queens under Backtracking in Python. I don't this its right to add another similar code.
> 
> @charlie219 I had raised an issue for this problem 10 days ago, refer to #1475 .
> I just checked an issue where you commented 8 days ago(same day this PR was made) that you want to work on the same problem, refer to #1524
> 
> Please check existing issues and pull requests before you make a PR, to make sure Contribution guidelines are being followed and value other's time as well.

@charlie219

2020-12-25 11:52 UTC, closed without merging