Added Generate Pythagorean Triples in C++
HarshCasper/NeoAlgo pull request #1517
Opened 2020-12-13 12:21 UTC by DeagleOfficial

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

My Implementation of a Pythagorean Triples generator using the Rationality relation approach in C++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Addressing #1444

2020-12-13 17:28 UTC, shraddhavp commented
LGTM

2020-12-13 19:43 UTC, atarax665 requested changes

2020-12-13 19:43 UTC, atarax665 commented on C-Plus-Plus/math/Pythagorean_Triples.cpp
> +		n = 1;	//For every m, evaluate a,b,c for all values of n from 1 to m-1
Move the comments above the code, instead of adding them just beside the code.

2020-12-13 19:43 UTC, atarax665 commented on C-Plus-Plus/math/Pythagorean_Triples.cpp
> +	cout << "Enter limit: ";	//Prompts user for input
```suggestion
	cout << "Enter limit (>4) : ";	//Prompts user for input
```

2020-12-13 20:35 UTC, DeagleOfficial commented on C-Plus-Plus/math/Pythagorean_Triples.cpp
> +	cout << "Enter limit: ";	//Prompts user for input
Made the changes, @atarax665

2020-12-14 07:55 UTC, atarax665 approved these changes
LGTM :+1:

2020-12-14 08:45 UTC, merged

2020-12-16 17:25 UTC, DeagleOfficial commented
@atarax665 hey, could you add me to Contributors.md, I'm not added yet.

2020-12-16 17:50 UTC, atarax665 commented
@all-contributors please add @DeagleOfficial for code