Sidhant prs
HarshCasper/NeoAlgo pull request #1518
Opened 2020-12-13 12:22 UTC by Sidhant-Gupta

### Have you read the [Contributing Guidelines on Pull Requests]
Yes,I have read.

(Write your answer here.)

### Description

Dutch National Flag Algorithm- Implemented in C++.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] Dutch National Flag algo -Implemented

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-14 11:03 UTC, Sidhant-Gupta commented
This pr is related to the issue - Dutch National Flag Implementation #1462

2020-12-15 15:07 UTC, HarshCasper commented
Hello @Sidhant-Gupta 

If you are picking problems for CP/DS-Algo Portals, please add their link. 

The above problem is from a [LeetCode Problem](https://leetcode.com/problems/sort-colors/).

2020-12-15 17:07 UTC, Sidhant-Gupta commented
I've made the desired changes. Please review it.

2020-12-21 14:13 UTC, HarshCasper requested changes

2020-12-21 14:13 UTC, HarshCasper commented on C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp
> +//                                 ************************DUTCH_NATIONAL_FLAG ALGORITHM***********************************
Shift the Comments above any lines of code

2020-12-21 14:13 UTC, HarshCasper commented on C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp
> +// Output: [0,1,2]
Shift the sample I/O after the Code ends

2020-12-21 14:13 UTC, HarshCasper commented on C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp
> +                // swap(nums[med],nums[high]);
Remove any instances of commented lines of code. We prefer to have comments over the code but not commented code

2020-12-21 14:13 UTC, HarshCasper commented on C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp
> +  //     space=O(1)
Add a line at the EOF

2020-12-21 14:25 UTC, Sidhant-Gupta commented
I've made all the requested changes. Kindly review @HarshCasper

2020-12-27 03:40 UTC, merged