Added Floyd Warshall And Knight Walk
HarshCasper/NeoAlgo pull request #1521
Opened 2020-12-13 17:32 UTC by atriadhiakri2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
YES
### Description

(Write your answer here.)

### Checklist

- [ Y ] I've read the contribution guidelines.
- [ Y ] I've checked the issue list before deciding what to submit.
- [ Y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-13 17:32 UTC, atriadhiakri2000 commented
@iamrajiv Please Check

2020-12-13 18:53 UTC, iamrajiv requested changes

2020-12-13 18:53 UTC, iamrajiv commented on Python/graphs/Floyd_Warshall_Algorithm.py
> +'''
@atriadhiakri2000 Remove trailing whitespace here.

2020-12-13 18:53 UTC, iamrajiv commented on Python/graphs/Floyd_Warshall_Algorithm.py
> +'''Problem Statement :The problem is to find shortest distances
@atriadhiakri2000 Fix typos here.

2020-12-13 18:53 UTC, iamrajiv commented on Python/graphs/Knight_Walk.py
> +'''Problem Statement :Given a chess board of order N x M and
@atriadhiakri2000 Fix typos here.

2020-12-13 18:53 UTC, iamrajiv commented on Python/graphs/Knight_Walk.py
> +# Importing sys module to initalize the maxsize
@atriadhiakri2000 In this code lot of whitespaces is there please remove the whitespaces.

2020-12-14 05:49 UTC, atriadhiakri2000 commented
@iamrajiv Please do check now

2020-12-14 08:39 UTC, iamrajiv approved these changes

2020-12-15 16:43 UTC, atarax665 requested changes

2020-12-15 16:43 UTC, atarax665 commented on Python/README.md
> +- [Floyd Warshall Algorithm](ds/Floyd_Warshall_Algorithm.py)
```suggestion
- [Floyd Warshall Algorithm](graphs/Floyd_Warshall_Algorithm.py)
```

2020-12-15 16:43 UTC, atarax665 commented on Python/README.md
> +- [Knight Walk](ds/Knight_Walk.py)
```suggestion
- [Knight Walk](graphs/Knight_Walk.py)
```

2020-12-16 05:49 UTC, atriadhiakri2000 commented
@HarshCasper Please check

2020-12-16 10:00 UTC, atriadhiakri2000 commented on Python/README.md
> +- [Knight Walk](ds/Knight_Walk.py)
@HarshCasper Please check

2020-12-16 18:14 UTC, atarax665 approved these changes

2020-12-17 11:05 UTC, merged