Added NQueens in Java
HarshCasper/NeoAlgo pull request #1531
Opened 2020-12-14 07:20 UTC by YASH01009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(NQueens added in Java)

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Issue #1524 is solved here)

2020-12-16 04:46 UTC, HarshCasper requested changes
Rest Code looks good to me! 

Please make these changes, and it will be good to merge 👍

2020-12-16 04:46 UTC, HarshCasper commented on Java/cp/NQueens.java
> +    //write your code here
This Comment is redundant. If you are solving a CP Problem from an Online Portal, prefer to add the link as well.

2020-12-16 04:46 UTC, HarshCasper commented on Java/cp/NQueens.java
> +        for(int col=0; col<board.length; col++) {
Can you put apt comments on your Code for better explainability?

2020-12-16 04:46 UTC, HarshCasper commented on Java/cp/NQueens.java
> +N-Queens problem is a famous problem
If possible, please add further information about the Algorithm

2020-12-16 15:57 UTC, YASH01009 commented
@HarshCasper changes done !!

2020-12-21 14:11 UTC, HarshCasper requested changes

2020-12-21 14:11 UTC, HarshCasper commented on Java/cp/NQueens.java
> +**/
Add a new line at the EOF

2020-12-21 14:11 UTC, HarshCasper commented on Java/cp/NQueens.java
> +                    // backtrack
Can you make the comments more understandable?

2020-12-21 14:11 UTC, HarshCasper commented on Java/cp/NQueens.java
> +                    // place the queen
Can you make the comments more understandable?

2020-12-21 15:55 UTC, YASH01009 commented
@HarshCasper changes done !!

2020-12-27 03:42 UTC, HarshCasper approved these changes

2020-12-27 03:42 UTC, merged