Added NQueens in C++
HarshCasper/NeoAlgo pull request #1534
Opened 2020-12-14 08:11 UTC by YASH01009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Added NQueens in cpp)

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Issue #1524 is solved here)

2020-12-16 04:51 UTC, HarshCasper requested changes
Code Looks good to me 👍

2020-12-16 04:51 UTC, HarshCasper commented on C-Plus-Plus/cp/NQueens.cpp
> +/**
Push the Algorithm Description above the Code

2020-12-16 04:51 UTC, HarshCasper commented on C-Plus-Plus/cp/NQueens.cpp
> +    bool cols[N];
Make the formatting consistent

2020-12-16 04:51 UTC, HarshCasper commented on C-Plus-Plus/cp/NQueens.cpp
> +    for(int col=0; col<n; col++) {
Add some Comments explaining the Code

2020-12-16 15:45 UTC, YASH01009 commented
@HarshCasper changes done !!

2020-12-19 05:36 UTC, shraddhavp commented
conflicts to be resolved @YASH01009

2020-12-21 14:02 UTC, HarshCasper commented
@YASH01009 Please resolve the Conflicts

2020-12-27 03:49 UTC, HarshCasper approved these changes

2020-12-27 03:50 UTC, merged