Boyer-Moore_Majority_Voting_algorithm is added
HarshCasper/NeoAlgo pull request #1556
Opened 2020-12-15 08:25 UTC by barnamensch056

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-15 08:35 UTC, barnamensch056 commented
Please review my code.

2020-12-17 16:37 UTC, atarax665 requested changes
Remove ```.vscode/settings.json``` and  ```Python/graphs/graph.png```. Update the README.md file.

2020-12-17 18:35 UTC, barnamensch056 commented
Is this ok now, Sir?

2020-12-19 04:41 UTC, HarshCasper requested changes

2020-12-19 04:41 UTC, HarshCasper commented on C/cp/BoyerMooreVote.c
> +#include<stdio.h>
Add a description/pitch about the Algorithm that you have implemented

2020-12-19 04:41 UTC, HarshCasper commented on C/cp/BoyerMooreVote.c
> +         }
Format the Code in and around the Operators

2020-12-19 04:41 UTC, HarshCasper commented on C/cp/BoyerMooreVote.c
> +//diver function
Minor Typo. It should be `driver` not `diver`

2020-12-19 04:41 UTC, HarshCasper commented on C/cp/BoyerMooreVote.c
> +        value will become the majority number*/
Make the Comments more consistent and grammatically correct

2020-12-19 07:42 UTC, barnamensch056 commented
Sure I'll make the changes

2020-12-27 03:52 UTC, HarshCasper requested changes
Please format the Code as well.

2020-12-27 03:52 UTC, HarshCasper commented on C/cp/BoyerMooreVote.c
> +#include<stdio.h>
Not done yet. Kindly take a look at other Code Files to better understand the requirement.

2020-12-28 04:17 UTC, barnamensch056 commented
Sure I'll look into the matter

2020-12-31 11:59 UTC, HarshCasper commented
Are you still working on it @barnamensch056 ?

2020-12-31 14:12 UTC, barnamensch056 commented
Yeah I am learning the clang format

2021-01-01 04:28 UTC, HarshCasper approved these changes

2021-01-01 04:30 UTC, merged