Add Knapsack0-1.py
HarshCasper/NeoAlgo pull request #1561
Opened 2020-12-15 11:54 UTC by kartikp36

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

Knapsack 0-1 algorithm in python using dynamic programming.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Second part of issue #1440
First Part: #1537

2020-12-16 05:21 UTC, HarshCasper requested changes

2020-12-16 05:21 UTC, HarshCasper commented on Python/dp/Knapsack0-1.py
> +print("Enter Capacity:")
Enclose this in a `if __name__ == '__main__'`

2020-12-16 05:21 UTC, HarshCasper commented on Python/dp/Knapsack0-1.py
> +    # items= number of items
Kindly make the comments in full sentences

2020-12-16 05:21 UTC, HarshCasper commented on Python/dp/Knapsack0-1.py
> +
Trim extra lines!

2020-12-16 05:21 UTC, HarshCasper commented on Python/dp/Knapsack0-1.py
> +                    # if ith item is included,
Can you try making the Comments more consistent as per grammar (That's not a necessity but it would look good 😅 )

2020-12-16 09:58 UTC, kartikp36 commented
I made the changes, but accidentally merged the latest master to this branch.

2020-12-18 05:56 UTC, kartikp36 commented
@HarshCasper Please review my changes and the mistake.

2020-12-22 06:42 UTC, closed without merging