Strong Number Using Indirect recursion
HarshCasper/NeoAlgo pull request #1564
Opened 2020-12-15 15:23 UTC by ErzaTitania-2001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes
### Description

(Write your answer here.)

### Checklist

- [ yes] I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Math Programs (WoC) #1527

2020-12-15 15:25 UTC, ErzaTitania-2001 commented
@iamrajiv  check my PR for any discrepancies and inform me if any! 
Issue in question Math Programs (WoC) #1527

2020-12-16 04:56 UTC, HarshCasper requested changes

2020-12-16 04:56 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +//checking for a strong number using indirect recursion
Add a description of the Algorithm/Code that you are looking to implement

2020-12-16 04:56 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +    public static int sofd(int n) //recursive function for sum of factorial of digits
Keep the Comments above the Line of Code not beside it

2020-12-16 04:56 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +
Remove redundant lines of code

2020-12-16 04:56 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +        Scanner sc=new Scanner(System.in);
You can try making the User Input more friendly

2020-12-16 04:56 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +    public static int sofd(int n) //recursive function for sum of factorial of digits
Use meaningful function and variable names

2020-12-16 04:56 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +
Add a newline at the end of the file

2020-12-16 05:22 UTC, ErzaTitania-2001 reviewed
Changes done @HarshCasper . Go over it.

2020-12-16 09:45 UTC, HarshCasper requested changes

2020-12-16 09:45 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +
Remove extra lines of code

2020-12-16 09:45 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +/* Sample Input And Output ;
`:` not `;`

2020-12-16 09:45 UTC, HarshCasper commented on Java/math/StrongRecursion.java
> +        if(n==0)
Format the Code with spaces around the Operators

2020-12-16 09:54 UTC, ErzaTitania-2001 reviewed
If any other problems present than indentation, do say @HarshCasper

2020-12-16 14:28 UTC, iamrajiv requested changes
@ErzaTitania-2001 Rename the program to `check_strong_number.java`. Also, Format your code using code formatter.

2020-12-17 10:56 UTC, iamrajiv requested changes
@ErzaTitania-2001 Rename the program `StrongRecursion.java` to `check_strong_number.java`.

2020-12-17 16:53 UTC, iamrajiv approved these changes

2020-12-18 18:15 UTC, ErzaTitania-2001 commented
@iamrajiv , should I close this pull request ? I want to pull another request on another program.

2020-12-18 18:26 UTC, vatsalkesarwani12 approved these changes
👍🏻

2020-12-19 06:12 UTC, ErzaTitania-2001 commented
@HarshCasper  @iamrajiv , I made a commit for the issue Bucket Sort #1590 in the same pull request  by mistake. Any solutions to this problem?

2020-12-20 12:35 UTC, iamrajiv approved these changes

2020-12-20 12:39 UTC, iamrajiv requested changes
@ErzaTitania-2001 Remove the Bucket Sort program from this PR and make another PR for Bucket Sort. Also, whenever you make PR make separate branches for each PR rather than committing to the master branch.

2020-12-20 14:50 UTC, ErzaTitania-2001 commented
@iamrajiv Done. Deleted Bucket_Sort. When is the PR gonna be merged?

2020-12-20 21:11 UTC, iamrajiv approved these changes

2020-12-20 21:11 UTC, merged