Added Breadth First Search in Python.
HarshCasper/NeoAlgo pull request #1569
Opened 2020-12-16 05:46 UTC by Pranav016

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Graph traversal algorithm of Breadth First Search in Python.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1528

2020-12-16 08:57 UTC, shraddhavp commented
Please format it using http://pep8online.com/

2020-12-22 17:29 UTC, iamrajiv requested changes
@Pranav016 Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

2020-12-23 18:26 UTC, charlie219 requested changes

2020-12-23 18:26 UTC, charlie219 commented on Python/graphs/BFS.py
> +# Time Complexity: O(V+E) where V is number of vertices in the graph and E is number of edges in the graph.
Use multi-line Comment instead of single-lined 👍

2020-12-25 11:22 UTC, Pranav016 commented on Python/graphs/BFS.py
> +# Time Complexity: O(V+E) where V is number of vertices in the graph and E is number of edges in the graph.
Done 👍

2020-12-25 11:29 UTC, Pranav016 commented
Can you please review this? @iamrajiv @atarax665 @shraddhavp
Thanks

2020-12-25 12:41 UTC, shraddhavp commented
👍

2020-12-26 08:19 UTC, charlie219 approved these changes
LGTM 👍

2020-12-26 08:53 UTC, iamrajiv requested changes
@Pranav016 Your code is not according to PEP 8 rules.

2020-12-26 15:21 UTC, Pranav016 commented
> @Pranav016 Your code is not according to PEP 8 rules.

Done 😄

2020-12-27 07:18 UTC, iamrajiv approved these changes

2020-12-27 07:18 UTC, merged