Program to print ancestors of given number of BST
HarshCasper/NeoAlgo pull request #1586
Opened 2020-12-16 17:55 UTC by vrandachag

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes!

### Description

Program to print Ancestors of given number of BST in C++.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#1565 issue is solved here)

2020-12-17 05:00 UTC, HarshCasper requested changes

2020-12-17 05:00 UTC, HarshCasper commented on C-Plus-Plus/ds/Ancestors of given number in BST.cpp
> +#include<iostream>
Add a beginner pitch enclosed in a multiline comment detailing about the Code/Algorithm

2020-12-17 05:00 UTC, HarshCasper commented on C-Plus-Plus/ds/Ancestors of given number in BST.cpp
> +#include<iostream>
Name the file properly. Like in your case, it should not be `Ancestors of given number in BST.cpp` but `ancestors_of_given_number_BST.cpp`. Make it look more meaningful and understanding.

2020-12-17 05:00 UTC, HarshCasper commented on C-Plus-Plus/ds/Ancestors of given number in BST.cpp
> +BST *start = NULL; //points to the root node
Put Comments above the Line of Code not beside it

2020-12-17 05:00 UTC, HarshCasper commented on C-Plus-Plus/ds/Ancestors of given number in BST.cpp
> +BST *arr_to_BST(int arr[20], int beg, int end) //function to convert array into Binary Search Tree with shortest height
Put Comments above the Line of Code not beside it

2020-12-17 05:00 UTC, HarshCasper commented on C-Plus-Plus/ds/Ancestors of given number in BST.cpp
> +void Display_BST(BST *ptr) //function to print Binary Search Tree
Put Comments above the Line of Code not beside it

2020-12-17 05:00 UTC, HarshCasper commented on C-Plus-Plus/ds/Ancestors of given number in BST.cpp
> +void level_assign(BST *ptr, int value=0) //function to assign level values to corresponding nodes
Put Comments above the Line of Code not beside it

2020-12-17 05:00 UTC, HarshCasper commented on C-Plus-Plus/ds/Ancestors of given number in BST.cpp
> +		cout<<"\nyoungest:"<<ptr->a;
Use meaningful Console Statements

2020-12-25 07:13 UTC, vrandachag commented
I've done the mentioned changes. Please have a look.

2020-12-29 05:06 UTC, HarshCasper requested changes
Rest looks good! Once done, ping me on Slack and I will merge it.

2020-12-29 05:06 UTC, HarshCasper commented on C-Plus-Plus/ds/ancestors_of_given_number_BST.cpp
> +/*
Can you add a brief summary about what Youngest and Oldest Members means? We usually add a description keeping in mind that the reader knows nothing about the same.

2020-12-29 05:06 UTC, HarshCasper commented on C-Plus-Plus/ds/ancestors_of_given_number_BST.cpp
> +void Display_BST(BST *ptr) //function to print Binary Search Tree
Put Comments above the Line of Code. Not beside it.

2020-12-29 05:06 UTC, HarshCasper commented on C-Plus-Plus/ds/ancestors_of_given_number_BST.cpp
> +}
Add sample I/O at the end of the Code.

2020-12-31 12:01 UTC, HarshCasper commented
LGTM!

2020-12-31 12:01 UTC, merged