Added solution for Count ways to Nth Stair in Java and Python (issue #1455)
HarshCasper/NeoAlgo pull request #1588
Opened 2020-12-16 18:11 UTC by ShubhamPatel33

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description
Oui,This program will give the total number of possible ways to reach Nth stair .
(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
issue #1455 
(Write your answer here.)

2020-12-17 03:34 UTC, shraddhavp commented
why is this issue being solved twice @ShubhamPatel33 ?😁

2020-12-17 04:10 UTC, HarshCasper requested changes

2020-12-17 04:10 UTC, HarshCasper commented on Java/cp/Staircase_problem.java
> +// This program finds the total number of possible combinations that can be used to
Format the Algorithm Description with proper Multi-Line Comments and understanding. Please don't use shorthand because we don't expect everyone to understand them.

2020-12-17 04:10 UTC, HarshCasper commented on Python/cp/staircase_problem.py
> +## This program finds the total number of possible combinations that can be used to
You can use multiline string (triple quotes) instead of using multiple Single Line Comments

2020-12-17 04:10 UTC, HarshCasper commented on Python/cp/staircase_problem.py
> +##Asking for number of steps to find combination.
Enclose this in `if __name__ == '__main__'` block of Code

2020-12-17 04:10 UTC, HarshCasper commented on Python/cp/staircase_problem.py
> +    ##Using Recursion to find the total number of stairs as f(a) = f(a-1) + a(a-2)
I guess `# Python is a Cool Language` and `## Python is a Cool Language` would work the same. Why the use of `##` to enclose comments?

2020-12-17 04:10 UTC, HarshCasper commented on Python/cp/staircase_problem.py
> +##passing stair number to  the function.
The Comments need not to be that detailed. The Code is readable enough. Try to focus on important parts rather than documenting everything.

2020-12-17 04:10 UTC, HarshCasper commented on Python/cp/staircase_problem.py
> +## Output
Enclose it in multiline string.

2020-12-17 04:25 UTC, ShubhamPatel33 commented
> why is this issue being solved twice @ShubhamPatel33 ?😁

I didn't get you .

2020-12-17 06:19 UTC, ShubhamPatel33 commented
Okay @HarshCasper ,the changes will be made

2020-12-18 06:07 UTC, ShubhamPatel33 commented
Thanks for the changes, both files are changed according to your reviews.

2020-12-22 05:56 UTC, HarshCasper commented
Resolve the Merge Conflicts and squash all your commits into one single commit.

Looks good to me!

2020-12-23 05:08 UTC, ShubhamPatel33 commented
I am on it

2020-12-23 05:19 UTC, ShubhamPatel33 commented
Conflict is resolved ,Thanks

2020-12-29 05:08 UTC, HarshCasper approved these changes

2020-12-29 05:09 UTC, merged