Added Matrix-Chain-Multiplication in Python.
HarshCasper/NeoAlgo pull request #1591
Opened 2020-12-17 04:12 UTC by Pranav016

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Dynamic Programming problem of Matrix-Chain-Multiplication in Python.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Solves #1474

2020-12-17 04:43 UTC, HarshCasper requested changes
Code looks good to me 👍

2020-12-17 04:43 UTC, HarshCasper commented on Python/dp/Matrix-Chain-Multiplication.py
> +import sys
Add a beginner pitch enclosed in a multiline string detailing about the Code/Algorithm

2020-12-17 04:43 UTC, HarshCasper commented on Python/dp/Matrix-Chain-Multiplication.py
> +    '''
Better use Docstrings for the purpose. 

```
"""
This is an example of Google style.

Args:
    param1: This is the first param.
    param2: This is a second param.

Returns:
    This is a description of what is returned.

Raises:
    KeyError: Raises an exception.
"""
```

2020-12-17 04:43 UTC, HarshCasper commented on Python/dp/Matrix-Chain-Multiplication.py
> +    for k in range(i, j):
Add proper Comments explaining the Code

2020-12-17 04:43 UTC, HarshCasper commented on Python/dp/Matrix-Chain-Multiplication.py
> +# Sample input-
Enclose this in a Multi-Line String

2020-12-17 04:52 UTC, Pranav016 commented on Python/dp/Matrix-Chain-Multiplication.py
> +    for k in range(i, j):
Sure, I'll add comments.

2020-12-17 04:53 UTC, Pranav016 commented on Python/dp/Matrix-Chain-Multiplication.py
> +    '''
ok 👍

2020-12-25 10:25 UTC, Pranav016 commented
Can you please review this? @iamrajiv @atarax665 @shraddhavp
Thanks

2020-12-31 12:01 UTC, HarshCasper approved these changes

2020-12-31 12:02 UTC, merged