Depth Of Tree
HarshCasper/NeoAlgo pull request #1595
Opened 2020-12-17 06:39 UTC by satyampgt4

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

The is program will give the depth of the binary tree

### Checklist

- [X] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1558

2020-12-17 13:22 UTC, satyampgt4 commented
I request @shraddhavp  @iamrajiv  @Neilblaze to review this PR. Thankyou

2020-12-24 07:52 UTC, satyampgt4 commented
@iamrajiv @atarax665 please review this PR. Thankyou

2020-12-28 04:29 UTC, shraddhavp commented
please resolve the conflicts

2020-12-31 12:08 UTC, HarshCasper requested changes
Remove extra lines of Code. There are a lot of them!

2020-12-31 12:08 UTC, HarshCasper commented on C-Plus-Plus/graphs/Depth_of_tree.cpp
> +    t.insert_data(70);
Don't push static input. Make it dynamic and let the User input the Data

2020-12-31 12:08 UTC, HarshCasper commented on C-Plus-Plus/graphs/Depth_of_tree.cpp
> +
Remove extra lines of Code

2020-12-31 16:50 UTC, satyampgt4 commented
@HarshCasper i have done requested changes please check.

2021-01-01 04:17 UTC, iamrajiv requested changes
@satyampgt4 Add space and time complexity.

2021-01-02 11:19 UTC, satyampgt4 commented
@iamrajiv i have done requested changes please check.

2021-01-03 05:47 UTC, iamrajiv approved these changes

2021-01-03 08:41 UTC, Neilblaze approved these changes
LGTM :+1:

2021-01-03 08:42 UTC, merged