Added stock span problem
HarshCasper/NeoAlgo pull request #1600
Opened 2020-12-17 08:34 UTC by gargVader

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Stock span problem is an interesting application of the stack data structure

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1566

2020-12-18 17:14 UTC, atarax665 requested changes

2020-12-18 17:14 UTC, atarax665 commented on C-Plus-Plus/other/Stock_span_problem.cpp
> +of stock's price on ith day. The span of a stoock's price on a given day i, is the maximum
```suggestion
of stock's price on ith day. The span of a stock's price on a given day i, is the maximum
```

2020-12-18 17:14 UTC, atarax665 commented on C-Plus-Plus/other/Stock_span_problem.cpp
> +
Add link of the problem.

2020-12-18 17:14 UTC, atarax665 commented on C-Plus-Plus/other/Stock_span_problem.cpp
> +/*
Add space and time complexity of your solution.

2020-12-20 13:29 UTC, atarax665 approved these changes
LGTM :+1:

2020-12-21 09:16 UTC, merged

2020-12-21 10:12 UTC, gargVader commented
@shraddhavp Should I add a separate section for stack based problems?

2020-12-21 16:18 UTC, shraddhavp commented
yes you can @gargVader

2020-12-21 16:18 UTC, shraddhavp commented
create a new issue and do it