Added Bridge edge in Graph in python
HarshCasper/NeoAlgo pull request #1603
Opened 2020-12-17 12:03 UTC by atriadhiakri2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ Y ] I've read the contribution guidelines.
- [ Y ] I've checked the issue list before deciding what to submit.
- [ Y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-17 13:51 UTC, atriadhiakri2000 commented
@iamrajiv Please Review my code

2020-12-17 16:59 UTC, iamrajiv requested changes

2020-12-17 16:59 UTC, iamrajiv commented on Python/README.md
> -- [Bridge Edge in Graph](graph/Bridge_Edge_in_Graph.py)
@atriadhiakri2000 Do not remove the program link.

2020-12-17 17:50 UTC, atarax665 requested changes
Update the deleted line in README.md as ```[Bridge Edge in Graph](grapha/Bridge_Edge_in_Graph.py)```

2020-12-17 17:50 UTC, atarax665 commented on Python/graphs/Bridge_Edge_in_Graph.py
>  No of Vertices = 4
Update Sample Input according to the updated code.

2020-12-18 04:58 UTC, atriadhiakri2000 commented
@iamrajiv  Please check
@atarax665  Please check

2020-12-19 17:30 UTC, atarax665 approved these changes

2020-12-20 12:33 UTC, iamrajiv approved these changes

2020-12-20 12:33 UTC, merged