Deque
HarshCasper/NeoAlgo pull request #1627
Opened 2020-12-19 18:06 UTC by satyampgt4

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

It is an implementation of Deque using doubly linked list in c++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

 #1602

2020-12-20 05:09 UTC, HarshCasper requested changes

2020-12-20 05:09 UTC, HarshCasper commented on C-Plus-Plus/ds/Deque.cpp
> +    q.display();
Use Dynamic Input instead of a Driver Code.

2020-12-20 05:09 UTC, HarshCasper commented on C-Plus-Plus/ds/Deque.cpp
> +In this Program we will implement Double Ended Queue (de_que)
Can you add a beginner pitch about Double Ended Queue?

2020-12-20 05:09 UTC, HarshCasper commented on C-Plus-Plus/ds/Deque.cpp
> +
Remove unnecessary lines

2020-12-20 05:09 UTC, HarshCasper commented on C-Plus-Plus/ds/Deque.cpp
> +        n=0;
The Formatting is inconsistent. Try to keep it consistent for better uniformity.

2020-12-24 07:47 UTC, satyampgt4 commented on C-Plus-Plus/ds/Deque.cpp
> +    q.display();
i use the drive code to show how these function will execute

2020-12-27 04:19 UTC, HarshCasper requested changes

2020-12-27 04:19 UTC, HarshCasper commented on C-Plus-Plus/ds/Deque.cpp
> +    q.display();
We need the Driver Code to help the User use the Code. Not to show how the Code is being executed. If not changed, we will not be able to merge this.

2020-12-29 15:40 UTC, Khimit commented
@HarshCasper  can you please assign this to me?? from DWoC

2020-12-31 12:05 UTC, HarshCasper commented
> @HarshCasper can you please assign this to me?? from DWoC

PRs are not meant to be assigned.

2020-12-31 12:06 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-31 12:06 UTC, closed without merging