Added largest rectangular area under histogram
HarshCasper/NeoAlgo pull request #1630
Opened 2020-12-20 06:28 UTC by gargVader

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added C++ program for largest rectangular area under histogram

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1568

2020-12-20 12:44 UTC, iamrajiv approved these changes

2020-12-21 17:07 UTC, atarax665 requested changes

2020-12-21 17:07 UTC, atarax665 commented on C-Plus-Plus/other/Largest_rect_area_under_histogram.cpp
> +	int n; cin >> n;
Prompt user to input to enter number of bars and height of each bar respectively.

2020-12-22 08:48 UTC, shraddhavp commented
conflicts to be  resolved @gargVader

2020-12-22 10:52 UTC, gargVader commented
> conflicts to be resolved @gargVader

Conflicts will be resolved once I get nod on #1661

2020-12-22 18:23 UTC, atarax665 approved these changes

2020-12-23 04:33 UTC, merged