Updated : Automorphic number and Kaprekar number in C
HarshCasper/NeoAlgo pull request #1658
Opened 2020-12-22 06:55 UTC by Tausif121

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

I have added 2  updated programs in C on Automorphic number and Kaprekar number as assigned by @shraddhavp and i have made a separate PR as told by @yashaswibiyahut 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Related Issue: #1643 
Related PR: #1657

2020-12-22 08:47 UTC, shraddhavp commented
@Tausif121  please add time complexities for the programs added

2020-12-22 15:06 UTC, Tausif121 commented
> @Tausif121 please add time complexities for the programs added

@shraddhavp , Time complexity added for both the programs.

2020-12-22 17:25 UTC, iamrajiv requested changes
@Tausif121 Add your program link in `C/README.md` not in `C/math/README.md `. Also, format your code using code formatter.

2020-12-23 04:38 UTC, Tausif121 commented
> @Tausif121 Add your program link in `C/README.md` not in `C/math/README.md `. Also, format your code using code formatter.

@iamrajiv  Now i have updated C/README.md and also formatted my 2 prorams using code editor.
sorry for the mistake, this is my first code contribution

2020-12-23 07:15 UTC, iamrajiv requested changes

2020-12-23 07:15 UTC, iamrajiv commented on C/math/README.md
> +# Programs added by Tausif
@Tausif121 Do not edit this file.

2020-12-23 07:44 UTC, iamrajiv approved these changes

2020-12-23 07:45 UTC, merged

2020-12-23 07:47 UTC, Tausif121 commented
@iamrajiv , so sorry I just realised my mistake and thank you for helping.

2020-12-23 07:52 UTC, iamrajiv commented
@all-contributors please add @Tausif121 for code