Added Largest possible sum of a contiguous subarray
HarshCasper/NeoAlgo pull request #1662
Opened 2020-12-22 12:34 UTC by Siddhant-K-code

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Largest possible sum of a contiguous sub-array using Kadane's Algorithm

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1604 
(Write your answer here.)

2020-12-23 04:32 UTC, shraddhavp commented
LGTM

2020-12-24 18:01 UTC, atarax665 requested changes
Add comments wherever needed, this will help beginners to understand the algorithm used.

2020-12-24 18:01 UTC, atarax665 commented on C-Plus-Plus/dp/Max_Sum_SubArray(Kadane).cpp
> +#include <bits/stdc++.h>
Add a short description of the problem at the top.

2020-12-25 01:30 UTC, Siddhant-K-code commented
Req. Changes done, pls review it now. @atarax665

2020-12-28 02:05 UTC, Siddhant-K-code commented
Maintainers, Pls look review it @iamrajiv

2020-12-28 02:27 UTC, iamrajiv requested changes
@Siddhant-K-code Rename the program to `Max_subarray_sum_constant_space(DP)` because there is already `Max_subarray_sum(DP)` file which has linear time and space complexity. Also, update the README file.

2020-12-28 02:48 UTC, Siddhant-K-code commented
Created PR #1749 , because this PR was creating conflicts while push!

Closing This!

2020-12-28 02:48 UTC, closed without merging