Added round function
HarshCasper/NeoAlgo pull request #1664
Opened 2020-12-22 14:09 UTC by Ritu01-git

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-23 08:30 UTC, iamrajiv requested changes

2020-12-23 08:30 UTC, iamrajiv commented on C/math/stdout.txt
> +DOSBox version 0.74
@Ritu01-git Remove this file.

2020-12-23 11:43 UTC, Ritu01-git commented on C/math/stdout.txt
> +DOSBox version 0.74
@iamrajiv removed  this file.

2020-12-23 19:16 UTC, iamrajiv requested changes
@Ritu01-git Remove `stdout.txt` and `stdout.txt` files they are not relevant.

2020-12-30 17:51 UTC, atarax665 requested changes
Make your forked repo even with the main repo. You can use [this](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) for reference.

2020-12-31 12:12 UTC, HarshCasper commented
@Ritu01-git You don't seem to have worked on an Issue. I am closing the PR in the case because we don't accept PRs with no Issues attached to them. 

Make an Issue and reopen the PR by joining the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and dropping me a message.

2020-12-31 12:12 UTC, closed without merging