Median in a running stream of integers added
HarshCasper/NeoAlgo pull request #1720
Opened 2020-12-26 15:23 UTC by gargVader

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

C++ program for finding median in a running stream of integers added. New section for heaps added (confirmed on slack).

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1631

2020-12-26 15:26 UTC, gargVader commented
Please merge #1601 before this. I think I mistakenly updated my master branch too while making changes in other branch. That's why its showing commits from that branch here. I am really sorry for this mishap

2020-12-31 12:38 UTC, HarshCasper requested changes

2020-12-31 12:38 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +## Heaps based problems
Just mention Heaps

2020-12-31 12:38 UTC, HarshCasper commented on C-Plus-Plus/heaps/Median_in_a_running_stream_of_integers.cpp
> +int main() {
Shift your entire logic to a different function. And use main() just for the Driver Code.

2020-12-31 12:38 UTC, HarshCasper commented on C-Plus-Plus/heaps/Median_in_a_running_stream_of_integers.cpp
> +	double curr = n; // When count of numbers is 1, median is equal to the number itself
Use comments above the LOC. Not beside it.

2020-12-31 17:36 UTC, HarshCasper approved these changes

2020-12-31 17:36 UTC, merged