Changed Readme and Added Euler circuit and Path
HarshCasper/NeoAlgo pull request #1740
Opened 2020-12-27 14:08 UTC by atriadhiakri2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ Y ] I've read the contribution guidelines.
- [ Y ] I've checked the issue list before deciding what to submit.
- [ Y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-27 14:18 UTC, atriadhiakri2000 commented
@iamrajiv @shraddhavp @HarshCasper  Please check my PR

2020-12-27 17:06 UTC, atarax665 requested changes
The code looks good to me, I would like you to just format the code according to our [python code template](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/Code_Template.md) to maintain the code consistency in this repository.

2020-12-27 17:06 UTC, atarax665 commented on Python/graphs/Euler_circuit_and_Path.py
> +from collections import deque
You can import both ```deque and defaultdict``` at once using ```from collections import deque, defaultdict```

2020-12-28 11:34 UTC, atriadhiakri2000 commented
@iamrajiv @shraddhavp @HarshCasper Please check my PR

2020-12-29 17:31 UTC, atarax665 approved these changes
LGTM :+1:

2020-12-30 13:17 UTC, shraddhavp commented
conflicts to be resolved @atriadhiakri2000

2020-12-30 13:34 UTC, iamrajiv approved these changes

2020-12-30 13:34 UTC, merged