Merge Sort in JavaScript
HarshCasper/NeoAlgo pull request #1748
Opened 2020-12-28 02:31 UTC by Siddhant-K-code

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Merge Sort in JavaScript

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1427

2020-12-31 12:30 UTC, HarshCasper requested changes
Tiny change. Ready to merge then 🍾

2020-12-31 12:30 UTC, HarshCasper commented on JavaScript/sort/MergeSort.js
> +array = [4, 8, 7, 2, 11, 1, 3];
Make the input dynamic.

2020-12-31 14:25 UTC, Siddhant-K-code commented on JavaScript/sort/MergeSort.js
> +array = [4, 8, 7, 2, 11, 1, 3];
Fixed! Please Review It Again.

2021-01-01 04:32 UTC, iamrajiv requested changes
@Siddhant-K-code Add space and time complexity.

2021-01-01 05:41 UTC, Siddhant-K-code commented
> @Siddhant-K-code Add space and time complexity.

Done, Pls review @iamrajiv @HarshCasper

2021-01-01 07:20 UTC, iamrajiv approved these changes

2021-01-07 03:37 UTC, HarshCasper approved these changes

2021-01-07 03:37 UTC, merged