Created Circular Queue in C
HarshCasper/NeoAlgo pull request #1761
Opened 2020-12-28 09:18 UTC by iamvs-2002

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes, I have read them.
### Description

(Write your answer here.)
Implemented the circular queue data structure in the C language. 
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1741 
(Write your answer here.)

2020-12-29 03:58 UTC, HarshCasper requested changes

2020-12-29 03:58 UTC, HarshCasper commented on C/ds/circularqueue.c
> +}
Add a new line at the end of the file

2020-12-29 03:58 UTC, HarshCasper commented on C/ds/circularqueue.c
> +    st.rear = -1; //setting the rear pointer to null
Keep Comments above the Line of Code. Not beside them.

2020-12-29 03:58 UTC, HarshCasper commented on C/ds/circularqueue.c
> +// removing a specific node fromt he queue
Typo Errors.

2020-12-29 03:58 UTC, HarshCasper commented on C/ds/circularqueue.c
> +//In the circular queue, in the last node, the front pointer points to the first node.
If you are creating multiple comments, prefer to use multi-line comment.

2020-12-29 03:58 UTC, HarshCasper commented on C/ds/circularqueue.c
> +#include <stdio.h> //headers
Add a beginner pitch about your Code.

2020-12-29 03:58 UTC, HarshCasper commented on C/ds/circularqueue.c
> +}
Add a sample I/O.

2020-12-29 05:54 UTC, iamvs-2002 commented on C/ds/circularqueue.c
> +}
Ohhk

2020-12-29 05:54 UTC, iamvs-2002 commented on C/ds/circularqueue.c
> +// removing a specific node fromt he queue
ooops

2020-12-29 06:20 UTC, iamvs-2002 reviewed
Added the comments and resolved the typo errrors.

2020-12-31 12:25 UTC, HarshCasper requested changes
Code looks good. Make the apt README changes as well, and it would be ready to merge.

2020-12-31 17:01 UTC, iamvs-2002 commented
@HarshCasper Done!

2021-01-01 04:39 UTC, HarshCasper approved these changes

2021-01-01 04:39 UTC, merged

2021-01-06 07:43 UTC, iamvs-2002 commented
@HarshCasper Kindly add the dwoc label as the core team says that the label must be both on the pr and the issue.