Added Stack using Queue program in Cpp
HarshCasper/NeoAlgo pull request #1762
Opened 2020-12-28 09:23 UTC by rahulk32

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Added Stack using Queue program in Cpp)

### Checklist

- [ Y ] I've read the contribution guidelines.
- [ Y ] I've checked the issue list before deciding what to submit.
- [ Y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Issue #1715 is solved here)

2020-12-28 09:32 UTC, rahulk32 commented
This is for DWOC. Thankyou!

2020-12-31 12:24 UTC, HarshCasper requested changes

2020-12-31 12:24 UTC, HarshCasper commented on C-Plus-Plus/stack/stack_using_queue.cpp
> +    s.push(250);
Change static input to dynamic input and take it from the User.

2020-12-31 12:24 UTC, HarshCasper commented on C-Plus-Plus/stack/stack_using_queue.cpp
> +    cout<<"current size of stack: "<<s.size()<<endl;
Make a Switch Statement to take the responses from the User

2020-12-31 12:24 UTC, HarshCasper commented on C-Plus-Plus/stack/stack_using_queue.cpp
> +        q1=q2;
Format your Code with a formatter.

2021-01-09 03:37 UTC, HarshCasper commented
Hi @rahulk32 

Are you still working on it?

2021-01-12 05:58 UTC, HarshCasper commented
Closing this because of no updates.

2021-01-12 05:58 UTC, closed without merging