Lucas Theorem implementation
HarshCasper/NeoAlgo pull request #1775
Opened 2020-12-28 16:46 UTC by Rishikeshrajrxl

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-12-29 05:28 UTC, Rishikeshrajrxl commented
@shraddhavp  can you please help me with these checks, why not successful.

2020-12-29 09:17 UTC, shraddhavp commented
@Rishikeshrajrxl  dont worry it is a deepsource check fail,it is a new feature where implementation is still in progress ,it will soon be fixed ,it is not the error of PR dont worry

2020-12-30 18:20 UTC, Rishikeshrajrxl commented
@atarax665, @shraddhavp please review this PR.

2020-12-30 18:34 UTC, atarax665 requested changes
Add a comment that you have referred to [GFG article](https://www.geeksforgeeks.org/compute-ncr-p-set-2-lucas-theorem/) as the code looks quite similar.

2020-12-30 18:34 UTC, atarax665 commented on Python/math/Lucas Theorem.py
> +def Mod(n, r, p):
Add docstring to explain how this function works.

2020-12-30 18:34 UTC, atarax665 commented on Python/math/Lucas Theorem.py
> +
Remove all these blank lines.

2020-12-30 18:34 UTC, atarax665 commented on Python/math/Lucas Theorem.py
> +Output: 6
Add time and space complexity of the program.

2020-12-30 18:34 UTC, atarax665 commented
Please update Readme.md too.

2020-12-31 13:11 UTC, Rishikeshrajrxl commented
@atarax665, please have a look

2020-12-31 13:27 UTC, plazzy99 approved these changes
👍🏻 
Code looks good to me 


I want to add something,
Contributing to an open-source project like this helps you to learn new things, upskill yourself. 

But if, if you are simply referring to the code from the websites, making few changes to it and submitting them. Then my friend you all are not learning anything and simply wasting the time of raising a pr and asking for a review.

2020-12-31 15:11 UTC, Rishikeshrajrxl commented
> 👍🏻
> Code looks good to me
> 
> I want to add something,
> Contributing to an open-source project like this helps you to learn new things, upskill yourself.
> 
> But if, if you are simply referring to the code from the websites, making few changes to it and submitting them. Then my friend you all are not learning anything and simply wasting the time of raising a pr and asking for a review.

Thanks, @plazzy99  for your feedback, From next time I will keep that in mind and try to implement on my own. Thanks again.

2020-12-31 15:57 UTC, atarax665 requested changes
LGTM, just update the correct README.md.

2020-12-31 15:57 UTC, atarax665 commented on Python/math/README.md
> +[Lucas Theorem](https://github.com/Rishikeshrajrxl/NeoAlgo/blob/rishikeshrajrxl/Python/math/Lucas%20Theorem.py)
You need to update the main [README.md](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/README.md) of Python folder.

2020-12-31 16:11 UTC, atarax665 commented
Update [this](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/README.md) README.md, and revert all the changes made to the README.md of the Math sub-folder.

2020-12-31 16:47 UTC, Rishikeshrajrxl commented
> Update [this](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/README.md) README.md, and revert all the changes made to the README.md of the Math sub-folder.

@atarax665  Done the changes

2021-01-04 03:49 UTC, Rishikeshrajrxl commented
@atarax665, please review

2021-01-05 07:44 UTC, Rishikeshrajrxl commented
@siddharth25pandey  @SKAUL05 , @Abhijit2505  please review this

2021-01-05 15:09 UTC, atarax665 approved these changes

2021-01-05 15:10 UTC, merged