Github Action to Auto-Assign Reviewers to Pull Requests
HarshCasper/NeoAlgo pull request #1779
Opened 2020-12-28 19:14 UTC by nrickles3

Added Github Action to auto-assign HarshCasper, iamrajiv, and atarax665 to pull requests

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added a Github Action to auto-assign reviewers to pull requests.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #1770, https://github.com/TesseractCoding/NeoAlgo/issues/1770

2020-12-28 19:27 UTC, nrickles3 commented
Looks like Github Actions may not have the necessary permissions when working from forked repositories. Receiving this error on the check: "Resource not accessible by integration". Please let me know how you would like me to proceed. @HarshCasper @atarax665

2021-01-01 04:47 UTC, HarshCasper requested changes
The Action looks fine to me. We will merge to see if it actually works as we expected.

2021-01-01 04:47 UTC, HarshCasper commented on .github/auto_assigner_config.yml
> +#    - wip
Please remove all these comments. They are kinda redundant.

2021-01-09 03:36 UTC, HarshCasper approved these changes

2021-01-09 03:37 UTC, merged