Count the number of Set bits of an integer
HarshCasper/NeoAlgo pull request #1784
Opened 2020-12-29 08:51 UTC by Sameera-Aryasomayajula

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-01-12 06:02 UTC, HarshCasper requested changes
Make apt README changes and I will merge it

2021-01-12 06:02 UTC, HarshCasper commented on C-Plus-Plus/other/countsetbit.cpp
> +}
Add a new line at the EOF

2021-01-26 18:09 UTC, atarax665 commented
@Sameera-Aryasomayajula Are you still working on this? Please reply to reopen this PR.

2021-01-27 09:21 UTC, Sameera-Aryasomayajula commented
I am working on this and will make the requested changes.

2021-02-04 14:29 UTC, HarshCasper commented
Closing the PR cause of no updates. Let me know if you would like this to be reopened.

2021-02-04 14:29 UTC, closed without merging