Added counting_sort.cpp which implements Counting Sort for integers for DWOC 2020-21
HarshCasper/NeoAlgo pull request #1808
Opened 2020-12-30 10:53 UTC by Sarthak-9

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Contributed to open source

### Checklist

- [ #] I've read the contribution guidelines.
- [ #] I've checked the issue list before deciding what to submit.
- [ #] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Implemented Count Sort #1776

2020-12-30 17:42 UTC, atarax665 requested changes
Format your code according to [C++ style guide](https://google.github.io/styleguide/cppguide.html).

2020-12-30 17:42 UTC, atarax665 commented on C-Plus-Plus/sort/counting_sort.cpp
> +    long long int max = -32768;
Its better to assign the 1st element of the array (A[0]) as max initially while checking for maximum element in an array.

2020-12-30 17:42 UTC, atarax665 commented on C-Plus-Plus/sort/counting_sort.cpp
> +//
Use multi-line comments instead of single line comments.

2020-12-30 17:42 UTC, atarax665 commented on C-Plus-Plus/sort/counting_sort.cpp
> +    for (long long int i=0; i<max+1; i++){
Add comment before each  loop to explain what it does in the code.

2020-12-30 17:42 UTC, atarax665 commented on C-Plus-Plus/sort/counting_sort.cpp
> +}
Add Sample Input/Output in commented form, refer to any recent merged C++ PR for reference.

2020-12-30 17:43 UTC, atarax665 requested changes

2020-12-30 17:43 UTC, atarax665 commented on C-Plus-Plus/README.md
> +- [Counting Sort](sort/counting_sort.cpp)
Add a blank line after this.

2020-12-30 17:50 UTC, Sarthak-9 commented
I'll resolve these soon.

2020-12-31 16:59 UTC, atarax665 requested changes
Format the code according to [C++ style guide](https://google.github.io/styleguide/cppguide.html).

2020-12-31 18:14 UTC, Sarthak-9 commented
> Format the code according to [C++ style guide](https://google.github.io/styleguide/cppguide.html).

Could you please elaborate a bit. I have made some changes but still not sure.

2021-01-01 04:02 UTC, iamrajiv requested changes
@Sarthak-9 Your code is not formatted properly. Format like this

```c++
/*
 Created by Sarthak-9 on 30-12-2020.
 Count Sort Algorithm for Sorting an array of small integers quickly.

 Worst complexity: O(n+k)
 Average complexity: O(n+k)
 Space complexity: O(n+k)
 where n is the number of elements in input array and k is the range of input.
*/

#include <iostream>

using namespace std;

int Max(long long int A[], long long int n) {
	long long int max = A[0];

	// finds the maximum element of the array
	for (long long int i = 0; i < n; i++) {
		if (A[i] > max) {
			max = A[i];
		}
	}
	return max;
}

void CountSort(long long int A[], long long int n) {
	long long int max = Max(A, n);
	int* count = new int [max + 1];

	// initializes the count array with all elements to zero
	for (long long int i = 0; i < max + 1; i++) {
		count[i] = 0;
	}

	// updates the count array with frequencies of given numbers
	for (long long int i = 0; i < n; i++) {
		count[A[i]]++;
	}

	long long int i = 0;
	long long int j = 0;

	// updates A with sorted elements
	while (j < max + 1) {
		if (count[j] > 0) {
			A[i++] = j;
			count[j]--;
		} else {
			j++;
		}
	}

	delete [] count;
}

int main() {

	long long int n;
	long long int A[100000];
	cout << "Enter the size of array" << endl;
	cin >> n;
	cout << "Enter the elements" << endl;

	// inputs numbers from the user
	for (long long int i = 0; i < n; i++) {
		cin >> A[i];
	}

	CountSort(A, n);

	cout << "The sorted array is :" << endl;

	// prints the sorted array
	for (long long int i = 0; i < n; i++) {
		cout << A[i] << " ";
	}
	cout << endl;
	return 0;
}

/*
  Input:
  Enter the size of array
  10
  Enter the elements
  45 86 27 38 59 12 86 72 125 38

  Output:
  The sorted array is :
  12 27 38 38 45 59 72 86 86 125
*/
```

2021-01-01 17:01 UTC, Sarthak-9 commented
Please review

2021-01-01 17:43 UTC, atarax665 requested changes
Your current implementation won't work for negative integers, please modify your code for standard array input.

2021-01-03 09:17 UTC, Sarthak-9 commented
I optimized the solution for negative numbers. Please review .

2021-01-03 18:40 UTC, Sarthak-9 commented
@atarax665 Please review

2021-01-07 05:39 UTC, Sarthak-9 commented
> @atarax665 @shraddhavp Please review

Any changes?

2021-01-07 10:39 UTC, iamrajiv approved these changes

2021-01-12 18:07 UTC, atarax665 approved these changes
Resolve the conflict ASAP so that I can merge this PR.

2021-01-12 20:46 UTC, Sarthak-9 commented
@atarax665 Conflicts resolved

2021-01-12 20:48 UTC, merged