Added bankers algorithm in java
HarshCasper/NeoAlgo pull request #1819
Opened 2020-12-30 14:41 UTC by shraiyya

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Pull request corresponding to issue number #1806 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

2021-01-01 05:12 UTC, HarshCasper requested changes

2021-01-01 05:12 UTC, HarshCasper commented on Java/Operating System/banker.java
> +import java.util.Scanner;
Change the Directory name from `Operating System` to `Operating-System`

2021-01-01 05:12 UTC, HarshCasper commented on Java/Operating System/banker.java
> +class algorithm //class for calculation and display
Comments don't have to be very layman. We all understand what work does a class do.

2021-01-01 05:12 UTC, HarshCasper commented on Java/Operating System/banker.java
> +	System.out.println("THE MAXIMUM RESOURCES MATRIX IS AS FOLLOWS :");
Follow a consistent indentation

2021-01-01 05:12 UTC, HarshCasper commented on Java/Operating System/banker.java
> +for (int i = 0 ; i < p ; i++) {
Inconsistent indentation!

2021-01-01 05:12 UTC, HarshCasper commented on Java/Operating System/banker.java
> +            need[i][j] = max[i][j] - allocation[i][j]; // Need of instance = maxm instance -allocated instance
Use comments above the line of code, not beside them

2021-01-01 10:12 UTC, shraiyya commented
I am done with the changes. Please review it again.

2021-01-02 17:45 UTC, atarax665 requested changes
Remove the Huffman encoding program, you may have a separate PR for this.

2021-01-03 07:13 UTC, iamrajiv requested changes
@shraiyya Add space and time complexity. Also, try to give as many comments about the code.

2021-01-03 07:13 UTC, iamrajiv commented on Java/README.md
> +-  [Banker's Algorithm](Operating%20System/banker.java)
@shraiyya This link is not working. Update this to  `-  [Banker's Algorithm](Operating-System/banker.java)`.

2021-01-03 07:13 UTC, iamrajiv commented on Java/Operating-System/banker.java
> +import java.util.Scanner;
@shraiyya Add description about Banker's algorithm.

2021-01-03 07:13 UTC, iamrajiv commented on Java/Operating-System/banker.java
> +                avail[i] = res[i] - allocation[j][i];
@shraiyya You can add a comment here about `Checking for available resources inline`.

2021-01-04 16:58 UTC, atarax665 approved these changes

2021-01-04 17:32 UTC, iamrajiv approved these changes

2021-01-04 17:33 UTC, merged

2021-01-06 09:23 UTC, shraiyya commented
Can you please label this pull request as DWOC?

2021-01-13 06:37 UTC, shraiyya commented
Please add the level of the PR for DWOC