commit -m "Benjamin Bulb code completed"
HarshCasper/NeoAlgo pull request #1840
Opened 2020-12-31 16:09 UTC by shivangi00

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description
Submitting code for issue #1668 in folder /Java/other
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-01-01 05:02 UTC, HarshCasper requested changes

2021-01-01 05:02 UTC, HarshCasper commented on Java/other/BenjaminBulbs.java
> +    public static void main(String args[]){
Shift all the primary Code Logic to another function. `main()` is primarily used for the driver code purpose.

2021-01-01 05:02 UTC, HarshCasper commented on Java/other/BenjaminBulbs.java
> +*/
Add a link to the Problem because it looks like from some online Code Portal.

2021-01-02 17:49 UTC, atarax665 commented
@shivangi00 Are you still working on this?

2021-01-02 18:42 UTC, shivangi00 commented
> @shivangi00 Are you still working on this?

Yes I am.

2021-01-05 08:30 UTC, shivangi00 commented
I am creating a new PR for this with all needed changes.

2021-01-05 08:30 UTC, closed without merging