add a new file ratInAMaze
HarshCasper/NeoAlgo pull request #1882
Opened 2021-01-02 05:37 UTC by nayanajain

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-01-03 13:48 UTC, nayanajain commented
updated readme file as well...please merge my code.

2021-01-07 03:46 UTC, HarshCasper requested changes
Do these changes as well: 

- Remove extra lines of code 
- Format the Code to make it look readable
- Put Comments above the Code, not beside it

2021-01-07 03:46 UTC, HarshCasper commented on C-Plus-Plus/cp/ratInAMaze.cpp
> + 0 denotes that the mouse cannot reach at that point. */
Can you add more details about the Problem here 😅 

Also if possible add a Problem Link on some Online Coding Platform

2021-01-07 03:46 UTC, HarshCasper commented on C-Plus-Plus/cp/ratInAMaze.cpp
> +    int m, n;
Use meaningful variable names

2021-01-07 13:10 UTC, nayanajain commented
done the requested changes

2021-01-12 05:30 UTC, HarshCasper requested changes

2021-01-12 05:30 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Next Largest Permutation](cp/NextPermutation.cpp)
Why so many README changes?

2021-01-12 05:30 UTC, HarshCasper commented on C-Plus-Plus/cp/ratInAMaze.cpp
> +
Remove extra lines of code

2021-01-12 05:30 UTC, HarshCasper commented on C-Plus-Plus/cp/ratInAMaze.cpp
> +//mpving in right direction
Can you remove the typos? Also properly format the Comments to make them look meaningful

2021-01-21 02:10 UTC, HarshCasper requested changes
Remove unnecessary lines of Code

2021-01-21 02:10 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Next Largest Permutation](cp/NextPermutation.cpp)
The Question still remains.

2021-01-21 06:33 UTC, nayanajain commented
I have added only a single line (rat in a maze) in the Readme file ..I am
not able to understand  your change request

On Thu, 21 Jan 2021, 7:41 am Harsh Bardhan Mishra, <notifications@github.com>
wrote:

> *@HarshCasper* requested changes on this pull request.
>
> Remove unnecessary lines of Code
> ------------------------------
>
> In C-Plus-Plus/README.md
> <https://github.com/TesseractCoding/NeoAlgo/pull/1882#discussion_r561474509>
> :
>
> > +- [ArraySub](cp/ARRAYSUB.cpp)
> +- [Suduko Solver](cp/SudukoSolver.cpp)
> +- [Josephus Problem](cp/Josephus.cpp)
> +- [NQueens](cp/NQueens.cpp)
> +- [rat in a maze](cp/ratInAMaze.cpp)
> +- [Longest Subarray with Zero Sum](cp/ZeroSum.cpp)
> +- [Next Largest Permutation](cp/NextPermutation.cpp)
>
> The Question still remains.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TesseractCoding/NeoAlgo/pull/1882#pullrequestreview-572929213>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL7HKZGFCQG7JKYY2E7G22LS26ELHANCNFSM4VQZYQ3A>
> .
>

2021-01-21 06:38 UTC, nayanajain commented
If my pr not gets merged, will I get points for issue??please clear my query
Thank you

On Thu, 21 Jan 2021, 12:03 pm Nayana Jain, <nayanajain854@gmail.com> wrote:

> I have added only a single line (rat in a maze) in the Readme file ..I am
> not able to understand  your change request
>
> On Thu, 21 Jan 2021, 7:41 am Harsh Bardhan Mishra, <
> notifications@github.com> wrote:
>
>> *@HarshCasper* requested changes on this pull request.
>>
>> Remove unnecessary lines of Code
>> ------------------------------
>>
>> In C-Plus-Plus/README.md
>> <https://github.com/TesseractCoding/NeoAlgo/pull/1882#discussion_r561474509>
>> :
>>
>> > +- [ArraySub](cp/ARRAYSUB.cpp)
>> +- [Suduko Solver](cp/SudukoSolver.cpp)
>> +- [Josephus Problem](cp/Josephus.cpp)
>> +- [NQueens](cp/NQueens.cpp)
>> +- [rat in a maze](cp/ratInAMaze.cpp)
>> +- [Longest Subarray with Zero Sum](cp/ZeroSum.cpp)
>> +- [Next Largest Permutation](cp/NextPermutation.cpp)
>>
>> The Question still remains.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/TesseractCoding/NeoAlgo/pull/1882#pullrequestreview-572929213>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AL7HKZGFCQG7JKYY2E7G22LS26ELHANCNFSM4VQZYQ3A>
>> .
>>
>

2021-01-21 09:01 UTC, closed without merging