Problem Solved of Rat in a maze
HarshCasper/NeoAlgo pull request #1883
Opened 2021-01-02 06:23 UTC by Rajat-Jain29

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-01-07 03:43 UTC, HarshCasper requested changes
Code looks great. Maybe @iamrajiv and @atarax665 would like to take a look. 

Make apt README changes as well. And change the file name from `Rat in a maze.cpp` to `rat_in_maze.cpp`

2021-01-07 03:43 UTC, HarshCasper commented on C-Plus-Plus/cp/Rat in a maze.cpp
> +/* C++ program to solve Rat in
Describe the Problem in detail. If possible add a Problem Link on some Online Coding Portal.

2021-01-07 10:41 UTC, iamrajiv requested changes
@Rajat-Jain29 Add sample input-output, space and time complexity. Also, update the README file and rename the program to `rat_in_a_maze.cpp `.

2021-01-11 17:41 UTC, atarax665 commented
@Rajat-Jain29 Are you still working on this PR? Do the suggested changes ASAP.

2021-01-30 04:01 UTC, HarshCasper commented
Closing the PR because of no updates.

2021-01-30 04:01 UTC, closed without merging