Implemented Sprague Grundy Theorem on Strings
HarshCasper/NeoAlgo pull request #1885
Opened 2021-01-02 07:40 UTC by KartikeySharma

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Sprague-Grundy Theorem says that in a composite game in which 2 players A and B play, if both A and B play optimally (i.e., they don’t make any mistakes), then the player starting first is guaranteed to win if the XOR of the grundy numbers of position in each sub-games at the beginning of the game is non-zero. Otherwise, if the XOR evaluates to zero, then player A will lose definitely, no matter what.

### Checklist

- [Tick] I've read the contribution guidelines.
- [Tick] I've checked the issue list before deciding what to submit.
- [Tick] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #1701

2021-01-02 07:40 UTC, KartikeySharma commented
Pls review @atarax665

2021-01-06 16:00 UTC, KartikeySharma commented
Pls check @atarax665

2021-01-06 17:35 UTC, atarax665 requested changes
Format your code according to C++ style guide. You may use [this](https://techiedelight.com/tools/clike) for it.

2021-01-06 17:35 UTC, atarax665 commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> +    	cout<<"Player 1";
```suggestion
    	cout<<"Player 1 wins.";

```

2021-01-06 17:35 UTC, atarax665 commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> +    	cout<<"Player 2";
```suggestion
    	cout<<"Player 2 wins";

```

2021-01-06 17:35 UTC, atarax665 commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> +    cin>>a>>y;
Prompt user to input the required data.

2021-01-06 18:36 UTC, KartikeySharma commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> +    	cout<<"Player 1";
ok

2021-01-06 18:36 UTC, KartikeySharma commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> +    cin>>a>>y;
ok

2021-01-06 18:37 UTC, KartikeySharma commented
Pls review @atarax665

2021-01-08 17:10 UTC, atarax665 requested changes

2021-01-08 17:10 UTC, atarax665 commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> +spraguegrundy	// Main string
Update the Sample Input/Output according to the updated code.

2021-01-08 17:10 UTC, atarax665 commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> + -> The first player who can't remove a substring loses. */
Add a line break after this line.

2021-01-10 12:18 UTC, KartikeySharma commented
@atarax665 Pls review. I have other PRs to submit too. Pls, understand as it has been 2 days since you last replied.

2021-01-10 12:54 UTC, atarax665 commented
> @atarax665 Pls review. I have other PRs to submit too. Pls, understand as it has been 2 days since you last replied.

You haven't resolved the last suggested changes yet. Please do the suggested changes ASAP and request a review.

2021-01-10 13:48 UTC, KartikeySharma commented
Pls have a look now @atarax665

2021-01-10 14:09 UTC, atarax665 requested changes
Also resolve the merge conflict so that I can merge this PR.

2021-01-10 14:09 UTC, atarax665 commented on C-Plus-Plus/dp/Sprague_Grundy_Theorem.cpp
> +Sample Input:
Sample Input/Output should be exactly whats shows on the screen when the program is run.
![output](https://user-images.githubusercontent.com/29673671/104125232-7097a000-537b-11eb-9d06-a1b85fa2c122.PNG)
Format it this way.

2021-01-11 17:04 UTC, atarax665 approved these changes
I have made the appropriate changes as it was just a minor one, please make sure to resolve such minor issues ASAP so that one of the maintainer can review and merge the PR.

2021-01-11 17:05 UTC, atarax665 commented
Resolve the conflict ASAP so that I can merge this PR.

2021-01-12 06:42 UTC, KartikeySharma commented
I don't know how this conflict arose. Could you please help me in understanding as I have never encountered such an error before...

2021-01-12 06:44 UTC, KartikeySharma commented
Resolved the issue @atarax665 . Pls merge it . Thanks :)

2021-01-12 17:58 UTC, atarax665 commented
:+1:

2021-01-12 17:58 UTC, merged

2021-01-15 11:52 UTC, KartikeySharma commented
Pls add DWOC tag @atarax665 .. i forgot to mention it earlier