Python program implementation for Counting sort
HarshCasper/NeoAlgo pull request #1892
Opened 2021-01-02 18:00 UTC by sahebsunny

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

counting sort is an algorithm for sorting a collection of objects according to keys that are small integers.
Worst complexity: n+r
Average complexity: n+r
Space complexity: n+r

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1772
I want to keep contributing to NeoAlgo.
Thank you.

2021-01-09 04:17 UTC, HarshCasper requested changes

2021-01-09 04:17 UTC, HarshCasper commented on Python/sort/Counting_Sort.py
> +# Data structure: Array
We don't need to mention them

2021-01-09 04:17 UTC, HarshCasper commented on Python/sort/Counting_Sort.py
> +# Space complexity: n+r
Push them to the bottom of the Code

2021-01-09 04:17 UTC, HarshCasper commented on Python/sort/Counting_Sort.py
> +"""
Add a new line at the end of the Code

2021-01-09 04:17 UTC, HarshCasper commented on Python/sort/Counting_Sort.py
> +def counting_Sort(arr):
If possible add a Docstring for your Python function.

2021-01-09 04:17 UTC, HarshCasper commented on Python/sort/Counting_Sort.py
> +print(lst)
Enclose this in a main function

2021-01-11 16:28 UTC, atarax665 commented
@sahebsunny Closing this PR due to inactivity, comment if you are still working on this PR.

2021-01-11 16:28 UTC, closed without merging