Add k-prefix Problem to CP
HarshCasper/NeoAlgo pull request #1906
Opened 2021-01-03 19:20 UTC by Bharati2612

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given a list of integers nums and an integer k, return the maximum possible i where nums[0] + nums[1] + ...  + nums[i] ≤ k. Return -1 if no valid i exists.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue number #1905

2021-01-04 09:23 UTC, srimani-programmer commented
@Bharati2612 Your PR has a conflict with the base branch, please make the PR properly.

2021-01-05 08:34 UTC, Bharati2612 commented
> @Bharati2612 Your PR has a conflict with the base branch, please make the PR properly.

@srimani-programmer Done

2021-01-09 03:54 UTC, HarshCasper requested changes

2021-01-09 03:54 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +
I don't see the README update for `Partition_Problem.cpp`

2021-01-09 03:54 UTC, HarshCasper commented on C-Plus-Plus/cp/K_Prefix.cpp
> +//K Prefix
Don't use Single-Line Comments and Multi-Line Comments inconsistently.

2021-01-09 03:54 UTC, HarshCasper commented on C-Plus-Plus/cp/K_Prefix.cpp
> +*/
Add a new line at the End of Code

2021-01-09 03:54 UTC, HarshCasper commented on C-Plus-Plus/cp/K_Prefix.cpp
> +}
Format the Code aptly using Clang.

2021-01-09 03:54 UTC, HarshCasper commented on C-Plus-Plus/dp/Matrix_Chain_Multiplication.cpp
>  */
Add a new line at the end of the Code

2021-01-11 17:40 UTC, atarax665 commented
@Bharati2612 Are you still working on this PR?

2021-01-30 04:01 UTC, HarshCasper commented
Closing the PR because of no updates.

2021-01-30 04:01 UTC, closed without merging