Program to convert BST to Greater Sum Tree
HarshCasper/NeoAlgo pull request #1928
Opened 2021-01-04 17:06 UTC by vrandachag

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes!

### Description

Given BST is transformed into greater sum tree where each node contains sum of all nodes greater than that node.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1726

2021-01-05 11:06 UTC, HarshCasper requested changes
Code looks good to me 👍 

Maybe @iamrajiv can take a look. A tiny change has been suggested. Along with the same, please make the README changes as well.

2021-01-05 11:06 UTC, HarshCasper commented on C-Plus-Plus/ds/BST_to_Greater_Sum_Tree.cpp
> +  return 0;
Incorrect indentation

2021-01-05 14:50 UTC, vrandachag commented
Changes done!
Please have a look.

2021-01-05 14:56 UTC, HarshCasper commented
I don't see the README changes.

2021-01-05 16:02 UTC, iamrajiv requested changes
@vrandachag Add space and time complexity. Also, update the README file.

2021-01-05 16:02 UTC, iamrajiv commented on C-Plus-Plus/ds/BST_to_Greater_Sum_Tree.cpp
> +		int mid = (beg+end)/2;
@vrandachag Please avoid this technique to find the mid element since this can cause an integer overflow. Use this `int mid = beg + ((end - beg) / 2);`.

2021-01-05 16:02 UTC, iamrajiv commented on C-Plus-Plus/ds/BST_to_Greater_Sum_Tree.cpp
> +/*
@vrandachag Add problem link here.

2021-01-05 16:02 UTC, iamrajiv commented on C-Plus-Plus/ds/BST_to_Greater_Sum_Tree.cpp
> +Binary Search Tree after conversion
@vrandachag You can return the inorder traversal of the given tree.

2021-01-09 03:48 UTC, HarshCasper commented
Are you working on it @vrandachag ?

2021-01-09 03:54 UTC, vrandachag commented
@HarshCasper Yes! I'll update it by today.

2021-01-09 07:24 UTC, vrandachag commented on C-Plus-Plus/ds/BST_to_Greater_Sum_Tree.cpp
> +/*
I don't think I have a problem link.

2021-01-12 05:32 UTC, HarshCasper commented
LGTM!

2021-01-12 05:32 UTC, merged