Stacks
HarshCasper/NeoAlgo pull request #1930
Opened 2021-01-04 18:27 UTC by atriadhiakri2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ Y ] I've read the contribution guidelines.
- [ Y ] I've checked the issue list before deciding what to submit.
- [ Y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-01-05 04:29 UTC, atriadhiakri2000 commented
@iamrajiv  Please check

2021-01-05 12:08 UTC, plazzy99 approved these changes
👍🏻 
Always, Try adding 1 pr for 1 issue

2021-01-05 12:20 UTC, atriadhiakri2000 commented
> 👍🏻
> Always, Try adding 1 pr for 1 issue

All right Bro  👍🏻

2021-01-05 16:04 UTC, iamrajiv requested changes
@atriadhiakri2000 Your codes are not following PEP 8 standard. Format all your code according to PEP 8 standard.

2021-01-05 17:49 UTC, atarax665 requested changes

2021-01-05 17:49 UTC, atarax665 commented on Python/other/Check_for_balanced_parentheses.py
> +
One blank line is enough, add the problem link from any coding website too.

2021-01-05 17:49 UTC, atarax665 commented on Python/other/Check_for_balanced_parentheses.py
> +    print("The parentheses are balnced")
```suggestion
    print("The parentheses are balanced")
```

2021-01-05 17:49 UTC, atarax665 commented on Python/other/Check_for_balanced_parentheses.py
> +    print("The parentheses are not balnced")
```suggestion
    print("The parentheses are not balanced")
```

2021-01-05 17:49 UTC, atarax665 commented on Python/other/Check_for_balanced_parentheses.py
> +    The parentheses are balnced
```suggestion
    The parentheses are balanced
```

2021-01-05 17:49 UTC, atarax665 commented on Python/other/Check_for_balanced_parentheses.py
> +
Remove this extra line break.

2021-01-05 17:49 UTC, atarax665 commented on Python/other/Next_Greater_Element.py
> +    Enter the brackets: {{[[[()]]]}}{(())}
Update the Sample I/O.

2021-01-06 04:25 UTC, atriadhiakri2000 commented
@iamrajiv Please check

2021-01-15 17:02 UTC, atarax665 requested changes
Move ```Implement_Queue_using_Stack.py``` and ```Implement_Stack_using_Queue.py``` to the ```ds folder```. Do the suggested changes ASAP so that I can merge  this PR.

2021-01-30 04:01 UTC, HarshCasper commented
Closing the PR because of no updates.

2021-01-30 04:01 UTC, closed without merging