Count inversion in Java
HarshCasper/NeoAlgo pull request #1931
Opened 2021-01-04 18:34 UTC by pranjalshinde

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

As assigned by @iamrajiv for issue #1778, I have added the solution for the Counting Inversion problem using modified merge sort algorithm

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1778

2021-01-05 15:44 UTC, iamrajiv requested changes
@pranjalshinde Add sample input-output, space and time complexity.

2021-01-05 15:45 UTC, iamrajiv commented on Java/README.md
> +- [Count INversion](sort/CountInversion.java)
@pranjalshinde Update this to `- [Count Inversion](sort/CountInversion.java)`.

2021-01-12 09:23 UTC, srimani-programmer requested changes

2021-01-12 09:23 UTC, srimani-programmer commented on Java/sort/CountInversion.java
> +
@pranjalshinde please remove the extra spaces and also add the comments that could understand by everyone.

2021-01-12 09:23 UTC, srimani-programmer commented on Java/sort/CountInversion.java
> +
Remove extra spaces like this.! Add the necessary comments to your code.

2021-01-12 09:23 UTC, srimani-programmer commented on Java/sort/CountInversion.java
> +
Remove extra line.

2021-01-12 09:23 UTC, srimani-programmer commented on Java/sort/CountInversion.java
> +
Remove the extra line.

2021-01-30 04:02 UTC, HarshCasper commented
Closing the PR because of no updates.

2021-01-30 04:02 UTC, closed without merging