Created String Palindrome program in Java
HarshCasper/NeoAlgo pull request #1943
Opened 2021-01-05 17:27 UTC by iamvs-2002

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
I have implemented a java program to check if a string entered by the user is a palindrome or not.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1925 
(Write your answer here.)

2021-01-06 13:46 UTC, srimani-programmer commented
@iamvs-2002 Your branch has some conflicts, please check it at your end make the PR appropriately.

2021-01-06 13:48 UTC, srimani-programmer requested changes
Along with Conflicts, Your code will take O(n) time complexity where you can solve it in O(n/2) time only. please have a look at it and modify it appropriately.

2021-01-06 14:00 UTC, iamvs-2002 commented
> Along with Conflicts, Your code will take O(n) time complexity where you can solve it in O(n/2) time only. please have a look at it and modify it appropriately.

Oh, I see. Thanks for pointing that out!

2021-01-06 17:59 UTC, atarax665 requested changes

2021-01-06 17:59 UTC, atarax665 commented on Java/other/Palindrome.java
> +Time Complexity = O(n/2)
Add space complexity too.

2021-01-06 17:59 UTC, atarax665 commented on Java/other/Palindrome.java
> +        for (int i = 0; i < (n)/2; i++)
```suggestion
        for (int i = 0; i < (n) / 2; i++) 
```

2021-01-07 17:14 UTC, atarax665 approved these changes
LGTM :+1:

2021-01-11 05:47 UTC, merged

2021-01-11 05:48 UTC, srimani-programmer commented
@iamvs-2002 is this part of any open source program?

2021-01-11 05:53 UTC, iamvs-2002 commented
> @iamvs-2002 is this part of any open source program?

Yes, DWOC