Gcd python
HarshCasper/NeoAlgo pull request #1951
Opened 2021-01-06 16:25 UTC by sakshi300699

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
(Write your answer here.)

### Description

This is a python program to find the GCD of two numbers. I have used recursion to find the GCD.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Addressed - #1902 
(Write your answer here.)

2021-01-06 16:36 UTC, sakshi300699 commented
Project Maintainers please review the PR.

2021-01-07 03:13 UTC, HarshCasper requested changes

2021-01-07 03:13 UTC, HarshCasper commented on Python/math/GCD_of_two_numbers.py
> +"""
Add a new line at the end of file

2021-01-07 03:13 UTC, HarshCasper commented on Python/math/GCD_of_two_numbers.py
> +print("The GCD is: ", gcd_of_nums(num1,num2))
Enclose this in a main function

2021-01-07 03:13 UTC, HarshCasper commented on Python/math/GCD_of_two_numbers.py
> +#Program to find GCD of 2 Numbers in Python.
Add an Intro about the Algorithm that you have implemented in multi-line string

2021-01-07 16:51 UTC, sakshi300699 commented
@HarshCasper sir, I have made the required changes, Kindly review.

2021-01-09 15:32 UTC, sakshi300699 commented
Project Maintainers, please review.

2021-01-11 21:36 UTC, sakshi300699 commented
@shraddhavp @iamrajiv please review the pr if any other change is needed

2021-01-12 05:55 UTC, HarshCasper requested changes
Please squash your Commits and I would merge it.

2021-01-12 05:55 UTC, HarshCasper commented on Python/math/GCD_of_two_numbers.py
> +print("\n")
Not needed

2021-01-12 07:46 UTC, sakshi300699 commented
@HarshCasper Squashed the Commits, Kindly merge.

2021-01-12 19:35 UTC, iamrajiv requested changes
@sakshi300699 Remove `e -i [SHA]` file.

2021-01-12 19:35 UTC, iamrajiv commented on C-Plus-Plus/README.md
> +
@sakshi300699 Do not edit this file.

2021-01-13 07:36 UTC, sakshi300699 commented
@iamrajiv @HarshCasper I think there is some problem with this branch. Can I close this PR and open a new one?

2021-01-13 08:46 UTC, sakshi300699 commented
@iamrajiv @HarshCasper I have made the necesssary changes. However there is some conflict with the PR for which I need to edit the C-Plus-Plus/README.md file. How should I proceed further?

2021-01-13 11:59 UTC, iamrajiv commented
@sakshi300699 Yes resolve the conflicts by editing the `C-Plus-Plus/README.md` file.

2021-01-13 14:21 UTC, sakshi300699 commented
@iamrajiv @HarshCasper The conflict has been resolved. Please review.

2021-01-14 04:20 UTC, HarshCasper approved these changes

2021-01-14 04:20 UTC, merged