Left view of tree
HarshCasper/NeoAlgo pull request #1957
Opened 2021-01-06 17:10 UTC by satyampgt4

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

It Will Print Left view of tree

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1922

2021-01-12 19:39 UTC, iamrajiv requested changes
@satyampgt4 Rename the program to `left_view_of_tree.cpp`.

2021-01-13 04:27 UTC, satyampgt4 commented
@iamrajiv  requested changes are done please check

2021-01-13 05:28 UTC, satyampgt4 commented
@iamrajiv requested changes are done please check

2021-01-13 11:55 UTC, iamrajiv requested changes
@satyampgt4 Add space and time complexity.

2021-01-13 12:22 UTC, satyampgt4 commented
@iamrajiv Time and Space Complexity is added please check

2021-01-14 04:26 UTC, HarshCasper requested changes
Tiny Changes. Would be fit to merge after them 👍

2021-01-14 04:26 UTC, HarshCasper commented on C-Plus-Plus/graphs/left_view_of_tree.cpp
> +   Space Complexity: O(n)
Push the Time and Space Complexity to the bottom of the Code

2021-01-14 04:26 UTC, HarshCasper commented on C-Plus-Plus/graphs/left_view_of_tree.cpp
> +					//if left child of current node is node present we simple add new node with the data to be inserted
Break down the Comment into simpler multiple-lines.

2021-01-14 04:26 UTC, HarshCasper commented on C-Plus-Plus/graphs/left_view_of_tree.cpp
> +					if (!temp->right_child) {
Break down the Comment into simpler multiple-lines.

2021-01-14 04:26 UTC, HarshCasper commented on C-Plus-Plus/graphs/left_view_of_tree.cpp
> +				//if data to be inserted is grater then or equal to the data of current node
Break down the Comment into simpler multiple-lines.

2021-01-14 04:26 UTC, HarshCasper commented on C-Plus-Plus/graphs/left_view_of_tree.cpp
> +	// last printed level
Remove redundant comments

2021-01-14 04:26 UTC, HarshCasper commented on C-Plus-Plus/graphs/left_view_of_tree.cpp
> +	// current level
Remove redundant comments

2021-01-14 07:20 UTC, satyampgt4 commented
@HarshCasper requested changes are done please check

2021-01-14 14:24 UTC, iamrajiv approved these changes

2021-01-14 16:57 UTC, atarax665 approved these changes

2021-01-14 16:57 UTC, merged