Add Inorder Traversal
HarshCasper/NeoAlgo pull request #1964
Opened 2021-01-07 13:54 UTC by muthuannamalai12

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Added Inorder Traversal in C 
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1923 
(Write your answer here.)

2021-01-07 14:00 UTC, muthuannamalai12 commented
@srimani-programmer . Kindly Review

2021-01-08 09:55 UTC, muthuannamalai12 commented
Kindly review it @atarax665

2021-01-08 16:47 UTC, atarax665 requested changes

2021-01-08 16:47 UTC, atarax665 commented on C/ds/Inorder.c
> +		printf(" %d", t->data);
```suggestion
		printf("%d ", t->data);
```

2021-01-08 16:47 UTC, atarax665 commented on C/ds/Inorder.c
> +// Inorder Traversal
Use multi-line comment instead of multiple single line comments.

2021-01-08 16:47 UTC, atarax665 commented on C/ds/Inorder.c
> +
Remove these redundant blank lines.

2021-01-08 16:47 UTC, atarax665 commented on C/ds/Inorder.c
> +Sample Output
Add Space and Time complexity of the program too.

2021-01-08 17:35 UTC, muthuannamalai12 commented
I have changed it. Kindly review it @atarax665

2021-01-08 18:27 UTC, atarax665 approved these changes

2021-01-09 03:42 UTC, muthuannamalai12 commented
@iamrajiv Please Review

2021-01-10 09:24 UTC, iamrajiv approved these changes

2021-01-10 09:25 UTC, merged