Added Matrix Script in Python
HarshCasper/NeoAlgo pull request #1966
Opened 2021-01-07 14:46 UTC by mehabhalodiya

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Matrix Script in Python(HackerRank).

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Solves #1581

2021-01-07 15:35 UTC, mehabhalodiya commented
Please check this @HarshCasper

2021-01-09 17:35 UTC, atarax665 requested changes
You should have a look on our [Python coding template](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/Code_Template.md) and format your code accorcingly.

2021-01-09 17:35 UTC, atarax665 commented on Miscellaneous/HackerRank/MatrixScript.py
> +first_multiple_input = input().rstrip().split()
Add proper description of the problem in commented form along with the link of the hackerrank question.

2021-01-09 17:35 UTC, atarax665 commented on Miscellaneous/HackerRank/MatrixScript.py
> +
You may put the logic in a function and only have the input and output function in the main code. Also add proper comments to explain your approach.

2021-01-09 17:35 UTC, atarax665 commented on Miscellaneous/HackerRank/MatrixScript.py
> +
Add sample input/output at the end of the program in commented form.

2021-01-10 07:14 UTC, mehabhalodiya commented
Kindly check it out @atarax665 .

2021-01-11 18:00 UTC, atarax665 requested changes
Please update the README.md file.

2021-01-11 18:00 UTC, atarax665 commented on Miscellaneous/HackerRank/MatrixScript.py
> +import math
Do we really need to import all these in this program?

2021-01-12 10:40 UTC, mehabhalodiya commented on Miscellaneous/HackerRank/MatrixScript.py
> +import math
Yes, HackerRank provides us all required libraries.

2021-01-12 17:23 UTC, atarax665 requested changes

2021-01-12 17:23 UTC, atarax665 commented on Miscellaneous/HackerRank/MatrixScript.py
> +import math
Its not needed atleast for this program, but anyways you can leave it as it is.

2021-01-12 17:23 UTC, atarax665 commented on Miscellaneous/HackerRank/MatrixScript.py
> +
Add appropriate comments and then this PR will be good to merge.

2021-01-12 17:23 UTC, atarax665 commented on Miscellaneous/HackerRank/MatrixScript.py
> +
Remove this extra blank line.

2021-01-13 17:39 UTC, atarax665 approved these changes

2021-01-13 17:40 UTC, merged

2021-01-13 17:41 UTC, atarax665 commented
@all-contributors please add @mehabhalodiya for code