Max Length Subarray with sum k added
HarshCasper/NeoAlgo pull request #1979
Opened 2021-01-09 04:02 UTC by thevivekpande

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
CPP solution for max length subarray with sum k added

### Checklist

- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [ Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1813

2021-01-12 04:55 UTC, HarshCasper requested changes
Tiny change. Code looks good 👍 

Please make apt README changes as well

2021-01-12 04:55 UTC, HarshCasper commented on C-Plus-Plus/cp/MaxLengthSubarrayWithSumK.cpp
> +#include<bits/stdc++.h>
Add a beginner description to the Code

2021-01-12 10:29 UTC, thevivekpande commented
Readme has been updated. please have a look.

2021-01-13 15:03 UTC, plazzy99 requested changes

2021-01-13 15:03 UTC, plazzy99 commented on C-Plus-Plus/cp/MaxLengthSubarrayWithSumK.cpp
> +
Add time and space complexity

2021-01-13 18:00 UTC, atarax665 requested changes

2021-01-13 18:00 UTC, atarax665 commented on C-Plus-Plus/cp/MaxLengthSubarrayWithSumK.cpp
> +// CPP program to find maximum length subarray with sum = k.
Add a line break after the problem introduction.

2021-01-13 18:00 UTC, atarax665 commented on C-Plus-Plus/cp/MaxLengthSubarrayWithSumK.cpp
> +    int n, arr[100], length, k;
Declare the array after taking the size of the array as input from the user.  You don't need to declare fixed length array initially.

2021-01-13 18:00 UTC, atarax665 commented on C-Plus-Plus/cp/MaxLengthSubarrayWithSumK.cpp
> +    for(int i=0;i<n;i++) cin>>arr[i];
```suggestion
    for(int i = 0; i < n; i++){
        cin>>arr[i];
        }
```

2021-01-14 04:19 UTC, HarshCasper requested changes

2021-01-14 04:19 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Maximum Length subarray with sum k ](cp/MaxLengthSubarrayWithSumK.cpp)
Why are there so many README changes?

2021-01-14 04:19 UTC, HarshCasper commented on C-Plus-Plus/cp/MaxLengthSubarrayWithSumK.cpp
> +// CPP program to find maximum length subarray with sum = k.
Make the description more intuitive.

2021-01-14 04:19 UTC, HarshCasper commented on C-Plus-Plus/cp/MaxLengthSubarrayWithSumK.cpp
> +        //if sum is not present in map do enter it.
Use Multi-Line Comments instead of Single-Line Comments

2021-01-26 18:05 UTC, atarax665 commented
@thevivekpande Are you still working on this? Please reply to reopen this PR.

2021-01-26 18:05 UTC, closed without merging