Queue program, issue #1780
HarshCasper/NeoAlgo pull request #1986
Opened 2021-01-10 18:21 UTC by chicken-biryani

Made the required fix in my program related to dynamic queue

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes.)

### Description

### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Fixes #1781 )

2021-01-10 18:52 UTC, chicken-biryani commented
Made fixes in two programs. Kindly check them out. 
(DWOC)

2021-01-11 17:36 UTC, atarax665 requested changes
These are the suggested changes:
- Format your code according to PEP8 guidelines.
- Make necessary changes in README.md
- As you have not resolved issues on the PR #1781, I think it would be better to have separate PR for each one of those programs, as it gets quite a task for reviewers to review PRs with so many files and changes.

2021-01-11 17:36 UTC, atarax665 commented on Python/cp/LetterCount.py
> +word=input("enter a word ").lower() #Converting to lowercase for the ASCII code to be same
Move the comment above the code.

2021-01-11 17:36 UTC, atarax665 commented on Python/cp/LetterCount.py
> +for c in word:
It would be better if you can make separate functions for code logic and driver code.

2021-01-11 17:36 UTC, atarax665 commented on Python/cp/LetterCount.py
> +Complexity- O(n)
```suggestion
Time Complexity- O(n)
```

2021-01-11 17:36 UTC, atarax665 commented on Python/ds/dynamic_queue.py
> +        1 to insert into queue
```suggestion
         1 to insert into queue 
```

2021-01-11 17:36 UTC, atarax665 commented on Python/ds/dynamic_queue.py
> +Complexity - O(n)
```suggestion
Time Complexity - O(n)
```

2021-01-25 17:10 UTC, atarax665 commented
Closing this PR due to inactivity from contributor's end.

2021-01-25 17:10 UTC, closed without merging