Queue in C as list with extra methods
HarshCasper/NeoAlgo pull request #2008
Opened 2021-01-14 10:30 UTC by KlaraKrmpotic

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-01-17 17:29 UTC, srimani-programmer requested changes

2021-01-17 17:29 UTC, srimani-programmer commented on C/other/Queue_as_List.c
> +}
@KlaraKrmpotic please add an extra line at the end of the file.

2021-01-17 17:29 UTC, srimani-programmer commented on C/other/Queue_as_List.c
> +
@KlaraKrmpotic Try to read input from the console. It should be good.

2021-01-26 18:04 UTC, atarax665 commented
Closing the PR due to inactivity from contributor's end.

2021-01-26 18:04 UTC, closed without merging