implemented merge sort for kotlin lang
HarshCasper/NeoAlgo pull request #2017
Opened 2021-01-15 15:26 UTC by gat786

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have.

### Description

Implementation of Merge Sort for Kotlin Lang

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

It is not enlisted in Issues. Atleast, not that I know of.

2021-01-19 16:34 UTC, srimani-programmer requested changes

2021-01-19 16:34 UTC, srimani-programmer commented on Kotlin/sort/MergeSort/src/MergeSort.kt
> +fun mergeSort(list : MutableList<Int>) : MutableList<Int>{
@gat786 Add the Sample Output at the end of the program.

2021-01-19 16:34 UTC, srimani-programmer commented on Kotlin/sort/MergeSort/src/MergeSort.kt
> +
@gat786 Remove all the extra spaces in the code file.

2021-01-21 07:05 UTC, plazzy99 requested changes

2021-01-21 07:05 UTC, plazzy99 commented on Kotlin/sort/MergeSort/src/MergeSort.kt
> +}
add space and time complexity

2021-01-30 04:07 UTC, HarshCasper commented
Are you working on the same @gat786 ?

2021-01-30 04:07 UTC, gat786 commented
Yes been a little busy the past week.

2021-01-31 15:30 UTC, gat786 commented
@HarshCasper I added the required changes and I hope the current version is acceptable

2021-02-04 14:29 UTC, HarshCasper approved these changes

2021-02-04 14:29 UTC, merged