Add stack using array
HarshCasper/NeoAlgo pull request #2019
Opened 2021-01-16 07:19 UTC by muthuannamalai12

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Added Stack Implementation using Array in C.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1982 
(Write your answer here.)

2021-01-16 12:41 UTC, muthuannamalai12 commented
@atarax665 Kindly Review

2021-01-16 18:04 UTC, muthuannamalai12 commented
@atarax665 Kindly Review

2021-01-17 17:33 UTC, srimani-programmer requested changes

2021-01-17 17:33 UTC, srimani-programmer commented on C/ds/StackImplementationWithArray.c
> +
@muthuannamalai12 Remove all the unnecessary extra lines at the end of the file.

2021-01-17 17:33 UTC, srimani-programmer commented on C/ds/StackImplementationWithArray.c
> +#define SIZE 10
@muthuannamalai12 Try to assign the size of an array at runtime.

2021-01-17 18:30 UTC, muthuannamalai12 commented
I have changed it. Kindly review it @srimani-programmer

2021-01-18 12:46 UTC, HarshCasper approved these changes

2021-01-18 12:48 UTC, merged