Add stack using linked list
HarshCasper/NeoAlgo pull request #2020
Opened 2021-01-16 07:28 UTC by muthuannamalai12

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Added Stack Implementation using Linked List in C.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1983
(Write your answer here.)

2021-01-16 12:41 UTC, muthuannamalai12 commented
@atarax665 Kindly Review

2021-01-16 17:38 UTC, atarax665 requested changes

2021-01-16 17:38 UTC, atarax665 commented on C/README.md
> -- [Post Order Traversal](ds/Postorder.c)
Don't remove anything from the README. You just need to add the link of your program under appropriate section.

2021-01-16 17:38 UTC, atarax665 commented on C/ds/StackImplementationWithLinkedList.c
> +data is 23 25
```suggestion
Data is 23 25
```

2021-01-16 17:38 UTC, atarax665 commented on C/ds/StackImplementationWithLinkedList.c
> +		do {
Add ```printf("\n*****MENU******\n");``` to have the output similar to the Sample I/O.

2021-01-16 17:38 UTC, atarax665 commented on C/ds/StackImplementationWithLinkedList.c
> +		temp = top;
Add a line ```printf("\nData is "); before the while loop.

2021-01-16 17:38 UTC, atarax665 commented on C/ds/StackImplementationWithLinkedList.c
> +			printf("%d\n", temp->data);
```suggestion
			printf("%d ", temp->data);
```

2021-01-16 17:38 UTC, atarax665 commented on C/ds/StackImplementationWithLinkedList.c
> +
Remove this extra blank line.

2021-01-16 17:57 UTC, muthuannamalai12 commented
I have changed it @atarax665 Kindly review it again

2021-01-18 12:41 UTC, HarshCasper requested changes
Code looks good. Tiny change required and ready to merge 👍

2021-01-18 12:41 UTC, HarshCasper commented on C/ds/StackImplementationWithLinkedList.c
> +
Inconsistent indentation. Please fix it 👍

2021-01-18 13:12 UTC, muthuannamalai12 commented
I have changed it. Kindly review again @HarshCasper

2021-01-19 18:26 UTC, atarax665 requested changes

2021-01-19 18:26 UTC, atarax665 commented on C/ds/StackImplementationWithLinkedList.c
> +            printf("\n*****Menu*****)
```suggestion
            printf("\n*****Menu*****);
```

2021-01-19 18:26 UTC, atarax665 commented on C/ds/StackImplementationWithLinkedList.c
> +                printf("\n1.Push\n2.Pop\n3.Display\n4.Exit\n"); printf("Enter your choice:"); scanf("%d", & choice);
Indentation is still inconsistent.

2021-01-20 04:01 UTC, muthuannamalai12 commented
I have changed it. Kindly review again @atarax665

2021-01-20 05:43 UTC, atarax665 commented on C/README.md
> -- [Post Order Traversal](ds/Postorder.c)
This issue has not been resolved yet.

2021-01-20 05:53 UTC, muthuannamalai12 commented
I have resolved the change in README.md. Kindly review again @atarax665

2021-01-20 16:08 UTC, plazzy99 approved these changes
update readme rest LGTM

2021-01-25 14:43 UTC, muthuannamalai12 commented
@atarax665 @HarshCasper @iamrajiv  Kindly Review

2021-01-25 14:51 UTC, plazzy99 commented on C/README.md
> -- [Stack Implementation with Array](ds/StackImplementationWithArray.c)
This is missing

2021-01-25 15:01 UTC, muthuannamalai12 commented
@plazzy99 I have resolved it Kindly review again

2021-01-27 09:08 UTC, muthuannamalai12 commented
@plazzy99 I have updated it. Kindly review again

2021-01-27 14:30 UTC, muthuannamalai12 commented
@atarax665 @HarshCasper @iamrajiv Kindly Review

2021-01-27 14:57 UTC, muthuannamalai12 commented
@atarax665 @HarshCasper @iamrajiv @plazzy99. Kindly Review

2021-01-27 17:55 UTC, atarax665 approved these changes

2021-01-27 17:56 UTC, merged

2021-02-13 08:05 UTC, muthuannamalai12 commented
@HarshCasper @atarax665. Can you please add DWOC and level label for this issue here on my PR.

2021-02-17 17:09 UTC, muthuannamalai12 commented
@HarshCasper @atarax665 @anushkrishnav. Can you please add DWOC and level label for this issue here on my PR.

2021-02-19 05:06 UTC, muthuannamalai12 commented
@HarshCasper @atarax665 @anushkrishnav . Can you please add DWOC and level label for this issue here on my PR.

2021-02-19 06:41 UTC, muthuannamalai12 commented
@HarshCasper @atarax6 @anushkrishnav. Can you please add a level label for this issue here on my PR.