Sleep Sort in Java
HarshCasper/NeoAlgo pull request #2022
Opened 2021-01-16 15:10 UTC by sakshikhachane

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added sleep sort in java

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
 #2018

2021-01-16 15:11 UTC, sakshikhachane commented
@anushkrishnav Please review the PR.

2021-01-17 05:05 UTC, shraddhavp commented
@sakshikhachane  the code has static input already given,Can you change the code to take input from t he user dynamically?

2021-01-17 09:26 UTC, sakshikhachane commented
@shraddhavp Changes done to add the input dynamically.

2021-01-17 11:29 UTC, shraddhavp commented
@sakshikhachane  also add the time and space complexity ,then it is ready to merge

2021-01-17 11:52 UTC, sakshikhachane commented
@shraddhavp Did the changes.

2021-01-18 04:27 UTC, shraddhavp commented
LGTM! @iamrajiv  please once review it

2021-01-18 12:26 UTC, iamrajiv approved these changes

2021-01-18 12:35 UTC, HarshCasper requested changes
Tiny changes required. LGTM 👍

2021-01-18 12:35 UTC, HarshCasper commented on Java/sort/SleepSort.java
> +import java.util.Scanner;
Add a Beginner Pitch about your Code

2021-01-18 12:35 UTC, HarshCasper commented on Java/sort/SleepSort.java
> +            }).start();
Can you add proper comments?

2021-01-19 09:58 UTC, sakshikhachane commented on Java/sort/SleepSort.java
> +import java.util.Scanner;
@HarshCasper Done with the changes.

2021-01-19 10:00 UTC, sakshikhachane commented
@HarshCasper Please review this now. I have done all the changes.

2021-01-19 11:53 UTC, merged