Reverse a string #1999
HarshCasper/NeoAlgo pull request #2024
Opened 2021-01-16 16:00 UTC by Amit366

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have made a program for reversing a string and also updated the readme.md file.

2021-01-16 17:07 UTC, atarax665 commented
Couldn't find any issue related to this PR.

2021-01-16 17:14 UTC, Amit366 commented
Sir it is the part of implementation in Java  #1999

2021-01-16 17:14 UTC, Amit366 commented
And also I was assigned.

2021-01-16 17:16 UTC, Amit366 commented
It was my fault that I didn't mention above but I mentioned the issue number #1999

2021-01-16 18:06 UTC, atarax665 requested changes

2021-01-16 18:06 UTC, atarax665 commented on Java/cp/ReverseString.java
> +}
Add Sample Input/Output with space and time complexity of the program in commented form.

2021-01-16 18:06 UTC, atarax665 commented on Java/cp/ReverseString.java
> +            result+= str.charAt(i);
```suggestion
            result += str.charAt(i);
```

2021-01-16 18:06 UTC, atarax665 commented on Java/cp/ReverseString.java
> +        for (int i = str.length()-1; i >= 0; i--)
```suggestion
        for (int i = str.length() - 1; i >= 0; i--)
```

2021-01-16 18:06 UTC, atarax665 commented on Java/cp/ReverseString.java
> +        String result="";
```suggestion
        String result = "";
```

2021-01-17 04:50 UTC, Amit366 commented
Sir I have updated the suggested changes.

2021-01-18 12:23 UTC, HarshCasper requested changes

2021-01-18 12:23 UTC, HarshCasper commented on Java/cp/ReverseString.java
> +import java.lang.*;
Add a beginner pitch about your Code

2021-01-18 12:23 UTC, HarshCasper commented on Java/cp/ReverseString.java
> +*/
Add a new line at the EOF

2021-01-18 12:23 UTC, HarshCasper commented on Java/cp/ReverseString.java
> +            result += str.charAt(i);
Push your main Code Logic to a different function. Use the main() function only as your driver code

2021-01-18 12:29 UTC, Amit366 commented on Java/cp/ReverseString.java
> +*/
Sir could you elaborate a bit

2021-01-20 16:06 UTC, plazzy99 approved these changes

2021-01-20 18:44 UTC, atarax665 approved these changes

2021-01-20 18:44 UTC, merged

2021-01-20 19:17 UTC, Amit366 commented
Sir please add the level and DWOC tags so that it is counted

2021-01-24 05:47 UTC, Amit366 commented
@atarax665 please add the DWOC and level tags so that it is considered for points.