Memory Allocation in Operating Systems in Java
HarshCasper/NeoAlgo pull request #2025
Opened 2021-01-16 17:58 UTC by shraiyya

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

PR corresponding to issue #1984 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Please add the DWOC tag and level of the code.

2021-01-18 12:14 UTC, HarshCasper requested changes

2021-01-18 12:14 UTC, HarshCasper commented on Java/Operating-System/alloc.java
> +(a) First-Fit: Allocate the first hole that is big enough. Searching can start either at the beginning of the set of holes or where the previous first search ended. We can stop searching as soon as w
Break down the line into shorter, more consumable lines.

2021-01-18 12:14 UTC, HarshCasper commented on Java/Operating-System/alloc.java
> +  public static void main(String[] args) {
Keep your main() function only for the Driver Code. Break down your entire code into modular functions and then call them from the main() function

2021-01-18 12:14 UTC, HarshCasper commented on Java/Operating-System/alloc.java
> +}
Add sample I/O in a Multi-Line Comment

2021-01-21 02:00 UTC, HarshCasper approved these changes

2021-01-21 02:01 UTC, merged

2021-02-01 07:23 UTC, shraiyya commented
Please add the level of the code.