circular_queue using Java
HarshCasper/NeoAlgo pull request #2027
Opened 2021-01-17 11:59 UTC by Rishikeshrajrxl

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1741 
(Write your answer here.)

2021-01-17 12:00 UTC, Rishikeshrajrxl commented
@shraddhavp, please review

2021-01-18 12:09 UTC, HarshCasper requested changes
Make README changes as well

2021-01-18 12:09 UTC, HarshCasper commented on Java/ds/circular_queue.java
> +        }while(true);
Indent the piece of Code

2021-01-18 12:09 UTC, HarshCasper commented on Java/ds/circular_queue.java
> +        Main m = new Main(size);
Follow a consistent indentation

2021-01-18 12:09 UTC, HarshCasper commented on Java/ds/circular_queue.java
> +    //////////////////////////////////////////////////////////////
Remove such comments from the entire Code

2021-01-18 12:09 UTC, HarshCasper commented on Java/ds/circular_queue.java
> +        else if(front ==size-1)
Inconsistent Indentation.

2021-01-18 12:09 UTC, HarshCasper commented on Java/ds/circular_queue.java
> +    Main(int n) //Constructor
Use Comments above the LOC not beside them. Also don't put simplistic comments.

2021-01-18 12:09 UTC, HarshCasper commented on Java/ds/circular_queue.java
> +import java.util.*;
Add a beginner pitch about the Code that you have written

2021-02-04 14:32 UTC, HarshCasper commented
Closing the PR cause of no updates. Let me know if you would like this to be reopened.

2021-02-04 14:32 UTC, closed without merging

2021-02-14 03:38 UTC, Rishikeshrajrxl commented
> Closing the PR cause of no updates. Let me know if you would like this to be reopened.

@HarshCasper , please reopen this PR, I will do the changes. And sorry for delay.