Added linked_list_middle_element.cpp which detects the middle element…
HarshCasper/NeoAlgo pull request #2028
Opened 2021-01-18 10:51 UTC by Sarthak-9

… of a linked list and updated README.md

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Algorithm to find the middle element of a Linked List

### Checklist

- [#] I've read the contribution guidelines.
- [#] I've checked the issue list before deciding what to submit.
- [#] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1617

2021-01-18 10:54 UTC, Sarthak-9 commented
@shraddhavp Please review

2021-01-18 12:06 UTC, HarshCasper requested changes
Remove unused lines of Code. Changes suggested are tiny ones. 

I will let @iamrajiv and @atarax665 to take a look at the Code. From my side, it looks good.

2021-01-18 12:06 UTC, HarshCasper commented on C-Plus-Plus/ds/linked_list_middle_element.cpp
> + Created by Sarthak-9
If you would like to be cited for the Source Code, please add `Author: Sarthak Saxea (@Sarthak-9)`

2021-01-18 12:06 UTC, HarshCasper commented on C-Plus-Plus/ds/linked_list_middle_element.cpp
> +*/
Add a new line at the EOF

2021-01-18 12:06 UTC, HarshCasper commented on C-Plus-Plus/ds/linked_list_middle_element.cpp
> +};
What level of indentation are you following? This is incoherent with the code that exists in the repo.

2021-01-18 12:06 UTC, HarshCasper commented on C-Plus-Plus/ds/linked_list_middle_element.cpp
> +        for (int i=1; i<n; i++){
Format the Code

2021-01-18 14:02 UTC, Sarthak-9 commented
@HarshCasper Check please

2021-01-18 17:40 UTC, atarax665 requested changes

2021-01-18 17:40 UTC, atarax665 commented on C-Plus-Plus/ds/linked_list_middle_element.cpp
> + Time complexity of MiddleNode1 : O(n)
Please do add a short description of both the methods individually.

2021-01-18 17:40 UTC, atarax665 commented on C-Plus-Plus/ds/linked_list_middle_element.cpp
> +        int index = (int)ceil(length/2.0);
```suggestion
        int index = (int) ceil(length / 2.0);
```

2021-01-18 17:40 UTC, atarax665 commented on C-Plus-Plus/ds/linked_list_middle_element.cpp
> +        for (int i=0; i<index-1; i++){
```suggestion
        for (int i = 0; i < index - 1; i++){
```

2021-01-18 18:27 UTC, Sarthak-9 commented
@atarax665 Check now

2021-01-19 18:03 UTC, atarax665 approved these changes
LGTM :+1:

2021-01-19 22:51 UTC, iamrajiv approved these changes

2021-01-19 22:51 UTC, merged