program to detect the middle element of a linkedlist in c is added
HarshCasper/NeoAlgo pull request #2031
Opened 2021-01-18 12:43 UTC by sakshi300699

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

C program to detect the middle element of the linkedlist using two-pointer approach.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Addressed- #1617

2021-01-19 16:20 UTC, srimani-programmer requested changes

2021-01-19 16:20 UTC, srimani-programmer commented on C/ds/middle_element_of_linkedlist.c
> +
@sakshi300699 please remove these extra lines

2021-01-19 16:20 UTC, srimani-programmer commented on C/ds/middle_element_of_linkedlist.c
> +/*
@sakshi300699 Remove all the extra unnecessary spaces in the code.

2021-01-19 16:20 UTC, srimani-programmer commented on C/ds/middle_element_of_linkedlist.c
> +
@sakshi300699 Remove this extra lines from the end of the file.

2021-01-21 14:03 UTC, sakshi300699 commented
@srimani-programmer Done the required changes. Please review and also kindly add the necessary level tag.

2021-01-31 08:12 UTC, sakshi300699 commented
Please review my PR, project maintainers

2021-02-03 16:23 UTC, sakshi300699 commented
It's been 16 days since I made this PR. Please review the PR @HarshCasper  @srimani-programmer

2021-02-04 14:33 UTC, HarshCasper approved these changes

2021-02-04 14:33 UTC, merged

2021-02-17 18:14 UTC, sakshi300699 commented
@HarshCasper @srimani-programmer Please add DWOC tag to this

2021-02-19 16:33 UTC, sakshi300699 commented
@HarshCasper @atarax665 @anushkrishnav @srimani-programmer please add DWOC tag to this PR.