Ankita Added Diameter Of A BinaryTree Using Java
HarshCasper/NeoAlgo pull request #2034
Opened 2021-01-19 07:28 UTC by ankitasantape

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

The diameter of a binary tree is the length of the longest path between any two nodes in a tree. This path may or may not pass through the root.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

DWoC
issue Addressed -  #1802

2021-01-20 17:17 UTC, atarax665 requested changes

2021-01-20 17:17 UTC, atarax665 commented on Java/Algorithms/NthFibonacciElement.java
> +public class NthFoboElement {
```suggestion
public class NthFibonacciElement {
```

2021-01-20 17:17 UTC, atarax665 commented on Java/ds/Diameter_Of_A_BinaryTree.java
> +		root.left = new BinaryTreeNode<>(2);
Dynamic inputs are preferred.

2021-01-20 17:17 UTC, atarax665 commented on Java/ds/Diameter_Of_A_BinaryTree.java
> +
Remove these extra blank spaces.

2021-01-20 17:17 UTC, atarax665 commented on Java/ds/Diameter_Of_A_BinaryTree.java
> +}
Add sample input/output in commented form.

2021-01-20 17:17 UTC, atarax665 commented on Java/Algorithms/NthFibonacciElement.java
> +
Remove this line.

2021-01-25 21:19 UTC, iamrajiv approved these changes

2021-02-04 14:34 UTC, HarshCasper commented
@ankitasantape 

Please remove the Merge Conflicts 👍

2021-02-07 04:58 UTC, merged