Sumit Added LongestSubArrayHavingSumK code
HarshCasper/NeoAlgo pull request #2035
Opened 2021-01-19 07:29 UTC by sumitsantape30

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

This code helps to find the length of the longest sub-array having sum equal to the given value k.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

DWoC
Issue Addressed-  #1813

2021-01-19 18:11 UTC, atarax665 requested changes
Update the README file as well.

2021-01-19 18:11 UTC, atarax665 commented on Java/other/LongestSubArrayHavingSumk.java
> +		int[] arr = { 1, 2, 1, 0, 1, 1, 0 };
Dynamic input is preferred.

2021-01-19 18:11 UTC, atarax665 commented on Java/other/LongestSubArrayHavingSumk.java
> +
Add a beginner introduction of the program with the space and time complexity of your approach.

2021-01-19 18:11 UTC, atarax665 commented on Java/other/LongestSubArrayHavingSumk.java
> +/*
Add sample input/output here. Please refer to any recently merged Java PR to get an idea of the Java Code template that we follow.

2021-01-22 11:49 UTC, plazzy99 requested changes
Update readme

2021-02-04 14:34 UTC, HarshCasper commented
Closing the PR cause of no updates. Let me know if you would like this to be reopened.

2021-02-04 14:34 UTC, closed without merging

2021-02-08 16:11 UTC, sumitsantape30 commented
Please Open this PR, sorry for the delays I had my exams so couldn't work on it.