Missing elements
HarshCasper/NeoAlgo pull request #2039
Opened 2021-01-20 08:57 UTC by proghead00

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes, I have.

### Description

(Write your answer here.)
This program will find out the missing elements in a series.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
I will be opening more PRs as each program I add.

2021-01-20 17:07 UTC, atarax665 requested changes

2021-01-20 17:07 UTC, atarax665 commented on C/cp/missingElementsFasterMethod.c
> +#include <stdio.h>
Add a beginner introduction of the problem and your approach.

2021-01-20 17:07 UTC, atarax665 commented on C/cp/missingElementsFasterMethod.c
> +    int arr[6];
Why have you initialized the size of the array? You can take the size of the array as an input from the user.

2021-01-20 17:07 UTC, atarax665 commented on C/cp/missingElementsFasterMethod.c
> +}
Add sample input/output and space and time complexity of the program.

2021-02-04 14:35 UTC, HarshCasper commented
Closing the PR cause of no updates. Let me know if you would like this to be reopened.

2021-02-04 14:35 UTC, closed without merging