added Armstrong number file
HarshCasper/NeoAlgo pull request #2051
Opened 2021-01-22 13:58 UTC by nayanajain

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-01-22 13:59 UTC, nayanajain commented
Added Armstrong_Number.py file

2021-01-22 18:28 UTC, atarax665 requested changes
Update appropriate README.md

2021-01-22 18:28 UTC, atarax665 commented on Python/math/Armstrong_Number.py
> +# program to check if the number is an Armstrong number or not
Add an introduction of Armstrong number.

2021-01-22 18:28 UTC, atarax665 commented on Python/math/Armstrong_Number.py
> +# take input from the user
Don't add such trivial comments, add comments only where needed.

2021-01-22 18:28 UTC, atarax665 commented on Python/math/Armstrong_Number.py
> +#Output
Add sample input/output in docstring with Space and time complexity of your program.

2021-01-22 18:28 UTC, atarax665 commented on Python/math/Armstrong_Number.py
> +
Remove these blank lines.

2021-01-23 07:24 UTC, nayanajain commented
..

2021-01-23 12:00 UTC, HarshCasper requested changes

2021-01-23 12:00 UTC, HarshCasper commented on Python/math/Armstrong_Number.py
> +'''
Add a new line at the EOF

2021-01-23 12:00 UTC, HarshCasper commented on Python/math/Armstrong_Number.py
> +   temp //= 10
Push the primary logic inside a modular function

2021-01-23 12:00 UTC, HarshCasper commented on Python/math/Armstrong_Number.py
> +sum = 0
Enclose the driver logic in a `if __name__ == '__main__'` block

2021-02-04 14:40 UTC, HarshCasper commented
@nayanajain 

Are you still working on the same?

2021-02-05 05:06 UTC, nayanajain commented
This program is already present in python...so i stopped working on it

On Thu, 4 Feb 2021, 8:10 pm Harsh Mishra, <notifications@github.com> wrote:

> @nayanajain <https://github.com/nayanajain>
>
> Are you still working on the same?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/TesseractCoding/NeoAlgo/pull/2051#issuecomment-773359175>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL7HKZAAKBKICAFFGDNSHP3S5KWVPANCNFSM4WOQW24A>
> .
>

2021-02-07 16:51 UTC, closed without merging