Issue #1780 - VowelsConsonants #DWOC
HarshCasper/NeoAlgo pull request #2057
Opened 2021-01-24 10:14 UTC by chicken-biryani

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

I added the Vowels and Consonants program

### Checklist

- [YES] I've read the contribution guidelines.
- [YES] I've checked the issue list before deciding what to submit.
- [YES] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #1780

2021-01-24 10:15 UTC, chicken-biryani commented
Kindly tell me if there are any changes required

2021-01-24 17:03 UTC, atarax665 requested changes
Format your code according to PEP8 guidelines. You can use [this](http://pep8online.com/).

2021-01-25 08:05 UTC, chicken-biryani commented
I did so

2021-01-26 11:21 UTC, chicken-biryani commented
Can someone kindly tell me there are any required changes?

2021-01-26 18:27 UTC, atarax665 requested changes

2021-01-26 18:27 UTC, atarax665 commented on Python/README.md
> +- [Vowels ans consonants in a word](cp/VowelsConsonants.py)
```suggestion
- [Vowels and consonants in a string](cp/VowelsConsonants.py)
```

2021-01-29 05:19 UTC, HarshCasper requested changes

2021-01-29 05:19 UTC, HarshCasper commented on Python/cp/VowelsConsants.py
> +def Count(word):
Add proper Docstrings

2021-01-29 05:19 UTC, HarshCasper commented on Python/cp/VowelsConsants.py
> +print("Vowel count = ", vc, " Consonant count = ", cc)
Enclose in a `if __name__ == '__main__'` block

2021-02-04 11:20 UTC, chicken-biryani commented
Re-review

2021-02-04 12:57 UTC, atarax665 approved these changes

2021-02-07 16:54 UTC, HarshCasper approved these changes

2021-02-07 16:54 UTC, merged

2021-02-10 18:52 UTC, chicken-biryani commented
Hey, can you add the DWOC label?

2021-02-19 09:29 UTC, chicken-biryani commented
Hey @HarshCasper // @atarax665  can you kindly add the DWOC label?