Issue#1620 - reverse linked list in golang
HarshCasper/NeoAlgo pull request #2060
Opened 2021-01-25 13:01 UTC by swordcom367

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

A program to reverse a singly linked list in golang.

### Checklist

- [yes] I've read the contribution guidelines.
- [yes] I've checked the issue list before deciding what to submit.
- [yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue#1620

2021-01-29 05:12 UTC, HarshCasper requested changes

2021-01-29 05:12 UTC, HarshCasper commented on Go/ds/singly_linked_list_reversed.go
> +			"5 -> quit\n")
Can you use better Console Statements?

2021-01-29 05:12 UTC, HarshCasper commented on Go/ds/singly_linked_list_reversed.go
> +package main
Add a beginner pitch about the Code/Algorithm/Data Structures

2021-01-29 05:12 UTC, HarshCasper commented on Go/ds/singly_linked_list_reversed.go
> +//fillListWithDummyData: add values 1 - 9 to the linked list for testing reasons
Please use better comments to exactly show what is being done, rather than vague idea about the same

2021-02-04 15:14 UTC, HarshCasper requested changes
Tiny change required. Please squash your Commits as well. I will merge it soon after

2021-02-04 15:14 UTC, HarshCasper commented on Go/ds/singly_linked_list_reversed.go
> + reverce linked list is an implimention of a singaly linked list with an algorithm to reverce the order of the list
Typo. It should be `reverse`

2021-02-04 18:47 UTC, swordcom367 commented
could you check if I squashed my commits correctly? it's my first time doing so and I don't know if I did it correctly .

2021-02-05 16:06 UTC, atarax665 commented
> could you check if I squashed my commits correctly? it's my first time doing so and I don't know if I did it correctly.

Your commits have not been squashed yet.

2021-02-08 17:43 UTC, swordcom367 commented
My commits should be squashed.

2021-02-13 10:13 UTC, HarshCasper approved these changes

2021-02-13 10:14 UTC, merged