Added Logically Weighted Regression
HarshCasper/NeoAlgo pull request #2061
Opened 2021-01-25 15:06 UTC by infiniteoverflow

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

I have implemented a Logically Weighted Regression Model on a given dataset contained in a .csv file.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2000

2021-01-25 15:10 UTC, infiniteoverflow commented
@shraddhavp i have added the program. Kindly let me know if any changes are required. Thank you

2021-01-27 12:22 UTC, HarshCasper commented
Hi @infiniteoverflow 

Thanks for making this PR. Please make these changes: 

- Add a line at the End of the File 
- Remove ` .DS_Store` from the Commits 
- Use dashes or underscores in `Logically Weighted Regression`
- Remove the Dataset and add a Kaggle/G-Drive Link instead

2021-01-27 12:31 UTC, infiniteoverflow commented
thank you @HarshCasper  , I have made changes accordingly.

2021-01-29 05:07 UTC, HarshCasper requested changes
You have not yet removed `.DS_Store` from the Commits

2021-01-29 05:07 UTC, HarshCasper commented on Python/README.md
> +* [Logically Weighted Regression](ml/Logically%20Weighted%20Regression)
The Reference is wrong.

2021-01-29 05:07 UTC, HarshCasper commented on Python/ml/Logically_weighted_regression.py
> +# Get the dataset from 'https://www.kaggle.com/aswin1871/tips-csv'
Add a beginner pitch about the Algorithm along with the Dataset

2021-01-29 05:07 UTC, HarshCasper commented on Python/ml/Logically_weighted_regression.py
> +def kernel(point,xmat,k):
Add proper Docstrings here along with Comments

2021-01-29 05:07 UTC, HarshCasper commented on Python/ml/Logically_weighted_regression.py
> +def local_weight(point,xmat,k,ymat):
Add proper Docstrings here along with Comments

2021-01-29 05:07 UTC, HarshCasper commented on Python/ml/Logically_weighted_regression.py
> +def local_weight_regression(xmat,ymat,k):
Add proper Docstrings here along with Comments

2021-01-29 05:07 UTC, HarshCasper commented on Python/ml/Logically_weighted_regression.py
> +plt.show()
Enclose this in a `if __name__ == '__main__'` block

2021-01-29 13:11 UTC, infiniteoverflow commented
@HarshCasper I have updated the files as per the requirements. Kindly have a look.
The .DS_STORE file in my commits is not present in my repo , it is pointing the same file in the parent repo.

2021-01-30 04:38 UTC, HarshCasper approved these changes

2021-01-30 04:38 UTC, merged

2021-01-30 05:58 UTC, infiniteoverflow commented
@HarshCasper Can you please add the DWOC and Level label for this issue #2000