Angastrom
HarshCasper/NeoAlgo pull request #2066
Opened 2021-01-28 17:02 UTC by satyampgt4

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

this program will check whether a number is ARMSTRONG NUMBER or not

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2036

2021-01-29 04:59 UTC, HarshCasper requested changes

2021-01-29 04:59 UTC, HarshCasper commented on JavaScript/Algorithms/Armstrong.js
> +process.stdin.resume();
Add a beginner pitch about the Code with a brief background of the Algorithm

2021-01-29 04:59 UTC, HarshCasper commented on JavaScript/Algorithms/Armstrong.js
> +});
Add sample I/O

2021-01-29 04:59 UTC, HarshCasper commented on JavaScript/README.md
> +- [Check Armstrong](Algorithms/Armstrong.js)
Use `Armstrong Number` instead of `Check Armstrong`

2021-01-29 16:42 UTC, satyampgt4 commented
@HarshCasper  requested changes are done please check

2021-01-30 04:35 UTC, HarshCasper approved these changes

2021-01-30 04:36 UTC, merged