Postfix Evaluation
HarshCasper/NeoAlgo pull request #2068
Opened 2021-01-29 09:00 UTC by muthuannamalai12

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Added C code for Postfix Evaluation
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2045
(Write your answer here.)

2021-01-30 04:11 UTC, HarshCasper requested changes

2021-01-30 04:11 UTC, HarshCasper commented on C/ds/EvaluationOfPostfixExpression.c
> +4.Finally! perform a pop operation and display the popped value as final result.
Modularize this. It is tough to read and skim through on Mobile/Laptop Devices

2021-01-30 04:11 UTC, HarshCasper commented on C/ds/EvaluationOfPostfixExpression.c
> +void main()
Use `int main()` instead of `void`

2021-01-30 04:11 UTC, HarshCasper commented on C/ds/EvaluationOfPostfixExpression.c
> +                s.a[++s.top] = d1 / d2;
Few changes: 
- Use meaningful variable names 
- Shift the Stack Code to a function

2021-01-30 07:50 UTC, muthuannamalai12 commented
I have updated kindly review again @HarshCasper @atarax665

2021-01-30 10:57 UTC, atarax665 requested changes

2021-01-30 10:57 UTC, atarax665 commented on C/ds/EvaluationOfPostfixExpression.c
> +    char ch[50];
Use a meaningful name for variables. i.e -  postfix[30]  etc. Do the same with variables x, y, z.

2021-01-30 12:23 UTC, muthuannamalai12 commented
I have updated kindly review again @atarax665

2021-01-30 17:29 UTC, muthuannamalai12 commented
I have updated kindly review again @atarax665

2021-02-02 17:14 UTC, atarax665 requested changes
Shift the stack code in a function. The main function should only have the driver code.

2021-02-02 18:23 UTC, muthuannamalai12 commented
I have updated it. Kindly Review again @atarax665

2021-02-04 15:16 UTC, HarshCasper approved these changes

2021-02-04 15:16 UTC, merged

2021-02-13 08:06 UTC, muthuannamalai12 commented
@HarshCasper @atarax665. Can you please add DWOC and level label for this issue here on my PR.

2021-02-17 17:07 UTC, muthuannamalai12 commented
@HarshCasper @atarax665 @anushkrishnav . Can you please add DWOC and level label for this issue here on my PR.