Yuvraj 3
HarshCasper/NeoAlgo pull request #2076
Opened 2021-01-30 20:17 UTC by 07yuvraj

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-02-04 15:42 UTC, HarshCasper requested changes

2021-02-04 15:42 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +-[Infix to Postfix Conversiion](stack/Infix_to_Postfix.c)
Typo in the spelling of conversion

2021-02-04 15:42 UTC, HarshCasper commented on C-Plus-Plus/stack/Infix_to_Postfix.c
> +#include <stdio.h>
Add a description about what your algorithm does

2021-02-04 15:42 UTC, HarshCasper commented on C-Plus-Plus/stack/Infix_to_Postfix.c
> +}
Format the Code using a C++ Formatter

2021-02-04 15:42 UTC, HarshCasper commented on C-Plus-Plus/stack/Infix_to_Postfix.c
> +    postfix[j]='\0';
Put apt comments here

2021-02-07 16:59 UTC, HarshCasper commented
Are you working on the same @07yuvraj ?

2021-02-07 20:30 UTC, 07yuvraj commented
> Are you working on the same @07yuvraj ?

Actually this was done by mistake I changed the readme file and it was done on another branch

2021-02-07 20:30 UTC, closed without merging