Adding BucketSort and SelectionSort in JavaScript
HarshCasper/NeoAlgo pull request #2091
Opened 2021-02-01 06:08 UTC by rushi-173

I have added BucketSort and SelectionSort algorithms in javascript

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-02-07 11:13 UTC, iamrajiv requested changes
@rushi-173 Please update the README file.

2021-02-08 17:28 UTC, atarax665 requested changes

2021-02-08 17:28 UTC, atarax665 commented on JavaScript/sort/BucketSort.js
> +function bucketSort(arr, bucketSize) {
Add a beginner pitch of the algorithm along with space and time complexity in commented form.

2021-02-08 17:28 UTC, atarax665 commented on JavaScript/sort/BucketSort.js
> +}
Please add driver code.

2021-02-13 10:46 UTC, HarshCasper commented
Is it being worked on @rushi-173 ?

2021-02-13 11:47 UTC, HarshCasper commented
Please work only on those Issues that you are assigned. The original assignee is @Sloth-Panda

2021-02-13 11:47 UTC, closed without merging