Sleep sort in python
HarshCasper/NeoAlgo pull request #2092
Opened 2021-02-01 18:02 UTC by sakshikhachane

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)? 

Yes

### Description

Added Sleep sort in python.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes: #2018

2021-02-08 01:49 UTC, sakshikhachane commented
@atarax665 Please review the PR.

2021-02-09 17:33 UTC, atarax665 requested changes

2021-02-09 17:33 UTC, atarax665 commented on Python/sort/Sleep_sort.py
> +'''
Add a blank line at the EOF.

2021-02-09 17:33 UTC, atarax665 commented on Python/sort/Sleep_sort.py
> +#    Sleep sort is a sorting algorithm used to sort non-negative integers. Sleep sort works by creating a separate thread for each item in the input which is to be sorted and then each thread sleeps
Use doc string here.

2021-02-09 17:42 UTC, sakshikhachane commented on Python/sort/Sleep_sort.py
> +'''
Done

2021-02-09 17:42 UTC, sakshikhachane commented on Python/sort/Sleep_sort.py
> +#    Sleep sort is a sorting algorithm used to sort non-negative integers. Sleep sort works by creating a separate thread for each item in the input which is to be sorted and then each thread sleeps
Done

2021-02-09 17:43 UTC, sakshikhachane commented
@atarax665 I have done all the changes that were requested.

2021-02-12 17:14 UTC, atarax665 requested changes

2021-02-12 17:14 UTC, atarax665 commented on Python/sort/Sleep_sort.py
> +
Put the driver code inside ```if __name__ == "__main__"``` block.

2021-02-13 16:39 UTC, sakshikhachane commented on Python/sort/Sleep_sort.py
> +
@atarax665 Done.

2021-02-13 17:50 UTC, atarax665 approved these changes

2021-02-17 08:00 UTC, sakshikhachane commented
@atarax665 Are there any changes to be done?

2021-02-20 14:48 UTC, sakshikhachane commented
@atarax665 @HarshCasper Is there any change that is to be done? If not please merge this PR.

2021-02-20 16:24 UTC, atarax665 approved these changes

2021-02-20 16:24 UTC, merged