adde higher order array methods
HarshCasper/NeoAlgo pull request #2104
Opened 2021-02-05 15:51 UTC by Sloth-Panda

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description

(Write your answer here.)
Added higher order array methods
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2059

2021-02-05 15:51 UTC, Sloth-Panda commented
I am  a part of DWOC @HarshCasper

2021-02-06 18:09 UTC, Sloth-Panda commented
can you please also add level to it @atarax665

2021-02-09 16:07 UTC, atarax665 requested changes

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/filter.js
> +//The filter() method takes each element in an array and it applies a conditional statement against it.If this conditional returns true, the element gets pushed to the output array. If the condition
Break such long comments in small multi-line comments.

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/filter.js
> +console.log(evens); // [2, 4]
Shift the output below the code.

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/map.js
> +
Remove this blank line.

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/map.js
> +console.log(doubled); // [2, 4, 6, 8]
Shift the output below this line.

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/map.js
> +
Remove this extra blank line.

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/map.js
> +console.log(sub); // [-1, 0, 1, 2]
Shift the output below the code and add a blank line at the end of file.

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/sort.js
> +    .map(number => number * 2)  // [30, 4, 100, 110, 180, 10, 8, 18, 20]//
Shift the output below the respective lines of code.

2021-02-09 16:07 UTC, atarax665 commented on JavaScript/other/sort.js
> +console.log(result); // Answer is 425
Add a blank line at the end of the file.

2021-02-09 16:43 UTC, Sloth-Panda commented
https://github.com/TesseractCoding/NeoAlgo/pull/2112/commits/2fa7a1610cc5d5e4b708ba77443f91b0ba81cfc5

@atarax665  I have updated the file this is actually the updated commit mistakenly pushed to master from a different branch take a look

2021-02-14 16:07 UTC, Sloth-Panda commented
@HarshCasper @atarax665 can anyone check this its been 9-10 days now

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/filter.js
> +//The filter() method takes each element in an array and it applies a conditional statement against it.If this conditional returns true, the element gets pushed to the output array. If the condition
It has not been resolved

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/sort.js
> +console.log(result); // Answer is 425
Not done yet

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/filter.js
> +console.log(evens); // [2, 4]
Not done yet

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/map.js
> +
Not done yet

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/map.js
> +console.log(doubled); // [2, 4, 6, 8]
Not done yet

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/map.js
> +
Not done yet

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/map.js
> +console.log(sub); // [-1, 0, 1, 2]
Not done yet

2021-02-24 03:57 UTC, HarshCasper commented on JavaScript/other/sort.js
> +    .map(number => number * 2)  // [30, 4, 100, 110, 180, 10, 8, 18, 20]//
Not done yet

2021-02-24 04:01 UTC, HarshCasper requested changes

2021-02-24 04:01 UTC, HarshCasper commented on JavaScript/other/filter.js
> +//The filter() method takes each element in an array and it applies a conditional statement against it.If this conditional returns true, the element gets pushed to the output array. If the condition
@Sloth-Panda Please don't unresolve Comments if you have not actually resolved them. This defeats the purpose of putting a review and we obviously don't want to re-review such PRs.

2021-02-24 04:01 UTC, HarshCasper commented on JavaScript/other/filter.js
> +console.log(evens); // [2, 4]
What is the meaning of resolving conversations when you have not actually made the updates?

2021-02-24 04:02 UTC, HarshCasper commented
> @HarshCasper @atarax665 can anyone check this its been 9-10 days now

Please make the changes as we suggested. Resolving the comments, without actually making the updates, defeats the purpose of having a PR review.

2021-03-02 08:33 UTC, closed without merging