Implementation in Java #1999
HarshCasper/NeoAlgo pull request #2111
Opened 2021-02-07 17:04 UTC by Amit366

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is the last part of implementation in Java #1999

2021-02-11 17:29 UTC, atarax665 reviewed
The code looks copied from Geeks For Geeks.

2021-02-12 03:52 UTC, Amit366 commented
@atarax665 sir check it now.

2021-02-12 03:54 UTC, Amit366 commented
And also please add the tags for this merged PR.
https://github.com/TesseractCoding/NeoAlgo/pull/2058

2021-02-13 08:31 UTC, HarshCasper requested changes

2021-02-13 08:31 UTC, HarshCasper commented on Java/cp/Longest_Pallindromicsubstring.java
> +}
Add sample I/O and a new line at the EOF

2021-02-13 08:31 UTC, HarshCasper commented on Java/cp/Longest_Pallindromicsubstring.java
> +// Java solution for longest palindrome in a substring
Add a beginner pitch about your Code/Algorithm

2021-02-13 08:31 UTC, HarshCasper commented on Java/cp/Longest_Pallindromicsubstring.java
> +    // get length of input String
Isn't the comment kinda redundant? 

![image](https://user-images.githubusercontent.com/47351025/107845725-ddcba480-6e03-11eb-8497-af9e0aae9278.png)

2021-02-13 08:31 UTC, HarshCasper commented
> @atarax665 sir check it now.

Do you actually mean that you picked code from GFG and edited it later? If yes, we would have to close the PR on grounds of plagiarms

2021-02-13 08:51 UTC, Amit366 commented
@HarshCasper sir if you feel it is a copy of GFG then you can compare it.

2021-02-13 10:55 UTC, HarshCasper commented
Not all my reviews are taken care of. Take a look at them and resolve the same.

2021-02-13 12:36 UTC, Amit366 commented
@HarshCasper sir what should be the beginning pitcher??

2021-02-13 17:44 UTC, atarax665 commented
> @HarshCasper sir what should be the beginning pitcher??

Beginner Pitch includes introduction of the problem that your code solves and description of your approach to solve it.

2021-02-14 04:13 UTC, Amit366 commented
@HarshCasper sir now is it fine??

2021-02-15 18:25 UTC, atarax665 commented on Java/cp/Longest_Pallindromicsubstring.java
> +// This is a Java program  to find the longest palindromicsubstring from a word using dynamic programming approach
Go through some merged PR to get a better idea of how to write a beginner pitch of a program.

2021-02-16 05:06 UTC, Amit366 commented
@atarax665 I have gone through some of the merged PRs. In some there are no beginner pitch and in others it is written similar to mine.

2021-02-16 05:07 UTC, Amit366 commented
And already my 3 PRs have been merged and  in them I have written in this manner then what's the problem in this??

2021-02-21 17:33 UTC, atarax665 commented
> And already my 3 PRs have been merged and in them I have written in this manner then what's the problem in this??

Okay, atleast explain what is a palindromic string with example and then this PR will be good to go.

2021-02-22 06:51 UTC, Amit366 commented
@atarax665 please review now

2021-02-22 06:57 UTC, HarshCasper approved these changes

2021-02-22 06:57 UTC, merged