added solution two reverse No. using bits
HarshCasper/NeoAlgo pull request #2113
Opened 2021-02-08 14:19 UTC by rcoder23

Added solution two reverse 2 numbers  #2095

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Here , We can swap 2 Numbers using bit manipulation (XOR operations ) .
It's faster way to swap two variables .

### Checklist

- [Y ] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2095
(Write your answer here.)

2021-02-13 16:39 UTC, iamrajiv requested changes
@rcoder23 Add sample input-output, time complexity and space complexity.

2021-02-19 17:26 UTC, atarax665 requested changes

2021-02-19 17:26 UTC, atarax665 commented on Java/bit_manipulation/swap.java
> +Example No1:- Let a=5 and b=10
Please go through some recently merged Java PRs to get a better idea of the standard Java Template that we use.

2021-02-24 05:18 UTC, HarshCasper commented
@rcoder23 Are you still working on it?

2021-02-24 13:53 UTC, rcoder23 commented
@HarshCasper yes updated.

2021-02-24 13:54 UTC, rcoder23 commented
@HarshCasper How i can join organization.?

2021-02-25 07:18 UTC, HarshCasper commented
Make README updates as well. 

@rcoder23 Which organization are you looking to join?

2021-02-27 18:15 UTC, atarax665 requested changes

2021-02-27 18:15 UTC, atarax665 commented on Java/bit_manipulation/swap.java
> +		System.out.println("Enter No a=");
```suggestion
		System.out.println("Enter No b=");

```

2021-02-27 18:15 UTC, atarax665 commented on Java/bit_manipulation/swap.java
> +		a=a^b;
Move the logic part to a new function, the main function should only have the driver code.

2021-02-28 03:36 UTC, rcoder23 reviewed
separate logic code and driver code

2021-03-03 03:35 UTC, HarshCasper commented
Make the README.md updates as well

2021-03-13 16:07 UTC, atarax665 commented
Closing due to inactivity.

2021-03-13 16:07 UTC, closed without merging