Matrix chain multiplication
HarshCasper/NeoAlgo pull request #2130
Opened 2021-02-13 20:21 UTC by smriti1313

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes

### Description

added matrix chain multiplication algorithm using dynamic programming

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue: #2094 
pull request #2123

2021-02-25 07:11 UTC, HarshCasper requested changes
Please revert the README changes. 

We can have a separate issue for that

2021-02-25 07:11 UTC, HarshCasper commented on Python/dp/matrix_chain_multiplication.py
> +print(print_matrix_chain(s, 1, 3))
Add this in a `if __name__ == '__main__'` block

2021-02-25 07:11 UTC, HarshCasper commented on Python/dp/matrix_chain_multiplication.py
> +        return s
Use meaningful variable names

2021-02-25 07:11 UTC, HarshCasper commented on Python/dp/matrix_chain_multiplication.py
> +def matrix_chain_order(p):
Add function docstring

2021-02-25 07:11 UTC, HarshCasper commented on Python/dp/matrix_chain_multiplication.py
> +def matrix(m, n):
Add function docstring

2021-02-25 07:11 UTC, HarshCasper commented on Python/dp/matrix_chain_multiplication.py
> +def chain_matrix_multiplication(matrices, i, j):
Add function docstring

2021-03-13 16:09 UTC, atarax665 commented
No update!

2021-03-13 16:09 UTC, closed without merging