Added AVL tree
HarshCasper/NeoAlgo pull request #2131
Opened 2021-02-14 03:03 UTC by sakshikhachane

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

AVL tree in Java. AVL tree is a self-balancing Binary Search Tree (BST).

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Solves : #2065

2021-02-14 03:05 UTC, sakshikhachane commented
@atarax665 Please review the PR.

2021-02-16 17:08 UTC, atarax665 commented on Java/ds/AVL_Tree.java
> +    AVL tree is a self-balancing Binary Search Tree (BST) where the difference between heights of left and right subtrees cannot be more than one for all nodes and if at any time they differ by more
Justify align this description part.

2021-02-17 08:08 UTC, sakshikhachane commented on Java/ds/AVL_Tree.java
> +    AVL tree is a self-balancing Binary Search Tree (BST) where the difference between heights of left and right subtrees cannot be more than one for all nodes and if at any time they differ by more
@atarax665 Is it okay now?

2021-02-20 14:46 UTC, sakshikhachane commented
@atarax665 Are there any changes required?

2021-02-22 06:40 UTC, HarshCasper requested changes
A small change required. The rest looks good. 

Please ping me on Discord once the changes are done. Thanks!

2021-02-22 06:40 UTC, HarshCasper commented on Java/ds/AVL_Tree.java
> +AVL tree is a self-balancing Binary Search Tree (BST) where the difference between heights of left and right subtrees cannot be more than one for all nodes and if at any time they differ by more than
Break this line into multiple smaller lines and justify the content. Even on a Desktop, its difficult to read

2021-02-22 07:03 UTC, HarshCasper approved these changes

2021-02-22 07:03 UTC, merged