feat: Added Bead Sort in C++
HarshCasper/NeoAlgo pull request #2132
Opened 2021-02-14 07:36 UTC by m-code12

### Fixes
#2072 

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2021-02-14 07:37 UTC, m-code12 commented
@HarshCasper @atarax665 Please review this pr.

2021-02-20 07:59 UTC, HarshCasper requested changes

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +        for(auto j = 0; j < nums[i]; j++)
Push all your core code logic into another function. Keep the main() function solely for the driver code.

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +bead sort is implemented without a mechanism to assist in finding empty spaces below the beads, such as in software implementations.
No need to explain them. Just mention all the complexities plainly.

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +to the manner in which beads slide on parallel poles, such as on an abacus. However, each pole may have a distinct number of beads.*/
Make it more compact and justify the formatting. It should be easy to read and consume

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +    for(int i=0;i<n;i++){                       //For loop for taking elements from the user, can be space-seperated as well
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +    nums.reserve(n);                        // reserve static vector for optimal performance gain
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +    auto max = *max_element(nums.begin(), nums.end());      // find maximum element in vector
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +    for(auto i = 0; i < nums.size(); i++)                   // initialize the beads accordingly
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +    cout << "After sorting" << endl;               //For loop for printing out the array after sorting
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +    nums.shrink_to_fit();               // Free memory space of vector
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +using namespace std;               //For cin and cout
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +    int a,n;                                    // Declaration of required variables
Keep the Comments above the Line of Code

2021-02-20 07:59 UTC, HarshCasper commented on C-Plus-Plus/sort/Bead_Sort.cpp
> +
Remove the extra line

2021-02-23 10:38 UTC, m-code12 commented
@HarshCasper I have made all the changes, please could you review it.

2021-02-23 17:34 UTC, m-code12 commented
@atarax665 Can you review and merge this?

2021-02-24 05:23 UTC, HarshCasper commented
@m-code12 Make the README updates as well

2021-02-24 05:43 UTC, m-code12 commented
> @m-code12 Make the README updates as well

@HarshCasper Done

2021-02-25 06:50 UTC, HarshCasper approved these changes

2021-02-25 06:50 UTC, merged

2021-02-26 09:12 UTC, m-code12 commented
@HarshCasper Please could you add the relevant labels