Added dynamic Prims and Kruskals algorithm.
HarshCasper/NeoAlgo pull request #2145
Opened 2021-02-17 16:36 UTC by Tanmay2510

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-02-20 07:53 UTC, HarshCasper requested changes
Please make these changes initially.

2021-02-20 07:53 UTC, HarshCasper commented on .classpath
> +</classpath>
Remove this

2021-02-20 07:53 UTC, HarshCasper commented on .gitignore
> +/bin/
Remove this

2021-02-20 07:53 UTC, HarshCasper commented on .project
> +</projectDescription>
Remove this

2021-02-20 07:53 UTC, HarshCasper commented on Java/Algorithms/Kruskals_Algorithm.java
> +//import java.util.Scanner;
Add a beginner-friendly pitch about the Algorithm and what it does.

2021-02-20 07:53 UTC, HarshCasper commented on Java/Algorithms/Kruskals_Algorithm.java
> +		return this.weight - o.weight;  //To Sort in increasing order
Use comments above the line of code and not beside it

2021-02-20 07:53 UTC, HarshCasper commented on Java/Algorithms/Kruskals_Algorithm.java
> +
Remove these extra lines of code

2021-02-20 07:53 UTC, HarshCasper commented on Java/Algorithms/Kruskals_Algorithm.java
> +        Edge input[] = new Edge[E];
Improper indentation. Fix it!

2021-02-20 07:53 UTC, HarshCasper commented on Java/Algorithms/Kruskals_Algorithm.java
> +		for(int j=0;j<v-1;j++) {
Poorly formatted Code. Use a Code formatter to format your Code properly

2021-02-20 18:26 UTC, Tanmay2510 commented
Hey, Now can you review my pull request @HarshCasper

2021-02-24 05:22 UTC, HarshCasper commented
Why is the `.gitignore` deleted? 

And make the README updates for all of your Code files.

2021-02-24 07:56 UTC, Tanmay2510 commented
There is no Readme file in Java algorithm folder @HarshCasper.

2021-02-24 08:07 UTC, Tanmay2510 commented
I have updated the Readme file can you check it @HarshCasper ?

2021-02-24 08:53 UTC, Tanmay2510 commented
> Why is the `.gitignore` deleted?
> 
> And make the README updates for all of your Code files.

Can you please help me with the .gitignore file ?

2021-02-25 07:08 UTC, HarshCasper commented
> > Why is the `.gitignore` deleted?
> > And make the README updates for all of your Code files.
> 
> Can you please help me with the .gitignore file ?

What help is required?

2021-02-25 07:08 UTC, HarshCasper commented
> I have updated the Readme file can you check it @HarshCasper ?

Nope. You have not updated it.

2021-02-25 09:28 UTC, Tanmay2510 commented
Are you able to see the changes @HarshCasper @atarax665 ?
![Screenshot 2021-02-25 151147](https://user-images.githubusercontent.com/78039581/109132504-eadc8200-7779-11eb-9dd3-d22d1bd4de27.jpg)
![Screenshot 2021-02-25 151147](https://user-images.githubusercontent.com/78039581/109132517-eca64580-7779-11eb-8090-56173cdddd44.jpg)

2021-02-25 11:17 UTC, HarshCasper commented
We are not familiar with this UI tool which you are using to visualize the Git branching and commits. Have a look [here](https://github.com/TesseractCoding/NeoAlgo/pull/2145/files) and see all the changes being pushed by you in your commits.

2021-02-26 09:27 UTC, closed without merging