Added In-place heap sort and Max. Priority Queue using java
HarshCasper/NeoAlgo pull request #2150
Opened 2021-02-18 11:22 UTC by Tanmay2510

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-02-19 17:26 UTC, atarax665 reviewed
Remove all the irrelevant files.

2021-02-20 17:45 UTC, Tanmay2510 commented
Hey, i have removed the irrelevant files. Now can you review my pull request @atarax665

2021-02-21 17:59 UTC, atarax665 requested changes

2021-02-21 17:59 UTC, atarax665 commented on Java/ds/MaxPriorityQueue.java
> +//Implementing the class for Max Priority Queue which includes the required functions......
Add an introduction of what is a Max Priority Queue.

2021-02-21 17:59 UTC, atarax665 commented on Java/ds/MaxPriorityQueue.java
> +}
Add driver code and add sample input/output.

2021-02-21 17:59 UTC, atarax665 commented on Java/sort/InplaceHeapSort.java
> +         int n = arr.length;
Inconsistent indentation.

2021-02-21 17:59 UTC, atarax665 commented on Java/sort/InplaceHeapSort.java
> +
Remove all the unnecessary blank lines.

2021-02-21 17:59 UTC, atarax665 commented on Java/sort/InplaceHeapSort.java
> +
Add driver code and sample input/output.

2021-02-22 08:42 UTC, Tanmay2510 commented
Can you review the file @atarax665? I have made the required changes in file.

2021-02-24 08:29 UTC, Tanmay2510 commented
Hey, I have updated the readme file  and made all the needy changes. Can you review my pull request @HarshCasper @atarax665 ?

2021-02-24 17:33 UTC, atarax665 requested changes
Please do not remove  ```.gitignore```. Add driver code.

2021-02-25 07:08 UTC, HarshCasper requested changes

2021-02-25 07:08 UTC, HarshCasper commented on Java/sort/InplaceHeapSort.java
> +// 8 6 5 4 3 2
Add them in a multi-line comment

2021-02-25 07:08 UTC, HarshCasper commented on Java/sort/InplaceHeapSort.java
> +	}
Properly indent the Code

2021-02-25 07:08 UTC, HarshCasper commented on Java/ds/MaxPriorityQueue.java
> +// 12 10 8 6 4 2
Add in a multi-line comment

2021-02-25 09:02 UTC, Tanmay2510 commented
Can you see the changes now @HarshCasper @atarax665 ?
![Screenshot 2021-02-25 144518](https://user-images.githubusercontent.com/78039581/109129092-43118500-7776-11eb-8d90-390b55b8cddc.jpg)

2021-02-25 11:18 UTC, HarshCasper commented
We are not familiar with this UI tool which you are using to visualize the Git branching and commits. Have a look [here](https://github.com/TesseractCoding/NeoAlgo/pull/2150/files) and see all the changes being pushed by you in your commits.

2021-02-26 09:50 UTC, closed without merging