added selection sort
HarshCasper/NeoAlgo pull request #2169
Opened 2021-02-23 21:13 UTC by Sloth-Panda

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
(Write your answer here.)

### Description

(Write your answer here.)

This is selection sort implemented in js and explained with description too.
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2075

2021-02-23 21:14 UTC, Sloth-Panda commented
@HarshCasper please take a look into it.

2021-02-24 04:29 UTC, HarshCasper requested changes

2021-02-24 04:29 UTC, HarshCasper commented on JavaScript/sort/SelectionSort.js
> +(5)[1, 2, 12, 19, 34] /*output*/
This is an entirely bad code example 🤦 

Keep the sample I/O in a multi-line comment just for better understanding. And add a line at the end of the file

2021-02-24 04:29 UTC, HarshCasper commented on JavaScript/sort/SelectionSort.js
> +let inputArray = [12, 2, 34, 1, 19];
Make the input dynamic

2021-02-24 04:29 UTC, HarshCasper commented on JavaScript/sort/SelectionSort.js
> +unsorted array boundary by one element to the right. */
Justify the content and use proper sentences

2021-02-27 09:07 UTC, closed without merging