add knapsack fraction problem using greedy appraoch.
HarshCasper/NeoAlgo pull request #2174
Opened 2021-02-24 09:05 UTC by bagladivyang03

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-02-24 09:06 UTC, bagladivyang03 commented
@HarshCasper Could u pls review and merge it :)

2021-02-25 05:53 UTC, HarshCasper requested changes

2021-02-25 05:53 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +*/
Add a new line at the EOF

2021-02-25 05:53 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +#include<iostream>
Add a beginner pitch about the Code/Approach

2021-02-25 05:53 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +            profit[j+1] = temp;
Put apt comments explaining the Code

2021-02-25 05:53 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    sort_arr(ratio,profit,weight,n);
Inconsistent indentation and formatting

2021-02-25 05:53 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    cout<<"the maximum profit is : "<<ans<<endl;
Use properly formatted console statements

2021-02-27 16:08 UTC, bagladivyang03 commented
@HarshCasper could u check now

2021-03-02 13:56 UTC, bagladivyang03 commented
@HarshCasper could u pls check :)

2021-03-03 03:32 UTC, HarshCasper requested changes
Tiny changes needed. Rest looks good to merge.

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    int ans = knapsack_fraction(weight, ratio, profit, n, capacity); //call the function to calculate max profit.
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +void sort_arr(float ratio[], float profit[], float weight[], int n) // A function to sort the arrays according to profit/weight
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +int knapsack_fraction(float weight[], float ratio[], float profit[], int n, int capacity) //function to calculate max value in knapsack.
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    for (i = 0; i < n; i++) //iterating over all items
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +        if (weight[i] > capacity) //checking if current weight is greater tahn break i.e this weight can't be put into knapsack.
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +        else //else add profir to final varibale i.e max profit and update capacity accordingly
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    if (i < n) //for fraction amount of item
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    for (i = 0; i < n; i++) //accepting the profit and weight values for given value of n.
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    for (i = 0; i < n; i++) //making the new array and storing ratio (profit/weight)
Comments should be made above the line of code, not beside it

2021-03-03 03:32 UTC, HarshCasper commented on C-Plus-Plus/other/knapsackfraction.cpp
> +    sort_arr(ratio, profit, weight, n); //first sort the array acc to Profit/weight
Comments should be made above the line of code, not beside it

2021-03-03 05:22 UTC, bagladivyang03 commented
@HarshCasper Could u pls check now :)

2021-03-03 14:29 UTC, HarshCasper approved these changes

2021-03-03 14:29 UTC, merged