Added Bead Sort in C
HarshCasper/NeoAlgo pull request #2184
Opened 2021-02-25 13:09 UTC by m-code12

Fixes: #2072

2021-02-25 13:14 UTC, m-code12 commented
@HarshCasper @atarax665 Could you review this pr?

2021-02-25 13:48 UTC, HarshCasper requested changes
Make the README changes as well. Fit to merge 👍

2021-02-25 13:48 UTC, HarshCasper commented on C/sort/beadSort.c
> +	}
Push the core code logic into a separate function and use the main() function for driver code

2021-02-25 14:30 UTC, m-code12 commented
@HarshCasper Made the changes

2021-02-25 17:42 UTC, atarax665 requested changes
Just some minor fixes and then it would be good to merge.

2021-02-25 17:42 UTC, atarax665 commented on C/sort/beadSort.c
> +	int n,i,k;
```suggestion
	int n, i, k;
```

2021-02-25 17:42 UTC, atarax665 commented on C/sort/beadSort.c
> +	for(i=0;i<n;i++){
```suggestion
	for(i = 0; i < n; i++){
```

2021-02-25 17:42 UTC, atarax665 commented on C/sort/beadSort.c
> +    bead_sort(nums, n);
Inconsistent indentation.

2021-02-25 18:06 UTC, m-code12 commented
@atarax665 Made all the changes

2021-02-26 07:00 UTC, HarshCasper approved these changes

2021-02-26 07:00 UTC, merged