Added Prim and Kruskal's Algorithm.
HarshCasper/NeoAlgo pull request #2188
Opened 2021-02-26 09:22 UTC by Tanmay2510

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-02-26 10:00 UTC, Tanmay2510 commented
Can you review the new pull request @HarshCasper ?

2021-02-27 17:56 UTC, atarax665 requested changes

2021-02-27 17:56 UTC, atarax665 commented on .gitignore
> +
This change is irrelevant.

2021-02-27 17:56 UTC, atarax665 commented on Java/Algorithms/KruskalS_Algorithm.java
> +                int Vertices = scan.nextInt();
Inconsistent indentation.

2021-02-27 17:56 UTC, atarax665 commented on Java/Algorithms/KruskalS_Algorithm.java
> + }
Add sample Input/Output and space, time complexity in commented form.

2021-02-27 17:56 UTC, atarax665 commented on Java/Algorithms/KruskalS_Algorithm.java
> +//It is an algroithm that help us to figure out the Minimum Spanning Tree of a given graph.
Enclose the description in multiline comment.

2021-02-27 17:56 UTC, atarax665 commented on Java/Algorithms/Prim_Algorithm.java
> +//It is an algorithm that help us to figure out  minimum spanning tree by selecting the adjacent vertices of already selected vertices.
Enclose the description in multiline comment.

2021-02-27 17:56 UTC, atarax665 commented on Java/Algorithms/Prim_Algorithm.java
> +}
Add sample Input/Output and space, time complexity in commented form.

2021-02-27 17:56 UTC, atarax665 commented on Java/README.md
> +- [Prim Algorithm](Algorithms/Prim_Algorithm.java
```suggestion
- [Prim Algorithm](Algorithms/Prim_Algorithm.java)
```

2021-03-01 14:48 UTC, Tanmay2510 commented
Please review it @HarshCasper @atarax665 .

2021-03-03 03:34 UTC, HarshCasper requested changes

2021-03-03 03:34 UTC, HarshCasper commented on Java/Algorithms/KruskalS_Algorithm.java
> +                int Vertices = scan.nextInt();
Not resolved.

2021-03-03 03:34 UTC, HarshCasper commented on Java/Algorithms/KruskalS_Algorithm.java
> +                Edge input[] = new Edge[Edges];
Inconsistent Indentation

2021-03-03 03:34 UTC, HarshCasper commented on Java/README.md
> +
Revert this back

2021-03-03 03:34 UTC, HarshCasper commented on Java/Algorithms/Prim_Algorithm.java
> +       }
Fix the indentation

2021-03-03 03:34 UTC, HarshCasper commented on Java/Algorithms/Prim_Algorithm.java
> +	}
Format the Code

2021-03-03 03:34 UTC, HarshCasper commented on Java/Algorithms/KruskalS_Algorithm.java
> +/*
Format the Code

2021-03-13 16:19 UTC, atarax665 commented
Please make a new PR or squash the commits before I merge this.

2021-03-13 16:19 UTC, closed without merging