Added In-place heap sort and Max Priority Queue.
HarshCasper/NeoAlgo pull request #2189
Opened 2021-02-26 09:47 UTC by Tanmay2510

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-02-26 09:59 UTC, Tanmay2510 commented
Can you review the new pull request @HarshCasper ?

2021-02-26 17:25 UTC, atarax665 requested changes
- Add driver code in both the programs.
- Update README for Max Priority Queue too.

2021-02-26 17:25 UTC, atarax665 commented on Java/README.md
> +=======
Remove all these irrelevant lines that have been pushed due to improper use of git commands.

2021-02-26 17:25 UTC, atarax665 commented on Java/ds/maxPriorityQueue.java
> +//Implementing the class for Max Priority Queue which includes the required functions......
Enclose the description in multi-line comment.

2021-02-27 01:15 UTC, atarax665 requested changes

2021-02-27 01:15 UTC, atarax665 commented on Java/ds/maxPriorityQueue.java
> +       h.insert(array, 6);
Take dynamic inputs.

2021-02-27 01:15 UTC, atarax665 commented on Java/sort/InPlaceHeapsort.java
> +          int A[] = {2, 6, 8, 5, 4, 3};
Take dynamic inputs.

2021-03-01 14:47 UTC, Tanmay2510 commented
Please review it @atarax665 @HarshCasper .

2021-03-01 17:29 UTC, atarax665 requested changes

2021-03-01 17:29 UTC, atarax665 commented on Java/ds/maxPriorityQueue.java
> +				case 1 : // insert
If you are making a menu driven program then make sure you prompt user all the available choices as a program like this should be much more interactive.

2021-03-01 17:29 UTC, atarax665 commented on Java/ds/maxPriorityQueue.java
> + Sample Input
Sample I/O should be exactly what once you see on the terminal when they run this program. Please demonstrate all the functionalities of the program.

2021-03-01 17:29 UTC, atarax665 commented on Java/ds/maxPriorityQueue.java
> +                st = new StringTokenizer(br.readLine());
There is inconsistent indentation throughout the code, please use any java formatter to format your code.

2021-03-13 16:17 UTC, atarax665 commented
You have not resolved all the conversations. Request review only when you are done with the requested changes.

2021-03-13 16:17 UTC, closed without merging