Merging two Linked List using c
HarshCasper/NeoAlgo pull request #2197
Opened 2021-03-01 15:43 UTC by saimanoharhm

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes
### Description

(Write your answer here.)
I have added code for Merging two Linked List using c
### Checklist

- [ yes] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2171

2021-03-01 15:44 UTC, saimanoharhm commented
@gat786 Could you pls review my PR

2021-03-02 02:54 UTC, gat786 commented
Add an example of what happens. 
Add a line break at the End Of File(EOF).
@saimanoharhm

2021-03-02 05:53 UTC, saimanoharhm commented
@gat786 I didn't get you. What Example do you want me to add and break at eof

2021-03-02 05:53 UTC, saimanoharhm commented
@gat786 Could you pls explain me more eloboratly

2021-03-02 15:07 UTC, vgb-codes commented
@saimanoharhm Please update the [README.md](https://github.com/TesseractCoding/NeoAlgo/blob/master/C/README.md).

2021-03-03 03:27 UTC, HarshCasper commented
Thanks for making your Pull Request!

PRs would be reviewed after the start of the Coding Period. Thanks!

2021-03-03 11:39 UTC, gat786 commented
@saimanoharhm An Example will be an example of how one would use your piece of code. Suppose I wrote a program to add two numbers then my example would be 

```
First Number: 12
Second Number: 25
Addition is: 37
```

Like a dummy example of how some one would run your piece of code.

And this [link](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) should clear your mind on why we have a line break at the end of every file.

2021-03-03 14:00 UTC, saimanoharhm commented
> @saimanoharhm Please update the [README.md](https://github.com/TesseractCoding/NeoAlgo/blob/master/C/README.md).

I have already updated it. Pls check PR #2198

2021-03-03 14:05 UTC, saimanoharhm commented
> @saimanoharhm An Example will be an example of how one would use your piece of code. Suppose I wrote a program to add two numbers then my example would be
> 
> ```
> First Number: 12
> Second Number: 25
> Addition is: 37
> ```
> 
> Like a dummy example of how some one would run your piece of code.
> 
> And this [link](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) should clear your mind on why we have a line break at the end of every file.

@gat786 Ok I got it! but where do you want me to add it at the end of the program by putting output as a heading or where?

2021-03-03 14:06 UTC, saimanoharhm commented
> @saimanoharhm Please update the [README.md](https://github.com/TesseractCoding/NeoAlgo/blob/master/C/README.md).

@vgb-codes  I have already updated it. Pls check PR #2198

2021-03-03 14:12 UTC, gat786 commented
Whereever you feel like it. Poeple usually add it at the bottom of their programs

2021-03-08 03:55 UTC, HarshCasper commented
@saimanoharhm 

Please make your README updates here itself. Thanks!

2021-03-08 04:32 UTC, saimanoharhm commented
@HarshCasper and @gat786 Could you check it now I have updated readme file and added example output as comment. Pls let me know if further changes needed

2021-03-10 05:15 UTC, saimanoharhm commented
@HarshCasper Could you pls check my PR.

2021-03-10 11:10 UTC, HarshCasper requested changes
Few changes: 

- Resolve the Merge Conflicts. 
- Add Comments above the lines of code wherever possible

2021-03-11 10:47 UTC, saimanoharhm commented
@HarshCasper Could you pls check it now. I have done all the changes that you asked.

2021-03-13 16:51 UTC, HarshCasper requested changes
Use a 4-spaces formatting

2021-03-13 16:51 UTC, HarshCasper commented on C/ds/Merging_two_Linked_List.c
> +and convert into one linkelist in the ascending order.
Not gramatically correct: 
- Replace `Linkedlist` with `Linked List`
- Here `the` user `is` going...

2021-03-15 12:19 UTC, HarshCasper requested changes
Few more changes: 
- Don't use variable names like `A`, `B`, `t` and all. Use meaningful variable names
- Share the complexity of the code
- Put spaces after functions 
- Remove some redundant comments

2021-03-16 18:04 UTC, HarshCasper approved these changes

2021-03-16 18:04 UTC, merged