Add Shamir's Secret Sharing cryptographic algorithm in C-Plus-Plus
HarshCasper/NeoAlgo pull request #2199
Opened 2021-03-02 11:13 UTC by pganguli

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have.

### Description

Adds Shamir's Secret Sharing cryptographic algorithm in C++.

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #2140 .

2021-03-03 03:26 UTC, HarshCasper commented
Thanks for making your Pull Request!

PRs would be reviewed after the start of the Coding Period. Thanks!

2021-03-03 04:34 UTC, pganguli commented
> Thanks for making your Pull Request!
> 
> PRs would be reviewed after the start of the Coding Period. Thanks!

As per the [GSSOC'21 schedule](https://gssoc.girlscript.tech/schedule.html), I was under the impression that the coding period would have started from the 1st of March. Can you please let me know when it really starts from? Thanks!

2021-03-03 06:14 UTC, HarshCasper commented
> > Thanks for making your Pull Request!
> > PRs would be reviewed after the start of the Coding Period. Thanks!
> 
> As per the [GSSOC'21 schedule](https://gssoc.girlscript.tech/schedule.html), I was under the impression that the coding period would have started from the 1st of March. Can you please let me know when it really starts from? Thanks!

The timeline has been updated and it would start from March 8, 2021. Keep an eye on the Mail.

2021-03-08 04:01 UTC, HarshCasper requested changes
Great Work! Ready to merge :tada: 

One tiny change requested, and it would be merged!

2021-03-08 04:01 UTC, HarshCasper commented on C-Plus-Plus/cryptography/README.md
> +[Shamir's Secret Sharing algorithm](cryptography/Shamir_Secret_Sharing.cpp)
We don't add programs on the individual sub-directory READMEs as of now. Please make the README changes on the language-specific README. Have a look at the existing PRs to understand this.

2021-03-08 04:16 UTC, pganguli commented on C-Plus-Plus/cryptography/README.md
> +[Shamir's Secret Sharing algorithm](cryptography/Shamir_Secret_Sharing.cpp)
Got it, thanks. Resolved now.

2021-03-10 09:10 UTC, merged