Optimized N-Queen Problem using JAVA
HarshCasper/NeoAlgo pull request #2231
Opened 2021-03-05 13:24 UTC by Shreyash41

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Implementing Optimized N-Queens Problem using Java Language.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2210

2021-03-05 17:17 UTC, atarax665 commented
Thanks for making your Pull Request!

PR would be reviewed after the start of the Coding Period. Thanks!

2021-03-08 05:07 UTC, HarshCasper requested changes

2021-03-08 05:07 UTC, HarshCasper commented on Java/cp/N_Queens_Problem_Efficient.java
> + */
Add a new line at the EOF

2021-03-08 05:07 UTC, HarshCasper commented on Java/cp/N_Queens_Problem_Efficient.java
> +package com.company;
Remove Packages

2021-03-08 05:07 UTC, HarshCasper commented on Java/cp/N_Queens_Problem_Efficient.java
> +class anaGram
Can you use more meaningful class names?

2021-03-08 05:07 UTC, HarshCasper commented on Java/cp/N_Queens_Problem_Efficient.java
> +    static int []col = new int[30];// column array
Use more meaningful variable names and use comments above the line of the code

2021-03-08 05:07 UTC, HarshCasper commented on Java/cp/N_Queens_Problem_Efficient.java
> +    static boolean solveUtil(int onBoard[][], int colo)
Add a function description

2021-03-08 05:07 UTC, HarshCasper commented on Java/cp/N_Queens_Problem_Efficient.java
> +    static void printSolution(int onBoard[][])
Add a function description

2021-03-09 03:21 UTC, HarshCasper approved these changes

2021-03-10 09:12 UTC, merged