Added program to reverse words of string in c++.
HarshCasper/NeoAlgo pull request #2237
Opened 2021-03-06 16:36 UTC by maanpatel2492

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-07 03:56 UTC, HarshCasper commented
Add the Issue Link in your PR Description. The PR would be reviewed after the Coding Period of GSSoC starts. Thanks!

2021-03-09 12:14 UTC, Simi06 commented
Can I please have this assigned to me?

2021-03-10 13:35 UTC, Vishakha-sta commented on Rev_str.cpp
> +}
/*
test case 1:
input:- 

Hello World!

output:-

World! Hello

test case 2:
input:- 

Hello     .        World!

output:-

World!        .     Hello

*/

2021-03-11 03:04 UTC, HarshCasper requested changes
Few changes: 

- Add a beginner friendly pitch at the top of the Code.
- Add Time and Space Complexity at the end of the Code
- Add sample I/O at the end of the Code
- Add comments where possible

2021-03-12 04:07 UTC, maanpatel2492 commented
> Few changes:
> 
> * Add a beginner friendly pitch at the top of the Code.
> * Add Time and Space Complexity at the end of the Code
> * Add sample I/O at the end of the Code
> * Add comments where possible

Sure.

2021-03-15 17:30 UTC, atarax665 commented
@maanpatel2492  Are you still working on this?

2021-03-16 01:47 UTC, maanpatel2492 commented
> @maanpatel2492 Are you still working on this?

Yes,

2021-03-16 03:31 UTC, HarshCasper commented
> > @maanpatel2492 Are you still working on this?
> 
> Yes,
> I have to make above changes and create pull request again right?

Make the changes in the same PR

2021-03-16 08:04 UTC, ankitaggarwal23 commented
@maanpatel2492 All contributions done by participants from 8 March in GSSoC'21 Projects will be counted. Thanks, Closing this as of now.

2021-03-16 08:05 UTC, closed without merging

2021-03-16 08:21 UTC, maanpatel2492 commented
> @maanpatel2492 All contributions done by participants from 8 March in GSSoC'21 Projects will be counted. Thanks, Closing this as of now.


There is invalid tag.Does I made any mistake.

2021-03-16 08:26 UTC, ankitaggarwal23 commented
@maanpatel2492 No there is no mistake in that the thing is we are considering the PR from 8'March'2021