Bogo Sort in Python
HarshCasper/NeoAlgo pull request #2240
Opened 2021-03-07 09:22 UTC by vybhav72954

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes 

### Description

Added Bogo Sorting in Python along with test case to illustrate the concept.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #2207

#### Additional

I can implement this in other languages as well if needed

2021-03-11 06:59 UTC, vybhav72954 commented
Hey @HarshCasper @atarax665 @anushkrishnav Any changes I need to make?

2021-03-11 07:11 UTC, anushkrishnav commented
@vybhav72954 there are some formatting issues pointed out by DeepSource fix that .

2021-03-11 07:23 UTC, vybhav72954 commented
The error is of Anti Patterns.

I have already enforced PEP-8 guidelines aggressively on my code.

The thing is
```py
"""
"""
```
arent meant for providing test cases of all things. We don't have any specific README for that purpose either. So the only solution is i combine both the test cases in one.I can do that if you want

2021-03-12 10:56 UTC, vybhav72954 commented
@HarshCasper @anushkrishnav Waiting for updates

2021-03-13 16:22 UTC, atarax665 requested changes
Please update the corresponding README too.

2021-03-13 16:22 UTC, atarax665 commented on Python/sort/Bogo_sort.py
> +import time
Add a beginner pitch of the algorithm.

2021-03-15 17:29 UTC, atarax665 commented
@vybhav72954 Any updates?

2021-03-15 17:43 UTC, vybhav72954 commented
> @vybhav72954 Any updates?

I will do this within an hour or so

2021-03-18 17:00 UTC, atarax665 approved these changes
Just update README.md so that I can merge this PR.

2021-03-23 13:29 UTC, atarax665 commented
??

2021-03-25 13:08 UTC, satyampandeygit commented
@atarax665 I can update readme.md so that it can be merged

2021-03-26 16:39 UTC, merged

2021-03-27 04:02 UTC, vybhav72954 commented
@atarax665 I am sorry! I was traveling and was unable to work. My bad and thank you for helping here.