Wave Sort #2228
HarshCasper/NeoAlgo pull request #2245
Opened 2021-03-07 18:25 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code added in the sorting folder.

### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2228

2021-03-08 14:15 UTC, HarshCasper requested changes

2021-03-08 14:15 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +//Output[] : {20 12 60 5 45}
Put it in Multi-Line Comments and add Complexity

2021-03-08 14:15 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +}
Format and Indent the Code properly

2021-03-08 14:15 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +        if(v[i]<v[i-1] and i!=0) { //If the current element is lesser in value than the previous and is not the first..
Put Comments above the line of code, not beside them

2021-03-08 14:15 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +            swap(v[i],v[i+1]); //then the values are swapped
Put Comments above the line of code, not beside them

2021-03-08 14:15 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +//that is A[0 to n-1] is sorted in the form A[0]>=A[1]<=A[2]>=A[3]....
Add more descriptive Problem Statement

2021-03-08 15:34 UTC, gayatri517 commented
@HarshCasper I have made the changes that were requested. Please check them. 
Thank you.

2021-03-08 15:43 UTC, HarshCasper requested changes

2021-03-08 15:43 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +}
Why do we have so many lines of code missed out?

2021-03-08 15:43 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +            swap(v[i],v[i+1]);
Format the Code

2021-03-08 15:43 UTC, HarshCasper commented on C-Plus-Plus/sort/wave_sort.cpp
> +        	cout<<v[i]<<" ";
Format the Code

2021-03-08 17:29 UTC, gayatri517 commented
@HarshCasper formatting done. Please check them.
Thank you.

2021-03-09 03:21 UTC, HarshCasper approved these changes

2021-03-10 09:13 UTC, merged

2021-04-23 12:45 UTC, gayatri517 commented
@HarshCasper this PR is not getting included in the score in leaderboard. Please check it.
Thank you