Added Shaker Sort in C
HarshCasper/NeoAlgo pull request #2256
Opened 2021-03-08 06:22 UTC by rohanbabbar04

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
Implemented Shaker sort In C
### Checklist

- [✅] I've read the contribution guidelines.
- [✅] I've checked the issue list before deciding what to submit.
- [✅] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Added #2235

2021-03-08 13:22 UTC, HarshCasper requested changes

2021-03-08 13:22 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +*/
Add a new line at the EOF

2021-03-08 13:22 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +/* *****************Sample Output*************
Remove the asterisks.

2021-03-08 13:22 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +/* *****************Complexities***************
Remove the asterisks.

2021-03-08 13:22 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +}
Format the Code using a C Code Formatter

2021-03-08 13:22 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +      }
Why is the indentation so mis-matched? Please use a proper indentation pattern across the repo

2021-03-08 13:22 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +     int num1,num2,i;
Bad variable names. Use better ones

2021-03-08 13:22 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +    return 0;
Improper indentation and formatting. Fix it

2021-03-09 05:00 UTC, HarshCasper requested changes

2021-03-09 05:00 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +#include <stdio.h>
Add a beginner pitch to the Code

2021-03-09 05:00 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +void shakersort(int arr[], int num)
Add proper function descriptions

2021-03-09 05:00 UTC, HarshCasper commented on C/sort/shaker_sort.c
> +void swap(int *x, int *y)
Add proper function descriptions

2021-03-09 05:02 UTC, rohanbabbar04 commented
I have modified the changes do review the PR @HarshCasper

2021-03-09 05:36 UTC, rohanbabbar04 commented
Modified the changes do review @HarshCasper

2021-03-11 03:05 UTC, HarshCasper requested changes
One tiny change. Otherwise looks good to merge

2021-03-11 03:05 UTC, HarshCasper commented on C/README.md
> +- [Adjacent Element Product](cp/Adjacent_Element_Product.c)
It doesn't exist in your commit. Revert this

2021-03-11 06:24 UTC, rohanbabbar04 commented
I have made the changes you can now merge @HarshCasper

2021-03-12 09:59 UTC, HarshCasper approved these changes

2021-03-12 10:00 UTC, merged