Hamming Distance in Bits Manipulation
HarshCasper/NeoAlgo pull request #2270
Opened 2021-03-08 13:35 UTC by aakriti1318

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
### Description

Given x and y, return the number of positions where their values differ in their binary representations as a 32-bit integer.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2221

2021-03-09 00:45 UTC, iamrajiv requested changes
@aakriti1318 Move this program to the math section. Add problem link. Also, we can do this in constant time so you can add this program too along with the existing program

```c++
int solve(int x, int y) {
 int count = 0;
 for (int i = 0; i < 32; i++)
 if ( (x & (1 << i)) != (y & (1 << i)) )
 count++;
 return count;
}
```

2021-03-09 04:23 UTC, HarshCasper requested changes

2021-03-09 04:23 UTC, HarshCasper commented on C-Plus-Plus/bits_manipulation/Hamming_Distance.cpp
> +*/
Shift sample I/O to the end of the Code

2021-03-09 04:23 UTC, HarshCasper commented on C-Plus-Plus/bits_manipulation/Hamming_Distance.cpp
> +
Remove the extra line at the EOF

2021-03-09 04:23 UTC, HarshCasper commented on C-Plus-Plus/bits_manipulation/Hamming_Distance.cpp
> +    cout<<solve(x,y)<<endl;
Indent the Code and format it properly

2021-03-09 16:50 UTC, iamrajiv approved these changes

2021-03-10 11:07 UTC, HarshCasper approved these changes

2021-03-10 11:07 UTC, merged