Added bankers algorithm in C language.
HarshCasper/NeoAlgo pull request #2276
Opened 2021-03-08 14:48 UTC by Karthik-Nayak98

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-08 15:37 UTC, HarshCasper requested changes
Few changes: 

- Revert back the changes made on the C Style Guide. 
- Push all your functional code in a separate function and use main() for driver code

2021-03-08 15:48 UTC, Karthik-Nayak98 commented
Sure @HarshCasper

2021-03-09 03:27 UTC, HarshCasper requested changes
Great work! Few changes requested otherwise good to merge :tada:

2021-03-09 03:27 UTC, HarshCasper commented on C/operating_system/bankers.c
> +*/
Add a new line at the EOF

2021-03-09 03:27 UTC, HarshCasper commented on C/operating_system/bankers.c
> +    // Initializing with value '0' which means no process is executed yet.
Please use Multi-Line Comments

2021-03-09 03:27 UTC, HarshCasper commented on C/operating_system/bankers.c
> +    int p, r, i, j;
Can we use more meaningful variable names for non-iterators?

2021-03-09 04:42 UTC, Karthik-Nayak98 commented
Made all the changes mentioned above @HarshCasper.

2021-03-09 04:59 UTC, HarshCasper approved these changes

2021-03-10 09:13 UTC, merged