Add jump search
HarshCasper/NeoAlgo pull request #2283
Opened 2021-03-08 16:12 UTC by muthuannamalai12

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
I have added an algorithm for Jump Search in C
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2233 
(Write your answer here.)

2021-03-08 17:39 UTC, atarax665 requested changes

2021-03-08 17:39 UTC, atarax665 commented on C/search/JumpSearch.c
> +	while (a[pos] <= ele && pos < n)	//We keep on jumping elements by a distance 'jmp' until the current array position becomes greater than the element to be searched.
Comment should be above the line of code not beside it.

2021-03-08 17:39 UTC, atarax665 commented on C/search/JumpSearch.c
> +	for (int j = i; j < pos; j++)	//Now we iterate from the last position 'i' where the a[i] <= ele, and iterate jmp(=sqrt(n) times in worst case.
Comment should be above the line of code not beside it.

2021-03-08 17:39 UTC, atarax665 commented on C/search/JumpSearch.c
> +		if (a[j] == ele)	// If element is found we store in the variable flag, the final answer of the position where its found.
Comment should be above the line of code not beside it.

2021-03-08 17:39 UTC, atarax665 commented on C/search/JumpSearch.c
> +		printf("\n Element Found at %dth position", flag);
Use a better output message. Something similar to *Element found at index :*

2021-03-08 17:39 UTC, atarax665 commented on C/search/JumpSearch.c
> +	int jmp = sqrt(n);
The ```main``` block should only have input-output statements. Make a new function and shift all the logic there.

2021-03-08 17:39 UTC, atarax665 commented on C/search/JumpSearch.c
> +Example 2:
One sample I/O is enough.

2021-03-11 13:41 UTC, HarshCasper commented
@muthuannamalai12 Are you working on this?

2021-03-11 13:53 UTC, muthuannamalai12 commented
> @muthuannamalai12 Are you working on this?

Yes I am working on it

2021-03-16 04:05 UTC, HarshCasper commented
Closing this because of no updates

2021-03-16 04:05 UTC, closed without merging