Kahns's Algorithm added
HarshCasper/NeoAlgo pull request #2289
Opened 2021-03-08 16:37 UTC by dhruvinfo28

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

### Description

Added Kahn's algorithm.  closes #2271 

### Checklist

- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [ Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

2021-03-09 04:02 UTC, HarshCasper requested changes

2021-03-09 04:02 UTC, HarshCasper commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +*/
Add a new line at the EOF

2021-03-09 04:02 UTC, HarshCasper commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +No topological sort possible, there exists a cycle
Only one sample I/O is required

2021-03-09 04:02 UTC, HarshCasper commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +    kahn_topological_sort(adj,n);
Format the entire Code

2021-03-09 04:02 UTC, HarshCasper commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +    int in_degree[n]; //Array for keeping a track for indegree of all nodes
Keep the Comments above the line of code not beside it

2021-03-09 04:02 UTC, HarshCasper commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +    vector <int> topological_order; //This vector will store the order
Keep the Comments above the line of code not beside it

2021-03-09 04:02 UTC, HarshCasper commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +
Can you document it?

2021-03-09 06:51 UTC, dhruvinfo28 commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +    kahn_topological_sort(adj,n);
Do you mean removing extra lines? @HarshCasper

2021-03-09 08:44 UTC, HarshCasper commented on C-Plus-Plus/graphs/kahns_algorithm.cpp
> +    kahn_topological_sort(adj,n);
Yes. And to format the Code as well

2021-03-10 11:04 UTC, HarshCasper approved these changes

2021-03-10 11:05 UTC, merged