Added Two Pointer Method
HarshCasper/NeoAlgo pull request #2292
Opened 2021-03-08 17:04 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes.

### Description

Find a pair of elements in the array whose sum is equal to a target value. 
Can be solved in O(N) by using Two Pointers Method

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

5333c2c

2021-03-09 00:24 UTC, iamrajiv commented
@RaiyanMahin Please provide the related issue number.

2021-03-09 00:29 UTC, iamrajiv requested changes
@RaiyanMahin Rename the file to `Two_Pointers_Method.cpp`. Also, I would suggest adding a naive solution as well in the same file.

2021-03-09 00:29 UTC, iamrajiv commented on C-Plus-Plus/cp/Two Pointers Method.cpp
> +#define endl "\n"
@RaiyanMahin Avoid using macros it decreases the code readability.

2021-03-09 06:46 UTC, RaiyanMahin commented
@iamrajiv I have added the issue number , rename the file as you told and added the naive solution as well. I also remove the macros from my code.
Kindly review.

2021-03-09 16:48 UTC, iamrajiv approved these changes

2021-03-09 17:24 UTC, RaiyanMahin commented
@iamrajiv  Sir , I want to make my 2nd pull request. But can't do it.
can you please tell me how can i do it?

2021-03-09 23:25 UTC, iamrajiv commented
@RaiyanMahin Whenever you make PR try to make a new branch for every PR so that your main branch did not mess with other branches. Read more about it here https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests. Also, make sure you update your fork repository regularly so that you get the latest changes from the original repository. Read more about it here https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository.

2021-03-10 11:55 UTC, RaiyanMahin commented
@iamrajiv Thanks. Still trying to do.

2021-03-10 11:55 UTC, RaiyanMahin commented
@HarshCasper , @atarax665 Kindly review :)

2021-03-11 03:07 UTC, HarshCasper requested changes
Why are two codes pushed in the same file?

2021-03-11 03:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Two_Pointers_Method.cpp
> +#include <bits/stdc++.h>
Why has a second code been added here? Do you understand that this would mess up badly?

2021-03-11 03:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Two_Pointers_Method.cpp
> +
Remove extra lines of code

2021-03-11 08:21 UTC, RaiyanMahin commented
@HarshCasper , previously @iamrajiv told me to add the naive solution in the same file, So
i added it. 
Now, i updated it and keep the most optimal solution only and remove the extra lines of code.

2021-03-11 14:12 UTC, HarshCasper approved these changes

2021-03-11 14:29 UTC, merged