Added Longest Palindromic Subsequence Under Dynamic Programming in C-Plus-Plus
HarshCasper/NeoAlgo pull request #2294
Opened 2021-03-08 17:10 UTC by BullHoN

…-Plus

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Find Longest Palindromic Subsequence
Can be solved in O(N^2) by using Bottom-Up Dynamic Programming

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2021-03-09 04:19 UTC, HarshCasper requested changes
Few changes: 

- Use Comments above the Line of Code not beside it
- Add a new line at the EOF 
- Run a formatter across your Code and indent it properly

2021-03-09 05:08 UTC, BullHoN commented
@HarshCasper I had made the required changes, can you please check it.

2021-03-16 17:26 UTC, atarax665 requested changes

2021-03-16 17:26 UTC, atarax665 commented on C-Plus-Plus/dp/longest_palindromic_subsequence.cpp
> +	    Try Running with input
Shift sample I/O at the end of the program and also add time and space complexity of your program.

2021-03-16 17:26 UTC, atarax665 commented on C-Plus-Plus/dp/longest_palindromic_subsequence.cpp
> +	string s;
Add a statement to prompt user to enter the string.

2021-03-17 00:09 UTC, BullHoN commented
@atarax665 I had made the changes, can you please check it 😊😊

2021-03-17 03:28 UTC, HarshCasper requested changes

2021-03-17 03:28 UTC, HarshCasper commented on C-Plus-Plus/dp/longest_palindromic_subsequence.cpp
> +
Left-align this and remove unnecessary lines of code

2021-03-17 03:28 UTC, HarshCasper commented on C-Plus-Plus/dp/longest_palindromic_subsequence.cpp
> +
Approach should be captured through Code. Remove it here

2021-03-17 03:28 UTC, HarshCasper commented on C-Plus-Plus/dp/longest_palindromic_subsequence.cpp
> +        ans = 5, "abdba" is the longest palindromic subsequence
Sample I/O are good enough for the example

2021-03-17 03:28 UTC, HarshCasper commented on C-Plus-Plus/dp/longest_palindromic_subsequence.cpp
> +	string s;
Use meaningful variable names

2021-03-23 13:40 UTC, atarax665 commented
Hey @BullHoN Are you still working on this?

2021-03-26 16:28 UTC, closed without merging