Algorithm for finding Peak element added
HarshCasper/NeoAlgo pull request #2319
Opened 2021-03-09 05:11 UTC by DevilAJ

I have added Algorithm for finding Peak element in an array by implementing Divide & Conquer algorithm
in both manner recursively and using while loop.
I also added proper comments and illustration to understand.

2021-03-09 08:44 UTC, atarax665 commented
> I have added Algorithm for finding Peak element in an array by implementing Divide & Conquer algorithm
> in both manner recursively and using while loop.
> I also added proper comments and illustration to understand.

Please always open an issue regarding your proposal before making a pull request.

2021-03-09 08:47 UTC, DevilAJ commented
#2274
I did open the issue and it was assigned to me.
You can check.

2021-03-09 08:51 UTC, atarax665 commented
> @atarax665
> #2274
> I did open the issue and it was assigned to me.
> You can check.

Okay, please do mention the issue related to your PR, you can use the default PR template provided. It allows the maintainers to have a glance on all the necessary details at one place.

2021-03-09 08:53 UTC, DevilAJ commented
Ok sir.
I will make sure to mention issue from now on.

2021-03-09 09:18 UTC, atarax665 requested changes
Please make appropriate changes to the corresponding readme and change the file location from ```C-Plus-Plus/search to C-Plus-Plus/cp```

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +A divide-and-conquer algorithm recursively breaks
Please remove this explanation of what is a divide and conquer algorithm it ain't needed here.

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +//  Complexity : O(log(N)
Time and space complexity should be added at the end of the program.

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +        if(mid == 0 || mid+1 == v.size()) // means we are at corner
Comments should be above the line of code not beside it.

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +	ios_base::sync_with_stdio(0);
Remove ```ios_base::sync_with_stdio(0); cin.tie(0); cout.tie(0);```.

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +	int n;cin>>n;
Use proper input output statements. It makes your program interactive.

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +int findPeek(vector<int>arr)
Rename the iterative function as ```find_peak_iter```

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +int findPeek(vector<int>v,int l,int r)
Rename the iterative function as ```find_peak_recursive```

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +	int i = findPeek(v,0,n-1);
Use proper variable names and as you have added 2 different approaches then format your output accordingly.
ex : 
```
Peak Element (Recursive approach) : 
Peak Element (Iterative approach) :
```

2021-03-09 09:18 UTC, atarax665 commented on C-Plus-Plus/search/Peak_element.cpp
> +Input : a[] = { 10, 20, 15, 2, 23, 90, 6 }
You just need to add Sample Input/Output and complexity at the end. You can explain your approach briefly either using inline comments or adding a docstring before your functions.

2021-03-09 09:22 UTC, DevilAJ commented
Ok sir and thanx for your time.
I will make required changes.

2021-03-09 09:37 UTC, DevilAJ commented
I had done the required changes.
Do let me know for any further updation.

2021-03-10 04:06 UTC, DevilAJ commented
@atarax665 
Please check the changes 
And let me know for any changes.

2021-03-10 17:20 UTC, atarax665 requested changes
There are just some minor fixes and then this PR will be good to merge. Also format your code using [this](https://techiedelight.com/tools/clike).

2021-03-10 17:20 UTC, atarax665 commented on C-Plus-Plus/cp/Peak_element.cpp
> +	cin>>n;
Prompt user to ```Enter the number of elements in the array :``` and ```Enter the elements of the array :```

2021-03-10 17:20 UTC, atarax665 commented on C-Plus-Plus/cp/Peak_element.cpp
> +	for(int i=0;i<n;i++)
Add opening and closing braces of the for loop.

2021-03-10 17:20 UTC, atarax665 commented on C-Plus-Plus/cp/Peak_element.cpp
> +Input: array[] = {10, 20, 15, 2, 23, 90, 67}
Your sample input should replicate the input you will give when the program is run in console or any IDE.

2021-03-10 17:20 UTC, atarax665 commented on C-Plus-Plus/cp/README.md
> +Peak Element
Revert this. You don't need to update this sub-folder README. You just need to add hyperlink of your program in the README file of C-Plus-Plus folder. Refer to a recently merged C++ PR to get a better idea of this.

2021-03-10 17:20 UTC, atarax665 commented on C-Plus-Plus/cp/Peak_element.cpp
> +**/
Add a blank line at the EOF.

2021-03-10 17:20 UTC, atarax665 commented on C-Plus-Plus/cp/Peak_element.cpp
> +Approach :If the middle element is not the peak element, then check if the element on the right side is greater than the middle element
Shift this approach paragraph after the description part at the top.

2021-03-11 05:33 UTC, DevilAJ commented
@atarax665 
I have done the changes you can check.

2021-03-12 08:23 UTC, DevilAJ commented
@atarax665 
Please check it.
I think it will show conflicts after some time.

2021-03-15 10:06 UTC, DevilAJ commented
@atarax665 
@HarshCasper 
@bhav09 
@gat786 
Please look into this pr it still pending....

2021-03-15 16:27 UTC, atarax665 requested changes

2021-03-15 16:27 UTC, atarax665 commented on C-Plus-Plus/cp/Peak_element.cpp
> +7
Update the sample input according to the updated code.

2021-03-15 16:27 UTC, atarax665 commented on C-Plus-Plus/README.md
> +<<<<<<< HEAD
Remove this line.

2021-03-15 16:27 UTC, atarax665 commented on C-Plus-Plus/README.md
> +>>>>>>> c8ecee37a2708f6788e13c1e0080f40635dd0702
Remove this line.

2021-03-16 03:45 UTC, DevilAJ commented
@atarax665 
Please look now..

2021-03-16 09:04 UTC, DevilAJ commented
@atarax665 
My issue had been closed and PR is still unmerged please look into it.

2021-03-16 17:06 UTC, atarax665 commented on C-Plus-Plus/README.md
> +- [Moore's Voting Algorithm to find the majority element](cp/moore_voting.cpp)
Do not make unnecessary changes in the README. Just add hyper link of your program under the correct heading.

2021-03-16 18:29 UTC, merged