Word Break
HarshCasper/NeoAlgo pull request #2324
Opened 2021-03-09 05:29 UTC by Meghag5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(yes)

### Description

(This problem is solved using backtracking it divides the string into words and pass all the valid strings which can be formed with those words)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2295 
(Write your answer here.)

2021-03-09 08:34 UTC, HarshCasper requested changes
You have committed binary files into the PR. Remove them.

Also we won't review PRs having more than one Code File change. Either remove the other code file or break this PR into two

2021-03-09 08:34 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +>>>>>>> f3f8e3ecff01def04109ea96784a01ca0ec9414f
Why are the commit hashes in the README now 🤷‍♂️

2021-03-09 10:01 UTC, Meghag5 commented
> You have committed binary files into the PR. Remove them.
> 
> Also we won't review PRs having more than one Code File change. Either remove the other code file or break this PR into two

should I send it again on new branch?

2021-03-09 10:05 UTC, Meghag5 commented
> > You have committed binary files into the PR. Remove them.
> > Also we won't review PRs having more than one Code File change. Either remove the other code file or break this PR into two
> 
> should I send it again on new branch?

pls help me as I am a beginner and i face problem using git how should I remove extra files it is showing

2021-03-09 15:43 UTC, closed without merging

2021-03-10 03:39 UTC, HarshCasper commented
@Meghag5 

Drop me a message on Discord. Don't panic and just let us know on the apt channels.