largest subarray which contains equal no of 0s and 1s
HarshCasper/NeoAlgo pull request #2352
Opened 2021-03-09 06:39 UTC by kotwani2883

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

This is the code for the implementation of finding the longest subarray of equal number of 0's and 1's.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2314

2021-03-09 08:17 UTC, HarshCasper requested changes

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +
Remove extra lines of code

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +Auxilary Space complexity:O(n)
Give a space after Colon

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +/*
Add the sample I/O

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +
Indent the piece of Code

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +*Output: 0 to 3 Or 1 to 4
Shift the I/O to the end of Code

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +*Author-:Palak
The Git Commit would be forever credited to you. It would be good to remove the author name

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +*/
Add this in the previous comment block

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +*/
Add this in the previous comment block

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +view as it is a combination of trick,prefix sum and hashing.*/
Add this in the previous comment block

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +//number of 0 and 1
Use Multi-Line Comments

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +// having some sum
Use Multi-Line Comments

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +// subarray with zero-sum starts from index 0
Use Multi-Line Comments

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +            // subarray having zero-sum
Use Multi-Line Comments

2021-03-09 08:17 UTC, HarshCasper commented on C-Plus-Plus/other/Longest_subarray_with_equal_0_1.cpp
> +        // index into the map
Use Multi-Line Comments

2021-03-10 10:23 UTC, kotwani2883 commented
Kindly give it a check.I have made the requested changes! 
Thanks.

2021-03-11 03:18 UTC, HarshCasper approved these changes

2021-03-11 03:18 UTC, merged