ADDED IMPLEMENTATION OF DOUBLY LINKED LIST AND UPDATED README.md of C…
HarshCasper/NeoAlgo pull request #2356
Opened 2021-03-09 06:58 UTC by imsushant12

… DIRECTORY

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

I have added the implementation of Doubly Linked List in C Language as well as updated README.md of the same.

### Checklist

- [YES ] I've read the contribution guidelines.
- [YES ] I've checked the issue list before deciding what to submit.
- [YES ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

https://github.com/TesseractCoding/NeoAlgo/issues/2323

2021-03-09 07:58 UTC, HarshCasper requested changes
Make apt changes to the sample I/O as well. The Code looks good.

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +        printf("\n 9- To exit.");
Don't repeat them on every iteration. Instead keep them out of the loop body

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void insertstart()
Add a function description right here

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void insertlast()
Add a function description right here

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void insertafter(struct node *ptr)
Add a function description right here

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void insertat()
Add a function description right here

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void deletefirst()
Add a function description right here

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void deletelast()
Add a function description right here

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void deleteafter()
Add a function description right here

2021-03-09 07:58 UTC, HarshCasper commented on C/ds/doubly_linked_list.c
> +void viewlist()
Add a function description right here

2021-03-09 09:35 UTC, imsushant12 commented on C/ds/doubly_linked_list.c
> +void viewlist()
Added!

2021-03-09 09:35 UTC, imsushant12 commented on C/ds/doubly_linked_list.c
> +void deleteafter()
added

2021-03-09 09:35 UTC, imsushant12 commented on C/ds/doubly_linked_list.c
> +void deletelast()
added

2021-03-09 09:35 UTC, imsushant12 commented on C/ds/doubly_linked_list.c
> +void insertafter(struct node *ptr)
added

2021-03-09 09:35 UTC, imsushant12 commented on C/ds/doubly_linked_list.c
> +void deletefirst()
added

2021-03-09 09:35 UTC, imsushant12 commented on C/ds/doubly_linked_list.c
> +void insertstart()
added

2021-03-09 09:36 UTC, imsushant12 commented on C/ds/doubly_linked_list.c
> +        printf("\n 9- To exit.");
did that

2021-03-10 11:22 UTC, HarshCasper requested changes
Few more changes: 

- Add a beginner friendly description about your Code
- Resolve Conflicts 

Otherwise good to merge :tada:

2021-03-10 11:29 UTC, imsushant12 commented
> Few more changes:
> 
> * Add a beginner friendly description about your Code
> * Resolve Conflicts
> 
> Otherwise good to merge 🎉

2021-03-10 11:29 UTC, imsushant12 commented
Okay working on it

2021-03-11 03:19 UTC, HarshCasper approved these changes

2021-03-11 03:19 UTC, merged

2021-03-27 12:14 UTC, HarshCasper commented
@all-contributors bot please add @imsushant12 for code