Branch1
HarshCasper/NeoAlgo pull request #2390
Opened 2021-03-09 11:56 UTC by gokulkannan7

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for the count of zero sum subarray problem with 2 methods.
Added link to README.md in the c++ folder

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2322

2021-03-09 12:35 UTC, HarshCasper requested changes

2021-03-09 12:35 UTC, HarshCasper commented on C-Plus-Plus/other/Count_Zero_Subarrays.cpp
> +}
Add a new line at the EOF

2021-03-09 12:35 UTC, HarshCasper commented on C-Plus-Plus/other/Count_Zero_Subarrays.cpp
> +#include <bits/stdc++.h>
Add a beginner friendly pitch about your Code/Agorithm

2021-03-09 12:35 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [[Maximum Subarray Sum (Constant Space)](<dp/Max_subarray_sum_constant_space(DP).cpp>)]
Revert these changes

2021-03-09 13:04 UTC, gokulkannan7 commented
@HarshCasper, I have made the changes, can u review it?

2021-03-12 10:16 UTC, gokulkannan7 commented
@HarshCasper, can you review the code once, is there anything to be changed?

2021-03-13 03:38 UTC, HarshCasper requested changes

2021-03-13 03:38 UTC, HarshCasper commented on .vscode/settings.json
> +}
Remove this

2021-03-13 03:38 UTC, HarshCasper commented on C-Plus-Plus/other/Count_Zero_Subarrays.cpp
> +#include <bits/stdc++.h>
Not yet resolved

2021-03-13 03:38 UTC, HarshCasper commented on C-Plus-Plus/other/Count_Zero_Subarrays.cpp
> +5
Add sample I/O at the end of the Code

2021-03-13 03:38 UTC, HarshCasper commented on C-Plus-Plus/other/Count_Zero_Subarrays.cpp
> +}
Not yet resolved

2021-03-26 16:41 UTC, atarax665 commented
Closing due to inactivity.

2021-03-26 16:41 UTC, closed without merging