first commit
HarshCasper/NeoAlgo pull request #2425
Opened 2021-03-09 15:18 UTC by YashPaste

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for the Palindrome Partitioning of string in c++ using 2 methods.
Added link to README.md in the c++ folder

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2367

2021-03-11 03:29 UTC, HarshCasper requested changes
Few changes: 
- Use only one approach which should be the most optimal one
- Add sample I/O at the end of the Code
- Add Code Complexity at the end of the Code
- Remove the example at the beginning

2021-03-12 05:55 UTC, YashPaste commented
@HarshCasper I've made the changes. Please do check.
Thank you!

2021-03-12 09:57 UTC, HarshCasper approved these changes

2021-03-12 09:57 UTC, merged

2021-05-10 08:14 UTC, YashPaste commented
@HarshCasper @ankitaggarwal23 Thanks for merging the pr, but I am not able to see my name on the leaderboard. Is there an error with this PR? Thank you!