Meghag5
HarshCasper/NeoAlgo pull request #2433
Opened 2021-03-09 16:02 UTC by Meghag5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes.)

### Description

(This problem is solved using backtracking in which we divide single string with valid words.)
eg.
input - ilovecoding
output - i love coding

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2295

2021-03-11 03:32 UTC, HarshCasper requested changes
Few changes: 

- Don't make a new section `Backtracking`
- Add a beginner friendly pitch about the Code
- Add sample I/O at the end of the Code
- Add Code Complexity at the end of the Code
- Format your Code using a clang formatter 
- Use dynamic input from the user

2021-03-24 15:08 UTC, HarshCasper requested changes

2021-03-24 15:08 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +
Remove the extra line

2021-03-24 15:08 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +-[Word Break Problem](backtracking/Word_break.cpp)
Give a space between `-` and `[`

2021-03-24 15:08 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +-[Word Break Problem](backtracking/Word_break.cpp)
Why are you adding backtracking directory here? Didn't I tell you to remove that?

2021-03-24 15:08 UTC, HarshCasper commented on C-Plus-Plus/math/Word_break.cpp
> +#include <bits/stdc++.h>
Add a beginner friendly pitch about the Code

2021-03-24 15:08 UTC, HarshCasper commented on C-Plus-Plus/math/Word_break.cpp
> +//Space Complexity - O(1)
Keep them in multi-line comments

2021-03-24 15:08 UTC, HarshCasper commented on C-Plus-Plus/math/Word_break.cpp
> +    BreakWords("microsofthiring");
Use dynamic input

2021-03-24 15:20 UTC, Meghag5 commented on C-Plus-Plus/README.md
> +-[Word Break Problem](backtracking/Word_break.cpp)
really sorry i removed backtracking directory but forgot to write math

2021-03-24 15:22 UTC, Meghag5 commented
pls review it again made all the changes asked @HarshCasper

2021-03-25 17:01 UTC, HarshCasper requested changes
Format the Code properly

2021-03-25 17:01 UTC, HarshCasper commented on C-Plus-Plus/math/Word_break.cpp
> +//Space Complexity - O(1)
Put in multi-line comments

2021-03-25 17:01 UTC, HarshCasper commented on C-Plus-Plus/math/Word_break.cpp
> +#include <iostream>
Add a beginner friendly description

2021-03-26 06:21 UTC, Meghag5 commented on C-Plus-Plus/math/Word_break.cpp
> +//Space Complexity - O(1)
done

2021-03-26 06:21 UTC, Meghag5 commented on C-Plus-Plus/math/Word_break.cpp
> +#include <iostream>
done

2021-03-26 09:26 UTC, HarshCasper approved these changes

2021-03-26 09:27 UTC, merged