Coder srinivas
HarshCasper/NeoAlgo pull request #2498
Opened 2021-03-10 06:37 UTC by Coder-Srinivas

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

Adding Job Sequencing to Maximize profit in Java's Dynamic Programming Section

(Write your answer here.)

### Checklist

- [✔] I've read the contribution guidelines.
- [✔] I've checked the issue list before deciding what to submit.
- [✔] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #2349

2021-03-12 03:15 UTC, HarshCasper requested changes
Rest looks good to merge. One small change and we are good to go

2021-03-12 03:15 UTC, HarshCasper commented on Java/dp/JobSequencingToMaximizeProfit.java
> +// We can take intervals [1, 2, 50] and [2, 100, 200] thereby maximizing our profit, which is coming out to be 250
Use Multi-Line Comments. Also shift the sample I/O at the end of the Code

2021-03-12 06:10 UTC, Coder-Srinivas commented
@HarshCasper Made necessary changes. Please review it and let me know if anything is wrong ☺.

2021-03-13 03:40 UTC, HarshCasper approved these changes

2021-03-13 03:40 UTC, merged