Fractional Knapsack in Java
HarshCasper/NeoAlgo pull request #2512
Opened 2021-03-10 08:56 UTC by Coder-Srinivas

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Fractional Knapsack in Java's Dynamic Programming Section

### Checklist

- [✔] I've read the contribution guidelines.
- [✔] I've checked the issue list before deciding what to submit.
- [✔] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue : #2347

2021-03-12 03:41 UTC, HarshCasper requested changes

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +// Thereby getting a maximum profit of 150
Few changes: 
- Use multi-line comments 
- Shift sample I/O to the end of the code
- Add complexity at the end of the Code

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +// Class Fractional Knapsack
Redundant Comment

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +}
Add a new line at the EOF

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +    /**End Main Function**/
Redundant Comment

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +        // Inputting the values
Redundant Comment

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +        // Inputting the values
Redundant Comment

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +    // Main method
Redundant Comment

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +        // Initializing an empty weights and values array
Redundant Comment

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +        // Taking the number of items from the user
Redundant Comment

2021-03-12 03:41 UTC, HarshCasper commented on Java/Greedy_Algorithms/FractionalKnapsack.java
> +        // Initializing the variable capacity
Redundant Comment

2021-03-12 05:55 UTC, Coder-Srinivas commented
@HarshCasper Made necessary changes. Please review it and let me know if anything is wrong ☺.

2021-03-13 04:06 UTC, HarshCasper approved these changes

2021-03-13 04:07 UTC, merged