Reverse a Doubly Link List Problem Added(https://github.com/TesseractCoding/NeoAlgo/issues/2457#issue-826501841)
HarshCasper/NeoAlgo pull request #2526
Opened 2021-03-10 10:15 UTC by SamarpanCoder2002

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

New Problem(Reverse a Doubly Link List.cpp) Added through C-plus-plus->ds->Reverse_a_Doubly_Link_List.cpp
(This pull request is associated with https://github.com/TesseractCoding/NeoAlgo/issues/2457#issue-826501841)
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Excited to contribute here..... This problem is new here..... Hope You will merge that pull request...Thank you..

2021-03-10 16:55 UTC, SamarpanCoder2002 commented
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
> yes
> 
> ### Description
> New Problem(Reverse a Doubly Link List.cpp) Added through C-plus-plus->ds->Reverse_a_Doubly_Link_List.cpp
> (This pull request is associated with [#2457 (comment)](https://github.com/TesseractCoding/NeoAlgo/issues/2457#issue-826501841))
> 
> ### Checklist
> * [x]  I've read the contribution guidelines.
> * [x]  I've checked the issue list before deciding what to submit.
> * [x]  I've edited the `README.md` and link to my code.
> 
> ## Related Issues or Pull Requests
> Excited to contribute here..... This problem is new here..... Hope You will merge that pull request...Thank you..

Please Merge This Pull Request.... If any problem here to merge this, you can feel free to tell me...Thanks

2021-03-12 04:25 UTC, HarshCasper requested changes
Few changes: 
- Add a beginner-friendly description about your Code at the top
- Add description of functions 
- Add sample I/O at the end of the Code
- Add a new line at the EOF
- Add complexity at the end of the code
- Use a Code formatter to format the Code

2021-03-12 04:25 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Stack using queue](ds/stack/Stack_using_queue.cpp)
Why are there two Markdown updates?

2021-03-30 00:12 UTC, atarax665 commented
Closing due to inactivity.

2021-03-30 00:12 UTC, closed without merging