Longest common subsequence
HarshCasper/NeoAlgo pull request #2540
Opened 2021-03-10 11:55 UTC by BeAgarwal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the guidelines.

### Description

Solution to longest common subsequence added.

### Checklist

- [ x] I've read the contribution guidelines.
- [ x] I've checked the issue list before deciding what to submit.
- [ x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2437

2021-03-10 12:11 UTC, BeAgarwal commented
I am not getting the error in DeepSource. Please have a look at it. Else this is good to go.

2021-03-12 04:09 UTC, HarshCasper requested changes
Open up the DeepSource Dashboard and understand the reason why the CI is failing

2021-03-12 04:09 UTC, HarshCasper commented on Go/dp/longest_common_subsequence.go
> +    	str2 := "ALGORITHM"
Take dynamic input

2021-03-12 04:09 UTC, HarshCasper commented on Go/dp/longest_common_subsequence.go
> +*/
Add a new line at the EOF

2021-03-12 05:06 UTC, BeAgarwal commented
I have gone through DeepSource dashboard. It is showing other declarations of the main function. This is because we have main in every file of the same directory. Now, it is okay to merge. @HarshCasper

2021-03-13 04:35 UTC, HarshCasper approved these changes

2021-03-13 04:35 UTC, merged