Guruc 134 edges that disconnect graph
HarshCasper/NeoAlgo pull request #2552
Opened 2021-03-10 14:32 UTC by guruc-134

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
 
added the code for a problem related to graphs, the problem uses tarjans algorithm to find the edges which upon removal increase the number of components in the graph i.e (disconnect the graph)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue: #2338

2021-03-12 04:08 UTC, HarshCasper requested changes
Why does it look like a solution for a problem from some Competitive Coding site?

2021-03-12 04:40 UTC, guruc-134 commented
@HarshCasper  the reason is that this is a sum from the category of competitive programming , and the solution is mine you can verify it from [here](https://binarysearch.com/problems/Edges-that-Disconnect-the-Graph/editorials/3980208). I am the author of the solution .
Thanks for reviewing

2021-03-16 04:05 UTC, guruc-134 commented
@HarshCasper  where can I see the changes that are requested, once could you point out where i need to make a change

2021-03-17 03:26 UTC, HarshCasper requested changes

2021-03-17 03:26 UTC, HarshCasper commented on Python/cp/edges_that_disconnect_graph.py
> +# --> back-edge detection
Try to ensure that the intuition is captured from the code itself. Here the description is larger than the Code itself and we are not writing articles here

2021-03-17 03:26 UTC, HarshCasper commented on Python/cp/edges_that_disconnect_graph.py
> +    return len(bridges)
Add a driver code along with sample I/O and code complexity

2021-03-17 03:26 UTC, HarshCasper commented on Python/cp/edges_that_disconnect_graph.py
> +# 3
Use multi-line strings

2021-03-17 03:26 UTC, HarshCasper commented on Python/README.md
> +- [edges that disconnect the graph](cp/edges_that_disconnect_graph.py)
Make it `Edges that disconnect the Graph`

2021-03-17 03:29 UTC, guruc-134 commented
@HarshCasper  sure, thanks for  the review

2021-03-20 11:20 UTC, HarshCasper commented
You don't seem to have addressed any of the reviews. Please close the PR if you are not interested in implementing the changes.

2021-03-21 17:48 UTC, closed without merging