Added Neon Number
HarshCasper/NeoAlgo pull request #2558
Opened 2021-03-10 15:40 UTC by Madhumitamoi

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes I have been through the guidelines.)

### Description

Added Neon Number.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2449

2021-03-10 15:41 UTC, Madhumitamoi commented
@HarshCasper Please review.

2021-03-11 06:55 UTC, siddharth25pandey requested changes
@Madhumitamoi Some modifications are required. Rest is fine.

2021-03-11 06:55 UTC, siddharth25pandey commented on C/math/Neon_number.c
> +}
As you are not returning anything, better to create a void function

2021-03-11 06:55 UTC, siddharth25pandey commented on C/math/Neon_number.c
> +    printf("Enter a number to check wheather it is neon or not- ");
Change the sentence format and remove the *-* from the end.

2021-03-11 14:39 UTC, Madhumitamoi commented
@HarshCasper Please review

2021-03-12 01:40 UTC, siddharth25pandey approved these changes
@Madhumitamoi Good to go. Able to merge !

2021-03-12 03:02 UTC, HarshCasper requested changes
Rest looks good to merge :+1:

2021-03-12 03:02 UTC, HarshCasper commented on C/math/Neon_number.c
> +// C Program to check whether a number is Neon or not. A neon number is a number where the sum of digits of square of the number is equal to the number.
Modularize this content: Break it up into multiple lines and use multi-line comments

2021-03-12 03:17 UTC, Madhumitamoi commented
New Changes added.

2021-03-12 06:10 UTC, iamrajiv requested changes
@Madhumitamoi Add space and time complexity.

2021-03-12 10:10 UTC, Madhumitamoi commented
Space and time complexity added.

2021-03-12 17:03 UTC, iamrajiv approved these changes

2021-03-12 17:03 UTC, merged

2021-03-12 17:03 UTC, iamrajiv commented
@all-contributors bot please add @Madhumitamoi for code