Added CombSort for Kotlin Language
HarshCasper/NeoAlgo pull request #2562
Opened 2021-03-10 16:31 UTC by adiig7

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Checklist

- [*] I've read the contribution guidelines.
- [*] I've checked the issue list before deciding what to submit.
- [*] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2546

2021-03-10 18:34 UTC, atarax665 requested changes
Your code should follow [this](https://github.com/TesseractCoding/NeoAlgo/blob/master/Kotlin/sort/MergeSort/src/MergeSort.kt) template. 
- Your file should be in ```Kotlin/sort/CombSort/src/CombSort.kt```

2021-03-10 18:59 UTC, adiig7 commented
@atarax665 done as per the changes requested. Please check.

2021-03-30 00:29 UTC, atarax665 requested changes
Make appropriate changes to the README and do the suggested changes.

2021-03-30 00:29 UTC, atarax665 commented on C-Sharp/sort/RadixSort.cs
> +    int[] a = {65, 3,91, 80, 45, 106,41, 1};
Dynamic input required.

2021-03-30 00:29 UTC, atarax665 commented on C-Sharp/sort/RadixSort.cs
> +using System;
Add a small description of the algorithm.

2021-03-30 00:29 UTC, atarax665 commented on C-Sharp/sort/RadixSort.cs
> +    for (int x = 1; max_element/x > 0; x *= 10){
Add comments wherever possible.

2021-04-04 11:15 UTC, ankitaggarwal23 reviewed
Closing due to inactivity

2021-04-04 11:15 UTC, closed without merging