Linked list Insertion
HarshCasper/NeoAlgo pull request #2586
Opened 2021-03-10 18:24 UTC by TidbitsJS

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Created dynamic insertion of nodes in a linked list

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2519

2021-03-10 18:26 UTC, TidbitsJS commented
Kindly review the PR @HarshCasper
Part of GSSOC'21

2021-03-12 14:50 UTC, HarshCasper requested changes

2021-03-12 14:50 UTC, HarshCasper commented on JavaScript/ds/DynamicLinkedList.js
> +// Sample I/O of the above program -
Use only one sample I/O

2021-03-12 14:50 UTC, HarshCasper commented on JavaScript/ds/DynamicLinkedList.js
> +*/
Add a new line at the EOF

2021-03-12 14:50 UTC, HarshCasper commented on JavaScript/ds/DynamicLinkedList.js
> +
Remove this

2021-03-12 14:58 UTC, TidbitsJS commented on JavaScript/ds/DynamicLinkedList.js
> +
I made the changes @HarshCasper

2021-03-12 17:10 UTC, HarshCasper approved these changes

2021-03-12 17:10 UTC, merged