added code and explanation for reverse lookup in 1D array
HarshCasper/NeoAlgo pull request #2619
Opened 2021-03-11 04:23 UTC by aromal17

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I have added the code for reverse lookup in 1D array and generated the pull request

2021-03-11 04:34 UTC, aromal17 commented
I have added the code for reverse lookup in 1D and updated the readme file for the same
Please review it and kindly let me know of any changes so that I can proceed with another pull request for reverse lookup in 2D array.

2021-03-12 04:27 UTC, HarshCasper requested changes
Few changes: 
- Modularize the beginner description. Its too large to consume easily
- Add description of functions 
- Add a new line at the EOF
- Use a Code formatter to format the Code

2021-03-13 08:25 UTC, aromal17 commented
I have made the requested changes and committed the same...Kindly review the changes and please let me know of any further changes.

2021-03-13 14:49 UTC, HarshCasper requested changes

2021-03-13 14:49 UTC, HarshCasper commented on C-Plus-Plus/cp/Reverse_Lookup_in_1D_array.cpp
> +*/
Add a new line at the EOF

2021-03-13 14:49 UTC, HarshCasper commented on C-Plus-Plus/cp/Reverse_Lookup_in_1D_array.cpp
> +    // reading the elements to the array
Redundant Comment

2021-03-13 17:13 UTC, aromal17 commented
I have removed the redundant comment and added a new line at the EOF. Kindly review the code for possible improvisations.

2021-03-16 03:30 UTC, HarshCasper requested changes

2021-03-16 03:30 UTC, HarshCasper commented on C-Plus-Plus/cp/Reverse_Lookup_in_1D_array.cpp
> +
Remove extra lines of code

2021-03-16 03:30 UTC, HarshCasper commented on C-Plus-Plus/cp/Reverse_Lookup_in_1D_array.cpp
> +// contribution variable denotes the contribution given by each element in the array.
Use Multi-Line Comments

2021-03-16 14:25 UTC, aromal17 commented
I have made the requested changes to the file. Kindly review the code.

2021-03-17 03:22 UTC, HarshCasper approved these changes

2021-03-17 03:23 UTC, merged