Adaptive Bubble Sort Implemented Issue #2325 fixed
HarshCasper/NeoAlgo pull request #2632
Opened 2021-03-11 06:20 UTC by SaloniSwagata

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Making the bubble sort adaptive so that it runs only till the array is unsorted. I have also changed the name of the array from 'list' to 'Array' because in Python, 'list' is a keyword. Also in the initial code, the final list was not printed, so changed that too.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2325

2021-03-12 04:32 UTC, HarshCasper approved these changes

2021-03-12 04:33 UTC, HarshCasper requested changes
Few changes I would recommend: 

- Use Comments above the Line of Code 
- Create a function which can be called while using the Code 
- Enclose the driver code in a `if__name__ == "__main__":` block of code

2021-03-12 04:34 UTC, SaloniSwagata commented
> Few changes I would recommend:
> 
> * Use Comments above the Line of Code
> * Create a function which can be called while using the Code
> * Enclose the driver code in a `if__name__ == "__main__":` block of code

Okay, I'll fix them

2021-03-15 15:57 UTC, SaloniSwagata commented
@HarshCasper I've made the required changes.

2021-03-17 03:22 UTC, HarshCasper requested changes

2021-03-17 03:22 UTC, HarshCasper commented on Python/sort/Bubble_Sort.py
> +Space Complexity: O(1)
Shift Time and Space Complexity at the end of the Code

2021-03-17 03:22 UTC, HarshCasper commented on Python/sort/Bubble_Sort.py
> +        print(i,end=" ")
Add sample I/O

2021-03-17 04:44 UTC, SaloniSwagata commented
@HarshCasper I've reordered the time and space complexity, added sample I/O and also fixed some bugs which I found.

2021-03-23 03:58 UTC, siddharth25pandey commented
@SaloniSwagata Add the update in **Readme** file

2021-03-23 04:03 UTC, SaloniSwagata commented
@siddharth25pandey I just edited an existing code. The code is already linked in the readme file.

2021-03-23 04:05 UTC, siddharth25pandey commented
> @siddharth25pandey I just edited an existing code. The code is already linked in the readme file.

@SaloniSwagata Alright then :)

2021-03-23 04:05 UTC, siddharth25pandey approved these changes
@SaloniSwagata LGTM, able to merge

2021-03-23 04:06 UTC, merged

2021-03-23 04:06 UTC, siddharth25pandey commented
@all-contributors please add @SaloniSwagata for her code