Solved Josephus Problem using recursion by @pshivesh8
HarshCasper/NeoAlgo pull request #2658
Opened 2021-03-11 09:30 UTC by pshivesh8

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-11 09:32 UTC, pshivesh8 commented
Solved #2658 issue as a part of GSSOC'21

2021-03-11 15:39 UTC, HarshCasper requested changes
Few changes: 
- Make the README updates 
- Add a function description

2021-03-12 05:55 UTC, pshivesh8 commented
I have updated the changes @HarshCasper please review it.

2021-03-13 15:02 UTC, HarshCasper requested changes

2021-03-13 15:02 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Set Clear and Check bits](other/check_set_clear_bit.cpp)
Why is there a second Markdown update?

2021-03-13 16:57 UTC, pshivesh8 commented on C-Plus-Plus/README.md
> +- [Set Clear and Check bits](other/check_set_clear_bit.cpp)
Sir, I thought my readme file is not updated, so I re-committed it. Please consider the previous commit 00f08e3 , 87a989a .

2021-03-14 11:46 UTC, pshivesh8 reviewed
Please review

2021-03-16 03:29 UTC, HarshCasper requested changes
Why did you delete the C++ README? Please revert that

2021-03-16 05:04 UTC, closed without merging