Issue 2556
HarshCasper/NeoAlgo pull request #2675
Opened 2021-03-11 10:42 UTC by Sakshi0401

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Detet_Cycle_In_LinkedList.cpp which detect cycle in linked list and updated README.md

### Checklist

- [1] I've read the contribution guidelines.
- [1] I've checked the issue list before deciding what to submit.
- [1] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2556

2021-03-12 09:38 UTC, HarshCasper requested changes

2021-03-12 09:38 UTC, HarshCasper commented on .vscode/settings.json
> +}
Remove this

2021-03-12 09:38 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [[Maximum Subarray Sum (Constant Space)](<dp/Max_subarray_sum_constant_space(DP).cpp>)]
Revert this

2021-03-12 09:38 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Detect Loop in Linked List ](ds/Detet_Cycle_In_LinkedList.cpp)
Typo in the file name

2021-03-12 09:38 UTC, HarshCasper commented on C-Plus-Plus/ds/Detet_Cycle_In_LinkedList.cpp
> +    Space complexity: O(1)
Push Time and Space Complexity at the end of the Code

2021-03-12 09:38 UTC, HarshCasper commented on C-Plus-Plus/ds/Detet_Cycle_In_LinkedList.cpp
> +*/
Add a new line at the EOF

2021-03-12 17:53 UTC, Sakshi0401 commented
@HarshCasper I think I have made all the necessary changes. Please consider.

2021-03-13 14:27 UTC, HarshCasper requested changes

2021-03-13 14:27 UTC, HarshCasper commented on .vscode/settings.json
> +
Remove this file

2021-03-14 17:12 UTC, Sakshi0401 commented
@HarshCasper  Done

2021-03-16 03:28 UTC, HarshCasper approved these changes

2021-03-16 03:29 UTC, merged