Added Sliding Window Technique
HarshCasper/NeoAlgo pull request #2689
Opened 2021-03-11 15:02 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Given an array of N elements and a value K (K <= N) , calculate maximum summation of K consecutive elements in the array.
Can be solved this problem by using Sliding Window Technique.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-12 09:50 UTC, HarshCasper requested changes

2021-03-12 09:50 UTC, HarshCasper commented on C-Plus-Plus/other/Calculate_max_sum_of_k_consecutive_elements.cpp
> +*/
Enclose them in a single comment block

2021-03-12 09:50 UTC, HarshCasper commented on C-Plus-Plus/other/Calculate_max_sum_of_k_consecutive_elements.cpp
> +*/
Add a new line at the EOF

2021-03-12 09:50 UTC, HarshCasper commented on C-Plus-Plus/other/Calculate_max_sum_of_k_consecutive_elements.cpp
> +
Remove extra lines of code

2021-03-12 09:50 UTC, HarshCasper commented on C-Plus-Plus/other/Calculate_max_sum_of_k_consecutive_elements.cpp
> +        // by removing elements from first window simultaneously add elements to current window
Use multi-line comments

2021-03-12 11:05 UTC, RaiyanMahin commented
I have made all the changes. Please review.

2021-03-12 11:26 UTC, RaiyanMahin commented
I don't know why  1 check was failed :(
@HarshCasper

2021-03-13 14:26 UTC, HarshCasper approved these changes

2021-03-13 14:26 UTC, merged