Added remove spaces from a string
HarshCasper/NeoAlgo pull request #2693
Opened 2021-03-11 15:49 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

For string related problems we need to remove spaces to get our expected output , that can be done by getline function in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2604

2021-03-11 16:31 UTC, atarax665 requested changes

2021-03-11 16:31 UTC, atarax665 commented on C-Plus-Plus/cp/remove_spaces_from_a_string.cpp
> +    string s;
Please format input/output to make your program more interactive.

2021-03-11 16:31 UTC, atarax665 commented on C-Plus-Plus/cp/remove_spaces_from_a_string.cpp
> +// Given a string , remove spaces from it and then return new string
Add both the problem description and your approach in a single multi-line comment.

2021-03-11 16:49 UTC, RaiyanMahin commented
I have resolved the changes.
Kindly review.

2021-03-12 18:58 UTC, RaiyanMahin commented
@atarax665 kindly review.

2021-03-15 06:55 UTC, HarshCasper approved these changes

2021-03-15 06:55 UTC, merged