Added wiggle sort in C-Plus-Plus
HarshCasper/NeoAlgo pull request #2713
Opened 2021-03-11 19:27 UTC by aish2002

Fixes #2354

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Wiggle sort is an algorithm to reorder an unsorted array in a particular way.
If given array is arr, Wriggle sort reorders the array such that arr[0]<arr[1]>arr[2]<arr[3]...
There can be more than one possible answer for a given input array

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #2354

2021-03-12 01:49 UTC, siddharth25pandey requested changes
@aish2002 Do the modifications as suggested.
Thanks!

2021-03-12 01:49 UTC, siddharth25pandey commented on C-Plus-Plus/sort/wiggle_sort.cpp
> +#include <algorithm>
Write single header file as **bits/stdc++**

2021-03-12 01:49 UTC, siddharth25pandey commented on C-Plus-Plus/sort/wiggle_sort.cpp
> +    cin >> n;
Use proper naming convention

2021-03-12 01:49 UTC, siddharth25pandey commented on C-Plus-Plus/sort/wiggle_sort.cpp
> +        cin >> a;
Use proper naming convention

2021-03-12 05:08 UTC, aish2002 commented
I have made necessary changes mentioned .@siddharth25pandey  kindly re-review the code

2021-03-14 17:39 UTC, siddharth25pandey approved these changes
@aish2002 LGTM, able to merge

2021-03-14 17:40 UTC, merged

2021-03-14 17:41 UTC, siddharth25pandey commented
@all-contributors please add @aish2002 for his/her code