Added 4 Sum Problem and updated readme
HarshCasper/NeoAlgo pull request #2745
Opened 2021-03-12 06:25 UTC by kotwani2883

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added 4 Sum Problem

### Checklist

- [x] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2480

2021-03-12 09:08 UTC, HarshCasper requested changes
Rest looks good to merge!

2021-03-12 09:08 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [[Maximum Subarray Sum (Constant Space)](<dp/Max_subarray_sum_constant_space(DP).cpp>)]
Revert these changes

2021-03-12 09:08 UTC, HarshCasper commented on C-Plus-Plus/other/4Sum.cpp
> +   /* Function to find combination of 4 elements that sum to given sum */
Indent the Comment properly

2021-03-12 09:08 UTC, HarshCasper commented on C-Plus-Plus/other/4Sum.cpp
> +/* Given an array of integers, find anyone combination of four elements in the array whose sum is equal to a given value X. */
Add a more detailed description

2021-03-12 19:08 UTC, kotwani2883 commented
Hii , I have made the changes and also commited but it is not showing here. Is there any way to commit to a particular pull request.I know its  very childish but since I am a newbie kindly help me!
Thanks in advance.

2021-03-13 15:12 UTC, HarshCasper requested changes

2021-03-13 15:12 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [[Maximum Subarray Sum (Constant Space)](<dp/Max_subarray_sum_constant_space(DP).cpp>)] -->
Don't comment them out. Just leave them out as it is. Rebase it from the Master

2021-03-14 19:57 UTC, kotwani2883 commented
Changes have been done

2021-03-15 04:26 UTC, closed without merging