Implementation of Stack using queues in Python
HarshCasper/NeoAlgo pull request #2822
Opened 2021-03-12 09:57 UTC by DEEPALI-SUK

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Implementation of Stack using queues in Python

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #2244

2021-03-12 10:02 UTC, DEEPALI-SUK commented
Please guide me why these errors are coming, I changed only python files but then also it is showing errors in java.

2021-03-15 12:31 UTC, HarshCasper requested changes

2021-03-15 12:31 UTC, HarshCasper commented on Python/ds/Implementation_of_Stack_using_queues.py
> +class my_stack:
Add a beginner-friendly pitch about the code

2021-03-15 12:31 UTC, HarshCasper commented on Python/ds/Implementation_of_Stack_using_queues.py
> +    # The names of my_queue1 and my_queue2 are then swapped.
Use multi-line string

2021-03-15 12:31 UTC, HarshCasper commented on Python/ds/Implementation_of_Stack_using_queues.py
> +    print('Enter n nubmers to be pushed into stack')
Use a more descriptive console statement

2021-03-16 04:38 UTC, DEEPALI-SUK commented
@HarshCasper Kindly review it now, I have made the changes accordingly.

2021-03-17 03:20 UTC, HarshCasper approved these changes

2021-03-17 03:21 UTC, merged

2021-03-27 08:59 UTC, HarshCasper commented
@all-contributors bot please add @DEEPALI-SUK for code

2021-03-27 08:59 UTC, HarshCasper commented
@all-contributors bot please add @DEEPALI-SUK for code