To find the Sum of Digits #2726
HarshCasper/NeoAlgo pull request #2839
Opened 2021-03-12 10:56 UTC by drishika2002

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for finding the sum of digits of a number in C++

### Checklist

- [☑] I've read the contribution guidelines.
- [☑] I've checked the issue list before deciding what to submit.
- [☑] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is related to #2726

2021-03-16 03:56 UTC, HarshCasper requested changes
Rest is good to merge

2021-03-16 03:56 UTC, HarshCasper commented on C-Plus-Plus/math/Sum_of_digits.cpp
> +    }
Put the logic in a separate function.

2021-03-17 12:44 UTC, drishika2002 commented on C-Plus-Plus/math/Sum_of_digits.cpp
> +    }
Okay sir

2021-03-20 11:21 UTC, HarshCasper approved these changes

2021-03-20 11:21 UTC, merged