Lucky Numbers
HarshCasper/NeoAlgo pull request #2852
Opened 2021-03-12 12:10 UTC by Anu-123-gif

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Lucky Number is a number that consists of digits 7 and 8 only. 
Find the maximum number of offices in the new building of the Tax Office given that a door-plate can hold a number not longer than n digits

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-17 02:30 UTC, iamrajiv requested changes
@Anu-123-gif Add space and time complexity. Also, add the problem link. Update the readme in this PR do not make separate PR for the readme file.

2021-03-17 02:30 UTC, iamrajiv commented on C-Plus-Plus/cp/Lucky_Numbers.cpp
> +    cin>>i;
@Anu-123-gif `i` is undeclared.

2021-03-17 17:34 UTC, iamrajiv requested changes

2021-03-17 17:34 UTC, iamrajiv commented on C-Plus-Plus/cp/Lucky_Numbers.cpp
> +Link to problem: https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/cp/Lucky_Numbers.cpp
@Anu-123-gif Add a link to the website or platform where this problem exists.

2021-03-17 19:07 UTC, iamrajiv approved these changes

2021-03-17 19:07 UTC, merged

2021-04-28 15:11 UTC, anshmishra010 commented
@ankitaggarwal23 @HarshCasper .
I am refactoring this code .
Please guide me if I did anything wrong as it's my first refactor .