Selection Sort in JavaScript
HarshCasper/NeoAlgo pull request #2868
Opened 2021-03-12 13:18 UTC by ireneelizabethsabu

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Adding algorithm for selection sort in javascript
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2505 
(Write your answer here.)

2021-03-15 17:08 UTC, ireneelizabethsabu commented
@HarshCasper please review this PR.

2021-03-17 03:10 UTC, HarshCasper requested changes

2021-03-17 03:10 UTC, HarshCasper commented on JavaScript/sort/selectionSort.js
> +//Expected output : [3,4,5,6,7,8,9]
Add a new line at the EOF

2021-03-17 03:10 UTC, HarshCasper commented on JavaScript/sort/selectionSort.js
> +//var arr = prompt("Enter numbers to sort comma separated: ").split(",");
Prefer Dynamic Input instead of static input

2021-03-17 03:10 UTC, HarshCasper commented on JavaScript/sort/selectionSort.js
> +    Space Complexity - O(1)
Add description of Selection Sort here. Shift Time/Space Complexity to the end

2021-03-17 04:49 UTC, ireneelizabethsabu commented
@HarshCasper Kindly look into the changes made.Thank you.

2021-03-20 11:22 UTC, HarshCasper approved these changes

2021-03-20 11:22 UTC, merged