Cyclesort
HarshCasper/NeoAlgo pull request #2878
Opened 2021-03-12 14:40 UTC by ireneelizabethsabu

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
YES
(Write your answer here.)

### Description
Adding cycleSort algorithm in JavaScript.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2505 
(Write your answer here.)

2021-03-13 09:00 UTC, HarshCasper requested changes

2021-03-13 09:00 UTC, HarshCasper commented on JavaScript/sort/cycleSort.js
> +*/
Add a new line at the EOF

2021-03-13 09:00 UTC, HarshCasper commented on JavaScript/sort/cycleSort.js
> +*/
Add a more descriptive pitch

2021-03-14 09:57 UTC, ireneelizabethsabu commented
@HarshCasper please review the changes made.

2021-03-17 03:08 UTC, HarshCasper requested changes
Rest is good to merge :+1:

2021-03-17 03:08 UTC, HarshCasper commented on JavaScript/sort/cycleSort.js
> +*/
Modularize this Content

2021-03-17 03:08 UTC, HarshCasper commented on JavaScript/sort/cycleSort.js
> +
Remove the extra line

2021-03-17 04:27 UTC, ireneelizabethsabu commented
@HarshCasper Updated cycleSort.js. Please look into it.

2021-03-20 11:22 UTC, HarshCasper approved these changes

2021-03-20 11:23 UTC, merged