Java Program to check if a singly linked list is a palindrome or not.
HarshCasper/NeoAlgo pull request #2891
Opened 2021-03-12 16:56 UTC by IdealisticINTJ

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes, I have.
### Description

(Write your answer here.)
This is a Java Program to check if a singly linked list is a palindrome or not. I have included proper comments throughout the code, whenever found necessary.
### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-17 03:19 UTC, HarshCasper requested changes
Few changes: 
- Make markdown updates
- Add comments at proper places
- Add a beginner description about the code
- Add dynamic input
- Add sample I/O and complexity at the end of the code

2021-03-17 07:51 UTC, IdealisticINTJ commented
I have made the required changes. However, Could you please tell me how to make markdown updates...? And, I don't get the one failing check - Java(beta).

2021-03-20 11:23 UTC, HarshCasper commented
> @HarshCasper I have made the required changes. And, I don't get the one failing check - Java(beta)...

No you have not. Make the README (Markdown) changes.

2021-03-20 12:44 UTC, IdealisticINTJ commented
I made the README changes. I am sorry. I forgot to, earlier.

2021-03-22 06:07 UTC, IdealisticINTJ commented
@HarshCasper I have made the changes 2 days ago. Could you please check it?

2021-03-26 17:08 UTC, HarshCasper requested changes

2021-03-26 17:08 UTC, HarshCasper commented on Java/other/PalindromeLinkedList.java
> +// eg. racecar, madam etc.
Use Multi-Line Comments

2021-03-26 17:09 UTC, atarax665 approved these changes
LGTM 👍

2021-03-26 17:10 UTC, atarax665 commented
Do some minor suggested changes and resolve the conflict so that I could merge the PR.

2021-03-26 17:59 UTC, IdealisticINTJ commented
Did! @atarax665

2021-03-29 09:11 UTC, IdealisticINTJ commented
I made the changes 3 days ago. Please review it @HarshCasper @atarax665.

2021-03-30 00:13 UTC, atarax665 commented
I can still see the merge conflict, please do resolve it.

2021-03-30 04:07 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here.](https://www.javatpoint.com/java-program-to-determine-whether-a-singly-linked-list-is-the-palindrome)

2021-03-30 04:08 UTC, closed without merging