C code for two issues assigned to me
HarshCasper/NeoAlgo pull request #2896
Opened 2021-03-12 17:26 UTC by TechSpiritSS

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

I wrote C code for issue #2865 and issue #2861 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #2865 
issue #2861

2021-03-12 17:27 UTC, TechSpiritSS commented
There was nothing to do in readme.md so I kept that as it is

2021-03-12 17:29 UTC, TechSpiritSS commented
This was my first pull here; I'll try to provide each issue with its own PR instead of this combined one

2021-03-14 09:19 UTC, TechSpiritSS commented
/assign

2021-03-22 12:16 UTC, RaiyanMahin commented
Don't push more than one code file into the same PR. Break down your PRs into separate PRs so that it becomes easy to review.

2021-03-22 12:18 UTC, RaiyanMahin requested changes

2021-03-22 12:18 UTC, RaiyanMahin commented on C/other/LCM.c
> +github - TechSpiritSS
remove your name

2021-03-22 12:18 UTC, RaiyanMahin commented on C/other/LCM.c
> +}
add a new line at EOF

2021-03-22 12:19 UTC, RaiyanMahin commented on C/other/LCM.c
> +#include <stdio.h>
use main function ( ) for driven the code

2021-03-22 12:21 UTC, RaiyanMahin requested changes

2021-03-22 12:21 UTC, RaiyanMahin commented on C/other/LCM.c
> +    printf("LCM of %d and %d is %d", a1,b1,a);
add time complexity and space complexity of your code

2021-03-22 12:21 UTC, RaiyanMahin commented on C/other/LCM.c
> +    }
add sample I/O

2021-03-22 12:21 UTC, RaiyanMahin commented on C/other/LCM.c
> +/*
add a beginner friendly description

2021-03-22 12:22 UTC, RaiyanMahin commented
Check some merged PR's for better understanding

2021-03-26 16:42 UTC, atarax665 commented
@TechSpiritSS Are you still working on this?

2021-03-30 00:29 UTC, closed without merging