feat: Added Arithmetic slices problem in C++ (Issue #2717)
HarshCasper/NeoAlgo pull request #2898
Opened 2021-03-12 17:26 UTC by ShreyashRoyzada

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have.

### Description

Added the Arithmetic slices problem in C++ (Issue #2717). Updated the Documentation. Fixed a small typographical error present in the C++ Readme file.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2021-03-13 08:48 UTC, iamrajiv requested changes
@ShreyashRoyzada Add space and time complexity.

2021-03-13 08:48 UTC, iamrajiv commented on C-Plus-Plus/dp/Arithmetic_Slices.cpp
> +
@ShreyashRoyzada Remove these unwanted lines.

2021-03-13 14:38 UTC, ShreyashRoyzada commented on C-Plus-Plus/dp/Arithmetic_Slices.cpp
> +
Added requested changes.

2021-03-13 22:49 UTC, iamrajiv approved these changes

2021-03-17 03:20 UTC, HarshCasper requested changes

2021-03-17 03:20 UTC, HarshCasper commented on C-Plus-Plus/dp/Arithmetic_Slices.cpp
> +
Add a description about the Code

2021-03-17 03:20 UTC, HarshCasper commented on C-Plus-Plus/dp/Arithmetic_Slices.cpp
> +int numberOfArithmeticSlices(int A[],int size) {
Add a function description

2021-03-17 03:20 UTC, HarshCasper commented on C-Plus-Plus/dp/Arithmetic_Slices.cpp
> +    }
Put Comments describing the functionality

2021-03-17 08:20 UTC, ShreyashRoyzada commented
Added requested changes

2021-03-20 11:25 UTC, HarshCasper requested changes

2021-03-20 11:25 UTC, HarshCasper commented on C-Plus-Plus/dp/Arithmetic_Slices.cpp
> +    Thus restarting the sequence when another continuous AP is found.*/
Make it compact to read and understand

2021-03-30 00:30 UTC, atarax665 commented
@ShreyashRoyzada Are you still working on this?

2021-03-30 10:33 UTC, ShreyashRoyzada commented
> @ShreyashRoyzada Are you still working on this?

Yes

2021-04-01 03:43 UTC, HarshCasper approved these changes

2021-04-01 03:43 UTC, merged