Replace Pi added
HarshCasper/NeoAlgo pull request #2901
Opened 2021-03-12 17:41 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Replace Pi using recursion added in cp(competitive programming) folder added.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2772

2021-03-13 01:10 UTC, bhav09 commented on C-Plus-Plus/cp/replace_pi.cpp
> +int main()
Great work! Can you please comment the code and write down the complexity at the end.

2021-03-13 09:52 UTC, gayatri517 commented
@bhav09 I have added the complexity and the comments in the code. Please check them.
Thank you.

2021-03-13 13:27 UTC, bhav09 requested changes
Reviewed.

2021-03-13 13:27 UTC, bhav09 commented on C-Plus-Plus/cp/replace_pi.cpp
> +Example :
Great work! A very small change needs to be made. I/O should be at last, after the code.

2021-03-13 13:40 UTC, gayatri517 commented
@bhav09 I have made the necessary changes. Kindly check them.
Thank you.

2021-03-13 14:04 UTC, bhav09 commented
Great work!

2021-03-13 14:04 UTC, merged

2021-03-25 17:34 UTC, HarshCasper commented
@all-contributors bot please add @gayatri517 for code