Solutions Added in CP
HarshCasper/NeoAlgo pull request #291
Opened 2020-07-24 15:03 UTC by mechiragjain

Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Added solution of "Remove Loop from a Linked List" in CPP Module.

2020-07-24 17:21 UTC, anushkrishnav commented
kindly alter the README to link your work and issue a PR . Good day

2020-07-31 18:24 UTC, atarax665 requested changes

2020-07-31 18:24 UTC, atarax665 commented on C++/cp/Remove_Loop_in_Linked_List.cpp
> +
Remove these unnecessary lines.

2020-07-31 18:24 UTC, atarax665 commented on C++/cp/Remove_Loop_in_Linked_List.cpp
> +    for(int i=1; i<position; i++)
As per good coding habit space should be added before and after operators.

2020-07-31 18:26 UTC, atarax665 commented
@mechiragjain Make the suggested changes and make sure that you change the README to link your work.

2020-08-29 16:52 UTC, atarax665 requested changes

2020-08-29 16:52 UTC, atarax665 commented on C++/cp/Remove_Loop_in_Linked_List.cpp
> +void removeLoop(Node* head)
Shift this function above the driver code and use proper comments where necessary.

2020-08-29 16:52 UTC, atarax665 commented
And make changes to the README.md file.

2020-09-24 16:27 UTC, atarax665 commented
The PR is being closed due to inactivity from contributor's end.

2020-09-24 16:27 UTC, closed without merging