I have wriiten code for hoe to check if a connected graph is bipartite
HarshCasper/NeoAlgo pull request #2960
Opened 2021-03-13 08:23 UTC by Ritish758

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-17 04:22 UTC, HarshCasper requested changes
Make the README changes as well

2021-03-17 04:22 UTC, HarshCasper commented on C-Plus-Plus/graphs/check_if_graph_is_bipartite.cpp
> +I am showing this problem by use of DFS and adjacency
Use a more standard description

2021-03-17 04:22 UTC, HarshCasper commented on C-Plus-Plus/graphs/check_if_graph_is_bipartite.cpp
> +        // else graph is not bipartite
Prefer multi-line comments

2021-03-17 04:22 UTC, HarshCasper commented on C-Plus-Plus/graphs/check_if_graph_is_bipartite.cpp
> +
You didn't even bother to complete the comment

2021-03-25 08:58 UTC, gargVader commented
Duplicate #1510

2021-03-26 17:10 UTC, closed without merging