Noble integer
HarshCasper/NeoAlgo pull request #2971
Opened 2021-03-13 10:32 UTC by rohanbabbar04

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Noble Integer in Mathematics section in C,C++ and Python.

### Checklist

- [ ✅] I've read the contribution guidelines.
- [✅ ] I've checked the issue list before deciding what to submit.
- [ ✅] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Added #2371

2021-03-13 10:34 UTC, rohanbabbar04 commented
Do review this PR @bhav09  @HarshCasper

2021-03-13 12:08 UTC, rohanbabbar04 commented
Could you please review the PR @ankitaggarwal23

2021-03-13 12:19 UTC, ankitaggarwal23 approved these changes

2021-03-14 07:47 UTC, ankitaggarwal23 requested changes
- Add Time and Space Complexity at the end of the Code

2021-03-14 07:47 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/Noble_Integer.cpp
> +
Remove the extra line.

2021-03-14 07:47 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/Noble_Integer.cpp
> +
Remove the extra line.

2021-03-14 07:47 UTC, ankitaggarwal23 commented on Python/math/Noble_Integer.py
> +if __name__ == "__main__" :
Give a new line after `return(-1);`

2021-03-16 05:50 UTC, ankitaggarwal23 approved these changes

2021-03-16 05:51 UTC, rohanbabbar04 commented
I have made all the changes do review @ankitaggarwal23 @HarshCasper

2021-03-18 17:52 UTC, rohanbabbar04 commented
Do approve the changes and merge @HarshCasper

2021-03-19 08:12 UTC, ankitaggarwal23 approved these changes

2021-03-19 08:13 UTC, merged