Implemented trie datastructure in Java
HarshCasper/NeoAlgo pull request #2974
Opened 2021-03-13 11:02 UTC by samar08

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description

This file contains code for Trie datastructure implemented in Java. 

### Checklist

- [√ ] I've read the contribution guidelines.
- [√ ] I've checked the issue list before deciding what to submit.
- [√ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue number: #2301

2021-03-13 11:05 UTC, samar08 commented
Please merge my pull request. Thanks and regards: A.M.Samara simha reddy

2021-03-13 12:30 UTC, ankitaggarwal23 requested changes
Few changes: 

- Remove the comment you have added at the top
- Add a beginner-friendly description at the top
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code

2021-03-14 06:41 UTC, samar08 commented
> Few changes:
> 
> * Remove the comment you have added at the top
> * Add a beginner-friendly description at the top
> * Remove extra lines of code and spaces
> * Add sample I/O at the end of the Code
> * Add Time and Space Complexity at the end of the Code

I have made the required changes, please verify them.

2021-03-14 07:15 UTC, ankitaggarwal23 requested changes

2021-03-14 07:15 UTC, ankitaggarwal23 commented on Java/ds/Trie.java
> +
Remove the line or space.

2021-03-14 07:15 UTC, ankitaggarwal23 commented on Java/ds/Trie.java
> +
Remove the line or space.

2021-03-14 07:15 UTC, ankitaggarwal23 commented on Java/ds/Trie.java
> +
Remove the line or space.

2021-03-14 07:15 UTC, ankitaggarwal23 commented on Java/ds/Trie.java
> +
Remove the line or space.

2021-03-14 07:15 UTC, ankitaggarwal23 commented on Java/ds/Trie.java
> + * trie: simha Found Enter the word to search in trie: nara Not Found
Your I/O is not readable. Use newline and space after reading input or print any output.

2021-03-14 07:15 UTC, ankitaggarwal23 commented on Java/ds/Trie.java
> + *
Remove the line or space.

2021-03-14 09:47 UTC, ankitaggarwal23 commented
@samar08 As I'm seeing you closed this issue [here](https://github.com/TesseractCoding/NeoAlgo/issues/2301) and after that we assigned it to someone else [here](https://github.com/TesseractCoding/NeoAlgo/issues/2968). So we can't review this PR again as it is already assigned to someone. Thanks, Closing this is issue.😊

2021-03-14 09:47 UTC, closed without merging