Added code for generating BST from it's Preorder Traversal #2605
HarshCasper/NeoAlgo pull request #2978
Opened 2021-03-13 11:45 UTC by sakshigoel19

### Have you read the [Contributing Guidelines on Pull Requests] (https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
 Yes

### Description

Given preorder traversal of a given BST, generate the binary search tree and return it's root.

### Checklist

- [Yes] I've read the contribution guidelines. 
- [Yes] I've checked the issue list before deciding what to submit. 
- [Yes] I've edited the `README.md` and link to my code. 

## Related Issues or Pull Requests

#2605

2021-03-13 12:06 UTC, ankitaggarwal23 approved these changes

2021-03-14 07:31 UTC, ankitaggarwal23 requested changes

2021-03-14 07:31 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/BST_from_Preorder_Traversal.cpp
> +Sample Input:
Give a new line after SC.

2021-03-14 07:31 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/BST_from_Preorder_Traversal.cpp
> + Given an array of integers which represents the preorder traversal of a Binary Search Tree
Remove the space before the word `Given`

2021-03-14 07:31 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/BST_from_Preorder_Traversal.cpp
> +    int count = 1;                        //count maintains number of nodes in tree
Add comment above the line of code.

2021-03-14 07:31 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/BST_from_Preorder_Traversal.cpp
> +    cout<<"Inorder traversal of the constructed tree: \n"; //Inorder traversal printed to view the constructed BST
Remove the unnecessary comments.

2021-03-16 05:47 UTC, sakshigoel19 commented
@ankitaggarwal23 I have made the requested changes. Please review it.

2021-03-16 06:00 UTC, ankitaggarwal23 reviewed
Rest looks good to merge

2021-03-16 06:00 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/BST_from_Preorder_Traversal.cpp
> +*/
Use multiline comments // for description

2021-03-16 06:00 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Generate BST from given preorder traversal](ds/BST_from_Preorder_Traversal.cpp)
Make your title concise like Generate BST from preorder traversal or BST from preorder traversal

2021-03-16 06:25 UTC, ankitaggarwal23 requested changes
Make the few changes

2021-03-16 06:55 UTC, sakshigoel19 commented
@ankitaggarwal23 I have made the changes asked.

2021-03-16 06:57 UTC, ankitaggarwal23 approved these changes

2021-03-16 07:01 UTC, merged