Created InfixtoPrefix program in Java
HarshCasper/NeoAlgo pull request #2987
Opened 2021-03-13 13:50 UTC by iamvs-2002

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Created program to convert an expression from Infix to Prefix in Java
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2970 
(Write your answer here.)

2021-03-13 13:56 UTC, iamvs-2002 commented
@ankitaggarwal23 Hy. Why does Java(beta) check fail even when the code is completely fine? Please help.

2021-03-13 14:07 UTC, atarax665 commented
> @ankitaggarwal23 Hy. Why does Java(beta) check fail even when the code is completely fine? Please help.

You can ignore it, there is some glitch at deepsource's end.

2021-03-13 14:21 UTC, atarax665 requested changes
The code looks good to merge, just make all the suggested changes.

2021-03-13 14:21 UTC, atarax665 commented on Java/other/InfixtoPrefix.java
> + * Infix Expression : A * B + C / D
Remove sample I/O from here as you have already added them at the end.

2021-03-13 14:21 UTC, atarax665 commented on Java/other/InfixtoPrefix.java
> + * First the gicen infix expression is reversed.
```suggestion
 * First the given infix expression is reversed.
```

2021-03-13 14:21 UTC, atarax665 commented on Java/other/InfixtoPrefix.java
> + *
Add space and time complexity of your approach.

2021-03-13 14:21 UTC, atarax665 commented on Java/other/InfixtoPrefix.java
> +        //finally, arr contains the prefix expression.
Remove trivial comments.

2021-03-13 14:21 UTC, atarax665 commented on Java/other/InfixtoPrefix.java
> +
Remove this line.

2021-03-13 15:11 UTC, iamvs-2002 commented
> > @ankitaggarwal23 Hy. Why does Java(beta) check fail even when the code is completely fine? Please help.
> 
> You can ignore it, there is some glitch at deepsource's end.

Ohh okay, thanks.

2021-03-14 18:04 UTC, atarax665 approved these changes

2021-03-14 18:04 UTC, atarax665 commented on Java/other/InfixtoPrefix.java
> + * Time Complexity: O(n^2)
Shift time and space complexity below the sample input/output.

2021-03-15 13:02 UTC, ankitaggarwal23 approved these changes

2021-03-15 13:02 UTC, merged