Added code for Sum of Digit
HarshCasper/NeoAlgo pull request #2990
Opened 2021-03-13 14:14 UTC by Sweeti-Gupta

Fixed #2726

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
-YES

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I have added the code for  calculating the sum of digits of a number and fixed the issue-2726. Please review and merge it.

2021-03-13 16:05 UTC, atarax665 requested changes

2021-03-13 16:05 UTC, atarax665 commented on Java/math/SumOfDigit.java
> +		System.out.println(x);
Format your output as ```Sum of the digits of X is Y```.

2021-03-13 16:05 UTC, atarax665 commented on Java/math/SumOfDigit.java
> +
Remove all extra blank lines.

2021-03-13 16:05 UTC, atarax665 commented on Java/math/SumOfDigit.java
> +
Add space and time complexity of the program.

2021-03-13 19:36 UTC, Sweeti-Gupta commented
Hey @atarax665, I have made all the necessary changes. Please review and merge it.

2021-03-14 05:58 UTC, Manish5237 commented
Hi ,

I am GSSOC'21 participant.
Please assign me this. I will do this in C with proper comments and test cases.

@atarax665

2021-03-15 17:06 UTC, atarax665 commented
> Hi ,
> 
> I am GSSOC'21 participant.
> Please assign me this. I will do this in C with proper comments and test cases.
> 
> @atarax665

Commented on the linked issue #2726  to get it assigned to you.

2021-03-15 17:18 UTC, atarax665 approved these changes
LGTM :)

2021-03-15 17:18 UTC, merged