[feature-1] Added Binary Search in Kotlin
HarshCasper/NeoAlgo pull request #2999
Opened 2021-03-13 15:21 UTC by kiruba-r11

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description
Added Iterative Binary Search Algorithm in Kotlin.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Closes: #2312

2021-03-13 15:22 UTC, kiruba-r11 commented
@HarshCasper and @bhav09 Please review this.

2021-03-14 05:40 UTC, bhav09 requested changes
It's perfect! However, you can add a new line at the end of the code.

2021-03-14 05:40 UTC, bhav09 commented on Kotlin/search/BinarySearch.kt
> + */
Add a new line here

2021-03-14 05:53 UTC, kiruba-r11 commented
@bhav09 I have added it👍

2021-03-14 18:30 UTC, bhav09 commented
Great!

2021-03-14 18:30 UTC, merged

2021-03-29 15:07 UTC, kiruba-r11 commented
@HarshCasper @bhav09 Please add the level and gssoc label