Sieve of atkins in C++
HarshCasper/NeoAlgo pull request #3002
Opened 2021-03-13 15:31 UTC by ShubhamGupta577

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

**Adding the code for Sieve_Of_Atkins in C++**
Sieve of Atkin is a modern algorithm for finding all prime numbers up to a specified integer. Compared with the ancient Sieve of Eratosthenes, which marks off multiples of primes, the Sieve of Atkin does some preliminary work and then marks off multiples of squares of primes, thus achieving a better theoretical asymptotic complexity.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Resolved - (#2665 )

2021-03-13 17:54 UTC, ShubhamGupta577 commented
@bhav09 Please review this.

2021-03-14 05:45 UTC, bhav09 requested changes
Reviewed.

2021-03-14 05:45 UTC, bhav09 commented on C-Plus-Plus/math/Sieve_Of_Atkins.cpp
> +	Sample input :
Can you mention I/O at the end of the code. Rest everything is picture perfect!

2021-03-14 09:59 UTC, ShubhamGupta577 commented
@bhav09 Requested changes have been made.

2021-03-14 18:52 UTC, bhav09 requested changes
Reviewed.

2021-03-14 18:52 UTC, bhav09 commented on C-Plus-Plus/math/Sieve_Of_Atkins.cpp
> +*/
Great work!
Can you add a new line at the end here. Rest everything is cool

2021-03-14 20:17 UTC, ShubhamGupta577 commented
@bhav09 Requested Change has been done. Please review it

2021-03-14 20:18 UTC, bhav09 commented
Great work! Keep it up :)

2021-03-14 20:18 UTC, merged