Added the code to check for palindrome#3001
HarshCasper/NeoAlgo pull request #3009
Opened 2021-03-13 15:56 UTC by cintamg

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
Yes

Hey @ankitaggarwal23 I have written the code.

2021-03-13 16:10 UTC, cintamg commented
@ankitaggarwal23 can you help to find out the problem with this check.

2021-03-13 16:13 UTC, ankitaggarwal23 commented
> @ankitaggarwal23 can you help to find out the problem with this check.

You can ignore it, there is some glitch at deepsource's end.

2021-03-13 16:22 UTC, cintamg commented
PR for issue #3001

2021-03-13 16:23 UTC, cintamg commented
Palindrome_or_not.c

2021-03-14 05:04 UTC, HarshCasper requested changes

2021-03-14 05:04 UTC, HarshCasper commented on C/dp/Palindrome_or_not.c
> +Output : Not palindrome
You did not even bother to end the comment body. Follow proper conventions here. Add a new line at the EOF here as well

2021-03-14 05:04 UTC, HarshCasper commented on C/dp/Palindrome_or_not.c
> +*/
Add a bit more description from a layman's point of view

2021-03-14 09:30 UTC, cintamg commented
Hey @HarshCasper, I have made all the necessary changes. Please review and merge it.

2021-03-16 03:27 UTC, HarshCasper requested changes
Make README updates as well and remove extra lines of code

2021-03-16 14:08 UTC, cintamg commented
Hey @HarshCasper, I have made all the necessary changes. Please review and merge it.

2021-03-18 07:16 UTC, cintamg commented
@ankitaggarwal23 do I need to make any more changes.

2021-03-20 07:36 UTC, cintamg commented
Hey, @HarshCasper @ankitaggarwal23 @anushkrishnav @siddharth25pandey, please do review my pr
Thank you.

2021-03-20 11:33 UTC, HarshCasper requested changes

2021-03-20 11:33 UTC, HarshCasper commented on C/dp/Palindrome_or_not.c
> +*/
Add a new line at the EOF

2021-03-20 11:33 UTC, HarshCasper commented on C/dp/Palindrome_or_not.c
> +Output : Not palindrome
Remove extra I/O samples. Add Time and Space Complexity

2021-03-20 13:41 UTC, cintamg commented
@HarshCasper I have made the changes. Please do review my pr.

2021-03-22 18:19 UTC, cintamg commented
Hey, @HarshCasper @ankitaggarwal23 @anushkrishnav @siddharth25pandey , please do review my pr
Thank you.

2021-03-26 06:42 UTC, cintamg commented
@HarshCasper I request you to review PR
Thank You

2021-03-26 17:12 UTC, HarshCasper approved these changes

2021-03-26 17:12 UTC, merged