Tarunyadav148
HarshCasper/NeoAlgo pull request #3016
Opened 2021-03-13 16:54 UTC by tarunyadav148

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Added code for checking Magic Number

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2770

2021-03-13 19:02 UTC, tarunyadav148 commented
@bhav09 Can you please review this, sorry i forget to edit PR's title

2021-03-14 04:30 UTC, HarshCasper requested changes

2021-03-14 04:30 UTC, HarshCasper commented on C-Plus-Plus/math/magic_number.cpp
> +*/
Add a new line at the EOF

2021-03-14 04:30 UTC, HarshCasper commented on C-Plus-Plus/math/magic_number.cpp
> +If single digit comes out to be 1 then the number is a Magic Number.
Use proper sentences

2021-03-14 04:30 UTC, HarshCasper commented on C-Plus-Plus/math/magic_number.cpp
> +    785 is Not Magic Number.
Remove extra I/O samples

2021-03-14 08:10 UTC, tarunyadav148 commented
I have modified the changes please review the PR @HarshCasper

2021-03-16 03:27 UTC, HarshCasper approved these changes

2021-03-16 03:27 UTC, merged