Added Trie Implementation Using Java Hashmap Closes #2968
HarshCasper/NeoAlgo pull request #3026
Opened 2021-03-13 17:50 UTC by pm0824

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
I have used Java Hashmap to implement Trie Insert and Search String Operations in efficient way.

### Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Resolved issue #2968

2021-03-13 21:27 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces

2021-03-13 21:27 UTC, ankitaggarwal23 commented on Java/ds/Trie_with_Hashmap.java
> +
-Use Multiline comments
- Remove Extra lines one line is enough.

2021-03-13 21:27 UTC, ankitaggarwal23 commented on Java/ds/Trie_with_Hashmap.java
> +//Class to define Trie node operations
Remove Extra lines one line is enough.

2021-03-13 21:27 UTC, ankitaggarwal23 commented on Java/ds/Trie_with_Hashmap.java
> +
Remove Extra lines.

2021-03-13 21:27 UTC, ankitaggarwal23 commented on Java/ds/Trie_with_Hashmap.java
> +
Remove Extra lines and unnecessary comments.

2021-03-14 05:52 UTC, pm0824 commented
Thank you for the review. I have made necessary changes, kindly check once again.

2021-03-14 07:56 UTC, ankitaggarwal23 requested changes

2021-03-14 07:56 UTC, ankitaggarwal23 commented on Java/ds/Trie_with_Hashmap.java
> +            }
Kindly properly align your this part of code.

2021-03-14 07:56 UTC, ankitaggarwal23 commented on Java/ds/Trie_with_Hashmap.java
> +
Remove that extra line.

2021-03-14 08:12 UTC, pm0824 commented
Changes made as per the request. Please review.

2021-03-14 08:59 UTC, ankitaggarwal23 approved these changes

2021-03-14 09:03 UTC, ankitaggarwal23 requested changes

2021-03-14 09:03 UTC, ankitaggarwal23 commented on Java/ds/Trie_with_Hashmap.java
> +        } while (ch == 'Y'|| ch == 'y');
- Code is not in a proper format. Take care of your braces aligning.
Ex- See your switch case braces and also it collides with cases.

2021-03-14 10:13 UTC, pm0824 commented
I have referred [`java conventions`](https://www.oracle.com/java/technologies/javase/codeconventions-statements.html) and made the changes accordingly. Kindly check it now.

2021-03-15 06:51 UTC, HarshCasper approved these changes

2021-03-15 06:51 UTC, merged