Added Sine function algorithm
HarshCasper/NeoAlgo pull request #3037
Opened 2021-03-13 19:38 UTC by XZANATOL

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

- [x] Yes

### Description

Added the algorithm for the Sine function as assigned in #2906 Issue

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue number: #2906

2021-03-13 19:42 UTC, XZANATOL commented
Most of the checks considering the Python action failed to pass becuase defining the names of variables in different scopes, but each has its own job. Shall I resubmit the Script using other names?

2021-03-13 20:45 UTC, ankitaggarwal23 commented
You can ignore it, there is some glitch at deepsource's end.

2021-03-13 20:47 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces 
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code

2021-03-13 23:17 UTC, XZANATOL commented
@ankitaggarwal23 Requested changes has been added.

2021-03-15 04:42 UTC, XZANATOL commented
@ankitaggarwal23 any updates?

2021-03-15 14:03 UTC, ankitaggarwal23 requested changes
- Remove Extra Spaces or new line(if any)

2021-03-15 14:03 UTC, ankitaggarwal23 commented on Python/math/Sine_Function.py
> +#Algorithm is a contribution to Neo-Algo at https://github.com/TesseractCoding/NeoAlgo
Kindly Remove this line.

2021-03-15 14:27 UTC, XZANATOL commented
@ankitaggarwal23 Done

2021-03-15 16:49 UTC, ankitaggarwal23 approved these changes

2021-03-15 16:54 UTC, merged