Added BST Sort in C-Plus-Plus
HarshCasper/NeoAlgo pull request #3047
Opened 2021-03-14 04:57 UTC by aish2002

Fixes #2570

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Sorts a list of numbers using binary search tree

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2570

2021-03-15 08:17 UTC, aish2002 commented
@HarshCasper , @bhav09 , @siddharth25pandey  , Kindly review the PR

2021-03-15 11:19 UTC, siddharth25pandey requested changes
@aish2002 Remove the unnecessary blank lines
Rest is fine :)

2021-03-15 11:19 UTC, siddharth25pandey commented on C-Plus-Plus/sort/BST_Sort.cpp
> +/*
Remove the blank lines

2021-03-15 11:19 UTC, siddharth25pandey commented on C-Plus-Plus/sort/BST_Sort.cpp
> +/*
Remove the blank lines

2021-03-16 08:08 UTC, aish2002 commented
I have removed the unnecessary blank lines. @siddharth25pandey  kindly re-review the PR

2021-03-17 08:29 UTC, siddharth25pandey approved these changes
@aish2002 LGTM, able to merge

2021-03-17 08:30 UTC, merged

2021-03-17 08:30 UTC, siddharth25pandey commented
@all-contributors please add @aish2002 for her code.