Issue 2910
HarshCasper/NeoAlgo pull request #3063
Opened 2021-03-14 08:25 UTC by AmanBisht01

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description

Find the point where a monotonically increasing function becomes positive first time.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue-Unbounded Binary Search #2910

2021-03-14 08:29 UTC, AmanBisht01 reviewed
Review Requested

2021-03-15 15:38 UTC, ankitaggarwal23 requested changes
Few Changes:

- Use proper names for variables

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +int binarySearch(int low, int high); // prototype
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +	// When first value itself is positive
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +// first time.
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +	// Find 'high' for binary search by repeated doubling
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +	// Call binary search
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +// of f(i) where low <= i <= high
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +		// b) f(mid-1) is negative
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +		// If f(mid) is smaller than or equal to 0
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +		else // f(mid) > 0
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +	positive value in given range */
Remove the redundant comments.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +		"positive first is "<< findFirstPositive();
Add in a single line.

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +*/
- Add sample I/O at the end of the Code

2021-03-15 15:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +*/
Use Multiline comments

2021-03-15 17:07 UTC, AmanBisht01 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +*/
done

2021-03-15 18:32 UTC, ankitaggarwal23 requested changes

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove one extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +int f(int x) { return (x*x - 10*x - 20); }
Rewrite this to: Also give proper function name as Don't use single letter to define function as it looks not meaningful.
int f(int x) 
{ 
       return (x*x - 10*x - 20); 
}

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove one extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove one extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove one extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove one extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove one extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove one extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +
Remove two extra line

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +*/
Add a new line at EOF

2021-03-15 18:32 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Unbounded_Binary_Search.cpp
> +Output : The value n where f() becomes positive first is 12
Make it as:
/*
SAMPLE OUTPUT:

Input  : x^2 - 10*x - 20
Output : The value n where f() becomes positive first is 12

2021-03-16 15:00 UTC, ankitaggarwal23 approved these changes

2021-03-16 15:03 UTC, merged