Generating all subsets iteratively
HarshCasper/NeoAlgo pull request #3092
Opened 2021-03-14 10:57 UTC by dhruvinfo28

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

### Description

closes #3067. Algorithm for generating all subsets iteratively added with time and space complexity.

### Checklist

- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [ Yes] I've edited the `README.md` and link to my code.

2021-03-18 03:10 UTC, HarshCasper requested changes
Few changes: 
- Push the primary logic of code in some other function
- Use the `main()` function only for driver code
- Format and indent the Code properly 
- Use multi-line comments wherever possible

2021-03-18 12:47 UTC, dhruvinfo28 commented
@HarshCasper  I made the requested changes kindly review.

2021-03-19 18:48 UTC, dhruvinfo28 commented
/assign

2021-03-20 12:09 UTC, HarshCasper approved these changes

2021-03-20 12:09 UTC, merged