'Concatenation of two strings' is added in the 'other' section of C file' #3024
HarshCasper/NeoAlgo pull request #3103
Opened 2021-03-14 13:25 UTC by jyoti-anjaly

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes , I have read the guidelines.

### Description

I added a new file in "Other" file in "C" . Concatenation of two strings without using strcat() function.
Issue number: #3024  

### Checklist

- [ /] I've read the contribution guidelines.
- [ /] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This issue was created by me. Issue number #3024

2021-03-15 13:55 UTC, ankitaggarwal23 requested changes

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +  // concatenate str2 to str1
Remove the redundant comments.

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +  // terminating the str1 string
Remove the redundant comments.

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +  printf("After concatenation, Final string will be: ");
Use `\n` to print the output in new line which looks more readable and understandable.

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +//The two strings str1 and str2 will be concatenated and the result will be  stored in s1.
Remove the redundant comments.

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +  // store length of str1 in the length variable
Remove the redundant comments.

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +  char str1[100] = "Hey,Open Source is amazing", str2[] = " Start contributing";   //It's important to note that the length of str1 should be sufficient to hold the string after concatenation.
- Remove the redundant comments.
- Don't fix input from yourself. Read I/P from user for both the strings.

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +#include <string.h>     //header file
Remove the redundant comments.

2021-03-15 13:55 UTC, ankitaggarwal23 commented on C/other/concatenate_two_strings.c
> +// The best way to concatenate two strings in C programming is by using the strcat() function.But,in this example, we will concatenate two strings manually.
Few changes: 

- Add a beginner-friendly description at the top and make it concise and looks readable.

2021-03-15 13:58 UTC, ankitaggarwal23 commented
@jyoti-anjaly Mark the checklist properly and update the README.md file as well.

![Capture](https://user-images.githubusercontent.com/67387053/111164959-88321580-85c4-11eb-8d66-b909230bab40.JPG)

2021-03-15 16:29 UTC, ankitaggarwal23 requested changes
Kindly Do the changes as mentioned earlier

2021-03-15 16:41 UTC, ankitaggarwal23 requested changes
Also do the changes marked above
/*
SAMPLE OUTPUT: 

After concatenation, Final string will be:
Hey,Open Source is amazing Start contributing
*/
Give new line after that.

2021-03-16 04:18 UTC, jyoti-anjaly commented
@ankitaggarwal23 Sir,I have made changes as told by use. Can you please check this? #3347

2021-03-16 04:23 UTC, closed without merging