Added code for Conversion of Binary to Decimal
HarshCasper/NeoAlgo pull request #3104
Opened 2021-03-14 13:28 UTC by sanskruti-shahu

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the guidelines.

### Description

Added code for Conversion of Binary  to Decimal

### Checklist

- [ Yes ] I've read the contribution guidelines.
- [ Yes ] I've checked the issue list before deciding what to submit.
- [ Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #3060

2021-03-14 13:28 UTC, sanskruti-shahu commented
@ankitaggarwal23 Please review this PR.

2021-03-15 06:15 UTC, sanskruti-shahu commented
@HarshCasper Please review my PR

2021-03-15 12:07 UTC, HarshCasper requested changes
Format the Code as well

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +Here, a function named binary_to_decimal will convert the given binary input into decimal number.
Keep `binary_to_decimal` in backticks

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +    //initialising variables
Redundant Comments

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +    //loop to perform conversion task
Redundant Comments

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +        //dividing number by 10 to get its digits of one's place, ten's place, etc.. in each iteration respectively
Make it shorter

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +        //multiplying remainder with power of 2 according to its place value
Make it shorter

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +        //modifying number
Redundant Comment

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +    //calling function to perform the task
Redundant Comment

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +    cin>>numberInput;
Redundant Comment

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +
Remove the extra line of Code

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +Time Complexity is O(t)    where t is number of digit in 'number'
Keep `t` in capital

2021-03-15 12:07 UTC, HarshCasper commented on C-Plus-Plus/cp/Conversion_from_Binary_to_Decimal.cpp
> +OUTPUT  56
Remove extra test-cases

2021-03-15 13:20 UTC, sanskruti-shahu commented
@ankitaggarwal23 @HarshCasper I updated changes please review

2021-03-15 13:36 UTC, HarshCasper approved these changes

2021-03-15 13:37 UTC, merged