Diameter of a binary tree
HarshCasper/NeoAlgo pull request #3105
Opened 2021-03-14 13:46 UTC by zhcet19

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-15 16:37 UTC, vanshika2906 commented
I would like to work on this. Please /assign it to  me.

2021-03-16 11:54 UTC, zhcet19 commented
@iamrajiv please review my pr

2021-03-16 11:54 UTC, zhcet19 commented
@iamrajiv please review my pr

2021-03-16 11:55 UTC, zhcet19 commented
@iamrajiv please review my pr

2021-03-16 12:09 UTC, iamrajiv approved these changes

2021-03-16 14:35 UTC, ankitaggarwal23 requested changes

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +
- Remove extra lines of spaces

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +
- Remove extra one lines of spaces

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +
- Remove extra one lines of spaces

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +
- Remove extra two lines of spaces

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +
- Remove extra one lines of spaces

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +    */
- Remove extra lines of spaces and redundant comments

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +
- Remove extra lines of spaces

2021-03-16 14:35 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +
- Remove extra two lines of spaces

2021-03-17 03:50 UTC, zhcet19 commented
I have removed extra spaces please review it now @ankitaggarwal23

2021-03-17 06:09 UTC, ankitaggarwal23 requested changes
Removing extra spaces means if you have more than one line space in your code just remove that extra line.

2021-03-17 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +struct Tree* CreateNode(int data)
Add a new line after this };

2021-03-17 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +int height(struct Tree* node)
Add a new line after this }

2021-03-17 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +int Diameter(struct Tree* node)
Add a new line above int Diameter

2021-03-17 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +int main()
Add a new line above the int main()

2021-03-17 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +      Output:-5
![Capture](https://user-images.githubusercontent.com/67387053/111422726-246b3200-8715-11eb-83ab-5ade0ec2547e.JPG)

You Code prints the output like this kindly rewrite in a proper way.

2021-03-17 06:29 UTC, zhcet19 commented
I have added changes,kindly review it

2021-03-17 06:42 UTC, ankitaggarwal23 requested changes
Rest looks good to merge.

2021-03-17 06:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Diameter_of_binary_tree.cpp
> +      Output:-Diameter of the above tree is:-5
Remove that Extra space before Output.
`Output:-` 
`Diameter of the above tree is:-5`

2021-03-17 08:02 UTC, zhcet19 commented
Removed extra spacing before output

2021-03-17 08:04 UTC, ankitaggarwal23 approved these changes

2021-03-18 10:53 UTC, zhcet19 commented
@HarshCasper please merge this pull request

2021-03-18 10:56 UTC, merged