added bit manipulation
HarshCasper/NeoAlgo pull request #3112
Opened 2021-03-14 15:29 UTC by saumyasrivastava08

I have fixed the issue #3111 
@iamrajiv please review it and merge it.

2021-03-14 18:08 UTC, iamrajiv requested changes
@saumyasrivastava08 Update the readme file by adding every program link in it. Also, add sample input-output, space and time complexity in every program. I would also suggest adding a little bit of description of the program and problem link in code comments.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/1.1 Check if Kth bit is set or not.cpp
> +//check if the kth bit is set or not
@saumyasrivastava08 Rename this program to `Check_Kth_bit_is_set_or_not.cpp`.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/2.1 Count No of Set Bits.cpp
> +//Count No of bits
@saumyasrivastava08 Rename this program to `Count_set_bits.cpp`.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/2.2 Brian Algo.cpp
> +//Power of 2
@saumyasrivastava08 Rename this program to `Brian_Kernighan's_Algorithm.cpp`.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/3.1 Power of 2.cpp
> +//Power of 2 (Naive Approach)
@saumyasrivastava08 Rename this program to `Is_power_of_2.cpp`.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/4.1 One odd occuring.cpp
> +// Only one odd ocurring number
@saumyasrivastava08 Rename this program to `One_odd_occuring.cpp`.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/5.1 Two odd occuring elements.cpp
> +// Only two odd ocurring number
@saumyasrivastava08 Rename this program to `Two_odd_occuring.cpp`.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/6.1 Power Set Using Bitwise.cpp
> +#include <iostream>
@saumyasrivastava08 Rename this program to `Power_set_using_bitwise.cpp`.

2021-03-14 18:08 UTC, iamrajiv commented on C-Plus-Plus/Bit--Manipulation/7.1 Swap even nd odd bits.cpp
> +// C++ program to swap even and
@saumyasrivastava08 Rename this program to `Power Set Using Bitwise.cpp`.

2021-03-15 05:45 UTC, saumyasrivastava08 commented
@iamrajiv check

2021-03-15 05:55 UTC, iamrajiv reviewed
@saumyasrivastava08 Add sample input-output in every program. Also, space and time complexity is not added to every program.

2021-03-16 07:25 UTC, saumyasrivastava08 commented
@iamrajiv done can you review

2021-03-16 12:07 UTC, iamrajiv approved these changes

2021-03-16 12:07 UTC, merged

2021-03-16 12:07 UTC, iamrajiv commented
@all-contributors please add @saumyasrivastava08 for her code