Updates in Cp questions in JAVA
HarshCasper/NeoAlgo pull request #314
Opened 2020-07-29 23:27 UTC by shobhu98

Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [ ] I've checked the issue list __BEFORE__ deciding what to submit
* [ ] I've read the contribution guidelines
* [ ] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

<img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

2020-07-29 23:48 UTC, shobhu98 commented
I am interested in being part of the organization .I will be a team player as well as a hard working guy. Please allow me to handle the Java and JavaScript divisions.

2020-07-30 16:49 UTC, atarax665 requested changes

2020-07-30 16:49 UTC, atarax665 commented on Java/cp/Delete_Middle_of_a_LinkedList.java
> +//Given a singly linked list, delete middle of the linked list. For example, if given linked list is 1->2->3->4->5 then linked list should be modified to 1->2->4->5.
I'll recommend to use /*.....*/ instead of // for multi-line comments.

2020-07-30 16:49 UTC, atarax665 commented on Java/cp/Delete_Middle_of_a_LinkedList.java
> +
Remove unnecessary lines.

2020-07-30 16:54 UTC, atarax665 commented
@shobhu98 Its not a great practice to commit all the files in the same branch. Please make pull requests separately for various issues.

2020-07-30 16:56 UTC, shobhu98 commented
From next time I will make sure.
I am new to open source.

Excuse me for this

2020-07-30 16:56 UTC, shobhu98 commented
Can you merge?

2020-08-05 13:26 UTC, atarax665 commented
@shobhu98 I am closing this PR, it would be better if you re-fork this repo and raise PR for various issues separately. Go through this link for better understanding. [How to open multiple pull requests](https://stackoverflow.com/questions/8450036/how-to-open-multiple-pull-requests-on-github)

2020-08-05 13:26 UTC, closed without merging