Children Sum Property
HarshCasper/NeoAlgo pull request #3163
Opened 2021-03-14 18:11 UTC by Shreyash41

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

### YES

### Description

Implemented Children Sum Property which is the basic concept of Trees using C++ Language.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2936

2021-03-16 12:43 UTC, Shreyash41 commented
@HarshCasper @bhav09 Sir, Can you Please Review My PR.

2021-03-16 19:53 UTC, bhav09 commented on C-Plus-Plus/graphs/Childern_Sum_Property.cpp
> +*/
Add a new line at EOF

2021-03-16 19:54 UTC, bhav09 commented on C-Plus-Plus/graphs/Childern_Sum_Property.cpp
> +Time Complexity : O(n)
Complexity should after code.

2021-03-16 19:55 UTC, bhav09 requested changes
Reviewed.
See the comments

2021-03-17 04:12 UTC, merged

2021-03-17 04:12 UTC, bhav09 commented
Great work :)

2021-03-17 04:56 UTC, Shreyash41 commented
@bhav09 Thank you sir for your appreciation :)

2021-03-28 10:38 UTC, HarshCasper reviewed
Code plagiarized from [here](https://saividyanand.blogspot.com/2020/07/given-binary-tree-your-task-is-to.html)