Added Crossword Puzzle Code in Python
HarshCasper/NeoAlgo pull request #3192
Opened 2021-03-14 20:02 UTC by arnab031

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Crossword Puzzle Problem

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Added Crossword Puzzle Code in python and update readme.md

2021-03-18 03:26 UTC, HarshCasper requested changes

2021-03-18 03:26 UTC, HarshCasper commented on .deepsource.toml
> +  import_paths = ["github.com/arnab031/NeoAlgo"]
Why did you change the `.deepsource.toml` after all?

2021-03-18 03:26 UTC, HarshCasper commented on .deepsource.toml
> -  runtime_version = "8"
Why did you remove this?

2021-03-18 03:26 UTC, HarshCasper commented on Python/cp/crossword_puzzle.py
> +def solveCrossword(crossword0, words0, index0, wordfill0):
Add function docstring

2021-03-18 03:26 UTC, HarshCasper commented on Python/cp/crossword_puzzle.py
> +def removeHorizontally(i1, j1, crossword1, words1, index1, wordfill1):
Add function docstring

2021-03-18 03:26 UTC, HarshCasper commented on Python/cp/crossword_puzzle.py
> +def insertHorPoss(i2, j2, crossword2, words2, index2, wordfill2):
Add function docstring

2021-03-18 03:26 UTC, HarshCasper commented on Python/cp/crossword_puzzle.py
> +def insertVerPoss(i3, j3, crossword3, words3, index3, wordfill3):
Add function docstring

2021-03-18 03:26 UTC, HarshCasper commented on Python/cp/crossword_puzzle.py
> +def removeVertically(i4, j4, crossword4, words4, index4, wordfill4):
Add function docstring

2021-03-18 03:26 UTC, HarshCasper commented on Python/cp/crossword_puzzle.py
> +def printCrossword(crossword5):
Add function docstring

2021-03-30 00:38 UTC, atarax665 commented
No update

2021-03-30 00:38 UTC, closed without merging