Generate all valid parentheses (Backtracking Algorithm) #2926
HarshCasper/NeoAlgo pull request #3193
Opened 2021-03-14 20:26 UTC by kanchan1910

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Program to generate all combinations of well-formed parentheses.

### Checklist

- [ yes] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

2021-03-14 20:38 UTC, kanchan1910 commented
@bhav09, Kindly review this, and if any changes required please let me know.

Thank you sir for your time!

2021-03-15 05:23 UTC, bhav09 requested changes
Reviewed.

2021-03-15 05:23 UTC, bhav09 commented on C-Plus-Plus/cp/Generate_all_valid_parentheses_combinations.cpp
> +Sample test cases :
Can you please add the test case at the end of the code after the complexity.

2021-03-15 06:16 UTC, kanchan1910 commented
@bhav09 sir, kindly check now!

2021-03-15 06:29 UTC, bhav09 requested changes
Add all the comments should be above the line of code. Rest, perfect.

2021-03-15 06:29 UTC, bhav09 commented on C-Plus-Plus/cp/Generate_all_valid_parentheses_combinations.cpp
> +	vector<string>ans;  // this is our output vector
Comments should be above the line of code. and not alongside. Please work on it. Rest everything is fine. Great work!

2021-03-15 06:41 UTC, bhav09 commented
Great work @kanchan1910!

2021-03-15 06:41 UTC, merged

2021-03-15 06:46 UTC, kanchan1910 commented
@bhav09 Thank you so much, sir!

2021-03-28 13:50 UTC, kanchan1910 commented
@bhav09, sir, kindly check this, why my score is not getting updated.

https://gssoc.girlscript.tech/profile.html?id=kanchan1910

Thank you for your time