4Sum problem added and updated Readme
HarshCasper/NeoAlgo pull request #3217
Opened 2021-03-15 04:21 UTC by kotwani2883

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added 4 Sum Problem

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2480

2021-03-15 09:58 UTC, iamrajiv approved these changes

2021-03-22 10:47 UTC, kotwani2883 commented
I have resolved the conflicts kindly give it a check.

2021-03-23 10:48 UTC, siddharth25pandey requested changes
@kotwani2883 Do the changes as suggested

2021-03-23 10:48 UTC, siddharth25pandey commented on C-Plus-Plus/README.md
> +- [[Maximum Subarray Sum (Constant Space)](<dp/Max_subarray_sum_constant_space(DP).cpp>)]
Remove one line (Duplication of same line)

2021-03-23 10:48 UTC, siddharth25pandey commented on C-Plus-Plus/other/4Sum.cpp
> +	int n;
Write good naming convention

2021-03-23 10:48 UTC, siddharth25pandey commented on C-Plus-Plus/other/4Sum.cpp
> +	cin >> n;
Display a message in print form as what are you taking input from the user

2021-03-23 10:48 UTC, siddharth25pandey commented on C-Plus-Plus/other/4Sum.cpp
> +	cin >> sum;
Display a message in print form as what are you taking input from the user

2021-03-23 10:48 UTC, siddharth25pandey commented on C-Plus-Plus/other/4Sum.cpp
> +	findFourElements(a, n, sum);
Display a message in print form as what are you displaying output to the user

2021-03-23 10:48 UTC, siddharth25pandey commented on C-Plus-Plus/other/4Sum.cpp
> +	int a[n];
Write good naming convention

2021-03-24 11:03 UTC, kotwani2883 commented
I have made the changes.Kindly give it a check.

2021-03-25 05:54 UTC, siddharth25pandey requested changes
@kotwani2883 Minor changes is required

2021-03-25 05:54 UTC, siddharth25pandey commented on C-Plus-Plus/README.md
> -- [Trapping Rainwater](other/trappingRainwater.cpp)
unnecessary deletion of the previous content,
Add it.

2021-03-25 07:26 UTC, kotwani2883 commented
Kindly Check. I have made the changes.
Thanks!!

2021-03-25 07:41 UTC, siddharth25pandey approved these changes
@kotwani2883 LGTM, able to merge

2021-03-25 07:41 UTC, merged

2021-03-25 07:41 UTC, siddharth25pandey commented
@all-contributors please add @kotwani2883 for her code