1st negative number in every window size of k
HarshCasper/NeoAlgo pull request #3277
Opened 2021-03-15 12:33 UTC by bitaashna

#2304
#3265 
Description

One of the variable sliding window problem has been solved and implemented using c++.

Checklist

I've read the contribution guidelines.
I've checked the issue list before deciding what to submit.
I've edited the README.md and link to my code.
#C++
#2304

2021-03-15 14:05 UTC, siddharth25pandey requested changes
@bitaashna Do the suggested changes

2021-03-15 14:05 UTC, siddharth25pandey commented on C-Plus-Plus/README.md
> +
Remove the blank lines

2021-03-15 14:05 UTC, siddharth25pandey commented on C-Plus-Plus/README.md
> +
Remove the blank lines

2021-03-15 14:05 UTC, siddharth25pandey commented on C-Plus-Plus/sliding_window/1st_negative_no_in_every_window_of_size_k.cpp
> +	int n;
Please use a good naming convention

2021-03-15 14:05 UTC, siddharth25pandey commented on C-Plus-Plus/sliding_window/1st_negative_no_in_every_window_of_size_k.cpp
> +		cout<<ans[i]<<" ";
Display a message (before this) what you are printing for better user-interface.

2021-03-15 14:05 UTC, siddharth25pandey commented on C-Plus-Plus/sliding_window/1st_negative_no_in_every_window_of_size_k.cpp
> +	cin>>n;
Display message what you are taking input from the user

2021-03-15 14:05 UTC, siddharth25pandey commented on C-Plus-Plus/sliding_window/1st_negative_no_in_every_window_of_size_k.cpp
> +		cin>>arr[i];
Display message what you are taking input from the user

2021-03-15 14:06 UTC, siddharth25pandey commented
@bitaashna Also, no need to create multiple commits for a single PR

2021-03-15 16:41 UTC, bitaashna commented
> @bitaashna Do the suggested changes

I have made the changes @siddharth25pandey 
Please check it.

2021-03-16 06:04 UTC, siddharth25pandey commented
@bitaashna Too many commits for single PR. Better to create a new PR

2021-03-16 06:04 UTC, closed without merging