Aggressive cows added
HarshCasper/NeoAlgo pull request #3279
Opened 2021-03-15 12:50 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Aggressive cows program added in cp( competitive programming folder)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3215 

kindly review my PR @bhav09 
Thank you.

2021-03-15 14:01 UTC, bhav09 requested changes
Reviewed.

2021-03-15 14:01 UTC, bhav09 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +Output : 2  */
Add a new line here, EOF.

2021-03-15 14:01 UTC, bhav09 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +// Time Complexity : O(nlogn)
Complexity should be at the end of the code.

2021-03-15 14:16 UTC, gayatri517 commented
@bhav09 Changes added. Kindly check them.
Thank you.

2021-03-15 16:07 UTC, bhav09 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +*/
Add a new line here. EOF.

2021-03-15 17:50 UTC, gayatri517 commented
@bhav09 new line added, Kindly check it.
Thank you.

2021-03-16 12:40 UTC, gayatri517 commented
Kindly have look at my PR. Thank you.
@HarshCasper

2021-03-17 10:43 UTC, gayatri517 commented
@bhav09 kindly take look at my PR. 
Thank you.

2021-03-18 13:02 UTC, gayatri517 commented
@HarshCasper @ankitaggarwal23 @siddharth25pandey 
@bhav09 please review my PR.
Thank you.

2021-03-19 04:26 UTC, siddharth25pandey requested changes
@gayatri517 Do the suggested changes

2021-03-19 04:26 UTC, siddharth25pandey commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	int cows;
Display message, what are you taking input from the user

2021-03-19 04:26 UTC, siddharth25pandey commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	//Input of the stall coordinates
Display message, what are you taking input from the user

2021-03-19 04:26 UTC, siddharth25pandey commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +
Display output message for better user-interface

2021-03-19 07:37 UTC, ankitaggarwal23 requested changes

2021-03-19 07:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +using namespace std;
Add a new line after using namespace std;

2021-03-19 07:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	int cows;
Shift these variable declaration to a single line i.e `int stalls[100], n, cows;`

2021-03-19 07:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	//Input of the stall coordinates
Remove the redundant comments

2021-03-19 07:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	int e = stalls[n - 1] - stalls[0];
Use proper naming convention for declaring variables, Don't use single letters.

2021-03-19 07:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +Output : 2
Remove the extra test case one is enough

2021-03-19 07:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +EOF
Remove the word EOF
Add Space Complexity

2021-03-19 07:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +*/
Add a new after */

2021-03-19 08:09 UTC, closed without merging