Updated LinkedList.cpp
HarshCasper/NeoAlgo pull request #328
Opened 2020-08-02 14:23 UTC by YashThakare

Implemented Reversing a  Linked List in C++ and  corrected the error in the program

2020-08-03 07:57 UTC, atarax665 commented
I find the changes to be superfluous.

2020-08-13 15:26 UTC, YashThakare commented
Please updated my work

2020-08-14 18:28 UTC, YashThakare commented
@iamrajiv Please update my work

2020-08-14 18:40 UTC, iamrajiv requested changes
@YashThakare update the readme file

2020-08-14 18:40 UTC, iamrajiv commented on C++/ds/LinkedList.cpp
> +void ReverseList()  //To Reverse a Linked List
@YashThakare I think you have implemented an iterative way of reversing the linked list so mention that in the code comments. Also, add time and space complexity for the same.

2020-08-14 18:41 UTC, iamrajiv commented
@YashThakare Please, resolve merge conflicts

2020-08-15 08:57 UTC, YashThakare commented
I will resolve merge conflicts @iamrajiv

2020-10-31 00:18 UTC, closed without merging