Removes duplicates from a linked list without using extra space
HarshCasper/NeoAlgo pull request #3285
Opened 2021-03-15 14:06 UTC by sumitgsh

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)
It removes the duplicates in a linked list without using extra storage (in JAVA)
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2357

2021-03-15 14:09 UTC, sumitgsh commented
@HarshCasper @ankitaggarwal23 @bhav09 please review my PR

2021-03-16 03:47 UTC, HarshCasper requested changes

2021-03-16 03:47 UTC, HarshCasper commented on Java/README.md
> +-[Remove Duplicate In a Unsorted Linked List(No Extra Space Allowed)](ds/RemDupInLLWithoutExtraSpace.java)
Make it proper

2021-03-16 03:47 UTC, HarshCasper commented on Java/ds/RemDupInLLWithoutExtraSpace.java
> + */
Add a new line at the EOF

2021-03-16 03:47 UTC, HarshCasper commented on Java/ds/RemDupInLLWithoutExtraSpace.java
> +/* Java Program to Remove Duplicates from a Unsorted Linked List
Add more information

2021-03-16 05:35 UTC, closed without merging