Added the code for deletion of elements from the LinkedList using Java
HarshCasper/NeoAlgo pull request #3326
Opened 2021-03-15 17:46 UTC by sofia0605

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes

Hey, @HarshCasper I have added the code. Please check it

2021-03-16 03:50 UTC, HarshCasper requested changes

2021-03-16 03:50 UTC, HarshCasper commented on Java/ds/DeleteElementLL.java
> +		   list.createList(1);
Make it dynamic input

2021-03-16 03:50 UTC, HarshCasper commented on Java/ds/DeleteElementLL.java
> + */
Add a new line at the EOF

2021-03-17 17:06 UTC, sofia0605 commented
@HarshCasper I have made the changes please review it.

2021-03-18 05:09 UTC, HarshCasper approved these changes

2021-03-18 05:09 UTC, merged

2021-03-26 08:45 UTC, HarshCasper commented
@all-contributors bot please add @Puja-Kumari-909 for code