Added Middle Of LinkedList in Java
HarshCasper/NeoAlgo pull request #3334
Opened 2021-03-15 19:09 UTC by Priya730

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added the code to find the Middle Element of a LinkedList in JAVA. 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes issue #2337

2021-03-15 19:15 UTC, Priya730 commented
@HarshCasper It would be very helpful if you could provide feedback and review the PR. Thanks!

2021-03-16 03:39 UTC, HarshCasper requested changes

2021-03-16 03:39 UTC, HarshCasper commented on Java/ds/MiddleOfLinkedList.java
> +
Make the User Input dynamic

2021-03-16 03:39 UTC, HarshCasper commented on Java/ds/MiddleOfLinkedList.java
> +**/
Left-Align the Content

2021-03-16 03:39 UTC, HarshCasper commented on Java/ds/MiddleOfLinkedList.java
> +package linkedList;
Remove the package

2021-03-16 03:39 UTC, HarshCasper commented on Java/ds/MiddleOfLinkedList.java
> + */
Add complexity of the Code

2021-03-18 12:16 UTC, ankitaggarwal23 requested changes

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +**/
Remove this line as you already mentioned at the EOF of the code and Extra one *

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +public class MiddleOfLinkedList {
Missing java header file

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +        // constructor
Remove redundant comments

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +
Remove all redundant comments and align your code properly

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +    }
Remove redundant comments and extra line

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +        // Creating a linked list
Remove redundant comments

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +        //size of linked list
Remove redundant comments

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +        //Input for the Linked list
Remove redundant comments

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +        //Linked List created
Remove redundant comments

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +        list.printList();  //prints list
Remove redundant comments

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +    }
Remove redundant comments and extra line

2021-03-18 12:16 UTC, ankitaggarwal23 commented on Java/ds/MiddleOfLinkedList.java
> +  Time Complexity: O(n) Space Complexity: O(1)
Shift Space Complexity to new line

2021-03-26 17:13 UTC, HarshCasper approved these changes

2021-03-26 17:13 UTC, merged