Topological Sort in Simple Approach
HarshCasper/NeoAlgo pull request #3345
Opened 2021-03-16 03:11 UTC by HarshitPandey251

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Topological Sort in C++

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3344

2021-03-16 03:13 UTC, HarshitPandey251 commented
kindly review my PR @bhav09
Thank you.

2021-03-16 03:35 UTC, HarshCasper requested changes

2021-03-16 03:35 UTC, HarshCasper commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +//not a DAG.
Use Multi-Line Comments

2021-03-16 03:35 UTC, HarshCasper commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +void createGraph()
Add function description

2021-03-16 03:35 UTC, HarshCasper commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +void topoSortFun(int i)
Add function description

2021-03-16 03:35 UTC, HarshCasper commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +void topoSort()
Add function description

2021-03-16 03:42 UTC, HarshitPandey251 commented
ok

2021-03-16 04:56 UTC, HarshitPandey251 commented
I add description in every function. Now Check it @HarshCasper 
Thank you!

2021-03-16 05:28 UTC, ankitaggarwal23 approved these changes

2021-03-17 14:15 UTC, HarshitPandey251 commented
@ankitaggarwal23 @HarshCasper why does it take time to merge if the PR is approved?

2021-03-18 03:35 UTC, HarshCasper commented
> @ankitaggarwal23 @HarshCasper why does it take time to merge if the PR is approved?

Don't think that we don't know that you are plagiarizing code from somewhere in your PRs :wink: 

We have had three plagiarism reports, which is enough to count your ban from the project. I will tag some more maintainers here to have a look at the code: @anushkrishnav @atarax665 @iamrajiv

2021-03-18 14:38 UTC, HarshitPandey251 commented
I just make PR of program which I have work on project and have code written on my personal storage. First time I making PR so don't know about "plagiarism", after knowing I have check every detail I have written and then only asked to merge.
Thank you!!

2021-03-23 13:30 UTC, atarax665 requested changes

2021-03-23 13:30 UTC, atarax665 commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +    createGraph();
Add proper input/output prompts.

2021-03-23 14:13 UTC, HarshitPandey251 commented
kindly review my PR @atarax665

2021-03-23 18:41 UTC, iamrajiv approved these changes

2021-03-26 17:17 UTC, atarax665 requested changes

2021-03-26 17:17 UTC, atarax665 commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +Input:
Update your sample I/O according to your code. The sample I/O should be the same as it will look on the terminal when someone runs the program.

2021-03-26 17:40 UTC, HarshitPandey251 commented
I have done changes now Check it @atarax665

2021-03-27 16:45 UTC, ankitaggarwal23 requested changes
Rest looks good to merge

2021-03-27 16:45 UTC, ankitaggarwal23 commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +void display()
Add a new line above void display

2021-03-27 16:45 UTC, ankitaggarwal23 commented on C-Plus-Plus/sort/Topological_Sort.cpp
> +int main()
Add a new line above int main

2021-03-27 16:58 UTC, HarshitPandey251 commented
ok

2021-03-27 17:02 UTC, HarshitPandey251 commented
I have done changes now Check it @ankitaggarwal23

2021-03-27 18:02 UTC, ankitaggarwal23 approved these changes

2021-03-27 18:03 UTC, merged