Uploading the code for long factorials solving Issue #2452
HarshCasper/NeoAlgo pull request #3365
Opened 2021-03-16 07:12 UTC by Saviour1001

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

### Description

The algorithm of finding long factorials is already present in the algorithm database but isn't that understandable. It uses a lot of inbuilt functions and thus is hard to follow. I have added a different way to find the output and have explained it much better. Thus I have enhanced the existing algorithm.

### Checklist

- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [ Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR solves issue #2452
I had tried merging another PR earlier #2496 but it had conflicts with the Readme file. So I am closing #2496  and this PR will be the alternative.

2021-03-18 05:16 UTC, HarshCasper requested changes
Format your Code properly

2021-03-18 05:16 UTC, HarshCasper commented on C-Plus-Plus/cp/long_factorials.cpp
> + */
Add a new line at the EOF

2021-03-18 05:16 UTC, HarshCasper commented on C-Plus-Plus/cp/long_factorials.cpp
> +// Time Complexity = O(N)
Comment inside a Comment?

2021-03-18 05:16 UTC, HarshCasper commented on C-Plus-Plus/cp/long_factorials.cpp
> +   Output: 1307674368000
Keep only one sample I/O

2021-03-18 06:29 UTC, Saviour1001 commented
Did the changes which were asked. @HarshCasper

2021-03-18 12:03 UTC, ankitaggarwal23 requested changes

2021-03-18 12:03 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/long_factorials.cpp
> +
Remove the extra two lines one is enough

2021-03-18 12:03 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/long_factorials.cpp
> +#include <iostream>
Replace this header file with `#include<bits/stdc++.h>`

2021-03-18 12:03 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/long_factorials.cpp
> +   Output: 1307674368000
Remove that 1. and space before I/P and O/P

2021-03-18 12:03 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/long_factorials.cpp
> +Time Complexity = O(N)
Add Space Complexity at the end of the Code

2021-03-18 12:03 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/long_factorials.cpp
> + */
Add a new line at the EOF

2021-03-18 12:42 UTC, Saviour1001 commented
Did the changes @ankitaggarwal23

2021-03-20 11:33 UTC, HarshCasper requested changes
Make README changes as well

2021-03-20 13:05 UTC, Saviour1001 commented
Done @HarshCasper

2021-03-22 11:40 UTC, HarshCasper approved these changes

2021-03-22 11:40 UTC, merged