1st_negative_no_in_every_window
HarshCasper/NeoAlgo pull request #3368
Opened 2021-03-16 07:26 UTC by bitaashna

### Have you read the [Contributing Guidelines on Pull Requests]
Yes,I have read it

### Description
I have implemented the code to find maximum sum subarray of size k with the help of sliding window in cpp .

### Checklist

- [x]  I've read the contribution guidelines.
- [x]  I've checked the issue list before deciding what to submit.
- [x]  I've edited the README.md and link to my code.

### Related Issues or Pull Requests
#2304

2021-03-16 17:51 UTC, HarshCasper requested changes
Indent and format the code properly

2021-03-16 17:51 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [First Negative Number in Every window of size k](sliding_window/1st_negative_no_in_every_window_of_size_k.cpp)
Move this to `cp`

2021-03-17 01:30 UTC, bitaashna reviewed
@HarshCasper I have made the changes.Please review!!

2021-03-17 05:00 UTC, HarshCasper requested changes
Format the Code using a formatter

2021-03-17 05:43 UTC, bitaashna reviewed
@HarshCasper I have formatted the code.Please check!

2021-03-20 12:09 UTC, HarshCasper requested changes

2021-03-20 12:09 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Peak element](cp/Peak_element.cpp]
Not done properly

2021-03-20 12:09 UTC, HarshCasper commented on C-Plus-Plus/1st_negative_no_in_every_window_of_size_k.cpp
> + size-window_size+1 elements
Make it more intuitive

2021-03-20 15:44 UTC, bitaashna reviewed
@HarshCasper please review!

2021-03-23 11:08 UTC, bitaashna commented
@HarshCasper Sorry for the inconvenience but I will be creating a fresh PR..as I deleted the forked repo and forked it again.
So to avoid any issue, I will be opening a new PR

2021-03-23 11:08 UTC, closed without merging