Jump Game
HarshCasper/NeoAlgo pull request #3379
Opened 2021-03-16 08:48 UTC by Amanduttbhagat

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

We need to find the minimum number of jumps to reach the end of the array starting from the first element of the array,
jumps value would be (-1) if we are not able to reach the end of the array

example : array = {2,3,0,1,4,1,1,2,0,3,5}
minimum jumps = 5 {2 to 3, 3 to 4, 4 to 2, 2 to 3, 3 to 5}

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3346

2021-03-16 09:15 UTC, Amanduttbhagat commented
@HarshCasper @siddharth25pandey @iamrajiv please review my PR

2021-03-16 09:16 UTC, Amanduttbhagat commented
@ankitaggarwal23 please review my PR

2021-03-16 15:20 UTC, ankitaggarwal23 requested changes
Few changes: 

- Use proper code Format and align your code properly
- Remove the redundant comments
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code  
- Add a new line at the EOF

2021-03-16 16:06 UTC, Amanduttbhagat commented
@ankitaggarwal23  can you review it again

2021-03-17 13:56 UTC, Amanduttbhagat commented
@ankitaggarwal23 please review the changes

2021-03-17 13:58 UTC, Amanduttbhagat commented
@ankitaggarwal23  I have removed redundant comments and lines, if I'll remove more lines then it would be difficult to read

2021-03-18 05:59 UTC, ankitaggarwal23 requested changes
Rest looks good to merge.

2021-03-18 05:59 UTC, ankitaggarwal23 commented on Java/cp/Jump_Game.java
> +			System.out.println("minimum number of Jumps required : "+jumps);
Remove two tabs space make it to one tab space.

2021-03-18 06:26 UTC, Amanduttbhagat commented
@ankitaggarwal23 I have removed two tabs space and made it to one tab space.

2021-03-18 06:43 UTC, ankitaggarwal23 approved these changes

2021-03-18 06:45 UTC, merged

2021-03-18 06:46 UTC, Amanduttbhagat commented
Thank you @ankitaggarwal23

2021-03-18 07:51 UTC, Amanduttbhagat commented
@ankitaggarwal23 can you check #3592 also
Thank you