interesting xor solution added
HarshCasper/NeoAlgo pull request #3381
Opened 2021-03-16 09:09 UTC by vabhv1903

fixes #3051

2021-03-21 13:53 UTC, HarshCasper requested changes
Make README changes and add a new line at the EOF

2021-03-22 07:26 UTC, vabhv1903 commented
> Make README changes and add a new line at the EOF

done sir

2021-03-30 00:48 UTC, atarax665 requested changes

2021-03-30 00:48 UTC, atarax665 commented on C-Plus-Plus/cp/interestingxor.cpp
> +Example Input
Shift the sample I/O and complexities at the end of the program.

2021-03-30 00:48 UTC, atarax665 commented on C-Plus-Plus/README.md
> +
Remove this extra line.

2021-03-30 00:48 UTC, atarax665 commented on C-Plus-Plus/cp/interestingxor.cpp
> +        //used to calculate length of string
Remove such trivial comments, use comments only where necessary.

2021-03-30 00:48 UTC, atarax665 commented on C-Plus-Plus/cp/interestingxor.cpp
> +        cin >> N;
Use proper input/output statements to make your program more interactive.

2021-03-30 00:48 UTC, atarax665 commented on C-Plus-Plus/cp/interestingxor.cpp
> +*/
Add a line at EOF

2021-04-04 11:03 UTC, ankitaggarwal23 requested changes
Do the changes mentioned.

2021-04-09 06:36 UTC, ankitaggarwal23 reviewed
Are you still working on it.

2021-04-17 03:37 UTC, ankitaggarwal23 commented
Closing this due to inactivity since last 21 days. Thank you for your valuable time.😊

2021-04-17 03:38 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity since last 21 days. Thank you for your valuable time.😊

2021-04-17 03:38 UTC, closed without merging