Adding file and updated readme issue-3337
HarshCasper/NeoAlgo pull request #3383
Opened 2021-03-16 09:27 UTC by Mohim-Singla

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This program check if the given tree is binary tree or not through recursion.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3337

2021-03-19 09:28 UTC, bhav09 requested changes
Reviewed.

2021-03-19 09:28 UTC, bhav09 commented on C-Plus-Plus/ds/Check_for_Binary_search_tree.cpp
> +*/
Add a new at EOF

2021-03-19 09:28 UTC, bhav09 commented on C-Plus-Plus/ds/Check_for_Binary_search_tree.cpp
> +Validating BST: This program check if the given tree is BST or not.
Can you describe a BST here. The description here is very short.

2021-03-19 10:49 UTC, Mohim-Singla commented
@bhav09 Made the required changes in the program.

2021-03-21 13:56 UTC, HarshCasper requested changes
Format your code properly as well

2021-03-21 13:56 UTC, HarshCasper commented on C-Plus-Plus/ds/Check_for_Binary_search_tree.cpp
> +    root=create(root, 32);
Use dynamic input

2021-03-21 16:16 UTC, Mohim-Singla commented
@HarshCasper  done

2021-03-30 00:54 UTC, atarax665 requested changes

2021-03-30 00:54 UTC, atarax665 commented on C-Plus-Plus/ds/Check_for_Binary_search_tree.cpp
> +
Include ```#include <limit.h>``` as you have used INT_MIN and INT_MAX. Or you can also use ```#include <bits/stdc++.h>``` directly.

2021-03-30 17:07 UTC, Mohim-Singla commented
@atarax665 resolved.

2021-04-05 13:35 UTC, HarshCasper approved these changes

2021-04-05 13:35 UTC, merged