Rabin Karp Algorithm implemented
HarshCasper/NeoAlgo pull request #340
Opened 2020-08-07 04:25 UTC by parjanyaacoder

Implemented Rabin Karp Algorithm which is a pattern searching algorithm in Java. 

- [x] I've checked the issue list before deciding what to submit.
- [x] I've read the contribution guidelines.
- [x] I've edited the `README.md` link to my code.

Fixes #334

2020-08-07 07:18 UTC, atarax665 requested changes

2020-08-07 07:18 UTC, atarax665 commented on Java/cp/Rabin_Karp.java
> +import java.util.*;
Add Rabin-Karp algorithm's description.

2020-08-07 07:18 UTC, atarax665 commented on Java/cp/Rabin_Karp.java
> +   int indexI,indexJ,locationIndex=-1,count=0;
Try following [Google java style guide](https://google.github.io/styleguide/javaguide.html) to write readable and clean code. For now, add space before and after each operator.

2020-08-08 02:45 UTC, parjanyaacoder commented on Java/cp/Rabin_Karp.java
> +import java.util.*;
@atarax665 Please review.

2020-08-08 07:40 UTC, atarax665 approved these changes

2020-08-08 07:41 UTC, atarax665 commented
LGTM! Great work @parjanyaacoder

2020-08-08 07:41 UTC, merged