Issue 2509
HarshCasper/NeoAlgo pull request #3408
Opened 2021-03-16 13:06 UTC by hritikgupta92

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Level Order Traversal is the traversal of the nodes in a binary tree in a BFS( Breadth First Search) order 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-16 18:32 UTC, HarshCasper requested changes

2021-03-16 18:32 UTC, HarshCasper commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +
Add sample I/O and code complexity

2021-03-16 18:32 UTC, HarshCasper commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +    //  Input Values here
Remove the redundant comment

2021-03-16 18:32 UTC, HarshCasper commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +      Level Order Traversal for the following Tree will be   :  3 4 5 6 7
Remove this

2021-03-16 18:32 UTC, HarshCasper commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +      a level Order i.e in a BFS( Breadth First Search) order.
Add a bit more information

2021-03-17 04:39 UTC, hritikgupta92 commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +
Done

2021-03-17 04:40 UTC, hritikgupta92 commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +      Level Order Traversal for the following Tree will be   :  3 4 5 6 7
Ok I have removed this now

2021-03-17 04:40 UTC, hritikgupta92 commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +      a level Order i.e in a BFS( Breadth First Search) order.
done

2021-03-17 04:41 UTC, hritikgupta92 commented on C-Plus-Plus/ds/LevelOrderTraversal.cpp
> +    //  Input Values here
Done

2021-03-17 04:55 UTC, HarshCasper approved these changes

2021-03-17 04:56 UTC, merged