added GitHub action for auto label issues
HarshCasper/NeoAlgo pull request #342
Opened 2020-08-07 09:20 UTC by atarax665

Please read [how to contribute](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md) First.

### Description

GitHub action to label issues based on the body content of the issue.

Checklist:

- [X] I've checked the issue list before deciding what to submit.
- [X] I've read the contribution guidelines.
- [ ] I've edited the `README.md` link to my code.

### References to other Issues or PRs

Fixes:

### Don't forget to visit our [website](https://www.tesseractcoding.tech/)!

Feel free to add this badge after your submission is accepted!

<img src="https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen?style=flat-square" />

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
<img src="https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen?style=flat-square" />
</a>
```

2020-08-07 09:52 UTC, iamrajiv requested changes

2020-08-07 09:52 UTC, iamrajiv commented on .github/issue_labeler.yml
> +  - "(bug)"
@atarax665 you may add `error` too.

2020-08-07 09:58 UTC, atarax665 commented on .github/issue_labeler.yml
> +  - "(bug)"
@iamrajiv Done

2020-08-07 09:59 UTC, iamrajiv approved these changes

2020-08-08 16:42 UTC, merged

2020-08-08 18:36 UTC, ricardoprins commented
This is so cool!