Add quadratic equation roots
HarshCasper/NeoAlgo pull request #3423
Opened 2021-03-16 16:22 UTC by nagasaisriya

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
YES
(Write your answer here.)

### Description
Quadratic equations are actually used in everyday life, as when calculating areas, determining a product's profit or formulating the speed of an object.
Solving Quadratic equations in Java-A program that prints all real solutions to quadratic equation ax^2+bx+c=0, if discriminant is negative displays a message "roots are imaginary".
(Write your answer here.)

### Checklist

- [ X ] I've read the contribution guidelines.
- [ X ] I've checked the issue list before deciding what to submit.
- [ X ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2628 
(Write your answer here.)

2021-03-17 04:15 UTC, HarshCasper requested changes
Few changes: 
- Add a new line at the EOF
- Use meaningful variable names
- Move your Code logic to separate function and use `main()` for the driver code

2021-03-17 08:33 UTC, nagasaisriya commented
Yeah, would look into it. 
Thank you

2021-03-17 08:55 UTC, nagasaisriya commented
I have updated the File according to requested changes, @HarshCasper do review it

2021-03-18 11:13 UTC, ankitaggarwal23 reviewed
- Add Time and Space Complexity at the end of the Code   
- Use proper code Format 
- Remove extra lines of code and spaces

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +
Remove that extra space

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +    // linear
remove that and shift to upper comment

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +    // calculate the discriminant (b^2 - 4ac)
Remove redundant comments

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +      System.out.format("root1 = %.2f and root2 = %.2f", root1, root2);
Give one tab space inside the body of statement

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +      // discriminant is equal to 0
Remove redundant comments as you already mentioned this line above

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +      System.out.format("\nroot2 = %.2f-%.2fi", real, imaginary);
Give one tab space inside the body of statement

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +
Remove extra line

2021-03-18 11:13 UTC, ankitaggarwal23 commented on Java/math/Quadratic_Equation.java
> +}
Give one tab space inside the body of statement and remove extra line

2021-03-19 18:59 UTC, nagasaisriya commented
Hello, @ankitaggarwal23 @HarshCasper , made a commit and the updated file with requested changes, do review it. Thank you!

2021-03-20 11:52 UTC, HarshCasper commented
> Hello, @ankitaggarwal23 @HarshCasper , made a commit and the updated file with requested changes, do review it. Thank you!

Not all of the comments have been addressed

2021-03-20 15:12 UTC, nagasaisriya commented
> > Hello, @ankitaggarwal23 @HarshCasper , made a commit and the updated file with requested changes, do review it. Thank you!
> 
> Not all of the comments have been addressed

Please can yo be more specific, like which comment is being missed and any other changes to be made?

2021-03-24 15:25 UTC, HarshCasper approved these changes

2021-03-24 15:25 UTC, merged