Added Double Ended Queue in C
HarshCasper/NeoAlgo pull request #3438
Opened 2021-03-16 18:49 UTC by aish2002

Fixes #3376 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented double ended queue in C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3376

2021-03-16 18:51 UTC, aish2002 commented
@HarshCasper kindly review the PR

2021-03-17 00:50 UTC, iamrajiv requested changes
@aish2002

- Add time complexity as follows:
- The time complexity of all insertion or deletion in the middle is O(n).
- The time complexity of random access by index is O(1).
- The time complexity of all insertion and deletion operations are O(1).

2021-03-17 05:01 UTC, aish2002 commented
I have added time complexity as advised . @iamrajiv  kindly re-review the PR

2021-03-17 05:01 UTC, iamrajiv approved these changes

2021-03-18 11:07 UTC, ankitaggarwal23 approved these changes

2021-03-18 11:08 UTC, merged