Reverse Linked List
HarshCasper/NeoAlgo pull request #344
Opened 2020-08-07 13:39 UTC by Abhijit2505

### Description

Submission description here

Checklist:

- [x] I've checked the issue list before deciding what to submit.
- [x] I've read the contribution guidelines.
- [ ] I've edited the `README.md` link to my code.

2020-08-07 13:40 UTC, Abhijit2505 commented
I have not edited any README.md file, please explain on that thing, I did not get it.

2020-08-07 13:56 UTC, atarax665 reviewed
Rename the file as Reverse_linked_list.cpp and Reverse_linked_list.py

2020-08-07 14:01 UTC, Abhijit2505 commented
> Rename the file as Reverse_linked_list.cpp and Reverse_linked_list.py

Made the changes ✔

2020-08-07 14:02 UTC, atarax665 requested changes

2020-08-07 14:02 UTC, atarax665 commented on C++/Linked List/ReverseLL.cpp
> +/// Creating a class for Linked List object
Remove this whole comment.

2020-08-07 14:02 UTC, atarax665 commented on C++/Linked List/ReverseLL.cpp
> +
Remove this extra line

2020-08-07 14:02 UTC, atarax665 commented on C++/Linked List/ReverseLL.cpp
> +
Remove this blank line too.

2020-08-07 14:02 UTC, atarax665 commented on Python/Linked List/ReverseLL.py
> +            count+=1
Add space before and after the operator.

2020-08-07 14:09 UTC, atarax665 commented
@Abhijit2505 There is no need of creating a new folder with the name 'LinkedList'. You have to commit your code in the [ds folder](https://github.com/TesseractCoding/NeoAlgo/tree/master/C%2B%2B/ds)

2020-08-07 14:12 UTC, atarax665 commented
> I have not edited any README.md file, please explain on that thing, I did not get it.

You have to edit this [README.md](https://github.com/TesseractCoding/NeoAlgo/blob/master/C%2B%2B/README.md) to link your program under the Data structure list. You have to do the same for the python file in the python folder.

2020-08-07 14:15 UTC, atarax665 commented on C++/Linked List/Reverse_linked_list.cpp
> +/*
Remove this whole comment, from line 8 to 17.

2020-08-07 14:26 UTC, Abhijit2505 commented
Three things,
* The space after count+= and the blank line you pointed out gets ignored by the compiler in C++ and Python when the compiled file is generated. There is no meaning of removing a blank line or adding some space. 

* ds folder is good, but there are around 40/50 Linked List algorithms which will be messy inside the ds folder. Hence I have created another folder named Linked List to make the repository modularized. Well as the number of program increases, you will understand the thing.

* Comments should be there inside every code to make it easier for some users. The comments which you have asked me to remover were not wrong neither had any faults, still as per your review I have removed them.

I was here just to know about the repository structure and mechanism because I am going to mentor the participants in the upcoming Contributor's Hack by HakinCodes.

Thank You.

2020-08-07 18:56 UTC, atarax665 commented
> Three things,
> 
> * The space after count+= and the blank line you pointed out gets ignored by the compiler in C++ and Python when the compiled file is generated. There is no meaning of removing a blank line or adding some space.
> * ds folder is good, but there are around 40/50 Linked List algorithms which will be messy inside the ds folder. Hence I have created another folder named Linked List to make the repository modularized. Well as the number of program increases, you will understand the thing.
> * Comments should be there inside every code to make it easier for some users. The comments which you have asked me to remover were not wrong neither had any faults, still as per your review I have removed them.
> 
> I was here just to know about the repository structure and mechanism because I am going to mentor the participants in the upcoming Contributor's Hack by HakinCodes.
> 
> Thank You.

All the points mentioned by you are quite legit but I have my own reasons for suggesting those changes.

Reasons:
* Yes, the space and blank lines gets ignored by the compiler in C++ and Python when compiled file is generated, but proper use of spaces and blank lines enhance the readability of the code. [Refer to point 5 and 7 of this document](http://users.csc.calpoly.edu/~cstaley/General/CStyle.htm). Your code is well structured and that's commendable.

* We will be restructuring all the folders soon. For now we are merging all the commits to their respective domain folder. Making a new folder was justified from your end.

* I never said that the comment I asked you to remove was wrong or had any fault. I just felt that it was superfluous.

We are really excited about Contributor's Hack. Will love to work with you . Your codes are really well structured and are example for our other contributors. I hope I cleared my points.

Thank You

2020-08-07 18:57 UTC, atarax665 commented
@Abhijit2505 Can you please squash your commits so that I can merge this PR.

2020-08-07 19:28 UTC, atarax665 approved these changes

2020-08-08 01:49 UTC, Abhijit2505 commented
> @Abhijit2505 Can you please squash your commits so that I can merge this PR.

I think the Squash And Merge option is available for the people having write access to the repository. Hence please squash and merge it.

2020-08-08 01:52 UTC, merged

2020-08-08 01:53 UTC, atarax665 commented
@Abhijit2505 Okay, done.

2020-08-23 17:19 UTC, iamrajiv commented
@all-contributors please add @Abhijit2505 for code