Added C program to find inorder predecessor and successor in a BST
HarshCasper/NeoAlgo pull request #3452
Opened 2021-03-17 04:21 UTC by Tanya170620

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

It is a menu driven program which helps to find the inorder predecessor and successor in a BST.
The user first create their desired BST and then can find the inorder predecessor and successor of a node.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

To find inorder successor and predecessor in BST #3388

2021-03-18 11:02 UTC, ankitaggarwal23 requested changes

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +#include<stdio.h>
Add a new line after description

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +//structure of tree
Remove the redundant comments

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +//Insert function of BST
Add a new line above the comments

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +//Inorder display function using recursion
Add a new line above the comments

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +//Function to find inorder predecessor of a node
Add a new line above the comments

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +    printf("Predecessor of %d does not exist\n",node);
Give proper one tab space inside the body of the condition.

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +//Function to find inorder successor of a node
Add a new line above the comments

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +        x=x->rptr;
Give proper one tab space inside the body of the condition.

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +        return 0;
Give proper one tab space inside the body of the condition.

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +}
Give proper one tab space inside the body of the condition.

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +                printf("Tree is empty\n");
Give proper one tab space inside the body of the condition.

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +                printf("Tree is empty\n");
Give proper one tab space inside the body of the condition.

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +                printf("Tree is empty\n");
Give proper one tab space inside the body of the condition.

2021-03-18 11:02 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +*/
- Remove the extra test case 3  5  9  14 (Use only four values as sample input)
- Add Time and Space Complexity at the end of the Code

2021-03-19 07:59 UTC, ankitaggarwal23 requested changes

2021-03-19 07:59 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +        x=x->rptr;
Give proper one tab space inside the body of the condition.

2021-03-19 07:59 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +        x=x->lptr;
Give proper one tab space inside the body of the condition.

2021-03-19 07:59 UTC, ankitaggarwal23 commented on C/ds/inorder_predecessor_successor.c
> +Space Complexity: O(n)
Shift this after I/P and O/P. What is O(h) I guess it is O(n) kindly change.

2021-03-20 04:15 UTC, Tanya170620 commented
@ankitaggarwal23  I'm sorry as I did not know that if I have an existing PR which was not closed yet and if I make another PR for another issue then it will be reflected in all my PRs. 
Should I close all the PRs and make a fresh PR for this one or what do you suggest?

2021-03-22 05:45 UTC, Tanya170620 commented
Should I make a new PR for this issue or is it fine right now?
@ankitaggarwal23 @gat786 @bhav09

2021-03-22 17:10 UTC, HarshCasper requested changes
Use a formatter to format the code. Rest looks good!

2021-03-22 17:50 UTC, HarshCasper approved these changes

2021-03-22 17:50 UTC, merged