Reverse individual words of a string using stacks in C (issue #2585)
HarshCasper/NeoAlgo pull request #3460
Opened 2021-03-17 05:58 UTC by taruni-always

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes
### Description

Implementation of reversing individual words of a string using stacks in C language.
(Issue #2585)
I wanted to contribute under GSSoC '21.
### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
(issue #2585)

In reference with : #2900

2021-03-18 10:48 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-03-30 05:02 UTC, ankitaggarwal23 approved these changes

2021-03-30 05:08 UTC, ankitaggarwal23 requested changes

2021-03-30 05:08 UTC, ankitaggarwal23 commented on C/ds/reverseWordsOfString.c
> +Sample Output2: yppah yadhtrib
Code produces output like that change it and remove the extra test case one is enough

2021-03-30 05:08 UTC, ankitaggarwal23 commented on C/ds/reverseWordsOfString.c
> +Sample Output2: yppah yadhtrib
Code produces output like that change it and remove the extra test case one is enough

2021-03-30 05:11 UTC, ankitaggarwal23 requested changes

2021-03-30 05:11 UTC, ankitaggarwal23 commented on C/ds/reverseWordsOfString.c
> +*/
Code produces output like that change it and remove the extra test case one is enough.

![Capture](https://user-images.githubusercontent.com/67387053/112936927-56808900-9144-11eb-80cc-ac9615e7d20c.JPG)

2021-03-30 05:19 UTC, taruni-always commented
Apart from removing the extra test case, what change am I supposed to make @ankitaggarwal23 ?

2021-03-30 05:31 UTC, ankitaggarwal23 reviewed
Kindly change the output I added the snapshot.

2021-03-30 07:18 UTC, taruni-always commented
![image](https://user-images.githubusercontent.com/67354057/112948770-162a0680-9156-11eb-9052-2dcc86e2bff4.png)
Is this how you want the output to be?  (I mean without any prompts)?

2021-03-30 07:49 UTC, ankitaggarwal23 commented
> ![image](https://user-images.githubusercontent.com/67354057/112948770-162a0680-9156-11eb-9052-2dcc86e2bff4.png)
> Is this how you want the output to be? (I mean without any prompts)?

I added the screenshot. Your code producing like that

2021-03-31 10:08 UTC, ankitaggarwal23 commented
@taruni-always You have to write the output the way your code is producing See, How your code is producing Output with proper display message and how you wrote previously Kindly rewrite it

2021-03-31 10:35 UTC, taruni-always commented
@ankitaggarwal23 got it! Thanks will do that. :-)

2021-03-31 11:19 UTC, ankitaggarwal23 approved these changes

2021-03-31 11:19 UTC, merged