Added code for prims algorithm to find MST using Priority Queue
HarshCasper/NeoAlgo pull request #3486
Opened 2021-03-17 08:46 UTC by shubhii0206

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-17 15:41 UTC, shubhii0206 commented
close #3524

2021-03-18 10:26 UTC, ankitaggarwal23 requested changes
Few changes: 

- Use proper code Format 
- Remove extra lines of code and spaces

2021-03-18 10:26 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Prims_Algo_PriorityQueue.cpp
> +
- Remove these lines
- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-03-18 10:26 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Prims_Algo_PriorityQueue.cpp
> +*/
Shift this to the end

2021-03-18 14:59 UTC, shubhii0206 commented
I have made necessary changes.Kindly review.

2021-03-30 01:00 UTC, atarax665 requested changes
Update the corresponding README.

2021-03-30 01:00 UTC, atarax665 commented on C-Plus-Plus/graphs/Prims_Algo_PriorityQueue.cpp
> +/*Prims Algorithm to find Minimum Spanning of a Graph using Priority Queue.
Justify align this paragraph.

2021-03-30 01:00 UTC, atarax665 commented on C-Plus-Plus/graphs/Prims_Algo_PriorityQueue.cpp
> +Test case2 :
One test case is enough.

2021-03-30 01:00 UTC, atarax665 commented on C-Plus-Plus/graphs/Prims_Algo_PriorityQueue.cpp
> +    adjList[u].push_back(make_pair(v, wt)); //edges between u & v vertices
Shift comment above the line of code.

2021-03-30 01:00 UTC, atarax665 commented on C-Plus-Plus/graphs/Prims_Algo_PriorityQueue.cpp
> +
Add a new line at EOF.

2021-03-30 03:29 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/prims-algorithm-using-priority_queue-stl/).

2021-03-30 03:29 UTC, closed without merging