Printing Tribonacci series upt to "n" number of terms
HarshCasper/NeoAlgo pull request #3487
Opened 2021-03-17 09:20 UTC by AkanshaUniyal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Prints the Tribonacci series till n terms.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixes #3028

2021-03-18 10:19 UTC, ankitaggarwal23 requested changes

2021-03-18 10:19 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> + package mypack;
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-03-18 10:19 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +	  overrided by the sum. This process will continue till n terms.*/
Shit your approach after description

2021-03-18 10:19 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +        long num;int first=0,second=0,third=1,sum=0,count=0;
Shift `int first=0,second=0,third=1,sum=0,count=0;` to new line

2021-03-18 10:19 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +         num--;
- Align your code properly
- Use proper code Format

2021-03-19 06:04 UTC, AkanshaUniyal commented
@ankitaggarwal23 sir, changes have been made.

2021-03-19 07:17 UTC, ankitaggarwal23 requested changes

2021-03-19 07:17 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +   overrided by the sum. This process will continue till n terms.  */
Make it short and concise.

2021-03-19 07:17 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +        num=scan.nextLong();
Align your code properly

2021-03-19 07:17 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +            System.out.print(0);
Add one tab space

2021-03-19 07:17 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +            System.out.print(", "+0);
Add one tab space

2021-03-19 07:17 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +            System.out.print(", "+1);
Add one tab space

2021-03-19 07:17 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +            first=second;second=third;third=sum;  //Storing the values of succeeding terms in respective variables.
Add one tab space and in last line ` first=second;second=third;third=sum;` give new line after semicolon

2021-03-19 07:17 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +
Remove extra test case one is enough

2021-03-19 07:48 UTC, AkanshaUniyal commented
@ankitaggarwal23 sir, changes have been made.

2021-03-27 17:09 UTC, ankitaggarwal23 requested changes
Rest looks good to merge.

2021-03-27 17:09 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> + package mypack;
Remove the package mypack;

2021-03-27 17:09 UTC, ankitaggarwal23 commented on Java/math/tribonacci.java
> +        }
Align your code properly

2021-03-27 17:53 UTC, ankitaggarwal23 approved these changes

2021-03-27 17:57 UTC, ankitaggarwal23 commented
@AkanshaUniyal You have committed your code from master branch. Kindly don't commit from master branch that's why showing conflicts. Kindly open a new PR and commit from new branch not from main or master branch. Closing this PR as of now.

2021-03-27 17:57 UTC, closed without merging