Added Double ended queue in C-Plus-Plus
HarshCasper/NeoAlgo pull request #3494
Opened 2021-03-17 09:58 UTC by aish2002

Fixes #3376 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Double ended queue in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3376

2021-03-18 11:43 UTC, ankitaggarwal23 requested changes

2021-03-18 11:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/Double_Ended_Queue.cpp
> +    5
Reduce the no. of sample test case and make it understandable how you are reading I/P as it is a menu driven program.

2021-03-18 11:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/Double_Ended_Queue.cpp
> +*/
- Add new line at the EOF

2021-03-19 11:52 UTC, aish2002 commented
@ankitaggarwal23 I have made  necessary changes . Kindly re-review the PR

2021-03-25 04:19 UTC, HarshCasper approved these changes

2021-03-25 04:20 UTC, merged