Added Linear Search Issue#3435
HarshCasper/NeoAlgo pull request #3501
Opened 2021-03-17 10:54 UTC by nagasrihith608

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes
### Description
Added Linear search algo in kotlin.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes #3435 
(Write your answer here.)

2021-03-18 09:44 UTC, ankitaggarwal23 requested changes
- Add Time and Space Complexity at the end of the Code

2021-03-18 09:44 UTC, ankitaggarwal23 commented on Kotlin/search/LinearSearch.kt
> +//This is a program that allows us to do linear search in kotlin
Add few more description

2021-03-18 09:44 UTC, ankitaggarwal23 commented on Kotlin/search/LinearSearch.kt
> +   //Here we take the size of the input array/List
Remove the redundant comments

2021-03-18 09:44 UTC, ankitaggarwal23 commented on Kotlin/search/LinearSearch.kt
> +   //Taking the elements and storing them in array
Remove the redundant comments

2021-03-18 09:44 UTC, ankitaggarwal23 commented on Kotlin/search/LinearSearch.kt
> +   //The number we want to search for
Remove the redundant comments

2021-03-18 09:44 UTC, ankitaggarwal23 commented on Kotlin/search/LinearSearch.kt
> +
Remove the space

2021-03-18 10:55 UTC, nagasrihith608 commented
hey, @ankitaggarwal23 I had updated the requested changes please have a look at them.

2021-03-19 18:14 UTC, nagasrihith608 commented
@HarshCasper please merge this. Thank you.

2021-03-20 10:49 UTC, HarshCasper requested changes

2021-03-20 10:49 UTC, HarshCasper commented on Kotlin/search/LinearSearch.kt
> +fun main(){
Don't put the main logic in the main() function

2021-03-20 10:49 UTC, HarshCasper commented on Kotlin/search/LinearSearch.kt
> +
Remove any extra new lines

2021-03-20 10:49 UTC, HarshCasper commented on Kotlin/search/LinearSearch.kt
> +  The number given is not there in the given List
Use only one sample I/O.

2021-03-20 10:49 UTC, HarshCasper commented on Kotlin/search/LinearSearch.kt
> +
Make it more readable

2021-03-20 13:53 UTC, closed without merging