Added Rail Fence Cipher Algorithm Issue#2668
HarshCasper/NeoAlgo pull request #3502
Opened 2021-03-17 11:04 UTC by nagasrihith608

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description
This algorithm allows us to cipher the plain text using rail fence cipher algorithm
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes #2668
(Write your answer here.)

2021-03-18 09:49 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code

2021-03-18 11:20 UTC, nagasrihith608 commented
Hello, @ankitaggarwal23 I had updated the changes requested, please have a look at it now. Thank you!

2021-03-19 18:14 UTC, nagasrihith608 commented
@HarshCasper please merge this. Thank you.

2021-03-20 10:47 UTC, HarshCasper commented on C/cryptography/railFenceCipher.c
> +/* The rail fence cipher (also called a zigzag cipher) is a form of transposition cipher. It derives its name from the way in which it is encoded. Given a plain-text message and a numeric key, it cip
Break this line down into multiple separate lines. That makes it easy for us to read and understand.

2021-03-20 10:47 UTC, HarshCasper commented on C/cryptography/railFenceCipher.c
> +int main( void ) {
Don't keep the primary logic of your code in the main() function. Use main() only for the driver code

2021-03-20 10:47 UTC, HarshCasper commented on C/cryptography/railFenceCipher.c
> +
Remove any extra lines

2021-03-20 13:52 UTC, closed without merging