Add Matrix Chain Multiplication in Java to NeoAlgo
HarshCasper/NeoAlgo pull request #3512
Opened 2021-03-17 12:18 UTC by leoshrey

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the contribution guidelines.
### Description

This adds Matrix Chain Multiplication implementation in Java by following Dynamic Programming approach which leads to the optimal solution. 
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #3405

2021-03-18 05:42 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code

2021-03-18 07:25 UTC, leoshrey commented
@ankitaggarwal23, changes are made successfully.

2021-03-18 08:28 UTC, bhav09 requested changes
Reviewed.

2021-03-18 08:28 UTC, bhav09 commented on Java/dp/MatrixChainMultiplication.java
> +*/
Add a new line at EOF

2021-03-18 09:06 UTC, leoshrey commented on Java/dp/MatrixChainMultiplication.java
> +*/
sure

2021-03-18 09:28 UTC, leoshrey commented
Actually, I have already left a new line at EOF, it cannot be seen on this commit page, as it only shows the lines with changes made. But it can be seen in the code.

2021-03-20 11:06 UTC, HarshCasper requested changes

2021-03-20 11:06 UTC, HarshCasper commented on Java/dp/MatrixChainMultiplication.java
> +		// in case of int[] dimension = { 10, 30, 5, 60 };
Use multi-line comments

2021-03-20 11:06 UTC, HarshCasper commented on Java/dp/MatrixChainMultiplication.java
> +         */
Use multi-line comments

2021-03-20 11:06 UTC, HarshCasper commented on Java/dp/MatrixChainMultiplication.java
> +		// needed to compute matrix `M[i+1] … M[j] = M[i…j]`
Use multi-line comments

2021-03-22 11:28 UTC, leoshrey commented
@HarshCasper, Changes are made successfully

2021-03-22 17:11 UTC, HarshCasper approved these changes

2021-03-22 17:12 UTC, merged

2021-04-26 10:23 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.techiedelight.com/matrix-chain-multiplication/#:~:text=Matrix%20chain%20multiplication%20(or%20Matrix,of%20the%20matrix%20multiplications%20involved.)