Added Find duplicate elements from an array
HarshCasper/NeoAlgo pull request #3518
Opened 2021-03-17 13:40 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES.

### Description

Given an array of N elements , find all duplicate elements from it. In Competitive Programming, some times we need to do this to solve our problem.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixed Issue #3517

2021-03-17 17:29 UTC, atarax665 requested changes

2021-03-17 17:29 UTC, atarax665 commented on C-Plus-Plus/other/find_duplicate_elements_from_an_array.cpp
> +int ar[100009];
You can declare the array locally after taking input N from the user.

2021-03-17 17:29 UTC, atarax665 commented on C-Plus-Plus/other/find_duplicate_elements_from_an_array.cpp
> +    cin >> N;
Add proper statements to prompt user to input data.

2021-03-17 18:24 UTC, RaiyanMahin commented
@atarax665  L made all the changes. Kindly Review.

2021-03-18 13:38 UTC, RaiyanMahin commented
@iamrajiv @ankitaggarwal23 kindly review

2021-03-18 16:57 UTC, RaiyanMahin commented
@bhav09 @atarax665 kindly review

2021-03-18 17:12 UTC, atarax665 approved these changes
LGTM

2021-03-18 17:27 UTC, RaiyanMahin commented
@atarax665  Thanks. Any other's review is required?
Or you can merge it? 😁

2021-03-18 18:06 UTC, iamrajiv approved these changes

2021-03-19 08:05 UTC, ankitaggarwal23 approved these changes

2021-03-19 08:07 UTC, merged