Source Code for Tiling 2 x N in C++
HarshCasper/NeoAlgo pull request #3531
Opened 2021-03-17 15:16 UTC by weirdrag08

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Adding Source Code for Tiling 2 x N in C++ using dynamic programming

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2320

2021-03-18 12:14 UTC, weirdrag08 commented
Kindly review my PR.

2021-03-20 10:58 UTC, HarshCasper requested changes

2021-03-20 10:58 UTC, HarshCasper commented on C-Plus-Plus/dp/Tiling_2xN.cpp
> +*/
Add a new line at the EOF

2021-03-20 10:58 UTC, HarshCasper commented on C-Plus-Plus/dp/Tiling_2xN.cpp
> +    cin >> n;
Use proper console statements to take the user input

2021-03-24 03:44 UTC, weirdrag08 commented
@HarshCasper Kindly review the changes .

2021-03-24 15:09 UTC, HarshCasper requested changes

2021-03-24 15:09 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Tiling 2 x N](dp/Tiling_2xN.cpp)
Can you use a better title and filename for your code?

2021-03-24 15:09 UTC, HarshCasper commented on C-Plus-Plus/dp/Tiling_2xN.cpp
> +    at last return, dp[n] for number of ways. */
Don't put your algorithm here. Instead document them in my code

2021-03-25 15:09 UTC, HarshCasper approved these changes

2021-03-25 15:21 UTC, merged

2021-03-25 17:08 UTC, HarshCasper commented
@all-contributors bot please add @weirdrag08 for code