Added the code for matrix transpose in C++
HarshCasper/NeoAlgo pull request #3543
Opened 2021-03-17 17:43 UTC by MayureeS

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
The code takes input as a matrix and outputs the transpose of given matrix. This code is added to NeoAlgo/C-Plus-Plus/cp

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue related to this PR : #3421

2021-03-18 04:33 UTC, HarshCasper requested changes
Make README changes as well

2021-03-18 06:13 UTC, MayureeS commented
@HarshCasper  Thank you for reviewing my PR. I have updated the README file. Please check if it is correct.

2021-03-18 08:14 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Shift the logic to another function and use main for driver code
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code

2021-03-18 16:23 UTC, MayureeS commented
@HarshCasper @ankitaggarwal23  I have made the changes. But now it is showing 4 failing checks. What should I do now?

2021-03-19 09:01 UTC, ankitaggarwal23 requested changes

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Matrix Transpose](cp/matrix_transpose.cpp)
Remove this file from cp section and add this code file to math section

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix_transpose.cpp
> +using namespace std;
Add a new line after using namespace std;

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix_transpose.cpp
> +void transpose(int frows, int fcolumns, int **finput_matrix, int **ftranspose_matrix)	//Function that computes transpose
shift the comment above the function defination

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix_transpose.cpp
> +}
Align your code properly give one tab space while writing code inside the body of the statement or condition

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix_transpose.cpp
> +    int j = 0;
Change it to like this, it will save your lines

![1](https://user-images.githubusercontent.com/67387053/111755503-2e309900-88bf-11eb-8911-90edc315ceed.JPG)

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix_transpose.cpp
> +}
Align your code properly give one tab space while writing code inside the body of the statement or condition.

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix_transpose.cpp
> + *
Kindly cross check Is it Theta or O(mn)

2021-03-19 09:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix_transpose.cpp
> + */
Add a new line at the end of file

2021-03-19 12:17 UTC, MayureeS commented
@ankitaggarwal23 I have made the said changes. I hope it is correct now. Really sorry for the inconvenience caused by my silly mistakes.

2021-03-20 12:06 UTC, HarshCasper approved these changes

2021-03-20 12:08 UTC, merged