Added code for Open hashing in c
HarshCasper/NeoAlgo pull request #3554
Opened 2021-03-17 19:43 UTC by cintamg

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3548

2021-03-17 19:53 UTC, cintamg commented
@ankitaggarwal23 
Why does it show merge conflict?

2021-03-18 04:31 UTC, HarshCasper requested changes
Few changes: 
- Add a new line at the EOF
- Add function descriptions
- Resolve the merge conflicts
- Format the Code properly

2021-03-20 07:35 UTC, cintamg commented
Hey, @HarshCasper @ankitaggarwal23 @anushkrishnav @siddharth25pandey , please do review my pr
Thank you.

2021-03-20 11:53 UTC, HarshCasper requested changes

2021-03-20 11:53 UTC, HarshCasper commented on C/ds/README.md
> +- [Open Hashing](ds/Open_hashing.c)
Don't make the changes here. Make it on `C/README.md`

2021-03-20 14:40 UTC, cintamg commented
@HarshCasper I have made the changes. Please do review my pr.

2021-03-22 18:17 UTC, cintamg commented
Hey, @HarshCasper @ankitaggarwal23 @anushkrishnav @siddharth25pandey , please do review my pr
Thank you.

2021-03-26 06:42 UTC, cintamg commented
@HarshCasper I request you to review PR
Thank You

2021-03-26 17:21 UTC, HarshCasper approved these changes

2021-03-26 17:21 UTC, merged