Add code for Interval List Intersection
HarshCasper/NeoAlgo pull request #3584
Opened 2021-03-18 06:00 UTC by ANUJAGRAWAL2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description
I have add the code , description and I/O sample for the Interval List Intersection
(Write your answer here.)

### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2751 is the issue related which this PR.
(Write your answer here.)

2021-03-18 08:47 UTC, ankitaggarwal23 requested changes
Few changes: 

- Use proper code Format 
- Align your code properly
- Use proper naming conventions to define variables
- Add Time and Space Complexity at the end of the Code

2021-03-18 18:48 UTC, ANUJAGRAWAL2000 commented
I have updated the Interval List Intersection as align properly, format code, add Time complexity and space complexity, used proper naming conventions.

2021-03-26 05:05 UTC, ANUJAGRAWAL2000 commented
@tarunyadav148 Please look to this PR and merged. Thank You

2021-03-26 09:33 UTC, HarshCasper requested changes

2021-03-26 09:33 UTC, HarshCasper commented on C-Plus-Plus/cp/Interval_list_Intersection.cpp
> +[2, 4] is [2, 3].
Can you make this more compact and break it down into smaller sentences?

2021-03-26 09:51 UTC, ANUJAGRAWAL2000 commented
I have make it more compact. Please look into it and merge.

2021-03-26 09:56 UTC, HarshCasper approved these changes

2021-03-26 09:57 UTC, merged