Polynomial Sum & Product using Linked Lists
HarshCasper/NeoAlgo pull request #3589
Opened 2021-03-18 06:54 UTC by Suvraneel

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yep!

### Description

A dynamic implementation of Polynomial Sum & Product using Linked Lists.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

resolves #3560

2021-03-18 07:03 UTC, Suvraneel commented
Hello maintainers!  
Kindly review this...
@HarshCasper @bhav09 
@siddharth25pandey

2021-03-18 08:30 UTC, bhav09 commented on Java/math/polynomial.java
> +*/
Its perfect, just add a new line at EOF.

2021-03-18 09:14 UTC, Suvraneel commented on Java/math/polynomial.java
> +*/
Done,
- Thanks :)

2021-03-18 16:37 UTC, Suvraneel commented
@bhav09  @HarshCasper  @anushkrishnav 
Resolved = "\n at EOF"
Please kindly review

2021-03-19 04:21 UTC, siddharth25pandey requested changes
@Suvraneel Minor change is required

2021-03-19 04:21 UTC, siddharth25pandey commented on Java/README.md
> +- [Factorial Using BigInteger](math/FactorialUsingBigInteger.java)
Remove this line

2021-03-19 14:26 UTC, Suvraneel commented
@siddharth25pandey @HarshCasper @bhav09 
Resolved :)

2021-03-19 18:07 UTC, siddharth25pandey approved these changes
@Suvraneel LGTM, able to merge

2021-03-19 18:07 UTC, merged

2021-03-19 18:08 UTC, siddharth25pandey commented
@all-contributors please add @Suvraneel for his code