Maximum Function
HarshCasper/NeoAlgo pull request #3592
Opened 2021-03-18 07:26 UTC by Amanduttbhagat

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

  Maximum Function (in Java) :
 
   A sequence is given A1,A2,…,An (atleast 3 elements you need to give)
   Find the maximum value of the expression |Ax − Ay|+|Ay − Az|+|Az − Ax|
   over all triples of pairwise distinct valid indices (x,y,z).

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixed : #3519

2021-03-18 07:43 UTC, Amanduttbhagat commented
@ankitaggarwal23 @HarshCasper @siddharth25pandey @iamrajiv
Please review my PR

2021-03-19 04:24 UTC, siddharth25pandey requested changes
@Amanduttbhagat Do the suggested changes

2021-03-19 04:24 UTC, siddharth25pandey commented on Java/cp/Maximum_Function.java
> +
Display message, what are you taking input from the user

2021-03-19 04:24 UTC, siddharth25pandey commented on Java/cp/Maximum_Function.java
> +		//putting elements in the array
Display message, what are you taking input from the user

2021-03-19 04:24 UTC, siddharth25pandey commented on Java/cp/Maximum_Function.java
> +		//printing max
Display output message for better user-interface

2021-03-19 07:44 UTC, ankitaggarwal23 requested changes

2021-03-19 07:44 UTC, ankitaggarwal23 commented on Java/cp/Maximum_Function.java
> +import java.util.Arrays;
Add a new line after description

2021-03-19 07:44 UTC, ankitaggarwal23 commented on Java/cp/Maximum_Function.java
> +		long[] array = new long[(int)n];
Display a proper message How you are reading inputs .

2021-03-19 07:44 UTC, ankitaggarwal23 commented on Java/cp/Maximum_Function.java
> +      Output : Result = 16
Remove Extra test case one is enough

2021-03-19 07:44 UTC, ankitaggarwal23 commented on Java/cp/Maximum_Function.java
> + */
Add a new line at the end of file

2021-03-19 15:56 UTC, Amanduttbhagat commented
@ankitaggarwal23 I have made the requested changes
Can you please review it again

Thank you

2021-03-19 18:13 UTC, siddharth25pandey commented
@Amanduttbhagat Displaying message means you need to print the message not writing as in comment form

2021-03-20 06:08 UTC, Amanduttbhagat commented
@ankitaggarwal23 @siddharth25pandey
I have made the requested changes
Please review it again

Thank you

2021-03-20 11:59 UTC, HarshCasper approved these changes

2021-03-20 12:01 UTC, merged

2021-03-20 13:52 UTC, Amanduttbhagat commented
Thank you @HarshCasper @ankitaggarwal23 @siddharth25pandey

2021-03-25 03:21 UTC, siddharth25pandey commented
@all-contributors please add @Amanduttbhagat for his code