Uploaded the first code in Julia
HarshCasper/NeoAlgo pull request #3593
Opened 2021-03-18 07:30 UTC by Saviour1001

Added the Kadane's algorithm and also established a readme file for the folder

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added a new folder which currently comprises of a readme file and another folder of CP to hold the codes. Will be making more subfolders to add other algorithms such as backtracking and recursion.

### Checklist

- [ YES ] I've read the contribution guidelines.
- [ YES  ] I've checked the issue list before deciding what to submit.
- [ YES ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR closes issue #3587

2021-03-18 07:40 UTC, Saviour1001 commented
This PR closes issue #3587

2021-03-20 11:04 UTC, HarshCasper requested changes

2021-03-20 11:04 UTC, HarshCasper commented on Julia/cp/Maximum_subarray_sum.jl
> +end
Format the Code

2021-03-20 11:04 UTC, HarshCasper commented on Julia/cp/Maximum_subarray_sum.jl
> +
Remove the extra line of code

2021-03-20 12:38 UTC, HarshCasper approved these changes

2021-03-20 12:38 UTC, merged