written the code for bubble sort recursive function
HarshCasper/NeoAlgo pull request #3619
Opened 2021-03-18 13:22 UTC by devu26

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-19 13:37 UTC, iamrajiv requested changes
@devu26 Please provide the issue number.

2021-03-20 05:13 UTC, devu26 commented
issue number 3459

2021-03-20 12:48 UTC, iamrajiv requested changes
@devu26 Rename the program to this `recursive_bubble_sort.cpp`. Update the readme file.

2021-03-23 13:17 UTC, atarax665 requested changes
Format your code using [this](https://www.techiedelight.com/tools/clike).

2021-03-23 13:17 UTC, atarax665 commented on C-Plus-Plus/sort/recursive bubble sort.cpp
> +/*
Add space and time complexity of your approach.

2021-03-23 13:17 UTC, atarax665 commented on C-Plus-Plus/sort/recursive bubble sort.cpp
> +	cout<<"after sorting:"<<endl;
```suggestion
	cout<<"After sorting:"<<endl;
```

2021-03-23 13:17 UTC, atarax665 commented on C-Plus-Plus/sort/recursive bubble sort.cpp
> +	cout<<"enter the number of element:"<<endl;
```suggestion
	cout<<"Enter the number of element:"<<endl;
```

2021-03-23 13:17 UTC, atarax665 commented on C-Plus-Plus/sort/recursive bubble sort.cpp
> +	cout<<"enter the value of element:"<<endl;
```suggestion
	cout<<"Enter the value of element:"<<endl;
```

2021-03-30 17:07 UTC, atarax665 commented
@devu26 Are you still working on this?

2021-04-01 16:40 UTC, closed without merging