Aggressive cows added
HarshCasper/NeoAlgo pull request #3657
Opened 2021-03-19 08:25 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Aggressive cows code added in cp(competitive programming) folder added.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3215

2021-03-19 08:26 UTC, gayatri517 commented
@ankitaggarwal23 Kindly review my PR. 
Thank you.

2021-03-19 08:43 UTC, ankitaggarwal23 requested changes

2021-03-19 08:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Aggressive cows added](cp/aggressive_cows.cpp)
Remove the word "added"

2021-03-19 08:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +
Remove the extra line

2021-03-19 08:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	//User input : 3
Remove the redundant comments. We said use cout to display proper message like for example cout<<" Enter the value of n and Cows; etc. like that!

2021-03-19 08:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	//User input : 1 2 4 8 9
Remove the redundant comments. We said use cout to display proper message.

2021-03-19 08:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	int e = stalls[n - 1] - stalls[0];
Use proper naming convention. Don't use single letter.

2021-03-19 08:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +	//Output message : 3
Remove the redundant comments.

2021-03-19 08:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/aggressive_cows.cpp
> +*/
Add a new line at the end of file

2021-03-19 10:49 UTC, gayatri517 commented
@ankitaggarwal23 I have made the changes. Kindly review them. 
Thank you.

2021-03-21 03:23 UTC, gayatri517 commented
@ankitaggarwal23 kindly review my PR.

2021-03-23 07:40 UTC, gayatri517 commented
@ankitaggarwal23 Please review my PR.
Thank you.

2021-03-24 07:41 UTC, rohanbabbar04 reviewed
Add a new line at EOF
@gayatri517 Merge conflicts do resolve

2021-03-24 10:03 UTC, gayatri517 commented
@rohanbabbar04 I have added a new line at EOF. Please check it.

2021-03-24 10:54 UTC, gayatri517 commented
@rohanbabbar04 Kindly check it I have tried resolving the merge conflicts.

2021-03-24 15:51 UTC, gayatri517 commented
@HarshCasper please take look at my PR.
Thank you.

2021-03-25 04:10 UTC, HarshCasper approved these changes

2021-03-25 04:10 UTC, merged