Addition of Quick Select
HarshCasper/NeoAlgo pull request #3660
Opened 2021-03-19 09:28 UTC by abhay27chauhan

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This algorithm is used to find kth smallest element in an unsorted array. This is based on Quick Sort. 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
This PR is made under issue #3658

2021-03-19 17:37 UTC, HarshCasper requested changes
Make markdown changes as well

2021-03-19 17:37 UTC, HarshCasper commented on Java/sort/QuickSelect.java
> +        int[] arr = {8,5,1,3,7,2,9,6};
Don't use static input. Use dynamic input instead

2021-03-19 17:37 UTC, HarshCasper commented on Java/sort/QuickSelect.java
> +}
Add sample I/O and complexity at the end of the Code

2021-03-19 17:37 UTC, HarshCasper commented on Java/sort/QuickSelect.java
> +*/
Describe the problem here

2021-03-27 23:07 UTC, abhay27chauhan commented
@HarshCasper kindly review my PR

2021-04-04 11:20 UTC, ankitaggarwal23 reviewed
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-04 14:12 UTC, ankitaggarwal23 reviewed
Kindly do the changes

2021-04-09 06:37 UTC, ankitaggarwal23 reviewed
Are you still working on it.

2021-04-09 06:38 UTC, abhay27chauhan commented
No

On Fri, 9 Apr, 2021, 12:08 PM Ankit Aggarwal, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Are you still working on it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TesseractCoding/NeoAlgo/pull/3660#pullrequestreview-632085748>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKG5GE3CWLI2VASJ5TLRHQDTH2OFDANCNFSM4ZONEK5A>
> .
>

2021-04-09 12:53 UTC, closed without merging