Added string Concatenation
HarshCasper/NeoAlgo pull request #3663
Opened 2021-03-19 10:09 UTC by ansi22

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

Added string concatenation problem that solves issue #3362 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#3362 )

2021-03-19 10:32 UTC, rohanbabbar04 requested changes

2021-03-19 10:32 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +Sample Test Case :
Add the sample test case after the code

2021-03-19 10:32 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +    //n stores the no. of string
No need to explain each line just the important ones

2021-03-19 10:32 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +    //takes inut from the user
No need to explain each line

2021-03-19 10:32 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +	for(int i=0;i<n;i++)
Improper indentation

2021-03-19 10:32 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +    }
Use a C++ formatter  to format your code

2021-03-19 10:32 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +}
Add Time Complexity and Space Complexity 
Add a new line at EOF

2021-03-20 07:15 UTC, ansi22 commented
Hello mentors,
I have made the requested changes and updated the code.
Do check it and kindly let me know if more changes are required.
@HarshCasper @ankitaggarwal23 @bhav09

2021-03-20 09:47 UTC, rohanbabbar04 requested changes

2021-03-20 09:47 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +    f_str.append(a);
Improper Indentation

2021-03-20 09:56 UTC, rohanbabbar04 requested changes

2021-03-20 09:56 UTC, rohanbabbar04 commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +#include <string>
Instead of this use #include<bits/stdc++.h> which includes all the above libraries

2021-03-20 10:55 UTC, HarshCasper requested changes

2021-03-20 10:55 UTC, HarshCasper commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +int main() {
Don't push the main logic of the code in the main() function. Use main() only for the driver code

2021-03-20 14:39 UTC, rohanbabbar04 approved these changes

2021-03-20 14:59 UTC, HarshCasper requested changes

2021-03-20 14:59 UTC, HarshCasper commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +    //final output
Redundant comment

2021-03-20 14:59 UTC, HarshCasper commented on C-Plus-Plus/other/n_string_concatenate.cpp
> +
Remove this line of code

2021-03-21 14:26 UTC, HarshCasper approved these changes

2021-03-21 14:28 UTC, merged