added trapping rainwater in cpp #2873
HarshCasper/NeoAlgo pull request #3670
Opened 2021-03-19 14:19 UTC by Rishika30

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

i have used two pointer approach to solve the trapping rainwater problem in cpp. This is the optimised solution which takes O(n) time and O(1) space.  In two pointer approach, we take the starting index and the last index and start iterating comparing them.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2873

2021-03-19 17:31 UTC, HarshCasper requested changes
Format and Indent your Code properly

2021-03-19 17:31 UTC, HarshCasper commented on C-Plus-Plus/other/trappingRainwater.cpp
> +class Solution {
Use meaningful class names

2021-03-19 17:31 UTC, HarshCasper commented on C-Plus-Plus/other/trappingRainwater.cpp
> +*/
Add a new line at the EOF

2021-03-19 18:03 UTC, siddharth25pandey requested changes
@Rishika30 Do the suggested changes & Update the **Readme** file details

2021-03-19 18:03 UTC, siddharth25pandey commented on C-Plus-Plus/other/trappingRainwater.cpp
> +	int n, val;
Use suitable naming convention

2021-03-19 18:03 UTC, siddharth25pandey commented on C-Plus-Plus/other/trappingRainwater.cpp
> +	cin >> n;
Display a message what are you taking input from the user before this line

2021-03-19 18:03 UTC, siddharth25pandey commented on C-Plus-Plus/other/trappingRainwater.cpp
> +	cout << result;
Display message what are you giving output for better user-interface

2021-03-19 18:03 UTC, siddharth25pandey commented on C-Plus-Plus/other/trappingRainwater.cpp
> +Maximum water that can be accumulated is 5
You are not displaying any message, then how you are writing the same in Sample Output.

2021-03-20 12:05 UTC, HarshCasper requested changes
Make README changes as well

2021-03-20 14:51 UTC, siddharth25pandey commented
@Rishika30 Resolve the merge conflicts

2021-03-21 10:30 UTC, merged