first commit
HarshCasper/NeoAlgo pull request #3671
Opened 2021-03-19 14:29 UTC by yogitasaini

find small bug in bubblesort.java.
please review it.

2021-03-19 14:44 UTC, ritvij14 commented
@yogitasaini did you try running the code before making the changes? Was it actually not sorting correctly? Can you please show an example? Because I cannot see where exactly is the `sorted` variable being used.

Please give an example of what the bug was initially and how does your addition fix it.

2021-03-19 15:55 UTC, yogitasaini commented
It will not happen every time that our array runs n time. Suppose that if the array is sorted in first iterate then I put a check for those cases so it not need to iterate again in the loop

2021-03-19 16:16 UTC, ritvij14 requested changes

2021-03-19 16:16 UTC, ritvij14 commented on Java/sort/BubbleSort.java
@yogitasaini then in that case, shouldn't there be a check here in this line that checks for the value of `sorted`? If it's true, then there is no need to execute the loop anymore, so the loop should stop? I think you should add a check here.

2021-03-20 05:09 UTC, yogitasaini commented
Hey, @HarshCasper @ankitaggarwal23 @anushkrishnav @siddharth25pandey ,please do review my pr
Thank you.

2021-03-20 05:32 UTC, ritvij14 approved these changes

2021-03-20 06:30 UTC, HarshCasper approved these changes

2021-03-20 06:30 UTC, merged