Jump Search
HarshCasper/NeoAlgo pull request #3684
Opened 2021-03-19 19:33 UTC by TidbitsJS

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented the jump search algorithm in JavaScript

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Closes: #3649

2021-03-19 20:28 UTC, anushkrishnav requested changes

2021-03-19 20:28 UTC, anushkrishnav commented on JavaScript/search/JumpSearch.js
> +let array = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 111, 245, 250, 310];
Replace static input with dynamic

2021-03-19 20:28 UTC, anushkrishnav commented on JavaScript/search/JumpSearch.js
> +
add a sample Input and Output

2021-03-20 14:05 UTC, TidbitsJS commented
I have made the changes.
Let me know your thoughts @anushkrishnav :)

2021-03-22 17:17 UTC, HarshCasper approved these changes

2021-03-22 17:18 UTC, merged