reversal algorithm
HarshCasper/NeoAlgo pull request #3714
Opened 2021-03-20 08:23 UTC by Sapna2001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)
Reversal algorithm to rotate an array in java under the algorithms section.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#3640

2021-03-24 07:29 UTC, Sapna2001 commented
Replit link : https://replit.com/@Sapna2001/reversal

2021-03-24 15:30 UTC, HarshCasper requested changes

2021-03-24 15:30 UTC, HarshCasper commented on Java/Algorithms/reversalAlgorithm.java
> +public class ReversalAlgorithm {
Add a beginner friendly description

2021-03-24 15:30 UTC, HarshCasper commented on Java/Algorithms/reversalAlgorithm.java
> +		int[] array = {1,2,3,4,5,6,7};
Use dynamic input

2021-03-24 15:30 UTC, HarshCasper commented on Java/Algorithms/reversalAlgorithm.java
> +// 1 2 3 4 5 6 7 -> after right rotation of left rotated array
Put in multi-line comments

2021-03-24 15:30 UTC, HarshCasper commented on Java/Algorithms/reversalAlgorithm.java
> +// 1 2 3 4 5 6 7 -> after right rotation of left rotated array
Add a new line at the EOF

2021-03-25 09:29 UTC, Sapna2001 commented
@HarshCasper I have made the changes

2021-03-30 11:54 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/program-for-array-rotation-continued-reversal-algorithm/).

2021-03-30 11:54 UTC, closed without merging