union of two unsorted arrays  Issue:#3715
HarshCasper/NeoAlgo pull request #3728
Opened 2021-03-20 13:08 UTC by jaimehta1912

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes.)

### Description

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

2021-03-20 13:11 UTC, jaimehta1912 commented
@ananddasani please review

2021-03-20 13:47 UTC, ananddasani commented
@jaimehta1912 resolve this conflict

2021-03-20 13:49 UTC, ananddasani commented on C-Plus-Plus/cp/Tug_of_water.cpp
> +#include<iostream>
Question is :: union of two unsorted arrays Issue
and you have submitted the code of :: Tug_of_war ??

please check again everything :)

2021-03-20 13:50 UTC, ananddasani commented
check the source code file once

2021-03-20 14:43 UTC, rohanbabbar04 reviewed
Create different branches to solve different issues

2021-03-21 04:33 UTC, rohanbabbar04 commented
@jaimehta1912 do no merge from the main branch create a new branch to work on a new issue.
Create multiple branches to work on different issues

2021-03-28 03:54 UTC, HarshCasper requested changes
Don't push more than one code file in a single PR

2021-03-28 03:54 UTC, closed without merging