IMPLEMENTED DESCENDING PRIORITY QUEUE
HarshCasper/NeoAlgo pull request #3733
Opened 2021-03-20 13:41 UTC by ananddasani

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes !

### Description

I have updated the README file under ds section of C++ directory  and Added the source code file of Descending Priority Queue.

I would request @ankitaggarwal23 , @HarshCasper , @bhav09 to please review my PR :)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No

2021-03-21 14:15 UTC, HarshCasper requested changes

2021-03-21 14:15 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Descenidng Priority Queue] (ds/Descending_priority_queue.cpp)
Put it `[Descending Priority Queue](ds/Descending_priority_queue.cpp)`

2021-03-21 14:15 UTC, HarshCasper commented on C-Plus-Plus/ds/Descending_priority_queue.cpp
> +
Use comments above the line of the code

2021-03-21 14:17 UTC, ananddasani commented on C-Plus-Plus/ds/Descending_priority_queue.cpp
> +
okay

2021-03-22 11:46 UTC, HarshCasper approved these changes

2021-03-22 11:46 UTC, merged