added anagram algorithm in java
HarshCasper/NeoAlgo pull request #3758
Opened 2021-03-20 21:23 UTC by rajeshpanjiyar

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yeah I have.)

### Description

(This PR is to add an anagram algorithm in java of different approaches.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(This is to add an anagram algorithm in java under the issue#3709.)

2021-03-21 06:06 UTC, ritvij14 requested changes

2021-03-21 06:06 UTC, ritvij14 commented on Java/Algorithms/Anagram.java
> +		   boolean isAnagram =true;
The java code has too many indentations. Please format the code properly.

2021-03-21 06:06 UTC, ritvij14 commented on Java/Algorithms/Anagram.java
> +
Remove extra lines, there is only one line needed at EOF (End of File). Also, add comments to show input and output, and space and time complexity.

2021-03-21 06:08 UTC, rajeshpanjiyar commented
Yeah sure

On Sun, 21 Mar, 2021, 11:51 AM Ritvij Kumar Sharma, <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Java/Algorithms/Anagram.java
> <https://github.com/TesseractCoding/NeoAlgo/pull/3758#discussion_r598227245>
> :
>
> > +public class Anagram {
> +
> +	public static void main(String[] args) {
> +	
> +	  /// This code is for Anagram algorithm in Java
> +		
> +		
> +      Scanner scan = new Scanner(System.in);
> +		
> +	System.out.println("Enter a string");
> +	 String string1 = scan.nextLine();        //takes a input string
> +		
> +	    System.out.println("Enter another string");
> +	      String string2 =scan.nextLine();     //takes another input string
> +				scan.close();
> +		   boolean isAnagram =true;
>
> The java code has too many indentations. Please format the code properly.
> ------------------------------
>
> In Java/Algorithms/Anagram.java
> <https://github.com/TesseractCoding/NeoAlgo/pull/3758#discussion_r598227360>
> :
>
> > +			   break;
> +			          }
> +			       }
> +			
> +		      if(isAnagram) {
> +	     System.out.println("anagram");
> +	 }else {
> +	System.out.println("not anagram");
> +			   }
> +			
> +		
> +		}
> +	  }
> +
> +		
> +		
>
> Remove extra lines, there is only one line needed at EOF (End of File).
> Also, add comments to show input and output, and space and time complexity.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TesseractCoding/NeoAlgo/pull/3758#pullrequestreview-616986034>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS2W7K56FJV5UKDEXBUD33TTEWEH5ANCNFSM4ZQ2KWJQ>
> .
>

2021-03-28 03:58 UTC, HarshCasper commented
Closing the PR because of no updates.

2021-03-28 03:58 UTC, closed without merging

2021-03-28 04:14 UTC, rajeshpanjiyar commented
Hey @HarshCasper, I had regenerated pr for this. Can you please review this.
https://github.com/TesseractCoding/NeoAlgo/pull/4002