union of unsorted array
HarshCasper/NeoAlgo pull request #3772
Opened 2021-03-21 05:45 UTC by Sapna2001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)
Yes

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#3771

2021-03-24 07:31 UTC, Sapna2001 commented
Replit : https://replit.com/@Sapna2001/unionUnsorted

2021-03-28 04:02 UTC, HarshCasper requested changes
Use `main()` only for the driver code

2021-03-28 04:02 UTC, HarshCasper commented on Java/other/UnionUnsortedArray.java
> +	public static void main(String[] args) {
Don't put all the code logic in the `main()` function.

2021-03-28 13:00 UTC, Sapna2001 commented
@HarshCasper I have made changes in the main method

2021-04-05 13:39 UTC, HarshCasper approved these changes

2021-04-05 13:39 UTC, merged