Find all unique prime factor of any number n
HarshCasper/NeoAlgo pull request #3780
Opened 2021-03-21 07:07 UTC by Kirti1807

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
In this I try  to find all unique prime factors of any number n.
FIXES #3005

2021-03-21 07:14 UTC, Kirti1807 commented
@ankitaggarwal23 
Sir please review it.

2021-03-22 07:28 UTC, Kirti1807 commented
Please review it ,I am not able to understand why this tests were not passed.

2021-03-24 15:15 UTC, HarshCasper requested changes

2021-03-24 15:15 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +
Remove all these blank lines

2021-03-24 15:15 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +*/
Put a new line at the EOF

2021-03-24 15:15 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +int main(){
Shift all your code logic into another function and use main() for driver code.

2021-03-24 15:15 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +
Document it properly. And don't make silly typos (`algorethm`)

2021-03-24 15:15 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +  }
Mess of a code. Make it less complicated and format/indent it

2021-03-25 05:12 UTC, Kirti1807 commented
Sir, I try to make all required changes. Please review it again

2021-03-26 14:44 UTC, HarshCasper requested changes

2021-03-26 14:44 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +*/
Add a new line at the EOF

2021-03-26 14:44 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +
Put a proper description

2021-03-27 09:47 UTC, HarshCasper requested changes

2021-03-27 09:47 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +//In this first we store all prime factor of numbers till n and then print prime factors of n.
Put in a multi-line comment

2021-03-27 16:34 UTC, ankitaggarwal23 requested changes

2021-03-27 16:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +using namespace std;
Add a new line after using namespace std;

2021-03-27 16:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +}
Add a new line above the int main()

2021-03-27 16:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +   Test case_2 Output: 2  7  389
Remove the extra sample cases one is enough.
![Capture](https://user-images.githubusercontent.com/67387053/112727371-3b492a00-8f48-11eb-8ed3-0339ed6fd20f.JPG)

Kindly display a proper message using `cout` while reading and writing I/P and O/P

2021-03-28 05:25 UTC, ankitaggarwal23 requested changes

2021-03-28 05:25 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +*/
![Capture](https://user-images.githubusercontent.com/67387053/112743312-f65add00-8fb3-11eb-8b7b-be95aed92170.JPG)

Your code produces I/P & O/P like this kindly change it.

2021-03-30 13:29 UTC, siddharth25pandey commented
@Kirti1807 Please store the Prime Factors in **set** and reduce the Time Complexity for finding the Unique Prime factor

2021-03-30 13:30 UTC, siddharth25pandey requested changes
@Kirti1807 Do the suggested changes

2021-03-30 13:30 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +    }
@Kirti1807 Please store the Prime Factors in set and reduce the Time Complexity for finding the Unique Prime factor

2021-03-31 08:49 UTC, siddharth25pandey requested changes
@Kirti1807 Do the suggested changes or if possible
Try to create a **SET**  not **ARRAY** for storing prime numbers uniquely

2021-03-31 08:49 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +  }
Remove the Redundant line, Directly use **memset** for initializing the array

2021-03-31 10:43 UTC, ankitaggarwal23 requested changes

2021-03-31 10:43 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Unique_prime_factors.cpp
> +}
Rewrite it to
```
if(arr[i] == 0 && n%i == 0 ){
        cout << i <<"  ";
     }
  }
}
```

2021-03-31 18:17 UTC, siddharth25pandey approved these changes
@LGTM 💯 Able to merge

2021-03-31 18:18 UTC, merged

2021-03-31 18:18 UTC, siddharth25pandey commented
@all-contributors please add @Kirti1807 for her code