Kadane's Algorithm
HarshCasper/NeoAlgo pull request #3791
Opened 2021-03-21 09:55 UTC by JanhaviSoni

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3436

2021-03-21 12:05 UTC, gat786 requested changes

2021-03-21 12:05 UTC, gat786 commented on C-Plus-Plus/dp/Kadane_Algorithm.cpp
> +}
add a line break at the End of File

2021-03-21 12:07 UTC, gat786 commented
The code looks good to me. Theres just one slight change you need to make before we merge it.
Thanks for contributing :-)

2021-03-21 13:06 UTC, JanhaviSoni commented
@gat786 Please check

2021-03-22 03:10 UTC, gat786 approved these changes

2021-03-22 03:11 UTC, gat786 commented
Great work 😁 Have a great day 👍

2021-03-22 03:12 UTC, merged

2021-03-28 07:09 UTC, ankitaggarwal23 commented
@all-contributors bot please add @JanhaviSoni for code