Check if binary tree symmetric or not
HarshCasper/NeoAlgo pull request #3799
Opened 2021-03-21 14:11 UTC by ishvik

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is java implementation of checking if binary tree is Symmteric or not.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This is solution for issue-2880.

2021-03-28 04:09 UTC, HarshCasper requested changes
Format your code properly

2021-03-28 04:09 UTC, HarshCasper commented on Java/ds/SymmetricBT.java
> +//Space Complexity :- O(1)
Use Multi-Line Comments

2021-03-28 04:09 UTC, HarshCasper commented on Java/ds/SymmetricBT.java
> +//if a binary tree has mirror image of itself with O(n) time complexity
Use Multi-Line Comments and proper grammar as well as sentence formation

2021-03-28 04:09 UTC, HarshCasper commented on Java/README.md
> +
Remove this extra line

2021-03-31 05:55 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-03-31 05:55 UTC, closed without merging