Added MonoAlphabetic Cipher and updated README.md
HarshCasper/NeoAlgo pull request #3807
Opened 2021-03-21 15:12 UTC by nagasrihith608

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes
### Description

(Write your answer here.)
Added MonoAlphabetic Cipher in C and updated README.md
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes #3803 
(Write your answer here.)

2021-03-23 06:57 UTC, HarshCasper requested changes
Format the Code

2021-03-23 07:56 UTC, nagasrihith608 commented
@HarshCasper , yea done formating please check now

2021-03-24 06:34 UTC, nagasrihith608 commented
@HarshCasper, I formated the file now please check it.

2021-03-24 15:42 UTC, HarshCasper approved these changes

2021-03-24 15:42 UTC, HarshCasper requested changes

2021-03-24 15:42 UTC, HarshCasper commented on C/cryptography/MonoAlphabeticCipher.c
> +     //this where we store output
Redundant Comment

2021-03-24 15:42 UTC, HarshCasper commented on C/cryptography/MonoAlphabeticCipher.c
> +     //this is where we iterate and check what alphabetic is in input and then replace ii with its corresponding cipher
Redundant Comment

2021-03-24 15:42 UTC, HarshCasper commented on C/cryptography/MonoAlphabeticCipher.c
> +     //the list we use to check which alphebatic we recieved in plain text
Redundant Comment

2021-03-24 15:42 UTC, HarshCasper commented on C/cryptography/MonoAlphabeticCipher.c
> +     //this is the list which we use to cipher
Redundant Comment

2021-03-24 15:42 UTC, HarshCasper commented on C/cryptography/MonoAlphabeticCipher.c
> +     //printing out the cipher text
Redundant Comment

2021-03-24 15:42 UTC, HarshCasper commented on C/cryptography/MonoAlphabeticCipher.c
> +     //we store input here
Redundant Comment

2021-03-24 15:42 UTC, HarshCasper commented on C/cryptography/MonoAlphabeticCipher.c
> +     //we take input here
Redundant Comment

2021-03-24 16:43 UTC, HarshCasper approved these changes

2021-03-24 16:43 UTC, merged