Added Sorting the elements of a stack in C
HarshCasper/NeoAlgo pull request #3890
Opened 2021-03-22 20:17 UTC by Tanya170620

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This program sorts the elements of the stack without using another user defined stack. It is a menu driven program where the user first pushes the elements into the stack and then sorts the elements of the stack

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Sorting the elements of a stack in C #2596

2021-03-23 03:35 UTC, HarshCasper requested changes

2021-03-23 03:35 UTC, HarshCasper commented on C/ds/stack_sort.c
> +*/
Add a new line at the EOF

2021-03-23 03:35 UTC, HarshCasper commented on C/ds/stack_sort.c
> +	do {
Use a while loop instead of do while.

2021-03-24 09:24 UTC, Tanya170620 commented
I have made the requested changes. Please check. @HarshCasper

2021-03-24 16:56 UTC, HarshCasper approved these changes

2021-03-24 16:58 UTC, merged

2021-03-26 09:46 UTC, HarshCasper commented
@all-contributors bot please add @Tanya170620 for code