added Trailing_Zeros.py
HarshCasper/NeoAlgo pull request #3897
Opened 2021-03-23 05:49 UTC by Nkap23

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description
Added code to calculate the number of trailing zeros in python.

### Checklist
- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Resolves #3896

2021-03-28 04:13 UTC, HarshCasper requested changes

2021-03-28 04:13 UTC, HarshCasper commented on Python/math/Trailing_Zeros.py
> +print("Number of trailing zeros:",num_zeros)
Keep this in a function. And use a main() function for the driver code purpose

2021-03-28 04:13 UTC, HarshCasper commented on Python/math/Trailing_Zeros.py
> +Number of 5s = n//5 + n//25 + n//125 ...
Keep it modular and easy to understand

2021-03-31 05:50 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-03-31 05:51 UTC, closed without merging