Shell Sort In JAVA
HarshCasper/NeoAlgo pull request #391
Opened 2020-08-13 12:17 UTC by salonilakhotia

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-14 18:10 UTC, atarax665 requested changes

2020-08-14 18:10 UTC, atarax665 commented on Java/sort/ShellSort.java
> +        int array[] = {30, 25, 77, 16 , 80, 32, 67} ;
Take dynamic inputs

2020-08-14 18:10 UTC, atarax665 commented on Java/sort/ShellSort.java
> +import java.util.*;
Add description of the program.

2020-08-14 18:10 UTC, atarax665 commented on Java/sort/ShellSort.java
> +        int size = array.length;
Include appropriate Documentation (docstrings) for functions. Add comments where needed.

2020-08-15 07:02 UTC, salonilakhotia commented
@atarax665 I will do the changes.

2020-09-01 07:00 UTC, siddharth25pandey requested changes

2020-09-01 07:00 UTC, siddharth25pandey commented on Java/sort/ShellSort.java
> +    }
Add Sample Input & Output in Comment form

2020-09-01 07:01 UTC, siddharth25pandey commented
@salonilakhotia I request to from next time onwards Please create separate PR for different issue
Also, add the issue number in PR Template and do the required modifications

2020-09-01 16:26 UTC, salonilakhotia commented
@siddharth25pandey I have done the changes !!
I want to ask whether this PR will be accepted for both the questions?

2020-09-02 18:21 UTC, siddharth25pandey commented
> @siddharth25pandey I have done the changes !!
> I want to ask whether this PR will be accepted for both the questions?

@salonilakhotia Will be better if you create separate PR for separate Issues. 
From this PR you can only contribute for any one issue.

2020-09-22 16:05 UTC, atarax665 commented
@salonilakhotia We don't have any updates from you. Make the suggested changes ASAP.

2020-09-24 16:30 UTC, atarax665 reviewed
This PR is being closed due to inactivity from contributor's end.

2020-09-24 16:30 UTC, closed without merging