solved using double linked list
HarshCasper/NeoAlgo pull request #3910
Opened 2021-03-23 08:33 UTC by Vedika-Agrawal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have a smart look  over the guidelines

### Checklist

- [yes ] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#3343 
(Write your answer here.)

2021-03-23 10:32 UTC, siddharth25pandey requested changes
@Vedika-Agrawal As mentioned in the Issue,  you need to check for a word, it means it consists of characters as well not only integer. Therefore, I request you to change the datatype of the input as list of characters.

2021-03-25 14:19 UTC, Vedika-Agrawal commented
Sir , Changes are done according to your suggestion. plzz have a look once..

2021-03-25 19:49 UTC, siddharth25pandey requested changes
@Vedika-Agrawal Modifications required

2021-03-25 19:49 UTC, siddharth25pandey commented on C/other/Palindrome.c
> +aabbaa is palindrome
Shift it to the end of the Program & Also, write Time and space complexity.
Also, Your Sample Input/Output not matches with the given Program. (Display message is not present)

2021-03-31 05:53 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-03-31 05:53 UTC, closed without merging