Added BreathFirstSearch Algorithm #3392
HarshCasper/NeoAlgo pull request #3928
Opened 2021-03-23 12:39 UTC by theSatvik

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Breadth-first search (Uninformed Search)

## Related Issues or Pull Requests

Artificial Intelligence Algorithms #3392

2021-03-23 13:08 UTC, theSatvik commented
Hi @siddharth25pandey, I have added the following algorithm passed the check-in python also. Thankyou.

2021-03-25 06:05 UTC, siddharth25pandey requested changes
@theSatvik Add a Readme file and do the changes as suggested below

2021-03-25 06:05 UTC, siddharth25pandey commented on AI-Algorithms/breathFirstSearch.py
> +graph.add_edge('G', 'H')
Take dynamic input from the user

2021-03-25 06:05 UTC, siddharth25pandey commented on AI-Algorithms/breathFirstSearch.py
> +start, goal = 'A', 'H'
Take dynamic input from the user

2021-03-25 06:05 UTC, siddharth25pandey commented on AI-Algorithms/breathFirstSearch.py
> +    print('Path:', end=' ')
Display a message in print form as what are you showing output to user for better user-interface

2021-03-25 06:05 UTC, siddharth25pandey commented on AI-Algorithms/breathFirstSearch.py
> +    print()
At the end, write Sample Input & Output and write the Time and Space Complexity of the Algorithm.
Do the same for all PR you gonna create in future

2021-03-25 06:07 UTC, siddharth25pandey commented
@theSatvik Also add the newly created folder in the Python Directory

2021-03-28 11:15 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

@theSatvik Do the changes mentioned by @siddharth25pandey as well.

2021-03-31 06:00 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-03-31 06:00 UTC, closed without merging