Chinese Remainder Theorem Java #3958
HarshCasper/NeoAlgo pull request #3959
Opened 2021-03-24 00:13 UTC by sarahelshabrawy

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented the  Chinese Remainder Theorem in Java

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue [#3958](https://github.com/TesseractCoding/NeoAlgo/issues/3958)

2021-03-28 04:46 UTC, HarshCasper requested changes

2021-03-28 04:46 UTC, HarshCasper commented on Java/math/Chinese_Remainder_Theorem.java
> +import java.util.Scanner;
Add a beginner friendly pitch

2021-03-28 04:46 UTC, HarshCasper commented on Java/math/Chinese_Remainder_Theorem.java
> +}
Add time/space complexity and sample I/O

2021-03-31 06:03 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-03-31 06:03 UTC, closed without merging