Added Havel-Hakimi.cpp
HarshCasper/NeoAlgo pull request #3966
Opened 2021-03-24 07:46 UTC by urvashiramdasani

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added the Havel-Hakimi algorithm that checks whether a degree sequence is graphical or not. I have implemented in C++ as a part of GirlScript Summer of Code (GSSoC) 2021.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #3965

2021-03-28 06:09 UTC, HarshCasper requested changes

2021-03-28 06:09 UTC, HarshCasper commented on C-Plus-Plus/graphs/Havel-Hakimi.cpp
> +*/
Use multi-line comments and add a new line at the EOF

2021-03-28 06:09 UTC, HarshCasper commented on C-Plus-Plus/graphs/Havel-Hakimi.cpp
> +// Use Havel-Hakimi theorem and check whether the given degree sequence is graphical or not.
Add more information about the algorithm

2021-03-28 09:15 UTC, urvashiramdasani commented
Hey @HarshCasper, please check the code now. Thanks!

2021-03-31 06:16 UTC, ankitaggarwal23 requested changes

2021-03-31 06:16 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Havel-Hakimi.cpp
> +#include <algorithm>
Replace header files with `#include <bits/stdc++.h>`

2021-03-31 06:16 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Havel-Hakimi.cpp
> +		if(all_of(v.begin(), v.end(), [](int i) { return i == -1; })) return false;
Use proper code Format

2021-03-31 06:16 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/Havel-Hakimi.cpp
> +*/
Remove this redundant part and ,
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-04 11:32 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity.

2021-04-04 11:32 UTC, closed without merging