Added Find Smallest Prime Factor for any Number in C++
HarshCasper/NeoAlgo pull request #3974
Opened 2021-03-24 11:39 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES.

Given a number. find it's smallest prime factor.
we have to get the smallest factor of that number and
the smallest factor has to be a prime number.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #3973

2021-03-24 17:44 UTC, RaiyanMahin commented
@HarshCasper  @iamrajiv  Kindly review.

2021-03-24 18:01 UTC, rohanbabbar04 requested changes

2021-03-24 18:01 UTC, rohanbabbar04 commented on C-Plus-Plus/README.md
> +- [Find Smallest Prime Factor](amth/smallest_prime_factor.cpp)
Correct it write math not amth

2021-03-24 18:08 UTC, RaiyanMahin commented on C-Plus-Plus/README.md
> +- [Find Smallest Prime Factor](amth/smallest_prime_factor.cpp)
thanks

2021-03-24 19:19 UTC, iamrajiv approved these changes

2021-03-25 04:42 UTC, rohanbabbar04 approved these changes

2021-03-25 17:25 UTC, HarshCasper approved these changes

2021-03-25 17:25 UTC, merged