Create TargetSumSubsets.java
HarshCasper/NeoAlgo pull request #4013
Opened 2021-03-24 19:51 UTC by sejalvasan

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

An algorithm to calculate and print true or false, if there is a subset of the elements which add up to the given target.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Yes, I have clearly read the Guidelines, and followed the given code template format, and read READ.ME file and linked it to the code file

2021-03-28 12:10 UTC, HarshCasper requested changes
Make README updates

2021-03-29 12:08 UTC, sejalvasan commented
@HarshCasper changes done

2021-03-30 12:07 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-03-30 12:07 UTC, ankitaggarwal23 commented on Java/dp/TargetSumSubsets.java
> + */
Remove the redundant description

2021-03-31 06:17 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-03-31 06:17 UTC, closed without merging