Added Clonig stack without extra space file and changed cpp/readme.md
HarshCasper/NeoAlgo pull request #4035
Opened 2021-03-25 08:16 UTC by Ratnesh4193

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-27 13:39 UTC, Ratnesh4193 commented
this pr is for #4028 issue.
kindly review this and merge it

2021-03-28 12:13 UTC, HarshCasper requested changes

2021-03-28 12:13 UTC, HarshCasper commented on .vscode/settings.json
> +}
Remove this

2021-03-28 12:13 UTC, HarshCasper commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +	freopen("output.txt", "w", stdout);
Why do we have these files? We are not having any online judges

2021-03-29 19:11 UTC, Ratnesh4193 reviewed
MADE NECESSARY CHANGES

2021-03-31 06:13 UTC, ankitaggarwal23 requested changes

2021-03-31 06:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +
Remove extra space and write bit more description.

2021-03-31 06:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +typedef unsigned long long int  ull;
Remove CP templates and tricks

2021-03-31 06:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +
Remove extra space and write function description

2021-03-31 06:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +int main()
Add a new line

2021-03-31 06:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +	// cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl;
Remove redundant comments

2021-03-31 06:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +	source.push(4);
Use dynamic input from user

2021-04-03 09:30 UTC, Ratnesh4193 commented
@ankitaggarwal23 what changes I have to do now??

2021-04-09 06:41 UTC, ankitaggarwal23 requested changes

2021-04-09 06:41 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +// Cloning a stack into destination stack without using extra space
Use multiline comments and write proper description

2021-04-09 06:41 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +
Remove the redundant comments instead write one line about your function description

2021-04-09 06:41 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +		cloned.push(x); // now put the current element on the top
Remove the redundant comments

2021-04-09 06:41 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +int main()
Add a new line above the main

2021-04-09 06:41 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +	Cloned Stack : 4 3 2 1
Write the output in the way your code is producing and remove the tab spaces from the start Also write TC and SC

2021-04-09 13:50 UTC, Ratnesh4193 commented
Kindly review @ankitaggarwal23

2021-04-09 18:22 UTC, ankitaggarwal23 requested changes

2021-04-09 18:22 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +void clonestack(stack<int> st, stack<int> &cloned)
Rewrite it as,

```
/* 
Cloning stack without extra space:

This Function takes takes two stakes as input and copy data of first stack to the second stack.
It is a recursive code in which we store the top element of the stack in a temporary variable
and call the function which clones rest of the stack and push the stored to the top of
the stack.

*/

#include<bits/stdc++.h>
using namespace std;

void clonestack(stack<int> st, stack<int> &cloned)
```

2021-04-09 18:22 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +	*/
Left align it properly

2021-04-10 06:05 UTC, Ratnesh4193 commented
made changes kindly review @ankitaggarwal23

2021-04-11 15:57 UTC, ankitaggarwal23 requested changes
Also check your code now showing error.

2021-04-11 15:57 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +	*/
Left align it we are telling you in every review.

2021-04-11 15:59 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/clone_a_stack_without_usinig_extra_space.cpp
> +	*/
Also resolve merge conflict

2021-04-17 03:44 UTC, ankitaggarwal23 reviewed
Are you still working on it.

2021-04-18 09:10 UTC, ankitaggarwal23 reviewed
Last Reminder, Are you still working on it.

2021-04-18 09:57 UTC, Ratnesh4193 commented
@ankitaggarwal23  Sorry I was inactive for the past few days.
I will check and remove the error by evening.
I don't know how to solve merge conflict.

2021-04-19 08:10 UTC, ankitaggarwal23 approved these changes

2021-04-19 08:10 UTC, merged