Issue 2753: Check if Binary Tree is Symmetric
HarshCasper/NeoAlgo pull request #4044
Opened 2021-03-25 10:15 UTC by Ashee-Kanungo

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added the code in c++ to check if given binary tree is symmetric or not.

### Checklist

- yes I've read the contribution guidelines.
- yes I've checked the issue list before deciding what to submit.
- yes I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I was assigned issue-2753 for this.

2021-03-25 10:18 UTC, Ashee-Kanungo commented
@ankitaggarwal23 @gat786 @anushkrishnav @siddharth25pandey please review this PR.

2021-03-27 17:17 UTC, ankitaggarwal23 requested changes

2021-03-27 17:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_Symmetric_or_not.cpp
> +int height(TreeNode* A){		//this function calculate the height of the Binary Tree
Shift the comment above the function

2021-03-27 17:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_Symmetric_or_not.cpp
> +void level_order(TreeNode* A, int h, vector<int> &v){ 		//This gives us the vector of values of all the nodes at the given height
Shift the comment above the function

2021-03-27 17:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_Symmetric_or_not.cpp
> +bool is_level_palindrome(TreeNode* A, int h){		// This function checks if all the levels of given binary tree forms palindrome
Shift the comment above the function

2021-03-27 17:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_Symmetric_or_not.cpp
> +bool Check_Symmetry(TreeNode* A){		//This function checks if given binary tree is symmetrical
Shift the comment above the function

2021-03-27 17:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_Symmetric_or_not.cpp
> +*/
- Remove the extra testcase one is enough. 
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-03-28 09:26 UTC, Ashee-Kanungo commented
@ankitaggarwal23 I have made all the changes in the PR. Please review it.

2021-03-30 12:01 UTC, ankitaggarwal23 requested changes

2021-03-30 12:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_Symmetric_or_not.cpp
> +
Remove extra one line at the end

2021-03-30 12:29 UTC, Ashee-Kanungo commented
@ankitaggarwal23 I have removed one extra line at the end.

2021-03-30 12:30 UTC, Ashee-Kanungo commented
@ankitaggarwal23 please review it now.

2021-03-31 06:26 UTC, ankitaggarwal23 approved these changes

2021-03-31 06:26 UTC, merged