Added natural logarithm algorithm
HarshCasper/NeoAlgo pull request #4045
Opened 2021-03-25 10:17 UTC by XZANATOL

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

- [x] Yes

### Description

Added natural logarithm (ln) algorithm using Taylor's series along with the pros & cons of using this approach.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #4034

2021-03-26 20:15 UTC, XZANATOL commented
@HarshCasper I don't know wether the resolve i did to resolve the merge conficts will affect the repository or not.. but if it will, let me know so that i reopen another PR instead of this one. 🤔

2021-03-28 09:27 UTC, ankitaggarwal23 requested changes

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/README.md
> +<<<<<<< HEAD
Remove that redundant line

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/README.md
> +=======
Remove that redundant line

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/README.md
> +>>>>>>> 53f43cf279f04ab5f30212c23fd06935ced40093
Remove that redundant line

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/math/Natural_Logarithm_Algorithm.py
> +# Written by XZANATOL
Remove that redundant line

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/math/Natural_Logarithm_Algorithm.py
> +
Remove extra one line

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/math/Natural_Logarithm_Algorithm.py
> +    val, neg_flag = conv_if_neg(val)  # artanh(-x) = -1 * artanh(x)
Shift comment above the line of code

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/math/Natural_Logarithm_Algorithm.py
> +
Remove one line

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/math/Natural_Logarithm_Algorithm.py
> +
Remove one line

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/math/Natural_Logarithm_Algorithm.py
> +    3) artanh(-x) = -1 * artanh(x)
Shift your approach after description

2021-03-28 09:27 UTC, ankitaggarwal23 commented on Python/math/Natural_Logarithm_Algorithm.py
> +"""
Add SC as well.

2021-03-28 19:11 UTC, XZANATOL commented
I've done the required changes on a second PR, as I had unresolvable problems with that one. Please continue with the review on PR #4045

2021-03-29 13:36 UTC, closed without merging