Generate all n balanced parenthesis combinations
HarshCasper/NeoAlgo pull request #4049
Opened 2021-03-25 11:06 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Added generate valid parenthesis file in cp(competitive programming) folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4023

2021-03-25 16:14 UTC, gayatri517 commented
@HarshCasper kindly review it.

2021-03-26 04:53 UTC, HarshCasper requested changes

2021-03-26 04:53 UTC, HarshCasper commented on C-Plus-Plus/cp/generate_valid_parenthesis.cpp
> +You are given a number n, your job is to find al the n balanced parenthesis
It should be `all` not `al`

2021-03-26 04:53 UTC, HarshCasper commented on C-Plus-Plus/cp/generate_valid_parenthesis.cpp
> +void FindValidParenthesis(char *out, int n, int index, int open, int close)
Add a function description

2021-03-26 05:16 UTC, gayatri517 commented
@HarshCasper I have made the changes. Kindly review.
Thank you.

2021-03-28 08:50 UTC, HarshCasper approved these changes

2021-03-28 08:51 UTC, merged