Added Unique_Number.cpp and Updated REAMDME.md
HarshCasper/NeoAlgo pull request #4096
Opened 2021-03-25 22:16 UTC by Fab-Gaurav

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Given an integer array , finding the Unique Elements in the array that appears exactly once and return the sum of the unique element array.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

https://github.com/TesseractCoding/NeoAlgo/issues/4094

2021-03-26 09:41 UTC, HarshCasper requested changes

2021-03-26 09:41 UTC, HarshCasper commented on C-Plus-Plus/math/Unique_Number.cpp
> +int main(){
Don't put your code logic in `main()` function. Use `main()` for the driver code

2021-03-26 09:41 UTC, HarshCasper commented on C-Plus-Plus/math/Unique_Number.cpp
> +
Keep sample I/O at the end of the code

2021-03-26 09:41 UTC, HarshCasper commented on C-Plus-Plus/math/Unique_Number.cpp
> +}
Add a new line at the EOF

2021-03-27 16:10 UTC, Fab-Gaurav commented
@HarshCasper I have made the required changes.
Have a look : https://github.com/TesseractCoding/NeoAlgo/pull/4270

2021-03-28 07:52 UTC, ankitaggarwal23 reviewed
@Fab-Gaurav Don't open new PR for each changes requested by @HarshCasper. Closing all your PR open a new one Do all the changes Harsh requested.

2021-03-28 07:52 UTC, closed without merging

2021-03-28 16:00 UTC, Fab-Gaurav commented
> @Fab-Gaurav Don't open new PR for each changes requested by @HarshCasper. Closing all your PR open a new one Do all the changes Harsh requested.

Done @ankitaggarwal23 
I have make the changes and make the new PR #4400
Please have a look @HarshCasper 
Thank you