Ayush pradhan9
HarshCasper/NeoAlgo pull request #4106
Opened 2021-03-26 06:34 UTC by AyushPradhan9

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description
Adding merge string alternatively algorithm in C-Plus-Plus/cp

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Closes: #4104

2021-03-28 09:53 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-03-28 09:53 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Merge_string_alternatively.cpp
> +string mergeAlternately(string word1, string word2) {
Add one line function description

2021-03-28 12:04 UTC, AyushPradhan9 commented
Hey, @ankitaggarwal23 I have pushed the requested changes. Regards!

2021-03-28 13:29 UTC, ankitaggarwal23 requested changes

2021-03-28 13:29 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Merge_string_alternatively.cpp
> +    /* This function will take 2 string as input and return the resultant merged string formed alternatively from the inputted strings */
Shift the comment above the function

2021-03-28 13:29 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Merge_string_alternatively.cpp
> +    int less=min(word1.length(),word2.length());    // takes the size of the smallest string among word1 and word2
Shift the comment above the line of code

2021-03-28 13:29 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Merge_string_alternatively.cpp
> +    while(i<less || j<less){    // alternatively add word by word from each string to resultant string
Shift the comment above the line of code

2021-03-28 13:29 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Merge_string_alternatively.cpp
> +    if(word1.length()!=word2.length()){     // if both strings are of unequal sizes then add the rest of substring to the resultant string
Shift the comment above the line of code

2021-03-28 14:37 UTC, AyushPradhan9 commented
Thanks for the guidance!

2021-03-29 11:30 UTC, ankitaggarwal23 approved these changes

2021-03-29 11:30 UTC, merged