Issue 2754: Convert Binary tree to Doubly linked list
HarshCasper/NeoAlgo pull request #4114
Opened 2021-03-26 09:28 UTC by Ashee-Kanungo

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added the code in c++ to convert binary tree to doubly linked list.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I was assigned issue-2754 for this.

2021-03-26 09:30 UTC, Ashee-Kanungo commented
@ankitaggarwal23 @gat786 @anushkrishnav @siddharth25pandey @HarshCasper please review this PR.

2021-03-27 16:54 UTC, ankitaggarwal23 requested changes

2021-03-27 16:54 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +#include <queue>
Replace the header files with `#include<bits/stdc++.h>`

2021-03-27 16:54 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +TreeNode* insert(TreeNode* t, queue<TreeNode* > &q, int v){		//This function inserts node into the binary tree
Shift the comment above the function

2021-03-27 16:54 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +TreeNode* make_tree(vector<int> v){		//This function converts given vector into Binary Tree
Shift the comment above the function

2021-03-27 16:54 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +void print_elements(TreeNode* &T){		//This function prints all the elements of doubly linked list
Shift the comment above the function

2021-03-27 16:54 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +void to_dll(TreeNode* T, TreeNode* &temp){		//This function converts Binary tree to doubly linked list
Shift the comment above the function

2021-03-27 16:54 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +*/
- Remove the extra testcase one is enough. 
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-03-28 08:55 UTC, Ashee-Kanungo commented
@ankitaggarwal23 I have made all the changes in the PR. Please review it.

2021-03-28 14:01 UTC, siddharth25pandey requested changes
@Ashee-Kanungo Do the suggested changes

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +	int n;		//number of nodes of binary tree
Write a good naming convention for n such as nodes

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +	cin>>n;
Before this line, please print the the message as what are you taking input from the user for better UI

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +	vector<int> v;
write a good naming convention for v

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +		int x;
write a good naming convention for x

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +		cin>>x;
Before this line, please print the the message as what are you taking input from the user.

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +	TreeNode* T = make_tree(v);
Before this line, please print the the message as what are you showing to the user

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +	to_doubly_linked_list(T);
Before this line, please print the the message as what are you showing to the user

2021-03-28 14:01 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Binary_Tree_to_Doubly_Linked_List.cpp
> +
In Sample Input & Output, Display exactly same as what your program is executing

2021-03-28 14:02 UTC, siddharth25pandey commented
@Ashee-Kanungo Also resolve the merge conflict error

2021-03-28 14:13 UTC, Ashee-Kanungo commented
@siddharth25pandey how can I resolve the merge conflict error? Should I make a separate PR with all these changes?

2021-03-28 15:54 UTC, siddharth25pandey commented
> @siddharth25pandey how can I resolve the merge conflict error? Should I make a separate PR with all these changes?

@Ashee-Kanungo I have resolved the merge conflict error. Only you need to modify the changes as suggested earlier in the same PR

2021-03-28 19:42 UTC, Ashee-Kanungo commented
@siddharth25pandey  I have made all the changes in the PR. Please review it.

2021-03-31 06:40 UTC, ankitaggarwal23 requested changes
Write output what your code is producing.

2021-03-31 07:07 UTC, Ashee-Kanungo commented
@ankitaggarwal23 I have made the changes. Please review it.

2021-03-31 12:03 UTC, ankitaggarwal23 reviewed
I have checked your code and it shows error kindly check your code and also write the output in the same way the code is producing.

2021-03-31 14:19 UTC, Ashee-Kanungo commented
@ankitaggarwal23 I have made the changes. Please review it.

2021-03-31 15:16 UTC, ankitaggarwal23 approved these changes

2021-03-31 15:20 UTC, merged