Added a file of 'Remove all Fibonacci Nodes from a Circular Singly Linked List'Issue number: #4076
HarshCasper/NeoAlgo pull request #4124
Opened 2021-03-26 10:17 UTC by jyoti-anjaly

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes , I have read this.

### Description
Added a file of 'Remove all Fibonacci Nodes from a Circular Singly Linked List in C++'. Also updated the readme.md file.

### Checklist

- [ yes] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue number: #4076

2021-03-26 15:35 UTC, jyoti-anjaly commented
@maintainers Can anyone check whether the file added by me is okay or not?

2021-03-26 15:47 UTC, jyoti-anjaly commented
@reviewers issue number: #4076

2021-03-26 15:52 UTC, jyoti-anjaly reviewed
Can anyone please check whether the changes done by me is okay or not?

2021-03-28 07:58 UTC, jyoti-anjaly commented
@SKAUL05 @nrickles3 @ArchanGhosh @hushee69 Can you please view this whether it is correct or not?

2021-03-28 12:18 UTC, HarshCasper requested changes
Use multi-line comments wherever possible

2021-03-28 12:18 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Binary Search Tree Validation](ds/Binary_Search_Tree_Validation.)
Why are there two README changes?

2021-03-28 13:03 UTC, jyoti-anjaly reviewed
I've added multi line comments. Can you please check?

2021-03-28 13:05 UTC, jyoti-anjaly commented
@HarshCasper I've corrected readme file and added multi-lines comments. Please check

2021-03-31 06:55 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/various-operations-on-fibonacci-nodes-in-a-singly-linked-list/).

2021-03-31 06:56 UTC, closed without merging