added Three sum file (issue #4140)
HarshCasper/NeoAlgo pull request #4159
Opened 2021-03-26 14:12 UTC by anshmishra010

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

We have to find the sum of the target value using using three digit present in the list.
I'll provide the optimized solution using two pointer technique.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4140

2021-03-26 14:17 UTC, gat786 commented
The readme seems to be not updated. Push the commit in which we updated the readme.

2021-03-26 14:22 UTC, anshmishra010 commented
done

2021-03-26 17:30 UTC, HarshCasper requested changes

2021-03-26 17:30 UTC, HarshCasper commented on C-Plus-Plus/cp/Three_Sum.cpp
> +int main()
Push all the main code logic in a separate function and use main() for driver code

2021-03-28 07:27 UTC, ankitaggarwal23 reviewed
@anshmishra010 Do the changes mentioned.
Rest looks good to merge.

2021-03-28 07:34 UTC, anshmishra010 commented
Actually the thing is I have deleted the branch from which I have pushed.

2021-03-28 08:39 UTC, ankitaggarwal23 commented
@anshmishra010 Okay I'm closing this PR. Open a new one and do the changes, we will review

2021-03-28 08:40 UTC, closed without merging