Find the modulo of a huge Fibonacci number using Pisano Period in Java.
HarshCasper/NeoAlgo pull request #4165
Opened 2021-03-26 14:48 UTC by Meghna180401

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is the implementation to find the modulo of a huge fibonacci number using Pisano Period Properties.

### Checklist

- [ ✅] I've read the contribution guidelines.
- [ ✅] I've checked the issue list before deciding what to submit.
- [ ✅] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2543

2021-03-26 14:53 UTC, Meghna180401 commented
@HarshCasper @bhav09  Kindly review.

2021-03-28 12:32 UTC, HarshCasper requested changes

2021-03-28 12:32 UTC, HarshCasper commented on Java/other/Fibonacci_modulo.java
> +  Space Complexity:
Remove these

2021-03-28 12:32 UTC, HarshCasper commented on Java/other/Fibonacci_modulo.java
> + */
Add a new line at the EOF

2021-03-31 07:03 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/fibonacci-number-modulo-m-and-pisano-period/).

2021-03-31 07:03 UTC, closed without merging