SOLVED ASCII CODE OF EACH CHARACTER OF ENTERED STRING PROBLEM
HarshCasper/NeoAlgo pull request #4183
Opened 2021-03-26 17:44 UTC by ananddasani

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes !!

### Description

i have implemented the solution of SOLVED ASCII CODE OF EACH CHARACTER OF ENTERED STRING PROBLEM
so i would request @HarshCasper , @ankitaggarwal23 , @bhav09 to please review my PR.

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No :)

2021-03-27 16:41 UTC, ankitaggarwal23 requested changes

2021-03-27 16:41 UTC, ankitaggarwal23 commented on Java/README.md
> +- [ASCII_code_of_each_character_of_string](math/ASCII_code_of_each_character_of_string.java)
- Remove Underscores from `[ASCII_code_of_each_character_of_string]`
- `ASCII_code_of_each_character_of_string.java` make it concise and short

2021-03-27 16:41 UTC, ankitaggarwal23 commented on Java/math/ASCII_code_of_each_character_of_string.java
> +//AIM :: to print the ASCII CODE of each character of entered string
Add a bit more description

2021-03-27 16:41 UTC, ankitaggarwal23 commented on Java/math/ASCII_code_of_each_character_of_string.java
> +public class ASCII_code_of_each_character_of_string {
Make it short and concise ASCII_code_of_each_character_of_string

2021-03-27 16:41 UTC, ankitaggarwal23 commented on Java/math/ASCII_code_of_each_character_of_string.java
> +
Remove extra test case one is enough

2021-03-27 16:41 UTC, ankitaggarwal23 commented on Java/math/ASCII_code_of_each_character_of_string.java
> + */
Add a new line at the EOF

2021-03-27 17:04 UTC, ananddasani commented on Java/math/ASCII_code_of_each_character_of_string.java
> + */
okay

2021-03-27 17:20 UTC, ananddasani commented
@ankitaggarwal23 i have made all the changes as directed , please review again :)

2021-03-27 17:58 UTC, atarax665 requested changes
Segregate Driver code and the logic part. The main function should only have the driver code.

2021-03-27 17:58 UTC, atarax665 commented on Java/math/AsciiOfString.java
> +TEST CASE
Add space and time complexity.

2021-03-29 17:17 UTC, ananddasani commented
@ankitaggarwal23 all set ! 

please review this PR also :)

2021-03-30 05:42 UTC, ankitaggarwal23 approved these changes

2021-03-30 05:42 UTC, merged