First Negative Integer In Every Window Of Size K in JavaScript
HarshCasper/NeoAlgo pull request #4184
Opened 2021-03-26 17:46 UTC by Coder-Srinivas

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given an array of integers and a an integer k, we are supposed to return an array 
which contains the first negative integer in every window of size k 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue: #2304

2021-03-26 17:49 UTC, Coder-Srinivas commented
@siddharth25pandey I have added the code for First Negative Integer In Every Window Of Size K in JavaScript. You can test it [here](https://practice.geeksforgeeks.org/problems/first-negative-integer-in-every-window-of-size-k/0#). Please let me know if any changes are required. 😊

2021-03-28 12:38 UTC, HarshCasper requested changes

2021-03-28 12:38 UTC, HarshCasper commented on JavaScript/cp/FirstNegativeIntegerInEveryWindowOfSizeK.js
> +console.log(firstNegativeIntegerInEveryWindowOfSizeK([12, -1, -7, 8, -15, 30, 16, 28], 3))
Make it as a dynamic input

2021-03-31 07:06 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-04-03 08:05 UTC, Coder-Srinivas commented
@HarshCasper I have added dynamic input using the readline() module. Please let me know if any changes are required.

2021-04-04 11:42 UTC, ankitaggarwal23 requested changes

2021-04-04 11:42 UTC, ankitaggarwal23 commented on JavaScript/cp/FirstNegativeIntegerInEveryWindowOfSizeK.js
> +[0]
Write a proper display message how you are reading nums , k and printing output.
Remove the extra testcase one is enough.

2021-04-04 12:19 UTC, Coder-Srinivas commented
@ankitaggarwal23 Made the changes requested.

2021-04-04 13:22 UTC, ankitaggarwal23 requested changes

2021-04-04 13:22 UTC, ankitaggarwal23 commented on JavaScript/cp/FirstNegativeIntegerInEveryWindowOfSizeK.js
> +[-8, 0, -6, -6]
Write the I/p and O/p the way your code is producing

2021-04-04 15:49 UTC, Coder-Srinivas commented
@ankitaggarwal23 Made the changes requested.

2021-04-04 17:47 UTC, ankitaggarwal23 approved these changes

2021-04-04 17:49 UTC, merged