Added One plus to the whole
HarshCasper/NeoAlgo pull request #4216
Opened 2021-03-27 05:35 UTC by Nidhideveloper

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added One plus to the whole

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4210

2021-03-27 05:39 UTC, Nidhideveloper commented
@HarshCasper Sir, plz check this and let me know if there is any problem with the code or not. thank u sir. 
And sir plz give the label of the levels of my contributions as most of them donot have the level label. Sir, it will be very kind of you, if you do so.

2021-03-27 05:57 UTC, rohanbabbar04 commented
@Nidhideveloper If you have an issue don't post here DM him the PR's which are not marked

2021-03-28 05:10 UTC, ankitaggarwal23 requested changes

2021-03-28 05:10 UTC, ankitaggarwal23 commented on Java/other/OnePlustoWhole.java
> +
Remove extra new line

2021-03-28 05:10 UTC, ankitaggarwal23 commented on Java/other/OnePlustoWhole.java
> +The incremented number is: [1]
- Remove extra test case one is enough
- Add Space complexity

2021-03-28 09:41 UTC, Nidhideveloper commented
@ankitaggarwal23 Sir, I have made changes and please review it.

2021-03-28 12:53 UTC, ankitaggarwal23 approved these changes

2021-03-28 12:53 UTC, merged