Flight of stairs in java (Dp)
HarshCasper/NeoAlgo pull request #4226
Opened 2021-03-27 07:36 UTC by FireQueen-3010

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

The flight of stairs problem using dp in Java.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4223 (java)

2021-03-27 07:37 UTC, FireQueen-3010 commented
Please review my pr @HarshCasper

2021-03-28 12:06 UTC, HarshCasper requested changes

2021-03-28 12:06 UTC, HarshCasper commented on Java/dp/FlightOfStairs.java
> +*/
Try to modularize this content. Make it short, crisp and readable

2021-03-28 12:23 UTC, FireQueen-3010 commented
Done with the changes , @HarshCasper . Please review :)

2021-03-30 10:26 UTC, ankitaggarwal23 requested changes

2021-03-30 10:26 UTC, ankitaggarwal23 commented on Java/dp/FlightOfStairs.java
> +        int k = sc.nextInt();
Add a display message.

2021-03-30 10:26 UTC, ankitaggarwal23 commented on Java/dp/FlightOfStairs.java
> + */
Add a proper display message
Add a new line at the end

2021-03-30 14:39 UTC, FireQueen-3010 commented
Done with the changes please review @ankitaggarwal23

2021-03-31 07:11 UTC, ankitaggarwal23 approved these changes

2021-03-31 07:11 UTC, merged