Count Anagrams in JavaScript
HarshCasper/NeoAlgo pull request #4228
Opened 2021-03-27 07:39 UTC by Coder-Srinivas

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given two strings word and text, return the number of 
substrings where text contains any anagram of word.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue: #2304

2021-03-27 07:42 UTC, Coder-Srinivas commented
@siddharth25pandey @HarshCasper I have added the code for count anagrams in JavaScript. You can test it [here](https://binarysearch.com/problems/Anagram-Substrings). Please let me know if any changes are required. 😊

2021-03-28 12:08 UTC, HarshCasper requested changes

2021-03-28 12:08 UTC, HarshCasper commented on JavaScript/cp/CountAnagrams.js
> +console.log(countAnagrams("for", "trfororfideriorofrufrx"))
Make the input dynamic

2021-03-31 07:06 UTC, ankitaggarwal23 reviewed
Closing this PR due to inactivity.

2021-04-03 08:05 UTC, Coder-Srinivas commented
@HarshCasper I have added dynamic input using the readline() module. Please let me know if any changes are required.

2021-04-04 11:43 UTC, ankitaggarwal23 requested changes

2021-04-04 11:43 UTC, ankitaggarwal23 commented on JavaScript/cp/CountAnagrams.js
> +3
Write a proper display message how you are reading and printing output.
Remove the extra testcase one is enough.

2021-04-04 12:19 UTC, Coder-Srinivas commented
@ankitaggarwal23 Made the changes requested.

2021-04-04 13:19 UTC, ankitaggarwal23 requested changes

2021-04-04 13:19 UTC, ankitaggarwal23 commented on JavaScript/cp/CountAnagrams.js
> +1
Write the I/p and O/p the way your code is producing

2021-04-04 15:49 UTC, Coder-Srinivas commented
@ankitaggarwal23 Made the changes requested.

2021-04-04 17:47 UTC, ankitaggarwal23 approved these changes

2021-04-04 17:52 UTC, merged