Added Quick Sort in C
HarshCasper/NeoAlgo pull request #4276
Opened 2021-03-27 16:33 UTC by shadowasphodel2919

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes, I have

### Description

I have added quick sort program to the sort category under C.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Solved the issue
https://github.com/TesseractCoding/NeoAlgo/issues/2238

2021-03-27 17:28 UTC, atarax665 requested changes

2021-03-27 17:28 UTC, atarax665 commented on C/sort/quickSort.c
> +/*Quick Sort is a divide and conquer algorithm which works on the basic principle
Shift the description above the header file.

2021-03-27 17:28 UTC, atarax665 commented on C/sort/quickSort.c
> +    return (i+1);
```suggestion
    return (i + 1);
```

2021-03-27 17:28 UTC, atarax665 commented on C/sort/quickSort.c
> +}
Add sample I/O and space and time complexity of the program in commented form.

2021-03-28 09:50 UTC, shadowasphodel2919 commented
@atarax665 I have made the required changes, kindly review again.

2021-03-31 07:17 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/quicksort-using-random-pivoting/).

2021-03-31 07:17 UTC, closed without merging