Added Insert position in java
HarshCasper/NeoAlgo pull request #4295
Opened 2021-03-27 19:56 UTC by Nidhideveloper

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added Insert position in java

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4292

2021-03-27 19:57 UTC, Nidhideveloper commented
@HarshCasper Plz check the PR, thank u sir!

2021-03-30 01:39 UTC, atarax665 requested changes

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +
Remove this extra line.

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +    //DRIVER METHOD
```suggestion
    //DRIVER CODE
```

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +        int leftptr=0;
```suggestion
        int leftptr = 0;
```

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +        int rightptr=arr.length-1;
```suggestion
        int rightptr = arr.length - 1;
```

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +            int mid = (leftptr+rightptr)/2;
```suggestion
            int mid = (leftptr + rightptr) / 2;
```

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +            if(arr[mid]==key)
```suggestion
            if(arr[mid] == key)
```

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +            else if(arr[mid]>key)
```suggestion
            else if(arr[mid] > key)
```

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +                leftptr=mid+1;
```suggestion
                leftptr = mid + 1;
```

2021-03-30 01:39 UTC, atarax665 commented on Java/other/InsertPosition.java
> +                rightptr=mid-1;
```suggestion
                rightptr = mid - 1;
```

2021-03-30 03:49 UTC, Nidhideveloper commented
@atarax665 Sir I have modified the code, please check.

2021-03-31 07:28 UTC, ankitaggarwal23 approved these changes

2021-03-31 07:29 UTC, merged