Added node deletion from BST #4301
HarshCasper/NeoAlgo pull request #4302
Opened 2021-03-28 04:24 UTC by Amulya310

Solution to  #issue4301

Hey, I've added the code for node deletion from BST in CPP. This is a small contribution under GSSOC'21.
I've also included a brief description ,multiline comments and 3 test cases( inputs and outputs ) in my code.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-30 01:06 UTC, atarax665 requested changes
Update appropriate README.

2021-03-30 01:06 UTC, atarax665 commented on node_deletion_BST.cpp
> +	root = insert(root, 1);
Try to take inputs from the user.

2021-03-30 01:06 UTC, atarax665 commented on node_deletion_BST.cpp
> +1.input-2
Add space and time complexity of the program.

2021-03-31 07:31 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://github.com/tanvi-surana/data-structures/blob/master/trees/BinarySearchTree%20class1.cpp).

2021-03-31 07:31 UTC, closed without merging