CH20 SONU KUMAR KUSHWAHA -> IMPLEMENTED THE STACK VIA QUEUE AND VICE …
HarshCasper/NeoAlgo pull request #431
Opened 2020-08-16 05:11 UTC by sonukushwaha403

…VERSA

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-16 05:12 UTC, sonukushwaha403 commented
CH20 ISSUE #412 is done

2020-08-16 06:14 UTC, iamrajiv requested changes
@sonukushwaha403 I think it is similar to https://www.geeksforgeeks.org/queue-using-stacks/, please change it. Also, whenever you add codes do update the readme accordingly.

2020-08-16 06:16 UTC, iamrajiv requested changes

2020-08-16 06:16 UTC, iamrajiv commented on Python/ds/stack_via_queue.py
> +# Program to implement a stack using
@sonukushwaha403 similar to this https://www.geeksforgeeks.org/implement-stack-using-queue/

2020-08-17 05:22 UTC, vatsalkesarwani12 requested changes
do the changes

2020-08-17 05:22 UTC, plazzy99 commented on Python/ds/stack_via_queue.py
> +from queue import Queue
You have to use the only list for writing your code as clearly mentioned no inbuilt function

2020-08-18 12:56 UTC, Abhijit2505 requested changes
Plagiarized

2020-08-21 04:18 UTC, sonukushwaha403 commented
please review is have done changes

2020-08-22 11:04 UTC, siddharth25pandey commented
@sonukushwaha403 Refer [this](https://github.com/TesseractCoding/NeoAlgo/pull/431#pullrequestreview-468036613)

2020-08-22 11:04 UTC, closed without merging