Added flight of stairs in javascript (DP)
HarshCasper/NeoAlgo pull request #4330
Opened 2021-03-28 07:48 UTC by FireQueen-3010

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

The flight of stairs problem using dp in Javascript

Given two positive integers : n and k. We are currently at stair 0, and want to climb to stair n. We can either climb 1, 2 or 3 stairs at a time, but we can climb 3 stairs only k times. Return the number of ways to climb to the nth stair.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4223 (javascript)

2021-03-28 07:50 UTC, FireQueen-3010 commented
Please review @ankitaggarwal23 @HarshCasper @siddharth25pandey

2021-03-29 10:12 UTC, HarshCasper requested changes

2021-03-29 10:12 UTC, HarshCasper commented on JavaScript/dp/flightOfStairs.js
> +FlightOfStairs(4,1);
Use dynaminc input

2021-03-30 14:16 UTC, FireQueen-3010 commented
I have conflict issues which I am unable to resolve in this pr , so I am making a fresh pr(with the changes required) for the same issue and closing this one

2021-03-30 14:16 UTC, closed without merging