IMPLEMENTED DECIMAL TO BINARY NUMBER CONVERSION PROGRAM
HarshCasper/NeoAlgo pull request #4349
Opened 2021-03-28 09:16 UTC by ananddasani

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes !!

### Description

I have implemented the Decimal to Binary number conversion problem 

I have deleted the Tower of Hanoi source code file which was previously added by me , but it was already present in other directory of c rather than math :(

I request @ankitaggarwal23 , @HarshCasper to please review my PR.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No !!

Fixes #4342

2021-03-28 13:23 UTC, ankitaggarwal23 requested changes

2021-03-28 13:23 UTC, ankitaggarwal23 commented on C/README.md
> +- [Decimal To Binary] (math/DecimalToBinary.c)
Remove the space between `]  (math`

2021-03-28 13:23 UTC, ankitaggarwal23 commented on C/README.md
> +- [Neon Number](math/Neon_number.c)
Remove this `- [Neon Number](math/Neon_number.c) ` why you adding this as the file already present.

2021-03-28 13:39 UTC, ananddasani commented on C/README.md
> +- [Decimal To Binary] (math/DecimalToBinary.c)
okay

2021-03-28 14:09 UTC, ananddasani commented
@ankitaggarwal23 okay i got ,, i have deleted that 2 more neonumber list from README file at the time of solving conflicts ,
now you can check everything is alright i think :)

2021-03-29 11:28 UTC, ankitaggarwal23 requested changes

2021-03-29 11:28 UTC, ankitaggarwal23 commented on C/math/DecimalToBinary.c
> +int isFull();
Remove the function declaration.

2021-03-29 11:28 UTC, ankitaggarwal23 commented on C/math/DecimalToBinary.c
> +}
Shift the int main() after all the function end.

2021-03-29 11:28 UTC, ankitaggarwal23 commented on C/math/DecimalToBinary.c
> +int isEmpty()
Add a one line description above the function.

2021-03-29 11:28 UTC, ankitaggarwal23 commented on C/math/DecimalToBinary.c
> +int isFull()
Add a one line description above the function.

2021-03-29 11:28 UTC, ankitaggarwal23 commented on C/math/DecimalToBinary.c
> +void push(int r)
Add a one line description above the function.

2021-03-29 11:28 UTC, ankitaggarwal23 commented on C/math/DecimalToBinary.c
> +int pop()
Add a one line description above the function.

2021-03-29 13:39 UTC, ananddasani commented
@ankitaggarwal23 done :)

2021-03-29 14:18 UTC, ankitaggarwal23 approved these changes

2021-03-29 14:29 UTC, ankitaggarwal23 requested changes
@ananddasani Why you are adding Neon Number file again. Kindly delete it
![Capture](https://user-images.githubusercontent.com/67387053/112851907-0b756000-90c9-11eb-8f51-8208ae8c15dd.JPG)

2021-03-29 17:15 UTC, ananddasani commented
@ankitaggarwal23  now see !! 

don't know how this neon number is being added again again 🤷‍♂️😂

2021-03-30 05:38 UTC, ankitaggarwal23 approved these changes

2021-03-30 05:38 UTC, merged