Articulation Point in JAVA[ #2491 - Fixed ]
HarshCasper/NeoAlgo pull request #4363
Opened 2021-03-28 11:19 UTC by krishna-y2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description

I have contributed  Articulation Point problem of graph in  JAVA.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2491

2021-03-29 11:53 UTC, ankitaggarwal23 requested changes

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +import java.io.*;
Add a new line after header ends.

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +	static class Graph
Align your code and comments properly.

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +		 Graph(int v)
Align your code and comments properly.

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +		 static void addEdge(int u , int v)
Align your code and comments properly.

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +		 static void dfs(int node , int par)
Align your code and comments properly.

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +				if(par == 0  && children > 1)
Align your code and comments properly.

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +  }
Align your code and comments properly.

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +Output
Add a new line above output

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +Explanation :
Add a new line above explanation

2021-03-29 11:53 UTC, ankitaggarwal23 commented on Java/graphs/Articulation_Point.java
> +*/
Add a new line at the EOF

2021-03-29 12:26 UTC, krishna-y2000 commented
@ankitaggarwal23  changes are applied.

2021-04-01 10:58 UTC, krishna-y2000 commented
@ankitaggarwal23 hii,
if you find any spare time then please review my pr. This might be the last check.
@HarshCasper

2021-04-05 13:49 UTC, HarshCasper approved these changes

2021-04-05 13:49 UTC, merged