Job Scheduling algorithm - Greedy Problem in JAVA
HarshCasper/NeoAlgo pull request #4390
Opened 2021-03-28 14:40 UTC by krishna-y2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have contributed Job Scheduling algorithm in JAVA.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2494

2021-03-29 11:45 UTC, ankitaggarwal23 requested changes

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +//Solution :
Remove the redundant comments and add a new line after description ends */

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +import java.util.*;
Add a new line after header ends.

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +	// solve() will do the task of getting the profit
Add a new line above the comments

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +        Arrays.fill(slots, false);
Align your code properly.

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +            {
Align your code properly.

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> + 	public static void main(String[] args) throws IOException{
Add a new line above the public static

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +}
Add a new line after the `}`

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +Maximum Profit : 2 60
Add a proper new line and space to differentiate b/w Input and output it is bit confusing where input ends and output starts

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +Time Complexity : O(NLogN)
Add a new line above the TC

2021-03-29 11:45 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Job_Scheduling.java
> +*/
Add a new line at the EOF

2021-03-29 12:28 UTC, krishna-y2000 commented
@ankitaggarwal23  changes are applied

2021-04-01 10:57 UTC, krishna-y2000 commented
@ankitaggarwal23  hii,
 if you find any spare time then please review my pr. This might be the last check. 
@HarshCasper

2021-04-04 12:20 UTC, ankitaggarwal23 approved these changes

2021-04-04 12:20 UTC, merged