Print the first non repeating character in a running stream of characters
HarshCasper/NeoAlgo pull request #4393
Opened 2021-03-28 14:58 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Code added in cp(competitive programming) folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4357

2021-03-28 15:01 UTC, gayatri517 commented
@HarshCasper Kindly review it.
Thank you.

2021-03-31 07:48 UTC, ankitaggarwal23 requested changes
Shift your code to some other function and use main for driver code.

2021-03-31 10:57 UTC, gayatri517 commented
@ankitaggarwal23 I have made the changes. Kindly review it
Thank you.

2021-04-01 15:33 UTC, HarshCasper requested changes

2021-04-01 15:33 UTC, HarshCasper commented on C-Plus-Plus/cp/first_non_repeating_character.cpp
> +Else, it is the first occurance and therefore it prints it. */
It has been repeated twice

2021-04-01 15:33 UTC, HarshCasper commented on C-Plus-Plus/README.md
> -
Remove this line

2021-04-01 15:33 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [First non repeating character in a running stream](cp/first_non_repeating_character.cpp)
Give a space after this line

2021-04-01 15:44 UTC, gayatri517 commented
@HarshCasper I have made the changes requested. Kindly review it.
Thank you.

2021-04-03 05:44 UTC, gayatri517 commented
@HarshCasper please take a look at my PR.

2021-04-03 11:21 UTC, HarshCasper approved these changes

2021-04-03 11:22 UTC, merged