Printing all Good Numbers in a given range
HarshCasper/NeoAlgo pull request #4402
Opened 2021-03-28 16:50 UTC by AkanshaUniyal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This program prints all the "Good Numbers" present in a given range.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixes #4399

2021-03-29 10:24 UTC, gat786 requested changes

2021-03-29 10:24 UTC, gat786 commented on Java/math/good_number.java
> +         for(int count=start;count<end;count++)
Take the logic of finding good numbers out of the main function

2021-04-02 08:37 UTC, gat786 approved these changes

2021-04-05 13:52 UTC, HarshCasper approved these changes

2021-04-05 13:52 UTC, merged