Ceaser cipher
HarshCasper/NeoAlgo pull request #444
Opened 2020-08-16 06:45 UTC by parjanyaacoder

# Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented Ceaser Cipher in Java

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#422

2020-08-16 11:32 UTC, parjanyaacoder commented
@HarshCasper @Abhijit2505 Please review

2020-08-20 21:32 UTC, mar-galho approved these changes
The code works. I wouldn't mix nextLine and nextInt though; I'd rather receive the int value as a string and parse it - Scanners can get messy when you mix receiving input from texts and numbers in the same instance...

2020-08-22 14:08 UTC, parjanyaacoder commented
@atarax665 @iamrajiv Please review.

2020-08-28 07:24 UTC, HarshCasper requested changes
Make the apt changes required and correct the spell mistakes. Ping me on Slack once you have made these changes.

2020-08-28 07:24 UTC, HarshCasper commented on Java/README.md
> +* [Ceaser Cipher](cryptography/ceaserCipher.java)
Correct the Spelling

2020-08-28 10:29 UTC, merged