Added Next permutation in Python
HarshCasper/NeoAlgo pull request #4447
Opened 2021-03-29 05:43 UTC by NEERAJAP2001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

### Description
This PR adds Next Permutation in python[cp Folder]

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Solves #4230

2021-04-05 13:54 UTC, HarshCasper requested changes

2021-04-05 13:54 UTC, HarshCasper commented on Python/cp/Next_Permutation.py
> +def nenumbertPermutation(array):
Add a beginner friendly description

2021-04-05 14:31 UTC, HarshCasper requested changes

2021-04-05 14:31 UTC, HarshCasper commented on Python/cp/Next_Permutation.py
> +def nextPermutation(array):
Add a beginner friendly description

2021-04-05 14:31 UTC, HarshCasper commented on Python/cp/Next_Permutation.py
> +main()
Enclose in a `if __name__ == '__main__'` block

2021-04-07 14:27 UTC, HarshCasper approved these changes

2021-04-07 14:28 UTC, merged

2021-04-07 14:28 UTC, HarshCasper commented
Hi @NEERAJAP2001 

Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!

2021-04-07 14:32 UTC, NEERAJAP2001 commented
Hey, @HarshCasper Might be a small confusion.
There is an issue associated with this PR: #4230