Added Sum of Matrix's Principal and Secondary Diagonal in CPP
HarshCasper/NeoAlgo pull request #4460
Opened 2021-03-29 07:57 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES.

### Description

Given a N * N square matrix.
Find the sum of it's principal and secondary diagonal elements.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #4458

2021-03-29 13:56 UTC, ankitaggarwal23 requested changes

2021-03-29 13:56 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix's_principal_seconday_diagonal_sum.cpp
> +*/
Add bit more description

2021-03-29 13:56 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/matrix's_principal_seconday_diagonal_sum.cpp
> +int get_principal_secondary_diagonal_sum(int N)
Add a one line function description above the function definition

2021-03-29 14:10 UTC, RaiyanMahin commented
@ankitaggarwal23  I made all the changes.

2021-03-29 14:30 UTC, ankitaggarwal23 approved these changes

2021-03-29 14:38 UTC, merged

2021-04-07 15:04 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!