Identical Words
HarshCasper/NeoAlgo pull request #4487
Opened 2021-03-29 13:04 UTC by Amanduttbhagat

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

- Identical_Words : 
    We will give 3 Strings as input and we will check if it is possible to make 
    second_string and third_string equivalent to first_string by re-arranging characters of
    second_string and third_string any number of times

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4480

2021-03-29 16:10 UTC, Amanduttbhagat commented
@ankitaggarwal23 @HarshCasper @siddharth25pandey 
Can you review this please?

Thank you

2021-03-29 16:42 UTC, siddharth25pandey requested changes
@Amanduttbhagat Do the suggested changes

2021-03-29 16:42 UTC, siddharth25pandey commented on Java/README.md
> +- [Middle Of LinkedList](ds/MiddleOfLinkedList.java)
Remove the Redundant line

2021-03-29 16:42 UTC, siddharth25pandey commented on Java/cp/Identical_Words.java
> +			System.out.println("Not Possible");
Please write complete print message details, What is possible or not possible .

2021-03-30 06:58 UTC, ankitaggarwal23 approved these changes

2021-03-30 06:58 UTC, merged

2021-04-07 15:04 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!