Added largest distance between 2 nodes in a tree
HarshCasper/NeoAlgo pull request #4502
Opened 2021-03-29 13:54 UTC by sg-iitg

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-29 14:20 UTC, sg-iitg commented
@ankitaggarwal23 @HarshCasper 
Please review this Pull Request
Thankyou!

2021-03-31 04:07 UTC, HarshCasper requested changes

2021-03-31 04:07 UTC, HarshCasper commented on C-Plus-Plus/graphs/Largest_distance_between_2_nodes_in_a_tree.cpp
> +//And an adjacency list(adj) can be formed using the given input array(A)
Use Multi-Line Comments

2021-03-31 04:07 UTC, HarshCasper commented on C-Plus-Plus/graphs/Largest_distance_between_2_nodes_in_a_tree.cpp
> +//nd stores the node which is found to be at farthest distance from the source node (node)
Use Multi-Line Comments

2021-03-31 04:07 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Largest distance between 2 nodes of a tree](graphs/Largest_distance_between_2_nodes_in_a_tree.cpp)
Keep it `Tree` instead of `tree`

2021-03-31 06:35 UTC, HarshCasper approved these changes

2021-03-31 06:37 UTC, merged

2021-04-07 15:03 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!