Hamming Distance added under Python
HarshCasper/NeoAlgo pull request #4504
Opened 2021-03-29 14:01 UTC by batul02

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is Hamming Distance Algorithm pull request. This problem is used in many competitive coding exams and interviews. I am a GSSOC'21 participant and it would be really helpful if this pull request is accepted. I have written the problem statement for this and every necessary detail required for it. I have also attached the link to repl.it for this code in the file.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#fixes #4043

2021-03-30 08:45 UTC, ankitaggarwal23 requested changes

2021-03-30 08:45 UTC, ankitaggarwal23 commented on Python/math/Hamming_distance.py
> +Repl.it Link : https://replit.com/@batul02/Hammingdistance#main.py
Remove the repl link

2021-03-30 13:13 UTC, batul02 commented
Changes made as per asked. Please review it again @ankitaggarwal23 .

2021-03-31 08:25 UTC, ankitaggarwal23 approved these changes

2021-03-31 08:25 UTC, merged

2021-04-07 15:03 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!