Union and intersection
HarshCasper/NeoAlgo pull request #4525
Opened 2021-03-29 15:15 UTC by SwarnimaShishodia

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Union and Intersection of array)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#3647)

2021-04-05 14:02 UTC, HarshCasper requested changes
Tiny change. Rest looks good to merge!

2021-04-05 14:02 UTC, HarshCasper commented on C-Plus-Plus/other/Union_and_Intersection_of_arrays.cpp
> +using namespace std;
Add a beginner friendly description

2021-04-05 15:05 UTC, SwarnimaShishodia commented
I have done the changes.

2021-04-05 15:05 UTC, SwarnimaShishodia commented on C-Plus-Plus/other/Union_and_Intersection_of_arrays.cpp
> +using namespace std;
Done

2021-04-05 15:10 UTC, HarshCasper approved these changes

2021-04-05 15:10 UTC, merged

2021-04-07 15:02 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!

2021-04-08 16:16 UTC, SwarnimaShishodia commented
> Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs
> 
> It would be much appreciated. Thanks!

I will do!