JAVA BigInteger (Mathematics)
HarshCasper/NeoAlgo pull request #4532
Opened 2021-03-29 16:14 UTC by RuchiGitHu

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

We have to add and multiply huge numbers! These numbers are so big that you can't contain them in any ordinary data types like a long integer. We will use the power of Java's BigInteger class.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #4391

2021-03-30 12:52 UTC, ankitaggarwal23 requested changes
Why you update two files in READme.md

2021-03-30 12:52 UTC, ankitaggarwal23 commented on Java/math/Big_Integer.java
> +    */
Remove tab space before code.

2021-03-30 12:59 UTC, RuchiGitHu commented
> Why you update two files in READme.md

I will correct it. In my previous file I saw an error(Main method not found in class Big_Integer, please define the main method as: public static void main(String[] args)) that is why I used Constructor to run it. You can review my second file...
Apologize for the inconvenience caused by me...

2021-03-30 13:15 UTC, RuchiGitHu commented
> Why you update two files in READme.md

It's corrected now, please check whenever you want.
Thanks for your reply...

2021-04-01 17:01 UTC, RuchiGitHu commented
> > Why you update two files in READme.md
> 
> It's corrected now, please check whenever you want @ankitaggarwal23 .
> Thanks for your reply...

Please check again if it is possible to anyone...
Thanks for reviewing...

2021-04-03 07:24 UTC, HarshCasper requested changes
We don't need to have language-specific implementations

2021-04-03 07:24 UTC, closed without merging