Add Code For Binary Coded String and update README
HarshCasper/NeoAlgo pull request #4543
Opened 2021-03-29 17:27 UTC by ANUJAGRAWAL2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)

### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#4541
(Write your answer here.)

2021-03-29 17:29 UTC, ANUJAGRAWAL2000 commented
@HarshCasper I created this PR for issue #4541 Please check this one and merged this PR.

2021-03-30 01:43 UTC, iamrajiv requested changes
@ANUJAGRAWAL2000 Add space and time complexity.

2021-03-30 05:37 UTC, ANUJAGRAWAL2000 commented
@iamrajiv and @HarshCasper I have make the requested changes please merge it.

2021-03-30 06:04 UTC, ankitaggarwal23 requested changes

2021-03-30 06:04 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +    }
Remove one tab space

2021-03-30 06:04 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +Output: true
Rewrite it like that as your code produces like that.

![Capture](https://user-images.githubusercontent.com/67387053/112941174-c8a89c00-914b-11eb-8d74-016d67f93cca.JPG)

2021-03-30 06:34 UTC, ankitaggarwal23 requested changes

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +bool hasAllCodes(string s, int k) {
Add a one line description of your function above the function

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +    int X,Y,Z,i;
Don't use single letters for variable use proper naming conventions.

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +        Z=(Z<<1);
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +        Z++;
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +        Z-=(pow(2,k-1));
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +        Z=(Z<<1);
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +        Z++;
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +        return false;
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +int main()
Add a new line above main

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +    cout<<"Yes"<<endl;
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +    cout<<"No"<<endl;
Add a one tab space inside body of condition

2021-03-30 06:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Binary Coded String.cpp
> +*/
Add the new line at the end

2021-03-30 11:19 UTC, ankitaggarwal23 approved these changes

2021-03-30 11:20 UTC, merged

2021-04-07 14:59 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!