Added Reverse_String_Recursion.c and Updated readme.md
HarshCasper/NeoAlgo pull request #4556
Opened 2021-03-29 21:53 UTC by Fab-Gaurav

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Program to input an string to obtain the reversal string and it's length using recursion.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue : https://github.com/TesseractCoding/NeoAlgo/issues/4555

2021-03-30 15:34 UTC, rohanbabbar04 requested changes

2021-03-30 15:34 UTC, rohanbabbar04 commented on C/cp/Reverse_String_Recursion.c
> +	printf("%d\n",length(str));
For the length of the string no need to add another function 
Just use strlen(str)

2021-03-30 15:34 UTC, rohanbabbar04 commented on C/cp/Reverse_String_Recursion.c
> +*/
Add a new line at EOF

2021-03-30 15:34 UTC, rohanbabbar04 commented on C/cp/Reverse_String_Recursion.c
> +*/
Add Time and Space Complexity

2021-04-01 17:04 UTC, HarshCasper approved these changes

2021-04-01 17:05 UTC, merged