Mybranch
HarshCasper/NeoAlgo pull request #4577
Opened 2021-03-30 07:00 UTC by saketbyte

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes I have gone through the documentation.

### Description
Wrote a program as proposed in #4407 with self-explicable comments to understand each line and execution thoroughly and have checked on multiple test cases.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Related to #4407 . Kindly merge if it is up to the required standards or suggest changes if any,

2021-03-31 12:36 UTC, gat786 requested changes

2021-03-31 12:36 UTC, gat786 commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +}
Add a line break {i.e. new line} here

2021-03-31 12:36 UTC, gat786 commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +/*
First of all your title for this pr is `Mybranch` make it something relevant to the code you are writing. 
A suggested different title would be `Buy Sell Stock K Items implemented in cpp`. It just adds so much more context to the pr

2021-03-31 12:45 UTC, gat786 commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +/*
nvm i took care of it

2021-03-31 14:00 UTC, saketbyte commented
Thank you, I shall update accordingly. My apologies for inappropriate pull request name. I might have mistaken it for branch name.

2021-04-03 07:43 UTC, saketbyte commented
I updated the changes requested, kindly update if there are further changes needed or please merge the pull request, it has been 3 days.

2021-04-05 14:04 UTC, HarshCasper requested changes
Can you remove extra lines of code as well?

2021-04-05 14:04 UTC, HarshCasper commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +<<<<<<< HEAD
Seems like these should not be here

2021-04-05 14:04 UTC, HarshCasper commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +>>>>>>> c733b13aa7e4728a5b78f40398b46fb05ceb71ca
Seems like these should not be here

2021-04-08 04:51 UTC, gat786 commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +<<<<<<< HEAD
Yeah these aren't part of actual code

2021-04-08 04:52 UTC, gat786 commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +>>>>>>> c733b13aa7e4728a5b78f40398b46fb05ceb71ca
This seems to be a git conflict residue

2021-04-08 04:52 UTC, gat786 commented
Do the changes as pointed out by Harsh.

2021-04-09 06:48 UTC, ankitaggarwal23 reviewed
Are you still working on it.

2021-04-17 03:57 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-17 03:57 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +#include <iostream>
Remove the iostream header

2021-04-17 03:57 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/buy_sell_stock_k_time.cpp
> +    */
Remove the part

2021-04-19 08:12 UTC, ankitaggarwal23 reviewed
Last Reminder, Are you still working on it.

2021-04-20 10:07 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity. Thank you for your valuable time.😊

2021-04-20 10:07 UTC, closed without merging