Plucking Flowers
HarshCasper/NeoAlgo pull request #4595
Opened 2021-03-30 10:44 UTC by AsthaDad

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Jay's neighbour has a garden in which there are N flowers and each flower has a beauty associated with it i.e. ith flower has B[i] beauty. Jay wants to pluck exactly K flowers from his neighbour's garden such that the sum of beauties of all flowers he plucked is maximum but to not get caught he can't pluck more than one flower in a row, more formally he can't pluck two flowers if they are adjacent.
Your task is to find maximum sum of beauty of all flowers Jay can get.

### Checklist

- [X] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4465

2021-03-31 10:26 UTC, AsthaDad commented
Review this PR  @HarshCasper   @siddharth25pandey

2021-04-02 17:53 UTC, siddharth25pandey requested changes
@AsthaDad Do the minor changes, rest is fine

2021-04-02 17:53 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Plucking_Flowers.cpp
> +        cin >> N >> K;              // size of array and max sum required
Display message in print form as what are you taking input from the user for better UI

2021-04-02 17:53 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Plucking_Flowers.cpp
> +        int N, K;
Use good naming convention

2021-04-02 17:53 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Plucking_Flowers.cpp
> +        vector<int> B(N);
Use good naming convention

2021-04-02 17:53 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Plucking_Flowers.cpp
> +            cin >> B[i];                 // input array
Display message in print form as what are you taking input from the user for better UI

2021-04-02 17:53 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Plucking_Flowers.cpp
> +        cout << ans << endl;
Display message in print form as what are you showing output to the user for better UI

2021-04-02 18:41 UTC, siddharth25pandey requested changes

2021-04-02 18:41 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Plucking_Flowers.cpp
> +
Sample I/O is **not matching** with the execution of the Program

2021-04-02 18:53 UTC, siddharth25pandey approved these changes
@AsthaDad LGTM 💯 Able to merge

2021-04-02 18:53 UTC, merged

2021-04-02 18:54 UTC, siddharth25pandey commented
@all-contributors please add @AsthaDad for her code