#406 find_num_of_digits_in_int.cpp hakincodes
HarshCasper/NeoAlgo pull request #460
Opened 2020-08-16 10:23 UTC by sukritidawar

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added the solution in cp folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-17 08:37 UTC, sukritidawar commented
@HarshCasper @Kajol-Kumari please review.

2020-08-17 08:45 UTC, Kajol-Kumari requested changes
Please incorporate the suggested changes, Rest LGTM :)

2020-08-17 08:45 UTC, Kajol-Kumari commented on C-Plus-Plus/cp/find_no_of_digits_in_int.cpp
> +    //cout << num_of_digits(num) << endl;                 //Normal approach
@sukritidawar Please uncomment this line and add two `cout` statements for each of normal and recursive approach.

2020-08-17 17:14 UTC, Kajol-Kumari approved these changes
LGTM :) @sukritidawar please resolve the conflicts and it will be good to go!

2020-08-17 17:25 UTC, sukritidawar commented
> LGTM :) @sukritidawar please resolve the conflicts and it will be good to go!

Done!

2020-08-18 05:20 UTC, vatsalkesarwani12 approved these changes
code looks good to me

2020-08-18 13:42 UTC, Abhijit2505 requested changes
Code is good, I want you to add two more methods which can reduce the lines of code as well,

1 - Convert the number to a string, count the length of string using C++ functionality, two lines of code. While coding in any language try to use the language-specific desserts as well because that's important.

2 - Try something using Step function and Log Function. Hint - what happens if we add step function to the logarithm of a number with base 10? Is there any relation possible?

Do work on it and let me know.

2020-08-19 03:06 UTC, sukritidawar commented
> Code is good, I want you to add two more methods which can reduce the lines of code as well,
> 
> 1 - Convert the number to a string, count the length of string using C++ functionality, two lines of code. While coding in any language try to use the language-specific desserts as well because that's important.
> 
> 2 - Try something using Step function and Log Function. Hint - what happens if we add step function to the logarithm of a number with base 10? Is there any relation possible?
> 
> Do work on it and let me know.

Done

2020-08-20 16:04 UTC, iamrajiv commented
@sukritidawar, please resolve merge conflicts.

2020-08-20 16:09 UTC, sukritidawar commented
> @sukritidawar, please resolve merge conflicts.

resolved

2020-08-20 16:14 UTC, iamrajiv commented
@sukritidawar LGTM!

2020-08-20 16:14 UTC, iamrajiv approved these changes

2020-08-20 16:14 UTC, merged

2020-08-23 17:25 UTC, iamrajiv commented
@all-contributors please add @sukritidawar for code