added level order traversal of binary tree
HarshCasper/NeoAlgo pull request #4612
Opened 2021-03-30 14:27 UTC by Khushboo85277

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

->>Added C++ code for level order traversal of binary tree. 
->>Constructed binary tree using stack and used queue for printing level order traversal of the binary tree. 
Fixes#4591

### Checklist

- [* ] I've read the contribution guidelines.
- [* ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixed issue num #4591

2021-04-01 14:52 UTC, HarshCasper requested changes
Few more changes: 

- Use Comments above the Line of Code not beside it
- Format and Indent the Code properly

2021-04-01 14:52 UTC, HarshCasper commented on C-Plus-Plus/ds/LevelOrderTraversal_BinaryTree.cpp
> +
Remove all these extra lines

2021-04-01 14:52 UTC, HarshCasper commented on C-Plus-Plus/ds/LevelOrderTraversal_BinaryTree.cpp
> +// 30 70
Use Multi-Line Comments

2021-04-01 14:52 UTC, HarshCasper commented on C-Plus-Plus/ds/LevelOrderTraversal_BinaryTree.cpp
> +int arr[]={50,25,12,-1,-1,37,30,-1,-1,-1,75,62,-1,70,-1,-1,87,-1,-1};
Use dynamic input

2021-04-01 14:54 UTC, Khushboo85277 commented
Ok I will make all the requested changes.
Thank you

2021-04-04 15:46 UTC, ankitaggarwal23 reviewed
Issue already available #3408

2021-04-04 15:46 UTC, closed without merging