Added flight of stairs in js
HarshCasper/NeoAlgo pull request #4613
Opened 2021-03-30 14:27 UTC by FireQueen-3010

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

The flight of stairs problem using dp in Javascript

Given two positive integers : n and k. We are currently at stair 0, and want to climb to stair n. We can either climb 1, 2 or 3 stairs at a time, but we can climb 3 stairs only k times. Return the number of ways to climb to the nth stair.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4223 (javascript)

2021-03-30 14:28 UTC, FireQueen-3010 commented
Please review @ankitaggarwal23 @HarshCasper

2021-03-30 14:38 UTC, ankitaggarwal23 requested changes

2021-03-30 14:38 UTC, ankitaggarwal23 commented on JavaScript/dp/flightOfStairs.js
> +7
Use proper display message for I/P and O/P and also I checked your code is not displaying output cross check once.

2021-03-30 14:38 UTC, ankitaggarwal23 commented on JavaScript/dp/flightOfStairs.js
> +*/
Add a new line at the end

2021-03-30 14:47 UTC, FireQueen-3010 commented
Done with the changes, also regarding the output, since I had to make the input dynamic, in javascript dynamic input works only if parsed using html. For others, who implemented dynamic input using javascript also its the same thing. Please review :) @ankitaggarwal23 @HarshCasper

2021-04-01 15:29 UTC, HarshCasper requested changes

2021-04-01 15:29 UTC, HarshCasper commented on JavaScript/dp/flightOfStairs.js
> +let K=prompt("Enter value of k:");
Don't use prompt for taking user input. We are accepting only Node implementations. There are various implementations available in the Javascript directory that can help you to implement this

2021-04-03 05:49 UTC, FireQueen-3010 commented
Done with the requested changes, please review :) @HarshCasper @ankitaggarwal23 
![image](https://user-images.githubusercontent.com/59244300/113469843-6cf15200-946e-11eb-9612-b30badb70e08.png)

2021-04-04 13:24 UTC, ankitaggarwal23 approved these changes

2021-04-04 13:24 UTC, merged