Sg iitg patch 1
HarshCasper/NeoAlgo pull request #4618
Opened 2021-03-30 15:03 UTC by sg-iitg

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for Odd even linked list problem
The Program is used to rearrange a given linked list so that all odd indexed nodes are arranged first, followed by the even indexed nodes in one iteration through the linked list

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-03-30 15:09 UTC, sg-iitg commented
@ankitaggarwal23 @HarshCasper @siddharth25pandey 
Please review this pull request
Thankyou!

2021-03-31 04:10 UTC, HarshCasper requested changes

2021-03-31 04:10 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Largest distance between 2 nodes of a tree](graphs/Largest_distance_between_2_nodes_in_a_tree.cpp)
Please revert this change. Its part of a separate PR

2021-03-31 04:10 UTC, HarshCasper commented on C-Plus-Plus/other/odd_even_linked_list.cpp
> +    co->next= head_even;
Format the Code here

2021-03-31 04:10 UTC, HarshCasper commented on C-Plus-Plus/other/odd_even_linked_list.cpp
> +    int n;
Can you use more meaningful variable name?

2021-03-31 04:10 UTC, HarshCasper commented on C-Plus-Plus/other/odd_even_linked_list.cpp
> +    int x;
Can you use more meaningful variable name?

2021-03-31 06:34 UTC, HarshCasper approved these changes

2021-03-31 06:34 UTC, merged