Branch1
HarshCasper/NeoAlgo pull request #463
Opened 2020-08-16 10:43 UTC by Joshitha18

Fix #438
 Added longest_common_subsequence.cpp

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added DP solution in C++ for Longest common subsequence

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
issue #438

2020-08-19 05:22 UTC, Joshitha18 commented
@Abhijit2505 @iamrajiv @atarax665 can you review this pr?

2020-08-19 18:46 UTC, iamrajiv requested changes
@Joshitha18 remove unnecessary lines and format the comments with proper spacings. Also, add time and space complexity for this space-optimized DP solution.

2020-08-19 18:46 UTC, iamrajiv commented on C-Plus-Plus/dp/longest_common_subsequence.cpp
> +// input=
@Joshitha18 use C++ Multi-line Comments for multiple lines. Something like this 
```
/* 
...
*/
```

2020-08-20 14:34 UTC, Joshitha18 commented
@iamrajiv Added requested changes

2020-08-20 14:44 UTC, iamrajiv requested changes

2020-08-20 14:44 UTC, iamrajiv commented on C-Plus-Plus/dp/longest_common_subsequence.cpp
> +// Time and Space complexity : O(mn)
@Joshitha18 specify m and n something like this `O(mn), where m = length of string1 and n = length of string2` this will increase the readability.

2020-08-21 09:17 UTC, Joshitha18 commented
@iamrajiv done!

2020-08-21 09:46 UTC, iamrajiv approved these changes
@Joshitha18 LGTM!

2020-08-22 10:30 UTC, Joshitha18 commented
@atarax665 @Abhijit2505 @Kajol-Kumari Please review this

2020-08-23 02:33 UTC, Abhijit2505 requested changes
Please make the required changes. Everything else looks good to me.

2020-08-23 02:33 UTC, Abhijit2505 commented on C-Plus-Plus/dp/longest_common_subsequence.cpp
> +    char str1[100],str2[100];
I would like you to use the builtin **string** class instead of char array in C++.
We must use the full potential of the programming language while using it, particularly in object-oriented languages like C++ etc.

2020-08-23 02:33 UTC, Abhijit2505 commented on C-Plus-Plus/dp/longest_common_subsequence.cpp
> +{
Give this function a proper name. Naming is an important aspect of writing clean code. For example, you can name it as `int lowest_common_substring(){  ....  }`.

2020-08-23 02:33 UTC, Abhijit2505 commented on C-Plus-Plus/dp/longest_common_subsequence.cpp
> +    int n=strlen(y);
Give these length variables a good name like `len_x` & `len_y`.

Remember one thing, using short variable names is good for competitions, but not at all suitable for any software building or things like **open-source contribution**. Because in open-source, other developers need to read and understand your code.

So if you write clean code means the development process will be faster.

2020-08-23 02:33 UTC, Abhijit2505 commented on C-Plus-Plus/dp/longest_common_subsequence.cpp
> +
Make this array dynamic and based on dynamic memory allocation. In C++ it can be done by, 
`int* dynamic_arr = new int[size];`

2020-08-24 09:14 UTC, Joshitha18 commented
@Abhijit2505 Added requested changes

2020-08-26 12:16 UTC, Joshitha18 commented
@Abhijit2505 please review this

2020-08-26 15:02 UTC, Abhijit2505 approved these changes
LGTM

2020-08-26 15:03 UTC, Abhijit2505 commented
@HarshCasper @ricardoprins , Please merge the PR guys.

2020-08-26 15:09 UTC, merged

2020-08-26 15:13 UTC, iamrajiv commented
@all-contributors please add @Joshitha18 for code

2020-08-26 15:28 UTC, iamrajiv commented
@all-contributors please add @Joshitha18 for code