Added code for checking if a linked list is palindromic or not
HarshCasper/NeoAlgo pull request #4632
Opened 2021-03-30 17:02 UTC by SAY-droid427

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added code for checking if a linked list is palindromic or not in C++.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-01 15:12 UTC, HarshCasper requested changes

2021-04-01 15:12 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Checking if a lonked list is palindromic or not](stack/palindromic_list.cpp)
It should be `linked`

2021-04-01 15:12 UTC, HarshCasper commented on C-Plus-Plus/stack/palindromic_list.cpp
> +    push(&head, 1);
Use dynamic input here

2021-04-09 06:52 UTC, ankitaggarwal23 reviewed
Closing due to inactivity.

2021-04-09 06:52 UTC, closed without merging