Pshivesh8
HarshCasper/NeoAlgo pull request #4634
Opened 2021-03-30 17:10 UTC by pshivesh8

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Searching in BST

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #4629

2021-04-01 19:39 UTC, siddharth25pandey commented
@pshivesh8 Resolve the merge conflicts

2021-04-02 05:36 UTC, pshivesh8 commented
@siddharth25pandey  please tell me what is the conflict in merging.

2021-04-02 06:28 UTC, siddharth25pandey commented
> @siddharth25pandey please tell me what is the conflict in merging?

@pshivesh8 The Conflicting file is **README.md** . It had arised when Git wasn't able to locate the **branch** where to push the changes. You can easily see the conflict by introspecting the **README** file you have commited

2021-04-02 08:05 UTC, pshivesh8 commented
@siddharth25pandey , I have resolved the conflict in README.md.
Please review

2021-04-02 12:14 UTC, siddharth25pandey requested changes
@pshivesh8 Do the suggested changes

2021-04-02 12:14 UTC, siddharth25pandey commented on C-Plus-Plus/ds/Searching_in_BST.cpp
> +#include<iostream>
Use **bits/stdc++**

2021-04-02 12:14 UTC, siddharth25pandey commented on C-Plus-Plus/ds/Searching_in_BST.cpp
> +	cin >> data;
Display a message in print form as what are you taking input from the user, for better UI

2021-04-02 12:14 UTC, siddharth25pandey commented on C-Plus-Plus/ds/Searching_in_BST.cpp
> +	cin >> ele;
Display a message in print form as what are you taking input from the user, for better UI

2021-04-02 12:14 UTC, siddharth25pandey commented on C-Plus-Plus/ds/Searching_in_BST.cpp
> +	int ele;
Write a good naming convention

2021-04-02 12:14 UTC, siddharth25pandey commented on C-Plus-Plus/ds/Searching_in_BST.cpp
> +    cout << boolalpha << search(root, ele);
Display a message in print form as what are you showing output to the user, for better UI

2021-04-02 12:14 UTC, siddharth25pandey commented on C-Plus-Plus/ds/Searching_in_BST.cpp
> +
Remove the blank lines

2021-04-02 18:35 UTC, pshivesh8 commented
@siddharth25pandey  I have resolved all those issues.
Please review

2021-04-03 14:35 UTC, siddharth25pandey requested changes

2021-04-03 14:35 UTC, siddharth25pandey commented on C-Plus-Plus/ds/Searching_in_BST.cpp
> +
Sample I/O is **not matching** with the execution of the Program

2021-04-04 08:14 UTC, pshivesh8 commented
@siddharth25pandey , Please review
The code is working perfectly fine,  and I have attached the reference too :
### Note:  **You have to enter -1, at last, to stop inserting new nodes.**

![image](https://user-images.githubusercontent.com/53203340/113502649-3e957480-954b-11eb-942f-db15126b72e1.png)

2021-04-04 08:21 UTC, pshivesh8 commented
@siddharth25pandey  , I have updated the test cases too, Please review

2021-04-04 13:12 UTC, siddharth25pandey approved these changes
@pshivesh8 LGTM 💯 Able to merge

2021-04-04 13:12 UTC, merged

2021-04-04 13:13 UTC, siddharth25pandey commented
@all-contributors please add @pshivesh8 for his code

2021-04-04 14:47 UTC, pshivesh8 commented
Thanks, @siddharth25pandey for guiding me  🎉🎉