Ishita1608 euler's totient function in java
HarshCasper/NeoAlgo pull request #464
Opened 2020-08-16 10:49 UTC by Ishita1608

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

I add Solution of Euler's totient function in java

### Checklist

- [✔ ] I've read the contribution guidelines.
- [✔ ] I've checked the issue list before deciding what to submit.
- [✔ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This is the solution of the issue no #445

2020-08-18 16:54 UTC, siddharth25pandey approved these changes
@Ishita1608 looks fine to me
Able to merge.
Thanks!

2020-08-19 07:07 UTC, plazzy99 requested changes
https://www.geeksforgeeks.org/eulers-totient-function/

Code copied

2020-08-19 07:07 UTC, plazzy99 commented on Java/cp/Euler.java
> +static int phi(int n)
make a practice of naming the function with some logical name

2020-08-19 07:07 UTC, plazzy99 commented on Java/cp/Euler.java
> +public static void main (String[] args)
correct the indentation

2020-08-19 07:07 UTC, closed without merging