4602issue heap
HarshCasper/NeoAlgo pull request #4645
Opened 2021-03-30 18:32 UTC by reerajput930

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

contributed by creating code for the formation of max-heap in the C++ section.

2021-03-30 18:43 UTC, reerajput930 commented
sir @HarshCasper, @siddharth25pandey, @bhav09, @ArchanGhosh,@ankitaggarwal23 
I have made the PR,
my file can be tested

2021-03-30 19:29 UTC, iamrajiv requested changes
@reerajput930 Do not edit `.deepsource.toml` file. Please update the readme file. Also, provide the issue number.

2021-03-31 03:53 UTC, HarshCasper requested changes

2021-03-31 03:53 UTC, HarshCasper commented on .deepsource.toml
> +  import_paths = ["github.com/reerajput930/NeoAlgo"]
Why did you change this? Please don't do it.

2021-03-31 03:53 UTC, HarshCasper commented on C-Plus-Plus/heap/max_heap.cpp
> +    int r = ((2 * i) + 2); //formula to access right child of parent node
Don't use comments beside the line of code, but above it.

2021-03-31 03:53 UTC, HarshCasper commented on C-Plus-Plus/heap/max_heap.cpp
> +    //first check if left child exit
Use Multi-Line Comments

2021-03-31 03:53 UTC, HarshCasper commented on C-Plus-Plus/heap/max_heap.cpp
> +    //first check if right child exit
Use Multi-Line Comments

2021-03-31 03:53 UTC, HarshCasper commented on C-Plus-Plus/heap/max_heap.cpp
> +    int array[] = {4, 56, 2, 3, 7, 8};        // array
Don't use static input. Use dynamic input instead

2021-03-31 04:15 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/heap-sort/).

2021-03-31 04:15 UTC, closed without merging

2021-03-31 04:33 UTC, reerajput930 commented
@ankitaggarwal23 don't close it, The solution of this problem is unique, we can't make a different solution to this problem.
plz try to understand.