Tiling Problem 2XN
HarshCasper/NeoAlgo pull request #4648
Opened 2021-03-30 20:38 UTC by yashmita

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added the code for tiling problem using C language. The problem is to find the number of ways in which the floor of size 2XN can be tiled using tiles of size 2X1. 

### Checklist

- [ ] I've read the contribution guidelines. Yes
- [ ] I've checked the issue list before deciding what to submit. Yes
- [ ] I've edited the `README.md` and link to my code. Yes

## Related Issues or Pull Requests

This is the PR for issue #4430

2021-04-02 17:31 UTC, HarshCasper requested changes

2021-04-02 17:31 UTC, HarshCasper commented on C/dp/tiling_problem.c
> +	//An array, tiles of size n+1 which stores the no. of ways in which the floor of size 2Xi can be tiled
Use comments when necessary

2021-04-02 17:31 UTC, HarshCasper commented on C/dp/tiling_problem.c
> +	//function call to NoOfWays
Use comments when necessary

2021-04-02 17:31 UTC, HarshCasper commented on C/dp/tiling_problem.c
> +	//user input for value of n
Use comments when necessary

2021-04-02 17:31 UTC, HarshCasper commented on C/dp/tiling_problem.c
> +Output: 21
Remove these

2021-04-02 17:38 UTC, yashmita commented
I have updated the changes as requested. Kindly have a look at it.

2021-04-04 13:18 UTC, HarshCasper approved these changes

2021-04-04 13:23 UTC, merged