Maximum Topology Short in C++
HarshCasper/NeoAlgo pull request #4654
Opened 2021-03-31 01:52 UTC by codeakki

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Maximum Topology Short in C++

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4389

2021-04-09 06:54 UTC, ankitaggarwal23 reviewed
Closing due to inactivity.

2021-04-09 10:33 UTC, HarshCasper requested changes

2021-04-09 10:33 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Maximum Topology Short ] (cp/Max_Topology_short.cpp)
Fix the hyperlink here

2021-04-09 10:33 UTC, HarshCasper commented on C-Plus-Plus/cp/Max_Topology_short.cpp
> +/*To Include All Pre Required Liabries*/
Give a description of the algorithm. Share the examples at the bottom

2021-04-09 10:33 UTC, HarshCasper commented on C-Plus-Plus/cp/Max_Topology_short.cpp
> +4 2 */
Add a new line at the EOF

2021-04-09 10:33 UTC, HarshCasper commented on C-Plus-Plus/cp/Max_Topology_short.cpp
> +int f_a_c_t[Limit + 1];
Use meaningful variable names. Not just here bu throughout the code

2021-04-11 16:11 UTC, ankitaggarwal23 reviewed
Found same PR opened by you. Closing this as of now.

2021-04-11 16:12 UTC, closed without merging