Stack problem
HarshCasper/NeoAlgo pull request #4676
Opened 2021-03-31 06:04 UTC by reerajput930

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4671

2021-03-31 06:08 UTC, reerajput930 commented
sir @HarshCasper, @siddharth25pandey, @bhav09, @ArchanGhosh,@ankitaggarwal23
I have made the PR,
my file can be tested

2021-03-31 06:23 UTC, HarshCasper requested changes

2021-03-31 06:23 UTC, HarshCasper commented on .deepsource.toml
> -  environment = ["nodejs"]
Why are you making these changes?

2021-03-31 06:23 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [check if string is palindrome with stack](cp/check_palindrome.cpp)
Write `Check if the String is a palindrome using Stack`

2021-03-31 06:23 UTC, HarshCasper commented on C-Plus-Plus/stack/check_palindrome.cpp
> +*/
Add a new line at the EOF

2021-03-31 06:26 UTC, reerajput930 commented on .deepsource.toml
> -  environment = ["nodejs"]
I Myself don't know, plz help.

2021-03-31 06:50 UTC, reerajput930 commented
@HarshCasper I have committed as per your requested changes.
@ ankitaggarwal23 plz review it.

2021-04-01 15:26 UTC, HarshCasper commented
> @HarshCasper I have committed as per your requested changes.
> @ankitaggarwal23 plz review it.

You have deleted the whole DeepSource TOML file. Please don't do that or else we would need to close the PR.

2021-04-09 06:55 UTC, ankitaggarwal23 reviewed
Are you still working on it.

2021-04-17 03:58 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity since last 21 days. Thank you for your valuable time.😊

2021-04-17 03:59 UTC, closed without merging