Add Code For ReconstructOriginalDigitsFromEnglish.cpp and Update README
HarshCasper/NeoAlgo pull request #4711
Opened 2021-03-31 08:15 UTC by ANUJAGRAWAL2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)
I have add the code, description, time and space complexity, input/output sample for ReconstructOriginalDigitsFromEnglish.cpp.
### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#4707

2021-03-31 08:16 UTC, ANUJAGRAWAL2000 commented
@HarshCasper I have created the PR for the assigned issue. Please check this and merge.

2021-04-01 07:32 UTC, ANUJAGRAWAL2000 commented
@ankitaggarwal23 Please check this one and suggest me changes and merge!.

2021-04-02 06:11 UTC, HarshCasper requested changes
Few changes: 

- Use meaningful variable names
- Indent and format the code aptly

2021-04-05 13:48 UTC, HarshCasper approved these changes

2021-04-05 13:48 UTC, merged