Create PancakeSort.cpp
HarshCasper/NeoAlgo pull request #473
Opened 2020-08-16 14:19 UTC by kashika3101

Implemented a sorting technique colloquial for mathematical problem for sorting a disorder of pancakes in order of size.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

An important sorting technique using flip operation analogous to flipping pancakes.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#254

2020-08-21 16:15 UTC, kashika3101 commented
please review @atarax665

2020-08-29 17:00 UTC, atarax665 requested changes

2020-08-29 17:00 UTC, atarax665 commented on C-Plus-Plus/ds/PancakeSort.cpp
> +#include <iostream>
```suggestion

```
No need of adding iostream as its already included in bits/stdc++ .

2020-08-29 17:00 UTC, atarax665 commented on C-Plus-Plus/ds/PancakeSort.cpp
> +}
Add sample input/output, space and time complexity in commented form.

2020-08-29 17:00 UTC, atarax665 commented on C-Plus-Plus/ds/PancakeSort.cpp
> +#include<bits/stdc++.h>
Add description of Pancake Sort in commented form at the top.

2020-08-29 17:00 UTC, atarax665 commented
Make appropriate changes to README.md file of C++ folder.

2020-10-01 09:53 UTC, closed without merging