Added Sum Of Divisors in CPP
HarshCasper/NeoAlgo pull request #4733
Opened 2021-03-31 09:59 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Given a Number. Find it's Number of Divisors.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #4730

2021-03-31 10:21 UTC, ankitaggarwal23 requested changes

2021-03-31 10:21 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/sum_of_divisors.cpp
> +             */
Remove the redundant comments

2021-03-31 10:21 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/sum_of_divisors.cpp
> +    if(Number % limit == 0)
Add the new line above the if condition

2021-03-31 10:21 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/sum_of_divisors.cpp
> +            */
Remove the redundant comments

2021-03-31 10:21 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/sum_of_divisors.cpp
> +            */
Remove the redundant comments

2021-03-31 10:21 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/sum_of_divisors.cpp
> +	cout << sum_of_divisors_of_the_number << endl;
Align your code properly also `sum_of_divisors_of_the_number` rename this to `sum_of_divisors`

2021-03-31 10:33 UTC, RaiyanMahin commented
all done!

2021-03-31 13:42 UTC, ankitaggarwal23 approved these changes

2021-03-31 13:43 UTC, merged

2021-04-07 14:57 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!