Implemented KMP Algorithm in Python
HarshCasper/NeoAlgo pull request #475
Opened 2020-08-16 14:32 UTC by anubhvshrma18

KMP Algorithm in Python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Algorithm used for searching a pattern/string in a another text/string using an array of prefixes and suffixes. It overrides the Naive algorithm and improves the worst case to O(n).

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

 #427

2020-08-20 21:49 UTC, anubhvshrma18 commented
Please review @HarshCasper  @Kajol-Kumari

2020-08-21 07:44 UTC, Kajol-Kumari requested changes
Hey @anubhvshrma18 the `readme.md` is showing many unnecessary lines change, if possible please revert back the `readme.md` changes and just modify the line where you need to add you code path.
Functionality is working fine! Please incorporated the suggested changes and it will be goofd to go :)

2020-08-21 07:44 UTC, Kajol-Kumari commented on Python/cp/KMP_Algorithm.py
> +# Pattern found at 21
please add one extra blank line here.

2020-08-21 07:44 UTC, Kajol-Kumari commented on Python/cp/KMP_Algorithm.py
> +text = "aaanunaanuaunnanuubhanu"
please comment these static input. i.e line 52 to 54.

2020-08-21 07:44 UTC, Kajol-Kumari commented on Python/cp/KMP_Algorithm.py
> +# text =input()
please uncomment lines 47-49 and show a message like `please enter the input string` and `please enter the string to be searched` respectively in the both input statements.

2020-08-21 08:43 UTC, anubhvshrma18 commented
@Kajol-Kumari Updated all the changes as per requested . Please review and if anything more is to be changed please remind me, i will do that too.

2020-08-21 12:21 UTC, Kajol-Kumari requested changes
Hey @anubhvshrma18 please resolve the conflicts. And i can see many changes in readme can u please reset head only for `readme.md` and then add your code path in there? 

You can use `git checkout origin/master readme.md` for undoing the `readme.md` changes

2020-08-22 15:10 UTC, vatsalkesarwani12 approved these changes
LGTM 👍

2020-08-22 18:24 UTC, Kajol-Kumari approved these changes
LGTM :)

2020-08-23 09:45 UTC, merged

2020-08-23 17:27 UTC, iamrajiv commented
@all-contributors please add @anubhvshrma18 for code