median of the two sorted arrays
HarshCasper/NeoAlgo pull request #4803
Opened 2021-03-31 18:06 UTC by Amit366

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

## Related Issues or Pull Requests

Fixes: #4787

2021-04-01 04:16 UTC, Amit366 commented
@HarshCasper please review this PR.

2021-04-01 15:38 UTC, HarshCasper requested changes
Few changes: 

- Make Markdown changes 
- Don't use prompts
- Don't put the code in `Miscellaneous`. We will delete it soon. Put it in JS

2021-04-01 15:40 UTC, Amit366 commented
@HarshCasper should I take input ?? 
And also what is markdown changes??

2021-04-01 16:39 UTC, Amit366 commented
@HarshCasper please check it now

2021-04-02 17:11 UTC, HarshCasper requested changes

2021-04-02 17:11 UTC, HarshCasper commented on JavaScript/cp/Median_of_Two_Sorted_Arrays.js
> +2.00000
I don't think that the I/O format is proper

2021-04-02 17:11 UTC, HarshCasper commented on JavaScript/cp/Median_of_Two_Sorted_Arrays.js
> +  let nums3 = nums1.concat(nums2).sort(function(a, b){return a-b});
Use meaningful variable names

2021-04-02 17:39 UTC, Amit366 commented
@HarshCasper I am closing this as I lost this branch on my vscode. I have created a new PR .please check that

2021-04-02 17:39 UTC, closed without merging