Greedy Algorithm (Activity Selection) in JAVA with link attached in Readme file
HarshCasper/NeoAlgo pull request #482
Opened 2020-08-16 15:33 UTC by shobhu98

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-19 16:18 UTC, shobhu98 commented
Waiting for the maintainers to merge the request

2020-08-21 19:59 UTC, siddharth25pandey approved these changes
@shobhu98 Looks fine to me
Able to merge.
Thanks!

2020-08-22 07:05 UTC, Kajol-Kumari requested changes
@shobhu98 I can see a lot of empty white spaces in the code. Please use some code formatting tool to format your code. Rest looks good!

2020-08-22 07:05 UTC, Kajol-Kumari commented on Java/Greedy_Algorithms/Active_Selection.java
> +}
please prove one extra blank line at the end of the file.

2020-08-22 08:08 UTC, shobhu98 commented on Java/Greedy_Algorithms/Active_Selection.java
> +}
Done. I removed those extra spaces .

2020-08-22 13:30 UTC, shobhu98 commented
I have removed the spaces I guess you are good to go.

2020-08-24 04:46 UTC, SKAUL05 approved these changes

2020-08-26 07:58 UTC, shobhu98 commented
Waiting for the maintainers to merge the request.

2020-08-26 07:59 UTC, shobhu98 commented
It is now more than 10 days. I have done some more work waiting dor this request to merge first

2020-08-27 09:07 UTC, merged