3 Cycle
HarshCasper/NeoAlgo pull request #4821
Opened 2021-04-01 05:39 UTC by ishwari20

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given a graph with N vertices (numbered from 0 to N-1) and M undirected edges, then count the distinct 3-cycles in the graph. A 3-cycle PQR is a cycle in which (P,Q), (Q,R) and (R,P) are connected by an edge.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #4820

2021-04-01 17:36 UTC, ankitaggarwal23 requested changes
Shift your code to some other function and use main for driver code.

2021-04-06 14:30 UTC, siddharth25pandey requested changes
@ishwari20 Do the requested changes

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/README.md
> -- [Binary tree using stack (iterative method to construct tree)](ds/BinaryTreeUsingStack.cpp)
Add the unnecessary deleted lines

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/graphs/3Cycle.cpp
> +#include <iostream>
Use **#include<bits/stdc++.h>**

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/graphs/3Cycle.cpp
> +    int V,E;
Use good naming convention

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/graphs/3Cycle.cpp
> +    cin>>V>>E;
Display message in Print form as what are you taking input from the user

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/graphs/3Cycle.cpp
> +        cin>>f>>s;
Display message in Print form as what are you taking input from the user

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/graphs/3Cycle.cpp
> +        int f,s;
Use good naming convention

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/graphs/3Cycle.cpp
> +    count(V, edges);
Display message in Print form as what are you showing output to the user

2021-04-06 14:30 UTC, siddharth25pandey commented on C-Plus-Plus/graphs/3Cycle.cpp
> +Time Complexity: O(V+E)
Also, include Space Complexity

2021-04-07 13:24 UTC, closed without merging