euler's totient function in python
HarshCasper/NeoAlgo pull request #487
Opened 2020-08-16 17:15 UTC by ag278

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have created Euler's_Totient_Function.cpp file in python folder and I have updated readme file.

### Checklist

- [✓ ] I've read the contribution guidelines.
- [✓ ] I've checked the issue list before deciding what to submit.
- [✓ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-17 17:09 UTC, atarax665 requested changes

2020-08-17 17:09 UTC, atarax665 commented on Python/README.md
> +* [Euler’s Totient Function](euler_totient_function.py)
It should be **(math/euler_totient_function.py)**

2020-08-17 17:36 UTC, atarax665 requested changes

2020-08-17 17:36 UTC, atarax665 commented on Python/math/euler_totient_function.py
> +    ans=q   #defining the answer initially to n
The function give wrong answer for various sample cases. ex- 4, 6, 9 etc. Please check the algorithm used once again.

2020-08-17 17:36 UTC, atarax665 commented on Python/math/euler_totient_function.py
> +    euler_totient(n)
Add sample input/output in the end.

2020-08-17 17:36 UTC, atarax665 commented on Python/math/euler_totient_function.py
> +    if (q>1):              #this case ensures that if n have a prime factor greater than sqrt(n) then we are counting thaat case
Refer to [PEP 8](https://www.python.org/dev/peps/pep-0008/) to improve the readability of your code.

2020-08-17 18:14 UTC, ag278 commented
Sir, actually I have noticed that there is a problem in the statement of the issue. I just check the name of the topic and since many of the people are commenting at that time i only notice the topic name and not the statement . Actually F(n) denotes the number of coprimes of n from 1 to n. Example F(4) denotes number of coprimes of 4 from 1 to 4, so F(4)=2 as only 1 & 3 are coprimes to 4. Actually I have written the code for  euler's totient function and not for the number of coprime number between 1 and n( as mentiones in the problem statement). So what should I do now?

2020-08-17 18:32 UTC, atarax665 commented
> Sir, actually I have noticed that there is a problem in the statement of the issue. I just check the name of the topic and since many of the people are commenting at that time i only notice the topic name and not the statement . Actually F(n) denotes the number of coprimes of n from 1 to n. Example F(4) denotes number of coprimes of 4 from 1 to 4, so F(4)=2 as only 1 & 3 are coprimes to 4. Actually I have written the code for euler's totient function and not for the number of coprime number between 1 and n( as mentiones in the problem statement). So what should I do now?

As this PR is to be merged under #445 I will suggest you to write a new function to count the number of coprime between 1 to n. You can refer to [euler's totient function](https://www.geeksforgeeks.org/eulers-totient-function/) .

2020-08-18 09:44 UTC, ag278 commented
@atarax665  i have made the changes in the file. Now the function euler_totient (n) calculates the no. of coprimes between 1 and n (inclusive of 1 and n).Please review it and if it is ok please let me know

2020-08-19 19:52 UTC, atarax665 commented
> @atarax665 i have made the changes in the file. Now the function euler_totient (n) calculates the no. of coprimes between 1 and n (inclusive of 1 and n).Please review it and if it is ok please let me know
> Hakincode2020

You had to calculate the no. of coprimes of n between 1 and n (both exclusive). Your previous code was giving wrong answer for various inputs.
![euler](https://user-images.githubusercontent.com/29673671/90682893-530a5280-e283-11ea-9d5a-95f9bfca5b55.PNG)
 For input = 6 the program should return 2 as the only gcd(1, 6) =1 and gcd(5, 6)=1.

2020-08-19 19:55 UTC, atarax665 requested changes

2020-08-19 19:55 UTC, atarax665 commented on Python/math/euler_totient_function.py
> +print("Enter number of elements : ")
Change print statement to print('Enter a number : ')

2020-08-20 16:58 UTC, ag278 commented
@atarax665 please verify it once.

2020-08-20 19:39 UTC, atarax665 requested changes

2020-08-20 19:39 UTC, atarax665 commented on Python/math/euler_totient_function.py
> +def euler_totient(q):
Add docstring to make the code look well documented and add space before and after operators.

2020-08-20 19:54 UTC, ag278 commented
@atarax665 i have made the required changes. Please verify it once

2020-08-21 02:07 UTC, atarax665 approved these changes

2020-08-21 02:07 UTC, atarax665 commented on Python/math/euler_totient_function.py
> +here we are considering (2,3) and (3,2) as same pair
Remove this line. Its redundant now. Everything else looks fine. :)

2020-08-21 03:28 UTC, SKAUL05 requested changes
Use meaningful variable names instead of alphabets

2020-08-21 03:43 UTC, ag278 commented
@SKAUL05  i have made the required changes. Please verify it once

2020-08-21 04:07 UTC, SKAUL05 requested changes

2020-08-21 04:07 UTC, SKAUL05 commented on Python/math/euler_totient_function.py
> +    Arr=[]
Change to arr ( lower case )

2020-08-21 11:27 UTC, ag278 commented
@SKAUL05 i have made the required changes. Please verify it once

2020-08-21 11:28 UTC, SKAUL05 approved these changes

2020-08-21 11:41 UTC, iamrajiv approved these changes

2020-08-21 11:42 UTC, merged

2020-08-23 17:28 UTC, iamrajiv commented
@all-contributors please add @ag278 for code