Bucket sort
HarshCasper/NeoAlgo pull request #490
Opened 2020-08-16 17:42 UTC by santushtisharma10

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added python file of Bucket Sorting Algorithm and updated the readme file also.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-16 17:44 UTC, santushtisharma10 commented
@SKAUL05 Please review my PR

2020-08-17 06:20 UTC, SKAUL05 requested changes

2020-08-17 06:20 UTC, SKAUL05 commented on Python/sort/Bucket_Sort.py
> +    Bucket = []
Follow single convention for variable naming. Will suggest to follow PEP8 Guidelines
https://www.python.org/dev/peps/pep-0008/

2020-08-17 06:20 UTC, SKAUL05 commented on Python/sort/Bucket_Sort.py
> +for index in range(size):
Include a main function and then call the respective functions from there.

2020-08-17 08:01 UTC, santushtisharma10 commented
@SKAUL05 I have made changes as you said, Please review it

2020-08-17 08:02 UTC, SKAUL05 approved these changes

2020-08-18 05:44 UTC, SKAUL05 commented
@santushtisharma10 Copied from [here](https://www.geeksforgeeks.org/bucket-sort-2/)

- Exactly same, in some places only variable name is changed.
- Don't just copy & paste.
- Do it by your own
Note: It's very important to do legit work on your own. In case of repeated violations, you will be blocked to contribute in [Neo Algo](https://github.com/TesseractCoding/NeoAlgo)

2020-08-18 06:35 UTC, santushtisharma10 commented
@SKAUL05 the code of geeks for geeks works only for numbers between 0 and 1 and my code works for large as well as small numbers

2020-08-18 06:38 UTC, santushtisharma10 commented
I used these as referece https://www.youtube.com/watch?v=geVyIsFpxUs&t=355s and https://en.wikipedia.org/wiki/Bucket_sort

2020-08-18 06:39 UTC, santushtisharma10 commented
Moreover in geeks for geeks code they always used 10 buckets and since i took the help of wikipedia to understand the algorithm i created the buckets of the same size of unsorted array

2020-08-18 06:45 UTC, santushtisharma10 commented
@SKAUL05 please look into this matter

2020-08-18 07:05 UTC, SKAUL05 reviewed
There are these elements which helps in establishing strong relation between the two scripts which can't be neglected as coincidence.
Since the program is modified in a better way, I think it can be taken as a contribution but will require approval from PA as well.
Do keep in mind while raising PR, if you think you have taken references **(not copied)** from certain sites. Do mention it in PR Description as it will help in avoiding unnecessary element of suspicious activity.
I'm going ahead and opening it for thorough review from other reviewers.

2020-08-18 07:05 UTC, SKAUL05 commented on Python/sort/Bucket_Sort.py
> +    for index in range(size):
This could have been easily achieved by 
`bucket = [[]]*size`

2020-08-18 07:05 UTC, SKAUL05 commented on Python/sort/Bucket_Sort.py
> +def insertion_sort(array, size):
Placing of statements in insertion sort function is exact replica of GFG code only with minor changes in variable names.

2020-08-18 07:08 UTC, santushtisharma10 commented
@SKAUL05 thank you i will keep it in mind

2020-08-18 07:08 UTC, SKAUL05 commented
@HarshCasper @atarax665 @Kajol-Kumari 
Review Required on this PR for plagiarism check and modifications.
Thanks.

2020-08-18 13:30 UTC, Abhijit2505 requested changes
First thing first, you have obviously taken reference from the outer source.

I would like you to do 2 things,

1 - make the code shorter by using the reviews given above by @SKAUL05.
2 - Add some modularity to your code, i.e. please add two **class**, inside which you will have your functions. Next you can create custom objects and write the code again. This will solve my query on plagiarism.

2020-08-18 14:26 UTC, santushtisharma10 commented
@Abhijit2505 Sure

2020-08-21 07:51 UTC, Kajol-Kumari requested changes
Hey @santushtisharma10 I ran your code and the expected output isn't equal to what i am getting here. Please correct this. Also please add one sample input-output below the code section in commented form.
```
4                                                                                                                               
1                                                                                                                               
5                                                                                                                               
6                                                                                                                               
2                                                                                                                               
Unsorted Array : [1, 5, 6, 2]                                                                                                   
Sorted Array :  [1, 2, 5, 6, 1, 2, 5, 6, 1, 2, 5, 6, 1, 2, 5, 6] 
```

2020-08-21 07:51 UTC, Kajol-Kumari commented on Python/sort/Bucket_Sort.py
> +    size = int(input())
please show proper message to the user while taking the input.

2020-08-21 07:51 UTC, Kajol-Kumari commented on Python/sort/Bucket_Sort.py
> +        element = int(input())
same here. please show proper message to the user.

2020-10-31 00:17 UTC, closed without merging