Added code for Pair programmers productivity problem in Java
HarshCasper/NeoAlgo pull request #4910
Opened 2021-04-02 10:31 UTC by Devansu-Yadav

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.
(Write your answer here.)

### Description

Added code for Pair Programmer's Productivity Problem using Greedy Approach in Java
(Write your answer here.)

### Checklist

- [✔ ] I've read the contribution guidelines.
- [✔ ] I've checked the issue list before deciding what to submit.
- [ ✔] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

#4520

2021-04-03 05:35 UTC, Devansu-Yadav commented
@iamrajiv @ankitaggarwal23 Can u pls review my PR?

2021-04-03 06:35 UTC, iamrajiv approved these changes

2021-04-04 12:50 UTC, ankitaggarwal23 requested changes

2021-04-04 12:50 UTC, ankitaggarwal23 commented on Java/README.md
> +- [Pair_programmers_productivity_problem](other/Pair_programmers_productivity_problem.java)
Remove `_` from `[Pair_programmers_productivity_problem]` make it as `[Pair Programmers Productivity Problem]`

2021-04-09 07:07 UTC, ankitaggarwal23 approved these changes

2021-04-09 07:08 UTC, merged