Implement the basic functionality of stack using Array Data structure
HarshCasper/NeoAlgo pull request #492
Opened 2020-08-16 18:18 UTC by Rishikeshrajrxl

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes.)

### Description

(Implemented the basic functionality of stack such as push, pop, peek,is_Empty, is_Full, without using Inbuilt Functions.)

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#399 )

2020-08-16 18:19 UTC, Rishikeshrajrxl commented
@siddharth25pandey 
Kindly review it and let me know any change needed.

2020-08-17 01:41 UTC, Rishikeshrajrxl commented
@iamrajiv , @plazzy99  please review this.

2020-08-17 02:01 UTC, iamrajiv requested changes
@Rishikeshrajrxl fixed typos mistakes across the files. Also, remove unnecessary line breaks.

2020-08-17 02:50 UTC, siddharth25pandey requested changes
@Rishikeshrajrxl Please make following modifications
* count function is missing, which gives total number of elements present at that time.
* Remove unnecessary line breaks & space

2020-08-17 02:56 UTC, Rishikeshrajrxl commented
> @Rishikeshrajrxl fixed typos mistakes across the files. Also, remove unnecessary line breaks.

 @iamrajiv ,    What is fixed typos mistake across the file ? Please explain me.

2020-08-17 03:05 UTC, iamrajiv requested changes

2020-08-17 03:05 UTC, iamrajiv commented on C-Plus-Plus/ds/Stack_using_LinkedList.cpp
>  // Stsck using Vector
remove Stsck

2020-08-17 03:05 UTC, iamrajiv commented on C-Plus-Plus/ds/Stack_using_Array.cpp
> +
remove the unnecessary line break

2020-08-17 03:05 UTC, iamrajiv commented on C-Plus-Plus/ds/Stack_using_Array.cpp
> +
remove the unnecessary line break

2020-08-17 05:30 UTC, Rishikeshrajrxl commented
I have made all changes, please review this.

2020-08-17 07:36 UTC, siddharth25pandey requested changes
@Rishikeshrajrxl , follow the same workflow for Linked list implementation, as what you have done for working with array. 
* work on user interface

2020-08-17 09:03 UTC, Rishikeshrajrxl commented
@siddharth25pandey , Done with all changes.

2020-08-17 10:19 UTC, siddharth25pandey approved these changes
@Rishikeshrajrxl  Looks fine to me.
Able to merge
Thanks!

2020-08-17 14:48 UTC, vatsalkesarwani12 approved these changes
The code looks fine for me.

2020-08-17 14:50 UTC, iamrajiv approved these changes

2020-08-17 15:41 UTC, Rishikeshrajrxl commented
@siddharth25pandey , This pull request is approved, please merge it.

2020-08-17 15:58 UTC, merged