Made required changes in code and updated readme.md file for issue-3901
HarshCasper/NeoAlgo pull request #4922
Opened 2021-04-02 13:56 UTC by iaditichine

I have made required changes in the code and updated the readme.md file.

2021-04-02 17:25 UTC, HarshCasper requested changes

2021-04-02 17:25 UTC, HarshCasper commented on C-Plus-Plus/other/Sorting_an_array_of_zeroes_and_ones.cpp
> +    ios::sync_with_stdio(0);
Don't use CP references

2021-04-02 17:25 UTC, HarshCasper commented on C-Plus-Plus/other/Sorting_an_array_of_zeroes_and_ones.cpp
> +        cout << 1 << " "; //printing 1 for c1 times
Use comments above the line of code not beside it

2021-04-02 17:25 UTC, HarshCasper commented on C-Plus-Plus/other/Sorting_an_array_of_zeroes_and_ones.cpp
> +	//Input n= Size of array
Remove redundant comments

2021-04-04 09:42 UTC, ankitaggarwal23 reviewed
We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.  Closing this PR as of now. Open the new PR if you want this to be reviewed and add the proper details.

2021-04-04 09:45 UTC, closed without merging