Add Binary Search Tree to Python
HarshCasper/NeoAlgo pull request #4925
Opened 2021-04-02 14:43 UTC by abxhr

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Binary Search Tree implementation in Python (menu-based), which will also contain the basic Binary Search Tree operations such as Insert, Delete, Search, and Print (inorder).

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #4921

2021-04-05 14:14 UTC, HarshCasper requested changes

2021-04-05 14:14 UTC, HarshCasper commented on Python/ds/BinarySearchTree.py
> +            print()
Add sample I/O here

2021-04-05 14:14 UTC, HarshCasper commented on Python/README.md
> +- [Binary Search Tree](ds/BinarySearchTree.py)
Why have you added the same twice?

2021-04-05 17:33 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-06 08:28 UTC, ankitaggarwal23 approved these changes

2021-04-06 08:29 UTC, merged