Add Exponential Search In kotlin
HarshCasper/NeoAlgo pull request #4947
Opened 2021-04-03 04:27 UTC by hemant2705

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
I have Added Exponential Search in Kotlin.
I have added all necessary comments to make code more readable.

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#4536 
(Write your answer here.)

2021-04-04 11:14 UTC, hemant2705 commented
Can Anyone please review it?

2021-04-05 14:15 UTC, HarshCasper requested changes

2021-04-05 14:15 UTC, HarshCasper commented on Kotlin/search/ExponentialSearch.kt
> +//Iterative Binary Search O(1) space.
Use Multi-Line Comments

2021-04-05 14:15 UTC, HarshCasper commented on Kotlin/search/ExponentialSearch.kt
> +  int arr[] = {2, 3, 4, 10, 40};
Use dynamic input

2021-04-05 15:22 UTC, hemant2705 commented
Changes committed !
Can you please  go through it.

2021-04-05 17:26 UTC, ankitaggarwal23 approved these changes

2021-04-06 11:45 UTC, HarshCasper approved these changes

2021-04-06 11:45 UTC, merged