Made required changes in code for issue-3901
HarshCasper/NeoAlgo pull request #4952
Opened 2021-04-03 06:13 UTC by iaditichine

I have made the required changes in code and updated readme.md file for issue-3901.

2021-04-03 07:23 UTC, HarshCasper requested changes

2021-04-03 07:23 UTC, HarshCasper commented on C-Plus-Plus/other/Sorting_an_array_of_zeroes_and_ones.cpp
> +Given an array of size n which contains only 0's and 1's in any order,we have to modify the array in such a way that 0's are on left side and 1's on the right side.
Modularize this piece of comment

2021-04-03 07:23 UTC, HarshCasper commented on C-Plus-Plus/other/Sorting_an_array_of_zeroes_and_ones.cpp
> +//CODE
Redundant Comment

2021-04-03 11:49 UTC, iaditichine commented
How do I modularize this comment?

2021-04-03 11:50 UTC, iaditichine commented on C-Plus-Plus/other/Sorting_an_array_of_zeroes_and_ones.cpp
> +Given an array of size n which contains only 0's and 1's in any order,we have to modify the array in such a way that 0's are on left side and 1's on the right side.
How do I modularize this comment?

2021-04-04 09:48 UTC, ankitaggarwal23 reviewed
We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.  Closing this PR as of now. Open the new PR if you want this to be reviewed and add the proper details. Also do the changes as harsh mentioned in new PR.

2021-04-04 09:48 UTC, closed without merging