added the code for the Kth smallest element in an array
HarshCasper/NeoAlgo pull request #4980
Opened 2021-04-03 12:15 UTC by hw0105

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
Added the code for finding the kth smallest element in an array in cpp. #4413

### Checklist

- [ yes] I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
- [yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
     #4413

2021-04-04 08:42 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces

2021-04-04 19:57 UTC, iamrajiv approved these changes

2021-04-05 09:39 UTC, ankitaggarwal23 requested changes

2021-04-05 09:39 UTC, ankitaggarwal23 commented on C-Plus-Plus/heap/KthSmallestElement.cpp
> +*/
Shift your approach above the header

2021-04-05 09:39 UTC, ankitaggarwal23 commented on C-Plus-Plus/heap/KthSmallestElement.cpp
> +*/
Code produces output like that rewrite it.
![Capture](https://user-images.githubusercontent.com/67387053/113560528-c13c3380-9620-11eb-847e-05da553fb1dd.JPG)

2021-04-05 17:31 UTC, ankitaggarwal23 requested changes
Rest looks good to merge

2021-04-05 17:31 UTC, ankitaggarwal23 commented on C-Plus-Plus/heap/KthSmallestElement.cpp
> +*/
Add a new line at the end 
Remove the space before the testcase, input and output Rewrite it like that,
```
/*
Sample Input:

Enter the size of the array: 8
Enter k: 4
Enter array elements: 7 8 9 5 7 2 4 10

Sample Output:
The Kth Smallest Element: 7

Time Complexity: O(nlogk)
Space Complexity: O(k)
*/
```

2021-04-05 17:54 UTC, ankitaggarwal23 approved these changes

2021-04-05 17:55 UTC, merged