Minimum cost to generate n cells in the container starting from one cell
HarshCasper/NeoAlgo pull request #4991
Opened 2021-04-03 16:01 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code added in cp(competitive programming) folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4983

2021-04-03 16:02 UTC, gayatri517 commented
@HarshCasper Kindly review my PR.
Thank you.

2021-04-04 14:24 UTC, gayatri517 commented
@ankitaggarwal23 please take a look at my PR

2021-04-05 05:50 UTC, HarshCasper requested changes

2021-04-05 05:50 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Minimum cost to generate n cells in the container starting from one cell](cp/min_cost_to_generate_n_cells.cpp)
Keep it `Minimum Cost to generate N Cells`

2021-04-05 05:50 UTC, HarshCasper commented on C-Plus-Plus/cp/min_cost_to_generate_n_cells.cpp
> +
Remove extra line

2021-04-05 06:27 UTC, gayatri517 commented
@HarshCasper I have made the changes, Kindly review them

2021-04-05 09:17 UTC, ankitaggarwal23 approved these changes

2021-04-05 09:19 UTC, merged