Patch 6
HarshCasper/NeoAlgo pull request #4992
Opened 2021-04-03 16:02 UTC by Suvraneel

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yep !

### Description
Inversion Vector of a Singly Linked List

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

resolves #4115

2021-04-03 16:06 UTC, Suvraneel commented
Hello maintainers!
Kindly review this... Followed all suggestions from previous PRs :)
@HarshCasper @bhav09  @siddharth25pandey

2021-04-04 08:50 UTC, ankitaggarwal23 requested changes

2021-04-04 08:50 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/inversion_vector.cpp
> +
Remove this redundant comments

2021-04-04 08:50 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/inversion_vector.cpp
> +void inversion();
Remove the function declarations

2021-04-04 08:50 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/inversion_vector.cpp
> + }
Shift the main after all the functions

2021-04-04 08:50 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/inversion_vector.cpp
> +Time Complexity of Inversion Vector = O(n^2)
Shift TC after the end of outputs and write SC as well

2021-04-04 08:50 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/inversion_vector.cpp
> +9 inserted as node
Remove the extra elements show with 5 elements

2021-04-04 15:58 UTC, Suvraneel commented
@ankitaggarwal23  Done :)

2021-04-04 17:46 UTC, ankitaggarwal23 approved these changes

2021-04-04 17:46 UTC, merged

2021-04-07 14:33 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!