Added solution for Edit Distance
HarshCasper/NeoAlgo pull request #500
Opened 2020-08-17 02:36 UTC by Joshitha18

Edit Distance

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added DP solution for Edit Distance Problem

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#477

2020-08-17 06:10 UTC, Kajol-Kumari requested changes
Hey @Joshitha18 Good work! The code is working fine! Please add one input and output sample below the code section in commented form and it will be good to go.

Also please provide a bit of description about the problem your PR is going to solve or simpley link the related issue using `Fixes: #[number of the issue without these braces]` so that we can know what the PR is actually for :)

2020-08-17 06:44 UTC, Joshitha18 commented
@Kajol-Kumari Added requested changes

2020-08-17 08:07 UTC, Kajol-Kumari approved these changes
LGTM :)

2020-08-18 04:49 UTC, vatsalkesarwani12 requested changes
print a message before input describing the kind of input user have to enter 
Also, print the output with a message

2020-08-18 06:29 UTC, Joshitha18 commented
@plazzy99 Added requested changes

2020-08-18 06:31 UTC, vatsalkesarwani12 approved these changes
Request changes done 💯

2020-08-18 06:33 UTC, plazzy99 commented
@Joshitha18 also try to make a change to the original file and don't delete and add another file.

Follow few online tutorials to learn Github

2020-08-18 13:23 UTC, Abhijit2505 requested changes
I would like two things here,

1 - Implement the string algorithms (This is DP-String Manipulation) using the String Class in C++ because In most of the interviews they ask to use string class because that is tricky and something not present in procedural languages like C unlike char array which is common in C and C++.
2 - Add the recursive approach as well. Although it's a DP problem, but the recursive approach helps the learner in deriving to the DP solution.

Your code is good, but we should focus on writing better code using some better functionalities in CPP like string class and OOP.

2020-08-19 04:33 UTC, Joshitha18 commented
> I would like two things here,
> 
> 1 - Implement the string algorithms (This is DP-String Manipulation) using the String Class in C++ because In most of the interviews they ask to use string class because that is tricky and something not present in procedural languages like C unlike char array which is common in C and C++.
> 2 - Add the recursive approach as well. Although it's a DP problem, but the recursive approach helps the learner in deriving to the DP solution.
> 
> Your code is good, but we should focus on writing better code using some better functionalities in CPP like string class and OOP.

@Abhijit2505 I'll add recursive approach but I don't understand what u mean by 'Implement string Algorithm' for this above code. Can u be more elaborate or give some examples?

2020-08-19 06:15 UTC, Joshitha18 commented
@Abhijit2505 Added changes

2020-08-21 10:41 UTC, Joshitha18 commented
@Abhijit2505 ?

2020-08-22 10:33 UTC, Joshitha18 commented
@Abhijit2505 Please approve this. I made requested changes

2020-08-26 15:06 UTC, Abhijit2505 requested changes

2020-08-26 15:06 UTC, Abhijit2505 commented on C-Plus-Plus/dp/edit_distance.cpp
> +
Please change it into dynamic memory allocation, instead of some fixed size.

2020-08-26 15:42 UTC, Joshitha18 commented
@Abhijit2505 done

2020-08-28 07:21 UTC, merged