Bucket sort algorithm added
HarshCasper/NeoAlgo pull request #501
Opened 2020-08-17 03:37 UTC by Anjali2001saxena

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Bucket sort algorithm added.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-17 17:20 UTC, Kajol-Kumari requested changes
@Anjali2001saxena Functionality is working fine!
Please add the file path in the readme's appropriate section and incorporate the suggested changes.

2020-08-17 17:20 UTC, Kajol-Kumari commented on C-Plus-Plus/sort/bucketsort.cpp
> +}
Please give one extra blank line at the end of the file.

2020-08-17 17:20 UTC, Kajol-Kumari commented on C-Plus-Plus/sort/bucketsort.cpp
> +    float arr[] = {0.897, 0.565, 0.656, 0.1234, 0.665, 0.3434};
Please take the input from the user

2020-08-18 04:29 UTC, Anjali2001saxena commented
Mam I have made the necessary changes and update the readme file to add bucket sort. Please check.

2020-08-18 05:51 UTC, vatsalkesarwani12 reviewed
Code copied from [geeks for geeks](https://www.geeksforgeeks.org/bucket-sort-2/)

2020-08-18 07:14 UTC, SKAUL05 commented
> Code copied from [geeks for geeks](https://www.geeksforgeeks.org/bucket-sort-2/)

Closing this PR due to plagiarism.

2020-08-18 07:14 UTC, closed without merging