Transpose of a 3X3 Matrix using C++
HarshCasper/NeoAlgo pull request #5012
Opened 2021-04-04 08:04 UTC by somya1252

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-04 08:37 UTC, ankitaggarwal23 requested changes
Shift the logic to another function and use main for driver code

2021-04-04 08:37 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/Transpose_Of_3X3_Matrix.cpp
> +*/
- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-04-04 09:33 UTC, HarshCasper requested changes

2021-04-04 09:33 UTC, HarshCasper commented on C-Plus-Plus/other/Transpose_Of_3X3_Matrix.cpp
> +int main() {
Don't push your primary code logic in the `main()` function

2021-04-04 13:24 UTC, siddharth25pandey requested changes
@somya1252 Do the same for any square matrix

2021-04-05 04:37 UTC, siddharth25pandey requested changes
@somya1252 You are not taking input of the size **N** then how you are taking input for the square matrix. I request you before submitting any PR. Please try to execute it.

2021-04-05 04:37 UTC, siddharth25pandey commented on C-Plus-Plus/other/Transpose_Of_Square_Matrix.cpp
> +    int a[N][N];
Input of N is missing

2021-04-07 15:47 UTC, siddharth25pandey approved these changes
@somya1252 LGTM 💯 Able to merge

2021-04-07 15:48 UTC, merged

2021-04-07 15:49 UTC, siddharth25pandey commented
@all-contributors please add @somya1252 for her code