Double ended queue java
HarshCasper/NeoAlgo pull request #5013
Opened 2021-04-04 08:07 UTC by khusheekapoor

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the Contributing Guidelines on Pull Requests

### Description

I have written a code to implement basic operations (pushfront, pushrear, popfront, poprear, display) on Double Ended Queues in Java as a GSSoC'21 participant.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

For Issue #4984 .

2021-04-04 08:32 UTC, ankitaggarwal23 requested changes

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +
Remove the space

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +import java.util.*;
Add a new line after header file

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +         */
Remove the algo

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +         */
Remove the algo

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +         */
Remove the algo

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +         */
Remove the algo

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +        int size = scanner.nextInt(); scanner.nextLine();
Shift ` scanner.nextLine();` to new line

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +            int choice = scanner.nextInt(); scanner.nextLine();
Shift ` scanner.nextLine();` to new line

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +                ob.pushfront(value);
Give a one tab space

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +                ob.pushrear(value);
Give a one tab space

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +                ob.popfront();
Give a one tab space

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +                ob.poprear();
Give a one tab space

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +                ob.display();
Give a one tab space

2021-04-04 08:32 UTC, ankitaggarwal23 commented on Java/ds/DEQueue.java
> +            flag = scanner.nextInt(); scanner.nextLine();
Shift scanner.nextLine(); to new line

2021-04-04 09:08 UTC, khusheekapoor commented
Made the changes @ankitaggarwal23 . Let me know if any further changes are required. Thanks.

2021-04-04 13:35 UTC, ankitaggarwal23 approved these changes

2021-04-04 13:35 UTC, merged

2021-04-07 14:33 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!