add code for Product of maximum in first array and minimum in second
HarshCasper/NeoAlgo pull request #5017
Opened 2021-04-04 10:44 UTC by jtomar24

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

added code for #4579 issue .please review this and let me know if changes required .

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-04 10:48 UTC, jtomar24 commented
I will add logic in the function.

2021-04-04 11:23 UTC, jtomar24 commented
I had added the logic  in the function.

2021-04-04 12:42 UTC, ankitaggarwal23 requested changes
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-04 12:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +/*Given two arrays, the task is to calculate the product of max element of first array and min element of second array*/
Remove the duplicate description and write bit more description

2021-04-04 12:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +        //main logic
Remove redundant comments

2021-04-04 12:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +//main function
Remove redundant comments

2021-04-04 12:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +    int b[] = { 9, 8, 6, 4, 2};
Don't use static inputs use dynamic inputs with proper display message.

2021-04-04 12:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +    cout<<prod;
Don't use single letters use proper naming conventions for variables

2021-04-05 15:30 UTC, jtomar24 commented
Sir could you tell me how to resolve this ?I m new to pen source I don't know hoe to deal with this problem.

2021-04-05 16:08 UTC, HarshCasper requested changes

2021-04-05 16:08 UTC, HarshCasper commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +Example:we are given two arrays arr1={1,2,3,4} and arr2={5,6,7,8,9} ,so the maximum element in array arr1 is 4 and minimum element in array arr2 is 5.Hence,the product of max element in array arr1 an
Can you make it short, crisp and easy to read? Don't give examples here. Keep it at the bottom

2021-04-05 16:08 UTC, HarshCasper commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +->return the product.
Use bulleted list like `-` to denote points, not `->`

2021-04-05 16:08 UTC, HarshCasper commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +
Add a new line at the EOF

2021-04-05 16:08 UTC, HarshCasper commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +
Remove this

2021-04-05 18:02 UTC, ankitaggarwal23 requested changes
Use cpplint It will guide you how to format code properly for reference use this one [here](https://cpplint.appspot.com/).

2021-04-05 19:51 UTC, jtomar24 commented
I had made most of the changes which were listed regarding whitespaces .

2021-04-07 14:22 UTC, HarshCasper requested changes

2021-04-07 14:22 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [product of max in first array and min in second](cp/product_of_max_in_first_array_and_min_in_second.cpp)
Keep it `Product of the maximum element and the minimum element in two consecutive arrays`

2021-04-07 14:22 UTC, HarshCasper commented on C-Plus-Plus/cp/product_of_max_in_first_array_and_min_in_second.cpp
> +
Can you try to follow the standards and not make any shortforms?

2021-04-07 16:06 UTC, ankitaggarwal23 requested changes
.

2021-04-09 07:21 UTC, HarshCasper approved these changes

2021-04-09 07:22 UTC, merged