Circular queue java
HarshCasper/NeoAlgo pull request #5043
Opened 2021-04-05 05:11 UTC by khusheekapoor

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the Contributing Guidelines on Pull Requests

### Description

I have written a code to implement basic operations (inserting and deleting an element, displaying) on Circular Queues in Java as a GSSoC'21 participant.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

For issue #5042

2021-04-05 14:22 UTC, HarshCasper requested changes
Can you give a smaller I/O sample?

2021-04-05 14:22 UTC, HarshCasper commented on Java/ds/CircularQueue.java
> + */
Add a new line at the EOF

2021-04-05 16:35 UTC, khusheekapoor commented
> Can you give a smaller I/O sample?

Sure! Should I change the code (as in remove the menu), or only change the output in the comments (and mention that this is the essence of it)?

2021-04-07 14:23 UTC, HarshCasper commented
> > Can you give a smaller I/O sample?
> 
> Sure! Should I change the code (as in remove the menu), or only change the output in the comments (and mention that this is the essence of it)? @HarshCasper

Only the output

2021-04-08 05:19 UTC, khusheekapoor commented on Java/ds/CircularQueue.java
> + */
Made the changes.

2021-04-09 07:26 UTC, ankitaggarwal23 approved these changes

2021-04-09 07:26 UTC, merged