Kathan vakharia
HarshCasper/NeoAlgo pull request #505
Opened 2020-08-17 04:30 UTC by Kathan-Vakharia

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added python code for issue #414 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-17 07:16 UTC, Kathan-Vakharia commented
@plazzy99 , @Abhijit2505 , @Kajol-Kumari  Kindly review my PR :)

2020-08-17 07:24 UTC, Kajol-Kumari requested changes
@Kathan-Vakharia Please incorporate the requested changes and add a sample input and output below the code section in the commented from.

2020-08-17 07:24 UTC, Kajol-Kumari commented on Python/miscellaneous/find_freq_using_bs.py
> +    print(f"Ocurrence of '{key}': {get_freq_using_bs(arr, N, key)}")
@Kathan-Vakharia  Please replace this line here by `print("Ocurrence of",key,"is :", get_freq_using_bs(arr, N, key))`

2020-08-17 09:00 UTC, Kathan-Vakharia commented
@Kajol-Kumari , I have made the respective changes kindly review them :).
And ya I did some mistake while squashing the commits because it was my first time 😕 and that's the reason it is showing changes of previous commits also but nothing is broken I believe. Will take care next time 😀

2020-08-17 11:32 UTC, Kajol-Kumari commented
> @Kajol-Kumari , I have made the respective changes kindly review them :).
> And ya I did some mistake while squashing the commits because it was my first time  and that's the reason it is showing changes of previous commits also but nothing is broken I believe. Will take care next time

Hey @Kathan-Vakharia please remove the extra files that got added through your commit, otherwise your PR won't be merged.

2020-08-17 12:10 UTC, Kathan-Vakharia commented
@Kajol-Kumari , I have removed those files. Kindly review it again :)
Pardon for taking too long as it is like a new world for me :|

2020-08-18 05:08 UTC, vatsalkesarwani12 requested changes
The code you have written is doing a partial binary search so it is not accepted
your algo should should be purely binary search

2020-08-18 06:33 UTC, Kathan-Vakharia commented
@plazzy99  ,I have updated my code. Kindly review it :)

2020-08-18 06:42 UTC, vatsalkesarwani12 approved these changes
Nice documentation done 🥇 

Keep up the good work

2020-08-18 07:01 UTC, Kathan-Vakharia commented
Thanks, means a lot :) , @Kajol-Kumari  and @Abhijit2505 kindly review my pull request as per your convenience  😀

2020-08-18 10:14 UTC, Kajol-Kumari approved these changes
LGTM :)

2020-08-18 13:18 UTC, Abhijit2505 approved these changes
Great 😊

2020-08-18 13:19 UTC, merged

2020-08-23 17:31 UTC, iamrajiv commented
@all-contributors please add @Kathan-Vakharia for code