BipartiteCheck - Fix for PR #4882
HarshCasper/NeoAlgo pull request #5074
Opened 2021-04-05 14:55 UTC by Jahnavi-Majji

Fixed requested changes on the PR #4882

2021-04-05 14:56 UTC, Jahnavi-Majji commented
Kindly review @HarshCasper. Created a new branch to fix the issues requested because couldn't find the previous branch copy on my local machine.

2021-04-05 17:09 UTC, ankitaggarwal23 requested changes

2021-04-05 17:09 UTC, ankitaggarwal23 commented on Java/graphs/BipartiteCheck.java
> +    1 4
Use proper display message

2021-04-05 23:41 UTC, Jahnavi-Majji commented on Java/graphs/BipartiteCheck.java
> +    1 4
Fixed. You can check now.

2021-04-06 07:44 UTC, ankitaggarwal23 approved these changes

2021-04-06 07:44 UTC, ankitaggarwal23 commented on Java/graphs/BipartiteCheck.java
> +1 4
Use proper display message how you are reading inputs as 4 4 1 2 etc. doesn't make sense what it is use display proper display message in your code.

2021-04-06 07:45 UTC, ankitaggarwal23 commented
Also resolve merge conflicts.

2021-04-06 08:23 UTC, ankitaggarwal23 approved these changes

2021-04-06 08:24 UTC, merged

2021-04-07 14:31 UTC, HarshCasper commented
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!

2021-04-07 14:42 UTC, Jahnavi-Majji commented
Yeah sure!
But I see that there are no Docs-related issues raised in this repository. Can I make the issue on the NeoAlgo-Docs repo?

2021-04-07 15:44 UTC, HarshCasper commented
> Yeah sure!
> But I see that there are no Docs-related issues raised in this repository. Can I make the issue on the NeoAlgo-Docs repo?

Yeah. All the issues for the docs will go to that repo