Median of arrays in c
HarshCasper/NeoAlgo pull request #5075
Opened 2021-04-05 15:07 UTC by Amit366

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Median of two sorted arrays in C

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixes: #4961

2021-04-05 17:22 UTC, atarax665 requested changes
Changes requested:
- Rename the file name  from ```Median of two sorted arrays.c``` to  ```Median_of_two_sorted_arrays.c``` and make appropriate changes to thge README.md aswell.
- Remove unnecessary blank lines
- Add proper input-output statements to make the program more interactive.
- Remove variables ```sum and s``` as they aren't being used in the program

2021-04-05 17:32 UTC, Amit366 commented
@atarax665 updated. Please check.

2021-04-05 17:39 UTC, ankitaggarwal23 requested changes
Use cpplint it will guide you how to format code properly for reference you can use this one [here](https://cpplint.appspot.com/).

2021-04-06 06:03 UTC, Amit366 commented
@ankitaggarwal23 updated. Please review.

2021-04-06 13:03 UTC, Amit366 commented
@ankitaggarwal23 please review it.

2021-04-06 16:36 UTC, Amit366 commented
@HarshCasper please review it.

2021-04-07 14:25 UTC, HarshCasper requested changes

2021-04-07 14:25 UTC, HarshCasper commented on C/cp/Median_of_two_sorted_arrays.c
> +// respectively, return the median of the two sorted arrays
Use multi-line comments

2021-04-07 14:25 UTC, HarshCasper commented on C/cp/Median_of_two_sorted_arrays.c
> +#include<stdlib.h>
Add a new line after this

2021-04-07 14:25 UTC, HarshCasper commented on C/cp/Median_of_two_sorted_arrays.c
> +  for (int i = 0; i < n; i++) {
Add a new line after this

2021-04-07 14:25 UTC, HarshCasper commented on C/cp/Median_of_two_sorted_arrays.c
> +  printf("Enter elements of second array: ");
Add a new line after this

2021-04-07 14:25 UTC, HarshCasper commented on C/cp/Median_of_two_sorted_arrays.c
> +}
Add a new line after this

2021-04-07 14:25 UTC, HarshCasper commented on C/cp/Median_of_two_sorted_arrays.c
> +  }
Add a new line after this

2021-04-07 14:33 UTC, Amit366 commented
@HarshCasper initially I added the new lines but @ankitaggarwal23 said to format it and in the cpplint the extra lines where showing errors.

2021-04-07 16:21 UTC, Amit366 commented
@HarshCasper please review

2021-04-08 14:10 UTC, Amit366 commented
@HarshCasper please review it.

2021-04-08 14:53 UTC, HarshCasper approved these changes

2021-04-08 15:05 UTC, merged

2021-04-08 15:21 UTC, Amit366 commented
@HarshCasper could you please add the labels??