Two pointer Algorithm using java
HarshCasper/NeoAlgo pull request #5076
Opened 2021-04-05 15:13 UTC by RuchiGitHu

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

The algorithm basically uses the fact that the input array is sorted. We start the sum of extreme values (smallest and largest) and conditionally move both pointers.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixes #5023

2021-04-08 16:50 UTC, RuchiGitHu commented
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
> Yes
> 
> ### Description
> The algorithm basically uses the fact that the input array is sorted. We start the sum of extreme values (smallest and largest) and conditionally move both pointers.
> 
> ### Checklist
> * [x]  I've read the contribution guidelines.
> * [x]  I've checked the issue list before deciding what to submit.
> * [x]  I've edited the `README.md` and link to my code.
> 
> ## Related Issues or Pull Requests
> fixes #5023

@HarshCasper , @ankitaggarwal23 Please review my PR....

2021-04-09 07:31 UTC, ankitaggarwal23 reviewed
- Shift the logic to another function and use main for driver code
- Don't use static input use dynamic inputs from user with proper display message.

2021-04-09 07:32 UTC, ankitaggarwal23 requested changes

2021-04-09 07:32 UTC, ankitaggarwal23 commented on Java/README.md
> +- [Two_Pointer_Algorithm](Algorithms/Two_pointer_Algorithm.java)
Rewrite as ` [Two Pointer Algorithm]`

2021-04-09 18:38 UTC, RuchiGitHu commented
> * Shift the logic to another function and use main for driver code
> * Don't use static input use dynamic inputs from user with proper display message.

Please review again @ankitaggarwal23

2021-04-09 18:39 UTC, ankitaggarwal23 requested changes
Kindly use proper code format.

2021-04-09 18:42 UTC, RuchiGitHu commented
> Kindly use proper code format.

just now indented...

2021-04-10 15:05 UTC, RuchiGitHu commented
> > Kindly use proper code format.
> 
> just now intended...

Please check my code @HarshCasper @ankitaggarwal23

2021-04-11 16:32 UTC, ankitaggarwal23 requested changes

2021-04-11 16:32 UTC, ankitaggarwal23 commented on Java/Algorithms/Two_pointer_Algorithm.java
> +}
Give one tab space

2021-04-11 17:22 UTC, RuchiGitHu commented on Java/Algorithms/Two_pointer_Algorithm.java
> +}
updated as raquired.. Please review @ankitaggarwal23 .

2021-04-12 07:39 UTC, ankitaggarwal23 approved these changes

2021-04-12 07:39 UTC, merged