transpose square matrix
HarshCasper/NeoAlgo pull request #5108
Opened 2021-04-05 19:20 UTC by ANSHIKA1806

It is an important question and it should be in the project.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ yes] I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#4867

2021-04-07 15:53 UTC, siddharth25pandey requested changes
@ANSHIKA1806 Do the mentioned changes & add the update in **README FILE**

2021-04-07 15:53 UTC, siddharth25pandey commented on Java/other/Transpose square matrix.java
> +int original[][]={{1,3,4},{2,4,3},{3,4,5}};
Take Dynamic Input

2021-04-08 14:32 UTC, ANSHIKA1806 commented
@siddharth25pandey I've made the changes. Please check it and merge it.

2021-04-08 14:50 UTC, siddharth25pandey commented
> @siddharth25pandey I've made the changes. Please check it and merge it.

Please read complete [message](https://github.com/TesseractCoding/NeoAlgo/pull/5108#pullrequestreview-630180386)

2021-04-08 14:52 UTC, siddharth25pandey commented
@ANSHIKA1806 Also, include Sample Input & Output and Time & Space Complexity at the end of Program in commented form.

2021-04-09 07:37 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-09 07:37 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +public class MatrixTransposeExample2
Rewrite it as `MatrixTranspose`

2021-04-09 07:37 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +        }
Align your braces properly.

2021-04-09 07:38 UTC, ankitaggarwal23 requested changes

2021-04-09 07:38 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +            }
Add a one tab space inside the body

2021-04-09 07:38 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +            }
Add a one tab space inside the body

2021-04-09 10:31 UTC, ANSHIKA1806 commented
@ankitaggarwal23 @siddharth25pandey I've made the changes, Please check it and merge it.

2021-04-09 18:07 UTC, ankitaggarwal23 requested changes

2021-04-09 18:07 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +
- Use multiline comments
- Make it short and understandable
- Add a bit more description

2021-04-09 18:07 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +                    System.out.print(" "); //new line
Remove redundant comments

2021-04-09 18:07 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +                System.out.print(array[i][j]+" "); //Priting matrix as entered
Remove redundant comments

2021-04-09 18:07 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +                System.out.print(array[j][i]+" "); //Printing transposed matrix
Remove redundant comments

2021-04-09 18:07 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +                }
Align it properly braces are not aligned.

2021-04-09 18:07 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +            }
Remove extra braces. As code produces error.

2021-04-09 18:07 UTC, ankitaggarwal23 commented on Java/other/Transpose square matrix.java
> +*/
Rewrite it as,

```
/*
Sample Output:

Enter total rows and columns: 
3 3
Enter matrix:
1
2
3
4
5
6
7
8
9
The above matrix before Transpose is 
1 2 3  
4 5 6  
7 8 9  
The above matrix after Transpose is 
1 4 7  
2 5 8  
3 6 9

Time Complexity: 
Space Complexity: 
*/

```

Add TC and SC

2021-04-17 04:03 UTC, ankitaggarwal23 reviewed
Last Reminder, Are you still working on it.

2021-04-18 09:11 UTC, ankitaggarwal23 reviewed
Last Reminder, Are you still working on it.

2021-04-19 08:18 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity. Thank you for your valuable time.😊

2021-04-19 08:18 UTC, closed without merging