Fibonacci Series(Dp)
HarshCasper/NeoAlgo pull request #512
Opened 2020-08-17 08:26 UTC by ashishsahu1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-17 08:33 UTC, ashishsahu1 commented
![Screenshot1](https://user-images.githubusercontent.com/52550558/90375263-5985a800-e092-11ea-97e3-56fda5efcb57.jpg)
![Screenshot2](https://user-images.githubusercontent.com/52550558/90375271-5be80200-e092-11ea-9291-d554b7bda88a.jpg)

Outputs for both is some thing like this

2020-08-21 20:05 UTC, siddharth25pandey approved these changes
@ashishsahu1 Looks fine to me
Able to merge
 Thanks!

2020-08-22 07:07 UTC, Kajol-Kumari requested changes
@ashishsahu1 Minor changes required, rest Looks good to me :)

2020-08-22 07:07 UTC, Kajol-Kumari commented on Python/dp/fibinacci(TopDown).py
> +        print('Wrong choice')
please add one extra blank line at the end of the file.

2020-08-22 07:07 UTC, Kajol-Kumari commented on Python/dp/fibonacci(BottumUp).py
> +
please remove the unnecessary blank lines left here.

2020-08-23 12:38 UTC, ashishsahu1 commented
@Kajol-Kumari I have done with those changes.. can you review again

2020-11-03 00:17 UTC, closed without merging