Find repeating and missing number in array using CPP
HarshCasper/NeoAlgo pull request #5121
Opened 2021-04-05 20:58 UTC by shahina-bano

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added the solution for the problem in CPP

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

The issue is #5116

2021-04-06 08:49 UTC, ankitaggarwal23 requested changes
Shift the logic to another function and use main for driver code

2021-04-06 10:07 UTC, shahina-bano commented
> Shift the logic to another function and use main for driver code

I have done the changes, is it okay? Please let me know for any further changes @ankitaggarwal23

2021-04-09 07:40 UTC, ankitaggarwal23 requested changes

2021-04-09 07:40 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/repeated_missing.cpp
> +    //input the array elements
Remove the redundant comments instead write proper display message using `cout`

2021-04-09 07:40 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/repeated_missing.cpp
> +        cin >> input[i];
write proper display message using `cout`

2021-04-09 07:40 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/repeated_missing.cpp
> +Missing number: 5
Remove extra test case one is enough

2021-04-09 12:17 UTC, ankitaggarwal23 requested changes
LGTM.

2021-04-09 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Find repeating and missing number in array](other/repeated_missing.cpp)
Rewrite this ` [Find repeating and missing number in array]` to like that `[Repeating and Missing Number]`

2021-04-09 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/repeated_missing.cpp
> +*/
```
/*
Repeating and Missing number

Given an unsorted array of positive integers. The elements are in the range 1 to n where n is the size of array,
there is one number which is repeated and another number which is missing. Find these numbers and print them.
The approach used is that checking if the current element is in its desired position or not. It is, then simply iterate
for next, else put it in its desired position by comparing with its index number and swap it accordingly.

*/
```

2021-04-09 13:00 UTC, ankitaggarwal23 approved these changes

2021-04-09 13:00 UTC, merged