RRT Algorithm
HarshCasper/NeoAlgo pull request #5141
Opened 2021-04-06 08:18 UTC by shikha-16

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes!

### Description
Rapidly-exploring Random Trees for Robot Path Planning
A robot is attempting to navigate its path from the start point to a specified goal region, while avoiding the set of all obstacles.

In RRT, points are randomly generated within a specified radius and connected to the nearest existing node. Each time a node is created, we check that it lies outside of the obstacles. Furthermore, chaining the node to its closest neighbor must also avoid obstacles. The algorithm ends when a node is generated within the goal region, or a limit is hit

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5138

2021-04-08 06:06 UTC, shikha-16 commented
@ankitaggarwal23 please review

2021-04-09 07:49 UTC, ankitaggarwal23 requested changes
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-09 07:49 UTC, ankitaggarwal23 commented on Python/Pathfinding/2D_RRT.py
> +#The algorithm ends when a node is generated within the goal region, or a limit is hit.
Use Multi-Line Comments

2021-04-09 07:49 UTC, ankitaggarwal23 commented on Python/Pathfinding/2D_RRT.py
> +#have matplotlib and shapely installed
Remove one extra line and redundant comments

2021-04-09 07:49 UTC, ankitaggarwal23 commented on Python/Pathfinding/2D_RRT.py
> +
Use dynamic input from user with proper display message

2021-04-10 09:14 UTC, shikha-16 commented
@ankitaggarwal23 please check out #5462

2021-04-11 16:34 UTC, ankitaggarwal23 reviewed
Found two opened by you. Closing this PR

2021-04-11 16:34 UTC, closed without merging