Infix to Postfix Converter in JavaScript added
HarshCasper/NeoAlgo pull request #5152
Opened 2021-04-06 10:26 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#5082 )

2021-04-07 16:54 UTC, shivammahajancse commented
Sir please review it @ankitaggarwal23 @gat786 @siddharth25pandey @atarax665

2021-04-09 07:53 UTC, ankitaggarwal23 requested changes

2021-04-09 07:53 UTC, ankitaggarwal23 commented on JavaScript/README.md
> +- [Infix to Postfix Conversion in JavaScript](./ds/infixtopostfix.js)
Rewrite it as ` [Infix to Postfix Conversion]`

2021-04-09 07:53 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtopostfix.js
> +
Remove extra one line

2021-04-09 07:53 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtopostfix.js
> +            }
Align your code with proper format and remove redundant comments

2021-04-09 07:53 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtopostfix.js
> +
Remove extra lines

2021-04-09 07:53 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtopostfix.js
> +abcd^e-fgh*+^*+i-
- Write outputs with proper display message
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-09 07:54 UTC, ankitaggarwal23 reviewed
Add your code to repl.it and share the link as well.

2021-04-09 08:03 UTC, shivammahajancse commented
Repl link:- https://replit.com/join/hoabtdsf-shivammahajan4
All requested changes done @ankitaggarwal23

2021-04-09 17:56 UTC, ankitaggarwal23 requested changes

2021-04-09 17:56 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtopostfix.js
> +            }
Give a tab space before `pop()`

2021-04-09 17:56 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtopostfix.js
> +
Remove this lines

2021-04-09 17:56 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtopostfix.js
> +Postfix Expression: abcd^e-fgh*+^*+i-
Write proper display message while reading and printing the outputs

2021-04-10 03:57 UTC, shivammahajancse commented
Please review @ankitaggarwal23 sir

2021-04-11 09:20 UTC, atarax665 requested changes
Requested some minor fixes before we merge this PR.

2021-04-11 09:20 UTC, atarax665 commented on JavaScript/ds/infixtopostfix.js
> + InfixtoPostfix("((a+b)*c)");
Modify it for dynamic inputs

2021-04-11 09:20 UTC, atarax665 commented on JavaScript/ds/infixtopostfix.js
> +
Remove the extra blank line.

2021-04-12 10:45 UTC, ankitaggarwal23 approved these changes

2021-04-12 10:45 UTC, merged