Infix to Prefix Converter in JavaScript added
HarshCasper/NeoAlgo pull request #5153
Opened 2021-04-06 10:29 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#5083 )

2021-04-07 19:44 UTC, shivammahajancse commented
Sir please review it @ankitaggarwal23 @gat786 @siddharth25pandey @atarax665

2021-04-09 07:57 UTC, ankitaggarwal23 requested changes

2021-04-09 07:57 UTC, ankitaggarwal23 commented on JavaScript/README.md
> +- [Infix to Prefix Conversion in JavaScript](./ds/infixtoprefix.js)
Rewrite it as  `[Infix to Prefix Conversion]`

2021-04-09 07:57 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtoprefix.js
> + This project converts infix expression to prefix expression in JavaScript.
This is not a project rewrite to code

2021-04-09 07:57 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtoprefix.js
> +            }
Align your code with proper format and remove redundant comments

2021-04-09 07:57 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtoprefix.js
> +
Remove redundant comments and line

2021-04-09 07:57 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtoprefix.js
> ++a-*b^-^cde+f*ghi
- Write outputs with proper display message
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-09 07:57 UTC, ankitaggarwal23 reviewed
Add your code to repl.it and share the link as well.

2021-04-09 08:12 UTC, shivammahajancse commented
Repl link: https://replit.com/join/ijzcusnn-shivammahajan4
All requested changes done @ankitaggarwal23 sir

2021-04-09 17:59 UTC, ankitaggarwal23 requested changes

2021-04-09 17:59 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtoprefix.js
> +          pop();
Add a tab space before `pop`

2021-04-09 17:59 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtoprefix.js
> +Prefix Expression: *+abc
Remove these lines

2021-04-09 17:59 UTC, ankitaggarwal23 commented on JavaScript/ds/infixtoprefix.js
> +Prefix Expression: +a-*b^-^cde+f*ghi
Write proper display message while reading and printing the outputs

2021-04-10 04:06 UTC, shivammahajancse commented
Please review @ankitaggarwal23 sir.

2021-04-10 17:01 UTC, atarax665 approved these changes

2021-04-11 16:37 UTC, ankitaggarwal23 approved these changes

2021-04-11 16:37 UTC, merged