Busy Man
HarshCasper/NeoAlgo pull request #5156
Opened 2021-04-06 10:58 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Code added in cp(competitive programming) folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5072

2021-04-08 05:36 UTC, gayatri517 commented
@HarshCasper @ankitaggarwal23 please review my PR.

2021-04-08 16:27 UTC, gayatri517 commented
@siddharth25pandey please review my PR

2021-04-09 08:05 UTC, ankitaggarwal23 requested changes

2021-04-09 08:05 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/busy_man.cpp
> +    cin >> t;
Use proper naming conventions don't use single letter and also while reading inputs use cout for display proper message

What is `t`? Is it used for reading testcase then remove it as we don't have online judge for testcases.

2021-04-09 08:05 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/busy_man.cpp
> +    v.clear();
Use cout for display proper message. Remove` v.clear();`

2021-04-09 08:05 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/busy_man.cpp
> +2
Remove extra test case one is enough

2021-04-09 08:05 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/busy_man.cpp
> +Space Complexity: O(n) */
Add a new line at the end

2021-04-09 09:25 UTC, gayatri517 commented
@ankitaggarwal23 I have made the changes that were requested. Kindly review my PR.

2021-04-09 11:46 UTC, ankitaggarwal23 approved these changes

2021-04-09 11:46 UTC, merged