Minimum circles to be removed so that none are intersecting
HarshCasper/NeoAlgo pull request #5157
Opened 2021-04-06 11:04 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Code added in cp(competitive programming) folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5073

2021-04-08 05:36 UTC, gayatri517 commented
@HarshCasper @ankitaggarwal23 please review my PR.

2021-04-08 16:26 UTC, gayatri517 commented
@siddharth25pandey please review my PR

2021-04-09 08:07 UTC, ankitaggarwal23 requested changes

2021-04-09 08:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_circles_to_be_removed.cpp
> +    int n, c, r;
Use proper naming conventions don't use single letter and also while reading inputs use cout for display proper message

2021-04-09 08:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_circles_to_be_removed.cpp
> +    cin >> n;
Use cout for display proper message.

2021-04-09 08:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_circles_to_be_removed.cpp
> +        cin >> c >> r;
Use cout for display proper message.

2021-04-09 08:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_circles_to_be_removed.cpp
> +    cout << (n - ans) <<endl;
Use cout for display proper message.

2021-04-09 08:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_circles_to_be_removed.cpp
> +1
Remove extra test case one is enough

2021-04-09 08:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_circles_to_be_removed.cpp
> +Space Complexity: O(nlogn) */
Add a new line at the end

2021-04-09 09:18 UTC, gayatri517 commented
@ankitaggarwal23 I have made the changes that were requested. Please review it

2021-04-09 10:18 UTC, ankitaggarwal23 requested changes

2021-04-09 10:18 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_circles_to_be_removed.cpp
> +2
Write in a way your code is producing outputs

2021-04-09 11:09 UTC, gayatri517 commented
@ankitaggarwal23 I have made the changes. Please review

2021-04-09 11:47 UTC, ankitaggarwal23 approved these changes

2021-04-09 11:48 UTC, merged