add Fibonnaci Number
HarshCasper/NeoAlgo pull request #5159
Opened 2021-04-06 11:08 UTC by hemant2705

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description
The Fibonacci series is a series where the next term is the sum of pervious two terms.
The first two terms of the Fibonacci sequence is 0 followed by 1
So a program in kotlin to solve the same.
(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5158 
(Write your answer here.)

2021-04-09 08:12 UTC, ankitaggarwal23 requested changes

2021-04-09 08:12 UTC, ankitaggarwal23 commented on Kotlin/Maths/FibonacciNumber.kt
> +import java.util.Scanner                    //importing scanner
Remove the redundant comments

2021-04-09 08:12 UTC, ankitaggarwal23 commented on Kotlin/Maths/FibonacciNumber.kt
> +   var n :Int = reader.nextInt()            //Obtaining input from user
Remove the redundant comments

2021-04-09 08:12 UTC, ankitaggarwal23 commented on Kotlin/Maths/FibonacciNumber.kt
> +        t1 = t2                      //swapping the terms
Remove the redundant comments

2021-04-09 08:12 UTC, ankitaggarwal23 commented on Kotlin/Maths/FibonacciNumber.kt
> +    var t2 = 1
Don't use single letter for variable names use proper naming conventions

2021-04-09 08:12 UTC, ankitaggarwal23 commented on Kotlin/Maths/FibonacciNumber.kt
> +   var n :Int = reader.nextInt()            //Obtaining input from user
Don't use single letter for variable names use proper naming conventions

2021-04-09 08:12 UTC, ankitaggarwal23 commented on Kotlin/Readme.md
> +- [FibonacciNumber](Maths/FibonacciNumber.kt)
Rewrite it as `[Fibonacci Number]`

2021-04-09 16:11 UTC, hemant2705 commented
I have resloved all the changes suggested.
Please review it again sir.

2021-04-09 17:40 UTC, ankitaggarwal23 requested changes

2021-04-09 17:40 UTC, ankitaggarwal23 commented on Kotlin/Maths/FibonacciNumber.kt
> +Fibonacci series upto 5: 0 + 1 + 1 + 2 + 3
why you are adding + either remove it or place `,` or just add a space

2021-04-10 04:57 UTC, hemant2705 commented
I have replaced the+ sign with " , " as asked
please review it again.

2021-04-11 16:39 UTC, ankitaggarwal23 approved these changes

2021-04-11 16:40 UTC, merged