Added code to print the Row wise  sum in 2d array
HarshCasper/NeoAlgo pull request #5176
Opened 2021-04-06 14:10 UTC by Ritikakatoch0128

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-06 14:45 UTC, HarshCasper requested changes
Make Markdown Updates

2021-04-06 17:00 UTC, UG-SEP commented
@HarshCasper please check my pr #5145

2021-04-06 17:52 UTC, ankitaggarwal23 commented
@UG-SEP Don't spam other contributors PR. This is not the right way to ask for review by commenting other person PR.

2021-04-06 19:07 UTC, UG-SEP commented
> @UG-SEP Don't spam other contributors PR. This is not the right way to ask for review by commenting on other persons PR.

sorry for the that this will not from next time sorry @ankitaggarwal23

2021-04-07 13:31 UTC, Ritikakatoch0128 commented
@HarshCasper  I have updated the readme.md.

2021-04-07 14:26 UTC, HarshCasper requested changes

2021-04-07 14:26 UTC, HarshCasper commented on Java/README.md
> +- [RowWise_Sum]( Java/2d%20Array/RowWise_Sum.java)
This hyperlink is wrong.

2021-04-07 14:26 UTC, HarshCasper commented on Java/2d Array/RowWise_Sum.java
> + */
Keep the sample I/O at the end of the Code. And keep only one sample I/O

2021-04-07 14:26 UTC, HarshCasper commented on Java/2d Array/RowWise_Sum.java
> +2) Output for every test case will be printed in a seperate line.
No need to keep the I/O format

2021-04-07 14:26 UTC, HarshCasper commented on Java/2d Array/RowWise_Sum.java
> +i.e 1+2=3, 3+4=7, 5+6=11 and 7+8=15
No need of an example here. The sample I/O does the work

2021-04-07 16:19 UTC, ankitaggarwal23 reviewed
We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.  Closing this PR as of now. Open the new PR if you want this to be reviewed and add the proper details and do the mentioned changes requested by harsh.

2021-04-07 16:20 UTC, closed without merging