Check whether a number is a Perfect Number or not in C++
HarshCasper/NeoAlgo pull request #5182
Opened 2021-04-06 15:19 UTC by Aayushi-Mittal

…or not

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

A program to check whether a number is perfect number or not in C++.
Perfect number is a positive integer which is equal to the sum of its proper positive divisors.
For example: 6 is the first perfect number
Proper divisors of 6 are 1, 2, 3. Sum of its proper divisors = 1 + 2 + 3 = 6. Hence 6 is a perfect number.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4853

2021-04-08 13:11 UTC, Aayushi-Mittal commented
@HarshCasper Please review my PR.

2021-04-09 08:22 UTC, ankitaggarwal23 requested changes

2021-04-09 08:22 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/Perfect_Number.cpp
> +Output: 6 is a perfect number.
Add a new line after output

2021-04-09 08:22 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/Perfect_Number.cpp
> +using namespace std;
Add a new line above int main

2021-04-09 08:22 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/Perfect_Number.cpp
> +}
Shift the logic to another function and use main for driver code

2021-04-09 10:57 UTC, Aayushi-Mittal commented
@ankitaggarwal23  Made the required changes.

2021-04-09 11:50 UTC, ankitaggarwal23 requested changes

2021-04-09 11:50 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/Perfect_Number.cpp
> +int sumOfDivisors(int n)
Rename it to perfectnumber

2021-04-09 12:44 UTC, Aayushi-Mittal commented
@ankitaggarwal23 did the changes. Please review.

2021-04-09 12:48 UTC, ankitaggarwal23 approved these changes

2021-04-09 12:48 UTC, merged

2021-04-09 13:05 UTC, Aayushi-Mittal commented
Thank you so much!