adding level_order #401
HarshCasper/NeoAlgo pull request #520
Opened 2020-08-17 12:59 UTC by Jkp2072

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-17 13:02 UTC, Jkp2072 commented
@Kajol-Kumari  please do the review

2020-08-20 17:32 UTC, Jkp2072 commented
please review it @plazzy99  @Kajol-Kumari  @SKAUL05

2020-08-20 17:37 UTC, SKAUL05 requested changes

2020-08-20 17:37 UTC, SKAUL05 commented on C-Plus-Plus/graphs/level_order_traversal.cpp
> +     node * x =new node();
Use meaningful variable names instead of alphabets

2020-08-20 17:47 UTC, Jkp2072 commented
changes resolved.

2020-08-20 17:51 UTC, SKAUL05 requested changes

2020-08-20 17:51 UTC, SKAUL05 commented on C-Plus-Plus/graphs/level_order_traversal.cpp
> + for(auto i : anss) cout<<i<<" ";
Replace i

2020-08-20 18:11 UTC, Jkp2072 commented on C-Plus-Plus/graphs/level_order_traversal.cpp
> + for(auto i : anss) cout<<i<<" ";
okay sir

2020-08-20 18:22 UTC, Jkp2072 commented
changes done

2020-08-22 12:15 UTC, vatsalkesarwani12 commented
mention issue no.

2020-08-23 12:50 UTC, Jkp2072 commented
Do I have to mention it in code?? It is 401 which is in pr heading

2020-08-23 17:27 UTC, plazzy99 requested changes
add issue number

2020-08-24 10:05 UTC, Jkp2072 commented
issue number added

2020-08-24 14:48 UTC, plazzy99 requested changes

2020-08-24 14:48 UTC, plazzy99 commented on C-Plus-Plus/graphs/level_order_traversal.cpp
> + node * root =create(1); // level 1
take dynamic input

2020-12-07 00:24 UTC, closed without merging