Append last n to first linked list
HarshCasper/NeoAlgo pull request #5202
Opened 2021-04-06 19:47 UTC by anshika272

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
 given a singly linked list of integers along with an integer 'N'. Write a function to append the last 'N' nodes towards the front of the singly linked list and returns the new head to the list, Using Cpp.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
 issue #5200

2021-04-08 08:10 UTC, anshika272 commented
@HarshCasper  kindly please review the code.

2021-04-09 08:54 UTC, bhav09 requested changes
Minor changes need to be done. Rest fine.
Also, comment on your code a little more, it lacks that.

2021-04-09 08:54 UTC, bhav09 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +You have been given a singly linked list of integers along with an integer 'N'. Write a function to append the last 'N' nodes towards the front of the singly linked list and returns the new head to t
The description can be cut down to multiple lines. 
After every full stop, bring the sentence to the next line. Improves readablity.

2021-04-09 08:54 UTC, bhav09 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +Time Complexity-
Complexity has to be above Sample I/O

2021-04-09 10:05 UTC, anshika272 commented
@bhav09 please review the changes

2021-04-09 10:41 UTC, HarshCasper requested changes
Use comments above the line of code not beside it

2021-04-09 12:36 UTC, anshika272 commented
@HarshCasper  @bhav09  please review the changes

2021-04-11 04:55 UTC, anshika272 commented
@HarshCasper @bhav09 @ankitaggarwal23 please review the changes.

2021-04-17 04:07 UTC, ankitaggarwal23 requested changes

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +"Copyright [2021] <Anshika Dubey>"
remove the copyright comment line

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [AppendLastNToFirst](ds/AppendLastNToFirst - Linked List.cpp)
Rewrite it and also rename your file name as well 

`- [Append Last N To First](ds/Append_Last_N_To_First.cpp)`

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +// create a class node
Add a new line above comments

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +// taking input from the user for linked list
Add a new line above comments

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +//printing the linked list if head is given
Add a new line above comments

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +//finding the length of the linked list
Add a new line above comments

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +// function to append last n elements of linked list at front
Add a new line above comments

2021-04-17 04:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/AppendLastNToFirst - Linked List.cpp
> +	}
Remove the test case part as we don't have online judge.  Use proper display message how you are reading and writing outputs

2021-04-17 11:47 UTC, ankitaggarwal23 approved these changes

2021-04-17 11:47 UTC, merged