Implemented Post-order traversal in Go
HarshCasper/NeoAlgo pull request #5206
Opened 2021-04-07 05:01 UTC by nidh-ish

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented Post-order traversal in Go.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #5069

2021-04-08 07:30 UTC, nidh-ish commented
@HarshCasper Please review this PR.

2021-04-08 16:32 UTC, HarshCasper requested changes

2021-04-08 16:32 UTC, HarshCasper commented on Go/ds/binary_tree/post_order_traversal/Post_Order_Traversal.go
> +	root.right.right = new_node(7)
Can you add dynamic input?

2021-04-09 06:06 UTC, HarshCasper approved these changes

2021-04-09 06:06 UTC, merged