Kth largest
HarshCasper/NeoAlgo pull request #5217
Opened 2021-04-07 07:52 UTC by shonali2600

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-07 17:53 UTC, RaiyanMahin requested changes

2021-04-07 17:53 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +#include <queue>
remove `#include <queue>` and `#include <vector>`

2021-04-07 17:53 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +int findKthLargest(vector<int> &a, int k)
add a new line and a bit description about the function

2021-04-07 17:53 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +            if (u > heap.top()) //checking if there is another larger element that top of the heap remaining in the vector array.
use multi line comment

2021-04-07 17:53 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +    return heap.top(); //The element on the top of the heap after traversing the whole array will be the Kth Largest ELement.
use multi line comment

2021-04-07 17:53 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +    cout << "Enter the size of the vector array: ";
use proper variable names

2021-04-07 17:53 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +
remove extra lines of code

2021-04-07 18:36 UTC, shonali2600 commented
I've done all the required changes. Please review my PR again.

2021-04-08 06:37 UTC, RaiyanMahin requested changes

2021-04-08 06:37 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +/*
only one line description of your function.

2021-04-08 06:37 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +            if (u > heap.top()) /*checking if there is another element larger
use multi line comment.

2021-04-08 06:37 UTC, RaiyanMahin commented on C-Plus-Plus/heap/KthLargestElement.cpp
> +    return heap.top(); /*The element on the top of the heap after
use multi line comment.

2021-04-08 15:13 UTC, shonali2600 commented
Done, now please review my PR.

2021-04-08 15:31 UTC, RaiyanMahin approved these changes

2021-04-09 09:00 UTC, ankitaggarwal23 reviewed
Problem already available in Cpp section. Kindly check before opening any issue.

2021-04-09 09:00 UTC, closed without merging

2021-04-09 09:06 UTC, shonali2600 commented
@ankitaggarwal23 , No it is not there, I've checked. I've created pull request for "Kth largest" element, and in CPP section "Kth smallest" element program is present.

2021-04-09 12:24 UTC, ankitaggarwal23 commented
Kindly check it properly it there I checked and then only I'm telling

2021-04-09 12:52 UTC, RaiyanMahin commented
Ankit told about this one :
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/other/Kth_largest_element.cpp

2021-04-09 13:03 UTC, shonali2600 commented
ohh okay, i got it, I'm so sorry I was checking inside the heap folder and it is present inside the other folder

2021-04-12 16:11 UTC, HarshCasper commented
Hi @shonali2600 

What about writing an article on it? You can create an issue on NeoAlgo-Docs and get started with that :wink:

2021-04-12 16:22 UTC, shonali2600 commented
@HarshCasper Thanks for giving me the suggestion, I'll create an issue on that for the article.