Wi ng develop13
HarshCasper/NeoAlgo pull request #5218
Opened 2021-04-07 07:52 UTC by hemant2705

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Implementing all basic bit wise operation in Kotlin.
### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#5215

2021-04-07 13:08 UTC, hemant2705 commented
I mistakenly put pr name as the branch name.
Please consider it as per changes

2021-04-09 09:02 UTC, ankitaggarwal23 requested changes

2021-04-09 09:02 UTC, ankitaggarwal23 commented on Kotlin/BitManipulation/BasicBitOperations.kt
> +    println("Complement Operation :$result")
Remove redundant comments and Add your code to repl.it and share the link.

2021-04-09 16:35 UTC, hemant2705 commented
I have resolved everything as per changes 
repl link
https://replit.com/@HemantKumarKum1/IndolentDecentCommand#main.kt

2021-04-09 17:42 UTC, ankitaggarwal23 approved these changes

2021-04-09 17:42 UTC, merged