Parenthesis Checker #488 in java
HarshCasper/NeoAlgo pull request #522
Opened 2020-08-17 14:39 UTC by infoarpit

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-17 14:40 UTC, infoarpit commented
parenthesis checker in java added

2020-09-07 11:12 UTC, Kajol-Kumari requested changes
@infoarpit please attach one sample input/output and time complexity below the code section in commented form. Also i would recommend you to use some code formatter while writing the code.

2020-09-08 06:29 UTC, iamrajiv requested changes
@infoarpit Rename the file to `parenthesis_checker.java` and resolve the merge conflicts.

2020-09-08 06:49 UTC, infoarpit commented
@iamrajiv issue resolved

2020-09-08 08:08 UTC, iamrajiv requested changes

2020-09-08 08:08 UTC, iamrajiv commented on Java/cp/parenthesis_checker.java
> +Input: “[()]{}{[()()]()}”
@infoarpit remove quotation mark from the input because this can be misunderstood by the user.

2020-09-08 08:08 UTC, iamrajiv commented on Java/cp/parenthesis_checker.java
> +        int t= sc.nextInt();
@infoarpit we do not need the number of test cases so remove `int t= sc.nextInt();`

2020-11-16 00:19 UTC, closed without merging