Raksha
HarshCasper/NeoAlgo pull request #5225
Opened 2021-04-07 11:31 UTC by rakshakannu

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added code for Product of Array Except self in java, and updated the README file.

### Checklist

- [yes] I've read the contribution guidelines.
- [yes] I've checked the issue list before deciding what to submit.
- [yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

PR for #5223

2021-04-15 05:21 UTC, rakshakannu commented
May I know if any changes have to be made for this PR? @ankitaggarwal23 
also, would like to know why it has not been merged. thank you.

2021-04-17 04:09 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Use proper display message how you are reading and writing outputs

2021-04-18 09:08 UTC, ankitaggarwal23 requested changes

2021-04-18 09:08 UTC, ankitaggarwal23 commented on Java/other/ArrayProductExceptSelf.java
> +*/
- Don't write in such a way it doesn't look good 
- Add a beginner-friendly description at the top

2021-04-18 09:08 UTC, ankitaggarwal23 commented on Java/other/ArrayProductExceptSelf.java
> +
header missing

2021-04-18 09:08 UTC, ankitaggarwal23 commented on Java/other/ArrayProductExceptSelf.java
> +
remove extra test case max 2 is enough 
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

2021-04-22 03:35 UTC, ankitaggarwal23 reviewed
Last Reminder, Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-23 04:09 UTC, agamgupta2015 commented
please assign this issue to me

2021-04-26 09:04 UTC, closed without merging

2021-04-26 09:06 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity. Thank you for your valuable time.😊