Added max element in stack
HarshCasper/NeoAlgo pull request #5234
Opened 2021-04-07 15:00 UTC by sudipg4112001

Fixes #5232

2021-04-07 15:57 UTC, sudipg4112001 commented
Made the changes, please do review.

2021-04-09 09:17 UTC, ankitaggarwal23 requested changes

2021-04-09 09:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/Max_element.cpp
> +When the first element arrives, push it onto both of the stacks. As the elements may not be distinct, we need to keep track of their indices. So, declare a stack of pair<int,int> or use a structure.*
Make it short and readable

2021-04-09 09:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/Max_element.cpp
> +#include <stack>
Replace header with `#include <bits/stdc++.h>`

2021-04-09 09:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/Max_element.cpp
> +}
- Shift the logic to another function and use main for driver code
- Use proper variable naming conventions , Don't use short forms or single letters

2021-04-09 09:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/Max_element.cpp
> +        1 76
Remove extra test case , one is enough also use proper display message while reading and displaying the outputs

2021-04-09 09:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/stack/Max_element.cpp
> +/*  Time Complexicity: O(n)             Space Complexicity: O(n)
rewrite it as, 
```
Time Complexicity: O(n)             
Space Complexicity: O(n)
```

2021-04-09 09:19 UTC, ankitaggarwal23 requested changes

2021-04-09 09:19 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Maximum Element](C-Plus-Plus/stack/Max_element.cpp)
Rewrite it as `[Maximum Element using Stack](stack/Max_element.cpp)`

2021-04-09 09:20 UTC, ankitaggarwal23 requested changes
Kindly don't push from master branch, Closing this PR open a  new one and do the changes as I mentioned.

2021-04-09 09:21 UTC, closed without merging