code of issue 4759
HarshCasper/NeoAlgo pull request #5238
Opened 2021-04-07 15:51 UTC by PSoni8

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Added code of Remove Duplicates from sorted array using 2 pointer in cpp.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
code of issue 4759

2021-04-09 09:28 UTC, ankitaggarwal23 requested changes

2021-04-09 09:28 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/RemoveDuplicatesFromSortedArray.cpp
> +// Function removeDuplicates returns modified size of vector which is passed in this function initially.
Use Multi-Line Comments

2021-04-09 09:28 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/RemoveDuplicatesFromSortedArray.cpp
> +#include<vector>
Remove the header

2021-04-09 09:28 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/RemoveDuplicatesFromSortedArray.cpp
> +return nums.size();
Give a one tab space

2021-04-09 09:28 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/RemoveDuplicatesFromSortedArray.cpp
> +sample 1: Input - nums = [1,1,2] ; Output: 2, nums = [1,2]
Remove the redundant line

2021-04-09 09:28 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/RemoveDuplicatesFromSortedArray.cpp
> +Answer is 5
Remove the extra test case

2021-04-09 09:28 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Remove Duplicates From Sorted Array using 2 pointes](other/RemoveDuplicatesFromSortedArray.cpp)
Fix the typo `pointers`

2021-04-11 15:06 UTC, PSoni8 commented
@ankitaggarwal23 all suggested changes are modified . Please Check and Merge PR if all go nice.

2021-04-11 16:45 UTC, ankitaggarwal23 reviewed
Don't push more than one code file in a single PR.

2021-04-11 16:45 UTC, closed without merging

2021-04-11 16:45 UTC, ankitaggarwal23 commented
Closing this PR as of now. Open the new PR if you want this to be reviewed and add the proper details.