Activity Selection in python
HarshCasper/NeoAlgo pull request #5250
Opened 2021-04-07 17:40 UTC by shahina-bano

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added the solution code for activity selection in python

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #5114

2021-04-07 17:50 UTC, shahina-bano commented
@reviewers, I am facing an issue in deepsource python since it's showing errors of others code too.  So please help out.

2021-04-09 09:37 UTC, ankitaggarwal23 requested changes

2021-04-09 09:37 UTC, ankitaggarwal23 commented on Python/cp/activity_selection.py
> +1.
Remove this and rewrite it as `Sample Output:`

2021-04-09 09:37 UTC, ankitaggarwal23 commented on Python/cp/activity_selection.py
> +4
Use proper display message.

2021-04-09 09:37 UTC, ankitaggarwal23 commented on Python/cp/activity_selection.py
> +Following activities are selected :
Remove the extra test case

2021-04-09 10:42 UTC, shahina-bano commented
changes are done.

2021-04-09 12:02 UTC, ankitaggarwal23 requested changes
Rest looks good to merge

2021-04-09 12:02 UTC, ankitaggarwal23 commented on Python/cp/activity_selection.py
> +elements of row 3
Capitalize letter `E`

2021-04-09 12:55 UTC, shahina-bano commented
oops, sry for that capital thing, done now :) @ankitaggarwal23

2021-04-09 12:59 UTC, ankitaggarwal23 approved these changes

2021-04-09 12:59 UTC, merged