Added Minimum sum partition
HarshCasper/NeoAlgo pull request #5255
Opened 2021-04-07 18:49 UTC by Meghag5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description

(Write your answer here.)
This problem is solved using dp.
In this problem we have to find two subsets which will return minimum difference.
Input -
4
1 6 5 11
Output - 
1

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#5196

2021-04-09 10:03 UTC, ankitaggarwal23 requested changes

2021-04-09 10:03 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_sum_partition.cpp
> +*/
Remove this redundant description and add a proper description

2021-04-09 10:03 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_sum_partition.cpp
> +    }
Remove test case part as we are not using online judge use `cout` for proper display of input and Output.

2021-04-09 12:48 UTC, Meghag5 commented
pr updated @ankitaggarwal23 pls review

2021-04-09 18:34 UTC, ankitaggarwal23 requested changes

2021-04-09 18:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_sum_partition.cpp
> +#include <iostream>
Replace header with `#include <bits/stdc++.h>`

2021-04-09 18:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_sum_partition.cpp
> +        }
Remove redundant comments

2021-04-09 18:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_sum_partition.cpp
> +    // till value of matrix of last row do not return true we will decrese value of i by 1
Remove redundant comments and remove space and aligned it.

2021-04-09 18:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_sum_partition.cpp
> +}
Rewrite it like that,

```
int main()
{
    int N, ans;

    cout << "Enter the value of N: \n";
    cin >> N;
    int arr[N], sum = 0;

    //We will find the total sum of array to find the range of the array
    cout << "Enter the value of array: \n";
    for (int i = 0; i < N; i++)
    {
        cin >> arr[i];
        sum += arr[i];
    }


   ans = minimumSumPartition(arr, sum/2, N);

   if (sum & 1)
        ans++;

   cout << ans << "\n";

   return 0;
}
```

2021-04-09 18:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_sum_partition.cpp
> +*/
Rewrite it as

```
/*
Sample Output:

Input:
Enter the value of N:
4
Enter the value of array:
1 6 5 11

Output: 
1

Time Complexity - O(N*sum)
Space Complexity - O(N*sum)

*/
```

2021-04-09 19:10 UTC, Meghag5 commented
all changes made @ankitaggarwal23 pls review

2021-04-10 03:42 UTC, ankitaggarwal23 approved these changes

2021-04-10 03:43 UTC, merged

2021-04-16 13:58 UTC, gat786 commented
@ankitaggarwal23 this same codefile already exists in our repository. So, if this pr aims to improve the same file it should edit the same file and not create another file with same file name. I think after merging this PR there seems to be a problem on working with windows systems since their filenames are not case-sensitive