Added Check Alphabet, Digit, Special Character
HarshCasper/NeoAlgo pull request #5268
Opened 2021-04-07 20:12 UTC by Nidhideveloper

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Check Alphabet, Digit, Special Character 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5258

2021-04-07 20:13 UTC, Nidhideveloper commented
@HarshCasper Sir, Plz check the PR and and convey me for any problem with the code.

2021-04-09 10:14 UTC, ankitaggarwal23 requested changes

2021-04-09 10:14 UTC, ankitaggarwal23 commented on Java/other/Alpha_Digit_Spechar.java
> +            t--;
Remove the test case section as we don't have online judge to test

2021-04-09 10:15 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/program-check-input-character-alphabet-digit-special-character/)

2021-04-09 10:16 UTC, closed without merging