In-order tree traversal using python
HarshCasper/NeoAlgo pull request #527
Opened 2020-08-17 17:39 UTC by rutujadhanawade

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added In-order tree traversal Iterative program using python.  #415 
please review this @Abhijit2505 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#415 (Traversal in binary Tree)

2020-08-18 17:59 UTC, rutujadhanawade commented
@Kajol-Kumari will you please review this?, this PR is a part of CH20

2020-08-19 07:25 UTC, plazzy99 requested changes
do requested changes

2020-08-19 07:25 UTC, plazzy99 commented on Python/ds/Tree_Iterative_InOrder_Traversal.py
> +InOrdertree = Tree()
add an input message

2020-08-19 09:19 UTC, rutujadhanawade commented
> do requested changes

I have added Input message! please review this. @plazzy99

2020-08-19 13:56 UTC, Kajol-Kumari approved these changes
The code is working fine and LGTM!

2020-08-20 04:39 UTC, plazzy99 approved these changes
LGTM :)

2020-08-21 17:29 UTC, rutujadhanawade commented
@atarax665 Will you please review this .
@Kajol-Kumari and @plazzy99 Thank you for reviewing this PR.

2020-08-21 19:04 UTC, atarax665 approved these changes
Voila! Code looks fine to me. :100:

2020-08-21 19:04 UTC, merged

2020-08-30 04:19 UTC, iamrajiv commented
@all-contributors please add @rutujadhanawade for code