Path
HarshCasper/NeoAlgo pull request #5273
Opened 2021-04-08 04:05 UTC by ishwari20

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given an undirected graph G(V, E) and two vertices v1 and v2 (as integers), check if there exists any path between them or not. Print true if the path exists and false otherwise.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #5272

2021-04-09 10:23 UTC, bhav09 requested changes
Reviewed. 
Need to add more comments to the code.
Try to make main function as a "driver function" only.

2021-04-09 10:23 UTC, bhav09 commented on C-Plus-Plus/graphs/checkPath.cpp
> +
Please remove redundant lines.

2021-04-09 10:23 UTC, bhav09 commented on C-Plus-Plus/graphs/checkPath.cpp
> +Time Complexity: O(V+E)
Time complexity should be above Sample I/O

2021-04-09 20:14 UTC, bhav09 requested changes
Can you comment on the logic along with the code? 
Make sure, the comments are above the code lines.
Rest perfect.

2021-04-12 18:21 UTC, HarshCasper requested changes
Format the entire code

2021-04-12 18:21 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +
Remove this line

2021-04-12 18:21 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +
Remove this line

2021-04-12 18:21 UTC, HarshCasper commented on C-Plus-Plus/graphs/checkPath.cpp
> +Space Complexity: O(V^2)
Tell what `V` and `E` here signify

2021-04-12 18:21 UTC, HarshCasper commented on C-Plus-Plus/graphs/checkPath.cpp
> +	//If this adjacent node is the destination node, then return true
Indent the comments

2021-04-13 11:50 UTC, bhav09 commented
@ishwari20, There are a few unresolved issues in this PR. Please resolve them.

2021-04-15 09:36 UTC, ankitaggarwal23 requested changes

2021-04-15 09:36 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/checkPath.cpp
> +true
Use proper display message how you are reading and writing outputs

2021-04-17 04:11 UTC, ankitaggarwal23 requested changes
Do the changes mentioned.

2021-04-17 12:20 UTC, ankitaggarwal23 approved these changes

2021-04-17 12:20 UTC, merged