Palindrome Number
HarshCasper/NeoAlgo pull request #5279
Opened 2021-04-08 06:45 UTC by anshmishra010

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

To check whether  a number is palindrome or not .Without using extra space .

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Palindrome number check

2021-04-09 05:17 UTC, bhav09 commented on C-Plus-Plus/cp/Palindrome_number.cpp
> +        n=(n%divi)/10;  //reducing number to compare
Comments should be above the lines of code not alongside.

2021-04-09 05:18 UTC, bhav09 requested changes
Reviewed.

2021-04-09 05:18 UTC, bhav09 commented on C-Plus-Plus/cp/Palindrome_number.cpp
> +Description :
Description can be formated well.

2021-04-09 10:34 UTC, HarshCasper requested changes

2021-04-09 10:34 UTC, HarshCasper commented on C-Plus-Plus/cp/Palindrome_number.cpp
> +                                This code is implemented without using extra space.
Format this and left-align the same

2021-04-09 10:34 UTC, HarshCasper commented on C-Plus-Plus/cp/Palindrome_number.cpp
> +}
Use meaningful variable names

2021-04-10 08:43 UTC, HarshCasper approved these changes

2021-04-10 08:46 UTC, merged