Pull Request on Issue#4878
HarshCasper/NeoAlgo pull request #5280
Opened 2021-04-08 06:51 UTC by divya-rai-42

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
This pull request is under the issue#4878

2021-04-09 17:11 UTC, atarax665 requested changes

2021-04-09 17:11 UTC, atarax665 commented on C-Plus-Plus/README.md
> +- [Maximum element in each subarray of size k](cp/ma_element_in_k_size_subarray.cpp)
```suggestion
- [Maximum element in each subarray of size k](cp/max_element_in_k_size_subarray.cpp)
```

2021-04-09 17:11 UTC, atarax665 commented on C-Plus-Plus/cp/max_element_in_k_size_subarray.cpp
> +/*This algorithm uses deque. Only the significant elements of the current window are stored in the deque in decreasing
Edit the description. The objective of the program is not defined clearly.

2021-04-09 17:11 UTC, atarax665 commented on C-Plus-Plus/cp/max_element_in_k_size_subarray.cpp
> +    cin>>n;
Add input-output prompts to make the program more interactive.

2021-04-09 17:11 UTC, atarax665 commented on C-Plus-Plus/cp/max_element_in_k_size_subarray.cpp
> +        dq.push_back(i);//Adding new element to the current window
Shift the comment above the line of code.

2021-04-11 16:48 UTC, ankitaggarwal23 requested changes
Resolve merge conflicts as well

2021-04-12 04:00 UTC, divya-rai-42 commented
Sir, I have done the desired changes. Please review it further.

2021-04-12 19:04 UTC, divya-rai-42 commented
Can you please help me out why I am getting merge conflicts? When I resolved the previous issues, there were no conflicts. But after sometime , it shows merge conflicts. Is it because other commits have been done to the master branch of the main repo after I resolved the conflicts?
Also please tell me what is meant by label 'outdated'?

2021-04-15 03:28 UTC, divya-rai-42 commented
Sir, please help me out to resolve the merge conflicts and answer some of my queries that I have asked earlier!

2021-04-15 03:30 UTC, divya-rai-42 commented
Sir please guide me if I need to do more changes!

2021-04-16 20:36 UTC, divya-rai-42 commented
@ankitaggarwal23  Please review it

2021-04-17 04:13 UTC, ankitaggarwal23 requested changes

2021-04-17 04:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/max_element_in_k_size_subarray.cpp
> +
```
/*
Through this algorithm, we can find the maximum element in each of the k sized subarray.
The algorithm uses deque. Only the significant elements of the current window are stored in the deque in decreasing
order. The elements which are lesser than any of the elements of the deque and are to the left of that particular element
are insignificant. As the current window changes, significant values are updated.
 */
```
Rewrite like that

2021-04-17 04:13 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/max_element_in_k_size_subarray.cpp
> +  Sample Output: 7 7 7 5 8 9 9 */
Write the outputs in the way your code is producing.

2021-04-18 16:45 UTC, divya-rai-42 commented
@ankitaggarwal23  sir I have done the changes. Please review it!

2021-04-19 08:21 UTC, ankitaggarwal23 reviewed
Don't push more than one code file in a single PR.

2021-04-19 08:21 UTC, ankitaggarwal23 reviewed
Open the new PR if you want this to be reviewed and add the proper files

2021-04-19 08:21 UTC, closed without merging

2021-04-19 08:47 UTC, divya-rai-42 commented
@ankitaggarwal23  Sorry sir, but I had not attached two code files. It would be very grateful of you if you tell me which is the other file that I have added (maybe unknowingly) , so that I don't repeat this again. I am very new to github , so am unable to figure out which is the other file.

2021-04-19 10:05 UTC, ankitaggarwal23 commented
Minimum sum partition