Wiggle c
HarshCasper/NeoAlgo pull request #5287
Opened 2021-04-08 08:13 UTC by aish2002

Fixes #5197 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Wiggle sort in C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5197

2021-04-08 08:14 UTC, aish2002 commented
@ankitaggarwal23 , @HarshCasper  kindly review the PR

2021-04-09 17:40 UTC, atarax665 requested changes

2021-04-09 17:40 UTC, atarax665 commented on C/sort/Wiggle_sort.c
> +        int mid = (l + r) / 2;
Use ```mid = l + (r - l)  /  2``` to avoid overflow.

2021-04-09 17:40 UTC, atarax665 commented on C/sort/Wiggle_sort.c
> +    printf("[");
No need of enclosing the output sorted array in the bracket, you can print them normally.

2021-04-11 10:28 UTC, aish2002 commented
I have made the necessary changes. @atarax665 , @ankitaggarwal23  kindly re-review the PR

2021-04-11 16:49 UTC, ankitaggarwal23 reviewed
Don't push more than one code file in a single PR.
Closing this PR as of now. Open the new PR if you want this to be reviewed and add the proper Files.

2021-04-11 16:49 UTC, closed without merging