adding matrix transpose in javascript
HarshCasper/NeoAlgo pull request #5301
Opened 2021-04-08 09:54 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

issue #5296 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #5296

2021-04-11 16:51 UTC, ankitaggarwal23 approved these changes

2021-04-11 16:52 UTC, ankitaggarwal23 requested changes

2021-04-11 16:52 UTC, ankitaggarwal23 commented on JavaScript/math/Matrix_transpose.js
> +
Remove the extra two lines

2021-04-11 16:58 UTC, aaadddiii commented
@ankitaggarwal23  I have made the changes .

2021-04-12 07:52 UTC, ankitaggarwal23 approved these changes

2021-04-12 07:52 UTC, merged