Even-after-Odd in a LinkedList using C++
HarshCasper/NeoAlgo pull request #5331
Opened 2021-04-08 17:25 UTC by somya1252

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-08 17:32 UTC, HarshCasper requested changes

2021-04-08 17:32 UTC, HarshCasper commented on C-Plus-Plus/ds/even-after-odd_LinkedList.cpp
> +/* We arrange elements in a Linked List such that all even numbers are placed after odd numbers.
Can you add a bit more information?

2021-04-08 17:32 UTC, HarshCasper commented on C-Plus-Plus/ds/even-after-odd_LinkedList.cpp
> +*/
Keep the sample I/O for the purpose of examples

2021-04-08 17:32 UTC, HarshCasper commented on C-Plus-Plus/ds/even-after-odd_LinkedList.cpp
> +*/
Add a new line at the EOF

2021-04-11 16:59 UTC, ankitaggarwal23 requested changes
Resolve merge conflicts.

2021-04-17 04:15 UTC, ankitaggarwal23 requested changes
Do the changes mentioned

2021-04-18 09:09 UTC, ankitaggarwal23 reviewed
Last Reminder, Are you still working on it.

2021-04-19 08:22 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity. Thank you for your valuable time.😊

2021-04-19 08:22 UTC, closed without merging