#5260 Sum of Linked List
HarshCasper/NeoAlgo pull request #5337
Opened 2021-04-08 18:15 UTC by iamakkkhil

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5260

2021-04-11 17:04 UTC, ankitaggarwal23 requested changes

2021-04-11 17:04 UTC, ankitaggarwal23 commented on Python/ds/Sum_of_Linked_list.py
> +# Program to calculate sum of linked list.
- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-04-11 17:04 UTC, ankitaggarwal23 commented on Python/ds/Sum_of_Linked_list.py
> +head.push(50)
Don't use static inputs use dynamic inputs from user.

2021-04-11 17:04 UTC, ankitaggarwal23 commented on Python/ds/Sum_of_Linked_list.py
> +Time Complexity: O(n)
Remove extra two line and add SC as well

2021-04-11 17:04 UTC, ankitaggarwal23 commented
Resolve merge conflicts.

2021-04-13 19:15 UTC, iamakkkhil commented
Hey, I am not getting how to remove the merge conflict can have a look at it please

2021-04-14 07:29 UTC, ankitaggarwal23 reviewed
Always do `git pull `and then do the changes because it will update your repo with the changes added.

As I 'm closing this PR looks very confusing.

2021-04-14 07:29 UTC, closed without merging