Parenthesischecker
HarshCasper/NeoAlgo pull request #538
Opened 2020-08-17 18:56 UTC by stratospher

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Given a string input containing parenthesis check if parenthesis are balanced or not
Example:
Input: s="({})"
Output: yes

Input: s="[{(}])"
Output: yes

Input: s="(((}"
Output: no

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#488

2020-08-20 06:06 UTC, siddharth25pandey requested changes
@stratospher Update the README
* Only one issue at a time .You are updating for two issues.

2020-08-28 07:20 UTC, HarshCasper requested changes
Make these changes and it will be ready to merge

2020-08-28 07:20 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Stack](ds/Stack_Implementation.cpp)
Remove this reference. It seems you were trying to add two files together.

2020-08-28 07:20 UTC, HarshCasper commented on C-Plus-Plus/ds/stackParenthesisChecker.cpp
> +
Add sample Input and Output here

2020-08-28 07:20 UTC, HarshCasper commented on C-Plus-Plus/ds/stackParenthesisChecker.cpp
> +            if(s.empty())           //if not an opening bracket in  the beginning
Use comments above the code. Not beside it. Also prefer to use Multi-Line Comments

2020-11-05 00:18 UTC, closed without merging