All Unique Permutations in C++
HarshCasper/NeoAlgo pull request #5403
Opened 2021-04-09 14:58 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is a google interview question.
Code has been added in cp(competitive programming) folder.
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5396

2021-04-09 14:58 UTC, gayatri517 commented
@ankitaggarwal23 Kindly review my PR

2021-04-11 17:05 UTC, HarshCasper requested changes

2021-04-11 17:05 UTC, HarshCasper commented on C-Plus-Plus/cp/all_unique_permutation.cpp
> +return all possible unique permutations excluding the user input. */
Describe it properly

2021-04-11 17:15 UTC, ankitaggarwal23 reviewed
resolve merge conflicts.

2021-04-11 17:52 UTC, gayatri517 commented
@HarshCasper @ankitaggarwal23 I have made the changes and resolved the merge conflict
Kindly review it

2021-04-12 17:12 UTC, rohanbabbar04 commented
@gayatri517 
You still have merge conflicts

2021-04-12 18:00 UTC, gayatri517 commented
@HarshCasper @ankitaggarwal23 i have resolved the merge conflicts. Please review now

2021-04-14 04:54 UTC, bhav09 requested changes
Minor Changes. Reviewed.

2021-04-14 04:54 UTC, bhav09 commented on C-Plus-Plus/cp/all_unique_permutation.cpp
> +
Remove extra lines of code. These new lines are redundant to the code file.

2021-04-14 07:34 UTC, gayatri517 commented
@bhav09 I have made the changes and resolved the conflict also. Please look at it.

2021-04-14 07:46 UTC, ankitaggarwal23 approved these changes

2021-04-14 07:47 UTC, merged