Create Ackermann function (dart)
HarshCasper/NeoAlgo pull request #5408
Opened 2021-04-09 15:35 UTC by ashuvssut

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Create Ackermann function

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

closes #5407

2021-04-11 17:05 UTC, HarshCasper requested changes

2021-04-11 17:05 UTC, HarshCasper commented on Dart/maths/Ackermann_function.dart
> +import 'dart:io';
Add a beginner-friendly description

2021-04-11 17:05 UTC, HarshCasper commented on Dart/maths/Ackermann_function.dart
> +space complexity:- O(m) to compute A(m, n)
What do these `A(m, n)` mean? Can you please add a note?

2021-04-11 18:06 UTC, ankitaggarwal23 reviewed
Why code looks similar to gfg code,

![1](https://user-images.githubusercontent.com/67387053/114315881-a7b65280-9b1e-11eb-8815-265398e9dcac.JPG)
![2](https://user-images.githubusercontent.com/67387053/114315884-a9801600-9b1e-11eb-90b6-402fb8eccefb.JPG)

2021-04-11 18:11 UTC, ashuvssut commented
@ankitaggarwal23 

 in A(m,n),
    * If m=0, then A(m,n) = n+1
    * If m != 0 but n=0, A(m,n)=A(m-1,1)
    * If m and n both are not zero then... A(m,n) = A( m-1, A(m,n-1) )
    
upon these 3 conditions of an Ackermann function anyone would write the same code only

and about the time complexity lines... yes, i copied the two lines of the gfg article. I didn't find any direct answer in stackoverflow and stackexchange.

2021-04-14 03:35 UTC, ankitaggarwal23 requested changes
Remove the `.gitignore` file

2021-04-14 03:35 UTC, ankitaggarwal23 commented on Dart/maths/Ackermann_function.dart
> +space complexity:- O(m) to compute A(m, n)
Don't be lazy, Capitalize the first letter T and S, and what is mA?

2021-04-14 03:35 UTC, ankitaggarwal23 commented on Dart/maths/Ackermann_function.dart
> +*/
Write the output in the way your code is producing.

2021-04-14 10:16 UTC, ashuvssut commented
https://replit.com/@AshutoshKhandua/LimegreenSuperMosaic#main.dart

2021-04-14 10:34 UTC, ankitaggarwal23 approved these changes

2021-04-14 10:35 UTC, merged