add GitHub action to label DART code related issues
HarshCasper/NeoAlgo pull request #5413
Opened 2021-04-09 16:11 UTC by ashuvssut

closes #5412 

**Extra**: added more possible keywords to detect other languages😁😁

2021-04-09 18:16 UTC, atarax665 requested changes

2021-04-09 18:16 UTC, atarax665 commented on .github/labeler.yml
> +  - "(C-Plus-Plus|CPP|cpp|Cpp|C++)"
The action doesn't work for keyword ```C++```.

2021-04-11 08:51 UTC, atarax665 approved these changes
LGTM :) 
Thank you for your contribution. 
Happy Coding!!

2021-04-11 17:04 UTC, HarshCasper approved these changes

2021-04-11 17:04 UTC, merged