Sum of digits dart
HarshCasper/NeoAlgo pull request #5421
Opened 2021-04-09 17:42 UTC by Ayushjain2205

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code for sum of digits using dart added

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #5415

2021-04-09 18:05 UTC, atarax665 requested changes

2021-04-09 18:05 UTC, atarax665 commented on Dart/maths/SumOfDigits.dart
> +  int input = int.parse(stdin.readLineSync()!);
```suggestion
  int input = int.parse(stdin.readLineSync());
```

2021-04-09 18:05 UTC, atarax665 commented on Dart/maths/SumOfDigits.dart
> +// Calculate factorial of number
Factorial?

2021-04-09 18:05 UTC, atarax665 commented on Dart/maths/SumOfDigits.dart
> +  // Call factorial function
Factorial?

2021-04-09 18:05 UTC, atarax665 commented on Dart/maths/SumOfDigits.dart
> +Sum of digits in 401 is 50
```suggestion
Sum of digits in 401 is 5
```

2021-04-10 12:20 UTC, bhav09 requested changes
Minor Changes.

2021-04-10 12:20 UTC, bhav09 commented on Dart/maths/SumOfDigits.dart
> +Enter a number:
YOu need to add the time complexity of the code before sample I/O. Rest seems fine.

2021-04-10 15:22 UTC, Ayushjain2205 commented
@bhav09 Changes made

2021-04-10 16:53 UTC, atarax665 approved these changes
LGTM :)

2021-04-11 18:15 UTC, ankitaggarwal23 approved these changes

2021-04-11 18:15 UTC, merged