Added quick sort using C
HarshCasper/NeoAlgo pull request #5436
Opened 2021-04-10 02:51 UTC by shadowasphodel2919

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added quick sort using C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

https://github.com/TesseractCoding/NeoAlgo/issues/2238#issue-823716998

2021-04-10 08:42 UTC, HarshCasper requested changes

2021-04-10 08:42 UTC, HarshCasper commented on C/sort/quickSort.c
> +*/
Place this at the end of the code

2021-04-10 13:34 UTC, shadowasphodel2919 commented on C/sort/quickSort.c
> +*/
Yup I changed it's position.

2021-04-14 03:39 UTC, ankitaggarwal23 requested changes

2021-04-14 03:39 UTC, ankitaggarwal23 commented on C/sort/quickSort.c
> +are placed on the other side of the pivot element.*/
```
/*
OUICK SORT:

Quick Sort is a divide and conquer algorithm which works on the basic principle 
of finding a pivot element and dividing the elements in two parts that is, elements
smaller than pivot are kept on one side and the element larger than the pivot element 
are placed on the other side of the pivot element.
*/
```
rewrite it.

2021-04-14 03:39 UTC, ankitaggarwal23 commented on C/sort/quickSort.c
> +void printArray(int[], int);
remove this.

2021-04-14 03:39 UTC, ankitaggarwal23 commented on C/sort/quickSort.c
> +}
shift this main after the function ends

2021-04-17 04:21 UTC, ankitaggarwal23 requested changes
Do the changes mentioned

2021-04-17 20:35 UTC, shadowasphodel2919 commented
I have made the required changes @ankitaggarwal23

2021-04-18 08:55 UTC, ankitaggarwal23 approved these changes

2021-04-18 08:56 UTC, merged