Neon number dart
HarshCasper/NeoAlgo pull request #5443
Opened 2021-04-10 05:10 UTC by Ayushjain2205

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Dart program to check if a number is neon number added

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixed #5416

2021-04-10 12:18 UTC, bhav09 requested changes
Reviewed. Minor changes.

2021-04-10 12:18 UTC, bhav09 commented on Dart/maths/NeonNumber.dart
> +Sample input/output:
You need to mention the time complexity of the program here.

2021-04-10 15:17 UTC, Ayushjain2205 commented
@bhav09 Changes made

2021-04-11 18:32 UTC, ankitaggarwal23 approved these changes

2021-04-11 18:33 UTC, merged