Added Combinational sum without repeating the values
HarshCasper/NeoAlgo pull request #5450
Opened 2021-04-10 07:42 UTC by vedant-jain03

…me file

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

[Yes]

### Description

(Write your answer here.)

- I have added code of Combination sum without repeating the array values.
- I have checked that this code is not available in repository
- I have added test cases and description as well

### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5448 
(Write your answer here.)

2021-04-10 07:54 UTC, vedant-jain03 commented
@HarshCasper @ankitaggarwal23 Please review

2021-04-10 09:01 UTC, HarshCasper requested changes

2021-04-10 09:01 UTC, HarshCasper commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +
Use Multi-Line Comments and shorten the line

2021-04-10 09:01 UTC, HarshCasper commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +// [2,6,]
Use Muti-Line Comments and add a new line at the EOF

2021-04-10 09:01 UTC, HarshCasper commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +    cin>>n; // number of element in the given array
Redundant Comment

2021-04-10 09:01 UTC, HarshCasper commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +        find(arr,ans,r,target,0);
Format the Code

2021-04-10 11:08 UTC, vedant-jain03 commented
@HarshCasper Review my changes

2021-04-11 10:38 UTC, HarshCasper requested changes

2021-04-11 10:38 UTC, HarshCasper commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +Note that Same element from given array should not occur more then one time
Modularize this piece of content

2021-04-11 10:38 UTC, HarshCasper commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +    return ans;
Format the Code

2021-04-11 10:38 UTC, HarshCasper commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +        }
Format the Code

2021-04-11 11:09 UTC, vedant-jain03 reviewed
Formatted the code  and Modularize the Description

2021-04-14 03:47 UTC, ankitaggarwal23 requested changes

2021-04-14 03:47 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +*/
rewrite it, also fix typo `ary`
```

/*
The problem states that Given an array of integer and a target value. 
Return all the unique combination of array where chosen number sum to 
target. You may return combination in any order. (Note that each element 
in returned array should occur one time only)
*/
```

2021-04-14 03:47 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +void find(vector<int> arr, vector<vector<int>> &ans, vector<int> &r, int sum, int start)
Add a new line above after `std;`

2021-04-14 03:47 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Combination_sum_without_Repeated_values.cpp
> +*/
Use proper display message how you are reading and writing outputs. 
Add Time and Space Complexity at the end of the Code

2021-04-14 04:11 UTC, vedant-jain03 reviewed
Updated

2021-04-14 07:22 UTC, ankitaggarwal23 requested changes

2021-04-14 07:22 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Combination Sum without Reating the Values](cp/Combination_sum_without_Repeated_values.cpp)
Fix typo what is `reating`

2021-04-14 09:58 UTC, vedant-jain03 reviewed
Updated typo

2021-04-14 10:09 UTC, ankitaggarwal23 approved these changes

2021-04-14 10:09 UTC, merged