Added code in C++ and updated Readme file
HarshCasper/NeoAlgo pull request #5460
Opened 2021-04-10 08:24 UTC by vedant-jain03

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Dividing Tasks to student is CP problem that state that There are N students in the class, i'th student has Ci task in his collection. Your task is to determine if it is possible to redistribute C1 + C2 + ... + Cn task among the student of class thus that i'th student would get i task.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixes #5456

2021-04-10 08:27 UTC, vedant-jain03 commented
@ankitaggarwal23 @HarshCasper

2021-04-10 09:03 UTC, HarshCasper requested changes

2021-04-10 09:03 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Divind Task to Students](cp/Dividing_task.cpp)
Typo here

2021-04-10 09:03 UTC, HarshCasper commented on C-Plus-Plus/cp/Dividing_task.cpp
> +#include <bits/stdc++.h>
Use multi-line comments and add a more intuitive documentation here

2021-04-10 09:03 UTC, HarshCasper commented on C-Plus-Plus/cp/Dividing_task.cpp
> +// NO
Use Multi-Line Comments

2021-04-10 09:03 UTC, HarshCasper commented on C-Plus-Plus/cp/Dividing_task.cpp
> +int main()
Don't put the code logic in `main()` function. Keep it in another function and use `main()` for the driver code

2021-04-10 10:50 UTC, vedant-jain03 reviewed
Resolvd Issue and commit

2021-04-10 10:52 UTC, vedant-jain03 commented
@HarshCasper Review my Changes

2021-04-11 10:36 UTC, HarshCasper requested changes

2021-04-11 10:36 UTC, HarshCasper commented on C-Plus-Plus/cp/Dividing_task.cpp
> +The problem states that, there are N students in the class, i'th student has assign Ci number of task. Your task is to determine if it is possible to redistribute C1 + C2 + ... + Cn task among the st
Modularize this statement to make it crisp and easy to understand.

2021-04-11 10:36 UTC, HarshCasper commented on C-Plus-Plus/cp/Dividing_task.cpp
> +    int t;
No need of test cases here. Only one sample I/O is enough

2021-04-11 10:36 UTC, HarshCasper commented on C-Plus-Plus/cp/Dividing_task.cpp
> +    else cout<<"NO\n";
Format the Code

2021-04-11 10:36 UTC, HarshCasper commented on C-Plus-Plus/cp/Dividing_task.cpp
> +*/
Add a new line at the EOF

2021-04-11 13:41 UTC, vedant-jain03 reviewed
Code updated and formatted

2021-04-11 13:45 UTC, closed without merging