Unique number
HarshCasper/NeoAlgo pull request #5476
Opened 2021-04-10 11:03 UTC by anshmishra010

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

In the given range , print all numbers having unique digits.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Added a code in c++ in cp folder and updated readme

2021-04-10 11:35 UTC, HarshCasper requested changes

2021-04-10 11:35 UTC, HarshCasper commented on C-Plus-Plus/cp/Unique_number.cpp
> +       Unique Number : In the given range, print all numbers having unique digits.
Add a description about what are unique digits

2021-04-10 12:05 UTC, HarshCasper approved these changes

2021-04-10 12:05 UTC, merged

2021-04-14 11:04 UTC, ankitaggarwal23 reviewed
Great!