Updated readme.md and created fibonacci.c using dp
HarshCasper/NeoAlgo pull request #556
Opened 2020-08-18 06:35 UTC by chandansahuji

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

//C program to efficiently calculate the nth fibonacci term using DP memoization

### Checklist

- [✅ ] I've read the contribution guidelines.
- [✅ ] I've checked the issue list before deciding what to submit.
- [ ✅ I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#466  C language implementation

2020-08-18 06:36 UTC, chandansahuji commented
@Kajol-Kumari  @Abhijit2505 Please review this ,if any corrections are needed further please guide me.
Thanks

2020-09-02 22:02 UTC, Kajol-Kumari approved these changes
Hey @chandansahuji EVerything is working fine. Just add a check on the number input. Currently it's accepting the values <=0 which shouldn't happen. please show proper message to the users for wrong input. 

Rest LGTM :)

2020-09-03 17:04 UTC, siddharth25pandey requested changes

2020-09-03 17:04 UTC, siddharth25pandey commented on C/dp/Fibonacci.c
> +int f[1000];
Take dynamic size array using malloc

2020-09-05 13:49 UTC, plazzy99 approved these changes
Code Looks Good to me

2020-09-12 19:03 UTC, atarax665 approved these changes
Rest LGTM :) Make the suggested changes ASAP so that I can merge this PR.

2020-09-12 19:03 UTC, atarax665 commented on C/dp/Fibonacci.c
> +/* Author : Chandan Kumar Sahu (@chandansahuji)
Add time and space complexity of your code.

2020-09-13 06:25 UTC, chandansahuji commented
Done @Kajol-Kumari  @atarax665  @plazzy99

2020-09-13 17:58 UTC, merged