issue #5527
HarshCasper/NeoAlgo pull request #5560
Opened 2021-04-11 10:06 UTC by RYzen-009

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description
I have created a pull request for the issue  #5527 created on 11 April 2021
Left rotate array by d added to cp folder of the cpp file with proper explaination
Please review my pr

Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

2021-04-13 11:36 UTC, bhav09 requested changes
Reviewed.

2021-04-13 11:36 UTC, bhav09 commented on C-Plus-Plus/cp/leftarraybyd.cpp
> +	swap(arr[start],arr[end]);             //swap function
Comments should be above the line of the code and not alongside.

2021-04-13 11:36 UTC, bhav09 commented on C-Plus-Plus/cp/leftarraybyd.cpp
> +}
Mention the following things in this order:
1. Time complexity
2. Sample I/O

2021-04-13 11:36 UTC, bhav09 commented on C-Plus-Plus/cp/leftarraybyd.cpp
> +this will reverse in O(n) time
Remove complexity and Sample IO and mention them at EOF.

2021-04-16 05:34 UTC, bhav09 requested changes
Reviewed.

2021-04-16 05:34 UTC, bhav09 commented on C-Plus-Plus/cp/leftarraybyd.cpp
> +s*/
You need to add comments to the code. Remember the comments should be above the line segment of the code and not alongside. Also make a new line at EOF .

2021-04-16 07:58 UTC, RYzen-009 commented on C-Plus-Plus/cp/leftarraybyd.cpp
> +s*/
what do we you mean by make a new line at EOF

2021-04-16 09:29 UTC, bhav09 commented on C-Plus-Plus/cp/leftarraybyd.cpp
> +s*/
End Of FIle* :)

2021-04-16 10:00 UTC, closed without merging