Playfair cipher in python - CH20
HarshCasper/NeoAlgo pull request #558
Opened 2020-08-18 06:39 UTC by sharanya02

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes.

### Description

Imlementation of playfair cipher using python for CH20

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-18 06:46 UTC, sharanya02 commented
@SKAUL05 please review it and let me know if I should make any changes.Thank you!

2020-08-18 07:17 UTC, SKAUL05 requested changes
Why two files

2020-08-18 07:26 UTC, plazzy99 commented on playfair.py
> +key=input("Enter the key : ")
delete this file

2020-08-18 07:43 UTC, sharanya02 commented on playfair.py
> +key=input("Enter the key : ")
Yes done.

2020-08-18 07:44 UTC, sharanya02 commented
> Why two files
That was by mistake. I deleted the second file.

2020-08-18 08:19 UTC, plazzy99 commented
edit readme.md

2020-08-18 12:01 UTC, sharanya02 commented
> edit readme.md

Done.

2020-08-18 12:25 UTC, SKAUL05 requested changes

2020-08-18 12:25 UTC, SKAUL05 commented on Python/cryptography/playfair.py
> +for c in key:
Use meaningful names instead of alphabets.

2020-08-18 12:25 UTC, SKAUL05 commented on Python/cryptography/playfair.py
> +def locindex(c):
Use Docstrings to document code.

2020-08-23 06:48 UTC, sharanya02 commented on Python/cryptography/playfair.py
> +def locindex(c):
Done.

2020-08-23 06:49 UTC, sharanya02 commented
@plazzy99 @SKAUL05 Can you please review the code again now after the changes?

2020-08-23 07:56 UTC, SKAUL05 commented
Resolve conflicts

2020-08-23 17:24 UTC, plazzy99 requested changes
Enter the key : abc

 1.Encryption 
 2.Decryption: 
 3.Exit 
 Enter Your Choice: 1
ENTER MSG : hello
CIPHER TEXT: KC NV MP 
 1.Encryption 
 2.Decryption: 
 3.Exit 
 Enter Your Choice: 2
ENTER CIPHER TEXT:hello
PLAIN TEXT: KC FF 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-a0792602bbe2> in <module>()
    107         encrypt()
    108     elif ch==2:
--> 109         decrypt()
    110     elif ch==3:
    111         break;

<ipython-input-1-a0792602bbe2> in decrypt()
     92         loc=locindex(msg[i])
     93         loc1=list()
---> 94         loc1=locindex(msg[i+1])
     95         if loc[1]==loc1[1]:
     96             print("{}{}".format(my_matrix[(loc[0]-1)%5][loc[1]],my_matrix[(loc1[0]-1)%5][loc1[1]]),end=' ')

IndexError: string index out of range


make changes so that if cipher text is not correct code should not crash instead show an error or warning message

2020-08-30 07:16 UTC, atarax665 commented
@sharanya02 Do the suggested changes and resolve the conflict to get this PR merged ASAP.

2020-08-30 08:49 UTC, sharanya02 commented
> @sharanya02 Do the suggested changes and resolve the conflict to get this PR merged ASAP.

Done.Can you review it? Thank you!

2020-08-30 15:38 UTC, sharanya02 commented
> Enter the key : abc
> 
> ## 1.Encryption
> 2.Decryption:
> 3.Exit
> Enter Your Choice: 1
> ENTER MSG : hello
> CIPHER TEXT: KC NV MP
> 1.Encryption
> 2.Decryption:
> 3.Exit
> Enter Your Choice: 2
> ENTER CIPHER TEXT:hello
> PLAIN TEXT: KC FF
> IndexError Traceback (most recent call last)
> in ()
> 107 encrypt()
> 108 elif ch==2:
> --> 109 decrypt()
> 110 elif ch==3:
> 111 break;
> 
> in decrypt()
> 92 loc=locindex(msg[i])
> 93 loc1=list()
> ---> 94 loc1=locindex(msg[i+1])
> 95 if loc[1]==loc1[1]:
> 96 print("{}{}".format(my_matrix[(loc[0]-1)%5][loc[1]],my_matrix[(loc1[0]-1)%5][loc1[1]]),end=' ')
> 
> IndexError: string index out of range
> 
> make changes so that if cipher text is not correct code should not crash instead show an error or warning message

Done.

2020-08-30 16:39 UTC, plazzy99 requested changes

2020-08-30 16:39 UTC, plazzy99 commented on Python/README.md
> -    <img src="../img/neo_algo.png"><br>
why made so many changes .

2020-08-30 16:39 UTC, plazzy99 commented on Python/cryptography/playfair.py
> +        print("Choose correct choice")
add a sample test case in comment

2020-08-30 19:33 UTC, sharanya02 commented on Python/cryptography/playfair.py
> +        print("Choose correct choice")
Done

2020-08-31 13:14 UTC, plazzy99 approved these changes

2020-09-02 22:08 UTC, Kajol-Kumari requested changes
@sharanya02 please do the following changes:
1. Resolve the conflict
2. I am seeing here a lot of unnecessary changes in readme, please revert these and make only the changes required for this PR.

2020-09-04 11:55 UTC, Kajol-Kumari requested changes
@sharanya02 please incorpporate the following changes:
1. Remove unnecessary changes from `readme.md`
2. Resolve the conflict.

2020-09-12 19:04 UTC, atarax665 commented
I am closing this PR due to inactivity from the contributor's side.

2020-09-12 19:04 UTC, closed without merging