Matrix Subtraction in C
HarshCasper/NeoAlgo pull request #5586
Opened 2021-04-11 20:27 UTC by abhijeet141

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Matrix Subtraction in C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5580

2021-04-11 21:15 UTC, abhijeet141 commented
Respected Mentors please review my PR

2021-04-12 14:18 UTC, RaiyanMahin requested changes

2021-04-12 14:18 UTC, RaiyanMahin commented on C/math/matrix_subtraction.c
> +//C program to implement Matrix Subtraction
add a new line after `#include<stdio.h>`

2021-04-12 14:18 UTC, RaiyanMahin commented on C/math/matrix_subtraction.c
> +void sub(int r1, int c1, int mat1[r1][c1], int mat2[r1][c1])
add one line description about the function.

2021-04-12 14:18 UTC, RaiyanMahin commented on C/math/matrix_subtraction.c
> +    //If number of rows and columns of matrix 1 and matrix 2 are different then they cannot be subtracted
use multi line comment

2021-04-12 14:18 UTC, RaiyanMahin commented on C/math/matrix_subtraction.c
> +*/
add new line at EOF

2021-04-12 14:18 UTC, RaiyanMahin commented on C/math/matrix_subtraction.c
> +    {   for(int j = 0; j < c1; j++)
align code properly

2021-04-12 16:26 UTC, HarshCasper requested changes

2021-04-12 16:26 UTC, HarshCasper commented on C/math/matrix_subtraction.c
> +//C program to implement Matrix Subtraction
Add a bit more information about your code here

2021-04-12 16:26 UTC, HarshCasper commented on C/math/matrix_subtraction.c
> +*/
Add a new line at the EOF

2021-04-12 16:26 UTC, HarshCasper commented on C/math/matrix_subtraction.c
> +void sub(int r1, int c1, int mat1[r1][c1], int mat2[r1][c1])
Use meaningful variable names

2021-04-12 16:26 UTC, HarshCasper commented on C/math/matrix_subtraction.c
> +    int i, j , r1, r2, c1, c2;
Use meaningful variable names

2021-04-12 19:49 UTC, abhijeet141 commented
@HarshCasper I have made all changes please review it once

2021-04-14 04:20 UTC, ankitaggarwal23 requested changes

2021-04-14 04:20 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +                printf("Subtraction of the given matrices is not possible.");
Remove the redundant comments and left align it one tab space is enough

2021-04-14 04:33 UTC, abhijeet141 commented
@ankitaggarwal23 made changes please check

2021-04-14 07:21 UTC, ankitaggarwal23 requested changes

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +#include <stdio.h>
Add a new line after header

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +//Function that takes input of both matrices
Add a new line above comments

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +int main()
Add a new line above main

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +}
Align it properly

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +Space Complexity: O(r * c)
Add a new line after SC

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +
Remove one extra line

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +
Remove one extra line

2021-04-14 07:21 UTC, ankitaggarwal23 commented on C/math/matrix_subtraction.c
> +*/
Add a new line at the end

2021-04-14 08:10 UTC, abhijeet141 commented
@ankitaggarwal23 please check

2021-04-14 08:21 UTC, ankitaggarwal23 approved these changes

2021-04-14 08:21 UTC, merged