Transpose of a Matrix in C
HarshCasper/NeoAlgo pull request #5587
Opened 2021-04-11 21:13 UTC by abhijeet141

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Transpose of a matrix in C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-11 21:14 UTC, abhijeet141 commented
Respected Mentors please review my PR

2021-04-12 07:22 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-12 07:35 UTC, abhijeet141 commented
> Few changes:
> 
> * Add Multi-Line Comments
> * Add a beginner-friendly description at the top
> * Use proper code Format
> * Remove extra lines of code and spaces
> * Add sample I/O at the end of the Code
> * Add Time and Space Complexity at the end of the Code
> * Add new line at the EOF

I will make all changes but please check i have added sample input and output at the end of the code

2021-04-12 08:21 UTC, ankitaggarwal23 commented
> > Few changes:
> > 
> > * Add Multi-Line Comments
> > * Add a beginner-friendly description at the top
> > * Use proper code Format
> > * Remove extra lines of code and spaces
> > * Add sample I/O at the end of the Code
> > * Add Time and Space Complexity at the end of the Code
> > * Add new line at the EOF
> 
> I will make all changes but please check i have added sample input and output at the end of the code

Okay

2021-04-12 20:52 UTC, abhijeet141 commented
@ankitaggarwal23  I have made all changes please review it once

2021-04-14 04:24 UTC, ankitaggarwal23 requested changes

2021-04-14 04:24 UTC, ankitaggarwal23 commented on C/math/matrix_transpose.c
> +*/
rewrite it,

```
/*

Sample Output:

Enter the number of rows in matrix = 3
Enter the number of columns in matrix = 3

Enter the values in matrix  -->
1   2   3
4   5   6
7   8   9

Transpose of a matrix is -->
1       4       7
2       5       8
3       6       9

Time Complexity : O(mn) 
Space Complexity : O(mn)  
where,
	m = number of rows 
	n = number of columns

*/
```

2021-04-14 04:44 UTC, abhijeet141 commented
@ankitaggarwal23 made changes please check

2021-04-14 07:17 UTC, ankitaggarwal23 approved these changes

2021-04-14 07:17 UTC, merged