Added Decimal to Octal Conversion
HarshCasper/NeoAlgo pull request #5595
Opened 2021-04-12 04:18 UTC by UG-SEP

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes, I have 

### Description

I added decimal to octal conversion program in c->math .This program convert decimal number into octal

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
closes: #5508 
Please review it @HarshCasper and @siddharth25pandey

2021-04-12 04:20 UTC, UG-SEP commented on C/math/Decimal to Octal.c
> +#include<stdio.h>
should i add math.h header file or not

2021-04-12 04:20 UTC, UG-SEP commented on C/math/Decimal to Octal.c
> +Time complexity:O(n)
is this time complexity is correct or not

2021-04-13 12:50 UTC, UG-SEP commented
@HarshCasper @ankitaggarwal23 @siddharth25pandey please review it

2021-04-14 04:37 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format

2021-04-14 07:56 UTC, UG-SEP commented
> * Add Multi-Line Comments

I have added Multi-Line comments where needed

2021-04-14 07:57 UTC, UG-SEP commented
> * Use proper code Format

2021-04-15 09:44 UTC, ankitaggarwal23 requested changes
Use proper code Format

2021-04-15 10:29 UTC, UG-SEP commented
> Use proper code Format

what is improper please let me know @ankitaggarwal23

2021-04-17 06:23 UTC, ankitaggarwal23 requested changes
- Use proper code Format

2021-04-18 09:13 UTC, ankitaggarwal23 reviewed
Use proper code Format

2021-04-18 09:44 UTC, closed without merging