adding climbing stairs in javascript
HarshCasper/NeoAlgo pull request #5606
Opened 2021-04-12 08:17 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #5604 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #5604

2021-04-12 15:46 UTC, aaadddiii commented
@ankitaggarwal23  @HarshCasper  can you please review and merge my pr

2021-04-14 04:39 UTC, ankitaggarwal23 requested changes

2021-04-14 04:39 UTC, ankitaggarwal23 commented on JavaScript/dp/Climbing_stairs.js
> +The number of ways to climb the stairs is : 8
Write the output in the way your code is producing

2021-04-15 09:53 UTC, aaadddiii commented
@ankitaggarwal23  @HarshCasper  I have made the changes please review it

2021-04-15 09:54 UTC, ankitaggarwal23 approved these changes

2021-04-15 09:55 UTC, merged