adding pascal's triangle in c
HarshCasper/NeoAlgo pull request #5608
Opened 2021-04-12 08:29 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #5607 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #5607

2021-04-12 15:47 UTC, aaadddiii commented
@ankitaggarwal23  @HarshCasper  can you please review my pr

2021-04-14 04:41 UTC, ankitaggarwal23 requested changes

2021-04-14 04:41 UTC, ankitaggarwal23 commented on C/math/Pascals_triangle.c
> +1 6 15 20 15 6 1
Use proper display message how you are writing outputs

2021-04-15 09:17 UTC, aaadddiii commented
@ankitaggarwal23  I have made the changes can you please review my pr

2021-04-15 09:45 UTC, ankitaggarwal23 approved these changes

2021-04-15 09:45 UTC, merged