Added Sqrt monotonic binary search in cpp
HarshCasper/NeoAlgo pull request #5610
Opened 2021-04-12 08:36 UTC by satcasm

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added  Sqrt monotonic binary search in cpp

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5418

2021-04-12 08:39 UTC, satcasm commented
@ankitaggarwal23 @HarshCasper please review my PR.

2021-04-14 04:51 UTC, ankitaggarwal23 requested changes

2021-04-14 04:51 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Sqrt_Monotonic_Binary_Search.cpp
> +// In this algorithm we will find the square root of a number `n` upto `p` digits after decimal using the binary search algorithm.
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-04-14 04:51 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Sqrt_Monotonic_Binary_Search.cpp
> +#include <iostream>
replace header with `#include <bits/stdc++.h>`

2021-04-14 04:51 UTC, ankitaggarwal23 commented on C-Plus-Plus/search/Sqrt_Monotonic_Binary_Search.cpp
> +	while (s <= e)
remove redundant comments and use proper naming conventions for variables

2021-04-15 04:46 UTC, satcasm commented on C-Plus-Plus/search/Sqrt_Monotonic_Binary_Search.cpp
> +#include <iostream>
Done.

2021-04-15 04:47 UTC, satcasm commented
Hey @ankitaggarwal23  made the asked changes, kindly have a review.
Thanks!

2021-04-15 09:46 UTC, ankitaggarwal23 approved these changes

2021-04-15 09:46 UTC, merged