Magic number dart
HarshCasper/NeoAlgo pull request #5615
Opened 2021-04-12 09:43 UTC by Ayushjain2205

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code added to check if a number is a magic number or no

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #5585

2021-04-13 12:22 UTC, bhav09 requested changes
Share a replit link and have a look at the changes I have asked for. 
Thanks

2021-04-13 12:22 UTC, bhav09 commented on Dart/maths/MagicNumber.dart
> +*/
Add a new line here.

2021-04-13 12:36 UTC, Ayushjain2205 commented
@bhav09 Changes made and here is the [replit link](https://replit.com/@Ayushjain2205/Magic-number)

2021-04-14 04:47 UTC, ankitaggarwal23 approved these changes

2021-04-14 04:48 UTC, merged