Wiggle sort in C
HarshCasper/NeoAlgo pull request #5623
Opened 2021-04-12 10:41 UTC by aish2002

#5287 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added wiggle sort in C

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5287

2021-04-12 10:41 UTC, aish2002 commented
@ankitaggarwal23 , @HarshCasper , @siddharth25pandey  kindly review the PR

2021-04-14 05:40 UTC, ankitaggarwal23 requested changes

2021-04-14 05:40 UTC, ankitaggarwal23 commented on C/sort/Wiggle_sort.c
> +     2 3 1 3 1 2
Use proper display message how you are reading and writing outputs

2021-04-14 05:40 UTC, ankitaggarwal23 commented on C/sort/Wiggle_sort.c
> +/*
remove extra test case

2021-04-14 10:13 UTC, aish2002 commented
Necessary changes are made. @ankitaggarwal23 kindly re-review the PR

2021-04-14 10:14 UTC, ankitaggarwal23 approved these changes

2021-04-14 10:14 UTC, merged