Update find_duplicate_elements_from_an_array.cpp
HarshCasper/NeoAlgo pull request #5629
Opened 2021-04-12 11:06 UTC by AnushkaS09

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-14 05:34 UTC, ankitaggarwal23 requested changes

2021-04-14 05:34 UTC, ankitaggarwal23 commented on C-Plus-Plus/other/find_duplicate_elements_from_an_array.cpp
> +#include<unordered_map>
remove the header

2021-04-14 05:35 UTC, ankitaggarwal23 requested changes
add the readme as well

2021-04-16 11:06 UTC, ankitaggarwal23 requested changes
Add header file `#include <bits/stdc++.h>`

2021-04-17 06:25 UTC, ankitaggarwal23 requested changes
Code produces error cross check missing braces

2021-04-18 09:14 UTC, ankitaggarwal23 requested changes
Do the changes mentioned

2021-04-19 08:26 UTC, ankitaggarwal23 reviewed
Last Reminder, Are you still working on it.

2021-04-19 09:04 UTC, AnushkaS09 commented
Yes, I am working on it will do the changes required by today

2021-04-20 10:21 UTC, ankitaggarwal23 approved these changes

2021-04-20 10:21 UTC, merged

2021-04-20 10:24 UTC, ankitaggarwal23 reviewed
Problem already present #3518

2021-04-20 10:55 UTC, AnushkaS09 commented
@ankitaggarwal23 yes but the method is different and shorter I have created this PR on the already existing problem only and have not created an issue of the same problem  again