Added Printing subsequence
HarshCasper/NeoAlgo pull request #5632
Opened 2021-04-12 11:50 UTC by Meghag5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description

(Write your answer here.)
This problem will be solved using dp.
We will be given two strings and we have to find the longest
common string b/w two and will have to print it's subsequence.
Input -
Enter string X and string Y -
abcdaf
aebcf
Output -
Longest Common Subsequence -
abcf

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#5603

2021-04-12 17:58 UTC, HarshCasper requested changes
Format the Code as well

2021-04-12 17:58 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Printing Longest Common Subsequence](dp/Printing_LCSubsequence .cpp)
Improper filename

2021-04-12 18:51 UTC, Meghag5 commented
@HarshCasper pls review pr updated

2021-04-14 05:36 UTC, ankitaggarwal23 reviewed
Problem already present #3316

2021-04-14 05:36 UTC, closed without merging