Queue using stacks in C++
HarshCasper/NeoAlgo pull request #5642
Opened 2021-04-12 13:07 UTC by aish2002

Fixes #5635 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description

Implemented queue using 2 stacks in C++

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5635

2021-04-12 13:07 UTC, aish2002 commented
@ankitaggarwal23 , @HarshCasper  kindly review the PR

2021-04-14 06:09 UTC, ankitaggarwal23 requested changes

2021-04-14 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/Queue_using_Stacks.cpp
> +*/
```
/*  

QUEUE USING STACKS
A queue can be implemented using 2 stacks.

Enqueue operation proceeds by:
Popping second stack and pushing into first stack
till second stack becomes empty. New value is then
pushed into the first stack.

Dequeue operation proceeds by:
Popping first stack and pushing into second stack
till first stack becomes empty. Thus first element
appears at the top of second stack. Second stack is
then popped.

*/
```

rewrite it

2021-04-14 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/Queue_using_Stacks.cpp
> +#include <bits/stdc++.h>
Add `using namespace std;` after `#include <bits/stdc++.h>`

2021-04-14 06:09 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/Queue_using_Stacks.cpp
> +*/
Rewrite it like that,

```
/*
SAMPLE I/O:

Choose an option
1. Enqueue
2. Dequeue
3. Display
4. Exit
Option : 1
Enter the value : 1
Option : 1
Enter the value : 2
Option : 1
Enter the value : 3
Option : 2
Option : 1
Enter the value : 4
Option : 3
2 3 4
Option : 4

Time Complexity: O(n) 
Space complexity : O(n)

*/
```

2021-04-14 10:03 UTC, aish2002 commented
Necessary changes are made. @ankitaggarwal23  kindly re-review the PR

2021-04-14 10:10 UTC, ankitaggarwal23 approved these changes

2021-04-14 10:10 UTC, merged