Added the QuickSort Code in Kotlin
HarshCasper/NeoAlgo pull request #5646
Opened 2021-04-12 13:45 UTC by PriyanshuChatterjee

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the contributing guidelines.

### Description

Quicksort is based on the partitioning of an array of data into smaller arrays. A large array is partitioned into two arrays one of which holds values smaller than the specified value, say pivot, based on which the partition is made and another array holds values greater than the pivot value. Quicksort partitions an array and then calls itself recursively twice to sort the two resulting subarrays. This algorithm is quite efficient for large-sized data sets as its average and worst-case complexity are O(n2), respectively.

### Checklist

- [ x ] I've read the contribution guidelines.
- [ x ] I've checked the issue list before deciding what to submit.
- [ x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I created an issue. The link of the issue is: #5348

2021-04-12 16:37 UTC, PriyanshuChatterjee commented
@HarshCasper Please review this code.

2021-04-14 06:00 UTC, ankitaggarwal23 requested changes
Update the readme as well

2021-04-14 06:00 UTC, ankitaggarwal23 commented on Kotlin/sort/QuickSort/src/QuickSort.kt
> +//Kotlin program to implement QuickSort using recursive approach
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-04-14 06:00 UTC, ankitaggarwal23 commented on Kotlin/sort/QuickSort/src/QuickSort.kt
> +//Main Driver Code
add a new line above comments

2021-04-14 06:00 UTC, ankitaggarwal23 commented on Kotlin/sort/QuickSort/src/QuickSort.kt
> +Ordered list: [22, 23, 23, 54, 55, 67, 90]
Remove extra test case and Add Time and Space Complexity at the end of the Code

2021-04-15 13:06 UTC, PriyanshuChatterjee commented
@ankitaggarwal23 All the changes are done. Please Review it.

2021-04-17 06:27 UTC, ankitaggarwal23 requested changes

2021-04-17 06:27 UTC, ankitaggarwal23 commented on Kotlin/sort/QuickSort/src/QuickSort.kt
> +//Importing the Java.util package, it is needed because we are using the scanner object.
remove such redundant comments 
- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-04-17 06:27 UTC, ankitaggarwal23 commented on Kotlin/sort/QuickSort/src/QuickSort.kt
> +Original List: 34	33	67	3	2
45 missing in original list

2021-04-17 06:27 UTC, ankitaggarwal23 commented on Kotlin/sort/QuickSort/src/QuickSort.kt
> +Space Complexity: O(log n)[Average]
remove the average

2021-04-18 09:14 UTC, ankitaggarwal23 reviewed
Do the changes mentioned

2021-04-18 10:04 UTC, PriyanshuChatterjee commented
@ankitaggarwal23 Changes Done.

2021-04-18 10:12 UTC, ankitaggarwal23 requested changes
Readme missing

2021-04-18 14:07 UTC, PriyanshuChatterjee commented
@ankitaggarwal23 Added the Readme. Sorry didn't get you in the first go.

2021-04-19 08:07 UTC, ankitaggarwal23 approved these changes

2021-04-19 08:07 UTC, merged