Shubha028
HarshCasper/NeoAlgo pull request #565
Opened 2020-08-18 08:47 UTC by shubha028

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Longest Common Subsequence using DP in java

### Checklist

- [ x ] I've read the contribution guidelines.
- [ x ] I've checked the issue list before deciding what to submit.
- [ x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#438 using java language

2020-08-23 21:29 UTC, Kajol-Kumari requested changes
@shubha028 please do the following changes. 
1. Resolve the conflict
2. Format your code with proper indentation tool. 
3. Attach one sample input/output after the code section in commented form

2020-08-23 21:58 UTC, iamrajiv requested changes
@shubha028 In addition to @Kajol-Kumari suggestions add time and space complexity. Also, make sure sample input-output, time and space complexity are in multiline comments something like this at the end of the program.
```
/*
...
*/
```

2020-08-24 04:38 UTC, plazzy99 requested changes
make requested changes

Also, add Space and time Complexity in the comment

2020-08-24 04:38 UTC, plazzy99 commented on Java/dp/LCS.java
> +}
Add sample input and output in comments

2020-09-09 11:20 UTC, shubha028 commented
@Kajol-Kumari @iamrajiv @plazzy99  I have made the requested changes  and resolved the conflict .Please check

2020-09-09 13:42 UTC, iamrajiv approved these changes

2020-09-10 18:23 UTC, plazzy99 approved these changes

2020-09-11 13:57 UTC, Kajol-Kumari approved these changes
LGTM :)

2020-09-11 18:03 UTC, merged

2020-09-11 18:25 UTC, iamrajiv commented
@all-contributors please add @shubha028 for code