Dijsktra Algorithm
HarshCasper/NeoAlgo pull request #5651
Opened 2021-04-12 14:56 UTC by Khushi-agarwal

Fixes #5340 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
This Pr solves the issue #5340

2021-04-12 14:57 UTC, Khushi-agarwal commented
@bhav09 @HarshCasper Kindly review it.

2021-04-14 06:19 UTC, ankitaggarwal23 requested changes

2021-04-14 06:19 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Dijsktra.java
> +            System.out.println(i + " \t\t " + dist[i]); //Prints the distance in the form of table
Remove redundant comments

2021-04-14 06:19 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Dijsktra.java
> +                graph[i][j]=sc.nextInt();//creation of graph
Remove redundant comments

2021-04-14 06:19 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Dijsktra.java
> +The edge between two vertices having minimum distance is considered and also no vertex is left alone and not connected*/
rewrite it as,

```
/*

Problem Description-
This is a shortest path algorithm used in graphs which is used to find 
the shortest distance from a starting vertex to all the vertex. The edge 
between two vertices having minimum distance is considered and also no vertex 
is left alone and not connected.

*/
```

2021-04-14 06:19 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Dijsktra.java
> +}
Add a tab space and align braces

2021-04-14 06:19 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Dijsktra.java
> +        System.out.println("Vertex \t & Distance from Source");
remove `&`

2021-04-14 06:19 UTC, ankitaggarwal23 commented on Java/Greedy_Algorithms/Dijsktra.java
> +is being taken as 0,that is, the first vertex*/
rewrite it as,
```
/*
Input/Output

Enter number of vertices
3
Enter graph
0
0
2
0
0
0
6
7
0

Vertex 	 Distance from Source
0 		 0
1 		 9
2 		 2

Time Complexity:
Space Complexity:

*/
```
- Add Time and Space Complexity at the end of the Code   
- Remove the explanation

2021-04-14 06:19 UTC, ankitaggarwal23 commented on Java/README.md
> +- [Dijsktra](Greedy_Algorithms/Dijsktra.java)
rewrite only this part as `- [Dijsktra Algorithm]`

2021-04-15 15:04 UTC, Khushi-agarwal commented
@ankitaggarwal23 I have made all the changes as told by you and have created a new pr which is #5914.Kindly have a look.

2021-04-17 06:32 UTC, ankitaggarwal23 reviewed
Why you are creating new PR everytime for changes requested this is the last time don't repeat do the changes in same PR.

2021-04-17 06:32 UTC, closed without merging

2021-04-17 06:34 UTC, Khushi-agarwal commented
Actually my system crashed so that's why I couldn't access this,so had to create a new pr. Sorry for the inconvenience.

2021-04-17 06:35 UTC, Khushi-agarwal commented
> Why you are creating new PR everytime for changes requested this is the last time don't repeat do the changes in same PR.

Actually my system crashed so that's why I couldn't access this,so had to create a new pr. Sorry for the inconvenience.

2021-04-17 06:43 UTC, ankitaggarwal23 commented
Okay I already merged