Implementation of queue using stack & vice-versa
HarshCasper/NeoAlgo pull request #567
Opened 2020-08-18 09:04 UTC by Himanshu44626748

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implementation of queue using stack and stack using queue.

### Checklist

- [✔ ] I've read the contribution guidelines.
- [✔] I've checked the issue list before deciding what to submit.
- [✔] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-18 10:20 UTC, Himanshu44626748 commented
@siddharth25pandey @Kajol-Kumari can you please review my PR

2020-08-18 12:14 UTC, siddharth25pandey requested changes
@Himanshu44626748 Please do required modifications
* For more better user friendly interface, take input from the user.
* Display relevant success message after each operation.
*  Make a count function to count total number of elements present at that time.

2020-08-18 19:04 UTC, Kajol-Kumari requested changes
Hey @Himanshu44626748 please incorporate the suggested changed and it will be good to go :)

2020-08-18 19:04 UTC, Kajol-Kumari commented on Java/ds/QueueandStack.java
> +		obs.push(1);
Please take the input from user instead of hardcoding it .

2020-08-18 19:04 UTC, Kajol-Kumari commented on Java/ds/QueueandStack.java
> +5 4 3 2 1  */
Please add one extra blank line at the end of the file.

2020-08-18 19:04 UTC, Kajol-Kumari commented on Java/ds/QueueandStack.java
> +		Qs obq = new Qs(5);		//Creating an object of Qs class
Please take the size inputs from user.

2020-08-18 19:04 UTC, Kajol-Kumari commented on Java/ds/QueueandStack.java
> +	public Qs(int s)
Please provide a more meaningful name maybe `QueueUsingStack` ?

2020-08-18 19:04 UTC, Kajol-Kumari commented on Java/ds/QueueandStack.java
> +class Sq {
Can you please give the class a more meaningful name like `StackUsingQueue`

2020-08-19 14:35 UTC, Himanshu44626748 commented
@siddharth25pandey @Kajol-Kumari I have modified my code as per your instruction. Please review it.

2020-08-19 15:55 UTC, siddharth25pandey approved these changes
@Himanshu44626748 Looks fine to me
Able to merge
Thanks!

2020-08-19 16:20 UTC, iamrajiv approved these changes

2020-08-19 16:42 UTC, Kajol-Kumari approved these changes
Perfect!
This can be merged now :)

2020-08-19 16:43 UTC, merged

2020-08-23 22:02 UTC, iamrajiv commented
@all-contributors please add @Himanshu44626748 for code