Added Egg Dropping problem in Java - Fix for the Issue #5144 and PR #5676
HarshCasper/NeoAlgo pull request #5677
Opened 2021-04-13 00:19 UTC by Jahnavi-Majji

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Imagine there is a building of N floors and you have K eggs.
How many minimum number of attempts it would take to find the minimum floor (or first floor) F (0 <= f <= N)  where any egg dropped at a floor higher than f will break, and any egg dropped at or below the floor f will not break.

## Related Issues or Pull Requests

Fix for issue #5144 and the PR #5676

2021-04-13 00:19 UTC, Jahnavi-Majji commented
Kindly review my PR @HarshCasper @ankitaggarwal23 :)

2021-04-14 06:53 UTC, ankitaggarwal23 requested changes

2021-04-14 06:53 UTC, ankitaggarwal23 commented on Java/dp/EggDroppingProblem.java
> +
Remove the extra one line

2021-04-14 06:53 UTC, ankitaggarwal23 commented on Java/dp/EggDroppingProblem.java
> +
Remove the extra one line

2021-04-14 07:22 UTC, Jahnavi-Majji commented on Java/dp/EggDroppingProblem.java
> +
Removed.

2021-04-14 07:23 UTC, ankitaggarwal23 approved these changes

2021-04-14 07:23 UTC, merged