WaveForm Sort
HarshCasper/NeoAlgo pull request #5705
Opened 2021-04-13 17:08 UTC by TidbitsJS

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added program to create a WaveForm sort in JavaScript

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Closes: #5704

2021-04-14 08:19 UTC, ankitaggarwal23 requested changes

2021-04-14 08:19 UTC, ankitaggarwal23 commented on JavaScript/sort/WaveFormSort.js
> +
Remove extra line from the end

2021-04-14 16:09 UTC, TidbitsJS commented
Kindly check @ankitaggarwal23 :)

2021-04-16 14:39 UTC, HarshCasper approved these changes

2021-04-16 14:45 UTC, merged