readme updated and sort file added
HarshCasper/NeoAlgo pull request #5729
Opened 2021-04-13 18:48 UTC by Khushi-agarwal

Fixes #5711 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

It is a python program which is used to sort list having tuples in ascending order on the basis of last element of tuple.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
The PR solves the issue #5711

2021-04-13 18:49 UTC, Khushi-agarwal commented
@bhav09 @ankitaggarwal23 kindly review it

2021-04-14 04:43 UTC, bhav09 requested changes
Reviewed.

2021-04-14 04:43 UTC, bhav09 commented on Python/sort/ListTuplesort.py
> +def lys(ls):
Function definition should always be above driver code.

2021-04-14 04:43 UTC, bhav09 commented on Python/sort/ListTuplesort.py
> +ls=list(tuple(map(int,input().split()))for r in range(int(input('enter number of elements'))))
Can you use a main function in the driver code

2021-04-14 04:43 UTC, bhav09 commented on Python/sort/ListTuplesort.py
> +Input/Output-
Need to add complexity above Sample IO

2021-04-14 04:43 UTC, bhav09 commented on Python/sort/ListTuplesort.py
> +'''
Add a new line at EOF

2021-04-14 05:29 UTC, Khushi-agarwal commented
@bhav09 I have made the required changes.Kindly review.

2021-04-14 05:35 UTC, merged