Fibonacci search in c#
HarshCasper/NeoAlgo pull request #5735
Opened 2021-04-13 20:16 UTC by Mihir0106

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added the code for fibonacci search using C#

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5732

2021-04-13 20:18 UTC, Mihir0106 commented
@HarshCasper Please review this PR.

2021-04-14 09:50 UTC, ankitaggarwal23 requested changes
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-04-14 09:50 UTC, ankitaggarwal23 commented on C-Sharp/search/Fibonacci_Search.cs
> +// Space Complexity - O(1)
- Remove the line
- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-04-14 09:50 UTC, ankitaggarwal23 commented on C-Sharp/search/Fibonacci_Search.cs
> +    {
Rewrite it like that
```
public static int FibMonaccianSearch(int[] arr, int x, int n)
{
```

2021-04-14 09:50 UTC, ankitaggarwal23 commented on C-Sharp/search/Fibonacci_Search.cs
> +        int fibM = fibMMm2 + fibMMm1; // m'th Fibonacci
Remove the redundant comments

2021-04-16 18:35 UTC, ankitaggarwal23 requested changes

2021-04-16 18:35 UTC, ankitaggarwal23 commented on C-Sharp/search/Fibonacci_Search.cs
> +Space Complexity - O(1)
Shift this to the end of code

2021-04-17 06:34 UTC, ankitaggarwal23 requested changes
Do the changes mentioned

2021-04-18 08:26 UTC, ankitaggarwal23 approved these changes

2021-04-18 08:26 UTC, merged