Staircase search using c
HarshCasper/NeoAlgo pull request #5739
Opened 2021-04-13 21:48 UTC by ShubhamGupta577

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES
### Description

Added the code for Staircase searching using C language
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5736

2021-04-13 21:50 UTC, ShubhamGupta577 commented
@bhav09, Please review this PR and add the required labels to it.

2021-04-14 10:17 UTC, ankitaggarwal23 requested changes

2021-04-14 10:17 UTC, ankitaggarwal23 commented on C/search/Staircase_Search.c
> +*/
Shift this TC and SC to the end

2021-04-14 10:17 UTC, ankitaggarwal23 commented on C/search/Staircase_Search.c
> +#include<stdlib.h>    //Header file for malloc function
Remove redundant comments

2021-04-14 10:17 UTC, ankitaggarwal23 commented on C/search/Staircase_Search.c
> +
Remove redundant comments

2021-04-14 11:30 UTC, ankitaggarwal23 approved these changes

2021-04-14 11:30 UTC, merged