BreadthFirstSearch in C
HarshCasper/NeoAlgo pull request #574
Opened 2020-08-18 13:11 UTC by kulsoomzahra

Breadth First Search Algorithm in C.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-19 15:48 UTC, siddharth25pandey approved these changes
@kulsoomzahra Looks fine to me.
Able to merge.
Thanks

2020-08-19 16:28 UTC, atarax665 requested changes

2020-08-19 16:28 UTC, atarax665 commented on C/BreadthFirstSearch.c
> +}
Add sample input/output in the end.

2020-08-19 16:28 UTC, atarax665 commented on C/BreadthFirstSearch.c
> +BFS Implementation In C:
Comment out this line.

2020-08-19 16:28 UTC, atarax665 commented on C/BreadthFirstSearch.c
> +
Add docstring to every function for better understanding.

2020-08-20 04:41 UTC, plazzy99 requested changes
edit readme 
also, select the checklist

2020-10-16 18:35 UTC, atarax665 commented
Closing this PR as there is no update from contributor's side.

2020-10-16 18:35 UTC, closed without merging