Printing superstring
HarshCasper/NeoAlgo pull request #5762
Opened 2021-04-14 07:31 UTC by Meghag5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description
This problem will be solved using dp.
We will be given two strings and we have to find the shortest
common superstring b/w two and will have to print it's superstring.
Input -
Enter string X and string Y -
abcdaf
aebcf
Output -
Shortest Common Subsequence -
aebcdaf

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#5758

2021-04-14 09:39 UTC, ankitaggarwal23 reviewed
Problem Already opened by someone before you opened  #5767

2021-04-14 09:44 UTC, Meghag5 commented
`hey @ankitaggarwal23 in thi problem i am printing the string and in above problem the length was returned 
Pls check `

2021-04-14 09:51 UTC, ankitaggarwal23 commented
That person also doing the same thing. Have to check before opening an issue

2021-04-14 09:57 UTC, Meghag5 commented
<img width="441" alt="Screenshot 2021-04-14 at 3 25 50 PM" src="https://user-images.githubusercontent.com/65459236/114691834-b32f9680-9d35-11eb-891a-84544bc22b81.png">
she is printing the length and I am printing string
<img width="372" alt="Screenshot 2021-04-14 at 3 27 48 PM" src="https://user-images.githubusercontent.com/65459236/114692142-fa1d8c00-9d35-11eb-969a-62cb4a0d2f36.png">

2021-04-14 10:07 UTC, ankitaggarwal23 commented
> <img alt="Screenshot 2021-04-14 at 3 25 50 PM" width="441" src="https://user-images.githubusercontent.com/65459236/114691834-b32f9680-9d35-11eb-891a-84544bc22b81.png">
> 
> she is printing the length and I am printing string
> <img alt="Screenshot 2021-04-14 at 3 27 48 PM" width="372" src="https://user-images.githubusercontent.com/65459236/114692142-fa1d8c00-9d35-11eb-969a-62cb4a0d2f36.png">
> 
> code is different for the both

Oh okay Do one thing Dm me this link on discord `Ankit Aggarwal#2811` I will clarify with that participant because will let you know by evening.

2021-04-14 10:31 UTC, ankitaggarwal23 commented
> <img alt="Screenshot 2021-04-14 at 3 25 50 PM" width="441" src="https://user-images.githubusercontent.com/65459236/114691834-b32f9680-9d35-11eb-891a-84544bc22b81.png">
> 
> she is printing the length and I am printing string
> <img alt="Screenshot 2021-04-14 at 3 27 48 PM" width="372" src="https://user-images.githubusercontent.com/65459236/114692142-fa1d8c00-9d35-11eb-969a-62cb4a0d2f36.png">
> 
> code is different for the both

I found that the problem she chosen is already done by you so I closed their issue. You can continue Do one thing create a new PR and send. Will review again

2021-04-14 10:35 UTC, Meghag5 commented
Thank you so much 
It is already done pls review it @ankitaggarwal23

2021-04-16 15:11 UTC, bhav09 requested changes
Reviewed.

2021-04-16 15:11 UTC, bhav09 commented on C-Plus-Plus/dp/Printing_Shortest_Common_Supersequence.cpp
> +Time Complexity - O(m*n)
Please write the time complexity above Sample IO

2021-04-16 15:24 UTC, merged