Make pallindrome
HarshCasper/NeoAlgo pull request #5764
Opened 2021-04-14 07:45 UTC by Meghag5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description

(Write your answer here.)
This problem will be solved using dp.
We will be given one strings and we have to print the
Minimum number of deletion in a string to make it a palindrome.
Input - 
Enter string X
bbbab
Output -  
Minimum number of deletion in a string to make it a palindrome
4

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#5757

2021-04-14 08:15 UTC, HarshCasper requested changes

2021-04-14 08:15 UTC, HarshCasper commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +    //memset(t,-1,sizeof(t));
If it has no significance in the code, remove it up

2021-04-14 08:15 UTC, HarshCasper commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +int longestSubsequence(string X,string Y,int m,int n){
Can you use more meaningful variable names?

2021-04-14 08:15 UTC, HarshCasper commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +    string X;
Can you use more meaningful variable names?

2021-04-14 08:54 UTC, Meghag5 commented
@HarshCasper updated pls check

2021-04-14 14:54 UTC, HarshCasper requested changes
Format the entire Code

2021-04-16 16:03 UTC, HarshCasper requested changes

2021-04-16 16:03 UTC, HarshCasper commented on C-Plus-Plus/README.md
> +- [Minimum number of deletion in a string to make it a palindrome](dp/Minimum_number_of_deletion _to_make_palindrome.cpp)
The file path is buggy here. Kindly fix it

2021-04-16 16:03 UTC, HarshCasper commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +      //if letters of both string are not equal then first we will decrease row by 1 and then column by 1 and find maximum value b/w two
Break down this comment. Too difficult to make any sense of

2021-04-16 16:03 UTC, HarshCasper commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +      //if letters of both string are equal then we will decrease row and column both by 1
Break down this comment. Too difficult to make any sense of

2021-04-17 06:38 UTC, ankitaggarwal23 requested changes

2021-04-17 06:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Form a palindrome ](dp/Minimum_number_of_deletion _to_make_palindrome.cpp)
`[Minimum number of deletion to make palindrome]` rewrite it like this

2021-04-17 06:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +int minDeletion(string X, string Y, int m, int n) {
don't use single letters for variables use meaningful names

2021-04-17 06:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +  cout << minDeletion(s1, s2, m, n);
Use proper display message how you are reading and writing outputs

2021-04-17 06:38 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_number_of_deletion _to_make_palindrome.cpp
> +*/
Use proper spacing

2021-04-17 06:56 UTC, Meghag5 commented
Done all the changes required

2021-04-17 07:01 UTC, ankitaggarwal23 requested changes

2021-04-17 07:01 UTC, ankitaggarwal23 commented on C-Plus-Plus/README.md
> +- [Minimum number of deletion to make palindrome](dp/Minimum_number_of_deletion _to_make_palindrome.cpp)
You file is buggy due to inappropriate naming of file `(dp/Minimum_number_of_deletion _to_make_palindrome.cpp)`

Rename it properly or make it as `(dp/Minimum_number_of_deletion.cpp)`

2021-04-17 07:28 UTC, Meghag5 commented
Done @ankitaggarwal23

2021-04-17 07:42 UTC, ankitaggarwal23 requested changes
You have to save your file in .cpp you didn't save it properly

2021-04-17 07:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/dp/Minimum_number_of_deletion
> +
Remove this line

2021-04-17 07:53 UTC, Meghag5 commented
Really sorry @ankitaggarwal23 
done

2021-04-17 08:35 UTC, ankitaggarwal23 approved these changes

2021-04-17 08:36 UTC, merged