Added space optimized implementation and updated README file
HarshCasper/NeoAlgo pull request #5768
Opened 2021-04-14 08:10 UTC by imsushant12

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

I have added the Fibonacci series implementation without using recursion.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5718

2021-04-14 10:52 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Use proper display message how you are reading and writing outputs

2021-04-17 06:42 UTC, ankitaggarwal23 requested changes
What exactly you are doing finding fibonacci sum or what? didn't get exact clarity you have written something and finding something else

2021-04-17 06:42 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/fibonacci_space_optimized.cpp
> +*/
Shift this above the header

2021-04-17 07:08 UTC, imsushant12 commented on C-Plus-Plus/math/fibonacci_space_optimized.cpp
> +*/
Shifted

2021-04-17 07:11 UTC, imsushant12 commented
> What exactly you are doing finding fibonacci sum or what? didn't get exact clarity you have written something and finding something else

I am finding fibonacci number at given position (for example n=5  then answer will be fib(5) = 5; So I am using the DP approach i.e. saving the last and second last number to get current number.

2021-04-18 09:17 UTC, ankitaggarwal23 requested changes
Rename your issue, PR and file name it not suits with the work you have done

2021-04-18 09:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/math/fibonacci_space_optimized.cpp
> +    Test Case - 1:
test case 2 not 1

2021-04-19 08:33 UTC, imsushant12 commented on C-Plus-Plus/math/fibonacci_space_optimized.cpp
> +    Test Case - 1:
done!

2021-04-19 10:24 UTC, ankitaggarwal23 approved these changes

2021-04-19 10:24 UTC, merged