Linear probing
HarshCasper/NeoAlgo pull request #5796
Opened 2021-04-14 12:20 UTC by 1vivekanand

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Linear probing in hashing

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixed #5464

2021-04-17 07:14 UTC, ankitaggarwal23 requested changes
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

2021-04-18 08:24 UTC, ankitaggarwal23 requested changes

2021-04-18 08:24 UTC, ankitaggarwal23 commented on Java/other/linearProbing.java
> +80 90 60 10 74 45 -1 -1 -1 -1
Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

2021-04-20 10:28 UTC, ankitaggarwal23 requested changes
Use proper alignment of code and braces

2021-04-20 10:28 UTC, ankitaggarwal23 commented on Java/other/linearProbing.java
> +//-1 shows cell is still empty
Remove these parts one is enough

2021-04-21 06:52 UTC, 1vivekanand commented
@ankitaggarwal23 please add label for the level of issue

2021-04-22 02:52 UTC, ankitaggarwal23 requested changes
Use proper alignment of code and braces

2021-04-22 03:35 UTC, ankitaggarwal23 commented
> Use proper alignment of code and braces

Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 14:36 UTC, 1vivekanand commented
@ankitaggarwal23 if still there is problem with braces then please point out the line

2021-04-22 22:23 UTC, ankitaggarwal23 approved these changes

2021-04-22 22:24 UTC, merged