Basic Functionalities of Stack
HarshCasper/NeoAlgo pull request #580
Opened 2020-08-18 15:05 UTC by Alifbhanvadiya14

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented Stack using List and added some function in Stack implementation using Linked List

### Checklist

- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
- [✓] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

-  Stack using List /Array was not implemented and some functionalities were missing in the implementation of Stack using Linked List.  So  I add these functionalities.

2020-08-18 16:07 UTC, Alifbhanvadiya14 commented
Review only basic functionalities of Stack files

2020-08-19 15:34 UTC, siddharth25pandey requested changes
@Alifbhanvadiya14 Please do following modifications
* Take dynamic input, i.e take input from the user.
* Create a count function which counts total number of elements present at that time.
* Display suitable message after each operation

2020-08-19 16:40 UTC, Kajol-Kumari requested changes
Please remove the hardcoded values and take the input from user. Also please add a sample input-output at the end of the code section in commented form.

2020-08-19 16:40 UTC, Kajol-Kumari commented on Python/ds/Stacks.py
> +    stack.push(10)
Please take the input of the stack from user.

2020-08-19 16:40 UTC, Kajol-Kumari commented on Python/ds/Stacks.py
> +    print ("Pass" if (stack2.size() == 5) else "Fail")
please take the size as input as well instead of hardcoding.

2020-10-28 00:29 UTC, closed without merging