Symmetric Matrix in C
HarshCasper/NeoAlgo pull request #5802
Opened 2021-04-14 12:30 UTC by abhijeet141

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Program to check whether a matrix is symmetric or not.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #5769

2021-04-14 12:33 UTC, abhijeet141 commented
Respected Mentors please review this PR

2021-04-16 17:40 UTC, bhav09 requested changes
Can you make it a function-driven program where the main function acts more like a driver function only. Rest seems good to me :)

2021-04-16 18:47 UTC, abhijeet141 commented
@bhav09 Made changes please check

2021-04-17 07:19 UTC, ankitaggarwal23 approved these changes

2021-04-17 07:19 UTC, merged