longest substring without repetition of chars
HarshCasper/NeoAlgo pull request #586
Opened 2020-08-18 17:19 UTC by pradeep98

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

[Python] longest substring without repetition of characters. Issue opened by @piyushgoell Assigned by @SKAUL05 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

[Longest Substring Without Repeating Characters #563](https://github.com/TesseractCoding/NeoAlgo/issues/563)

2020-08-19 06:27 UTC, SKAUL05 requested changes

2020-08-19 06:27 UTC, SKAUL05 commented on Python/other/longest_Substring.py
> +def longestSubstringLength(string):
Document our function using docstrings

2020-08-19 06:27 UTC, SKAUL05 commented on Python/other/longest_Substring.py
> +testCase = int(input('No. of test cases:'))
Follow PEP8 Guidelines for variable naming & function naming conventions
https://www.python.org/dev/peps/pep-0008/#id45

2020-08-19 12:00 UTC, SKAUL05 approved these changes
Looks Good

2020-08-19 14:07 UTC, Kajol-Kumari reviewed
```
No. of test cases:1                                                                                                       
Teststring                                                                                                                     
6      
```                                                                                                               
Hey @pradeep98 If i am getting it correctly then your code should have output `3` as at the 4th position we have a common character `s` but it showing `6`. can you please explain, why?

2020-08-19 14:12 UTC, pradeep98 commented
> ```
> No. of test cases:1                                                                                                       
> Teststring                                                                                                                     
> 6      
> ```
> 
> Hey @pradeep98 If i am getting it correctly then your code should have output `3` as at the 4th position we have a common character `s` but it showing `6`. can you please explain, why?
Ma'am, statement says: longest substring without repetition of characters. Here in Teststring->  substring 'string' is the longest one with no repetition of characters. Thats why answer is 6.

2020-08-19 14:15 UTC, Kajol-Kumari approved these changes
It's good to go :)

2020-08-19 15:19 UTC, siddharth25pandey approved these changes
@pradeep98 Looks fine to me.
Able to merge.
Thanks!

2020-08-19 15:19 UTC, merged

2020-08-23 22:04 UTC, iamrajiv commented
@all-contributors please add @pradeep98 for code