Merge two sorted arrays without using extra space
HarshCasper/NeoAlgo pull request #5868
Opened 2021-04-14 20:32 UTC by nikitaaa23

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

C++ Program to merge two sorted arrays without using extra space O(1).

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5854

2021-04-19 04:15 UTC, nikitaaa23 commented
@atarax665 Kindly review!

2021-04-20 13:35 UTC, nikitaaa23 commented
@ankitaggarwal23 Please review

2021-04-22 03:13 UTC, ankitaggarwal23 requested changes
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 09:32 UTC, nikitaaa23 commented
@ankitaggarwal23 Made the changes, please review.
Replit link: https://replit.com/@NikitaSaini/Mergewithoutextraspace#main.cpp

2021-05-12 16:08 UTC, nikitaaa23 commented
@ankitaggarwal23 Made the changes, please review.
Replit link: https://replit.com/@NikitaSaini/Mergewithoutextraspace#main.cpp

2021-05-14 16:19 UTC, nikitaaa23 commented
@ankitaggarwal23 I made the changes.
Replit link: https://replit.com/@NikitaSaini/Mergewithoutextraspace#main.cpp

2021-05-15 07:10 UTC, ankitaggarwal23 requested changes

2021-05-15 07:10 UTC, ankitaggarwal23 commented on C-Plus-Plus/sort/merge_without_extra_space.cpp
> +
- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-05-15 07:10 UTC, ankitaggarwal23 commented on C-Plus-Plus/sort/merge_without_extra_space.cpp
> +}
You need to add comments to your code. Make sure the comments you add are above the line of code and not alongside it.

2021-05-15 07:10 UTC, ankitaggarwal23 commented on C-Plus-Plus/sort/merge_without_extra_space.cpp
> +
Remove extra space

2021-05-15 07:10 UTC, ankitaggarwal23 commented on C-Plus-Plus/sort/merge_without_extra_space.cpp
> +        cout<<"Sorted Array : ";
You need to add comments to your code. Make sure the comments you add are above the line of code and not alongside it.

2021-05-15 07:10 UTC, ankitaggarwal23 commented on C-Plus-Plus/sort/merge_without_extra_space.cpp
> +
Remove extra test case

2021-05-15 14:40 UTC, nikitaaa23 commented
@ankitaggarwal23 Made the changes, please check.

2021-05-15 18:37 UTC, ankitaggarwal23 approved these changes

2021-05-15 18:38 UTC, merged