Remove Duplicate From an Unsorted Linked List in C
HarshCasper/NeoAlgo pull request #5886
Opened 2021-04-15 06:25 UTC by sumitgsh

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES
(Write your answer here.)

### Description
Removes duplicated from an unsorted linked list in constant time
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#5818

2021-04-15 06:29 UTC, sumitgsh commented
@ankitaggarwal23  @iamrajiv  @siddharth25pandey can u please review my PR

2021-04-15 13:32 UTC, iamrajiv requested changes
@sumitgsh Rename `RemDupInUnSortedLL.c` to some proper name.

2021-04-16 05:16 UTC, sumitgsh commented
> @sumitgsh Rename `RemDupInUnSortedLL.c` to some proper name.

@iamrajiv can u please review and merge

2021-04-16 06:42 UTC, iamrajiv approved these changes

2021-04-16 18:38 UTC, ankitaggarwal23 approved these changes

2021-04-16 18:39 UTC, merged