Reverse circular linked list
HarshCasper/NeoAlgo pull request #5890
Opened 2021-04-15 07:32 UTC by khusheekapoor

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the Contributing Guidelines on Pull Requests

### Description

To reverse a circularly linked list in Java as a GSSoC'21 participant.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #5748

2021-04-17 07:47 UTC, ankitaggarwal23 requested changes

2021-04-17 07:47 UTC, ankitaggarwal23 commented on Java/README.md
> +- [Reversing Ciruclar Linked List](ds/ReversingCircularLinkedList.java)
Fix typo

2021-04-17 07:47 UTC, ankitaggarwal23 commented on Java/ds/ReversingCircularLinkedList.java
> + 8 7 6
Remove extra test case

2021-04-17 15:30 UTC, khusheekapoor commented on Java/README.md
> +- [Reversing Ciruclar Linked List](ds/ReversingCircularLinkedList.java)
Made the changes.

2021-04-17 15:30 UTC, khusheekapoor commented on Java/ds/ReversingCircularLinkedList.java
> + 8 7 6
Made the changes.

2021-04-18 08:19 UTC, ankitaggarwal23 approved these changes

2021-04-18 08:19 UTC, merged