adding longest bitonic subsequence in c++
HarshCasper/NeoAlgo pull request #5905
Opened 2021-04-15 12:07 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #5904 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #5904

2021-04-15 12:08 UTC, aaadddiii commented
@ankitaggarwal23  @HarshCasper  please review it

2021-04-19 09:14 UTC, ankitaggarwal23 requested changes
Use proper naming conventions for variable don't use single letters and use proper comments wherever need don't add redundant comments

2021-04-19 16:52 UTC, aaadddiii commented
@ankitaggarwal23  I have made the changes please review it

2021-04-20 10:32 UTC, ankitaggarwal23 approved these changes

2021-04-20 10:32 UTC, merged