Trapping rain water in python
HarshCasper/NeoAlgo pull request #5913
Opened 2021-04-15 15:02 UTC by Amit366

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added code for trapping rain water

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #5851

2021-04-16 11:38 UTC, Amit366 commented
@HarshCasper please review

2021-04-16 14:45 UTC, Amit366 commented
@ankitaggarwal23 please review

2021-04-17 12:25 UTC, ankitaggarwal23 requested changes

2021-04-17 12:25 UTC, ankitaggarwal23 commented on Python/cp/Trapping_rain_water.py
> +# width of each bar is 1, compute how much water it can trap after raining.
use Multi-Line Comments

2021-04-17 12:25 UTC, ankitaggarwal23 commented on Python/cp/Trapping_rain_water.py
> +# Water it can trap is: 1
remove extra test case

2021-04-17 12:25 UTC, ankitaggarwal23 commented on Python/cp/Trapping_rain_water.py
> +
use  Multi-Line Comments

2021-04-17 12:26 UTC, Amit366 commented on Python/cp/Trapping_rain_water.py
> +# Water it can trap is: 1
@ankitaggarwal23 so only one test case??

2021-04-18 08:17 UTC, ankitaggarwal23 approved these changes

2021-04-18 08:17 UTC, merged