Added number of minimum swaps to sort array in python
HarshCasper/NeoAlgo pull request #600
Opened 2020-08-19 07:45 UTC by AkM-2018

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given an array of length N with all numbers from 1 to N(without repetition) in a random order, find the number of minimum swaps to sort the array. The solution for this is written in python. The code is well commented and explained. A link is added to the readme file.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#461

2020-08-19 12:02 UTC, SKAUL05 requested changes

2020-08-19 12:02 UTC, SKAUL05 commented on Python/graphs/Minimum_swaps_to_sort_array.py
> +    for i in range(len(arr)):
Use `meaningful` variable names instead of i

2020-08-19 12:02 UTC, SKAUL05 commented on Python/graphs/Minimum_swaps_to_sort_array.py
> +    arr = [2,10,1,3,6,4,7,5,8,9];
Take input from user

2020-08-19 12:02 UTC, SKAUL05 commented on Python/graphs/Minimum_swaps_to_sort_array.py
> +def num_min_swaps(arr):
Include docstrings

2020-08-23 11:38 UTC, AkM-2018 commented
@SKAUL05, I did the requested changes, but it seems my local files are outdated. So, I added a new upstream and merged with master. Now, I can put a new pull request but I don't know how to make changes in this pull request

2020-09-12 06:38 UTC, closed without merging