Play With OR
HarshCasper/NeoAlgo pull request #6019
Opened 2021-04-17 06:11 UTC by anshmishra010

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes 

### Description

Given an array, you have to re-construct an array.
 The values in array are obtained by doing OR(bitwise or) of consecutive elements in the array.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6013

2021-04-17 12:02 UTC, ankitaggarwal23 requested changes

2021-04-17 12:02 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Play_with_OR.cpp
> +  11 11 3 3 3
![image](https://user-images.githubusercontent.com/67387053/115112323-a663aa80-9fa2-11eb-81f4-b0fbdc377998.png)

rewrite it as
```
Output :
New Array :
11 11 3 3 3

```

2021-04-17 13:05 UTC, anshmishra010 commented
Changes done

2021-04-18 08:15 UTC, ankitaggarwal23 approved these changes

2021-04-18 08:15 UTC, merged