Avantika782
HarshCasper/NeoAlgo pull request #6025
Opened 2021-04-17 08:16 UTC by Avantika782

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-17 08:28 UTC, Avantika782 commented
@ankitaggarwal23 Please check my PR and guide me if it needs any correction.

2021-04-17 09:36 UTC, gat786 commented
Change the title of PR. it currently just says your username outloud.

2021-04-17 09:47 UTC, gat786 requested changes

2021-04-17 09:47 UTC, gat786 commented on C-Plus-Plus/other/Minimum_number_of_swaps_for_bracket_balancing.cpp
> +We are given a string of 2N characters
take all this at the bottom of code file. While there is no particular reason to do so. But as a personal liking I try to keep all the most important things in a code file at the top or the most reachable point. all the information or not so important pieces hidden in the bottom.

2021-04-17 17:30 UTC, Avantika782 commented
@gat786 Please review the changes and let me know if it requires any correction.

2021-04-18 08:49 UTC, gat786 commented on C-Plus-Plus/README.md
> +- [Minimum number of swaps for bracket balancing](other/Minimum_number_of_swaps_for_bracket_balancing)
This link won't work. It doesn't have the extension applied.

2021-04-18 08:49 UTC, gat786 commented
Rest LGTM :)

2021-04-18 10:31 UTC, Avantika782 commented on C-Plus-Plus/README.md
> +- [Minimum number of swaps for bracket balancing](other/Minimum_number_of_swaps_for_bracket_balancing)
Please review it. @gat786

2021-04-18 10:32 UTC, Avantika782 commented on C-Plus-Plus/README.md
> +- [Minimum number of swaps for bracket balancing](other/Minimum_number_of_swaps_for_bracket_balancing)
OKhay , if the rest is okhay;-))

2021-04-19 10:55 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.geeksforgeeks.org/minimum-swaps-bracket-balancing/)

2021-04-19 10:55 UTC, closed without merging

2021-04-19 11:22 UTC, Avantika782 commented
@ankitaggarwal23 I want to correct my mistakes. Sir, can please reassign it to me.

2021-04-19 11:23 UTC, Avantika782 commented
@ankitaggarwal23 Sir I want to correct my mistakes. Can you please reassign it to me.