Binary Exponent calculation in Dart #5810
HarshCasper/NeoAlgo pull request #6027
Opened 2021-04-17 08:23 UTC by ashuvssut

implement Binary Exponent calculation in Dart

## Related Issues or Pull Requests

closes #5792

2021-04-17 08:30 UTC, ashuvssut commented
@ankitaggarwal23 can you please ask for changes instead of _directly closing_ an open PR and issue😅just for a some small mistakes. I know maintainers are too busy. but atleast consider asking for changes.

writing a PR and issue again after getting doesnt feel right😓

2021-04-17 08:37 UTC, ashuvssut commented
@ankitaggarwal23 if the code changes given in this PR is not what NeoAlgo wants.. then i will close this PR myself. I understand if there is no need for the code I have written

But from your side kindly tell what kind of algorithm do you expect from contributors

contributors wont make such mistakes again

2021-04-17 08:38 UTC, ankitaggarwal23 reviewed
Don't push more than one code file in a single PR.

2021-04-17 08:39 UTC, ankitaggarwal23 commented
> Don't push more than one code file in a single PR.

Why you are updating and pushing other code file and readme.md

2021-04-17 08:40 UTC, ashuvssut commented
> Don't push more than one code file in a single PR.

sir you can ask me to remove the code file. its the same code file that came through the recent merge I did.

why close this PR again😕

2021-04-17 08:41 UTC, ankitaggarwal23 commented
> > Don't push more than one code file in a single PR.
> 
> sir you can ask me to remove the code file. its the same code file that came through the recent merge I did.
> 
> why close this PR again😕

If you remove it will show three files in our side as well

2021-04-17 08:41 UTC, ankitaggarwal23 commented
You only see what you messed up with files

2021-04-17 08:41 UTC, ashuvssut commented
No it wont show

2021-04-17 08:42 UTC, ankitaggarwal23 commented
Add only your files and readme updates

2021-04-17 08:42 UTC, ashuvssut commented
> You only see what you messed up with files

I rearranged the Readme alphabetically😅

2021-04-17 08:42 UTC, ashuvssut commented
can you reopen this please

2021-04-17 09:33 UTC, ashuvssut commented on Dart/README.md
> +- [Binomial Coefficient (under modulo)](maths/binomial_coefficient_under_modulo.dart)
this is the link to the related code file.

readme is arranged in alphabetical order

2021-04-17 11:33 UTC, ankitaggarwal23 requested changes
Why you are pushing so many lines on readme. add you link only first you update your repo and then do the changes

2021-04-17 11:42 UTC, ashuvssut commented
actually I arranged them in  alphabetical order

In the review I have marked the line that links the "Binary Exponent calculation" code

2021-04-17 11:43 UTC, ashuvssut commented
ok i will remove the alphabetical order

2021-04-17 11:44 UTC, ashuvssut commented
removed aphabetical order

2021-04-17 11:55 UTC, ankitaggarwal23 requested changes
Can you confirm whether it is binary coefficient or binal exponent under modulo? Either make it same everywhere otherwise it becomes difficult for others to track

2021-04-17 12:30 UTC, ashuvssut commented
in https://github.com/TesseractCoding/NeoAlgo/pull/5810 you changed the PR title to Binary Exponent calculation in Dart
So i also changed to that here. 

Now I have put the old one "Binomial Coefficient (under modulo)". Now there should be no confusion😄

2021-04-18 08:13 UTC, ankitaggarwal23 approved these changes

2021-04-18 08:14 UTC, merged