Intersection of two arrays
HarshCasper/NeoAlgo pull request #6101
Opened 2021-04-18 05:05 UTC by Amanduttbhagat

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

  - Intersection : 
       We have to find intersection of two arrays :
       The intersection of two arrays is a list of numbers which are present in both the arrays
     Example :
       input : Enter the number of elements you want in the first array : 4
	           Enter the elements in the 1st array : 1 4 3 2
	 		   Enter the number of elements you want in the second array : 3
	 		   Enter the elements in the 2nd array : 1 2 3
      output : The intersection of two arrays is : 1 2 3
               Intersection of both arrays is [1 2 3] as these elements are present in both the arrays

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6070

2021-04-18 05:15 UTC, Amanduttbhagat commented
Hello @HarshCasper @ankitaggarwal23 ,
Can you review this PR

Thank you

2021-04-19 11:59 UTC, ankitaggarwal23 requested changes
- Use proper code Format

2021-04-19 13:07 UTC, Amanduttbhagat commented
@ankitaggarwal23 Can you please review it again

Thank you

2021-04-20 10:58 UTC, ankitaggarwal23 requested changes
Next time do like that only

2021-04-20 10:58 UTC, ankitaggarwal23 commented on Java/cp/Intersection_of_Two_Arrays.java
> +               Intersection of both arrays is [1 2 3] as these elements are present in both the arrays
Remove this and,
- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-04-20 10:58 UTC, ankitaggarwal23 commented on Java/cp/Intersection_of_Two_Arrays.java
> +}
rewrite it like that,
```
import java.util.Arrays;
import java.util.Scanner;

public class Intersection_of_Two_Arrays {

	//method intersection
	public void intersection(int[] array1, int[] array2) {

		int x = 0, y = 0;

		Arrays.sort(array1);
		Arrays.sort(array2);

		for(  ; x < array1.length && y < array2.length ;  ) 
		{

			if(array1[x] == array2[y]) 
			{
				System.out.print(array2[y]+" ");
				y = y+1;
				x = x+1;
			}
			else if(array1[x] < array2[y]) 
			{
				x = x+1;
			}
			else if(array1[x] > array2[y]) 
			{
				y = y+1;
			}
		}
	}

	//Driver Code
	public static void main(String[] args) {

		Scanner sc = new Scanner(System.in);

		System.out.print("Enter the number of elements you want in the first array : ");
		int first = sc.nextInt();

		//Creating array
		int[] array1 = new int[first];

		System.out.print("Enter the elements in the 1st array : ");
		for(int i = 0 ; i < first ; i++) {
			array1[i] = sc.nextInt();
		}

		System.out.print("Enter the number of elements you want in the second array : ");
		int second = sc.nextInt();

		//Creating array
		int[] array2 = new int[second];

		//Putting elements in the array
		System.out.print("Enter the elements in the 2nd array : ");
		for(int i = 0 ; i < second ; i++) {
			array2[i] = sc.nextInt();
		}

		//Creating object
		Intersection_of_Two_Arrays obj = new Intersection_of_Two_Arrays();

		System.out.print("The intersection of two arrays is : ");
		
		//calling intersection method
		obj.intersection(array1, array2);
	}
}
```

2021-04-20 10:58 UTC, ankitaggarwal23 commented on Java/cp/Intersection_of_Two_Arrays.java
> + */
rewrite it,


```
/*

Input:
Enter the number of elements you want in the first array : 4                                                                                  
Enter the elements in the 1st array : 1 2 3 4                                                                                                 
Enter the number of elements you want in the second array : 3                                                                                 
Enter the elements in the 2nd array : 1 2 3

Output:                                                                                                   
The intersection of two arrays is : 1 2 3

Time Complexity : O(n)
Space Complexity : O(n)

*/
```

2021-04-21 04:34 UTC, ankitaggarwal23 approved these changes

2021-04-21 04:34 UTC, merged