Coin Change Problem Using DP #216
HarshCasper/NeoAlgo pull request #611
Opened 2020-08-19 14:44 UTC by Huzaib

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This algorithm solves the coin change algorithm using dynamic programming in O(length of sums array * sum) time complexity.
It has passed the problem statement on LeetCode 322. Coin Change. 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#216

2020-08-19 18:55 UTC, iamrajiv requested changes
@Huzaib please add the codes there is no file changed apart from the readme

2020-08-19 19:11 UTC, Huzaib commented
Sorry sir,
I mistakenly added the .class file
I have corrected my mistake
Please take a look at it

2020-08-20 05:01 UTC, plazzy99 requested changes

2020-08-20 05:01 UTC, plazzy99 commented on Java/dp/CoinChangeUsingDp.java
> +}
add a sample test input and output case

2020-08-20 05:01 UTC, plazzy99 commented on Java/dp/CoinChangeUsingDp.java
> +
add input and output messages

2020-08-22 15:03 UTC, vatsalkesarwani12 commented on Java/dp/CoinChangeUsingDp.java
> +
resolve this also

2020-08-23 11:01 UTC, siddharth25pandey approved these changes
@Huzaib Good to go
Able to merge
Thanks!

2020-08-23 11:47 UTC, merged

2020-08-23 22:15 UTC, iamrajiv commented
@all-contributors please add @Huzaib for code