HashMap java script
HarshCasper/NeoAlgo pull request #612
Opened 2020-08-19 17:19 UTC by howdyAnkit

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes I have followed the contribution guidelines.)

### Description

([Javascript] HashMap DataStructure was opened by Me itself and was assigned by @iamrajiv .)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(https://github.com/TesseractCoding/NeoAlgo/issues/350.)

2020-08-22 09:21 UTC, howdyAnkit commented
I am aware NeoAlgo is getting spammed with PR. if possible can anyone kindly review my PR?

2020-08-22 20:11 UTC, mar-galho approved these changes

2020-08-23 04:03 UTC, atarax665 requested changes

2020-08-23 04:03 UTC, atarax665 commented on JavaScript/ds/HashMap.js
> +console.log(birdCensus.retrieve('horned owl'));
Add sample input/output in in the end in commented form.

2020-08-23 05:36 UTC, HarshCasper approved these changes

2020-08-23 14:54 UTC, howdyAnkit commented on JavaScript/ds/HashMap.js
> +console.log(birdCensus.retrieve('horned owl'));
Thank you for reviewing Abhinav. Please Check I have made the requested changes

2020-08-30 15:16 UTC, mar-galho approved these changes

2020-09-13 16:17 UTC, howdyAnkit commented
@atarax665 can you please review this...?

2020-09-21 05:06 UTC, closed without merging