Infix expression evaluator added
HarshCasper/NeoAlgo pull request #6124
Opened 2021-04-18 12:01 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#5656 )

2021-04-18 12:03 UTC, shivammahajancse commented
Please review @ankitaggarwal23 @iamrajiv @HarshCasper @atarax665 @gat786

2021-04-19 12:27 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

2021-04-19 13:07 UTC, shivammahajancse commented
All requested changes done @ankitaggarwal23

2021-04-20 10:59 UTC, ankitaggarwal23 approved these changes

2021-04-20 10:59 UTC, merged