Implemented Tree Sort In JAVA
HarshCasper/NeoAlgo pull request #6133
Opened 2021-04-18 14:42 UTC by Khushi-24

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

### Description

Added TreeSort.java to sort the directory
Updated README.md

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2021-04-19 12:55 UTC, ankitaggarwal23 requested changes
Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

2021-04-19 12:55 UTC, ankitaggarwal23 commented on Java/sort/TreeSort.java
> +        int[] arr = {12, 35, 1, 3, 13, 5, 72, 64, 2};
use dynamic inputs from user

2021-04-20 10:12 UTC, Khushi-24 commented
@ankitaggarwal23 I have made the required changes. Please tell, if any further changes are required.

2021-04-20 11:00 UTC, ankitaggarwal23 approved these changes

2021-04-20 11:00 UTC, merged