Special Number
HarshCasper/NeoAlgo pull request #6135
Opened 2021-04-18 15:13 UTC by Khushi-agarwal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

It is a JAVA program which is to test whether a number is special or not.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #6134

2021-04-18 15:13 UTC, Khushi-agarwal commented
@HarshCasper kindly review this.

2021-04-18 15:27 UTC, HarshCasper requested changes

2021-04-18 15:27 UTC, HarshCasper commented on Java/math/Special.java
> +    public static void main()
Put everything in a modular function. Use `main()` only for the driver code.

2021-04-18 15:27 UTC, HarshCasper commented on Java/math/Special.java
> +A special number is a number whose all digits are 1
Give an example here

2021-04-18 15:27 UTC, HarshCasper commented on Java/math/Special.java
> +		/*If the sum of digits and count of digits is equal then special*/
Align the comment with the code

2021-04-18 15:27 UTC, HarshCasper commented on Java/math/Special.java
> +			/*Calculating count of digits*/
Align the comment with the code

2021-04-18 15:27 UTC, HarshCasper commented on Java/math/Special.java
> +			/*Calculating sum of digits*/
Align the comment with the code

2021-04-18 17:01 UTC, Khushi-agarwal commented
@HarshCasper I have made the changes.Kindly review.

2021-04-19 12:57 UTC, ankitaggarwal23 approved these changes

2021-04-19 12:57 UTC, merged