Exactly four factors (CP)
HarshCasper/NeoAlgo pull request #6152
Opened 2021-04-18 20:47 UTC by ShubhamGupta577

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
YES

### Description

Added the code for checking a number has exactly 4 factors or not by using the number theory under CP folder.
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#6068

2021-04-18 20:51 UTC, ShubhamGupta577 commented
@bhav09, @ankitaggarwal23 Please review this PR.

2021-04-20 13:18 UTC, bhav09 requested changes
Can you add complexity to the code. Thanks.

2021-04-22 03:54 UTC, ankitaggarwal23 reviewed
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 10:44 UTC, ShubhamGupta577 commented
> Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

I have made the changes as per the format described on Discord. Please Review this PR.

2021-04-22 13:46 UTC, ankitaggarwal23 requested changes

2021-04-22 13:46 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Exactly_Four_Factors.cpp
> +
Replace header with ` #include <bits/stdc++.h>`

2021-04-22 13:46 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Exactly_Four_Factors.cpp
> +*/
Write the outputs in the way your code is producing.
Write TC and SC only once

2021-04-26 19:22 UTC, ShubhamGupta577 commented
@ankitaggarwal23 Please review the changes.

2021-04-30 10:52 UTC, ankitaggarwal23 approved these changes

2021-04-30 10:52 UTC, merged