Added the algorithm to sort an array of 0,1,2 without comparing the elements with each other in Julia
HarshCasper/NeoAlgo pull request #6164
Opened 2021-04-19 08:11 UTC by Saviour1001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added the algorithm to sort an array of 0,1,2 without comparing the elements with each other in Julia

### Checklist

- [ Yes ] I've read the contribution guidelines.
- [ Yes ] I've checked the issue list before deciding what to submit.
- [ Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR closes issue #6163

2021-04-22 03:57 UTC, ankitaggarwal23 reviewed
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 13:00 UTC, Saviour1001 commented
[REPLIT Link](https://replit.com/@09HarshHarsh/012-Sort#main.jl)

2021-04-30 11:03 UTC, ankitaggarwal23 requested changes

2021-04-30 11:03 UTC, ankitaggarwal23 commented on Julia/README.md
> +- [0,1,2 Sort](sort/012_sort.jl)
use good naming conventions

2021-04-30 11:03 UTC, ankitaggarwal23 commented on Julia/sort/012_sort.jl
> +=#
Add a good and understandable description

2021-04-30 13:26 UTC, closed without merging