Add Code For OnesAndZeroes and update README
HarshCasper/NeoAlgo pull request #6178
Opened 2021-04-19 11:32 UTC by ANUJAGRAWAL2000

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description
I have add the code For Ones and Zeroes Issue.
(Write your answer here.)

### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#5542 
(Write your answer here.)

2021-04-19 11:35 UTC, ANUJAGRAWAL2000 commented
@HarshCasper Sir please check this PR and suggest changes.

2021-04-22 04:03 UTC, ankitaggarwal23 reviewed
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-30 11:07 UTC, ankitaggarwal23 requested changes

2021-04-30 11:07 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Ones_and_Zeroes.cpp
> +4
Write the outputs in the way your code is producing.

2021-05-12 12:09 UTC, ankitaggarwal23 approved these changes

2021-05-12 12:09 UTC, merged