Intersection Point in Y Shapped Linked Lists
HarshCasper/NeoAlgo pull request #618
Opened 2020-08-19 19:15 UTC by Rishikeshrajrxl

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#495 )

2020-08-19 19:19 UTC, Rishikeshrajrxl commented
@plazzy99 
@siddharth25pandey 
@iamrajiv  
I have completed this assignment, please review this and let me know if any changes needed.

2020-08-20 05:20 UTC, plazzy99 requested changes
edit readme file

2020-08-20 05:20 UTC, plazzy99 commented on C-Plus-Plus/ds/Intersected Linked List.cpp
> +}*head1=NULL,*head2=NULL,*temp1,*temp2,*ptr;
make use of proper spacing for better readability of code

2020-08-20 05:20 UTC, plazzy99 commented on C-Plus-Plus/ds/Intersected Linked List.cpp
> +    ptr=(struct node*)malloc(sizeof(struct node));
when you are using cpp why using **malloc** use **new**

2020-08-20 05:20 UTC, plazzy99 commented on C-Plus-Plus/ds/Intersected Linked List.cpp
> +
import cmath header to let **abs** function to work

2020-08-20 05:21 UTC, plazzy99 commented
Best input/output message format seen till date🤩

2020-08-20 05:49 UTC, siddharth25pandey requested changes
@Rishikeshrajrxl  Instead of importing any header file.
just write <bits/stdc++.h>

2020-08-20 06:38 UTC, Rishikeshrajrxl commented
> edit readme file

I have made other pull request regarding update of ReadMe.me file 
#630. please follow this changes.

2020-08-20 07:29 UTC, Rishikeshrajrxl commented
@plazzy99  , Done with all changes, please review this.

2020-08-20 14:42 UTC, Rishikeshrajrxl commented
I have also updated  CONTRIBUTING.md file for the issue #542 .
In this I have written documentation that can actually help new contributors to understand how they can start contributing to this Project.

2020-08-20 23:32 UTC, atarax665 requested changes

2020-08-20 23:32 UTC, atarax665 commented on CONTRIBUTING.md
> +You have a GitHub repo and can push to it. All is well. But how the heck do you contribute to other people's GitHub projects? That is what I wanted to know after I learned git and GitHGub. I will exp
Use Grammarly to fix all the typos and grammatical errors.

2020-08-20 23:32 UTC, atarax665 commented on CONTRIBUTING.md
> +
Add all the rules mentioned in #398 for Contributor' Hack participants.

2020-08-21 07:04 UTC, Rishikeshrajrxl commented
Done all changes, please review.

2020-08-22 12:14 UTC, vatsalkesarwani12 requested changes
why so much file?

2020-08-22 13:02 UTC, iamrajiv commented
@Rishikeshrajrxl please remove unnecessary files and resolve merge conflicts

2020-08-22 15:01 UTC, closed without merging