Added the solution to Inorder traversal in C
HarshCasper/NeoAlgo pull request #620
Opened 2020-08-20 03:26 UTC by cherryWood55

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description
I have added the code for Inorder traversal in C - both Recursive and Iterative implementation.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#415

2020-08-20 16:13 UTC, iamrajiv requested changes
@cherryWood55 add time and space complexity for both techniques. I think you have implemented recursive and non-recursive both inorder traversal so avoid using names `inorder.c` and `inorder2.c` rather you can use `inorder_recursive.` and `inorder_non_recursive.c`.

2020-08-21 00:57 UTC, cherryWood55 commented
@iamrajiv I have incorporated the changes into my code, please review.

2020-08-21 02:23 UTC, atarax665 commented
Update README.md.

2020-08-21 05:21 UTC, cherryWood55 commented
@atarax665 I have previously created a PR for updation of README. Please look into #621 .

2020-08-21 08:22 UTC, Kajol-Kumari commented
> @atarax665 I have previously created a PR for updation of README. Please look into #621 .

Hey @cherryWood55 You need to add you code's path in the readme. @atarax665 meant to say this. So, please update the readme for this PR

2020-08-21 08:23 UTC, Kajol-Kumari reviewed
please add one sample input-output below the complexity section for each of these.

2020-08-27 01:08 UTC, cherryWood55 commented
I have added one Sample input and output @Kajol-Kumari . Please review.

2020-08-27 01:10 UTC, cherryWood55 commented
Please review this PR @maintainers.

2020-08-28 08:40 UTC, Kajol-Kumari requested changes
@cherryWood55 Please add your code path in `readme.md` for reference you can take a look at any other PR.

2020-08-28 08:40 UTC, Kajol-Kumari commented on inorder_recursive.c
> +	struct node* head = create_new_node(40);
Can we please take these input from user?

2020-11-05 00:18 UTC, closed without merging