added the code for longest consecutive sequence
HarshCasper/NeoAlgo pull request #6208
Opened 2021-04-19 14:36 UTC by apoorva0107

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Return the length of the longest consecutive elements sequence in an unsorted array.
I have added the Java code of this problem under the section of cp in Java. I have also added the time and space complexities along with sample test cases. 

### Checklist

- [ :heavy_check_mark: ] I've read the contribution guidelines.
- [ :heavy_check_mark: ] I've checked the issue list before deciding what to submit.
- [ :heavy_check_mark: ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-04-19 16:44 UTC, apoorva0107 commented
Fixes #6191

2021-04-19 16:47 UTC, apoorva0107 commented
fixes #6191

2021-04-21 10:40 UTC, HarshCasper requested changes
Add the `.java` extension to the file.

2021-04-21 11:13 UTC, apoorva0107 commented
@HarshCasper I made the changes, please review.

2021-04-22 04:51 UTC, ankitaggarwal23 reviewed
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 04:52 UTC, ankitaggarwal23 reviewed
It is not a cp problem kindly add it to appropriate section

2021-04-22 07:07 UTC, apoorva0107 commented
@ankitaggarwal23 Which section should I add it to? Should I put this in 'ds' section or 'other'? Simple questions like "removing an element from array" and "reverse string" are also included in the 'cp' section so I thought this belongs there.

2021-04-22 13:05 UTC, ankitaggarwal23 commented
> @ankitaggarwal23 Which section should I add it to? Should I put this in 'ds' section or 'other'? Simple questions like "removing an element from array" and "reverse string" are also included in the 'cp' section so I thought this belongs there.

No we are adding files in their proper section.  So add your file in proper section

2021-04-22 13:29 UTC, ankitaggarwal23 requested changes
Shift your code file also to other section. still in cp section

2021-04-22 14:04 UTC, apoorva0107 commented
@ankitaggarwal23 trying to figure that out. Please help.

2021-04-22 14:42 UTC, apoorva0107 commented
@ankitaggarwal23 when I pull this into my local device it shows everything up to date, but why does it still have conflict?

2021-04-22 22:27 UTC, ankitaggarwal23 requested changes

2021-04-22 22:27 UTC, ankitaggarwal23 commented on Java/other/Longest_Consecutive_Squence.java
> +*/
Rewrite it like this
```
/*
Problem Description: For a given unsorted array, your task is to return
the length of longest sub-sequence such that elements in the subsequence
are consecutive integers.

For example: For an array [3, 6, 10, 2, 4] the longest sequence of 
consecutive elements is 2, 3, 4 so the length will be 3.
*/
```

2021-04-22 22:27 UTC, ankitaggarwal23 commented on Java/other/Longest_Consecutive_Squence.java
> +7
Remove extra test case

2021-04-23 13:05 UTC, apoorva0107 commented on Java/other/Longest_Consecutive_Squence.java
> +7
@ankitaggarwal23 made the changes

2021-04-27 11:14 UTC, HarshCasper approved these changes

2021-04-27 11:14 UTC, merged