Merge Sort - Linked List
HarshCasper/NeoAlgo pull request #6227
Opened 2021-04-19 17:11 UTC by ishwari20

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

 Given a singly linked list of integers, sort it using 'Merge Sort.'

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #6150

2021-04-21 09:00 UTC, ishwari20 commented
@ankitaggarwal23 Please review

2021-04-22 03:14 UTC, ankitaggarwal23 requested changes
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 15:00 UTC, ishwari20 commented
@ankitaggarwal23 @anushkrishnav Please review

2021-04-27 11:13 UTC, HarshCasper approved these changes

2021-04-27 11:13 UTC, merged