Generating Power Set Problem
HarshCasper/NeoAlgo pull request #6262
Opened 2021-04-20 07:41 UTC by harsha-sam

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [☑️] I've read the contribution guidelines.
- [☑️] I've checked the issue list before deciding what to submit.
- [☑️] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Related Issue: #5899 
Related Pull Request: #5901

2021-04-20 08:37 UTC, harsha-sam commented
https://github.com/TesseractCoding/NeoAlgo/pull/5901#pullrequestreview-638636556

### Regarding the multi-line comment requested change:

I would like to mention about how Multi-Line Comments in Python are not same as compared to  any other programming language. Python doesn't support multi-line comment blocks out of the box. The recommended way to comment out multiple lines of code in python is to use consecutive `# single-line comments`. [Python's PEP 8 style guide](https://www.python.org/dev/peps/pep-0008/#block-comments) also favours repeated single-line comments. 

Checkout this program:
https://replit.com/join/fbvtsqxl-harshasam

In the above program, I used  """triple-quote strings""" to comment between an `if-else` block. This program raises a `SyntaxError` because triple quotes strings are treated as regular strings with the exception that they can span multiple lines. These regular strings are not assigned to a variable and they will be garbage collected immediately as soon as the code executes. So, these are not ignored by the interpreter in the same way that  `# a single line comment` is.

There's a case that whenever these  """triple-quote strings""" are placed right after a function or class or top of a module, they are treated as `doc strings` and available at `obj.__doc__`

To fix the syntax error in the above program. Replace """the triple quote strings""" between the if-else block with `# single-line comments`. 

Hence, the better way to comment out multiple lines is to use consecutive `# single-line comments`.

2021-04-22 07:04 UTC, ankitaggarwal23 requested changes

2021-04-22 07:04 UTC, ankitaggarwal23 commented on Python/cp/Generating_Power_Set.py
> +# Power Set: [[], ['b'], ['a'], ['a', 'b']]
remove these extra test case

2021-04-22 07:08 UTC, harsha-sam commented on Python/cp/Generating_Power_Set.py
> +# Power Set: [[], ['b'], ['a'], ['a', 'b']]
Done

2021-04-22 13:07 UTC, ankitaggarwal23 requested changes

2021-04-22 13:07 UTC, ankitaggarwal23 commented on Python/cp/Generating_Power_Set.py
> +# Space Complexity: O(2*N)
maintain proper newline spacing wherever needed

2021-04-23 14:37 UTC, harsha-sam commented on Python/cp/Generating_Power_Set.py
> +# Space Complexity: O(2*N)
Sure

2021-04-30 11:11 UTC, ankitaggarwal23 approved these changes

2021-04-30 11:11 UTC, merged