Added Binary Search Algorithm
HarshCasper/NeoAlgo pull request #629
Opened 2020-08-20 06:33 UTC by narayan2111

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
I added a binary search technique to find out the occurrences of a particular element appear in given list of an array.

### Checklist

- [Y ] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
I added a binary search technique to find out the occurrences of a particular element appear in given list of an array.
User need to enter an array in an ascending order to find out the occurrence of a entered element by user.
![Program Output](https://user-images.githubusercontent.com/66173390/90725050-27b45180-e2dd-11ea-827c-058cf6b6a162.jpg)

2020-08-20 15:01 UTC, iamrajiv commented
@narayan2111 binary search is already implemented in C++ at https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/search/Binary_Search.cpp

2020-08-20 15:10 UTC, narayan2111 commented
> @narayan2111 binary search is already implemented in C++ at https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/search/Binary_Search.cpp

I know sir ,but this is not a binary search only ,the issue assigned to me was to find out the occurrences of a element of an array using binary search technique.

2020-08-20 15:15 UTC, narayan2111 commented
> > @narayan2111 binary search is already implemented in C++ at https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/search/Binary_Search.cpp
> 
> I know sir ,but this is not a binary search only ,the issue assigned to me was to find out the occurrences of a element of an array using binary search technique.
I'm attaching a link of a issue assigned to me 

https://github.com/TesseractCoding/NeoAlgo/issues/414#issue-679656509

2020-08-20 15:30 UTC, iamrajiv requested changes

2020-08-20 15:30 UTC, iamrajiv commented on C-Plus-Plus/ds/Binary_search_technique.cpp
> +		int mid = (first+last)/2;
@narayan2111 please avoid this technique to find the mid element since this can cause an integer overflow.
use this `int mid = first + ((last - first) / 2);`

2020-08-20 15:30 UTC, iamrajiv commented on C-Plus-Plus/search/Binary Search technique.cpp
> +		int mid = (first+last)/2;
@narayan2111 update this too

2020-08-21 06:47 UTC, narayan2111 commented on C-Plus-Plus/ds/Binary_search_technique.cpp
> +		int mid = (first+last)/2;
I updated the code. @iamrajiv

2020-08-21 06:48 UTC, narayan2111 commented on C-Plus-Plus/search/Binary Search technique.cpp
> +		int mid = (first+last)/2;
done with this too. @iamrajiv

2020-08-22 12:13 UTC, vatsalkesarwani12 requested changes
why 2 cpp file

do the required changes

2020-08-22 12:13 UTC, vatsalkesarwani12 commented on C-Plus-Plus/search/Binary Search technique.cpp
> + * copyright 2020 @author narayan2111
remove this comment

2020-08-22 12:13 UTC, vatsalkesarwani12 commented on C-Plus-Plus/search/Binary Search technique.cpp
> +
either keep this comment at the top or at the bottom of the source code

2020-08-22 12:34 UTC, narayan2111 commented on C-Plus-Plus/search/Binary Search technique.cpp
> +
> either keep this comment at the top or at the bottom of the source code

Done with changing the order of comments.

2020-08-22 12:38 UTC, narayan2111 commented
> why 2 cpp file
> 
> do the required changes

done with the changes sir.
one file is in readme and another one is in the c-plus-plus/ds directory.

2020-08-22 12:46 UTC, iamrajiv requested changes
@narayan2111 this program should be in `cp` folder not in `ds` please change

2020-08-22 12:47 UTC, iamrajiv requested changes
@narayan2111 add time and space complexity for the program

2020-08-23 04:49 UTC, narayan2111 commented
> @narayan2111 this program should be in `cp` folder not in `ds` please change

Done sir ,changed the location.

2020-08-23 04:50 UTC, narayan2111 commented
> @narayan2111 add time and space complexity for the program

@iamrajiv  added space and time complexity.

2020-08-23 12:33 UTC, narayan2111 commented
@atarax665 @iamrajiv @plazzy99 @Abhijit2505   Do check my PR so that it can be merged early. I'm waiting for this to be added. 😃

2020-08-23 17:29 UTC, plazzy99 requested changes
one pull request for one issue

2020-08-24 03:38 UTC, narayan2111 commented
> one pull request for one issue

Done sir .

2020-08-24 04:27 UTC, plazzy99 requested changes
Currently, I can see 2 CPP file and 1 deleted file and I cannot find a readme file

2020-08-24 05:13 UTC, narayan2111 commented
> Currently, I can see 2 CPP file and 1 deleted file and I cannot find a readme file

Done with the Updated of README file and deleted extra cpp file.

2020-08-24 15:19 UTC, iamrajiv approved these changes

2020-08-25 03:25 UTC, narayan2111 commented
@plazzy99 @atarax665 sir do check this pull request, so that i can take another issue also.

2020-08-25 06:08 UTC, closed without merging