Greatest Common Divisor (Euclidian Algorithm) in Dart
HarshCasper/NeoAlgo pull request #6297
Opened 2021-04-20 14:00 UTC by ashuvssut

Greatest Common Divisor (Euclidian Algorithm) in Dart

I have written the comments to give a explanation and a proof for the Euclidian algorithm that states that `the remainder a' of a/b is also divisible by the GCD of a and b (i.e. d)` This single fact is used in the algorithm. The Statement might be confusing but my proof for that will make it easy to understand

My examples explanations illustrates how Time Complexity is `O(logn)` 😎

Hope you ll like it 😁

2021-04-21 17:50 UTC, atarax665 approved these changes

2021-04-22 07:17 UTC, ankitaggarwal23 requested changes

2021-04-22 07:17 UTC, ankitaggarwal23 commented on Dart/maths/Euclidean_Algorithm_to_find_GCD.dart
> +
Remove extra test case

2021-04-22 07:36 UTC, ashuvssut commented on Dart/maths/Euclidean_Algorithm_to_find_GCD.dart
> +    = gcd(100,25) here 25%100=25
Example 1 is referred here. this example 1 is important

it shows why gcd(a,b) ultimately becomes gcd(b,a) if a<b

2021-04-22 07:39 UTC, ashuvssut commented on Dart/maths/Euclidean_Algorithm_to_find_GCD.dart
> +    i.e. a,b,d have common gcd (You are going to get it at the end of calculation ---- consider example2)
Example 2 is reffered here. 

It shows how a,b,d have a common gcd d
gcd(100,70)
    =gcd(70,30)
    =gcd(30,10)
    =gcd(10,0)

it shows how problem is solved in O(logn)

2021-04-22 07:41 UTC, ashuvssut commented on Dart/maths/Euclidean_Algorithm_to_find_GCD.dart
> +    Why return gcd(b, a % b) and not gcd(a % b, b)???
Example 2 is reffered here.

it supports why in subsequent stack-frame we return gcd(b, a % b) and not gcd(a % b, b)

gcd(100,70)
=gcd(70,30)
=gcd(30,10)
=gcd(10,0)

2021-04-22 07:46 UTC, ashuvssut commented
@ankitaggarwal23 should i still delete the test case?

Both are important and serve as an example for my explanation i gave for the algorithm

2021-04-22 13:14 UTC, ankitaggarwal23 approved these changes

2021-04-22 13:14 UTC, merged