Max distance between same elements in Python
HarshCasper/NeoAlgo pull request #6298
Opened 2021-04-20 14:02 UTC by arpit456jain

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Let say an array is given with repeated elements, we have  to find the maximum distance between two occurrences of an element.

eg:
[1, 1, 2, 2, 2, 1]

ans : 5 (between two ones first and last)
Distance for 1 is: 5-0 = 5
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes : #6296 
(Write your answer here.)

2021-04-21 10:33 UTC, arpit456jain commented
@ankitaggarwal23 please review

2021-04-22 03:01 UTC, ankitaggarwal23 requested changes
Readme file is buggy fix it

2021-04-22 04:29 UTC, arpit456jain commented
@ankitaggarwal23 done

2021-04-22 07:15 UTC, ankitaggarwal23 requested changes

2021-04-22 07:15 UTC, ankitaggarwal23 commented on Python/README.md
> +* [Max distance between same elements](ds/MaxDistanceBetweenSameElements.py)
Write it as `Maximum`

2021-04-22 13:17 UTC, ankitaggarwal23 approved these changes

2021-04-22 13:17 UTC, merged