QuickSort on Singly Linked list added
HarshCasper/NeoAlgo pull request #6306
Opened 2021-04-20 15:06 UTC by Avantika782

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Program Quick sort for Singly linked list in C++ added
(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue : #6031 
Pull Request :

2021-04-20 15:09 UTC, Avantika782 commented
@ankitaggarwal23 Please review my PR and let me know if it has some correction to do.

2021-04-20 15:11 UTC, Avantika782 commented
@ankitaggarwal23  @gat786  Please review my PR and let me know if it has some correction to do.

2021-04-22 03:53 UTC, ankitaggarwal23 reviewed
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 07:16 UTC, Avantika782 commented
@ankitaggarwal23  Review my PR and I'm not able to detect why these checks  are not being checked.
Help me to get out of this and if any further correction please mention.

2021-04-29 09:06 UTC, Avantika782 commented
@ankitaggarwal23 @anushkrishnav  Review my PR and I'm not able to detect why these checks are not being checked.
Help me to get out of this and if any further correction please mention.

2021-04-30 11:20 UTC, ankitaggarwal23 requested changes

2021-04-30 11:20 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/qsort_on_LL.cpp
> +#include <cstdio>
Replace header with ` #include <bits/stdc++.h>`

2021-04-30 11:20 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/qsort_on_LL.cpp
> +    addNode(&head, 110);
Use dynamic inputs don't use static one

2021-04-30 11:20 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/qsort_on_LL.cpp
> +
remove extra lines

2021-05-06 04:41 UTC, Avantika782 commented on C-Plus-Plus/ds/qsort_on_LL.cpp
> +
@ankitaggarwal23 Review my PR once again.

2021-05-12 12:11 UTC, ankitaggarwal23 reviewed
Unknown file found. Don't push more than one code file in a single PR.

2021-05-12 12:11 UTC, closed without merging