Traveling Salesman Problem using Dynamic programming in Java
HarshCasper/NeoAlgo pull request #6352
Opened 2021-04-21 19:32 UTC by Khushi-24

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

### Description

Fixed https://github.com/TesseractCoding/NeoAlgo/issues/6289

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2021-04-22 09:21 UTC, ankitaggarwal23 reviewed
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

2021-04-22 12:54 UTC, Khushi-24 commented
Code is a bit difficult to understand that's why at some places I have tried to explain code via multiline comments in detail. @ankitaggarwal23 should I make them short as well(comments)? Can you please guide?

2021-04-30 11:28 UTC, ankitaggarwal23 requested changes

2021-04-30 11:28 UTC, ankitaggarwal23 commented on Java/dp/Traveling_SalesmanDP.java
> +}
Rewrite it

```
public class Traveling_SalesmanDP {

    public static void main(String[] args)
    {

        Scanner in = new Scanner(System.in);

        int c[][]=new int[10][10], tour[]=new int[10];

        int i, j,cost;

        System.out.println("");

        // taking no. of cities input from user
        System.out.print("Enter No. of Cities: ");

        int n = in.nextInt();

        if(n==1)

        {
            System.out.println("");
            System.out.println("Path is not possible!");
            System.exit(0);

        }

        System.out.println("");
        System.out.println("Enter the Cost Matrix:");

        for(i=1;i<=n;i++){
            for(j=1;j<=n;j++){
                c[i][j] = in.nextInt();
            }
        }

        for(i=1;i<=n;i++){
            tour[i]=i;
        }

        cost = tspdp(c, tour, 1, n);

        System.out.println("");

        //printing out the path(min cost)
        System.out.print("The Optimal Tour is: ");

        for(i=1;i<=n;i++)

            System.out.print(tour[i]+"->");

        System.out.println("1");

        System.out.println("");

        //cost of the optimal path
        System.out.println("Minimum Cost: "+cost);

    }

    static int tspdp(int c[][], int tour[], int start, int n)
    {

        int mintour[]=new int[10], temp[]=new int[10], mincost=999,ccost, i, j, k;

        if(start == n-1)
        {
            return (c[tour[n-1]][tour[n]] + c[tour[n]][1]);
        }

        for(i=start+1; i<=n; i++)
        {

            for(j=1; j<=n; j++)

                temp[j] = tour[j];

            temp[start+1] = tour[i];

            temp[i] = tour[start+1];

            if((c[tour[start]][tour[i]]+(ccost=tspdp(c,temp,start+1,n)))<mincost)
            {
                mincost = c[tour[start]][tour[i]] + ccost;

                for(k=1; k<=n; k++)

                    mintour[k] = temp[k];
            }
        }

        for(i=1; i<=n; i++)
        {
            tour[i] = mintour[i];
        }
        return mincost;
    }
}

```

2021-05-03 13:09 UTC, closed without merging