Pronic numbers in C++
HarshCasper/NeoAlgo pull request #6404
Opened 2021-04-22 11:21 UTC by ShrutiOmer

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
YES

### Description
I have added the Pronic Number program in C++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes: #5945

2021-04-27 03:54 UTC, HarshCasper requested changes

2021-04-27 03:54 UTC, HarshCasper commented on C-Plus-Plus/math/Pronic_numbers.cpp
> +}
Format the Code

2021-04-27 03:54 UTC, HarshCasper commented on C-Plus-Plus/math/Pronic_numbers.cpp
> +		   return false;
Fix the indentation

2021-04-27 03:54 UTC, HarshCasper commented on C-Plus-Plus/math/Pronic_numbers.cpp
> +    cout<<"PRONIC NUMBERS from "<<ll<<" to "<<hl<<" are:\n";
Use lower-case characters

2021-04-30 11:34 UTC, ankitaggarwal23 approved these changes

2021-04-30 11:34 UTC, merged