Added AVL Tree - CH20
HarshCasper/NeoAlgo pull request #641
Opened 2020-08-20 13:15 UTC by yashsahay2014

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added implementation of AVL Tree.
AVL tree is a height-balanced binary search tree (BST) where the Balance Factor ( the difference between heights of left and right subtrees) cannot be more than one for all nodes.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-20 15:56 UTC, iamrajiv requested changes
@yashsahay2014 add sample input-output

2020-08-20 15:56 UTC, iamrajiv commented on C/graphs/AVL_Tree.c
> +/*Progrm for AVL Tree*/
@yashsahay2014 fix `Progrm` typo

2020-08-20 16:20 UTC, siddharth25pandey requested changes
@yashsahay2014 Please do following modifications
* Add the Pre & Post Order traversal of the Constructed AVL Tree
* Add more suitable comments in the Code

2020-08-23 16:59 UTC, yashsahay2014 commented
@iamrajiv @siddharth25pandey Sorry for the delay. I have made the requested changes. Kindly review them.

2020-08-24 19:41 UTC, iamrajiv requested changes
@yashsahay2014 Add space and time complexity like time for rotate operations, updating the height, AVL insert etc.

2020-08-24 19:41 UTC, iamrajiv commented on C/graphs/AVL_Tree.c
> +------------------------------------------------*/
@yashsahay2014 remove this type of line pattern looks unprofessional

2020-08-24 19:41 UTC, iamrajiv commented on C/graphs/AVL_Tree.c
> +------------------------------------------------*/
remove this too

2020-08-24 20:46 UTC, yashsahay2014 commented
@iamrajiv I have made the requested changes and also included Time & Space complexity. But there is Merge Conflicts Labeler error. Kindly help me & how to solve that error?

2020-08-24 20:58 UTC, iamrajiv commented
@yashsahay2014 please update the readme

2020-08-24 21:16 UTC, yashsahay2014 commented
@iamrajiv Done

2020-08-24 21:20 UTC, iamrajiv commented
@yashsahay2014 update this https://github.com/TesseractCoding/NeoAlgo/blob/master/C/README.md

2020-08-24 21:22 UTC, yashsahay2014 commented
@iamrajiv Do I need to make a new PR for that? Kindly guide me.

2020-08-24 21:25 UTC, iamrajiv commented
@yashsahay2014 no just go to your branch and update the `C/README.md` file. Updating `C/README.md` file means add AVL Tree program link in graphs section.

2020-08-24 21:33 UTC, iamrajiv commented
@yashsahay2014 I have updated the readme

2020-08-24 21:35 UTC, yashsahay2014 commented
> @yashsahay2014 no just go to your branch and update the `C/README.md` file. Updating `C/README.md` file means add AVL Tree program link in graphs section.

@iamrajiv I have also done this. Thanks for guiding me. Kindly merge it into master.

2020-08-24 21:36 UTC, iamrajiv approved these changes

2020-08-24 21:38 UTC, iamrajiv commented
@yashsahay2014 I have approved the changes. Wait for others to review the changes.

2020-08-31 11:28 UTC, yashsahay2014 commented
@siddharth25pandey @SKAUL05 kindly review the PR

2020-11-15 00:19 UTC, closed without merging