Chopsticks in C++
HarshCasper/NeoAlgo pull request #6416
Opened 2021-04-22 12:37 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code added in cp(competitive programming) folder

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6401

2021-04-26 11:55 UTC, gayatri517 commented
@ankitaggarwal23 Please review this PR.

2021-04-29 05:54 UTC, gayatri517 commented
@ankitaggarwal23 @HarshCasper Please review my PR

2021-04-30 04:02 UTC, siddharth25pandey requested changes
@gayatri517 Small changes are required

2021-04-30 04:02 UTC, siddharth25pandey commented on C-Plus-Plus/cp/chopsticks.cpp
> +    int n,d,a;
Use a good naming convention for all three

2021-04-30 16:56 UTC, closed without merging