C++ | Block Sum of Matrix
HarshCasper/NeoAlgo pull request #6436
Opened 2021-04-22 17:05 UTC by U-c0de

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
(YES)

### Description
Block Sum of Matrix (Submatrix block addition according to coordinates) | C++ | Dynamic Programming

### Checklist
- [ yes] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

 #6425

2021-04-28 07:06 UTC, U-c0de commented
Please Check -- @HarshCasper @gat786

2021-04-29 04:18 UTC, U-c0de commented
@ankitaggarwal23  Do check !!

2021-04-30 04:15 UTC, U-c0de commented
Please check this @siddharth25pandey

2021-04-30 04:32 UTC, siddharth25pandey requested changes
@U-c0de Small changes are required

2021-04-30 04:32 UTC, siddharth25pandey commented on C-Plus-Plus/dp/BlockSumMatrix.cpp
> +   vector<vector<int>> sz1 = [[1,2,3], [4,5,6], [7,8,9]];  //put the input from test cases
Take Dynamic input from the user with displaying  message in print form, as what are you taking input from the user

2021-04-30 05:31 UTC, U-c0de commented
@siddharth25pandey  Now check

2021-04-30 08:52 UTC, U-c0de commented
Changes made @siddharth25pandey

2021-04-30 13:48 UTC, ankitaggarwal23 reviewed
Code plagiarized from [here](https://www.tutorialspoint.com/matrix-block-sum-in-cplusplus)

2021-04-30 13:48 UTC, closed without merging