kadane's Algorithm in C
HarshCasper/NeoAlgo pull request #645
Opened 2020-08-20 19:08 UTC by raksha009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

Max subarray sum implemented using Kadane's Algorithm in C.

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
ISSUE: #178 

Plz review my Pr @Kajol-Kumari  @harsh-9in

2020-08-21 12:26 UTC, iamrajiv requested changes
@raksha009 rename the file to `maxSubArraySum` since Kadane's Algorithm is more general algorithm and can be used in other problems but in your code, you have implemented `maxSubArraySum` which uses Kadane's Algorithm so renaming the file to `maxSubArraySum.c` will look better. Also, add time and space complexity at the end of the file.

2020-08-21 22:04 UTC, raksha009 commented
Done. Plz review and merge my pr @iamrajiv

2020-08-22 04:37 UTC, SKAUL05 requested changes

2020-08-22 04:37 UTC, SKAUL05 commented on C/cp/maxSubArraySum.c
> +	for (int i = 1; i < n; i++ ){
Change `i` to some suitable variable names.

2020-08-22 04:37 UTC, SKAUL05 commented on C/cp/maxSubArraySum.c
> +	int n;
Change all alphabets to suitable variable names

2020-08-22 06:48 UTC, Kajol-Kumari requested changes
Hey @raksha009 I am not sure why this is happening but when i ran your program it's taking input in the way i have attached below and also take a look at the answer of the code snippet i have pasted.
Can you please look at it, why is it happening?

```
Enter number of elemets in array                                                                                                
1                                                                                                                               
6                                                                                                                               
Enter elemets of array                                                                                                          
1                                                                                                                               
Maximum sum of subarray is 6
```

2020-08-22 06:48 UTC, Kajol-Kumari commented on C/cp/maxSubArraySum.c
> +	printf("Enter number of elemets in array \n");
please change `printf("Enter number of elemets in array \n");` to `printf("Enter the size of the array \n");`

2020-08-22 06:48 UTC, Kajol-Kumari commented on C/cp/maxSubArraySum.c
> +	printf("Enter elemets of array \n");
please correct the typo here `elemets` to  `elements`

2020-08-24 02:57 UTC, raksha009 commented
Done the changes @Kajol-Kumari

2020-08-24 03:02 UTC, iamrajiv requested changes
@raksha009 add time and space complexity

2020-08-24 03:02 UTC, iamrajiv commented on C/cp/maxSubArraySum.c
> +
@raksha009 remove the unnecessary line break

2020-08-24 03:23 UTC, iamrajiv requested changes

2020-08-24 03:23 UTC, iamrajiv commented on C/cp/maxSubArraySum.c
> +SPACE COMPLEXITY : o(1) as no new space is allocated
@raksha009 change `o(1)` to `O(1)`

2020-08-24 07:03 UTC, iamrajiv approved these changes

2020-08-24 07:09 UTC, SKAUL05 approved these changes

2020-08-24 13:55 UTC, Kajol-Kumari approved these changes
LGTM :)

2020-08-24 15:15 UTC, raksha009 commented
Plz merge my PR @Kajol-Kumari @SKAUL05 @iamrajiv

2020-08-25 06:16 UTC, merged

2020-08-25 13:50 UTC, iamrajiv commented
@all-contributors please add @raksha009 for code