Added Is Symmetric Tree
HarshCasper/NeoAlgo pull request #6471
Opened 2021-04-23 12:53 UTC by Nidhideveloper

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Is Symmetric Tree 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6464

2021-04-23 12:56 UTC, Nidhideveloper commented
@HarshCasper Sir kindly review the pr and let me know if there is any mistake that i need to correct.

2021-04-29 04:01 UTC, HarshCasper requested changes

2021-04-29 04:01 UTC, HarshCasper commented on Java/README.md
> -- [Keys and rooms for entry](other/Key_n_room.java)
Why did you change this when its not a refactor?

2021-04-29 07:43 UTC, Nidhideveloper commented
@HarshCasper  Sir, I have made changes accordingly , please see to it. Thank you.

2021-04-29 07:44 UTC, Nidhideveloper commented
> @HarshCasper Sir kindly review the pr and let me know if there is any mistake that i need to correct.

Sir mad e changes accordingly.

2021-04-30 13:03 UTC, ankitaggarwal23 approved these changes

2021-04-30 13:03 UTC, merged