Wave array
HarshCasper/NeoAlgo pull request #6542
Opened 2021-04-25 20:16 UTC by Aayushi-Mittal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Sort the array into a wave-like array and return it. In other words, arrange the elements into a sequence such that a1 >= a2 <= a3 >= a4 <= a5..... (considering the increasing lexicographical order) in python.
For eg: arr[] = {1,2,3,4,5}
Output: 2 1 4 3 5

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6315

2021-04-28 18:35 UTC, Aayushi-Mittal commented
@ankitaggarwal23 @HarshCasper Please review my pull request.

2021-05-02 14:42 UTC, Aayushi-Mittal commented
@ankitaggarwal23 Please merge the PR if everything is fine.

2021-05-03 05:03 UTC, Aayushi-Mittal commented
Otherwise, It will become unassigned.

2021-05-07 14:25 UTC, Aayushi-Mittal commented
@ankitaggarwal23 Please merge the PR if everything is fine.

2021-05-12 12:33 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs

2021-05-12 12:33 UTC, ankitaggarwal23 commented on Python/README.md
> +- [Wave Array](/other/Wave_Array.py)
Remove / before other

2021-05-12 12:33 UTC, ankitaggarwal23 commented on Python/other/Wave_Array.py
> +"""
Make it short and understandable

2021-05-12 12:33 UTC, ankitaggarwal23 commented on Python/other/Wave_Array.py
> +  print(el, end=" ")
Don't use a single letter for variable names.

2021-05-14 09:48 UTC, Aayushi-Mittal commented
Did the required changes. Please review.

2021-05-15 07:14 UTC, ankitaggarwal23 approved these changes

2021-05-15 07:14 UTC, merged