Reverse first k elements in a queue in Python
HarshCasper/NeoAlgo pull request #6546
Opened 2021-04-26 08:20 UTC by arpit456jain

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

reversing first k elements in a queue
Enter the number of elements in array
5
Enter value of k
2
Enter the array
1 2 3 4 5

Output: 2 1 3 4 5

Fixes : #6545

2021-04-27 10:02 UTC, arpit456jain commented
@ankitaggarwal23 kindly review  my PR

2021-04-29 18:43 UTC, arpit456jain commented
@ankitaggarwal23

2021-04-30 13:44 UTC, ankitaggarwal23 requested changes

2021-04-30 13:44 UTC, ankitaggarwal23 commented on Python/README.md
> +* [Reverse First K elements of Queue.py](ds/Reverse_First_K_elements_of_Queue.py)
remove .`py` from [Reverse First K elements of Queue.py]

2021-04-30 14:36 UTC, arpit456jain commented
@ankitaggarwal23 requested changes done

2021-05-01 13:45 UTC, arpit456jain commented
@ankitaggarwal23

2021-05-05 10:03 UTC, arpit456jain commented
@ankitaggarwal23

2021-05-10 05:39 UTC, arpit456jain commented
@ankitaggarwal23 kindly merge this its been 14 days

2021-05-11 05:01 UTC, arpit456jain commented
@ankitaggarwal23 @bhav09 can anyone review my PR its been a long time

2021-05-12 12:34 UTC, ankitaggarwal23 approved these changes

2021-05-12 12:35 UTC, merged