Position of the only set bit
HarshCasper/NeoAlgo pull request #6619
Opened 2021-04-28 16:02 UTC by RaveenaBhasin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

To find the position of the only set bit in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6615

2021-04-28 16:07 UTC, RaveenaBhasin commented
@ankitaggarwal23 Please review my PR

2021-04-30 17:17 UTC, ankitaggarwal23 reviewed
We don't accept such code. It falls neither as a Data Structure not as an algorithm.

2021-05-03 14:09 UTC, RaveenaBhasin commented
@ankitaggarwal23 But there are so many questions on bit manipulation already present so what is the problem with this question?

2021-05-05 09:17 UTC, HarshCasper requested changes
Add README updates as well. Shift the I/O sample at the bottom of the code along with the Time & Space Complexity.

2021-05-05 09:23 UTC, RaveenaBhasin commented
@HarshCasper I'll complete the required changes soon.

2021-05-05 10:57 UTC, RaveenaBhasin commented
@HarshCasper Required changes completed. Kindly review my PR.

2021-05-12 12:36 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.
- comments you add are above the line of code and not alongside it.

2021-05-13 05:07 UTC, RaveenaBhasin commented
@ankitaggarwal23 I have added the description, removed extra spaces, and added a new line at the EOF else everything was already present.

2021-05-15 07:17 UTC, ankitaggarwal23 requested changes

2021-05-15 07:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/Bit--Manipulation/Position_of_the_only_set_bit.cpp
> +        n=n>>1;   //Using right shift operator
You need to add comments to your code. Make sure the comments you add are above the line of code and not alongside it.

2021-05-15 07:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/Bit--Manipulation/Position_of_the_only_set_bit.cpp
> +    return 0;
Add input-output prompts to make the program more interactive.

2021-05-15 07:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/Bit--Manipulation/Position_of_the_only_set_bit.cpp
> +*/
```
/*

Sample Input/Output:

Input:

Output:


Time complexity:
Space complexity:

*/
```

Use this format

2021-05-18 05:51 UTC, ankitaggarwal23 reviewed
Last Reminder, Are you still working on it.

2021-05-19 18:32 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity. Thank you for your valuable time.😊

2021-05-19 18:32 UTC, closed without merging