Added code for  Sum of Root To Leaf Binary Numbers
HarshCasper/NeoAlgo pull request #6646
Opened 2021-04-29 12:35 UTC by kotwani2883

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

 Sum of Root To Leaf Binary Numbers

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6439

2021-05-04 05:32 UTC, siddharth25pandey requested changes
Small change is required, rest is fine 💯

2021-05-04 05:32 UTC, siddharth25pandey commented on C-Plus-Plus/ds/RootToLeafSum.cpp
> +	root->right->right=newNode(1);
Take Dynamic Input from the user

2021-05-04 05:59 UTC, kotwani2883 commented
Made Changes Pls check

2021-05-07 10:56 UTC, siddharth25pandey approved these changes
@kotwani2883 LGTM 💯 Able to merge

2021-05-07 10:56 UTC, merged