Fold a linked list
HarshCasper/NeoAlgo pull request #6668
Opened 2021-04-30 12:34 UTC by Prerna-07

### Have you read the [Contributing Guidelines on Pull Requests]Yes

Yes

### Description

The function is expected to place last element after 1st element, 2nd last element after 2nd element and so on

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

closes :  #6438

2021-04-30 12:35 UTC, Prerna-07 commented
@ankitaggarwal23 , @bhav09 , @anushkrishnav pls review the PR

2021-05-12 12:39 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.
- comments you add are above the line of code and not alongside it.

2021-05-12 12:39 UTC, ankitaggarwal23 commented on Java/ds/Fold A Linked List.java
> +
Remove redundant description

2021-05-12 12:39 UTC, ankitaggarwal23 commented on Java/ds/Fold A Linked List.java
> +*/
one is enough

2021-05-15 08:21 UTC, Prerna-07 commented
@ankitaggarwal23 done sir pls check.

2021-05-18 08:59 UTC, merged