Longest-Substring-Without-Repeating-Characters solution in C#
HarshCasper/NeoAlgo pull request #669
Opened 2020-08-22 05:01 UTC by PatelKeviin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

This is the sliding window solution for the 'Longest Substring without Repeating Characters' problem, which is way more efficient than the naive brute force approach. 
Complexity Analysis:
The time complexity for the algorithms is linear i.e. O(n), where n is the length of the given string.
The space complexity is O(k), where k is the number of unique characters in the string.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue: [#563 ](https://github.com/TesseractCoding/NeoAlgo/issues/563)

2020-08-23 03:38 UTC, PatelKeviin commented
Hi @Kajol-Kumari @plazzy99 @SKAUL05 @siddharth25pandey @iamrajiv, Could any 3 of you give valuable feedback on my PR. Thanks in advance!

2020-08-23 08:33 UTC, iamrajiv requested changes
@PatelKeviin add sample input-output, space and time complexity

2020-08-23 10:29 UTC, atarax665 requested changes

2020-08-23 10:29 UTC, atarax665 commented on C-Sharp/cp/LengthOfLongestSubstring.cs
> +﻿public class Solution
Add description of the problem.

2020-08-25 09:15 UTC, PatelKeviin commented on C-Sharp/cp/LengthOfLongestSubstring.cs
> +﻿public class Solution
Hi @atarax665, I hope this description works. Thanks for your time and effort.

2020-08-25 09:17 UTC, PatelKeviin commented
> @PatelKeviin add sample input-output, space and time complexity

Hi @iamrajiv, I have added sample inputs/outputs as well as complexities for the algorithm. I hope it answers your concern. Thanks!

2020-08-25 13:58 UTC, iamrajiv approved these changes

2020-08-25 14:02 UTC, SKAUL05 approved these changes

2020-08-31 00:32 UTC, PatelKeviin commented on C-Sharp/cp/LengthOfLongestSubstring.cs
> +﻿public class Solution
Hi @atarax665, could you please review my contribution. Thanks in advance!

2020-09-04 02:38 UTC, PatelKeviin commented
Hi @atarax665, hope this message finds you well. Could you please provide your valuable feedback on this issue so that I can update/improve it and close it asap. Thank you :)

2020-09-07 09:05 UTC, PatelKeviin commented
Hi @iamrajiv and @SKAUL05 thank you for approving my changes. I am still waiting on @atarax665 for quite a few days now (more than 10) and am wondering if I could get some feedback and get this merged. Could you please do something about it. Thanks once again :)

2020-09-07 11:45 UTC, atarax665 approved these changes
Code looks good to me, sorry for the delay though.

2020-09-07 11:46 UTC, merged

2020-09-07 11:47 UTC, atarax665 commented
@all-contributors add @PatelKeviin  for his code.