Best fit in python
HarshCasper/NeoAlgo pull request #6694
Opened 2021-05-01 05:38 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Fixes #6673 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #6673

2021-05-01 05:56 UTC, aaadddiii commented
@HarshCasper  @ankitaggarwal23  @anushkrishnav  please review my pr

2021-05-05 14:01 UTC, ankitaggarwal23 requested changes

2021-05-05 14:01 UTC, ankitaggarwal23 commented on Python/README.md
> +- [Best fot memory allocation](ds/Bestfit.py)
fix typo

2021-05-05 14:09 UTC, ankitaggarwal23 approved these changes

2021-05-05 14:09 UTC, merged

2021-05-05 14:09 UTC, aaadddiii commented
@ankitaggarwal23  I have made the changes can you please review it