Next larger element-tree_using cpp
HarshCasper/NeoAlgo pull request #6707
Opened 2021-05-01 10:50 UTC by anshika272

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given a generic tree and an integer n. Find and return the node with the next larger element in the tree i.e. find a node with a value just greater than n.
Note: Return NULL if no node is present with a value greater than n.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #6706

2021-05-01 10:53 UTC, anshika272 commented
@ankitaggarwal23 @HarshCasper @anushkrishnav please review my PR.

2021-05-20 19:21 UTC, ankitaggarwal23 requested changes

2021-05-20 19:21 UTC, ankitaggarwal23 commented on C-Plus-Plus/ds/Next_Larger_Element-tree_using_CPP.cpp
> +#include <vector>
Replave header with` #include<bits/stdc++.h>`

2021-05-21 09:14 UTC, anshika272 commented
@ankitaggarwal23 pls review the changes

2021-05-21 12:04 UTC, ankitaggarwal23 approved these changes

2021-05-21 12:04 UTC, merged

2021-05-21 12:05 UTC, ankitaggarwal23 commented
@all-contributors bot please add @anshika272 for code