Play Fair Cipher Algorithm in Cpp
HarshCasper/NeoAlgo pull request #6730
Opened 2021-05-02 06:58 UTC by ravireddy07

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

- Added code and updated README.md

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#6728 
(Write your answer here.)

2021-05-12 13:04 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-05-12 13:04 UTC, ankitaggarwal23 commented on C-Plus-Plus/cryptography/PlayFair_Cipher.cpp
> +    */
remove this part

2021-05-12 13:04 UTC, ankitaggarwal23 commented on C-Plus-Plus/cryptography/PlayFair_Cipher.cpp
> +*/
write the output in the way your code is producing

2021-05-13 05:33 UTC, ravireddy07 commented on C-Plus-Plus/cryptography/PlayFair_Cipher.cpp
> +    */
Done

2021-05-13 05:35 UTC, ankitaggarwal23 approved these changes

2021-05-13 05:50 UTC, merged