Auto Key Cipher Algorithm in C
HarshCasper/NeoAlgo pull request #6732
Opened 2021-05-02 07:09 UTC by ravireddy07

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

- Auto Key Cipher Algorithm code added in C and updated README.md
(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#6655 
(Write your answer here.)

2021-05-06 04:24 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-05-06 09:15 UTC, ravireddy07 commented
> Few changes:
> 
> * Add Multi-Line Comments
> * Add a beginner-friendly description at the top

Hey @ankitaggarwal23,
The requested changes have been made, have a look at once.

2021-05-12 13:03 UTC, ankitaggarwal23 requested changes

2021-05-12 13:03 UTC, ankitaggarwal23 commented on C/cryptography/AutoKey_Cipher.c
> +*/
shift this at the end of the file

2021-05-13 05:15 UTC, ravireddy07 commented on C/cryptography/AutoKey_Cipher.c
> +*/
Moved to End of file.

2021-05-13 05:29 UTC, ankitaggarwal23 approved these changes

2021-05-13 05:30 UTC, merged