Issue 6566
HarshCasper/NeoAlgo pull request #6746
Opened 2021-05-02 17:43 UTC by noviicee

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for priority queue in python and updated the corresponding readme file.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
closes #6566

2021-05-02 18:01 UTC, noviicee commented
@HarshCasper kindly review this one.

2021-05-07 11:16 UTC, noviicee commented
@ankitaggarwal23 can you review this..?
If the pr  is not merged within 2 days..it will be closed along with the issue!

2021-05-31 08:12 UTC, siddharth25pandey requested changes
@noviicee Do the suggested changes

2021-05-31 08:12 UTC, siddharth25pandey commented on Python/ds/priority_queue.py
> +    pq1.insert_into_pq('W', 55)
Use Dynamic Input

2021-05-31 12:14 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

2021-05-31 17:23 UTC, noviicee commented
> Few changes:
> 
> * Add Multi-Line Comments
> * Add a beginner-friendly description at the top
> * Use proper code Format
> * Remove extra lines of code and spaces
> * Add sample I/O at the end of the Code
> * Add Time and Space Complexity at the end of the Code
> * Add a new line at the EOF
> * Use proper display message how you are reading and writing outputs
> * Add input-output prompts to make the program more interactive.

I have added multi-line comments wherever necessary, sample test-cases and space-time complexity at the end of the code.
I have also formatted the code according to pep8 guidelines.

2021-05-31 18:40 UTC, ankitaggarwal23 approved these changes

2021-05-31 18:41 UTC, merged