Prime factorisation using sieve- Python
HarshCasper/NeoAlgo pull request #676
Opened 2020-08-22 14:30 UTC by Nagasuruthika

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Prime factorization using sieve- Python.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

prime factorization using sieve #437

2020-08-22 19:28 UTC, iamrajiv requested changes
@Nagasuruthika add examples for the code in the docstring

2020-08-22 19:28 UTC, iamrajiv commented on Python/cp/Prime_factorisation_using_sieve.py
> +import math as mf
@Nagasuruthika avoid using short variables. Use math as it is

2020-08-23 04:09 UTC, atarax665 requested changes

2020-08-23 04:09 UTC, atarax665 commented on Python/cp/Prime_factorisation_using_sieve.py
> +    print(y[i], end = " ")
Add sample input/output in commented form.

2020-08-23 09:08 UTC, Nagasuruthika commented
@atarax665 @iamrajiv changes made!

2020-08-23 09:46 UTC, SKAUL05 requested changes

2020-08-23 09:46 UTC, SKAUL05 commented on Python/cp/Prime_factorisation_using_sieve.py
> +        spf[i] = i
Meaningful variable names

2020-08-23 09:46 UTC, SKAUL05 commented on Python/cp/Prime_factorisation_using_sieve.py
> +x = int(input("Enter the number to find prime factors for:"))
Use readable name instead of x.
Include.  __name__ == '__main__'

2020-08-23 09:46 UTC, SKAUL05 commented on Python/cp/Prime_factorisation_using_sieve.py
> +y = getFactorization(x) #function calling
```
It should be get_factorization
```
Follow PEP8 Guidelines.
Inculde function docstrings

2020-08-23 16:03 UTC, Nagasuruthika commented
@SKAUL05 changes made! Please do review.

2020-08-23 16:08 UTC, SKAUL05 commented
> @SKAUL05 changes made! Please do review.

Showing merge conflicts. Pls resolve it first

2020-08-23 16:41 UTC, Nagasuruthika commented
@SKAUL05 Resolved merge conflict.

2020-08-23 16:42 UTC, SKAUL05 approved these changes

2020-08-24 14:41 UTC, atarax665 approved these changes
LGTM! Please revert Readme file and just make changes corresponding to the file you are adding.

2020-08-24 14:44 UTC, iamrajiv approved these changes

2020-08-24 16:29 UTC, Nagasuruthika commented
@atarax665 I guess the readme file looks fine now, sorry about too many commits for readme file, was figuring a way out

2020-08-24 16:39 UTC, iamrajiv approved these changes

2020-08-24 18:42 UTC, atarax665 approved these changes

2020-08-24 18:43 UTC, merged