Intersection Point in Y shaped Linked List
HarshCasper/NeoAlgo pull request #677
Opened 2020-08-22 15:43 UTC by Rishikeshrajrxl

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(I have closed the previous pull request due to messed up, and here I have created new PR.)

### Description

(Here I have Done two assigned work)
1) Intersection Point in Y shaped Linked List.
2) Created a Contributor's Guideline 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

( #495 )
(#542 )

2020-08-22 18:57 UTC, iamrajiv requested changes
@Rishikeshrajrxl add examples, time and space complexity of the program. Move this code to `cp` section, not in `ds` section. Also, remove unnecessary files in the commit.

2020-08-22 18:58 UTC, iamrajiv requested changes

2020-08-22 18:58 UTC, iamrajiv commented on C-Plus-Plus/ds/Intersection Point of Y shaped LinkedList.cpp
> +       cout<<"\t********************************************************************"<<endl;
@Rishikeshrajrxl avoid using this type of lines and patterns across the program.

2020-08-22 19:16 UTC, Rishikeshrajrxl commented
> @Rishikeshrajrxl add examples, time and space complexity of the program. Move this code to `cp` section, not in `ds` section. Also, remove unnecessary files in the commit.

@iamrajiv , There is no unnecessary file. There are some files that contain Images for the Contribution Page. Please have a look over there.

2020-08-22 19:20 UTC, Rishikeshrajrxl commented on C-Plus-Plus/ds/Intersection Point of Y shaped LinkedList.cpp
> +       cout<<"\t********************************************************************"<<endl;
> @Rishikeshrajrxl avoid using this type of lines and patterns across the program.

I have made this program User interactive which has a good Interface. And these Lines are to separate the function individually.
Previously @plazzy99  appreciated the same program and my work.

2020-08-22 19:23 UTC, Rishikeshrajrxl commented on C-Plus-Plus/ds/Intersection Point of Y shaped LinkedList.cpp
> +       cout<<"\t********************************************************************"<<endl;
These lines are to separate the functions inside the program, if I remove this the interface will look messed.

2020-08-23 17:18 UTC, plazzy99 requested changes
@Rishikeshrajrxl please make one pull request for one issue

2020-08-23 19:37 UTC, Rishikeshrajrxl commented
> @Rishikeshrajrxl please make one pull request for one issue

ok, from next time I will take care of this, Now for now, please review it merge it somehow, if possible.

2020-08-24 04:40 UTC, plazzy99 commented
sorry, we cannot merge this pull request you have to make changes before this request to be merged

2020-08-24 05:00 UTC, closed without merging