Added a program to find the roots of a quadratic equation using c in math directory.
HarshCasper/NeoAlgo pull request #6772
Opened 2021-05-03 20:20 UTC by Myself-Rohit-Dey

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Quadratic equations are commonly used in mathematics.
Added A program that prints roots and also tells us the types of the roots of a quadratic equation ax²+bx+c=0.

### Checklist

- [✓ ] I've read the contribution guidelines.
- [✓ ] I've checked the issue list before deciding what to submit.
- [✓ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Roots of Quadratic equation in C [math] #6768

2021-05-04 09:56 UTC, Myself-Rohit-Dey commented
@HarshCasper @ankitaggarwal23 @gat786 @anushkrishnav @Apoorve73  can anyone check and merge this PR.

2021-05-05 13:16 UTC, ankitaggarwal23 requested changes
Shift the logic to another function and use main for driver code

2021-05-05 20:08 UTC, Myself-Rohit-Dey commented
Updated the File according to the requested changes, @ankitaggarwal23Sir, please review it.

2021-05-06 04:17 UTC, ankitaggarwal23 approved these changes

2021-05-06 04:17 UTC, merged