fcfs algorithm added in operating_system folder and C/README.md modif…
HarshCasper/NeoAlgo pull request #6791
Opened 2021-05-05 15:49 UTC by Bhumika2409

1. Created first_come_first_serve_algorithm.c file in operating_system folder of C.
2. updated the C/README.md file for the ame

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
FCFS is a very famous scheduling algorithm that is used in operating systems and I have written the C code for the same

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-05-12 10:15 UTC, Bhumika2409 commented
@HarshCasper @ankitaggarwal23 @bhav09 @gat786 @anushkrishnav can anyone please review this pr

2021-05-12 13:12 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

Shift the logic to another function and use main for driver code

2021-05-12 14:37 UTC, Bhumika2409 commented
Sorry @ankitaggarwal23 I didn't know that we have to link issue to the PR. This is for issue #6790 . So should I make a new issue?

2021-05-12 14:43 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

2021-05-13 08:42 UTC, Bhumika2409 commented
@ankitaggarwal23  could you please review the changes

2021-05-15 07:23 UTC, ankitaggarwal23 requested changes

2021-05-15 07:23 UTC, ankitaggarwal23 commented on C/operating_system/first_come_first_serve_algorithm.c
> +*/
Rewrite it like that
```
/*

FCFS: First Come First Serve algorithm 

It is a CPU scheduling algorithm, in which the process are taken on the basis of their arrival time. 
The process that arrives first, is alloted the CPU first for the execution. Its working is similar to 
that of the FIFO in queue. It is a non-preemptive algorithm which means that the next process cannot be 
scheduled in the middle of the ongoing execution of a process in CPU.  

Terms explanation:
1. Burst time is the time taken by a process to complete its execution.
2. Waiting time is the total time for which a process has to wait for its chance to get the CPU for execution.
3. Turn around time is the total time between the submission of a process and its completion.

Implementation of the code:
Step 1: The number of process are scanned along with their respective burst time.
Step 2: Waiting time for a process is calculated by adding the burst time of the previous process. Waiting time for first process is taken as 0.
Step 3: Turn around time of a process is calculated which is the sum of burst time and waiting time of that process.
Step 4: Average waiting time and average turn around time are calculated by diving the total waiting and turn around time by nummber of process.

*/
```

2021-05-15 07:23 UTC, ankitaggarwal23 commented on C/operating_system/first_come_first_serve_algorithm.c
> +
Remove extra test case

2021-05-15 07:23 UTC, ankitaggarwal23 commented on C/operating_system/first_come_first_serve_algorithm.c
> +Complexities: Average case time complexity is of O(n^2) and the best case time complexity is of O(n). Space complexity is of O(1)
Rewrite it like that
```
Complexities: 
Time complexity: O(n)
Space complexity: O(1)

```

2021-05-15 07:35 UTC, Bhumika2409 commented
I'll do the changes

2021-05-15 07:58 UTC, Bhumika2409 commented
@ankitaggarwal23 can you please review the changes

2021-05-15 08:21 UTC, ankitaggarwal23 approved these changes

2021-05-15 08:21 UTC, merged