Added Power Of Two in Kotlin
HarshCasper/NeoAlgo pull request #6793
Opened 2021-05-05 15:59 UTC by kiruba-r11

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Closes: #6792

2021-05-05 15:59 UTC, kiruba-r11 commented
@ankitaggarwal23 @HarshCasper @bhav09 Please review this

2021-05-06 04:14 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Add a repl.it link as well

2021-05-06 04:27 UTC, kiruba-r11 commented
@ankitaggarwal23 I have already added all the changes that you requested

2021-05-06 04:28 UTC, ankitaggarwal23 requested changes

2021-05-06 04:28 UTC, ankitaggarwal23 commented on Kotlin/BitManipulation/PowerOfTwo.kt
> +*/
Shift above the header

2021-05-06 04:33 UTC, kiruba-r11 commented
@ankitaggarwal23 I have done it. Please check it again

2021-05-06 04:38 UTC, ankitaggarwal23 approved these changes

2021-05-06 04:39 UTC, merged