Added next nth palindrome
HarshCasper/NeoAlgo pull request #6807
Opened 2021-05-06 02:08 UTC by GayatriMunde

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added the solution to find out the next nth palindrome of given number

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6804

2021-05-06 04:08 UTC, ankitaggarwal23 requested changes

2021-05-06 04:08 UTC, ankitaggarwal23 commented on Python/math/Next_Palindrome.py
> +Example of nth palindrome: 2nd palindrome after 11 is 33
Remove this part

2021-05-06 04:08 UTC, ankitaggarwal23 commented on Python/math/Next_Palindrome.py
> +where k = no of digits in given number
Shift this to the end of the file

2021-05-06 08:45 UTC, GayatriMunde commented
Done!

2021-05-12 13:19 UTC, ankitaggarwal23 approved these changes

2021-05-12 13:19 UTC, merged