This file has been edited
HarshCasper/NeoAlgo pull request #6842
Opened 2021-05-07 12:51 UTC by radhikaaojha

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Segregate Even and Odd nodes in a Linked List using C.

### Checklist

- [x] I've read the contribution guidelines.

- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-05-07 13:06 UTC, radhikaaojha commented
@atarax665 Please Review my PR

2021-05-09 17:36 UTC, atarax665 commented
Please fill the PR template and mention the details of your contribution, also mention the linked issue as here #6816.

2021-05-09 17:41 UTC, atarax665 requested changes

2021-05-09 17:41 UTC, atarax665 commented on C/ds/SegregateOddEven.c
> +      		next_node = temp->next;		//Store value of current odd node's next in next_node
Move comment above the line of code.

2021-05-09 17:41 UTC, atarax665 commented on C/ds/SegregateOddEven.c
> +}
Add space/time complexity and sample input/output. Please refer to any recently merged code to get a better insight.

2021-05-11 04:25 UTC, anushkrishnav commented
Please solve the conflict issue

2021-05-11 12:00 UTC, radhikaaojha commented
I've done the requested changes.Please review my PR @atarax665

2021-05-12 13:32 UTC, ankitaggarwal23 approved these changes

2021-05-12 13:32 UTC, merged

2021-05-12 13:35 UTC, ankitaggarwal23 commented
@all-contributors bot please add @radhikaaojha for code