Added code for Binary Tree from Inorder and Postorder traversal
HarshCasper/NeoAlgo pull request #6846
Opened 2021-05-07 19:52 UTC by kotwani2883

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
Added code for Binary Tree from Inorder and Postorder traversal

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6647

2021-05-07 19:55 UTC, kotwani2883 commented
@siddharth25pandey  kindly review my PR . Thanks

2021-05-09 17:45 UTC, atarax665 approved these changes
LGTM :)

2021-05-11 07:03 UTC, siddharth25pandey requested changes
@kotwani2883 Small change is required, Rest is fine

2021-05-11 07:03 UTC, siddharth25pandey commented on C-Plus-Plus/ds/BinaryTreeFromInorderPostorder.cpp
> + Time Complexity : O(n^2)
Time Complexity is wrong

2021-05-11 07:23 UTC, kotwani2883 commented
But I think the complexity is correct as we are checking the index. I am running a loop inside the Recursion so quadratic is justified in worst case when we have left/right skewed tree

2021-05-11 07:24 UTC, kotwani2883 commented
What should be the complexity according to you? and why kindly justify

2021-05-11 07:41 UTC, siddharth25pandey commented
@kotwani2883 The Time Complexity for Binary Tree traversal is O(n) in worst case where n is the number of nodes (Incase of a Binary Search Tree). Apart from that, it only be O(h), where h is the height of the tree. (It can be O(log(n) as well in best case)
Now, coming to your point you are using a for loop for displaying the nodes elements values with traversal, Hence it's a **combination of traversal plus printing** but when we are talking about time complexity for a particular operation, you need to focus on that particular **only**.
So, either you use recursively or iteratively you will be get O(n) as worst .
Hope it makes sense.

2021-05-11 09:10 UTC, kotwani2883 commented
I am sorry I am cross questioning you againa and again but kindly look at this part of code snippet.
The traversal and recursion are separate but inside the recursion we have this for loop.
for(rootIndex=Instart ; rootIndex<=InEnd ; rootIndex++){
		if(inorder[rootIndex]==rootVal) //We have completely traversed left Subtree
		break;
	}
This is inside the recursion function call  So will it not make any significant effect in Time complexity.

2021-05-11 09:23 UTC, siddharth25pandey commented
@kotwani2883 the helper function you wrote is for conversion of (inorder and postorder ) to preorder traversal. This is **not same** as **traversal of tree** in any method (pre/in/post) order.
You need to write like this:
Time Complexity for performing the given operation : O(n^2)
Time Complexity for performing the traversal of the binary tree : O(n)

2021-05-11 09:27 UTC, kotwani2883 commented
@siddharth25pandey  Thank you for guiding me regarding the Time Complexity .

2021-05-11 09:27 UTC, siddharth25pandey requested changes

2021-05-11 09:27 UTC, siddharth25pandey commented on C-Plus-Plus/ds/BinaryTreeFromInorderPostorder.cpp
> +
Remove this

2021-05-11 09:31 UTC, siddharth25pandey approved these changes
@kotwani2883 LGTM 💯 , All the best for ahead contributions 👍

2021-05-11 09:31 UTC, merged