Target Sum triplets in Python
HarshCasper/NeoAlgo pull request #689
Opened 2020-08-23 06:52 UTC by shubham5351

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
Program in Python to print all triplets of numbers which sum to target.
For example
input:
9
5 7 9 1 2 4 6 8 3
10
output:
1, 2 and 7
1, 3 and 6
1, 4 and 5
2, 3 and 5

### Checklist

- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
- [✓] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Complexity Analysis-
Time Complexity - O(n^2)
Space Complexity - O(1)

2020-08-23 09:54 UTC, atarax665 requested changes

2020-08-23 09:54 UTC, atarax665 commented on Python/cp/Target_Sum_Triplet.py
> +                right -= 1
The function is incomplete. It ain't returning anything.

2020-08-23 09:54 UTC, atarax665 commented on Python/cp/Target_Sum_Triplet.py
> +targettriplets(lst, len(lst), op)
Add sample input/output in commented form.

2020-08-23 09:54 UTC, atarax665 commented on Python/cp/Target_Sum_Triplet.py
> +def targettriplets(lst, rang, target):
Add description of the problem in the beginning with time and space complexity of the algorithm you use.

2020-08-24 01:38 UTC, shubham5351 commented
Ok I will do the changes

2020-08-24 06:55 UTC, shubham5351 commented on Python/cp/Target_Sum_Triplet.py
> +                right -= 1
I am not returning any value as the condition satisfies I am just printing the values.The function is also complete you can review it

2020-08-24 07:15 UTC, shubham5351 commented on Python/cp/Target_Sum_Triplet.py
> +targettriplets(lst, len(lst), op)
I have also added the input/output in commented form.Please Review it.

2020-08-25 04:35 UTC, shubham5351 commented
Can any one tell me why there is this branch conflict I am not able to clarify it.

2020-08-28 07:28 UTC, merged