Adjacent elements Product in python
HarshCasper/NeoAlgo pull request #6902
Opened 2021-05-11 07:08 UTC by chicken-biryani

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(When given an array of integers, we have to find the pair of adjacent elements that have the largest product and return that product.)

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Issue #2236)

2021-05-11 07:11 UTC, chicken-biryani commented
Could you please review this PR?
@atarax665 

(And could you add the GSSOC21 label?)

2021-05-12 14:15 UTC, ankitaggarwal23 requested changes
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

2021-05-18 05:54 UTC, ankitaggarwal23 requested changes
Rest looks good to merge

2021-05-18 05:54 UTC, ankitaggarwal23 commented on Python/cp/adjacent_elements_product.py
> +
Remove this extra lines one line is enough

2021-05-18 05:54 UTC, ankitaggarwal23 commented
Resolve conflicts

2021-05-19 18:33 UTC, ankitaggarwal23 approved these changes

2021-05-19 18:33 UTC, merged