hashtable
HarshCasper/NeoAlgo pull request #7089
Opened 2021-05-18 09:17 UTC by sameeksharl

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description
 hash table implemented in c which includes all CRUD operations (insert, display, update , delete) 
 and also included to return the size of table instantly.
(here updating happens if  the key already present in table )

### Checklist

- [ yes] I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-05-18 10:05 UTC, bhav09 requested changes
Please work on the following areas mentioned in the review.

2021-05-18 10:05 UTC, bhav09 commented on C/ds/hashtable.c
> +// Implementing hash table in C
Description at the start of the code file.

2021-05-18 10:05 UTC, bhav09 commented on C/ds/hashtable.c
> +int hashFunction(int key)
Function descriptions and thus comments are lacking.

2021-05-18 10:05 UTC, bhav09 commented on C/ds/hashtable.c
> +void insert(int key, int data)
Make sure the comment is above the line of code and not alongside.

2021-05-18 10:05 UTC, bhav09 commented on C/ds/hashtable.c
> +
Remove redundant spaces. that are in the form of new lines.

2021-05-18 10:05 UTC, bhav09 commented on C/ds/hashtable.c
> +}
At the end of the code file, write the complexity and sample I/O.

2021-05-20 20:05 UTC, ankitaggarwal23 reviewed
Code already present

2021-05-20 20:05 UTC, closed without merging