code for Search target element in Rotated Sorted Array added
HarshCasper/NeoAlgo pull request #7118
Opened 2021-05-18 16:20 UTC by Bhawana0001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

code for Search target element in Rotated Sorted Array added in C++

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Search target element in Rotated Sorted Array in C++ #7105

2021-05-21 09:51 UTC, Bhawana0001 commented
@ankitaggarwal23  Sir please Review my PR

2021-05-21 09:57 UTC, Bhawana0001 commented
@ankitaggarwal23 please review this PR

2021-05-31 08:13 UTC, siddharth25pandey approved these changes
@Bhawana0001 LGTM 💯 Able to merge

2021-05-31 08:14 UTC, siddharth25pandey requested changes
@Bhawana0001 Resolve the merge conflicts

2021-05-31 08:27 UTC, Bhawana0001 commented
@siddharth25pandey  changes done. Sir, Please review it.

2021-05-31 12:17 UTC, ankitaggarwal23 requested changes

2021-05-31 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +Write an algorithm with O(log n) runtime complexity.
remove this line

2021-05-31 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +*/
remove this redundant comments part

2021-05-31 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +        // Binary Search
remove this redundant comment

2021-05-31 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +        int x;    // input given array element
remove these redundant comments and Use proper display message how you are reading and writing outputs

2021-05-31 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +     cin>>target;
remove these redundant comments and Use proper display message how you are reading and writing outputs

2021-05-31 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +*/
Remove this part and rewrite in such format. Also use only one sample case

2021-05-31 12:17 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +*/
```
/*

Sample Input/Output:

Input:

Output:


Time complexity:
Space complexity:

*/
```

2021-05-31 13:39 UTC, Bhawana0001 commented
@ankitaggarwal23 sir have made the required changes but I when I try to push the changes I don't know what this merge branch thing happened.
please help me to with this.

2021-05-31 13:39 UTC, Bhawana0001 commented
@ankitaggarwal23 sir have made the required changes but I when I try to push the changes I don't know what this merge branch thing happened.
please help me to with this.

2021-05-31 13:46 UTC, siddharth25pandey approved these changes
@Bhawana0001 LGTM 💯 Able to merge

2021-05-31 13:46 UTC, merged

2021-05-31 13:48 UTC, ankitaggarwal23 requested changes
Rest LGTM💯

2021-05-31 13:48 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/Search_target_element_in_Rotated_Sorted_Array.cpp
> +#include <vector>
Replace Header with` #include<bits/stdc++.h>`