XOR Linked List
HarshCasper/NeoAlgo pull request #7124
Opened 2021-05-19 07:09 UTC by radhikaaojha

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

XOR Linked List implementation in C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#7088

2021-05-19 07:11 UTC, radhikaaojha commented
Please review my PR @ankitaggarwal23

2021-05-22 06:40 UTC, radhikaaojha commented
@atarax665

2021-05-23 05:53 UTC, ankitaggarwal23 requested changes

2021-05-23 05:53 UTC, ankitaggarwal23 commented on C/README.md
> +- [XOR Linked List ] (ds/XOR.c)
Remove the space after `List` and also between` ] (`

2021-05-23 09:02 UTC, radhikaaojha commented
I have updated the changes requested @ankitaggarwal23

2021-05-23 12:22 UTC, ankitaggarwal23 approved these changes

2021-05-23 12:23 UTC, merged