All possible String permutations (DART)
HarshCasper/NeoAlgo pull request #7152
Opened 2021-05-19 19:21 UTC by Ayushjain2205

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Dart program to find all possible string combinations for a given input string

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #7069

2021-05-20 20:29 UTC, ankitaggarwal23 requested changes

2021-05-20 20:29 UTC, ankitaggarwal23 commented on Dart/dp/StringPermutations.dart
> +import 'dart:io';
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top

2021-05-20 20:29 UTC, ankitaggarwal23 commented on Dart/dp/StringPermutations.dart
> +*/
Remove extra test case

2021-05-21 10:43 UTC, Ayushjain2205 commented
@ankitaggarwal23 changes made

2021-05-21 12:10 UTC, ankitaggarwal23 approved these changes

2021-05-21 12:10 UTC, merged