Painting fence problem in java
HarshCasper/NeoAlgo pull request #7159
Opened 2021-05-20 03:44 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Fixes #7157 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #7157

2021-05-20 04:06 UTC, aaadddiii commented
@HarshCasper  @ankitaggarwal23  can you please review my pr

2021-05-20 20:36 UTC, ankitaggarwal23 requested changes

2021-05-20 20:36 UTC, ankitaggarwal23 commented on Java/README.md
> +- [evel order traversal of a tree](ds/LevelOrderTraversalRecursion.java)
Why you update this line?

2021-05-20 20:36 UTC, ankitaggarwal23 commented on Java/dp/Painting_fence.java
> +n fences
Remove this part

2021-05-21 06:48 UTC, aaadddiii commented
@ankitaggarwal23  I have made the changes can you please review my pr

2021-05-21 12:12 UTC, ankitaggarwal23 approved these changes

2021-05-21 12:12 UTC, merged