8 Puzzle Problem using BFS
HarshCasper/NeoAlgo pull request #7176
Opened 2021-05-20 09:44 UTC by Manasi2001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

8 Puzzle Problem Solving using BFS has been successfully done. Three initial states have been taken into account and the search technique is applied to reach the goal state.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is with reference to issue #7175.

2021-05-20 20:52 UTC, ankitaggarwal23 requested changes

2021-05-20 20:52 UTC, ankitaggarwal23 commented on Python/search/8_Puzzle_Problem_using_BFS.py
> +
Remove extra test case

2021-05-21 04:47 UTC, Manasi2001 commented
You may check again now @ankitaggarwal23.

2021-05-21 07:51 UTC, Manasi2001 commented
@ankitaggarwal23 I've mentioned complexities here as well.

2021-05-21 12:14 UTC, ankitaggarwal23 approved these changes

2021-05-21 12:16 UTC, merged