8 Puzzle Problem using A* Algorithm
HarshCasper/NeoAlgo pull request #7178
Opened 2021-05-20 10:33 UTC by Manasi2001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

8 Puzzle Problem Solving using A* Algorithm has been successfully done. Three initial states have been taken into account and the search technique is applied to reach the goal state.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is with reference to issue #7177.

2021-05-20 20:53 UTC, ankitaggarwal23 requested changes

2021-05-20 20:53 UTC, ankitaggarwal23 commented on Python/search/8_Puzzle_Problem_using_A_star_Algorithm.py
> +
Remove extra test case

2021-05-21 05:33 UTC, Manasi2001 commented
You may check this again now @ankitaggarwal23.

2021-05-21 05:50 UTC, ankitaggarwal23 requested changes
- Add Time and Space Complexity at the end of the Code

2021-05-21 07:45 UTC, Manasi2001 commented
> * Add Time and Space Complexity at the end of the Code

Done.

2021-05-21 12:14 UTC, ankitaggarwal23 approved these changes

2021-05-21 12:14 UTC, merged

2021-05-21 12:15 UTC, ankitaggarwal23 commented
@all-contributors bot please add @Manasi2001 for code