Minimum cost to construct temple in C++
HarshCasper/NeoAlgo pull request #7239
Opened 2021-05-21 17:43 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code added in cp folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#7235

2021-05-25 10:12 UTC, bhav09 reviewed
The code is not comented. Please comment the code.  Make sure the comments are above the line of code and not alongside.

2021-05-25 12:26 UTC, gayatri517 commented
@bhav09 i have added the comments. Kindly review it

2021-05-26 07:23 UTC, ankitaggarwal23 requested changes

2021-05-26 07:23 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_cost_to_construct_temple.cpp
> +    return count;
Add a one tab space

2021-05-26 07:23 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_cost_to_construct_temple.cpp
> +    return sum;
Add a one tab space

2021-05-26 07:23 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/min_cost_to_construct_temple.cpp
> +    sum=g.dfs();
Add a one tab space

2021-05-26 07:52 UTC, gayatri517 commented
@ankitaggarwal23 I have done the changes.
Kindly review it

2021-05-26 08:40 UTC, ankitaggarwal23 approved these changes

2021-05-26 08:40 UTC, merged