Deque
HarshCasper/NeoAlgo pull request #7244
Opened 2021-05-22 00:49 UTC by chicken-biryani

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Since lists in python are dynamic in nature I have created a doubly ended queue using list in python)

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Issue #7200)

2021-05-22 00:49 UTC, chicken-biryani commented
@atarax665 could you kindly review this?

2021-05-26 07:36 UTC, ankitaggarwal23 requested changes

2021-05-26 07:36 UTC, ankitaggarwal23 commented on Python/ds/Deque_with_list.py
> +implementation using List in Python
- Add a beginner-friendly description at the top

2021-05-26 07:36 UTC, ankitaggarwal23 commented on Python/ds/Deque_with_list.py
> +
Remove this redundant part

2021-05-26 07:36 UTC, ankitaggarwal23 commented on Python/ds/Deque_with_list.py
> +7 to exit '''))
Remove this redundant part

2021-05-26 07:36 UTC, ankitaggarwal23 commented on Python/ds/Deque_with_list.py
> +            ele = int(input("enter elem to insert "))
What is `elem`? Rewrite it to `Element`

2021-05-26 07:36 UTC, ankitaggarwal23 commented on Python/ds/Deque_with_list.py
> +                ele = queue.pop(0)
Use proper naming conventions for declaring variables. `ele`

2021-05-31 18:41 UTC, ankitaggarwal23 reviewed
Thank you for your valuable time.😊

2021-05-31 18:42 UTC, closed without merging