Code
HarshCasper/NeoAlgo pull request #7267
Opened 2021-05-22 18:32 UTC by Muskan0

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for lowest common ancestor of binary search tree.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#7153

2021-05-22 18:35 UTC, Muskan0 commented
Resolves the issue #7153

2021-05-26 07:06 UTC, ankitaggarwal23 requested changes

2021-05-26 07:06 UTC, ankitaggarwal23 commented on Python/ds/lowest_common_ancestor_bst.py
> +Lowest Common Ancestor is:  50
Remove extra test case, one is enough

2021-05-26 07:29 UTC, Muskan0 commented on Python/ds/lowest_common_ancestor_bst.py
> +Lowest Common Ancestor is:  50
Done.

2021-05-26 08:39 UTC, ankitaggarwal23 approved these changes

2021-05-26 08:40 UTC, merged