Added bitonic subarray #7322
HarshCasper/NeoAlgo pull request #7334
Opened 2021-05-26 07:23 UTC by ishitakapoor26

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2021-05-30 20:49 UTC, ishitakapoor26 commented
Pls review my pr @SKAUL05 @nrickles3 @ArchanGhosh @Ayushjain2205

2021-05-31 08:22 UTC, siddharth25pandey requested changes
Do the suggested changes and also add the update in README file

2021-05-31 08:22 UTC, siddharth25pandey commented on C/cp/Bitonic_subarray.c
> +    int A[] = { 3, 5, 8, 4, 5, 9, 10, 8, 5, 3, 4 };
Use Dynamic Input

2021-05-31 08:22 UTC, siddharth25pandey commented on C/cp/Bitonic_subarray.c
> +    findBitonicSubarray(A, n - 1);
Display a message in print form as what are you showing output to the user

2021-05-31 11:25 UTC, ishitakapoor26 commented
@siddharth25pandey pls review changes.

2021-05-31 12:19 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.
- Make sure the comments you add are above the line of code and not alongside it.

2021-05-31 12:41 UTC, ishitakapoor26 commented
> Few changes:
> 
> * Add Multi-Line Comments
> * Add a beginner-friendly description at the top
> * Use proper code Format
> * Remove extra lines of code and spaces
> * Add sample I/O at the end of the Code
> * Add Time and Space Complexity at the end of the Code
> * Add a new line at the EOF
> * Use proper display message how you are reading and writing outputs
> * Add input-output prompts to make the program more interactive.
> * Make sure the comments you add are above the line of code and not alongside it
I've already made these changes. Pls review my pr @siddharth25pandey

2021-05-31 13:43 UTC, siddharth25pandey approved these changes
@ishitakapoor26 LGTM 💯 Able to merge

2021-05-31 13:43 UTC, merged