Bfs rotten oranges code
HarshCasper/NeoAlgo pull request #7344
Opened 2021-05-26 10:31 UTC by Shreya0229

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Added the famous problem of bfs graph implementation of finding Rotten Oranges.

### Checklist

- [ .] I've read the contribution guidelines.
- [. ] I've checked the issue list before deciding what to submit.
- [ .] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue no. #7283

2021-05-29 18:06 UTC, Shreya0229 commented
Please review the PR.

2021-05-31 08:26 UTC, siddharth25pandey requested changes
@Shreya0229 Add the update in README File

2021-05-31 10:00 UTC, Shreya0229 commented
Done. Updated the README File.

2021-05-31 12:21 UTC, ankitaggarwal23 requested changes
Few changes: 

- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

2021-05-31 12:21 UTC, ankitaggarwal23 commented on Java/cp/BFS_RottenOranges.java
> +    Oranges at positions (0,2), (1,2), (2,0) will rot oranges at (0,1), (1,1), (2,2) and (2,1) in unit time.
remove this part

2021-05-31 13:03 UTC, Shreya0229 commented
Done. Updated the changes.

2021-05-31 13:04 UTC, ankitaggarwal23 approved these changes

2021-05-31 13:04 UTC, merged