Issue #7345
HarshCasper/NeoAlgo pull request #7351
Opened 2021-05-26 15:21 UTC by get-satyam

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes I have read all the contributing guidelines on Pull requests

### Description

This program gives the no of points inside a circle that is described by its cartesian coordinates in a vector. The points lying on the border of the circle are a part of that circle too.

### Checklist

- [ ✅ ] I've read the contribution guidelines.
- [ ✅ ] I've checked the issue list before deciding what to submit.
- [ ✅ ] I've edited the `README.md` and link to my code.

2021-05-28 06:40 UTC, get-satyam commented
@bhav09 please review my PR

2021-05-31 08:28 UTC, siddharth25pandey requested changes
Do the suggested changes

2021-05-31 08:28 UTC, siddharth25pandey commented on C-Plus-Plus/cp/No_of_points_inside_a_circle.cpp
> +#include <vector>
Use single header file **bits/stdc++**

2021-05-31 08:28 UTC, siddharth25pandey commented on C-Plus-Plus/cp/No_of_points_inside_a_circle.cpp
> +    vector<vector<int>>points{{1,3},{3,3},{5,3},{2,2}};
Use Dynamic Input

2021-05-31 08:28 UTC, siddharth25pandey commented on C-Plus-Plus/cp/No_of_points_inside_a_circle.cpp
> +    vector<vector<int>>queries{{2,3,1},{4,3,1},{1,1,2}};
Use Dynamic Input

2021-05-31 08:28 UTC, siddharth25pandey commented on C-Plus-Plus/cp/No_of_points_inside_a_circle.cpp
> +    countPoints(points, queries);
Display a message in print form as what are you showing output to the user

2021-05-31 12:33 UTC, ankitaggarwal23 requested changes
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

2021-05-31 12:33 UTC, ankitaggarwal23 commented on C-Plus-Plus/cp/.vscode/settings.json
> +}
Remove this json file

2021-05-31 12:47 UTC, ankitaggarwal23 requested changes
Readme missing

2021-05-31 15:48 UTC, get-satyam commented
@ankitaggarwal23  I have done the necessary changes. Please see to it.

2021-05-31 18:48 UTC, ankitaggarwal23 reviewed
Don't push more than one code file in a single PR.

2021-05-31 18:48 UTC, closed without merging