Ugly number dart
HarshCasper/NeoAlgo pull request #7354
Opened 2021-05-26 15:28 UTC by Ayushjain2205

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Dart program to check if a number is a ugly number or no

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #7348

2021-05-30 07:20 UTC, ankitaggarwal23 approved these changes

2021-05-30 07:21 UTC, ankitaggarwal23 requested changes
Resolve conflicts

2021-05-30 09:54 UTC, Ayushjain2205 commented
@ankitaggarwal23 Conflicts resolved please review

2021-05-31 06:07 UTC, ankitaggarwal23 approved these changes

2021-05-31 06:07 UTC, merged