Subarray with palindromic concatenation added.
HarshCasper/NeoAlgo pull request #7356
Opened 2021-05-26 18:10 UTC by neha07kumari

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

For a given array and an integer K, we need to check if any subarray of size K exists in the array such that concatenation of elements form a palindrome.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues :
Solves issue #7355

2021-05-26 18:12 UTC, neha07kumari commented
@bhav09  @ankitaggarwal23  please review it and let me know if there are any conflicts.

2021-05-31 08:30 UTC, siddharth25pandey requested changes
Do the suggested changes

2021-05-31 08:30 UTC, siddharth25pandey commented on C-Plus-Plus/ds/subarray_palindrome_conact.cpp
> +#include<cmath>
Use single header file **bits/stdc++**

2021-05-31 08:30 UTC, siddharth25pandey commented on C-Plus-Plus/ds/subarray_palindrome_conact.cpp
> +    vector<int> arr ={2,3,5,1,1,5};
Use Dynamic Input

2021-05-31 13:41 UTC, siddharth25pandey commented
@neha07kumari Resolve the merge conflicts

2021-05-31 18:46 UTC, ankitaggarwal23 reviewed
Thank you for your valuable time.😊

2021-05-31 18:46 UTC, closed without merging