Finding equilibrium point in the array (#7381)
HarshCasper/NeoAlgo pull request #7409
Opened 2021-05-29 15:31 UTC by sonali-sk

Have you read the [Contributing Guidelines on Pull Requests]

YES

Description

Given an array of n positive integers, find the first equilibrium point in the array.
Equilibrium Point in an array is a position at which sum of elements before it is equal 
to the sum of elements after it.

Checklist

- [YES ] I've read the contribution guidelines.
- [YES ] I've checked the issue list before deciding what to submit.
- [ YES] I've edited the `README.md` and link to my code.

Related Issues or Pull Requests

Issue #7381

2021-05-30 02:51 UTC, sonali-sk commented
@HarshCasper @ankitaggarwal23 @Apoorve73 @siddharth25pandey

2021-05-31 10:14 UTC, siddharth25pandey requested changes
Do the suggested changes

2021-05-31 10:14 UTC, siddharth25pandey commented on Python/other/equilibrium_point_in_array.py
> +
Add Time and Space Complexity

2021-05-31 11:01 UTC, sonali-sk commented
@siddharth25pandey changes made. Please review.

2021-05-31 12:28 UTC, ankitaggarwal23 requested changes

2021-05-31 12:28 UTC, ankitaggarwal23 commented on Python/other/equilibrium_point_in_array.py
> +
Remove this redundant lines

2021-05-31 12:47 UTC, sonali-sk commented
@ankitaggarwal23 @siddharth25pandey changes made. Please review.

2021-05-31 13:09 UTC, ankitaggarwal23 approved these changes

2021-05-31 13:10 UTC, merged