added cpp file for cycle detection using BFS
HarshCasper/NeoAlgo pull request #7417
Opened 2021-05-29 18:27 UTC by garvitgupta13

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
YES

### Description
Add a cpp code to detect cycle in an undirected graph using BFS. The current detect cycle code uses dfs and I want to add extra approach using BFS

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#7415

2021-05-30 07:30 UTC, ankitaggarwal23 reviewed
Code already present #1157

2021-05-30 08:28 UTC, garvitgupta13 commented
> Code already present

Hey @ankitaggarwal23 the PR#1157 contains the code for checking a cycle using DFS, I have added another approach which checks the cycle using BFS
In the description also I have described about this

2021-05-30 08:35 UTC, garvitgupta13 commented
> Code already present

The code in detect_cycle.cpp and checkCycle.cpp is entirely different and the algorithm used is also different.

2021-05-31 12:31 UTC, ankitaggarwal23 requested changes
Rest looks good to merge

2021-05-31 12:31 UTC, ankitaggarwal23 commented on C-Plus-Plus/graphs/checkCycle_bfs.cpp
> +vector<int> vis(100000, 0); //Visited array, it stores wheather the node is visited or not
Shift comments above the lines of code.

2021-05-31 12:34 UTC, garvitgupta13 commented on C-Plus-Plus/graphs/checkCycle_bfs.cpp
> +vector<int> vis(100000, 0); //Visited array, it stores wheather the node is visited or not
done

2021-05-31 13:10 UTC, ankitaggarwal23 approved these changes

2021-05-31 13:11 UTC, merged