AffineCipher.py
HarshCasper/NeoAlgo pull request #742
Opened 2020-08-23 21:21 UTC by riya-joshi-401

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-23 21:27 UTC, riya-joshi-401 commented
added affine substitution cipher kindly review it
@SKAUL05 @plazzy99 @Abhijit2505 @Kajol-Kumari @HarshCasper @routrohan

2020-08-24 04:52 UTC, SKAUL05 requested changes
Use meaningful variable names instead of alphabets.
Include Sample I/O.

2020-08-24 07:25 UTC, SKAUL05 requested changes

2020-08-24 07:25 UTC, SKAUL05 commented on Python/cryptography/AffineCipher.py
> +          a, b = b, a % b
Change variable names from alphabets to meaningful names in whole script

2020-08-24 14:29 UTC, SKAUL05 approved these changes

2020-08-25 05:52 UTC, plazzy99 requested changes
update readme file for this program

2020-08-26 16:12 UTC, plazzy99 requested changes
you don't have to create the readme file 
you have to edit the python readme file

2020-08-26 18:09 UTC, riya-joshi-401 commented
> you don't have to create the readme file
> you have to edit the python readme file

im not getting exactly what is meant by " python readme file " ..please help me with that!!

2020-08-27 05:33 UTC, plazzy99 commented
> > you don't have to create the readme file
> > you have to edit the python readme file
> 
> im not getting exactly what is meant by " python readme file " ..please help me with that!!

check pull request made in the repository by other participant

2020-08-30 01:41 UTC, Abhijit2505 requested changes
Please add your work to the README file as well.

2020-08-30 01:41 UTC, Abhijit2505 commented on Python/cryptography/AffineCipher.py
> +
Please remove spaced from line 10-13 of your code. They are not needed.

2020-08-30 01:41 UTC, Abhijit2505 commented on Python/cryptography/AffineCipher.py
> +
Remove these spaces as well.

2020-08-31 13:22 UTC, plazzy99 requested changes
code LGTM but you have to update your readme file.

2020-09-01 06:18 UTC, plazzy99 approved these changes

2020-09-04 00:57 UTC, Abhijit2505 approved these changes
It's looking good to me as well.
Kindly Merge this PR

2020-09-04 01:01 UTC, merged

2020-09-04 04:58 UTC, iamrajiv commented
@all-contributors please add @riya-joshi-401 for code