Affine Cipher Cryptography using Java
HarshCasper/NeoAlgo pull request #753
Opened 2020-08-24 04:20 UTC by PrasadMulherkar

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-24 04:41 UTC, siddharth25pandey requested changes
@PrasadMulherkar Please add the **README** file details & fill the PR template by mentioning the issue number properly

2020-08-24 08:09 UTC, atarax665 requested changes

2020-08-24 08:09 UTC, atarax665 commented on Java/cryptography/AffineCipher.java
> +	int z, a, b, a_inverse;
Use meaningful variable names.

2020-08-24 08:09 UTC, atarax665 commented on Java/cryptography/AffineCipher.java
> +}
Add sample input/output in commented form.

2020-09-09 03:57 UTC, PrasadMulherkar commented
I have changed according to the suggestions, please review them.

2020-09-09 08:51 UTC, siddharth25pandey approved these changes
@PrasadMulherkar Good to go
Able to merge
Thanks!

2020-09-26 12:43 UTC, plazzy99 requested changes
update the readme file and do all the changes
ASAP.

2020-09-26 12:43 UTC, plazzy99 commented on Java/cryptography/AffineCipher.java
> +package hakinCodes.affineCipher;
remove package

2020-09-26 12:43 UTC, plazzy99 commented on Java/cryptography/README.md
> +AFFINE CIPHER :-
delete this file

2020-09-27 10:29 UTC, iamrajiv approved these changes

2020-10-01 09:15 UTC, Kajol-Kumari approved these changes
@PrasadMulherkar just address the @plazzy99 comments, rest LGTM :+1:

2020-10-21 04:31 UTC, PrasadMulherkar commented
Sorry for being late... I have made changes suggested by @plazzy99, hope this PR will be okay now

2020-10-22 08:45 UTC, plazzy99 reviewed
update readme file

2020-10-23 05:21 UTC, PrasadMulherkar commented
You told me to delete the readme file now which file to update??

2020-10-23 12:35 UTC, plazzy99 commented
> You told me to delete the readme file now which file to update??

update the existing readme file of java
You can refer to any merged pr for reference

2020-10-23 16:23 UTC, PrasadMulherkar commented
Hey I changed it please review it and tell me...
As I am new at it I tried my best please help me if I am wrong

2020-12-08 07:26 UTC, HarshCasper commented
I guess we can solve it out while cleaning out the Repository. Thanks for the PR @PrasadMulherkar 

Merging it!

2020-12-08 07:26 UTC, merged

2020-12-08 07:31 UTC, PrasadMulherkar commented
Thanks😀