Affine substitution Cipher - C++
HarshCasper/NeoAlgo pull request #757
Opened 2020-08-24 06:00 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented Affine substitution Cipher in C++.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-24 07:46 UTC, iamrajiv requested changes
@SangeetaMishra I would also like to suggest of adding affine functions used in the program in the code comments and also try to make it more informative like clarifying why space is used int `if(message[i]!=' ')` one reason maybe like `to avoid spaces to be encrypted or decrypted`

2020-08-24 07:46 UTC, iamrajiv commented on C-Plus-Plus/cryptography/Affine_substitution_Cipher.cpp
> +            cipher += (char)((a * (message[i] - 'A') + b) % 26 + 'A');
@SangeetaMishra make a comment here i.e. ` to make it in range of ASCII alphabet addition of "A" is done`

2020-08-24 07:46 UTC, iamrajiv commented on C-Plus-Plus/cryptography/Affine_substitution_Cipher.cpp
> +            message += (char)(a_inv * (cipher[i] + 'A' - b) % 26 + 'A');
@SangeetaMishra make the same comment here too

2020-08-24 08:50 UTC, atarax665 requested changes

2020-08-24 08:50 UTC, atarax665 commented on C-Plus-Plus/cryptography/Affine_substitution_Cipher.cpp
> +    //use only uppercase characters (you can modift the code for lowercase characters)
```suggestion
    //use only uppercase characters (you can modify the code for lowercase characters)
```

2020-08-24 09:33 UTC, iamrajiv approved these changes

2020-08-24 14:31 UTC, atarax665 approved these changes
Great! :+1:

2020-08-25 15:30 UTC, siddharth25pandey approved these changes
@SangeetaMishra Good to go
Able to merge.
Thanks!

2020-08-25 15:30 UTC, merged