Added CPP Code for merging K Sorted List
HarshCasper/NeoAlgo pull request #7574
Opened 2021-10-06 14:44 UTC by JayantGoel001

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#7573 )

2021-10-06 14:45 UTC, JayantGoel001 commented
@iamrajiv please review my pr and consider merging it and please add hacktoberfest label.
Thank You.

2021-10-06 17:13 UTC, iamrajiv requested changes
@JayantGoel001 Please document the code. Also, add sample input-output.

2021-10-07 00:53 UTC, JayantGoel001 commented
> @JayantGoel001 Please document the code. Also, add sample input-output.

Done.

2021-10-07 07:59 UTC, iamrajiv approved these changes

2021-10-07 07:59 UTC, merged