Ajay0511
HarshCasper/NeoAlgo pull request #787
Opened 2020-08-25 09:26 UTC by Ajay0511

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-28 12:49 UTC, plazzy99 approved these changes
update readme file

2020-08-28 13:21 UTC, SKAUL05 approved these changes

2020-08-29 06:06 UTC, siddharth25pandey requested changes

2020-08-29 06:06 UTC, siddharth25pandey commented on Python/sort/pancakesorting.py
> +user_input = input("Enter input numers separated by a comma\n").strip()
Remove grammatical mistake

2020-08-29 06:25 UTC, Ajay0511 commented
@siddharth25pandey Sir i have corrected the grammatical errors ,please review .

2020-08-29 09:36 UTC, siddharth25pandey approved these changes
@Ajay0511 Good to go
Able to merge.
Thanks!

2020-08-29 09:37 UTC, merged

2020-08-29 09:37 UTC, siddharth25pandey commented
@all-contributors please add @Ajay0511 for his code.