Added time and space complexity
HarshCasper/NeoAlgo pull request #821
Opened 2020-08-27 09:57 UTC by avinashkranjan

#### PR --> #657
### fixes #648

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Heap Sort Implementation
-Heapsort is a comparison based sorting technique based on a Binary Heap data structure. It is similar to selection sort where we first find the maximum element and place the maximum element at the end. We repeat the same process for the remaining element.

- Python

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2020-08-28 02:24 UTC, SKAUL05 requested changes

2020-08-28 02:24 UTC, SKAUL05 commented on Python/sort/Heap_sort.py
> +        for i in range(int(input("Enter elements to be sorted : ")))]
index in place of i

2020-08-28 04:09 UTC, avinashkranjan commented on Python/sort/Heap_sort.py
> +        for i in range(int(input("Enter elements to be sorted : ")))]
Done

2020-08-31 13:12 UTC, atarax665 approved these changes
LGTM :100:

2020-09-01 01:33 UTC, iamrajiv approved these changes

2020-09-07 09:00 UTC, avinashkranjan commented
@HarshCasper .. Take a Look here too..

2020-09-08 10:04 UTC, iamrajiv approved these changes

2020-09-11 12:24 UTC, SKAUL05 approved these changes

2020-09-11 18:36 UTC, merged

2020-09-11 18:37 UTC, iamrajiv commented
@all-contributors please add @avinashkranjan for code