Bubble sort algorithm optimized
HarshCasper/NeoAlgo pull request #822
Opened 2020-08-27 10:39 UTC by anubhvshrma18

Optimized Bubble Sort Algorithm
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes 

### Description

I optimized the solution of bubble sort algorithm. Added a integer which will check if swapping occurs or not. If swapping occurs then its value is updated , if not then  it will come out of loop and sorted array will be printed. This helped in reducing the time complexity in best case.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#436

2020-08-27 11:49 UTC, anubhvshrma18 commented
Please review @Kajol-Kumari @siddharth25pandey @SKAUL05 @plazzy99

2020-08-28 13:16 UTC, plazzy99 approved these changes
Code looks good to me

2020-08-28 15:03 UTC, iamrajiv requested changes
@anubhvshrma18 add description about Bubble Sort. Also, add sample input-output, space and time complexity of program in multiline comments something like this
```
 /*
...
*/ 
```

2020-08-28 15:18 UTC, iamrajiv requested changes

2020-08-28 15:18 UTC, iamrajiv commented on C-Plus-Plus/sort/Bubble_Sort.cpp
> +    for (int j = 0; j < n - 1; j++)
@anubhvshrma18 you can use this `for (int j = 0; j < n - 1 - i; j++)` to avoid checking the sorted part again.

2020-08-28 15:18 UTC, iamrajiv commented on C-Plus-Plus/sort/Bubble_Sort.cpp
> +    int sorted = 0; // declaring a sorted variable which will check if array is already sorted or not
@anubhvshrma18 udpate `int sorted = 0;` to `bool sorted = true;` because `bool` takes 1 byte of memory whereas `int` takes 4 bytes.

2020-08-28 16:46 UTC, anubhvshrma18 commented
> @anubhvshrma18 add description about Bubble Sort. Also, add sample input-output, space and time complexity of program in multiline comments something like this
> 
> ```
>  /*
> ...
> */ 
> ```
Sir i am just clarifying that i need to add description in the above template and comments in the code ? And the sample input output should be in the above template or in the code or in both?

2020-08-28 18:17 UTC, iamrajiv commented
> > @anubhvshrma18 add description about Bubble Sort. Also, add sample input-output, space and time complexity of program in multiline comments something like this
> > ```
> >  /*
> > ...
> > */ 
> > ```
> 
> Sir i am just clarifying that i need to add description in the above template and comments in the code ? And the sample input output should be in the above template or in the code or in both?

@anubhvshrma18 description of the program should at start and sample input-output, time and space complexity should be at the end of the program. All these things should be in multiline comments.

2020-08-28 19:27 UTC, iamrajiv commented
@anubhvshrma18 please remove unnecessary files

2020-08-28 19:29 UTC, anubhvshrma18 commented
i dont know how these have been added. Please tell me how to remove them

2020-08-28 19:40 UTC, anubhvshrma18 commented
@iamrajiv should i close these pr because i dont know how to remove these unnecessary commits

2020-08-28 19:52 UTC, iamrajiv commented
@anubhvshrma18 This is happening because you have merged the latest commit from `TesseractCoding:master` to `anubhvshrma18:anubhvshrma18-bubblesort`. Ok you can make another PR but do learn all these by the way you can also resolve this issue using this https://www.atlassian.com/git/tutorials/rewriting-history

2020-08-28 20:56 UTC, anubhvshrma18 commented
i am not understanding how to use git revert?Can you please tell which command i need to remove those commits?

2020-08-30 07:38 UTC, anubhvshrma18 commented
@iamrajiv can you please check it now?

2020-09-01 20:04 UTC, anubhvshrma18 commented
@iamrajiv @Kajol-Kumari pls review

2020-09-01 20:20 UTC, iamrajiv approved these changes

2020-09-03 13:06 UTC, atarax665 approved these changes

2020-09-03 13:06 UTC, merged