Tower of Hanoi Algorithm - C
HarshCasper/NeoAlgo pull request #842
Opened 2020-08-28 13:32 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-08-29 06:18 UTC, siddharth25pandey requested changes

2020-08-29 06:18 UTC, siddharth25pandey commented on C/other/Tower_Of_Hanoi.c
> +    int n;
Better to display message what is n for user

2020-08-29 10:32 UTC, siddharth25pandey requested changes

2020-08-29 10:32 UTC, siddharth25pandey commented on C/other/Tower_Of_Hanoi.c
> +    int n;
Please display message before & after of n.

2020-08-30 00:46 UTC, iamrajiv requested changes
@SangeetaMishra Add space and time complexity. Also, add a little bit description of the Tower of Hanoi problem and mention that the recursive method is used in this program.

2020-08-30 00:46 UTC, iamrajiv commented on C/other/Tower_Of_Hanoi.c
> +void TowerOfHanoi(int n,int a,int b,int c){
@SangeetaMishra this code can be shorten using this
```
void TowerOfHanoi(int n, int a, int b, int c)
{
    if (n != 0)
    {
        TowerOfHanoi(n - 1, a, c, b);
        printf("%d -> %d\n", a, b);
        TowerOfHanoi(n - 1, c, b, a);
    }
}
```

2020-08-30 01:51 UTC, Abhijit2505 requested changes
Please make the required changes.

2020-08-30 01:51 UTC, Abhijit2505 commented on C/other/Tower_Of_Hanoi.c
> +    int n;
Change the variable name n to something good, like number_of_discs or something like that.
It's necessary for a code to speak itself.

2020-08-30 18:26 UTC, siddharth25pandey approved these changes
@SangeetaMishra LGTM
Able to merge
Thanks!

2020-08-30 19:39 UTC, iamrajiv approved these changes

2020-09-01 10:31 UTC, SangeetaMishra commented
@siddharth25pandey  @iamrajiv  Could you please approve the pull request as I have to make other pull requests?

2020-09-01 10:35 UTC, iamrajiv approved these changes

2020-09-01 11:16 UTC, atarax665 approved these changes

2020-09-01 11:16 UTC, merged