Longest Palindromic Substring C++
HarshCasper/NeoAlgo pull request #844
Opened 2020-08-28 16:25 UTC by devanshiv123

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Efficient program for Longest Palindromic Substring added.

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#632

2020-08-31 04:49 UTC, siddharth25pandey requested changes

2020-08-31 04:49 UTC, siddharth25pandey commented on C-Plus-Plus/cp/LongestPalindromicSubstring.cpp
> +	cin>>str;
Display suitable message before taking input

2020-08-31 04:49 UTC, siddharth25pandey commented on C-Plus-Plus/cp/LongestPalindromicSubstring.cpp
> +	cout<<LongestPalindrome<<endl;
Along with this output, add some messages

2020-08-31 13:18 UTC, plazzy99 requested changes
Do the changes suggested

2020-08-31 17:56 UTC, devanshiv123 commented
@siddharth25pandey @plazzy99 Please review the PR again. I have done the changes.

2020-09-01 05:44 UTC, plazzy99 approved these changes
LGTM 👍

2020-09-12 05:17 UTC, HarshCasper commented
@devanshiv123 Please resolve the Merge Conflict before I merge it

2020-09-12 07:08 UTC, devanshiv123 commented
> @devanshiv123 Please resolve the Merge Conflict before I merge it

@HarshCasper Resolved conflicts

2020-10-20 15:45 UTC, atarax665 commented
@devanshiv123 Resolve the merge conflict ASAP.

2020-12-08 07:26 UTC, HarshCasper commented
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

2020-12-08 07:26 UTC, closed without merging