CoinChange
HarshCasper/NeoAlgo pull request #848
Opened 2020-08-29 04:51 UTC by Alifbhanvadiya14

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Coin Change problem

### Checklist

- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
- [✓] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Coin Change problem was not implemented. So I Implemented in python.

2020-08-31 04:40 UTC, Alifbhanvadiya14 commented
@siddharth25pandey please review my pr

2020-08-31 04:44 UTC, siddharth25pandey commented on Python/dp/CoinChange.py
> +
Display message regarding this

2020-08-31 04:46 UTC, siddharth25pandey requested changes

2020-08-31 04:46 UTC, siddharth25pandey commented on Python/dp/CoinChange.py
> +
Before & After taking input display suitable messages

2020-08-31 04:46 UTC, siddharth25pandey commented on Python/dp/CoinChange.py
> +
Add Sample Input & Output

2020-08-31 04:46 UTC, siddharth25pandey commented on Python/dp/CoinChange.py
> +''' Minimum no of coins required'''
Write a brief description of  Problem Statement

2020-08-31 05:16 UTC, Alifbhanvadiya14 commented
@siddharth25pandey  Please check the changes.

2020-08-31 06:23 UTC, siddharth25pandey approved these changes
@Alifbhanvadiya14 Looks fine to me
Able to merge
Thanks!

2020-08-31 13:09 UTC, atarax665 reviewed
Update README.md, the code looks fine. :+1:

2020-09-01 05:32 UTC, Alifbhanvadiya14 commented
Done

2020-09-02 13:09 UTC, atarax665 reviewed
Update README.md file to link your contribution. You can checkout other PRs for reference. Don't forget to rebase your branch to avoid merge conflict.

2020-09-02 13:09 UTC, atarax665 commented on Python/dp/CoinChange.py
> +
@Alifbhanvadiya14 Add sample input/output.

2020-09-03 11:18 UTC, Alifbhanvadiya14 commented
@atarax665  Could please check it

2020-09-03 11:21 UTC, Alifbhanvadiya14 commented
@atarax665  Please check it

2020-09-03 11:27 UTC, Alifbhanvadiya14 commented
Check the last commit

2020-09-03 13:03 UTC, atarax665 requested changes

2020-09-03 13:03 UTC, atarax665 commented on Python/dp/CoinChange.py
> +''' Sample input
Add sample input and output at the end of the program. Refer #863 for reference.

2020-09-03 13:03 UTC, atarax665 commented on Python/dp/README.md
> -a
No need to make changes to this file. Revert the changes.

2020-09-03 14:19 UTC, Alifbhanvadiya14 commented
@atarax665 Now check it. Is it proper ?

2020-09-07 01:44 UTC, Abhijit2505 approved these changes
The code is looking good.

2020-09-07 14:00 UTC, Alifbhanvadiya14 commented
@atarax665  please review it now

2020-09-12 07:12 UTC, Alifbhanvadiya14 commented
@atarax665  review it

2020-09-14 14:59 UTC, merged