Completed max and min heap Implementation
HarshCasper/NeoAlgo pull request #879
Opened 2020-09-01 08:00 UTC by bagladivyang03

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-09-01 08:01 UTC, bagladivyang03 commented
@Kajol-Kumari @siddharth25pandey @atarax665 @Abhijit2505 anyone of u could u pls review and merge it :)

2020-09-03 05:56 UTC, bagladivyang03 commented
Any one pls review and merge asap @siddharth25pandey @HarshCasper @SKAUL05 @Kajol-Kumari @Abhijit2505

2020-09-04 18:03 UTC, Kajol-Kumari approved these changes
Codewise LGTM :+1: Maybe you can improve little bit of indentation and add more comment to this code to make it better.

2020-09-05 05:39 UTC, siddharth25pandey requested changes
@bagladivyang03 Do the required changes as suggested

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +#define max 20
Don't define macros

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +#include <iostream>
Use single header **bits/stdc++.h**

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
Define the array here itself or use vector for Dynamic memory allocation

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +    int arr[max+1];
Remove this

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        for(int i =0;i< n+1;i++){
Use **memset** for declaring the array to a specific value

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +    }
Remove all this

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +            h.max_heap();
Display successful message after each operation performed for better User friendly interface.

2020-09-05 05:39 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +
remove the unnecessary break lines

2020-09-05 06:59 UTC, bagladivyang03 commented
@siddharth25pandey  review again asap pls :)

2020-09-05 07:05 UTC, siddharth25pandey requested changes

2020-09-05 07:05 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +    int arr[1000];
Don't take fixed values. Define the array after declaring n, like **a[n]**
Or better use vector for the same

2020-09-05 07:05 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        cin>>n;
After this declare array **a[n]**

2020-09-05 07:09 UTC, bagladivyang03 commented
@siddharth25pandey is it fine now ?

2020-09-05 07:12 UTC, siddharth25pandey requested changes

2020-09-05 07:12 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +    int arr[];
Remove from here

2020-09-05 07:12 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
here itself declare the array as **int a[n]**

2020-09-05 07:14 UTC, bagladivyang03 commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
I already tried that It is showing error while running no arr defined something like that :(

2020-09-05 07:15 UTC, bagladivyang03 commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
So it is correct or not ?

2020-09-05 07:23 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
@bagladivyang03 You can define a static array like this,
After taking values of n, you can do like this,
* *int a[n]** or int *a=(int*)malloc(n*sizeof(int))
* OR you can create a **vector**
**In all these three cases, no error will occur.

2020-09-05 07:25 UTC, bagladivyang03 commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
![image](https://user-images.githubusercontent.com/57760543/92300252-10c95c80-ef77-11ea-8c18-10dd59770708.png)
see this i tried

2020-09-05 07:28 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
@bagladivyang03 Because you have create the class for this. Hence it is not declared globally.
Okay then leave it same as previous

2020-09-05 07:29 UTC, bagladivyang03 commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
yeah i have used the class so is it fine can u approve this ?

2020-09-05 07:30 UTC, siddharth25pandey approved these changes

2020-09-05 07:30 UTC, siddharth25pandey commented on C-Plus-Plus/ds/max_min_heap.cpp
> +        arr[n+1];
@bagladivyang03 Done

2020-09-05 07:31 UTC, bagladivyang03 commented
@atarax665 could u pls do and merge it asap :)

2020-09-05 17:52 UTC, atarax665 approved these changes

2020-09-05 17:52 UTC, merged