C Program to print  m*n matrix in spiral order.
HarshCasper/NeoAlgo pull request #881
Opened 2020-09-01 09:03 UTC by narayan2111

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given a matrix of m x n elements (m rows, n columns), return all elements of the matrix in spiral order.

Sample case 1:

	Input:

	Enter Rows:2
	Enter Column: 2
	1
	2
	3
	4

	Output:

	Entered Matrix:
	1 2 
	3 4

	Spiral Order of the Matrix: 1 2 4 3

Sample Case 2:

	Input:

	Enter Rows:2
	Enter Column: 2
	0
	0
	0
	0

	Output:

	Null Matrix

Time Complexity: O(ROW*COLUMN)
Space Complexity:O(1).

### Checklist

- [Y ] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#792 
![ProgramOutput](https://user-images.githubusercontent.com/66173390/91830168-0bf76680-ec60-11ea-9627-961e5c2cf17d.jpg)

2020-09-01 09:05 UTC, narayan2111 commented
Kindly Review this PR. @Abhijit2505 @plazzy99 @iamrajiv @Kajol-Kumari

2020-09-02 11:41 UTC, plazzy99 approved these changes
Code works fine for all test case 👍 
Able to merge

2020-09-02 11:58 UTC, iamrajiv approved these changes

2020-09-02 13:02 UTC, atarax665 requested changes
Code looks good. Do the suggested changes in readme ASAP so that I can merge this PR.

2020-09-02 13:02 UTC, atarax665 commented on C/README.md
> +
You only need to add your program's hyperlink in the README.md file. Check out other PRs for reference.

2020-09-02 16:34 UTC, narayan2111 commented
> Code looks good. Do the suggested changes in readme ASAP so that I can merge this PR.

How will I do that  sir? 
I mean it works fine and i also updated the readme file and also added link of the code.

2020-09-06 10:45 UTC, narayan2111 commented
Kindly review this PR, it's pending from 4 days @atarax665

2020-09-07 01:42 UTC, Abhijit2505 approved these changes
Code looks good, just make the ReadMe changes asked before.

2020-09-07 04:52 UTC, merged