First Missing Positive Number - C
HarshCasper/NeoAlgo pull request #882
Opened 2020-09-01 11:26 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

First Missing Positive Number in C

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#855

2020-09-01 14:47 UTC, iamrajiv requested changes
@SangeetaMishra move this program to `cp` section

2020-09-03 11:30 UTC, Abhijit2505 requested changes
Small changes required, other than that, It's nice

2020-09-03 11:30 UTC, Abhijit2505 commented on C/cp/first_missing_positive_integer.c
> +    for (int i = 1; i <= n; ++i)
Try dynamic memory allocation in C for array.

2020-09-03 11:30 UTC, Abhijit2505 commented on C/cp/first_missing_positive_integer.c
> +        while (a[x] != x) {
Give good names to the variables

2020-09-04 09:46 UTC, iamrajiv approved these changes

2020-09-07 01:38 UTC, Abhijit2505 approved these changes

2020-09-07 01:40 UTC, Abhijit2505 commented
@SangeetaMishra , as you can see there is a merge conflict. Pull from the master repo to your forked repo and you are good to go.
Also, remember the golden rule given by @HarshCasper - `"git pull origin a day, keeps merge conflicts away"`

2020-09-07 12:23 UTC, atarax665 requested changes

2020-09-07 12:23 UTC, atarax665 commented on C/README.md
> +- [First Missing Positive Integer](other/first_missing_positive_integer.c)
```suggestion

```

2020-09-07 15:03 UTC, SangeetaMishra commented
@atarax665  Can you please review the PR.

2020-09-08 03:11 UTC, atarax665 approved these changes

2020-09-08 03:11 UTC, merged