Matrixsorting issue825
HarshCasper/NeoAlgo pull request #888
Opened 2020-09-02 06:00 UTC by narayan2111

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Matrix sorting aims to sort the elements of the given matrix without affecting the matrix structure.
The algorithm takes as input a 2D array of elements and sorts it in the desired order. The elements are present in the desired order once the algorithm stops.

### Checklist

- [Y ] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#825 
![ProgramOutput](https://user-images.githubusercontent.com/66173390/91937514-b8445600-ed0f-11ea-8afb-416e1f4dc44d.jpg)

2020-09-02 06:04 UTC, narayan2111 commented
Kindly review this PR @SKAUL05 @iamrajiv @plazzy99 @atarax665

2020-09-02 11:52 UTC, plazzy99 requested changes
```
Input:
3 2
7 8 9 5 6 4

Sorted Matrix: 
5 7 
6 4 
6 4 
````
test case failed

2020-09-02 11:57 UTC, iamrajiv requested changes
@narayan2111 remove unnecessary line breaks and indentations

2020-09-03 08:32 UTC, narayan2111 commented
I Updated the required changes @plazzy99 

![Output](https://user-images.githubusercontent.com/66173390/92091166-fadc6000-eded-11ea-8d46-f49e1669ffd7.jpg)

2020-09-03 08:32 UTC, narayan2111 commented
> @narayan2111 remove unnecessary line breaks and indentations

Done Sir

2020-09-05 13:47 UTC, plazzy99 commented on C/ds/MatrixSorting.c
> +  3 1 2
place this comment at the rest is fine

2020-09-05 14:03 UTC, narayan2111 commented on C/ds/MatrixSorting.c
> +  3 1 2
where to place this comment

2020-09-05 14:10 UTC, narayan2111 commented on C/ds/MatrixSorting.c
> +  3 1 2
Done Sir.

2020-09-06 17:54 UTC, plazzy99 approved these changes
LGTM 👍

2020-09-07 00:59 UTC, iamrajiv approved these changes

2020-09-08 03:10 UTC, atarax665 requested changes

2020-09-08 03:10 UTC, atarax665 commented on C/README.md
> -- [Spiral Matrix](ds/Spiral_Matrix.c)
No need of deleting existing hyperlinks.

2020-09-08 03:10 UTC, atarax665 commented on C/README.md
> +- [Matrix Sorting ](ds/MatrixSorting.c)
There is no MatrixSorting.c file in ds folder. Remove this line.

2020-09-08 03:10 UTC, atarax665 commented on C/README.md
> +- [Matrix Sort](sort/MatrixSorting.c)
You have added the link of same program twice, remove this line.

2020-09-08 03:10 UTC, atarax665 commented on C/README.md
>  _add list here_
Remove this line too.

2020-09-08 14:39 UTC, narayan2111 commented on C/README.md
>  _add list here_
Done Sir @atarax665

2020-09-10 14:57 UTC, narayan2111 commented on C/README.md
>  _add list here_
kindly review this PR @atarax665

2020-09-10 15:53 UTC, atarax665 approved these changes
I have fixed the README.md file.

2020-09-10 15:55 UTC, merged