Activity selection
HarshCasper/NeoAlgo pull request #891
Opened 2020-09-02 19:19 UTC by NEEHITGOYAL

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description
Added solution of activity selection problem 
with the use of Dynamic Array of pairs in c++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#826

2020-09-02 19:22 UTC, NEEHITGOYAL commented
kindly review and merge this issue as part of hakin codes

2020-09-13 14:22 UTC, NEEHITGOYAL commented
KINDLY CHECK IT @HarshCasper

2020-09-18 07:00 UTC, siddharth25pandey requested changes
Small modifications is required
Else good to go!

2020-09-18 07:00 UTC, siddharth25pandey commented on C-Plus-Plus/cp/Activity_Selection.cpp
> +#include<iostream>
Add single header file
**bits/stdc++**

2020-09-18 18:05 UTC, Kajol-Kumari requested changes
@NEEHITGOYAL please make the following changes:

1. I am seeing many changes in the `readMe.md` file, I am not sure if all these are required for this PR, if not please revert them.

2. Your code indentation seems to be a bit off, can you please fit it?

2020-09-18 18:14 UTC, NEEHITGOYAL commented
@Kajol-Kumari due to so many days there were many pr merging and for resolving conflicts i have to make chages in readme and i still see there are two competitive coding links in readme i don't know who has done that i have made changes from my side and also idented the code you can re review

2020-09-18 19:44 UTC, iamrajiv requested changes
@NEEHITGOYAL I can see so much edit in README file. Just add `- [ActivitySelection](cp/Activity_Selection.cpp)`.

2020-09-19 04:31 UTC, Kajol-Kumari requested changes
@NEEHITGOYAL please use 
```
git fetch
git checkout upstream/master -- path/to/readme.md
```
this will revert all the changes and make the readme same as upstream/master(Here I  am assuming that you have added the original repo as upstream)

After doing this, just add your path file in readme, commit and push the changes.

For reference, do checkout [here](https://stackoverflow.com/questions/3334475/git-how-to-update-checkout-a-single-file-from-remote-origin-master)

2020-09-19 04:36 UTC, NEEHITGOYAL commented
Thankyou @Kajol-Kumari

2020-09-19 18:09 UTC, NEEHITGOYAL commented
i have updated readme same as it is now and added activity selection link and resolved all conflicts @Kajol-Kumari @iamrajiv  please check it and merge it thank you

2020-09-19 20:37 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2020-09-20 07:50 UTC, iamrajiv approved these changes

2020-09-22 08:35 UTC, NEEHITGOYAL commented
@siddharth25pandey @Abhijit2505  kindly merge it

2020-09-22 15:58 UTC, siddharth25pandey approved these changes
@NEEHITGOYAL Good to go!
Able to merge
Thanks!

2020-09-22 15:59 UTC, merged

2020-09-22 15:59 UTC, siddharth25pandey commented
@all-contributors please add @NEEHITGOYAL for his code.