Created  a Contributor's Guideline
HarshCasper/NeoAlgo pull request #899
Opened 2020-09-03 14:23 UTC by Rishikeshrajrxl

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(I have Created a Contributor's Guideline as Per assigned work a few days ago.)
Here I have used images and screenshots for better understanding. This is going to help new geeks who are new to Open Source. 

I have also used Grammarly.
Add Screenshots wherever possible.
Add the basic information about creating Issues, Pull Requests, and Branching.
Mention tutorials related to Git and Github to help them better understand.

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#542 )

2020-09-03 14:34 UTC, Rishikeshrajrxl commented
@siddharth25pandey 
I think this is an important assignment as it was labeled. Because it is very useful for new geeks so, I would like you to review this.

2020-09-06 06:11 UTC, iamrajiv requested changes
@Rishikeshrajrxl format the file using markdown formatter and avoid using a lot of `<br>` there is unnecessary line breaks.

2020-09-06 06:11 UTC, iamrajiv commented on CONTRIBUTING.md
> +# Contributing Guidlines
@Rishikeshrajrxl fix typo mistake it should be `Guidelines`

2020-09-08 06:37 UTC, iamrajiv requested changes
@Rishikeshrajrxl Use Prettier to format the markdowns. You can use this https://prettier.io/playground/

2020-09-12 14:56 UTC, Rishikeshrajrxl commented
@siddharth25pandey 
@iamrajiv 
I have made all the necessary changes. Please do the review.

2020-09-12 19:00 UTC, iamrajiv approved these changes

2020-09-15 03:03 UTC, Rishikeshrajrxl commented
@siddharth25pandey 
please review this.

2020-09-17 06:25 UTC, Rishikeshrajrxl commented
@siddharth25pandey 
@HarshCasper 
guys, please review this. as soon as possible.

2020-09-17 13:28 UTC, merged