finding least postive number python
HarshCasper/NeoAlgo pull request #903
Opened 2020-09-03 19:12 UTC by devanshi-katyal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Added the python solution for finding least positive number.
I am sorry if i am sending the wrong pull request
(Write your answer here.)

### Checklist

- [X ] I've read the contribution guidelines.
- [X ] I've checked the issue list before deciding what to submit.
- [X ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
https://github.com/TesseractCoding/NeoAlgo/issues/855

2020-09-04 05:17 UTC, iamrajiv requested changes
@devanshi-katyal add more description of the program. Add space and time complexity. Move this program to `cp` sections and update the filename with a suitable title.

2020-09-04 14:58 UTC, devanshi-katyal commented
<!--
Thank you for sending the PR! We appreciate you spending the time to work on these changes.

Help us understand your motivation by explaining why you decided to make this change.
You can learn more about contributing to NeoAlgo here: https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md

Happy Contributing!

-->

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
### Description
Added the python solution for finding least positive number.
space complexity:O(1)
time complexity:O(n)
### Checklist

- [X ] I've read the contribution guidelines.
- [X ] I've checked the issue list before deciding what to submit.
- [X ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
https://github.com/TesseractCoding/NeoAlgo/issues/855

2020-09-05 14:50 UTC, devanshi-katyal commented
> @devanshi-katyal add more description of the program. Add space and time complexity. Move this program to `cp` sections and update the filename with a suitable title.

i have made the changes.please check.

2020-09-06 06:00 UTC, iamrajiv requested changes
@devanshi-katyal add the description in  `findingLeastPositiveNumber.py` program and move this program to ` Python/cp` not in ` Python/ds`.

2020-09-06 09:39 UTC, devanshi-katyal commented
made the changes

2020-09-07 01:30 UTC, Abhijit2505 approved these changes
Looking Good To Me

2020-09-07 05:24 UTC, iamrajiv requested changes
@devanshi-katyal Please check the file name its `findingLeastPositiveNumber.py.py` change to `findingLeastPositiveNumber.py`. Update the README. Your code is not following PEP 8 rules. You can check your program here http://pep8online.com/.

2020-09-07 06:44 UTC, devanshi-katyal commented
hi, i made the changes but i am not sure how to update the read me.
please help me with that

2020-09-07 06:52 UTC, iamrajiv commented
@devanshiv123 Update `NeoAlgo/Python/README.md` by adding the program in the list.

2020-09-07 09:09 UTC, devanshi-katyal commented
done! please have a look. i am sorry but you tagged the wrong person in the previous comment.

2020-09-07 10:29 UTC, iamrajiv approved these changes

2020-09-07 12:11 UTC, atarax665 requested changes

2020-09-07 12:11 UTC, atarax665 commented on Python/cp/findingLeastPositiveNumber.py
> +print("the smallest missing number", findpositive(arr, len(arr)))
Add sample input/output in commented form.

2020-09-10 18:12 UTC, devanshi-katyal commented
please merge this pl
thanks

2020-09-14 20:14 UTC, devanshi-katyal commented
Please merge this pull request.

2020-09-15 12:41 UTC, merged

2020-09-15 12:41 UTC, iamrajiv commented
@all-contributors please add @devanshi-katyal for code