Shell Sort in Python
HarshCasper/NeoAlgo pull request #921
Opened 2020-09-05 15:22 UTC by narayan2111

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

It is a generalized version of insertion sort.
In shell sort, elements at a specific interval are sorted.

Sample I/O
	Input:
	
	Enter Size : 5
	Enter Elements: 5 4 3 2 1

	Output:
	Array After Sorting: 1 2 3 4 5

Time Complexity: O(n*2)
Space Complexity: O(1)

### Checklist

- [ Y] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#387 
![ProgramOutput](https://user-images.githubusercontent.com/66173390/92308187-9f5ecd80-efb9-11ea-85aa-75cf68590389.jpg)

2020-09-05 15:24 UTC, narayan2111 commented
Kindle review this PR
@SKAUL05 @iamrajiv @Kajol-Kumari @Abhijit2505

2020-09-06 05:51 UTC, iamrajiv requested changes
@narayan2111 please follow PEP 8 rules to format the code.

2020-09-06 06:37 UTC, narayan2111 commented
> @narayan2111 please follow PEP 8 rules to format the code.



> @narayan2111 please follow PEP 8 rules to format the code.

Done Sir

2020-09-06 06:46 UTC, iamrajiv requested changes
@narayan2111 still it does not follow PEP 8 rules you can check your program here http://pep8online.com/

2020-09-06 07:18 UTC, narayan2111 commented
> @narayan2111 still it does not follow PEP 8 rules you can check your program here http://pep8online.com/

Sir, code works fine there but here it doesn't work fine, now, what should I do to pass this test case?

2020-09-06 14:52 UTC, atarax665 requested changes

2020-09-06 14:52 UTC, atarax665 commented on Python/sort/Shell_Sort.py
> +    print (arr[i])
Add sample input/output in the end in commented form.

2020-09-06 14:52 UTC, atarax665 commented on Python/README.md
> +* [Interpolation Search](search/Interpolation_Search.py)
Revert the changes and just add hyperlink of your program in the redme file.

2020-09-06 18:08 UTC, plazzy99 requested changes

2020-09-06 18:08 UTC, plazzy99 commented on Python/sort/Shell_Sort.py
> +
remove all extra spaces

2020-09-07 11:54 UTC, atarax665 requested changes
The readme file still contains repetitive blocks. Rever to other merged PRs to get a clear idea of what you are supposed to edit.

2020-09-08 14:47 UTC, narayan2111 commented
> The readme file still contains repetitive blocks. Rever to other merged PRs to get a clear idea of what you are supposed to edit.

Updated the readme file @atarax665

2020-09-09 17:58 UTC, plazzy99 commented
remove branch conflict

2020-09-10 04:58 UTC, narayan2111 commented
> remove branch conflict

Resolved

2020-09-10 18:42 UTC, vatsalkesarwani12 approved these changes

2020-09-10 19:43 UTC, iamrajiv approved these changes

2020-09-11 15:04 UTC, narayan2111 commented
Kindly look to this PR @atarax665

2020-09-11 16:27 UTC, atarax665 approved these changes
LGTM :)

2020-09-11 16:29 UTC, merged

2020-09-11 16:29 UTC, narayan2111 commented
> LGTM :)

Kindly merge this PR sir. :)