Code added for Longest Substring without repeating characters in java
HarshCasper/NeoAlgo pull request #926
Opened 2020-09-06 07:12 UTC by raksha009

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

Code added for Longest Substring without repeating characters in java
### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #563

2020-09-10 18:24 UTC, plazzy99 requested changes

2020-09-10 18:24 UTC, plazzy99 commented on Java/cp/LongestSubstring_without_repeating_characters.java
> +        int currlen = 0;
where is the complete code

2020-09-10 18:25 UTC, plazzy99 commented
resolve branch conflict too

2020-09-11 21:51 UTC, raksha009 commented
Hey! I wrote this code on my own. There is no chance of plagiarism. Also, the main is missing because thats how we submit on leetcode. 
I'll main here but please remove plag tag.

2020-09-12 17:47 UTC, plazzy99 approved these changes

2020-09-14 15:07 UTC, merged