Optimized Bubble Sorting
HarshCasper/NeoAlgo pull request #933
Opened 2020-09-07 08:53 UTC by nutanaarohi123

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
#822 
Bubble Sort Algorithm is the sorting algorithm in which each element is compared to its adjacent element 
and if the first element is greater than the second element, then the swapping occurs.
The swapping occurs till the array is sorted. 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#822

2020-09-07 08:55 UTC, nutanaarohi123 commented
Kindly review @Abhijit2505  @HarshCasper @iamrajiv @atarax665

2020-09-08 02:57 UTC, atarax665 requested changes

2020-09-08 02:57 UTC, atarax665 commented on C/README.md
> +- [Bubble Sort](sort/OPtimizBubble_Sort.c)
```suggestion
- [Optimized Bubble Sort](sort/OPtimizBubble_Sort.c)
```

2020-09-08 03:52 UTC, nutanaarohi123 commented on C/README.md
> +- [Bubble Sort](sort/OPtimizBubble_Sort.c)
Updated README .Kindly review @atarax665

2020-09-08 06:49 UTC, iamrajiv approved these changes

2020-09-09 00:33 UTC, closed without merging