Manacher's Algorithm - C++
HarshCasper/NeoAlgo pull request #942
Opened 2020-09-08 08:36 UTC by SangeetaMishra

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#667

2020-09-09 13:39 UTC, SangeetaMishra commented
@iamrajiv @Abhijit2505 @atarax665 Can you please review this PR.

2020-09-09 14:00 UTC, iamrajiv requested changes
@SangeetaMishra Remove whitespace from file name because every character is treated as hexadecimal value and sometimes it gets converted to hexadecimal values for some character. For whitespace, it's hexadecimal value is `20` that's why in `C-Plus-Plus/README.md` the file name is converted to `Manacher's%20Algorithm.cp`.

2020-09-09 14:00 UTC, iamrajiv commented on C-Plus-Plus/search/Manacher's Algorithm.cp
> +#include <bits/stdc++.h>
@SangeetaMishra Add a description of Manacher's Algorithm.

2020-09-09 14:00 UTC, iamrajiv commented on C-Plus-Plus/search/Manacher's Algorithm.cp
> +/*
@SangeetaMishra Add time and space complexity.

2020-09-09 17:57 UTC, iamrajiv approved these changes

2020-09-10 03:16 UTC, atarax665 approved these changes

2020-09-11 18:31 UTC, SangeetaMishra commented
@Abhijit2505  Please review the PR

2020-09-12 17:45 UTC, plazzy99 approved these changes
able to merge

2020-09-12 17:45 UTC, merged