Shell_Sort in CPP #387
HarshCasper/NeoAlgo pull request #944
Opened 2020-09-08 09:17 UTC by aniketsingh98571

Shell Sort is an extended version of Insertion sort. Have a Check.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description
Shell Sort is an extended version of Insertion Sort.
Worst case time complexity = O(n2)
Best case complexity = O(nlog(n)).
Space complexity = O(1).

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Please review my PR @HarshCasper @Kajol-Kumari @plazzy99 @Abhijit2505 @atarax665 
(Write your answer here.)

2020-09-09 17:56 UTC, plazzy99 requested changes
add .cpp file

2020-09-09 18:19 UTC, atarax665 reviewed
There already exist the [ShellSort.cpp](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/sort/ShellSort.cpp) . Though you have been assigned this issue so you can just refactor the existing file.

2020-09-10 04:25 UTC, aniketsingh98571 commented
how to rafactor the file? @atarax665

2020-09-10 14:08 UTC, atarax665 commented
> how to rafactor the file? @atarax665

Okay leave it, I will take care of the existing file from my end. Just update the README file to link this new the new program.

2020-09-10 16:54 UTC, Kajol-Kumari approved these changes
@aniketsingh98571 minor changes required. Functionality is working fine, well formatted and Looks good to me :+1:

2020-09-10 16:54 UTC, Kajol-Kumari commented on C-Plus-Plus/sort/Shellsort.cpp
> +    int sort[size];
Please show a message something like `Enter the array elements` here?

2020-09-11 03:37 UTC, aniketsingh98571 commented
@Kajol-Kumari @plazzy99

2020-09-11 03:38 UTC, aniketsingh98571 commented
@Abhijit2505

2020-09-11 16:28 UTC, atarax665 approved these changes
LGTM :)

2020-09-11 18:09 UTC, plazzy99 approved these changes
able to merge

2020-09-11 18:09 UTC, merged