Double factorial in C++ language
HarshCasper/NeoAlgo pull request #964
Opened 2020-09-09 19:00 UTC by ag278

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

double factorial  of a number n (denoted by n!!) is the product of all the integers from 1 up to n that have the same parity(odd or even) as n.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#930

2020-09-09 19:03 UTC, ag278 commented
@iamrajiv  @Kajol-Kumari @siddharth25pandey @plazzy99  please review this
@iamrajiv I have added both the approaches as you mentioned in the issue.

2020-09-10 04:59 UTC, iamrajiv approved these changes

2020-09-10 13:39 UTC, atarax665 commented on C-Plus-Plus/README.md
> +
```suggestion
```

2020-09-10 13:39 UTC, atarax665 commented on C-Plus-Plus/README.md
> +
```suggestion
```

2020-09-10 13:50 UTC, ag278 commented
@atarax665 I have made the required changes. Please review it

2020-09-11 15:56 UTC, atarax665 requested changes

2020-09-11 15:56 UTC, atarax665 commented on C-Plus-Plus/math/double_factorial.cpp
> +            ans*=i;
```suggestion
            ans *= i;
```

2020-09-11 15:56 UTC, atarax665 commented on C-Plus-Plus/math/double_factorial.cpp
> +
```suggestion
```

2020-09-11 17:37 UTC, ag278 commented
@atarax665 I have made the required changes.Please verify it

2020-09-12 17:29 UTC, atarax665 approved these changes
LGTM :)

2020-09-12 19:38 UTC, ag278 commented
@plazzy99 could you please review my PR

2020-09-13 17:51 UTC, plazzy99 approved these changes

2020-09-13 17:51 UTC, merged