Ag278 remove outermost parentheses
HarshCasper/NeoAlgo pull request #968
Opened 2020-09-10 11:54 UTC by ag278

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Remove outermost parentheses

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#955

2020-09-10 11:57 UTC, ag278 commented
@iamrajiv please have a review at my PR

2020-09-10 13:49 UTC, iamrajiv approved these changes

2020-09-11 09:08 UTC, ag278 commented
@atarax665 @Abhijit2505 could you please review my PR

2020-09-11 16:19 UTC, atarax665 requested changes

2020-09-11 16:19 UTC, atarax665 commented on C/README.md
> +
Remove these unnecessary line breaks.

2020-09-11 16:19 UTC, atarax665 commented on C/README.md
> +- [remove outermost parentheses](other/remove_outermost_parentheses.c)
```suggestion
- [Remove Outermost Parentheses](other/remove_outermost_parentheses.c)
```

2020-09-11 17:29 UTC, ag278 commented
@atarax665  i have made the required changes. Please verify it

2020-09-12 17:47 UTC, atarax665 requested changes

2020-09-12 17:47 UTC, atarax665 commented on C/README.md
> +## Sorting
Sorting heading already exists at line 41. Remove line 87 to 96.

2020-09-12 19:37 UTC, ag278 commented
@atarax665 i have made the required changes. Please verify it

2020-09-14 12:27 UTC, ag278 commented
@atarax665 @Abhijit2505 please review my pr

2020-09-19 20:12 UTC, ag278 commented
@atarax665 @Abhijit2505 @Kajol-Kumari @SKAUL05 please review my PR

2020-09-29 03:30 UTC, merged