Russian Peasant Algorithm in Java
HarshCasper/NeoAlgo pull request #990
Opened 2020-09-12 05:30 UTC by ritvij14

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Russian Peasant multiplication algorithm in Java.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #978 
(Write your answer here.)

2020-09-12 14:23 UTC, ritvij14 commented
@iamrajiv @plazzy99 @Kajol-Kumari @siddharth25pandey please review this.

2020-09-12 19:05 UTC, iamrajiv requested changes

2020-09-12 19:05 UTC, iamrajiv commented on Java/Algorithms/RussianPeasant.java
> +import java.util.*;
@ritvij14 Added description about Russian Peasant Algorithm.

2020-09-12 21:14 UTC, ritvij14 commented on Java/Algorithms/RussianPeasant.java
> +import java.util.*;
@iamrajiv done.

2020-09-13 08:25 UTC, iamrajiv approved these changes

2020-09-13 17:59 UTC, plazzy99 approved these changes

2020-09-15 05:22 UTC, Kajol-Kumari approved these changes
Well formatted and Looks good to Go! :+1:

2020-09-15 06:16 UTC, ritvij14 commented
@iamrajiv sir here also, 3 approvals done, please merge

2020-09-15 13:03 UTC, merged