Completed double factorial issue assigned to me
HarshCasper/NeoAlgo pull request #991
Opened 2020-09-12 06:43 UTC by bagladivyang03

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2020-09-13 08:58 UTC, bagladivyang03 commented
@Kajol-Kumari @Abhijit2505 @SKAUL05 @siddharth25pandey @HarshCasper 
Pls review and merge it asap :)

2020-09-15 05:25 UTC, Kajol-Kumari requested changes
@bagladivyang03 please do the following:
1. Link the related issue in the PR description. 
2. Please provide 1-2 line comment on the top of the file regarding what this code is going to do.

2020-09-15 05:30 UTC, bagladivyang03 commented
@Kajol-Kumari done
Pls review again asap :)

2020-09-15 06:20 UTC, Kajol-Kumari requested changes

2020-09-15 06:20 UTC, Kajol-Kumari commented on C/cp/doublefactorial.c
> +#Double factorial of a non-negative integer n is defined as the product of all the integers from 1 to n that have the same parity (odd or even) as n.
@bagladivyang03 This is not the correct way for commenting in C. Please use multi-line comment here `/* */`

2020-09-15 06:23 UTC, bagladivyang03 commented
@Kajol-Kumari yeah sorry because of using the python i had a habit of that
Now completed in correct way xD

2020-09-15 06:30 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2020-09-15 13:02 UTC, iamrajiv requested changes
@bagladivyang03 What you have added is Iterative Solution please add Recursive Solution too.

2020-09-17 03:30 UTC, bagladivyang03 commented
@iamrajiv added recursive soln too just check once pls :)

2020-09-17 13:33 UTC, iamrajiv requested changes
@bagladivyang03 Format your code using code formatter.

2020-09-17 13:33 UTC, iamrajiv commented on C/cp/doublefactorial.c
> +int doublefactorial(int n){
@bagladivyang03 rename this to `iterative _doublefactorial`

2020-09-17 13:33 UTC, iamrajiv commented on C/cp/doublefactorial.c
> +int recdoublefactorial(int n){
@bagladivyang03 rename this to `recursive _doublefactorial`

2020-09-17 14:27 UTC, bagladivyang03 commented
@iamrajiv pls check now

2020-09-17 14:27 UTC, bagladivyang03 commented
@atarax665 pls do check and merge asap

2020-09-17 14:45 UTC, iamrajiv approved these changes

2020-09-21 17:45 UTC, bagladivyang03 commented
@atarax665 pls could u review

2020-09-21 18:20 UTC, atarax665 requested changes

2020-09-21 18:20 UTC, atarax665 commented on C/README.md
> +
Update Readme.md

2020-09-22 14:12 UTC, bagladivyang03 commented on C/README.md
> +
its showing conflicts could u pls hlp me

2020-09-22 14:14 UTC, bagladivyang03 commented
@atarax665 pls merge now asap :)

2020-09-22 14:14 UTC, bagladivyang03 commented
i have  updated the readme too

2020-09-22 14:18 UTC, merged