Russian Peasant Algorithm
HarshCasper/NeoAlgo pull request #994
Opened 2020-09-12 10:55 UTC by narayan2111

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Russian Peasant algorithm to multiply two long numbers.

### Checklist

- [Y ] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#978

2020-09-12 10:57 UTC, narayan2111 commented
Kindly review this PR @iamrajiv @plazzy99 @Kajol-Kumari @atarax665 @SKAUL05

2020-09-13 17:49 UTC, plazzy99 approved these changes

2020-09-13 18:56 UTC, atarax665 requested changes

2020-09-13 18:56 UTC, atarax665 commented on Python/other/Russian_Peasant_Algorithm.py
> +		number1 = number1 << 1 		 #bitwise left operator
```suggestion
		number1 = number1 << 1 		 #bitwise left shift operator
```

2020-09-13 18:56 UTC, atarax665 commented on Python/other/Russian_Peasant_Algorithm.py
> +		number2 = number2 >> 1 		 #bitwise right operator
```suggestion
		number2 = number2 >> 1 		 #bitwise right shift operator
```

2020-09-13 18:56 UTC, atarax665 commented on Python/other/Russian_Peasant_Algorithm.py
> +# Driver program to test
```suggestion
# Driver code 
```

2020-09-13 18:56 UTC, atarax665 commented on Python/other/Russian_Peasant_Algorithm.py
> +# above function
```suggestion
```

2020-09-14 05:25 UTC, narayan2111 commented on Python/other/Russian_Peasant_Algorithm.py
> +# above function
> 

Updated the code  @atarax665

2020-09-14 05:26 UTC, narayan2111 commented
kindly review this PR @iamrajiv

2020-09-14 07:54 UTC, iamrajiv approved these changes

2020-09-14 11:24 UTC, Kajol-Kumari approved these changes
LGTM :+1:

2020-09-14 11:46 UTC, narayan2111 commented
kindly merge this PR it has 3 reviews @iamrajiv

2020-09-14 11:47 UTC, merged