Vigenere Cipher in Java
HarshCasper/NeoAlgo pull request #995
Opened 2020-09-12 11:45 UTC by parjanyaacoder

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Vigenere Cipher algo added in Java.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Solves #974

2020-09-12 11:46 UTC, parjanyaacoder commented
@iamrajiv @siddharth25pandey @HarshCasper  Please review.

2020-09-14 15:07 UTC, HarshCasper requested changes
Make these changes

2020-09-14 15:07 UTC, HarshCasper commented on Java/cryptography/vigenereCipher.java
> +
Add a proper description of the Code along with Examples for I/O

2020-09-14 15:07 UTC, HarshCasper commented on Java/cryptography/vigenereCipher.java
> +    int indexI= 0,indexJ=0;String s1="";char ch;
Use Meaningful Variable Names

2020-09-14 15:07 UTC, HarshCasper commented on Java/cryptography/vigenereCipher.java
> +        ch=(char)(ch+26);
Format your Code properly

2020-09-14 15:07 UTC, HarshCasper commented on Java/cryptography/vigenereCipher.java
> +   String encrpytedString = encrypt(str.toUpperCase(),key.toUpperCase());
Do proper Indentation

2020-11-21 00:20 UTC, closed without merging