Russian Peasant Algorithm in C++
HarshCasper/NeoAlgo pull request #998
Opened 2020-09-12 16:21 UTC by mahimagoyalx

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code for Russian Peasant Algorithm in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #978

2020-09-12 16:25 UTC, mahimagoyalx commented
@HarshCasper @Kajol-Kumari @iamrajiv @siddharth25pandey Kindly review.

2020-09-12 19:10 UTC, iamrajiv requested changes
@mahimagoyalx Move this program to `other` section. Add time complexity.

2020-09-12 19:10 UTC, iamrajiv commented on C-Plus-Plus/cp/RussianPeasant.cpp
> +// Russian Reasant Algorithm
@mahimagoyalx Add more description about Russian Peasant Algorithm.

2020-09-13 08:29 UTC, iamrajiv approved these changes

2020-09-14 16:37 UTC, mahimagoyalx commented
@plazzy99 @Abhijit2505 Kindly review.

2020-09-15 14:56 UTC, plazzy99 approved these changes

2020-09-15 14:57 UTC, plazzy99 commented
remove merge conflict

2020-09-15 16:07 UTC, mahimagoyalx commented
> remove merge conflict

Done

2020-09-15 16:24 UTC, mahimagoyalx commented
@Kajol-Kumari Kindly review.

2020-09-15 18:57 UTC, atarax665 approved these changes

2020-09-15 18:57 UTC, merged

2020-09-15 20:39 UTC, iamrajiv commented
@all-contributors please add @mahimagoyalx for code